### ISSUE TITLE
Deck Selection / Hidden tracker.

### ISSUE THREAD

**Issue by FenrisWolffe** [Epix37/Hearthstone-Deck-Tracker#1000]
New Laptop today, Windows 8.1 (ugh.)

Decks not being chosen, i.e. Druid, but HDT shows Hunter.
"Hide in menu" hides tracker in game.

Known issues?

**Comment by Epix37** [comment]
I'm not entirely sure what you mean but this: https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/master/README.md#faq

**Comment by FenrisWolffe** [comment]
1. The tracker tries to automatically select the deck you are playing. - It currently does not seem to switch decks if I change class for my next match.

2. Under Options / General, if I select "hide in menu", the whole tracker goes away.

3. I just had a match which didn't show my opponents discards, but I hadn't restarted.
