### ISSUE TITLE
import from web stopped working a few days ago

### ISSUE THREAD

**Issue by Riku241** [Epix37/Hearthstone-Deck-Tracker#1003]
been trying to impoirt anything off of hearthpwn like i ahve in the past and everytime for last few days comes up with Error: couldn't load deck with specified url.  also noticed the site has been pretty dodgy lately and a little slow maybe its their side?

**Comment by Epix37** [comment]
Hm, yea it seems they set up some kind of "ddos protection"? Interesting...

[NetDeck](http://netdeck.n4ru.it/) still works
