### ISSUE TITLE
Turn timer is inaccurate

### ISSUE THREAD

**Issue by NightKev** [Epix37/Hearthstone-Deck-Tracker#1007]
Turns currently last 75s (possibly slightly longer if there are animations still pending), not 90 as the tracker suggests.

**Comment by Epix37** [comment]
The base turn in 75 seconds, yes. To that is added some, so called `SLUSH`, which ranges from 0 to at least 24 seconds depending on the animations playing out (as you correctly stated) and possibly some other factors I am not sure about. It seems to increase as the game goes on. The log does contain this `SLUSH` value (`TURN_TIMER_SLUSH` to be exact) and I did try impementing it at somepoint, but it appeared to not be as straight forward as I had hoped. 

Taking the slush into account is planned eventually. However 90 seconds seems to be "good enough" most of the time, making it not really a priority at the moment.

(if anyone else wants to fix this, feel free)

**Comment by Matter94** [comment]
Can you please fix this to 75 seconds? This is really bugging me when I play.. Or let us choose if we want the timer ascending or descending please

**Comment by Epix37** [comment]
Since `SLUSH_TIME` no longer exists, there is most likely no way to do this accurately. 

v0.13.3: `Added an option to set the timer to 75 seconds` has to be good enough of a solution.
