### ISSUE TITLE
Constructed sorting/last played

### ISSUE THREAD

**Issue by culinko** [Epix37/Hearthstone-Deck-Tracker#1009]
If you sort constructed decks by last played, some of the decks with no matches (even in other play modes) are not sorted correctly. They should be on the bottom after the decks with matches and they should be sorted secondarily by creation date. Thanks for the fix.

![last-played](https://cloud.githubusercontent.com/assets/11700272/7932428/7cde487c-0918-11e5-916d-84c80cf95044.png)

**Comment by culinko** [comment]
I know this is a minor issue, but I noticed that you have more time recently, so maybe you could look at this. The only decks not sorted correctly are the decks without matches.

**Comment by Epix37** [comment]
Fixed :). Deck w/o matches are now just at the very end, instead of using the lastedited time.

**Comment by culinko** [comment]
You da best!

**Comment by culinko** [comment]
Yeah, actually. Could it be possible to have the old behavior on Arena sorting? I just realized I am using sorting by "Last Played" and every time I create a new Arena deck, it gets added to the bottom. I think when I created this issue, I was thinking only about the constructed, hence the title. But then I completely forgot about it. This would help me a ton. Sorry for inconvenience.

**Comment by Epix37** [comment]
I get where you are coming from but the new behaviour is still "correct", even for arena decks.
After creating the arena deck it is automatically activated and after playing with it once it's at the top of the list. Do you really run into the situation where you need to scroll to the bottom to activate your arena deck, that you created but didn't play - and played something else inbetween -  that often?

**Comment by culinko** [comment]
Well, sometimes I just draft the deck and don't play any matches. But now that I think about it, I can edit all the decks from the oldest to newest and sort by "Last Edited". This would solve this problem.

**Comment by Epix37** [comment]
In case you didn't know: you can also shift-click the scrollbar to get right to that point (so just above the down arrow to get to the bottom) or, with a deck selected, press the "End" key.
