### ISSUE TITLE
Firewal Trogen detection

### ISSUE THREAD

**Issue by PossumFlavored** [Epix37/Hearthstone-Deck-Tracker#1013]
I went to download it and my firewall, 360 internet security, detects the files as having a Trojan.

**Comment by Epix37** [comment]
[virustotal of the latest release](https://www.virustotal.com/de/file/ee677172fff8207a372b7c38ca49b76e6cf22b7f7e5414d207009e004bf59d01/analysis/1433272251/)

**Comment by PossumFlavored** [comment]
thanks.
