### ISSUE TITLE
Disable Login Prompt

### ISSUE THREAD

**Issue by tumri** [Epix37/Hearthstone-Deck-Tracker#1014]
I updated to the new version(0.10.2) and was wondering if there was any way to disable the login prompt. It's annoying having the login prompt pop up and ask to confirm that I want to use the app as a "guest" every time. I've tried HearthStats and didn't like it at all but love this tracker app.

**Comment by Epix37** [comment]
Since we want you to actually use hearthstats, there currently is not, no.

Easiest way to get rid of it is just to register/login and not actively use it. 
But maybe you even grow to like it: when synced, rightclick a deck > open hearthstats will easily let you share your decks with anyone.

**Comment by Epix37** [comment]
You know what, nevermind. See #1025.
