### ISSUE TITLE
HDT Crashes related.

### ISSUE THREAD

**Issue by Qn1410** [Epix37/Hearthstone-Deck-Tracker#1017]
Hi.
I really like your program. Hearthstone Deck Tracker is one awesome piece of work. This is why I decided to make an issue report, to support your great work. To the point then. After latest patch, HDT seems to crash, when you win/lose game. For me it happened 3 times and I stopped launching program. Crashes occurred with "-No Deck Tracking" option turn on. Its all fine until you either win or lose the game. On bottom of this issue I'm gonna paste "Crash reports" message created by program. Hope it helps. Keep up the great work.

Best regards, Qn1410.

P.S. Seems like few words of that report are actually in my language (Polish). I hope it wont be a problem for you. I might be wrong but there might be some problem with dividing by 0 problem, somewhere in the code. It's just my wild guess only anyway.
- - -

System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
   w Hearthstone_Deck_Tracker.GameEventHandler.HandleGoldReward(Int32 amount)
   w Hearthstone_Deck_Tracker.HsLogReader.Analyze(String log)
   w Hearthstone_Deck_Tracker.HsLogReader.<ReadFileAsync>d__1.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   w MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

- - -

**Comment by Epix37** [comment]
Should be fixed with v0.10.3. Sorry about that.
