### ISSUE TITLE
Import from Game (Constructed)

### ISSUE THREAD

**Issue by OriginalAlienOne** [Epix37/Hearthstone-Deck-Tracker#1020]
After the last update a few hours ago, I haven't been able to use this function. Every time I try to import, it just goes to the tooltip for how to import. When I click "ok," nothing happens. It's just a cycle of the same thing. I'll go to main menu, click on "My Collection," click on the deck I want to import, click "Done," and go back to main menu. From there, I'll click on "Import from game: Constructed (Beta)", and it will just give me the tooltip and the option to click ok, at which point nothing happens again.

Anyone else experiencing this issue?

**Comment by Ikissubetter** [comment]
Same for me. Just a second he tried to import (without doing so), next second always the popup. Fresh install, tried the HDS first time.

**Comment by Epix37** [comment]
Seems to be fine for me. Try redoing the setup process: `options > tracker > importing > set up constructed importing`.

**Comment by OriginalAlienOne** [comment]
It seems to be fine now after a major windows update (I'm on Windows 10 Insider) and a restart to the computer.
