### ISSUE TITLE
Bugs after updating to 10.3

### ISSUE THREAD

**Issue by askarmuk** [Epix37/Hearthstone-Deck-Tracker#1021]
Updated to 10.3 and got these bugs:
- overlay can be seen in Windows
- overlay can be seen after match has ended
- I can not minimize HDT into tray

![bandicam 2015-06-03 19-49-03-858](https://cloud.githubusercontent.com/assets/8628595/7963055/3622aa1e-0a2a-11e5-9c5b-21ac8388c183.jpg)
![bandicam 2015-06-03 19-33-26-725](https://cloud.githubusercontent.com/assets/8628595/7963056/3625ede6-0a2a-11e5-8681-e4e8d10efad7.jpg)

**Comment by Epix37** [comment]
Try re-enabling the options for all of those. (options > overlay > general for 1 and 2, options > tracker > settings for 3)

**Comment by askarmuk** [comment]
Yes looks like changing settings fixed it. Strange that setting were reseted.

**Comment by Epix37** [comment]
Yea, strange indeed.
