### ISSUE TITLE
Norton 360 won't allow the new update to be installed

### ISSUE THREAD

**Issue by cmeagher10** [Epix37/Hearthstone-Deck-Tracker#1023]
I uploaded the new Deck Tracker release this morning and Norton 360 flagged it as a high risk
and removed the executables. It didn't like finding SONAR.Heuristic.120.

This is unfortunate as the Deck Tracker was very helpful. But frankly, I trust Norton more than
an online software developer. So unless you can get this to pass the Norton virus check, 
Deck Tracker will stay inactive.

**Comment by Epix37** [comment]
[Totalvirus for the v0.10.3](https://www.virustotal.com/de/file/2ceca51741ff61035f95f9bc5d0c1f1b422f288db99dbcfd4dbc1579e24ac9ca/analysis/)
