### ISSUE TITLE
Hearthstone Detection

### ISSUE THREAD

**Issue by denali1** [Epix37/Hearthstone-Deck-Tracker#1024]
Any chance of adding a quick check to see if Hearthstone is running before HDT throws up the overlays?  Currently, it seems to check to see if DirectX is running, so any game will end up with the overlays.

**Comment by Epix37** [comment]
It checks for a uinity window by default to work with asian version of hearthstone (different window names). You can turn off "advanced window search" in `options > tracker > settings` to make it look for the window by name.
