### ISSUE TITLE
Hearthstats opt-out

### ISSUE THREAD

**Issue by labrys** [Epix37/Hearthstone-Deck-Tracker#1025]
No option to opt-out of Hearthstats.  Selecting Continue as guest does not stop pop up appearing every time HDT is started.

**Comment by Epix37** [comment]
Added an option now, will be possible with the next update (shouldn't be too long).

**Comment by Epix37** [comment]
Something you can do to disable it right now: [download this file](http://en.file-upload.net/download-10663783/hearthstatsauth.html) and place it in "%AppData%/HearthstoneDeckTracker". It's an empty authentication file that should let you bypass the login screen.

**Comment by tumri** [comment]
Thanks for this. Keep up the great work! This tracker is one of the best 3rd-party gaming tools I've seen since SimCraft.

**Comment by labrys** [comment]
Thanks a ton! And love the quick response
