### ISSUE TITLE
I can't open the file

### ISSUE THREAD

**Issue by Burritosniper** [Epix37/Hearthstone-Deck-Tracker#1028]
I have Windows 8, and i keep trying to open the file after unzipping but it will not open.

**Comment by Epix37** [comment]
a) make sure you downloaded the correct file [Hearthstone.Deck.Tracker-v0.10.3.zip](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/download/v0.10.3/Hearthstone.Deck.Tracker-v0.10.3.zip)  
b) make sure .NET Framework 4.5 is installed

**Comment by Burritosniper** [comment]
Where is the .Net framework 4.5?

**Comment by Burritosniper** [comment]
Because i did get the right file, it just says it can't open in Windows

**Comment by Epix37** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=30653

**Comment by Couldosh** [comment]
I have this problem too.
I get the right file and  .NET Framework 4.5 but it doesn't work :( 
Help ! :p

**Comment by Epix37** [comment]
What exactly is the error message?

**Comment by Couldosh** [comment]
Something like "HDT stopped worked" (I'm French so I don't know what it is exactly) :/

**Comment by Epix37** [comment]
Try **re**installing .NET

**Comment by Couldosh** [comment]
Do you know how? In the settings?
