### ISSUE TITLE
Update with Secret Checking

### ISSUE THREAD

**Issue by Anusien** [Epix37/Hearthstone-Deck-Tracker#1029]
When the opponent plays a secret, a dialog opens showing which secrets it could be. This list ought to update when secrets could have triggered but didn't ("secret checking").

**Comment by Epix37** [comment]
That is not yet implemented. Secrets currently only automatually gray out if another secret triggered. (#548)

You can manually click the secrets if you enable `options > overlay > interactivity`

**Comment by Anusien** [comment]
Was opening it to be a feature request.

**Comment by Epix37** [comment]
Oh I misunderstood then, sorry. The linked issue still applies though :).
