### ISSUE TITLE
Doesn't Work While In a Game

### ISSUE THREAD

**Issue by Metapalms** [Epix37/Hearthstone-Deck-Tracker#1033]
I I just got this program, and I am on the latest release, so it may not be a bug at all, and just don't know how to work it. However, I got my decks on here and everything, but when I am in a game it does not do any of the things it is suppose to do. All it does is show me my deck which is ultimately better than nothing but I would like to have the rest of the features to.
           Also I tried the start game keys, and it still does not work.

**Comment by Epix37** [comment]
Try restarting HDT and Hearthstone. If that does not help, [see here](https://github.com/Epix37/Hearthstone-Deck-Tracker#faq)
