### ISSUE TITLE
Advanced opponent card tracking using game logic

### ISSUE THREAD

**Issue by dvide** [Epix37/Hearthstone-Deck-Tracker#1034]
_N.b. This is not so much a request but a theoretical enhancement that would take a lot of work to actually design and implement. It would also be continual work as when new cards get introduced to the game, new deductions would need to be added and maintained. Just want to put it out there as an idea._

Throughout the course of a game, there are various ways we can learn details about our opponent's cards in hand. We can manually keep track of the cards that we know for sure are minions or spells, their mana costs, and other important characteristics of these cards, such as battlecries or their tribes. Using these details, we can often deduce useful information with knowledge of the game's logic. HDT could do this automatically and present the information to the player on the card markings, and on tooltips that show up when the player mouses over the card markings. The following page gives some examples of what might be possible.

Sometimes we can learn a lot about our opponent's cards, even though we don't know exactly what the cards are. Gazlowe, for example, generates a random mech minion when its effect procs. We could keep track of these generated cards in our opponent's hand and show that they are mech minions on a tooltip. The opponent may not play these mechs for many turns. Much later in the game, the opponent may then play a Mechwarper, and it would be useful to see just how many mechs there are in the opponent's hand that we know of. At this point, the card markings and the tooltips could show that they all cost (-1) mana, using knowledge of the game's logic. I think this information should be shown on the card marking too so that it is visible at a glance. Since we know that they are also minions, we can deduce that a Mana Wraith on the board will increase their cost by (+1) mana.

Similarly, if our opponent plays an Emperor Thaurissan and it survives a turn, we know that all of the remaining cards in our opponent's hand cost (-1) mana. Any cards drawn after this effect triggered will not have their mana cost reduced. This information could be tracked for the player and displayed on the card markings and tooltips. We may not know exactly what the cards are, but it could be useful to know that they cost less mana for our opponent. For example, much later in the game we may be wondering whether our opponent has any reduced mana cards left from Thaurissan. If the opponent has played all of them already, then we may not have to play around certain combos that would otherwise be possible, and so perhaps we could play an aggressive minion rather than a taunt.

Keeping track of combinations of these effects would also be useful. If your opponent plays Emperor Thaurissan when their hand is half full of mech minions generated from Gazlowe, then we can show that these are both mech minions and that they all cost (-1) mana. We don't know anything about the other cards that were in our opponent's hand when Thaurissan triggered, other than that they all cost (-1). Now when the opponent plays a Mechwarper, we can now show that the mechs still in hand cost (-2) due to the combination of these effects.

Sometimes we do know exactly what card the opponent has. The most obvious ways this can happen is with bounce effects like Youthful Brewmaster or Sap. Imagine your opponent plays a Youthful Brewmaster on an Antique Healbot. We could keep track of this card and its characteristics. When the player mouses over the marking for that card in hand, it could show a tooltip showing exactly what card it is, how much it costs, and that it is a mech minion. If, much later in the game, the opponent plays a Mechwarper, then we could then use game logic to determine that this minion costs (4) mana to play instead of (5). Note that we don't have to show a relative mana change this time, as we can just show the exact mana cost of the card. Our opponent could also get a Nerub'ar Weblord from a Piloted Shredder deathrattle. Since we know that Antique Healbot has a battlecry, we can deduce that it costs (7) mana rather than (5). Similarly, a Yeti bounced back to the hand with Freezing Trap or Shadowstep would show its mana cost changed to (6) or (2) respectively.

Sometimes we know exactly what the mana cost of the card is, but not what the card is itself. If the opponent plays Holy Wrath, for example, and it hits for 5 damage (assuming no spell damage), then we know the card  must cost (5) mana. We don't know anything else about it, but we could keep track of this information. If Emperor Thaurissan triggers with this card in hand, then we know that the card now costs (4). If, however, the card drawn from Holy Wrath hits for 20 damage, then we can know for sure the card is a Molten Giant, because that's the only card in the game so far that costs (20). This kind of logic would have to be removed in the future, if any more cards that cost 20 are ever introduced.

It may also be useful to keep track of cards that we know for sure are spells. Suppose that the opponent plays a Gnomish Experimenter, and we see that it doesn't transform the card into a 1/1 chicken minion. We now know for certain that this card cannot be a minion. On the tooltip, we could show that to the player by having the minion text crossed out with strikethrough. This means that it must either be a weapon or a spell. If, however, the opponent is playing a class which has no weapons, then we can deduce that it must be a spell. On the tooltip, we could simply show that the card is a spell. We don't know its mana cost, or anything else about it. But if the opponent plays a Sorcerer's Apprentice, or if one drops from a Piloted Shredder, the tooltip could now show that it costs (-1) mana. Similarly, Nefarian generates two cards that we know for sure are spells.

Speaking of Nefarian, there are some interesting deductions that can be made with dragon cards. For example, if the opponent plays a card like Blackwing Technician, and we see that its effect triggers, this means that the opponent must have at least one dragon somewhere in their hand. We could keep track of all of the cards in the opponent's hand at the moment that the Blackwing Technician was played. If all of those cards, except for one, are eventually played, and we saw that none of them were dragons, then we can deduce that the final card must be a dragon. This also tells us that it is definitely a minion, which means we can show its mana cost as (+1) if a Mana Wraith is on the field, or (+3) if the opponent plays a Venture Co. Mercenary. If the opponent later draws and plays a Dragon Consort, we can show that the minion which we know for sure is a dragon costs (-2) mana. We can go even further if we know that certain cards in hand, when Blackwing Technician was played, were definitely not dragons. For example, if we already know they were mech minions generated through Gazlowe, or spells generated from Nefarian. Then we don't need to consider those in the set of possible dragons.

Cards generated from Ysera could be anything from a limited set of dream cards. We don't know for sure what the cards are, only that they're definitely not weapons. But we could show the limited set of dream cards that they could be, just like how HDT already shows the possibilities from Animal Companion, etc. However, we could also know for certain that a dream card in hand is an Emerald Drake, if we deduce that it is definitely a dragon, using the above logic, since we know there is only one dragon dream card. Similarly, we could deduce that the card cannot possibly be an Emerald Drake, if a Blackwing Technician is played that doesn't trigger its effect. Then we could remove that possibility from the limited set of possible cards that are shown to the user.

Similarly, if Holy Wrath hits for 12, we could perhaps show a limited list of cards that cost 12 mana. When the potential card pool is perhaps 5 cards or less, we could show what the possibilities are.
 
We could also show the source of cards on a separate tooltip. For example, a card generated via Unstable Portal would naturally show (-3) mana cost, but we could also show that it was generated from Unstable Portal. This is more important though for a card drawn from Call Pet, for example, because it costs (-4) mana only if it's a beast. Since we don't know for sure if it's a beast, we cannot put that mana cost reduction into the tooltip. But we could show the player that the card came from Call Pet, and then the player can use their best judgement with the knowledge that it potentially costs (-4) mana. We don't need to bother showing the source of normal draws, like for example from a Loot Hoarder. Only show the source of the card when it is a generated random card not in the deck, like from Gazlowe, or if the drawn card is affected in some way by a condition, but we don't know for sure whether the condition was met, like with Call Pet.

We should keep track of the mana cost reductions even when they become negative. Just display the mana cost as zero if it is negative, but actually keep track of the negative number. This is because a spell card that costs (-5) absolute mana actually becomes (0) when Loatheb is played. Confirmed here: https://youtu.be/oXrXfB5dUDc?t=1007

We can also make sure all of this information is shown in the replays too. If the opponent gets a mech from a Gazlowe, but never plays the card from his hand before the game is over, in the replay we could show that it was a mech minion on a tooltip, just like in game.

**Comment by foxor** [comment]
+1

There are some pretty ambitious ideas in this issue, but it seems like there is a lot of low-hanging fruit, like adding marks to dream cards and gazlowe mechs that could be tackled before doing more complicated things, like thaurissan ticks and dragon interactions.

**Comment by jleclanche** [comment]
Consolidating into #2224
