### ISSUE TITLE
Arena Helper plugin missing in menu

### ISSUE THREAD

**Issue by TashaOtter** [Epix37/Hearthstone-Deck-Tracker#1035]
I downloaded the Arena Helper plugin, moved ArenaHelper.dll to the Plugins subfolder of the HDT folder, started HDT, went to Options, went to Plugins.  Arena Helper was listed there.  I clicked the switch, it now reads Enabled.  I close Options, click on the Plugins menu, and it shows "Empty..." - I restart HDT and it still shows "Empty...".

If I go back to Options > Plugins and click on the "Arena Helper" button in the lower-right, an "Arena Helper" window pops up, and says "Detecting arena...", but does nothing even when Hearthstone is open and I've started a new arena run, following all the instructions from the Arena Helper README.  (Except for the one about launching it from the Plugins menu, because the Plugins menu is empty.)

Not sure if this is an Arena Helper issue, a HDT issue, or both - I'm filing it here, let me know if I should move it.

Running Windows 10 Build 10074 in Boot Camp on a MacBook Pro, if it matters.  Thanks.

**Comment by Epix37** [comment]
Maybe this could be a WIndows 10 problem? I'm not sure.

Do other plugins work for you? (Show up in the menu?)

**Comment by TashaOtter** [comment]
I tried it in Windows 7 in a Parallels virtual machine under OS X, same behavior there.  Doesn't appear to be a Windows 10 issue.

I downloaded Collection Tracker and it appears to work as expected, and it shows up in the menu.  So perhaps this is an issue with Arena Helper specifically - should I open an issue over there?

**Comment by Epix37** [comment]
Before that, do this please:

1) disable the plugin
2) restart HDT
3) enable the plugin
4) upload the (latest) hdt_log.txt from "%AppData%/HearthstoneDeckTracker/Logs" (Win+R, paste) to http://pastebin.com and post the link here

Might either tell us the problem right away or at least give the ArenaHelper dev a place to start.

**Comment by TashaOtter** [comment]
hdt_log.txt said Arena Helper was choking trying to find Hearthstone Deck Tracker\Plugins\data\cardhashes.json, which didn't exist because I didn't have the plugin installed correctly.  I installed it correctly, and it now shows up in the menu.

The documentation is a little unclear.

https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Available-Plugins says to "Extract/copy [PLUGINNAME].dll to Hearthstone Deck Tracker/Plugins"... that was enough for Collection Tracker because it was only one file, but for Arena Helper, I needed to copy all the supporting files as well.

https://github.com/rembound/Arena-Helper says to "Unzip the archive to the Plugins directory of Hearthstone Deck Tracker"... the contents of the archive is a directory named ArenaHelper, and putting that directory in the plugins directory does not work, you have to move the contents of the ArenaHelper directory to the plugins directory.

Thanks for your help, and for the excellent program in general.

**Comment by Epix37** [comment]
Having it as "Plugins/ArenaHelper", containing the ArenaHelper.dll, as well as all the other .dlls and folders should work. HDT looks for plugins in the "Plugins" folder, plus one folder down. 

Extracting it to "Plugins/SomeFolder/ArenaHelper" or having the ArenaHelper.dll outside of the ArenaHelper folder (I'm gonna guess this was the case for you?) will not work. 

Sorry for the unclear directions, I will adjust it to hopefully be more clear! Glad you got it working though :).
