### ISSUE TITLE
Add an "Open plugins folder" button

### ISSUE THREAD

**Issue by dantedog** [Epix37/Hearthstone-Deck-Tracker#1037]
I can't be the only one that has a hard time remembering where I put hearthstone deck tracker folder. A little button similar to the "Open Appdata folder" would be nice.

**Comment by Epix37** [comment]
That's a good idea, I will do that!

**Comment by Epix37** [comment]
![plugins](https://cloud.githubusercontent.com/assets/7737910/8015036/d3d5782a-0bd5-11e5-8d1d-f107c46ccb67.PNG)

Done and also restructured the panel a little bit.

**Comment by dantedog** [comment]
Awesome!
