### ISSUE TITLE
Suggestion: Disable deck overlay while Hearthstone is not the active Window

### ISSUE THREAD

**Issue by greenbird13** [Epix37/Hearthstone-Deck-Tracker#1040]
The deck overlay is always visible. It should be visible if Hearthstone is minimized or not the Active Window.

pura vida
André

**Comment by Epix37** [comment]
Check out the "Hide in/if..." options in `options > overlay > general`

**Comment by greenbird13** [comment]
Perfect. I missed that option while looking through the menues. I suggest to tick the option "Hide if HS in Background" as a default. I guess most people would like to have it ticket.

Thanks for the quick reply.

pura vida
André

**Comment by Epix37** [comment]
I think you can argue both ways for the default on that one. "In background" means its not the topmost window, regardless of whether something is actually in front of it. So if you have a multi monitor setup or HS in windowed mode, clicking somewhere outside the window will hide the overlay.
