### ISSUE TITLE
Suggestion: Option to Auto discard matches for Spectator

### ISSUE THREAD

**Issue by ekohilas** [Epix37/Hearthstone-Deck-Tracker#1042]
Whenever I watch a spectator game, I want to be able to record the match, and be able to save their decks, But I don't want to save it to the deck's match history
cheeers

**Comment by mvordeme** [comment]
Actually, this kind of thing is puzzling me. When I spectate a game, the tracker tries to match the deck and fails. Then I have to use no deck which denies me the option to save either of the used decks in the spectated game. But that is the only meaningful thing to do after a spectated game. The same goes for tavern brawls and class challenges with prepared decks.

It would be nice to be able to reconstruct a prepared deck from multiple plays of the same tavern brawl or class challenge. The interface could work like this:

When I play for the first time, I have the option to create a new deck from the current game. Even if it is not complete, it can be used again in subsequent matches and be completed in the process.

**Comment by culinko** [comment]
Related to #1294.

**Comment by Epix37** [comment]
Closing in favor of #1294
