### ISSUE TITLE
Display gvg/brm/naxx icons in deck picker

### ISSUE THREAD

**Issue by anonymous555** [Epix37/Hearthstone-Deck-Tracker#1044]
Display gvg/brm/naxx icons in deck picker.

![cardsets](https://cloud.githubusercontent.com/assets/8370128/8025588/d210aa42-0d0f-11e5-84e1-a2474c293767.png)

**Comment by disshishkov** [comment]
what is the goal?

**Comment by Epix37** [comment]
I agree I don't quite see the point in having it visible on all decks at all times, *but* placing it next to the card count in the edit panel might be a good idea. Especially when importing decks, this could be helpful. (Amazing photoshop inc.)
![icons](https://cloud.githubusercontent.com/assets/7737910/8033390/41261e5c-0dde-11e5-894f-606cb2bf0131.PNG)

**Comment by anonymous555** [comment]
It makes it easy to identify older decks that don't use new card sets. Maybe an option to enable?  But as editing isn't a bad idea either.

**Comment by Epix37** [comment]
Added with v0.10.5, I did go for text, rather than icons for now though. These are the hearthpwn ones right? I did not want to just use them.
