### ISSUE TITLE
Add deck winrate plots in stats window

### ISSUE THREAD

**Issue by anonymous555** [Epix37/Hearthstone-Deck-Tracker#1045]
Show the winrate for each deck and for the class, display it as a bar graph.  I already implemented this in my sandbox..

![deckplots](https://cloud.githubusercontent.com/assets/8370128/8025603/90fd4e6a-0d10-11e5-9f37-6b9145df71e4.png)

**Comment by disshishkov** [comment]
off-topic 
@anonymous555 how did you make a stats with light theme?
I selected **BaseLight** but it doesn't affect options and stats windows

**Comment by GiggliG** [comment]
Interesting idea. You could probably add other graphs, like win rate over time.
