### ISSUE TITLE
Legendary Minion Returned to Hand by Freezing Trap "Not Found in Deck"

### ISSUE THREAD

**Issue by mvordeme** [Epix37/Hearthstone-Deck-Tracker#1046]
I just had Sneed's Old Shredder returned to my hand by a Freezing Trap which resulted in a "Card not Found" warning and the game not being properly recorded.

Maybe it is a problem with the Freezing Trap in particular. The replay doesn't show the Shredder attacking. It looks more like I simply picked up another card. In the end, the opponent's name wasn't recorded, the number of turns was set to 0 although the replay clearly shows all 10 turns, and the fact that the opponent conceded wasn't recorded.

I just edited the game and added those details, but I only found the problem because the warning had puzzled me.

**Comment by culinko** [comment]
I just tried to reproduce this specific issue with my friend and everything was working correctly.
