### ISSUE TITLE
Plugins folder doesnt appear

### ISSUE THREAD

**Issue by Cicor** [Epix37/Hearthstone-Deck-Tracker#1048]
Hey, 

Im trying to install HDT Twitch Plugin but I cant do the first step:

1) Place TwitchPlugin.dll in Hearthstone Deck Tracker/Plugins

I dont have that folder, I was trying to create the folder and place the dll but the 3rd step didnt go well because It doesnt appear as a plugin.

3) Enable plugin via options > Tracker > Plugins

http://gyazo.com/346d52f4c02ec92e91925d33cf842601

What can I do ? I have the lastest version of HDT.

Thanks.

**Comment by Epix37** [comment]
Manually downloading and extract the [latest release](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.10.3) and try again with that. (that does have the plugins folder)

**Comment by Cicor** [comment]
Ok, solved. 

I finally installed the plugin, and it seems it works because when I turn ON the plugin says HELLO on my twitch chat and bye when I turn OFF but It doesnt do anything when I write !commands on chat.

Any ideas?

Thanks!

**Comment by Cicor** [comment]
https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1048#issuecomment-110021923

Its almost done!

2015-06-08 16:48 GMT+02:00 Epix <notifications@github.com>:
