### ISSUE TITLE
Crashing when accessing card.name 

### ISSUE THREAD

**Issue by XGSleepWalker** [Epix37/Hearthstone-Deck-Tracker#1049]
http://pastebin.com/nZqn9e5N

**Comment by Epix37** [comment]
Can you provide a bit more context?

**Comment by XGSleepWalker** [comment]
i believe it to be in this part: http://pastebin.com/BLQ91a8k

(on the SpeakASync(h.Value.Card.Name part

**Comment by XGSleepWalker** [comment]
http://pastebin.com/VkndXE9B

Issue still exists on new version. HDT crashes when calling entity.card.name

**Comment by Epix37** [comment]
Does it work if you call `Game.GetCardFromId(h.Value.CardId).Name`?

**Comment by XGSleepWalker** [comment]
It does work when I call Game.GetCardFromId(string).Name
