### ISSUE TITLE
Crash After Doing a Full Sync on Latest Beta

### ISSUE THREAD

**Issue by rtucker88** [Epix37/Hearthstone-Deck-Tracker#1050]
Here's a gist with the crash report: https://gist.github.com/rtucker88/7eca96825dc378541f89.

I was trying to help a friend set-up the deck tracker so I ran it myself in a Windows 8.1 VM. I successfully logged into Hearthstats and saw all my decks and attempted a full sync. 

I don't have Hearthstone installed on this VM.

The program now immediately crashes on start-up.

**Comment by Epix37** [comment]
Now that's a Stacktrace...

Anyway, same problem as in #1036, see [my comment in #1036](https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1036#issuecomment-109748112) for a fix.
