### ISSUE TITLE
Decks don't display

### ISSUE THREAD

**Issue by Pand3m0nia** [Epix37/Hearthstone-Deck-Tracker#1051]
Hi there,

I don't know if it had anything to do with me Syncing with HearthStats, but now when I start up HDT none of my decks appear. My decks appear on the HearthStats Dashboard, and there are still records under the Stats tab.

Please help.

Thanks

**Comment by Epix37** [comment]
try main > quick filter > all

**Comment by Pand3m0nia** [comment]
Hahahaha, that worked, I feel like quite the idiot... Thanks. Would you happen to know what I accidentally clicked or changed for that to happen?
