### ISSUE TITLE
Grey font and all caps in new deck picker interface when using black theme

### ISSUE THREAD

**Issue by Rynvar** [Epix37/Hearthstone-Deck-Tracker#1053]
I initially disliked the deck picker change at first, but after getting past my initial reaction I found that it matches the rest of the UI better than before.

However, since I use the black theme, there are 2 things that bother me.
1) The percentage, win-lose count and tags are a few shades of grey too dark. It's fine for the "USE" button to be more faded out, but I feel the stats/tags should be a slightly lighter shade of grey to make it easier to see at first glance.
2) I've never noticed before that the deck names are in all-caps, but now that the class-based background gradients are gone, having all-caps white on back looks really awkward (just my thought).
So an option like "All-caps in deck picker" would be nice.

**Comment by Epix37** [comment]
Thanks for the PR and I agree on 1). 

I think this is a lot better now: 
![gray](https://cloud.githubusercontent.com/assets/7737910/8051742/90dfe020-0e80-11e5-9b82-dd58b80c0b8d.PNG)
