### ISSUE TITLE
crash try to open

### ISSUE THREAD

**Issue by Arsenikon** [Epix37/Hearthstone-Deck-Tracker#1057]
########## 09/06/2015 09:07:38 ##########
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à System.Windows.DeferredAppResourceReference.GetValue(BaseValueSourceInternal valueSource)
   à System.Windows.DependencyObject.GetEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, RequestFlags requests)
   à System.Windows.DependencyObject.GetValueEntry(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, RequestFlags requests)
   à System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   à System.Windows.Shapes.Shape.get_Fill()
   à System.Windows.Shapes.Shape.OnRender(DrawingContext drawingContext)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Controls.Canvas.ArrangeOverride(Size arrangeSize)
   à System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Media.VisualBrush.DoLayout(UIElement element)
   à System.Windows.Media.VisualBrush.LayoutCallback(Object arg)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

########## 09/06/2015 09:07:38 ##########
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à System.Windows.DeferredAppResourceReference.GetValue(BaseValueSourceInternal valueSource)
   à System.Windows.DependencyObject.GetEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, RequestFlags requests)
   à System.Windows.DependencyObject.GetValueEntry(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, RequestFlags requests)
   à System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   à System.Windows.Shapes.Shape.get_Fill()
   à System.Windows.Shapes.Shape.OnRender(DrawingContext drawingContext)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Controls.Canvas.ArrangeOverride(Size arrangeSize)
   à System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Media.VisualBrush.DoLayout(UIElement element)
   à System.Windows.Media.VisualBrush.LayoutCallback(Object arg)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

########## 09/06/2015 09:07:38 ##########
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à System.Windows.DeferredAppResourceReference.GetValue(BaseValueSourceInternal valueSource)
   à System.Windows.DependencyObject.GetEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, RequestFlags requests)
   à System.Windows.DependencyObject.GetValueEntry(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, RequestFlags requests)
   à System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   à System.Windows.Shapes.Shape.get_Fill()
   à System.Windows.Shapes.Shape.OnRender(DrawingContext drawingContext)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Controls.Canvas.ArrangeOverride(Size arrangeSize)
   à System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Media.VisualBrush.DoLayout(UIElement element)
   à System.Windows.Media.VisualBrush.LayoutCallback(Object arg)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

########## 09/06/2015 09:07:38 ##########
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à System.Windows.DeferredAppResourceReference.GetValue(BaseValueSourceInternal valueSource)
   à System.Windows.DependencyObject.GetEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, RequestFlags requests)
   à System.Windows.DependencyObject.GetValueEntry(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, RequestFlags requests)
   à System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   à System.Windows.Shapes.Shape.get_Fill()
   à System.Windows.Shapes.Shape.OnRender(DrawingContext drawingContext)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Controls.Canvas.ArrangeOverride(Size arrangeSize)
   à System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Media.VisualBrush.DoLayout(UIElement element)
   à System.Windows.Media.VisualBrush.LayoutCallback(Object arg)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

########## 09/06/2015 09:07:38 ##########
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à System.Windows.DeferredAppResourceReference.GetValue(BaseValueSourceInternal valueSource)
   à System.Windows.DependencyObject.GetEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, RequestFlags requests)
   à System.Windows.DependencyObject.GetValueEntry(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, RequestFlags requests)
   à System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   à System.Windows.Shapes.Shape.get_Fill()
   à System.Windows.Shapes.Shape.OnRender(DrawingContext drawingContext)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Controls.Canvas.ArrangeOverride(Size arrangeSize)
   à System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Media.VisualBrush.DoLayout(UIElement element)
   à System.Windows.Media.VisualBrush.LayoutCallback(Object arg)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

########## 09/06/2015 09:07:38 ##########
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à System.Windows.DeferredAppResourceReference.GetValue(BaseValueSourceInternal valueSource)
   à System.Windows.DependencyObject.GetEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, RequestFlags requests)
   à System.Windows.DependencyObject.GetValueEntry(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, RequestFlags requests)
   à System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   à System.Windows.Shapes.Shape.get_Fill()
   à System.Windows.Shapes.Shape.OnRender(DrawingContext drawingContext)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Controls.Canvas.ArrangeOverride(Size arrangeSize)
   à System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Media.VisualBrush.DoLayout(UIElement element)
   à System.Windows.Media.VisualBrush.LayoutCallback(Object arg)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

########## 09/06/2015 09:07:38 ##########
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à System.Windows.DeferredAppResourceReference.GetValue(BaseValueSourceInternal valueSource)
   à System.Windows.DependencyObject.GetEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, RequestFlags requests)
   à System.Windows.DependencyObject.GetValueEntry(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, RequestFlags requests)
   à System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   à System.Windows.Shapes.Shape.get_Fill()
   à System.Windows.Shapes.Shape.OnRender(DrawingContext drawingContext)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Controls.Canvas.ArrangeOverride(Size arrangeSize)
   à System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Media.VisualBrush.DoLayout(UIElement element)
   à System.Windows.Media.VisualBrush.LayoutCallback(Object arg)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

########## 09/06/2015 09:07:38 ##########
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à System.Windows.DeferredAppResourceReference.GetValue(BaseValueSourceInternal valueSource)
   à System.Windows.DependencyObject.GetEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, RequestFlags requests)
   à System.Windows.DependencyObject.GetValueEntry(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, RequestFlags requests)
   à System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   à System.Windows.Shapes.Shape.get_Fill()
   à System.Windows.Shapes.Shape.OnRender(DrawingContext drawingContext)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Controls.Canvas.ArrangeOverride(Size arrangeSize)
   à System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Media.VisualBrush.DoLayout(UIElement element)
   à System.Windows.Media.VisualBrush.LayoutCallback(Object arg)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

########## 09/06/2015 09:07:38 ##########
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à System.Windows.DeferredAppResourceReference.GetValue(BaseValueSourceInternal valueSource)
   à System.Windows.DependencyObject.GetEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, RequestFlags requests)
   à System.Windows.DependencyObject.GetValueEntry(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, RequestFlags requests)
   à System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   à System.Windows.Shapes.Shape.get_Fill()
   à System.Windows.Shapes.Shape.OnRender(DrawingContext drawingContext)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Controls.Canvas.ArrangeOverride(Size arrangeSize)
   à System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Media.VisualBrush.DoLayout(UIElement element)
   à System.Windows.Media.VisualBrush.LayoutCallback(Object arg)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

########## 09/06/2015 09:07:38 ##########
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à System.Windows.DeferredAppResourceReference.GetValue(BaseValueSourceInternal valueSource)
   à System.Windows.DependencyObject.GetEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, RequestFlags requests)
   à System.Windows.DependencyObject.GetValueEntry(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, RequestFlags requests)
   à System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   à System.Windows.Shapes.Shape.get_Fill()
   à System.Windows.Shapes.Shape.OnRender(DrawingContext drawingContext)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Controls.Canvas.ArrangeOverride(Size arrangeSize)
   à System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Media.VisualBrush.DoLayout(UIElement element)
   à System.Windows.Media.VisualBrush.LayoutCallback(Object arg)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

########## 09/06/2015 09:07:38 ##########
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à System.Windows.DeferredAppResourceReference.GetValue(BaseValueSourceInternal valueSource)
   à System.Windows.DependencyObject.GetEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, RequestFlags requests)
   à System.Windows.DependencyObject.GetValueEntry(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, RequestFlags requests)
   à System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   à System.Windows.Shapes.Shape.get_Fill()
   à System.Windows.Shapes.Shape.OnRender(DrawingContext drawingContext)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Controls.Canvas.ArrangeOverride(Size arrangeSize)
   à System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Media.VisualBrush.DoLayout(UIElement element)
   à System.Windows.Media.VisualBrush.LayoutCallback(Object arg)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

########## 09/06/2015 09:07:38 ##########
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à System.Windows.DeferredAppResourceReference.GetValue(BaseValueSourceInternal valueSource)
   à System.Windows.DependencyObject.GetEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, RequestFlags requests)
   à System.Windows.DependencyObject.GetValueEntry(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, RequestFlags requests)
   à System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   à System.Windows.Shapes.Shape.get_Fill()
   à System.Windows.Shapes.Shape.OnRender(DrawingContext drawingContext)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Controls.Canvas.ArrangeOverride(Size arrangeSize)
   à System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Media.VisualBrush.DoLayout(UIElement element)
   à System.Windows.Media.VisualBrush.LayoutCallback(Object arg)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

########## 09/06/2015 09:07:38 ##########
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à System.Windows.DeferredAppResourceReference.GetValue(BaseValueSourceInternal valueSource)
   à System.Windows.DependencyObject.GetEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, RequestFlags requests)
   à System.Windows.DependencyObject.GetValueEntry(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, RequestFlags requests)
   à System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   à System.Windows.Shapes.Shape.get_Fill()
   à System.Windows.Shapes.Shape.OnRender(DrawingContext drawingContext)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Controls.Canvas.ArrangeOverride(Size arrangeSize)
   à System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   à System.Windows.UIElement.Arrange(Rect finalRect)
   à System.Windows.Media.VisualBrush.DoLayout(UIElement element)
   à System.Windows.Media.VisualBrush.LayoutCallback(Object arg)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Epix37** [comment]
Does this happen with v0.10.4 and v0.10.3? If so try reinstalling .Net Framwork 4.5.

**Comment by Arsenikon** [comment]
Thanks you

I already found what going on :

Hearthstone-Deck-Tracker was running but no icon was display on the task bar.

I closed the process and everything became normal.

 

 

 

 

De : Epix [mailto:notifications@github.com] 
Envoyé : mardi 9 juin 2015 09:38
À : Epix37/Hearthstone-Deck-Tracker
Cc : Arsenikon
Objet : Re: [Hearthstone-Deck-Tracker] crash try to open (#1057)

 

Does this happen with v0.10.4 and v0.10.3? If so try reinstalling .Net Framwork 4.5.
