### ISSUE TITLE
Deck Tracker not showing my decks

### ISSUE THREAD

**Issue by Grahnade** [Epix37/Hearthstone-Deck-Tracker#1058]
I installed the Deck Tracker, set the Hearthstone path but it wont show my decks. I also can not export decks to Hearthstone (only from web). If I am ingame Deck Tracker only shows me which cards got played but not which cards are left in my deck.
![tracker](https://cloud.githubusercontent.com/assets/12811896/8055567/bf2867fc-0ea0-11e5-9ed7-5aa6ce08a588.jpg)

**Comment by Epix37** [comment]
It is not possible for HDT to automatically import your decks. 

[How to use](https://github.com/Epix37/Hearthstone-Deck-Tracker#how-to-use-)

You have to either
* create decks via the "new" menu item
* import from game or web via the "import" menu item

**Comment by Grahnade** [comment]
Now it works. Big thanks.
