### ISSUE TITLE
Suggestion: Guess opponent deck based off drawn cards

### ISSUE THREAD

**Issue by Nicktho** [Epix37/Hearthstone-Deck-Tracker#1060]
It would be cool to see a count of how many cards the opponent has drawn against popular decks on the major sites to calculate a guess as to which deck the opponent is using.

**Comment by Epix37** [comment]
Most likely not going to happen. While it would be very awesome, it is probably "a step too far" and could result in Blizzard no longer tolerating the tool. See #263.
