### ISSUE TITLE
New Patch - Can't make old versions the Active version

### ISSUE THREAD

**Issue by Taho22** [Epix37/Hearthstone-Deck-Tracker#1061]
Hi.  Here's some feedback on the latest patch.  I'm not sure if this is a bug, intended, or user error, but I am unable to make an older version of a deck the "Active" deck.  This seems like a problem to me.  Let me know if I am missing something or doing something wrong.  Thanks.

**Comment by Epix37** [comment]
Fixed this just now for the next update (tomorrow). Switching the version right now only works once, after that you have to restart HDT to do it again.

**Comment by JSallee** [comment]
Just noticed that editing an deck does not appear to save the changes to the deck list, only the older version is listed until the program is restarted.  Different bug or related?

**Comment by Epix37** [comment]
Different bug, also fixed now.

Beta release of this was out for 2 days, no one noticed these things :(.

**Comment by Epix37** [comment]
Here is the latest build with all the fixes: https://github.com/Epix37/HDT-Test/releases/tag/v0.10.6_PRE1

Let me know if you find any more problems!

**Comment by Sesquipedal** [comment]
Just signed up to say thanks Epix!  I saw this issue, came on here as per help file, and already you've fixed and updated it.   That's incredible that you give so much time to something we use for fun.  

Thanks again.

**Comment by Potaetoe** [comment]
Just as a note, could we create a button to restart HDT on the title bar. I know it's in Options --> Deck Tracker --> Settings. Just for GP, or allow the client to create hotlinks to settings in the title bar.

**Comment by Epix37** [comment]
Why do you need a restart button in the title bar?
