### ISSUE TITLE
Export to Hearthstone not working anymore

### ISSUE THREAD

**Issue by agaragnani** [Epix37/Hearthstone-Deck-Tracker#1065]
Release v0.10.5 seem to have broken export to hearthstone for me. Simply nothing appens after clicking it

**Comment by Epix37** [comment]
With 0.10.5, make sure you to have it set as the active deck. Fixed for the coming update.

**Comment by FenrisWolffe** [comment]
Not fixed in 10.6, active or not.

**Comment by Pand3m0nia** [comment]
When I try export to Hearthstone it usually goes up to exactly 16 cards then stops. It also has told me that I don't own certain cards when I do in fact own them.
