### ISSUE TITLE
Auto Selection deck does not work ?

### ISSUE THREAD

**Issue by Zaytchik** [Epix37/Hearthstone-Deck-Tracker#1067]
Hello, since yesterday release (with new design), auto deck selection is not working anymore (i have to manually select one deck when starting a new game or it keeps the previous one).

Thanks a lot for your great job, new design is wonderfull ;)

**Comment by Epix37** [comment]
v0.10.6 should fix this.

**Comment by Zaytchik** [comment]
Thanks !

**Comment by Epix37** [comment]
actually, this might yet be a different issue.  let me know if it works with the latest release.

**Comment by Zaytchik** [comment]
Still not working with 0.10.6 version.

**Comment by Epix37** [comment]
I will look into it, thank you.

**Comment by Crowfish** [comment]
It recognized one of my decks (a priest deck of which I have two in the list), a mage deck (two again) but not the rest. and there are other classes I have two decks of. I can't see any real pattern in the placement either but if there's any information I can provide I'll be happy to go look for it.

And also, a big thanks for this very useful application.

**Comment by GiggliG** [comment]
I'm having the same issue, with the latest patch (10.6). I need to manually click each deck to active.
On one of the games, it popped up a message at the top of the hearthstone screen that the deck was the wrong one (various cards missing), and other games it gave no message.

**Comment by catchum** [comment]
I cannot change decks while the program is open in the new update. When I click on a deck it highlights it, if i double click it opens up the deck editor. (is there a button that says make my active deck? I don't even see one) the only way i can switch is if i close the program and then open it back up. It will choose the last deck I had highlighted

**Comment by mvordeme** [comment]
I am experiencing that issue, too. My impression is that it doesn't work any longer after I imported a new deck. When I restart the tracker, auto selection usually works again. I must admit that I didn't test that assumption thoroughly, though.

**Comment by Bahzur** [comment]
Can confirm it still does not work. I only get the ingame warning that some cards don't match and it does not switch to the correct deck. Manually switching the deck does work for me though, also retroaktive while im already ingame.

**Comment by livejamie** [comment]
Not working for me either

**Comment by lunarwolfspirit** [comment]
Still not working for me. The tracker will always default to the deck that we have selected using "USE" and doesn't adapt when changing decks in game. (I'm running version 0.10.7)

**Comment by ryansmith18** [comment]
Still having trouble auto selecting for me as well. I noticed that when I open the interface and select or deselect the option, it's status isn't replicated in the system tray. I don't know if that's of any value to you or not, but it was odd to me. 

To clarify, when I right click the system tray icon I can choose "Use no deck" or "Autoselect deck." Whichever one I turn on or off, it's value is not the same in the main window. I can make changes in the main window, and it has no effect on what I selected in the tray.

Btw - thanks for all you do. This app is great.

**Comment by livejamie** [comment]
I found that the problem that was happening for me was related to the incorrect import.

I'd import a Shaman deck and it would get two of the cards wrong, but I didn't know.

That's why it was giving me errors because the cards didn't match the deck.

**Comment by mvordeme** [comment]
I wasn't too sure that maybe auto-selection works, only the deck to select is not unique. (It might be a good idea to present the player with a choice of eligible decks if that is the case.) But then after playing an arena, I played ranked with the only Shaman deck I have. I even watched HDT selecting the proper deck, but it didn't mark it active. It seems there is something confused about selecting and activating a deck. (If I remember correctly, there is another issue about deck version selection where active and selected decks are mixed up, but I can't seem to find it right now.)

**Comment by Epix37** [comment]
I'm pretty sure I found and fixes the issue now!

**Comment by andburn** [comment]
@Epix37 I found some of the auto selection problems (#1122) are caused by having no deck active. I think it could be the `IsUsingPremade` check [here](https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/a2d05c2f3b1aa22093b555ccb8368659b9cc0cf6/Hearthstone%20Deck%20Tracker/GameEventHandler.cs#L179).

**Comment by GaryKing** [comment]
@Epix37 Excellent. Will the app auto-update or do we have to download the new release when it's available?

**Comment by Epix37** [comment]
@andburn that's working as intended then. Auto selection is not supposed to work w/o a deck selected, otherwise you would have to turn off auto selection every time you want to use no deck. This way you can just activate any deck and it's good to go.

@GaryKing HDT will prompt an automatic download as soon as a new version is available, yes.

**Comment by Epix37** [comment]
Should be working again  (v0.10.9) - let me know if you still have issues with this.

**Comment by GaryKing** [comment]
I still have issues. Same as before. Auto-deck just doesn't always automatically select a deck, so I have to Alt-Tab out of the game to manually select the deck.

**Comment by culinko** [comment]
I can confirm it doesn't work in 0.10.10 even if I have only 1 constructed deck from that specific class.

**Comment by Zaytchik** [comment]
Works fine on my side now (ver 0.10.10). Thanks a lot, this tool is so awesome :+1:

**Comment by Epix37** [comment]
Two questions:
1) Do you have a deck selected (it's not in "no deck" mode) when that happens? Auto deck selection only works if a (any) deck is selected.
2) Do the drawn cards at that point match the deck? Auto selection only triggers when a card is drawn that is not found in the deck. No way around that.

If both of those are not the case, please do the following after it does not work the next time:
* Upload the log - [see here on where to find and upload it](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)
* Go to `options > tracker > backups`, click `create new` and then `show backup folder`. The folder will contain a file called something like "BackupManual_17082015.zip". Upload that file to a website of your choice or email it to me directly at `epikz37@gmail.com`.

**Comment by culinko** [comment]
I removed my previous post and investigated more:

- I had Tempo Mage activated but played as Freeze Mage, only the warning was displayed that the cards don't match the deck.
- I had Combo Druid activated but played as Freeze Mage, only Freeze Mage option appeared (I have 2 Mage decks).
- I had Combo Druid activated but played as Handlock, nothing happened (I have 2 Warlock decks).
- Also the first time I think I had Combo Priest active, but played as Druid (I have only 1 deck), the options displayed were Combo Druid and the newest Druid arena deck. But can't reproduce it again.

I'm sending you an e-mail with the required data now.

**Comment by mvordeme** [comment]
Since I have uploaded the log, anyway, I can post mine, too: http://pastebin.com/BaZqT810. Originally, I thought that it was working for me, but today, auto-detect failed. I had been playing (and losing) Rogue when I decided to continue as Priest (and lost some more). The warning was displayed and nothing else happened.

**Comment by mvordeme** [comment]
Okay, I found the reason why it didn't switch:

[15:03:49] GameEventHandler: Found incorrect deck on PlayerDraw
[15:03:49] GameStats: New play: PlayerDraw (GVG_114, turn: 0)
[15:03:49] GameEventHandler: PlayerDraw (id:GVG_096 turn:0 from:-1)
[15:03:49] Hearthstone: (player deck) Piloted Shredder count 2 -> 1
[15:03:49] GameStats: New play: PlayerDraw (GVG_096, turn: 0)
[15:03:49] GameEventHandler: PlayerDraw (id:CS1_112 turn:0 from:-1)
[15:03:49] GameStats: New play: PlayerDraw (CS1_112, turn: 0)
[15:03:49] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[15:03:49] GameStats: New play: OpponentDraw (, turn: 0)
[15:03:49] IncorrectDeckMessage: 0 possible decks found.
[15:03:49] GameEventHandler: Playing against Paladin
**[15:03:49] HandleGameStart: Found more than 1 deck to switch to - last played: Tavern Brawl: The Great Summoner Competition - Anduin**
**[15:03:49] HandleGameStart: Deck Tavern Brawl: The Great Summoner Competition - Anduin is archived - not switching**
[15:03:56] UpdateOverlay: Refreshed overlay topmost status
[15:04:09] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[15:04:09] Hearthstone: Set card 5 to age 0
[15:04:09] Hearthstone: Opponent Hand after draw: 0K,0K,0K,0K,0C,0K,  ,  ,  , 
[15:04:09] GameStats: New play: OpponentDraw (, turn: 0)
[15:04:09] GameEventHandler: OpponentMulligan (id: turn:0 from:1)
[15:04:09] Hearthstone: Fixed hand ages after mulligan (removed 5)
[15:04:09] Hearthstone: Opponent Hand after draw: 0M,0K,0K,0K,0C, K,  ,  ,  , 
[15:04:09] GameStats: New play: OpponentMulligan (, turn: 0)
[15:04:09] GameEventHandler: OpponentDraw (id: turn:0 from:-1)
[15:04:09] Hearthstone: Set card 5 to age 0
[15:04:09] Hearthstone: Opponent Hand after draw: 0M,0K,0K,0K,0C,0K,  ,  ,  , 
[15:04:09] GameStats: New play: OpponentDraw (, turn: 0)
[15:04:09] GameEventHandler: OpponentMulligan (id: turn:0 from:2)
[15:04:09] Hearthstone: Fixed hand ages after mulligan (removed 5)
[15:04:09] Hearthstone: Opponent Hand after draw: 0M,0M,0K,0K,0C, K,  ,  ,  , 
[15:04:09] GameStats: New play: OpponentMulligan (, turn: 0)
[15:04:10] Tracker: Set player itemsource as PlayerDeck
[15:04:10] Tracker: Switched to deck: Judas
[15:04:10] Game: >>>>>>>>>>> Reset <<<<<<<<<<<

HDT found more than one matching deck, and the last-played matching deck was archived, so it didn't switch. Is that intended behaviour? I'd assume that archived decks are not taken into account when switching, or else auto-detect would become entirely unusable over time.

**Comment by Epix37** [comment]
Correct, archived decks are not taken into account. The two lines mean that no automatic switch happened, it should still have presented you with a dialog to choose from :/.

**Comment by mvordeme** [comment]
I just checked the replay. Apart from archived decks, there is only one deck which matches the drawn cards. Could it be that the archived deck was only considered because it had been played more recently than the other one?

**Comment by Epix37** [comment]
I think so, yes. I may have found something to finally fully fix this. Update will be out in 3 hours - let me know :).

**Comment by mvordeme** [comment]
So far, things are looking good. Is the Tracker supposed to switch between constructed and arena? That's something which didn't work yesterday. A constructed deck was selected and I started an arena run. I got a pop-up window with the option to select no deck or something else I can't remember. The arena deck wasn't found, and I had to switch manually.

**Comment by mvordeme** [comment]
Hm, this time it worked.

**Comment by sehynes** [comment]
This is happening to me.  Deck Tracker auto-selects on my laptop but not on my desktop.  

Is anyone else still having this problem?  How do I go about troubleshooting ?

**Comment by vladimirgoncearuc** [comment]
have same problem , using on W10
