### ISSUE TITLE
Export function doesn't work

### ISSUE THREAD

**Issue by Ferrozin** [Epix37/Hearthstone-Deck-Tracker#1068]
Hi, first of all: thx for the lots of work, this app is awesome :-)

Unfortunaly i have a problem with the export tool. It doesn't work ... and i mean, it doesn't work at all. When i try to export a deck, no card is found. I read some issue reports on this site, but in all cases, there are found at least some cards (mostly about 15). But in my case, there isn't found any card. 

I think the problem is my resolution. I have got an old 4:3 Screen and my native Resolution is 1280:1024. When i activate the export, the mouse is somewhere in nowhere. I see that clicks are made, but it clicks not on buttons or something. It tries to activate my friends menu instead ^^.
I tried some other resolutions, even 16:9, but it doesn't help. It seems that the script can't recognize, that there are 2 black bars on top and bottom of my screen, when i take 16:9 resolution

Is there any solution for this problem?

**Comment by Binori** [comment]
Did you test it in Window Mode instead of HS fullscreen?

**Comment by FenrisWolffe** [comment]
I cannot export at all with this build. Tried 1920x all the way to 1020x.  Won't click the cards.

In some matches I sill get errors about missing cards that are in the deck.
