### ISSUE TITLE
Editing 1.0 versions

### ISSUE THREAD

**Issue by Flemeth** [Epix37/Hearthstone-Deck-Tracker#1069]
After creating v2.0 of any deck, is there any way to edit v1.0 without creating a new deck with new stats? The choices allowed by the software are: v2.0 (current - why current?), v2.1, v3.0, save as new 1.0 (why only new? :/). Why can't you edit the old v1.0 same way you do with any new deck? 

I find this very annoying, not even doing deck versions anymore because of that.

Sorry for poor english.

**Comment by culinko** [comment]
Same as #999 I think.
