### ISSUE TITLE
W/L Stats do not update when changing versions of a deck that is not active.

### ISSUE THREAD

**Issue by nicoelayda** [Epix37/Hearthstone-Deck-Tracker#1070]
When you change the selected version of a deck that isn't set as active, the W/L stats on the new interface does not update.

How to reproduce:
1. Select a deck that is NOT set as active and has multiple versions (e.g. 1.0, 1.1, etc.)
2. Select a different version from the dropdown.
3. W/L stats do not update on the main interface.

Version: 0.10.6

**Comment by culinko** [comment]
Currently, your deck needs to be both active and selected to update those stats after switching versions.
