### ISSUE TITLE
A number of crashes and data wipes since latest updates

### ISSUE THREAD

**Issue by OGWilson** [Epix37/Hearthstone-Deck-Tracker#1071]
I really think you should take more time on each update and make sure it's more stable than anything. The past couple of updates have caused a ton of crashing and other bugs. My latest crash resulted in my entire stats, decks and settings being wiped clean as if I just downloaded the app for the first time.

I can provide a log if needed, but didn't know where else to put my criticism. Perhaps try and test more before each update, love all the features but it's getting so complex that you can't keep up with all the bugs.

**Comment by Epix37** [comment]
HDT creates daily backups you can find at "%AppData%/HearthstoneDeckTracker/Backups". So getting your stats/decks back should be possible. 

Also while I understand your frustration and I'm sorry for any problems the updates cause, v0.10.4 was released a beta version and had no new reported bugs in over 24 hours. There is only so much testing I can do.
