### ISSUE TITLE
Bug: Playing Gang Up frequently causes deck not found error

### ISSUE THREAD

**Issue by shikaku2** [Epix37/Hearthstone-Deck-Tracker#1072]
NEW1_004:2;EX1_134:1;EX1_278:1;EX1_049:2;EX1_145:2;EX1_050:2;EX1_124:2;FP1_009:2;FP1_030:1;FP1_012:2;GVG_069:2;GVG_121:1;CS2_072:1;EX1_144:2;EX1_581:2;BRM_028:1;BRM_007:2;EX1_129:2;

This deck when played frequently causes deck not found error probably due to Gang Up.

**Comment by Epix37** [comment]
Seems to be working fine now (v0.10.10)
