### ISSUE TITLE
Stats displays active deck, not selected deck

### ISSUE THREAD

**Issue by GiggliG** [Epix37/Hearthstone-Deck-Tracker#1073]
~~The stats displayed in the stats form are always those of the ACTIVE deck, while the TITLE on the stats form shows the currently selected deck. When you click another deck, the title changes but the stats don't. This is confusing.~~

~~I believe the stats should display the currently selected deck not the active deck.~~

Never mind! This was an PEBKAC error. It's working as intended! (Not the first time those filters have caught me out.)

**Comment by dvide** [comment]
I believe the problem is just with the Games & Statistics menu item. I think when you click it, it sets the stats context to the active deck, not the selected deck. Changing the selected deck after the stats window is already open changes the stats context to the selected deck, as is expected.

**Comment by GiggliG** [comment]
Yes, despite my crossing out my earlier reportm, there is a bug here. I think i've identified it:

When you first open the stats screen, it always shows the stats of the currently ACTIVE deck, not the SELECTED deck. However, the title on the form is that of the selected deck.
If, while the stats screen is open, you click i the deck list to change selected deck, the stats does update with the correct stats.

**Comment by Elitesparkle** [comment]
Confirmed.

I've just noticed the bug and I was going to report it.
