### ISSUE TITLE
Proposal to refresh the deck tracker icon

### ISSUE THREAD

**Issue by CobraA1** [Epix37/Hearthstone-Deck-Tracker#1074]
Hey, I noticed the UI has been evolving over time, including a recent complete overhaul. IMO the old icon now looks a bit out of place with the new skins.
 
So, I thought I'd take the opportunity to propose a refresh of the icon. I've come up with a few possible alternatives, and I'm open to any feedback and ideas. I drew some inspiration for the rounded icons from the HearthStats icon set.
 
I will note that on some monitors a pure white could be quite bright, so it's probably a good idea to continue to consider alternative color combinations for the UI.

Here's a link to an Evernote note with some possible alternatives:
 http://www.evernote.com/l/AAEd_1EjBoRMo5JEjQQupFN6868JsaNiEXQ/

**Comment by andburn** [comment]
I think a new icon would be cool, and a revamped splash screen too maybe. I like these two 
![alt3](http://i.imgur.com/BLhr7mi.png) ![alt4](http://i.imgur.com/RF60W7W.png)
They could also work inverted I think.

**Comment by CobraA1** [comment]
It wouldn't show up very well in the forums with a white background, but an inverted icon would definitely work with some color themes. I'm not at my PC right now to check with all of the themes, and those are just rough drafts anyways. 

As far as the splash screen goes, I think that was put together by Epix, so that's up to him. I could try to come up with something, though.

The only thing I wouldn't want to do is to create an icon for each color theme. I have to create several sizes of the icon, and the smaller sizes of the icon require some tweaking and some pixel art to look good. That would just multiply the time it takes to create the icon.

**Comment by Epix37** [comment]
In general, yes, a new icon would be awesome! I tried all of them and they all look a bit awkward though. Maybe just the "icon" (black or gray), without a background?

As far as the splashscreen goes, feel free if you have any ideas. 

And I agree having icons for each accent color is a bit too much :).

**Comment by CobraA1** [comment]
Back on my PC.

Here's one without any background:

![alt6](https://cloud.githubusercontent.com/assets/8573502/8284631/8a253b48-18c3-11e5-9f5a-f5be7918647a.png)

Making it white and partially transparent gives me this:

![title bar test 1](https://cloud.githubusercontent.com/assets/8573502/8284715/04da693a-18c4-11e5-8be8-82c6b9e31216.png)

I've updated the Evernote note with a more, although there are some that are impossible to see against a white background.

**Comment by Epix37** [comment]
This looks great! 
MahApps allows to set the title bar icon separate from the tray icon, so I can just generate the one in the titlebar directly from the path which should make it a bit cleaner (its a bit pixelated for me).

For the tray one, either this one in full opacity white or maybe with some sort of background? I'm not sure.

**Comment by CobraA1** [comment]
" which should make it a bit cleaner (its a bit pixelated for me)"

Oh, I'll definitely clean it up before making the final icon :). What size icon do you want in the title bar? Should it be an .ico file like the others, or would a .png work fine as well?

**Comment by Epix37** [comment]
Oh, what I meant is: you can just export the title bar icon as a xaml path.

**Comment by CobraA1** [comment]
The mockup was created in the GIMP; I don't have any development tools installed that could export a XAML path.

**Comment by Epix37** [comment]
Ah okay. The last icon was a vector iirc? That's where the idea comes from. A png will do just fine then!

**Comment by CobraA1** [comment]
Yeah, I'm using Inkscape to create the vector images with.

. . . you know what? Looking at the save options, I do have an option for XAML. I take that last statement back, heh.

**Comment by CobraA1** [comment]
Okay, I've created the new icon. Easier than expected this time, once I sat down to actually do it. The only size that needed special treatment was the 16x16 version of the icon, but that's to be expected as 16x16 is such an incredibly small size to work with. I decided to remove the "spikes" for that size.

The file includes:
* The source .SVG files.
* The new icon.
* The 16x16 version of the icon for the system tray.
* A "ghostwhite" XAML version, which has white as the base color for dark accents.
* A "ghostblack" XAML version, which has black as the base color for light accents.

[You can find the file here, on Dropbox.](https://www.dropbox.com/s/by8i095gxfyc5yw/hearthtrack_v2.zip?dl=0)

**Comment by Epix37** [comment]
awesome! thanks
