### ISSUE TITLE
Active deck indicator on deck items not updated properly if you change class view

### ISSUE THREAD

**Issue by dvide** [Epix37/Hearthstone-Deck-Tracker#1075]
To recreate: Click the mage class to only show mage decks, then set a mage deck as the active deck. Now click the paladin class and set a paladin deck as the active deck. Now click back to the mage class. It should still say 'active' on the mage deck that you chose earlier.

**Comment by FishermanHS** [comment]
I'm having pretty much the exact same problem after last patch.

**Comment by culinko** [comment]
Also if you had active deck before going to class tabs, that one is still marked as "active" as well. So if you had active priest deck before going into mage and paladin tabs, when you come back to "All" tab, there will be 3 decks marked as "active", priest deck, mage deck and paladin deck.

![active-decks](https://cloud.githubusercontent.com/assets/11700272/8131465/b5d13144-111a-11e5-9734-1efa243fe368.png)

**Comment by evirae** [comment]
I am also having this issue; it's also not changing "active deck" manually when I choose another. This has led to many games where the overlay has shown as the cards were drawn and the W/L/etc stats were not recorded at all.

**Comment by pbh1963** [comment]
I am having the same issues as evirae
