### ISSUE TITLE
On startup, active deck is set to the last selected deck

### ISSUE THREAD

**Issue by dvide** [Epix37/Hearthstone-Deck-Tracker#1076]
Maybe this is intentional but I think it should be changed. When you open HDT, the active deck that is set is not the one you had active when you closed HDT, but the one you had selected. Perhaps the config file should store both the current selection and the active deck separately, and restore both respectively. Or just save and restore the previously active deck and then also select it.

**Comment by maiklohse** [comment]
My problem is similar but in that the tracker does not switch to a new deck at all unless I select the deck I want to use next, then close the tracker and restart it
