### ISSUE TITLE
Not able to switch "Active Deck" without closing out and restarting HDT

### ISSUE THREAD

**Issue by FishermanHS** [Epix37/Hearthstone-Deck-Tracker#1077]
So after the last patch, my HDT refuses to switch decks without closing the program and restarting it.

Here is a picture of what I mean: http://i.imgur.com/AMgEB4q.png

In this picture you can see that I have the Hunter deck named "Xixo Hunter" highlighted, yet the Mage decl "Zhandaly Aggro-Tempo" is still highlighted and is still set as my "Active Deck" down at the bottom. The only way for me to set a new deck as "Active Deck" is to select the deck I want, close the program, and open the program again. Sometimes I have to do this multiple times for it to work. It's very frustrating, so hopefully you guys can get this fixed. If not, I might end up just switching to another deck tracker.

I'd also like to note that I never had any issues/glitches/bugs happening with the tracker until this last patch, in case that helps at all.

**Comment by culinko** [comment]
Are you clicking the "use" button when you want to switch the deck?

**Comment by ultrababa** [comment]
Thanks for pointing out that 'use' is a button!
Problem solved.

**Comment by FishermanHS** [comment]
Where is the use button? I do not see it.

**Comment by wlfbck** [comment]
Found this issue while searching on how to set a deck as active. The use button is really easy to miss^^ It would be great if you could add the activate to the rightclick-context-menu too :)
