### ISSUE TITLE
Using a deck without selecting it first

### ISSUE THREAD

**Issue by culinko** [Epix37/Hearthstone-Deck-Tracker#1078]
There is an issue that if you have selected a deck with different deck versions than the one you want to use, the versioning on right side will adjust to the deck you click to use.

Two examples:

- I have no deck set as active, i have selected my Oil Rogue deck 1.3. I click use on my Tempo Mage 1.2. The deck on the right changes to Oil Rogue 1.2. Also there is only 1.0, 1.1 and 1.2 from the dropdown (because Tempo Mage doesn't have 1.3). The way to fix it is to click on another deck and click back to Oil Rogue and the 1.3 will appear in the dropdown.

- It also works the other way around. I have selected Tempo Mage 1.1 and click use on Oil Rogue 1.3. It will change the selected deck Tempo Mage to 1.3 (1.2 on deck overlay, but there is up to 1.3 in the dropdown).

Proposed behavior (two options, I prefer the first one):
- If you click use on some deck, also select that deck.
- Maintain the selected version on selected deck and don't take the dropdown versioning from active deck.

I found this issue by testing stuff in #1070.

**Comment by culinko** [comment]
The incorrect versioning still occurs when switching decks.

- Active and selected Oil Rogue 1.3. Clicked on USE on Combo Druid 1.1. Oil Rogue deactivated and deselected, but switched to 1.1.
- Active and selected Combo Druid 1.0. Clicked on USE on Oil Rogue 1.3. Combo Druid deactivated and deselected, but switched to 1.1.

This does not happen when selecting the desired deck before activating it.

**Comment by culinko** [comment]
@Epix37 Could you reopen this, please? Thanks.

**Comment by Epix37** [comment]
fixed now!

**Comment by culinko** [comment]
Great, thanks!
