### ISSUE TITLE
Automatic deck tracker

### ISSUE THREAD

**Issue by HowIsYourMoM** [Epix37/Hearthstone-Deck-Tracker#1081]
Hello,i wonder how can i make the tracking deck system automatically without doing it manually.Each time i change for example from a mage to hunter,i have to manually add cards then start playing matches.

**Comment by HowIsYourMoM** [comment]
Plus hearthtracker is not showing duplicated cards that i have.Example i am only seeing one fiery war axe on my warrior deck.Seems update didnt fix it.

**Comment by HowIsYourMoM** [comment]
Can you make the opponent decklist movable? and mine too because i cant se my friendlist.

**Comment by dantedog** [comment]
To start with, there is a "unlock overlay" button under settings > overlay > general at the bottom that lets you move things around. The opponent deck window should hide automatically when you open up chat though.

The decks do switch automatically. You will need to add all of the decks one time, however, after that, when you play them, the tracker will switch to the correct deck on its own. If that isn't happening, make sure the check box for "Auto deck selection" (Under main menu) is checked.

**Comment by HowIsYourMoM** [comment]
I play arena a lot so i am drafting constantly,because of that i have to manually create new decks and is cant of complicated.

**Comment by dantedog** [comment]
Have you seen the newish arena plugin?

**Comment by HowIsYourMoM** [comment]
yeah!~
