### ISSUE TITLE
Arena plugin help please

### ISSUE THREAD

**Issue by HowIsYourMoM** [Epix37/Hearthstone-Deck-Tracker#1083]
Hello,i understood the steps of installation but seem not working.Can you please tell me detailed?

I got working deck collections plugin.Help.

**Comment by HowIsYourMoM** [comment]
jesus christ,this is so stressful,i tried everything still not working.The plugin does not detect arena,face heroes,nothing.

**Comment by rembound** [comment]
It is probably a dll error. Check out the end of [Issue 1](https://github.com/rembound/Arena-Helper/issues/12) and [Issue 2](https://github.com/rembound/Arena-Helper/issues/4).

**Comment by HowIsYourMoM** [comment]
It doesnt work man.I really wanna draft good.Can you guys fix this? thanks.
