### ISSUE TITLE
Add archetype detection of your own decks

### ISSUE THREAD

**Issue by anonymous555** [Epix37/Hearthstone-Deck-Tracker#1088]
I already have this working in my sandbox.

1)  The player designates certain decks as archetypes, and gives the archetype a name.  For example, "Handlock"
2) For each of the player's decks, it compares cards against the archetype decks.  The archetype that matches the best, over a certain threshold, is displayed for the player's deck. I also display the number of cards that match the archetype.

The current way I implemented it, the player designates an archetype deck by labeling it archetype_ArchetypeName

One could do even more beyond what I did.   We could go and label decks from prior matches the same way.  It works pretty well, I used the archetype decks designated by tempostorm.

**Comment by anonymous555** [comment]
![archetypes_example](https://cloud.githubusercontent.com/assets/8370128/8152102/ce54ddf6-12cd-11e5-8716-9decab9a080b.png)

**Comment by Epix37** [comment]
Closing in favor of the 2 linked issues.
