### ISSUE TITLE
Turn Timer Assigning First Turn Time to Opponent

### ISSUE THREAD

**Issue by rtucker88** [Epix37/Hearthstone-Deck-Tracker#1089]
The turn timer is assigning your first turn time to your opponent's time. I know this happens when you go first but cannot remember if it happens when going second. I can look into that later today if needed.

**Comment by Epix37** [comment]
Fixed with https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/35a73cfa727423511875123ec84ddfb2342d278b and https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/ae57dc0e33b2fe3b7c7c7f62697b1af95cb373ef.
