### ISSUE TITLE
New Heroes show up incorrectly in game

### ISSUE THREAD

**Issue by Potaetoe** [Epix37/Hearthstone-Deck-Tracker#1098]
Don't have a screenshot atm, but was facing a hunter with the Alleria hero and it said it was a paladin deck. If it happens again I'll post a screenshot.

**Comment by Potaetoe** [comment]
http://imgur.com/v2k7O53

Seems to happen with Medivh to. Just as a note the last match I had before the new heroes was Paladin. So It seems it just results to last played hero. Also no records seem to have been made in the tracker for these matches.

**Comment by fmalk** [comment]
At least for me, I can confirm the bug with new Heroes' classed being shown incorrectly, but when exported to HearthStats it is recorded as the correct class.

**Comment by Ardulac** [comment]
I had the same problem with Medivh, and it stopped the secret overlay from activating.

**Comment by fmalk** [comment]
@Ardulac +1
Had exactly the same problem with his secrets.

**Comment by andburn** [comment]
Confirming this too.

The new hero's have new ids:
Jaina is `CardID=HERO_08` and Medivh is `CardID=HERO_08a`
so the tracker is treating them as unknown. Its easily fixed.

I'm guessing @Epix37 is away atm, so I'm sure all the new patch problems will be sorted out when he returns.

**Comment by fmalk** [comment]
@andburn I was trying to look at the code to suggest a quick fix, that seems to be it, I haven't look at game logs to see which ID they were assigned.
