### ISSUE TITLE
Request: Filter stats by server/region

### ISSUE THREAD

**Issue by 305jeff** [Epix37/Hearthstone-Deck-Tracker#1107]
Hi! Thanks for all your hard work.

When looking at my stats, I often want to remove the EU server and only look at NA stats. Can you add a filter for this? I play only ladder on NA and I play just to complete quests on EU (also on ladder)...so the stats have different meanings.

Thanks again!

**Comment by culinko** [comment]
#692 is talking about some new filters.

**Comment by Epix37** [comment]
closing in favor of #692
