### ISSUE TITLE
cant set hearthstone path

### ISSUE THREAD

**Issue by meetthepete** [Epix37/Hearthstone-Deck-Tracker#1108]
Hey,

my problem is, that i cant set the hearthstone path.
when i click on "set hearthstone path", nothing happens.
i installed Hearthstone on my secondary hard drive on E:\...
hope someone can help me out

meetthepete

**Comment by Epix37** [comment]
You can manually set the folder in the config.xml file found in "%AppData%/HearthstoneDeckTracker" (Win+R, paste). Look for `<HearthstoneDirectory>...</HearthstoneDirectory>`.

Setting the path from the GUI will hopefully properly work with the next update.

**Comment by meetthepete** [comment]
Thanks for your answer, but there's a problem. I filled the line with:
<HearthstoneDirectory>...</D:\Spiele\Battle.net\Hearthstone\Hearthstone Deck Tracker>
and if i start the decktracker after that, it just resets and the program says to me, that the hearthstonepath wasnt found..

**Comment by andburn** [comment]
You need to do it like this:
```
<HearthstoneDirectory>D:\Spiele\Battle.net\Hearthstone</HearthstoneDirectory>
```

**Comment by Epix37** [comment]
Let me know if it works with the latest update
