### ISSUE TITLE
Reflect the new reduced turn timer

### ISSUE THREAD

**Issue by rrwoods** [Epix37/Hearthstone-Deck-Tracker#1110]
[Apparently](http://www.reddit.com/r/hearthstone/comments/3agk6v/turn_time_has_been_reduced_from_90_to_70_seconds/), Blizzard reduced the turn timer to 70 seconds.  If this is in fact the case, HDT's timer widget should reflect that now.

**Comment by culinko** [comment]
They haven't reduced the timer since beta. The turn timer is 75 seconds + slush time.

Also, there is already #1007 covering this issue :)
