### ISSUE TITLE
First two cards.Wrong Export

### ISSUE THREAD

**Issue by clemson81** [Epix37/Hearthstone-Deck-Tracker#1111]
I use polish version of Heartstone and in program option of course I switch  language to polish.In some decks,for example Mage and Warrior first two cards are wrong exported....for mage it is always "Mirror Image" no meter what i have in deck list.

**Comment by andburn** [comment]
Probably the same problem as #1091, #1106 and #1094. Should be fixed in next update.

**Comment by Epix37** [comment]
Either what @andburn said, or try running the importing setup again via `options > tracker > importing > set up contructed importing"
