### ISSUE TITLE
Can't Import from Hearthpwn.com anymore?

### ISSUE THREAD

**Issue by MarineKingAizen** [Epix37/Hearthstone-Deck-Tracker#1112]
Hi, I was able to import decks from Hearthpwn until just recently. Now it gives me this error : ERROR could not load deck from specified url.

Please advise.

**Comment by NukerX** [comment]
I am seeing the same issue.

try this url: http://www.hearthpwn.com/decks/260386-hybrid-druid-is-new-meta-combo-taunt

**Comment by Epix37** [comment]
will be fixed with the next update

**Comment by zminin** [comment]
thanks!
