### ISSUE TITLE
Random Card Icons Missing in Deck Builder

### ISSUE THREAD

**Issue by mvordeme** [Epix37/Hearthstone-Deck-Tracker#1115]
This is not serious, just a little inconvenient. When I open the deck builder, there are always random card icons/images missing in the rightmost column with the complete list. As soon as I add a card to the deck, the icon is displayed.

**Comment by andburn** [comment]
I came across something similar today too, in the left deck pane after an import from web.
![Missing Card Images](http://imgur.com/d5Tw6gS)
I wasn't able to reproduce it to see what might be causing it, though.

**Comment by culinko** [comment]
I think it's similar to #757 and related to #830 and #898. It also happens quite often in Collection Tracker (plugin).

**Comment by mvordeme** [comment]
Whoops. For some reason, I didn't find those issues when looking for them. That's exactly what it looks like, just in a different part of the deck tracker.

![Uploading DeckBuilder.png…]()

This can be marked as a duplicate, then.
