### ISSUE TITLE
Feature: Option to Include Overload in Mana Curve

### ISSUE THREAD

**Issue by mvordeme** [Epix37/Hearthstone-Deck-Tracker#1116]
When building a Shaman deck, mana cost is only half the truth. Any overload will be missing from your mana budget next turn. I was wondering whether it might be meaningful to have some kind of gross mana curve which includes overload. Maybe there is a better representation than that, e.g. a separate overload curve. Suggestions are appreciated.

**Comment by chaosjockey** [comment]
I've always wondered why this isn't a current feature.

**Comment by Epix37** [comment]
Added overload to the manacurve selection now:
![screenshot 2015-08-11 15 53 27](https://cloud.githubusercontent.com/assets/7737910/9199581/89245704-4043-11e5-98a7-e8476cac9479.png)

In addition it now also includes a option to display the mechanics breakdown for the deck:
![screenshot 2015-08-11 15 53 40](https://cloud.githubusercontent.com/assets/7737910/9199582/8a23d242-4043-11e5-9591-ee4232078938.png)

**Comment by mvordeme** [comment]
This is awesome. Thank you.
