### ISSUE TITLE
Unable to set game path at all

### ISSUE THREAD

**Issue by Beo37** [Epix37/Hearthstone-Deck-Tracker#1119]
Hello there,

Can't set game installation path through the HDT program nor via editing config.xml. Upon editing config the program still says can't find installation and then rewrites the config.xml file to have no installation path.. My games installation is located at G:\@Battle.Net\Hearthstone\ and when I edit the config.xml it reads as < HearthstoneDirectory /> G:\@Battle.Net\Hearthstone\ 

Tried variants of the above to no avail, would appreciate some help. Thx for your time.

**Comment by Epix37** [comment]
The config needs to say `<HearthstoneDirectory>G:\@Battle.Net\Hearthstone</HearthstoneDr>`
