### ISSUE TITLE
Crash on incorrect password

### ISSUE THREAD

**Issue by Denisiums** [Epix37/Hearthstone-Deck-Tracker#1120]
Login crashes if: you try to login with incorrect password(ok), after try to login with empty password(crash).

**Comment by irufus** [comment]
That's one hell of a find:

I have the error output from debug:

An exception of type 'System.InvalidOperationException' occurred in MahApps.Metro.dll but was not handled in user code

Additional information: Operation is not valid due to the current state of the object.
