### ISSUE TITLE
Deck overlay doesnt change when change deck

### ISSUE THREAD

**Issue by FitzcairnHS** [Epix37/Hearthstone-Deck-Tracker#1122]
Hi, when i change my deck it keep the last deck i played even if i change the class for the new match. I need to close completemky HDV and to open it again everytime i change a deck if i want the good one selected.

**Comment by culinko** [comment]
Are you clicking "use" button on the deck?

**Comment by FitzcairnHS** [comment]
I want the deck to be used automatically so i only click on autoselect deck.

**Comment by rayamerica** [comment]
this is happening to me as well. Auto deck selection is on but the decks will not change. I cannot even manually change my decks when I disable the Auto selection.

**Comment by Anirosa119** [comment]
same not sure what to do

**Comment by andburn** [comment]
I think by default the auto selection feature will only select a deck if no other is possible. For example, if you have *Face Hunter*, *Midrange Hunter* and *Hybrid Hunter* in your deck list, when you play with one of those decks - it is difficult for the program to tell them apart. There is an option to make the auto select less strict, go to `Options > Tracker > General` and uncheck *Autoselect deck if only one possible*. This might help.

Personally, I'd recommend just manually selecting your decks by pressing the **USE** text to the right of the deck name.

**Comment by andburn** [comment]
I had another look at this, and it seems you need to have a deck set as [Active](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#active-deck), for the auto select to work. Maybe give that a try.

**Comment by FenrisWolffe** [comment]
"and it seems for auto-select to work you still need to have a deck set as Active. "

That defeats the purpose of auto-select. Imho, that is the most important bug/broken feature, instead of icons and color schemes.

**Comment by andburn** [comment]
Well, all I know from the testing I have done is that with **no** deck set as *Active* (the same thing as selecting *Use No Deck*) the auto-select mechanism doesn't kick in. But, once **any** deck is set as *Active* then the auto-select works and will reset the deck based on whats been played. I'm sure this won't be the solution for everyone. I'm merely putting it out there in the hope that it may help some people, while we wait for a fix.
