### ISSUE TITLE
Arena Importing Imports all choices given during Arena Draft.

### ISSUE THREAD

**Issue by RavenousSix** [Epix37/Hearthstone-Deck-Tracker#1124]
When I try to Import a new Arena game, it imports all choices given during Arena Draft. Lets say I had to choose between 3 cards, it will import all 3 in the deck and make a 68 card deck.

**Comment by Scheigy** [comment]
Hello,

I have the same problem, but for instant, the trick is:
- do it as usual, have you're 68 cards decks and then cancel it
- do the same protocol (in HS, open arena draft page, go back to main menu and choose Import from Game: Arena in HSDT)

Then you have the version of the deck as you would have seen it before.

**Comment by culinko** [comment]
Is this still an issue with the new arena importing method?

**Comment by Scheigy** [comment]
The new arena importing method is easier than before, because it will automatically detect your deck after finishing your draft and ask you if you want to save it.
Plus there's no more problem like 68 cards in deck or something !
