### ISSUE TITLE
Suggestion: skip animations

### ISSUE THREAD

**Issue by gendalv** [Epix37/Hearthstone-Deck-Tracker#1126]
add options to skip certain kinds of animations
 when the game is loaded - greetings and card movements when swapping cards.
 delays before attack because of animation of card summons/buffs/etc

**Comment by GiggliG** [comment]
Are you suggesting skipping animations in the hearthstone client? That's not possible.

**Comment by Epix37** [comment]
You can sort of skip some animations by clicking. I try to avoid adding any interaction with the game during actual gameplay though.
