### ISSUE TITLE
Tracker not coloring cards in hand properly

### ISSUE THREAD

**Issue by emzero** [Epix37/Hearthstone-Deck-Tracker#1127]
I've just installed the Deck Tracker and it seems to be working fine except for coloring the cards in my hand.

Whenever I'm about to draw a new one (actually, during the opponent's turn) I can see the card name color changing to orange, but when my turn starts it justs mark it as "not in the deck" but the name color is back at white.

According to this video: https://www.youtube.com/watch?v=WvA1fVB1CJQ the tracker is able to track and color the cards in the hand, unless that's from an old version and it doesn't work like that anymore.

Here's a screenshot of cards in hand not being colored properly:

![sshot](http://i.imgur.com/CdqvnfG.png)

**Comment by andburn** [comment]
I think you have to enable that particular option, go to `options > overlay > player` and check *Highlight cards in hand*.
The overlay is very customizable, you should play around with all the different options and see what you like best.

**Comment by emzero** [comment]
I feel like an idiot. I missed that completely.

Thanks and sorry!
