### ISSUE TITLE
Bug: When another game is running, the overlays do not work

### ISSUE THREAD

**Issue by scooter3** [Epix37/Hearthstone-Deck-Tracker#1129]
I noticed this while I had Kerbal Space Program running in a full screen window and Hearthstone running in a regular window. The deck, timer, etc. overlays showed up on KSP rather than Hearthstone.

**Comment by CobraA1** [comment]
Try going to options -> Settings and toggling the "Advanced window search" checkbox.

**Comment by scooter3** [comment]
That option is already checked.

**Comment by Epix37** [comment]
Unchecking it is what should fix it.
