### ISSUE TITLE
arena decks won't save

### ISSUE THREAD

**Issue by curtains20** [Epix37/Hearthstone-Deck-Tracker#1136]
It used to work a few weeks ago but now no matter what, I enter my arena deck, hit save and it just dissapears. This has been a problem for a few weeks. Any help greatly appreciated, thanks!

**Comment by andburn** [comment]
This is a bit obvious, but just to be sure - make sure *Arena* or *All* is is selected above the deck list, so the arena decks are shown. If its not that, try an arena deck again sometime and if its doesn't work get the log using [this](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues) procedure and post the link here.

**Comment by curtains20** [comment]
I still have been unable to use decktracker for months, although haven't tried again until today. Here is the pastebin url:

http://pastebin.com/BHLfgzj7

Note that it is not in the arena/all section. Everything worked fine and then after one of the updates just stopped recognizing any decks that I enter no matter what. I just press save and it ignores me and the save option dissapears from the top of the screen.

**Comment by riQQ** [comment]
How are your filters set (Main -> Sort / Filter)?

**Comment by andburn** [comment]
The deck is being saved according to the log. So It sounds like what @riQQ  said, some more info in [FAQ](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#decks-i-create-are-not-showing-up-or-disappear-when-i-apply-a-tag). 

This seems to have happened to a few people lately (#1180, #1169) some Filters and/or Tags have been enabled without them ever touching it.

**Comment by Epix37** [comment]
Working on correcting tags when a new deck is saved right now.

**Comment by curtains20** [comment]
It worked once I turned the filter off of Arena on to All. Does that make any sense? But when I set it back to Arena, it stops working.
