### ISSUE TITLE
Crash when Export to clipboard

### ISSUE THREAD

**Issue by GiggliG** [Epix37/Hearthstone-Deck-Tracker#1137]
Whenever I try to export a deck using the Names to Clipboard option, HDT crashes. 

This isn't a new bug. It happened a version or two ago, but I'd forgotten to report it, till I tried it again tonight.

**Comment by Epix37** [comment]
Not sure what the reason behind the problem actually is, but it should at least no longer crash now.

**Comment by GiggliG** [comment]
I confirm this is fixed.
