### ISSUE TITLE
Only drawn cards showing in player display

### ISSUE THREAD

**Issue by rbhollow** [Epix37/Hearthstone-Deck-Tracker#1139]
I am having an issue where only my drawn cards are showing up on my player display.  I have looked through all the settings and can't figure out what's happening.  I think I've had this happen before and checking the "Auto Deck Selection" box under the "Main" tab fixed it but it's not doing anything this time. Thanks for any responses.

**Comment by maiklohse** [comment]
Same thing here - but my tracker also keeps saying "Active Deck : None" on the bottom and I can't figure out a way to make a deck "active" manually......

**Comment by Epix37** [comment]
You have to click "use" on a deck to set it as active.

**Comment by 7tyson7** [comment]
Same thing here i have no idea what is going on.if you find a way to fix it plz write here. Thank you.

**Comment by 7tyson7** [comment]
and my tracker keep saying "Active Deck : None"too.Where is  "use"??

**Comment by andburn** [comment]
You need to press the word **use** to the right of the deck name

![hdt-use](https://cloud.githubusercontent.com/assets/5419653/8484163/09e3392a-20ee-11e5-8a7c-796165bbfd1e.png)

That will select the deck you want to use, it is then marked as the **active** deck

![hdt-active](https://cloud.githubusercontent.com/assets/5419653/8484199/39043c9a-20ee-11e5-9dca-6866ae7009cb.png)

**Comment by 7tyson7** [comment]
Thank you for your advice.I found it.but we have to press "use" each game?We cant "AUTO DECK SELECTION"??

**Comment by andburn** [comment]
It might be the same problem as  #1067
