### ISSUE TITLE
Add stats manually

### ISSUE THREAD

**Issue by CorentinMic** [Epix37/Hearthstone-Deck-Tracker#1142]
Hey,

I play on both tablet and PC and I use Hearthstone Deck Tracker on PC.
Is it possible to manually add games results I have played on tablet (at least Victory or Defeat) to keep a coherent ratio on decks ?

Thank's

**Comment by andburn** [comment]
You can add a game manually once you have an active deck. Go to the *Statistics* page and select *Deck* and then *Games*, press the *Add New Game*

![add_game](https://cloud.githubusercontent.com/assets/5419653/8503516/47ed0e2e-21b8-11e5-8af1-ad0980bb5a4b.png)

**Comment by CorentinMic** [comment]
I didn't see that ! Thank you !
