### ISSUE TITLE
No Stats : Stats is not saved

### ISSUE THREAD

**Issue by everchump** [Epix37/Hearthstone-Deck-Tracker#1143]
when i exit the HDT app before exiting the HS client，the stats is not saved。

the HDT replays log is saved ,but the deck stats is cleaned up , is it a bug？

**Comment by everchump** [comment]
Now，when i restart the HDT app，the STATS IS Gone，it display "No STATS".

**Comment by andburn** [comment]
Follow these [steps](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues) to upload your log files. Also, you could use the same steps to upload `config.xml` and `DeckStats.xml` which are located in the *AppData* folder too. Copy the links here and I'll see if I can help.

Same problem as #1144

**Comment by andburn** [comment]
Make sure that when you are playing, you have an *Active* deck. See [here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ) for more.

**Comment by everchump** [comment]
![2015-07-11-001](https://cloud.githubusercontent.com/assets/7987245/8632714/f1c30d6e-27d9-11e5-86f0-464190f52a74.png)
Before restart HDT,the STATS is 9:1.

The LOG:http://pastebin.com/DEQ1Sen8

Deck Stats: can't find  ，just deckstatsbaup.xml

config:http://pastebin.com/F4sgRGYP

After restart HDT, The STATS is Gone.
![2015-07-11-002](https://cloud.githubusercontent.com/assets/7987245/8632745/dad5f73c-27da-11e5-9009-ec61ba040bbc.png)

the log file:http://pastebin.com/3L0tN9KR

Deck Stats:http://pastebin.com/L2sDXRrL

config：http://pastebin.com/xaSS3u6v

**Comment by quark-zju** [comment]
I have this issue as well.

**Comment by Epix37** [comment]
Do you have this issue with all deck/classes/modes?

**Comment by everchump** [comment]
yes，all decks/classese/modes.

I del all HDT files and reinstall HDT，Still No stats and can't save stats.

**Comment by Epix37** [comment]
Any change if you disable `options > tracker > settings > save data in appdata`?

**Comment by everchump** [comment]
i disable the option and restart HDT.

play a game, before restart HDT, the stats is 0-1.

after restart HDT,the stats is gone, "No Stats" again.

so it doest work.
