### ISSUE TITLE
Can't get any game stats to record with any decks

### ISSUE THREAD

**Issue by Extattic** [Epix37/Hearthstone-Deck-Tracker#1144]
I downloaded the client earlier this evening and have been learning my way around it. I have created my decks and been familiarizing myself with the in game overlay. Only problem is that I don't have any stats getting recorded in the client. I tried playing multiple decks in both casual and ranked mode to no avail. The curious thing is that I can view the replays, just not win/loss stats. I've checked the options > tracker > stats portion and made sure that ranked, arena, casual, and friendly are all ticked off.

**Comment by Jumiric** [comment]
I have the same problem. The switch to the new program has been nothing but trouble.

**Comment by andburn** [comment]
Guys, follow these [steps](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues) to upload your log files. Also, you could use the same steps to upload `config.xml` and `DeckStats.xml` which are located in the *AppData* folder too. Copy the links here and I'll see if I can help.

**Comment by andburn** [comment]
Make sure that when you are playing, you have an *Active* deck. See [here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ) for more.
