### ISSUE TITLE
Can't correct winrate if deck was not in use

### ISSUE THREAD

**Issue by MMcCormick** [Epix37/Hearthstone-Deck-Tracker#1148]
I'd like to fix the win rate for my arena runs. For the first game or two, I won't always have HDT running, so some runs have fewer wins or losses than they should, and this affects my HearthStats. Is there a fix for this I'm not aware of?

**Comment by andburn** [comment]
You can add a game manually, select the arena deck you want to add games to. Then go to the Statistics page and select Deck and then Games, press the Add New Game button

![add_game](https://cloud.githubusercontent.com/assets/5419653/8503516/47ed0e2e-21b8-11e5-8af1-ad0980bb5a4b.png)

That should correct your win rate.

**Comment by MMcCormick** [comment]
Great, thanks!
