### ISSUE TITLE
Tavern Brawls show up as game mode none

### ISSUE THREAD

**Issue by anonymous555** [Epix37/Hearthstone-Deck-Tracker#1149]
It would be nice to show the tavern brawl game type, and allow it to show up in the game mode filter

**Comment by mvordeme** [comment]
... and, of course, it would be nice to have a new deck type "Tavern Brawl". But I must say that importing Tavern Brawl decks from Hearthstone works almost flawlessly, already. Kudos :+1:

**Comment by andburn** [comment]
I've added "Brawl" as a game mode, it should be available in @Epix37's next update. I didn't think there was any need to have a "Tavern Brawl" deck type, as it seems like the Brawl decks aren't going to be any different then constructed. Adding a "Tavern Brawl" tag for decks you want to use seems better.
