### ISSUE TITLE
Adding games doesn't effect stats on main page

### ISSUE THREAD

**Issue by Confirm4Crit** [Epix37/Hearthstone-Deck-Tracker#1150]
Adding a game manually doesn't seem to effect the w-l  or win percentage, even though the stats seem fine on the stats page. 
![stats2](https://cloud.githubusercontent.com/assets/3483618/8514638/14bbe164-2362-11e5-96ff-1f2325cb120c.PNG)
![stats3](https://cloud.githubusercontent.com/assets/3483618/8514640/14c09fe2-2362-11e5-99b4-15a894259318.PNG)
![statsjpeg](https://cloud.githubusercontent.com/assets/3483618/8514639/14bda4ea-2362-11e5-8c60-ae3e27ffb099.PNG)

**Comment by Confirm4Crit** [comment]
When I reopened the program, it was all good.

**Comment by GiggliG** [comment]
I have noticed this too. It seems the stats dont update on the deck view page, until you cause them to update by changing the view. If you are looking at a druid deck for instance, click the All button and then come back to Druid, and the stats will have updated.

**Comment by Epix37** [comment]
Should be working with v0.10.9
