### ISSUE TITLE
How to get deck tracker to show you your remaining cards rather than what you've drawn

### ISSUE THREAD

**Issue by Adastam** [Epix37/Hearthstone-Deck-Tracker#1151]
Know this might sound silly but I've gone through all the settings and can't for the life of me figure out How to get deck tracker to show me my remaining cards in my deck. All I can see is the cards I have currently drawn for my game.

**Comment by andburn** [comment]
It sounds like this problem in the [FAQ](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#only-drawn)

**Comment by endoflaven** [comment]
Make sure that you have your deck active, by clicking the word 'Use' on the Deck screen so that it toggles to 'Active'

**Comment by Anrich93** [comment]
How do I deactivate the deck?

**Comment by culinko** [comment]
Just activate another deck or click Main->Use no deck.
