### ISSUE TITLE
Decks do not save

### ISSUE THREAD

**Issue by khdou** [Epix37/Hearthstone-Deck-Tracker#1153]
After the most recent update, I cannot save decks (constructed, did not test arena). I tried saving decks via the import option and I tried by just manually creating new deck and saving. It gets to the "name your deck" screen and when I click Set, the decks are not showing up. I've clicked ALL and ALL classes so I know that's not it. I've uploaded my log file here: http://pastebin.com/YKMJNR5z

**Comment by andburn** [comment]
There are no errors in the log file that I can see. The Druid deck you created called "test" should've been saved and then uploaded to hearthstats successfully. You could check hearthstats to see if it was added there.
For the tracker, have a look at SORT/FILTER and QUICK FILTER under Main - make sure they're are set to ALL too.

**Comment by khdou** [comment]
Ah the filters were what was messing it up. Thanks for that!

**Comment by Goremaker** [comment]
I have the same problem. Importing decks from heartharena.com fails. After import when saving it just wont show up in HS. tried to reinstall then it worked for 1 game. Ive tried to delete all decks in deck tracker and start over without success.

**Comment by Goremaker** [comment]
nevermind, I found out that I had to press "use" on the deck, after reading more in the forum. That button should be more visible :)
