### ISSUE TITLE
Opponent card list does not update properly when a card is burned instead of played

### ISSUE THREAD

**Issue by j4mmyd0d93r** [Epix37/Hearthstone-Deck-Tracker#1154]
I do not know whether this feature is intentional or is a bug but if the opponent burns a card instead of playing it, it shows up as a different card than if another version of that card was played in the opponent's card list. For example, I was playing a warrior, he played a fiery war axe and it got displayed correctly in the opponent's card list, further into the game he overdrew by one and a fiery war axe got burned, but in the opponent's card list it had two fiery war axes as different cards instead of the same one twice. Its not a big thing but something to look into. If it's intentional then fair enough I can see why its in the system.

**Comment by culinko** [comment]
It's intentional. You can highlight it if you check the setting in Options/Overlay/Opponent/Highlight discarded from deck.

**Comment by Epix37** [comment]
since v0.11.0: should only show up as separate now if "highlight discarded" is enabled
