### ISSUE TITLE
7 Days To Die triggers HDT

### ISSUE THREAD

**Issue by jemiller226** [Epix37/Hearthstone-Deck-Tracker#1155]
Really weird issue.

Normally the only thing that triggers HDT's deck overlay is Hearthstone...other than 7 Days To Die. If I open that game, HDT overlays my most recent deck on top of the game. I have to close the tracker to get it to go away. (Normally I leave it open all the time in order to avoid forgetting to turn it on.)

The executable is 7daystodie.exe.

**Comment by andburn** [comment]
Go to `Options > Tracker > Settings` and see if *"Advanced windows search"* is checked. Unchecking it is suppose to solve the overlay showing up in other windows.
