### ISSUE TITLE
can't read logs / overlay over cifs

### ISSUE THREAD

**Issue by caldwelljt2** [Epix37/Hearthstone-Deck-Tracker#1156]
I may be trying something impossible, but i cant tell.

in this case i am attempting to run hearthstone on a separate computer (actually via a VM)

ive tried using cifs and shared folders to allow HDT to read the hearthstone. I don't need import/export but i want the overlay to show. i cant get it to show in windows, maybe because it can't see the process or window. is there a force setting?

**Comment by andburn** [comment]
AFAIK, the tracker checks to see if the Hearthstone window is running before it does most things. The overlay won't show the way you are running it.

However, I was  doing something with log files recently and needed to keep Hearthstone open while I was testing things, which got annoying. So, I created a fake hearthstone window to trick the tracker. Assuming you can share the folders from the VM ok, I think this will do what you want.
You can download the fake program [here](https://www.dropbox.com/s/dqijq2yxadtp8lg/FakeHSWindow.zip?dl=0), just run it and the tracker overlay should display in it. Its not transparent though, not sure if that matters.
Let me know how it goes.
