### ISSUE TITLE
Trying to write a plugin. Feedback required.

### ISSUE THREAD

**Issue by VicTT** [Epix37/Hearthstone-Deck-Tracker#1158]
I am trying to write a plugin to calculate the amount of damage a raging worgen can do using other cards in your hand. I am only considering Inner Rage, Cruel Taskmaster, Rampage and other cards present in the classic OTK Warrior deck.
I'm trying to get the damage to display on the overlay in-game. What class handles that? How do I display an arbitrary string somewhere in-game?
I'm looking at Hearthstone_Deck_Tracker.OverlayWindow and I don't see it. Can you post an example, please?
On the same note, it would be great if you could post the code for a sample plugin so that devs could have a starting point. Easy stuff, like:
1) How to mess with the overlay
2) How to check if a card is in your hand
3) Number of mana crystals max/remaining
The easy stuff
And if you have time, you can move on to the bigger stuff..I'd really appreciate any help you can provide with this Epix.
VicTT.

**Comment by andburn** [comment]
I'm guessing Epix probably isn't going to have the time to do this, so I'll help you out as best I can.

You've probably seen the wiki which gives some [info](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Creating-Plugins). The [available](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Available-Plugins) plugins section is also useful as it gives you some other plugins to look at. To be honest there's probably no substitute for just looking through the code, its the best way of understanding how the program works.

So, for what you want to do:

1. You can't access the overlay directly from a plugin. There is a helper method `Hearthstone_Deck_Tracker.API.Overlay.OverlayCanvas` that gives you access to it. You can then add the elements you want to it.
* To get the cards in your hand you need to look at `Game.Entities` and use `Entity.IsInHand` and also make sure the `Entity` is controlled by the player (not the opponent).
* Mana is similar to the cards, except you'll have to look at the tags of the `Entity` directly, the various tags are in `Hearthstone_Deck_Tracker.Enums.GAME_TAG` . Mana is tagged as `RESOURCES`, you also have `MAXRESOURCES` and `USED_RESOURCES`. You get the values from an entity something like this:
```
if (e.HasTag(GAME_TAG.RESOURCES))
    var mana = e.GetTag(GAME_TAG.RESOURCES);
```

Good places to look at this kind of stuff in the HDT code are `Hearthstone_Deck_Tracker.API` and `Hearthstone_Deck_Tracker.Replay`. I made an [example plugin](https://github.com/andburn/hdt-plugin-example) that shows the cards in the players hand in a text block in the middle of the overlay, it should help you get started. Good luck!
