### ISSUE TITLE
use no deck always selected

### ISSUE THREAD

**Issue by Burz14** [Epix37/Hearthstone-Deck-Tracker#1159]
For some reason i can't understand the option -use no deck- is always selected and i cant deselect it. What do i have to do in order to fix this issues?

thanks

**Comment by Burz14** [comment]
any fix for this?

**Comment by andburn** [comment]
You need to select a deck as *Active*, see [here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#active-deck).

**Comment by Burz14** [comment]
thanks man
