### ISSUE TITLE
Import searching for names...

### ISSUE THREAD

**Issue by robertalexstorm** [Epix37/Hearthstone-Deck-Tracker#1161]
I recently noticed while trying to import from hearthstone deck tracker to the game that it was searching for cards that include words like Jared and other such names. Not sure if it's a bug related to the user database or what but I would like it to actually find the cards I have in my created deck.

**Comment by andburn** [comment]
So, I'm not sure if you are saying that your decks aren't being exported into Hearthstone correctly or not. If they're not mention it below.

As for the names, when exporting decks from the tracker into Hearthstone, the names of the artists of the card art are included in the search. This is used to help distinguish cards. For example, if you search for **Mad Bomber** you end up with *Mad Bomber* and *Madder Bomber* - using **Mad Bomber Mike Sass** you get *Mad Bomber* only.

**Comment by robertalexstorm** [comment]
Ah. That's good to know but yes. I actually got two ancestral healing and then it stopped loading. I don't even use ancestral healing in the deck but rather ancestral spirit. Nothing else for my deck loaded. I watched it search for many things but in the end tell me I didn't have the cards.

**Comment by andburn** [comment]
Someone else had a problem (#1162) recently too. If you can give me the info below I might be able to figure it out.

1. how often does it happen, everytime or just sometimes
- are any of the mana crystals selected before the import
- the resolution you are running Hearthstone at
- and is it fullscreen or windowed
- in the tracker options what does it say for the *Speed* value in `Options > Tracker > Exporting` (e.g. *"Fast (40ms)"*)
- a link or screenshot of the deck you are trying to import
