### ISSUE TITLE
Don't work russian language

### ISSUE THREAD

**Issue by giwigiwi** [Epix37/Hearthstone-Deck-Tracker#1163]
when you chose russian language and theh restarting HDT, nothing changing in program,all in english(i'm sorry for mistakes)

**Comment by andburn** [comment]
Unfortunately, the program is not translated into other languages. The cards and their information are, like this:
![untitled-1](https://cloud.githubusercontent.com/assets/5419653/8707745/8c5066b2-2b2f-11e5-9d63-5f88326a52bb.png)

**Comment by giwigiwi** [comment]
will be cool if the program will be translated in other languages. it will be more comfortable than now. Are you need help with this?

**Comment by Epix37** [comment]
Translations *are* planned, there is no ETA currently though.
