### ISSUE TITLE
Error while trying to run on wine-1.7.44

### ISSUE THREAD

**Issue by chriskevini** [Epix37/Hearthstone-Deck-Tracker#1164]
This shows up in terminal whenever I try to run the Deck Tracker with wine:

fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
fixme:mscoree:parse_supported_runtime sku=L".NETFramework,Version=v4.5" not implemented
The entry point method could not be loaded

Any help with figuring this out would be greatly appreciated.

**Comment by riQQ** [comment]
Have you installed .NET Framework 4.5 with wine?

**Comment by chriskevini** [comment]
After finally getting .NET Framework 4.5 running, I get this error when trying to execute the Deck Tracker:

chris@Chris-VAIO:~$ cd Downloads/Hearthstone\ Deck\ Tracker/
chris@Chris-VAIO:~/Downloads/Hearthstone Deck Tracker$ wine Hearthstone\ Deck\ Tracker.exe 
fixme:process:GetNumaHighestNodeNumber (0x33fb88): stub
fixme:thread:SetThreadStackGuarantee (0x33fb6c): stub
err:ntdll:NtQueryInformationToken Unhandled Token Information class 29!
err:ntdll:NtQueryInformationToken Unhandled Token Information class 29!
fixme:advapi:RegisterEventSourceW ((null),L".NET Runtime"): stub
fixme:advapi:ReportEventW (0xcafe4242,0x0001,0x0000,0x000003fe,0x156960,0x0001,0x00000000,0x374e400,(nil)): stub
err:eventlog:ReportEventW L".NET Runtime version 4.0.30319.17929 - There was a failure initializing profiling API attach infrastructure.  This process will not allow a profiler to attach.  HRESULT: 0x800706a9.  Process ID (decimal): 48.  Message ID: [0x2509]."
fixme:advapi:DeregisterEventSource (0xcafe4242) stub
err:ole:CoGetContextToken apartment not initialised
fixme:shell:URL_ParseUrl failed to parse L"PresentationFramework"
fixme:shell:URL_ParseUrl failed to parse L"WindowsBase"
fixme:shell:URL_ParseUrl failed to parse L"System.Xaml"
fixme:shell:URL_ParseUrl failed to parse L"System"
fixme:shell:URL_ParseUrl failed to parse L"PresentationCore"
fixme:nls:LCMapStringEx unsupported lparam 186e48
fixme:advapi:EventRegister {8e9f5090-2d75-4d03-8a81-e5afbf85daf1}, 0x9f4152, (nil), 0x15b3dfc
fixme:shell:URL_ParseUrl failed to parse L"HearthstoneDeckTracker.resources"
fixme:nls:LCMapStringEx unsupported lparam 186e48
fixme:advapi:RegisterTraceGuidsW (0x9f4422, (nil), {e13b77a8-14b6-11de-8069-001b212b5009}, 1, 0x33ebe8, (null), (null), 0x33ebf0,): stub
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._initterm_e, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting
wine: Call from 0x7bc4e590 to unimplemented function MSVCR100_CLR0400.dll._except_handler4_common, aborting

**Comment by chriskevini** [comment]
Through winecfg, I changed my Windows Version to Windows 7 and get a different message: 

Unhandled exception: page fault on read access to 0x00000250 in 32-bit code (0x0578564c).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:0578564c ESP:0033dd18 EBP:0033dd4c EFLAGS:00010246(  R- --  I  Z- -P- )
 EAX:00000000 EBX:01868dd0 ECX:00000000 EDX:01892664
 ESI:01889d44 EDI:0188b3bc
Stack dump:
0x0033dd18:  01889d44 01889a88 015c6a1c c86a0a50
0x0033dd28:  88d2a9ac 00000000 00000000 00000000
0x0033dd38:  00000000 015c6a1c 015b38b4 015b5da8
0x0033dd48:  0188948c 0033dd7c 057852a9 015b5fbc
0x0033dd58:  00000000 00000000 00000000 00000000
0x0033dd68:  00000000 00000000 0188948c 0188948c
000c: sel=0067 base=00000000 limit=00000000 32-bit r-x
Backtrace:
=>0 0x0578564c (0x0033dd4c)
  1 0x057852a9 (0x0033dd7c)
  2 0x0578524b (0x0033dd94)
  3 0x04a9da82 (0x0033f04c)
  4 0x04a97752 (0x0033f09c)
  5 0x04a91da1 (0x0033f0e4)
  6 0x0039a08e (0x0033f118)
  7 0xf72504ea WINPROC_wrapper+0x19() in user32 (0x0033f148)
  8 0xf7250c26 in user32 (+0xa0c25) (0x0033f198)
  9 0xf7253383 in user32 (+0xa3382) (0x0033f1e8)
  10 0xf7214425 DispatchMessageW+0xb4() in user32 (0x0033f2e8)
  11 0x0556bb57 (0x0033f328)
  12 0x0556afb1 (0x0033f370)
  13 0x0556ae16 (0x0033f37c)
  14 0x0556ad86 (0x0033f388)
  15 0x0556ab33 (0x0033f39c)
  16 0x0556a949 (0x0033f3ac)
  17 0x03d837f6 (0x0033f3b8)
  18 0x00b12652 in clr (+0x2651) (0x0033f3c4)
  19 0x00b2264f in clr (+0x1264e) (0x0033f418)
  20 0x00b22e95 in clr (+0x12e94) (0x0033f490)
  21 0x00bd74ec in clr (+0xc74eb) (0x0033f5bc)
  22 0x00bd7610 in clr (+0xc760f) (0x0033f830)
  23 0x00c61dc4 in clr (+0x151dc3) (0x0033fd34)
  24 0x00c61e67 in clr (+0x151e66) (0x0033fd90)
  25 0x00c61f7a in clr (+0x151f79) (0x0033fdd0)
  26 0x00c6416a in clr (+0x154169) (0x0033fe0c)
  27 0x1000f5a3 in mscoreei (+0xf5a2) (0x0033fe48)
  28 0x79007f16 in mscoree (+0x7f15) (0x0033fe58)
  29 0x79004de3 in mscoree (+0x4de2) (0x0033fe78)
  30 0x7b85f653 in kernel32 (+0x4f652) (0x0033feb8)
  31 0x7bc799b0 call_thread_func_wrapper+0xb() in ntdll (0x0033fed8)
  32 0x7bc7c93d call_thread_func+0x7c() in ntdll (0x0033ffa8)
  33 0x7bc7998e RtlRaiseException+0x21() in ntdll (0x0033ffc8)
  34 0x7bc4e8fe call_dll_entry_point+0x7ed() in ntdll (0x0033ffe8)
  35 0xf75d550d wine_call_on_stack+0x1c() in libwine.so.1 (0x00000000)
  36 0xf75d55cb wine_switch_to_stack+0x2a() in libwine.so.1 (0xffe90df8)
  37 0x7bc541e2 LdrInitializeThunk+0x3a1() in ntdll (0xffe90e58)
  38 0x7b865bdd __wine_kernel_init+0xa0c() in kernel32 (0xffe91f78)
  39 0x7bc547a3 __wine_process_init+0x192() in ntdll (0xffe92008)
  40 0xf75d2c70 wine_init+0x30f() in libwine.so.1 (0xffe92068)
  41 0x7bf00fdc main+0xfb() in <wine-loader> (0xffe924b8)
  42 0xf73fca83 __libc_start_main+0xf2() in libc.so.6 (0x00000000)
0x0578564c: movl	0x250(%eax),%eax
Modules:
Module	Address			Debug info	Name (86 modules)
PE	  400000-  7de000	Deferred        hearthstone deck tracker
PE	  b10000- 11a2000	Export          clr
PE	 11b0000- 1283000	Deferred        msvcr110_clr0400
PE	 3cf0000- 3d5e000	Deferred        clrjit
PE	 4a00000- 4a12000	Deferred        nlssorting
PE	 4aa0000- 4b60000	Deferred        presentationnative_v0400
PE	 52e0000- 547d000	Deferred        wpfgfx_v0400
PE	10000000-1007a000	Export          mscoreei
PE	5e0d0000-5e1a4000	Deferred        diasymreader
PE	79000000-7904a000	Export          mscoree
ELF	7b800000-7ba5b000	Dwarf           kernel32<elf>
  \-PE	7b810000-7ba5b000	\               kernel32
ELF	7bc00000-7bcdb000	Dwarf           ntdll<elf>
  \-PE	7bc10000-7bcdb000	\               ntdll
ELF	7bf00000-7bf04000	Dwarf           <wine-loader>
ELF	7ec4d000-7ec5a000	Deferred        libnss_files.so.2
ELF	7ec5a000-7ec66000	Deferred        libnss_nis.so.2
ELF	7ec66000-7ec7f000	Deferred        libnsl.so.1
ELF	7ec7f000-7ec88000	Deferred        libnss_compat.so.2
ELF	7efba000-7f000000	Deferred        libm.so.6
ELF	f609d000-f60c5000	Deferred        mpr<elf>
  \-PE	f60a0000-f60c5000	\               mpr
ELF	f60c5000-f6141000	Deferred        wininet<elf>
  \-PE	f60d0000-f6141000	\               wininet
ELF	f6141000-f6248000	Deferred        comctl32<elf>
  \-PE	f6150000-f6248000	\               comctl32
ELF	f6248000-f647b000	Deferred        shell32<elf>
  \-PE	f6260000-f647b000	\               shell32
ELF	f647b000-f651d000	Deferred        urlmon<elf>
  \-PE	f6490000-f651d000	\               urlmon
ELF	f651d000-f6554000	Deferred        uxtheme<elf>
  \-PE	f6520000-f6554000	\               uxtheme
ELF	f65b0000-f65d4000	Deferred        dwrite<elf>
  \-PE	f65c0000-f65d4000	\               dwrite
ELF	f65d4000-f65f9000	Deferred        imm32<elf>
  \-PE	f65e0000-f65f9000	\               imm32
ELF	f65f9000-f672f000	Deferred        oleaut32<elf>
  \-PE	f6610000-f672f000	\               oleaut32
ELF	f672f000-f67ec000	Deferred        windowscodecs<elf>
  \-PE	f6740000-f67ec000	\               windowscodecs
ELF	f67ec000-f68bb000	Deferred        crypt32<elf>
  \-PE	f6800000-f68bb000	\               crypt32
ELF	f68bb000-f68fd000	Deferred        rsaenh<elf>
  \-PE	f68c0000-f68fd000	\               rsaenh
ELF	f6943000-f69c4000	Deferred        rpcrt4<elf>
  \-PE	f6950000-f69c4000	\               rpcrt4
ELF	f69c4000-f6b00000	Deferred        ole32<elf>
  \-PE	f69e0000-f6b00000	\               ole32
ELF	f6c20000-f6c26000	Deferred        libxfixes.so.3
ELF	f6c26000-f6c31000	Deferred        libxcursor.so.1
ELF	f6c31000-f6c41000	Deferred        libxi.so.6
ELF	f6c41000-f6c45000	Deferred        libxcomposite.so.1
ELF	f6c45000-f6c50000	Deferred        libxrandr.so.2
ELF	f6c50000-f6c5b000	Deferred        libxrender.so.1
ELF	f6c5b000-f6c61000	Deferred        libxxf86vm.so.1
ELF	f6c61000-f6c65000	Deferred        libxinerama.so.1
ELF	f6c65000-f6c6c000	Deferred        libxdmcp.so.6
ELF	f6c6c000-f6c70000	Deferred        libxau.so.6
ELF	f6c70000-f6c92000	Deferred        libxcb.so.1
ELF	f6c92000-f6dc6000	Deferred        libx11.so.6
ELF	f6dc6000-f6dd9000	Deferred        libxext.so.6
ELF	f6dda000-f6df0000	Deferred        dwmapi<elf>
  \-PE	f6de0000-f6df0000	\               dwmapi
ELF	f6df2000-f6e84000	Deferred        winex11<elf>
  \-PE	f6e00000-f6e84000	\               winex11
ELF	f6f1f000-f6f48000	Deferred        libexpat.so.1
ELF	f6f48000-f6f83000	Deferred        libfontconfig.so.1
ELF	f6f83000-f6fab000	Deferred        libpng12.so.0
ELF	f6fab000-f6fc5000	Deferred        libz.so.1
ELF	f6fc5000-f7065000	Deferred        libfreetype.so.6
ELF	f7065000-f707f000	Deferred        version<elf>
  \-PE	f7070000-f707f000	\               version
ELF	f707f000-f719c000	Deferred        gdi32<elf>
  \-PE	f7090000-f719c000	\               gdi32
ELF	f719c000-f72f6000	Dwarf           user32<elf>
  \-PE	f71b0000-f72f6000	\               user32
ELF	f72f6000-f7370000	Deferred        shlwapi<elf>
  \-PE	f7300000-f7370000	\               shlwapi
ELF	f7370000-f73e2000	Deferred        advapi32<elf>
  \-PE	f7380000-f73e2000	\               advapi32
ELF	f73e3000-f7591000	Dwarf           libc.so.6
ELF	f7591000-f7596000	Deferred        libdl.so.2
ELF	f7597000-f75b3000	Deferred        libpthread.so.0
ELF	f75cc000-f7781000	Dwarf           libwine.so.1
ELF	f7783000-f77a5000	Deferred        ld-linux.so.2
ELF	f77a5000-f77a6000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
00000008 winecfg.exe
	00000009    0
0000000e services.exe
	00000027    0
	00000026    0
	00000020    0
	00000017    0
	00000010    0
	0000000f    0
00000012 mscorsvw.exe
	0000001c    0
	0000001b    0
	0000001a    0
	00000013    0
00000014 explorer.exe
	00000016    0
	00000015    0
0000001e winedevice.exe
	0000002a    0
	00000023    0
	00000022    0
	0000001f    0
00000024 plugplay.exe
	00000029    0
	00000028    0
	00000025    0
0000002d (D) Z:\home\chris\Downloads\Hearthstone Deck Tracker\Hearthstone Deck Tracker.exe
	00000030    2
	0000002f    0
	0000002e    0 <==
System information:
    Wine build: wine-1.6.2
    Platform: i386
    Host system: Linux
    Host version: 3.16.0-46-generic

**Comment by asyncee** [comment]
Currently i'm using wine-staging (1.7.50) with clean wine environment (WINEARCH=win32). I have installed dotnet45 using this commands:

    $ ­wget http://winetricks.googlecode.com/svn/trunk/src/winetricks
    $ bash winetricks dotnet45

Windows version is set to "windows 7".
Appliation launches, gui working as expected, not sure if it will work with overlay, because i have not tested it with hearhtstone installation, but i think everything will be fine.

**Comment by asyncee** [comment]
Also, i'm using linux mint 17.2 Rafaela.

**Comment by ComtriS** [comment]
@asyncee were you able to get the overlay to work?
