### ISSUE TITLE
Hunter Hero Power Issues in Replays

### ISSUE THREAD

**Issue by Kyriella** [Epix37/Hearthstone-Deck-Tracker#1165]
When using your hunter hero power to target a minion through Steamwheedle Sniper's ability, the replay shows it as an unknown 2 mana card in your hand pointed at your target, then an unknown reason for the target to be taking two damage. (Shown here used on an Antique Healbot that was set to 1 health by a Hunter's Mark.)

Unknown 2 mana card
![steamwheedle sniper replay 1](https://cloud.githubusercontent.com/assets/13091455/8712621/84b9e9d0-2b2c-11e5-9c41-2f34c1ab6b46.PNG)
Unknown reason for damage taken
![steamwheedle sniper replay 2](https://cloud.githubusercontent.com/assets/13091455/8712622/84bb8e84-2b2c-11e5-84b4-41714b11eb77.PNG)

It also does a similar thing when you use the hunter hero power without Steamwheedle Sniper, except that it only shows a single unknown entry and lowers your mana and their health both by two.

Before hero power (9/9 mana, opponent at 29 health)
![before steady shot](https://cloud.githubusercontent.com/assets/13091455/8712735/f4cda7d8-2b2d-11e5-85b0-ecaab0a590b7.PNG)

After hero power (7/9 mana, opponent at 27 health)
![after steady shot](https://cloud.githubusercontent.com/assets/13091455/8712763/42911e50-2b2e-11e5-94fb-57703a253147.PNG)

**Comment by andburn** [comment]
Nice detailed post this should get fixed for that alone! :+1:
Were you playing with the *Alleria* skin or regular?

**Comment by Kyriella** [comment]
Thanks! I'm learning to program as well so I wanted to make your work as easy as possible.

Come to think of it, I *was* using the Alleria skin.

**Comment by andburn** [comment]
I thought it might've been Alleria, there still seems to be a problem with the new skins. I'll have a look and see what it might be.

**Comment by culinko** [comment]
Yeah, hero powers of new heroes have different IDs than the old ones.

DS1h_292_H1 (Steady Shot)
CS2_102_H1 (Armor Up!)
CS2_034_H1 (Fireblast)
