### ISSUE TITLE
Deleted game stay in deck stat

### ISSUE THREAD

**Issue by Cuttyflame** [Epix37/Hearthstone-Deck-Tracker#1166]
So in my stat, it say i got 44-29 win/lose, but in my total game on the web page i only get 40-27 win lose. I compare all battle between the website and the downloadable app and that was all the same. And the only option possible is when i have created game that i didnt found on the webpage but found them after on the app so i deleted them.

**Comment by Epix37** [comment]
Games with practice or unknown mode don't get uploaded. Probably the issue.
