### ISSUE TITLE
Cannot log on earthstats

### ISSUE THREAD

**Issue by fref** [Epix37/Hearthstone-Deck-Tracker#1167]
This is the error message I receive:
The underlying connection was closed: an unexpected error occurred on a receive

(for the record, I find annoying that the login window stays on top of the other window, there's no good reason for such an intrusive behaviour)

**Comment by Epix37** [comment]
Probably some temporary server issues? I guess this is no longer relevant. 

For the window: you can turn it off via `options > tracker > settings > show login dialog`.
