### ISSUE TITLE
Adding tag makes deck invisible

### ISSUE THREAD

**Issue by MorallyGreybeard** [Epix37/Hearthstone-Deck-Tracker#1169]
Adding a tag, normally or quick menu, makes the deck vanish.

**Comment by andburn** [comment]
It sounds like you are filtering decks by some tags. Check `MAIN > QUICK FILTER` and `MAIN > SORT / FILTER` set them to *ALL* and see if the deck comes back.

**Comment by MorallyGreybeard** [comment]
Bingo!  That's it :)  I've never touched the filter menu though so looks like it does this by default.
