### ISSUE TITLE
Cards "recycled" into the deck doesnt count

### ISSUE THREAD

**Issue by talmantel** [Epix37/Hearthstone-Deck-Tracker#1171]
My opponent played iron juggernaut and at the end of the game the tracker asked me if i want to delete the game since the mine i got from the iron juggernaut wasnt supposed to be in my deck..
i guess it will be the same with malorne, recycle etc'

**Comment by riQQ** [comment]
I had the same issue yesterday with recycle (see #1170).

**Comment by riQQ** [comment]
Do you have a replay of that game?

**Comment by talmantel** [comment]
yes i do. i found it using the program and i can watch it but i cant seem to find a way to export it
![image](https://cloud.githubusercontent.com/assets/1533962/8787336/3612f646-2f3c-11e5-8117-cf90882ddcc3.png)

**Comment by riQQ** [comment]
Replays are stored here: C:\Users\<UserName>\AppData\Roaming\HearthstoneDeckTracker\Replays.

**Comment by talmantel** [comment]
i found the replay. i cant upload it though because its a XML file and the comment system doesnt support it

**Comment by talmantel** [comment]
here is a copy of it though:

<?xml version="1.0" encoding="utf-8"?>
<ArrayOfTurnStats xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <TurnStats>
    <Plays>
      <Play>
        <CardId />
        <Type>OpponentDraw</Type>
      </Play>
      <Play>
        <CardId />
        <Type>OpponentDraw</Type>
      </Play>
      <Play>
        <CardId />
        <Type>OpponentDraw</Type>
      </Play>
      <Play>
        <CardId />
        <Type>OpponentDraw</Type>
      </Play>
      <Play>
        <CardId>GVG_003</CardId>
        <Type>PlayerDraw</Type>
      </Play>
      <Play>
        <CardId>CS2_032</CardId>
        <Type>PlayerDraw</Type>
      </Play>
      <Play>
        <CardId>CS2_023</CardId>
        <Type>PlayerDraw</Type>
      </Play>
      <Play>
        <CardId />
        <Type>OpponentDraw</Type>
      </Play>
      <Play>
        <CardId />
        <Type>OpponentDraw</Type>
      </Play>
      <Play>
        <CardId />
        <Type>OpponentMulligan</Type>
      </Play>
      <Play>
        <CardId>EX1_284</CardId>
        <Type>PlayerDraw</Type>
      </Play>
      <Play>
        <CardId>CS2_032</CardId>
        <Type>PlayerMulligan</Type>
      </Play>
      <Play>
        <CardId>GVG_096</CardId>
        <Type>PlayerDraw</Type>
      </Play>
    </Plays>
    <Turn>0</Turn>
  </TurnStats>
  <TurnStats>
    <Plays>
      <Play>
        <CardId />
        <Type>OpponentDraw</Type>
      </Play>
      <Play>
        <CardId>EX1_298</CardId>
        <Type>PlayerDraw</Type>
      </Play>
      <Play>
        <CardId>GVG_003</CardId>
        <Type>PlayerPlay</Type>
      </Play>
      <Play>
        <CardId>EX1_620</CardId>
        <Type>PlayerGet</Type>
      </Play>
    </Plays>
    <Turn>1</Turn>
  </TurnStats>
  <TurnStats>
    <Plays>
      <Play>
        <CardId />
        <Type>OpponentDraw</Type>
      </Play>
      <Play>
        <CardId>NEW1_012</CardId>
        <Type>PlayerDraw</Type>
      </Play>
      <Play>
        <CardId>CS2_023</CardId>
        <Type>PlayerPlay</Type>
      </Play>
      <Play>
        <CardId>GVG_096</CardId>
        <Type>PlayerDraw</Type>
      </Play>
      <Play>
        <CardId>CS2_024</CardId>
        <Type>PlayerDraw</Type>
      </Play>
    </Plays>
    <Turn>2</Turn>
  </TurnStats>
  <TurnStats>
    <Plays>
      <Play>
        <CardId />
        <Type>OpponentDraw</Type>
      </Play>
      <Play>
        <CardId>EX1_007</CardId>
        <Type>OpponentPlay</Type>
      </Play>
      <Play>
        <CardId>GVG_069</CardId>
        <Type>PlayerDraw</Type>
      </Play>
      <Play>
        <CardId>NEW1_012</CardId>
        <Type>PlayerPlay</Type>
      </Play>
      <Play>
        <CardId>CS2_024</CardId>
        <Type>PlayerPlay</Type>
      </Play>
      <Play>
        <CardId />
        <Type>OpponentDraw</Type>
      </Play>
    </Plays>
    <Turn>3</Turn>
  </TurnStats>
  <TurnStats>
    <Plays>
      <Play>
        <CardId />
        <Type>OpponentDraw</Type>
      </Play>
      <Play>
        <CardId>FP1_021</CardId>
        <Type>OpponentPlay</Type>
      </Play>
      <Play>
        <CardId>NEW1_012</CardId>
        <Type>PlayerDraw</Type>
      </Play>
      <Play>
        <CardId>NEW1_012</CardId>
        <Type>PlayerPlay</Type>
      </Play>
      <Play>
        <CardId>GVG_096</CardId>
        <Type>PlayerPlay</Type>
      </Play>
    </Plays>
    <Turn>4</Turn>
  </TurnStats>
  <TurnStats>
    <Plays>
      <Play>
        <CardId />
        <Type>OpponentDraw</Type>
      </Play>
      <Play>
        <CardId>EX1_606</CardId>
        <Type>OpponentPlay</Type>
      </Play>
      <Play>
        <CardId />
        <Type>OpponentDraw</Type>
      </Play>
      <Play>
        <CardId>EX1_410</CardId>
        <Type>OpponentPlay</Type>
      </Play>
      <Play>
        <CardId>GAME_005</CardId>
        <Type>OpponentPlay</Type>
      </Play>
      <Play>
        <CardId>EX1_402</CardId>
        <Type>OpponentPlay</Type>
      </Play>
      <Play>
        <CardId>CS2_032</CardId>
        <Type>PlayerDraw</Type>
      </Play>
      <Play>
        <CardId>GVG_096</CardId>
        <Type>PlayerPlay</Type>
      </Play>
      <Play>
        <CardId>CS2_034</CardId>
        <Type>PlayerHeroPower</Type>
      </Play>
    </Plays>
    <Turn>5</Turn>
  </TurnStats>
  <TurnStats>
    <Plays>
      <Play>
        <CardId />
        <Type>OpponentDraw</Type>
      </Play>
      <Play>
        <CardId>GVG_056</CardId>
        <Type>OpponentPlay</Type>
      </Play>
      <Play>
        <CardId>CS2_032</CardId>
        <Type>PlayerDraw</Type>
      </Play>
      <Play>
        <CardId>EX1_284</CardId>
        <Type>PlayerPlay</Type>
      </Play>
      <Play>
        <CardId>GVG_056t</CardId>
        <Type>PlayerDraw</Type>
      </Play>
      <Play>
        <CardId>GVG_056t</CardId>
        <Type>PlayerHandDiscard</Type>
      </Play>
      <Play>
        <CardId>FP1_012</CardId>
        <Type>PlayerDraw</Type>
      </Play>
      <Play>
        <CardId>CS2_034</CardId>
        <Type>PlayerHeroPower</Type>
      </Play>
    </Plays>
    <Turn>6</Turn>
  </TurnStats>
  <TurnStats>
    <Plays>
      <Play>
        <CardId />
        <Type>OpponentDraw</Type>
      </Play>
      <Play>
        <CardId>EX1_249</CardId>
        <Type>OpponentPlay</Type>
      </Play>
      <Play>
        <CardId>CS2_029</CardId>
        <Type>PlayerDraw</Type>
      </Play>
      <Play>
        <CardId>EX1_620</CardId>
        <Type>PlayerPlay</Type>
      </Play>
      <Play>
        <CardId>CS2_034</CardId>
        <Type>PlayerHeroPower</Type>
      </Play>
    </Plays>
    <Turn>7</Turn>
  </TurnStats>
  <TurnStats>
    <Plays>
      <Play>
        <CardId />
        <Type>OpponentDraw</Type>
      </Play>
      <Play>
        <CardId>EX1_298</CardId>
        <Type>OpponentPlay</Type>
      </Play>
      <Play>
        <CardId>FP1_004</CardId>
        <Type>PlayerDraw</Type>
      </Play>
      <Play>
        <CardId>EX1_298</CardId>
        <Type>PlayerPlay</Type>
      </Play>
    </Plays>
    <Turn>8</Turn>
  </TurnStats>
  <TurnStats>
    <Plays>
      <Play>
        <CardId />
        <Type>OpponentDraw</Type>
      </Play>
      <Play>
        <CardId>EX1_606</CardId>
        <Type>OpponentPlay</Type>
      </Play>
      <Play>
        <CardId />
        <Type>OpponentDraw</Type>
      </Play>
      <Play>
        <CardId>CS2_203</CardId>
        <Type>OpponentPlay</Type>
      </Play>
      <Play>
        <CardId>CS2_106</CardId>
        <Type>OpponentPlay</Type>
      </Play>
      <Play>
        <CardId>EX1_410</CardId>
        <Type>OpponentPlay</Type>
      </Play>
      <Play>
        <CardId>EX1_005</CardId>
        <Type>PlayerDraw</Type>
      </Play>
      <Play>
        <CardId>CS2_029</CardId>
        <Type>PlayerPlay</Type>
      </Play>
    </Plays>
    <Turn>9</Turn>
  </TurnStats>
</ArrayOfTurnStats>

**Comment by andburn** [comment]
That file is from `C:\Users\<UserName>\AppData\Roaming\HearthstoneDeckTracker\Games`. The replays are in found in `C:\Users\<UserName>\AppData\Roaming\HearthstoneDeckTracker\Replays` and are named like this `YourName(Hunter) vs OpponentName(Warlock) 2043-210715.hdtreplay`. If you can find the *Iron Juggernaut* game's replay file, you would then need to upload it to a site like [Dropbox](http://www.dropbox.com) or [Mega](http://www.mega.co.nz) and post a link to it here.

**Comment by talmantel** [comment]
https://www.dropbox.com/s/08xoui159bg9w79/BrightHammer%28Mage%29%20vs%20leott7%28Warrior%29%201519-190715.hdtreplay?dl=0
