### ISSUE TITLE
"Deck does not match" and druid cards

### ISSUE THREAD

**Issue by TheGoblinHero** [Epix37/Hearthstone-Deck-Tracker#1173]
I've tried to enable "Discard game if deck does not match option". After the game tracker says deck does not match, but the proper deck is selected. I suspect that druid cards like "Wrath" cause it.

**Comment by riQQ** [comment]
Do you have a replay for that? Could be the same issue like #1170 and #1171.

**Comment by TheGoblinHero** [comment]
Here's an archive with the replay:
www.slightlymagic.net/tmp/replay.rar

**Comment by riQQ** [comment]
I can't extract that file.

**Comment by TheGoblinHero** [comment]
It's rar5. Repacked:
www.slightlymagic.net/tmp/replay.zip

**Comment by Epix37** [comment]
most likely fixed with v0.11
