### ISSUE TITLE
Crash on startup, after that whole history gone

### ISSUE THREAD

**Issue by sausje** [Epix37/Hearthstone-Deck-Tracker#1174]
Like title says, I started the program, got a bunch of error messages and after that everything was gone, every played game..

http://pastebin.com/8dWNWqNK

**Comment by riQQ** [comment]
Looks like the PlayerDecks.xml got corrupted and there were no backups. What's in your folder C:\Users\<UserName>\AppData\Roaming?

**Comment by sausje** [comment]
Yeah seems there are some config files with numbers (presume the ones before the crashing happened) and the corrupted playerdecks xml: http://i.imgur.com/ycOVRe5.png

Let's see if I can recover all. Though why did this crash happened in the first place? I didn't do anything different nor has anything new been installed from quite some time.

**Comment by andburn** [comment]
It's hard to know what caused the problem. Hopefully, you will be able to recover the data from them. Backing up your current files and simply removing the "*_corrupted*" might even work. If not you could upload the problem files somewhere and we could have a look at them.

**Comment by sausje** [comment]
I noticed a few zip files in backups folder, lucky it made one the day before this crash happened. Replaced those files with the files in the zip and it's all good now. Still odd and hope it won't happen again.

**Comment by riQQ** [comment]
Do you still have the corrupted files? I'd like to take a look.

**Comment by sausje** [comment]
Just the corrupted ones? I rarred the whole folder before attempting to restore backups, so which ones you need that are listen in the screenshot above?

**Comment by riQQ** [comment]
If you have the complete folder, upload it somewhere. But delete the hearthstatsauth file.This contains your authentication token for hearthstats.

**Comment by sausje** [comment]
Ok done, let me know when you took it so I can take it down again ;)

http://www.kzn-clan.nl/HearthstoneDeckTracker.rar

**Comment by riQQ** [comment]
I got it, thanks.
