### ISSUE TITLE
I have a problem: My deck tracker don't work

### ISSUE THREAD

**Issue by Alessio1996** [Epix37/Hearthstone-Deck-Tracker#1175]
I tried to download it and set it but nothing changes. I setup the deck and while they game me alone cards that peach and I do not see the deck that I composed in the program. I tried to restart the program but does not change anything. Is there a way to sort it out ??? do not appear my deck while the game but only the cards that peach currently.   thanks

**Comment by riQQ** [comment]
Did you click use on your deck? Then it should be marked as active and the overlay should display your whole deck.

**Comment by Alessio1996** [comment]
where is this button use on your deck? because now the tracker display me the card when i drow. the complete deck I do not ever see

**Comment by riQQ** [comment]
Click the red button, then it should switch to active.

![Hearthstone Deck Tracker](https://cloud.githubusercontent.com/assets/3404787/8810132/3a264aa6-2fed-11e5-8566-8735f41e2ff5.png)

**Comment by andburn** [comment]
There are some pictures [here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#the-overlay-is-only-showing-the-cards-that-have-been-played-what-about-those-left-in-my-deck)

**Comment by Alessio1996** [comment]
ok perfect. thanks you

**Comment by Epix37** [comment]
The whole "use" thing needs some serious clarification... 

For now I added a hint that hopefully helps with this at least a little bit.

![use](https://cloud.githubusercontent.com/assets/7737910/9163381/0129e232-3f4a-11e5-9ad9-9897efc178d1.PNG)
