### ISSUE TITLE
exporting deck to hearthstone with name too long

### ISSUE THREAD

**Issue by talmantel** [Epix37/Hearthstone-Deck-Tracker#1176]
when i created a deck in the tracker and gave it a too long name (longer than hearthstone supports) and tried to export it into hearthstone it only changed the name of the deck (partially of course) and did not put the cards into it. as soon as i shortened the name everything worked fine

**Comment by mhmdfy** [comment]
can you reporduce the issue? ie. if you go back to a long name, does the export still fails?

**Comment by talmantel** [comment]
no, actually i cant. it works fine. i guess its a one time issue.
