### ISSUE TITLE
Exporting to Tavern Brawl?

### ISSUE THREAD

**Issue by megablue** [Epix37/Hearthstone-Deck-Tracker#1177]
The export to Hearthstone function seems all messed up with i tried to export a deck to Tavern Brawl.

**Comment by andburn** [comment]
It seems to work fine for me. What happened exactly? Were there cards missing or wrong cards, how many? Also, what resolution are you running hearthstone at and is it windowed or fullscreen?

**Comment by megablue** [comment]
I just figured what caused it. If you had a conversation in HS. it will messed up the exporting. I believe it is caused by the Enter key pressed on the deck name, since you cant change a deck name in Brawl mode, Enter key will bring up the conversation window instead and it somehow disturbed the other mouse clicks and key presses.

**Comment by mvordeme** [comment]
I have a different issue when exporting to Tavern Brawl (although I must say that it did work fine once):  When I try to export a deck to Tavern Brawl, the first thing HDT does is activate the 0 mana cost filter, and it subsequently does not find a single card. If I activate the filter myself (hoping that HDT will deactivate it), nothing changes.

**Comment by andburn** [comment]
@mvordeme Does it only happen in Brawl exporting or also in constructed? What resolution are you running Hearthstone at and is it fullscreen or windowed? Probably same problem as #1162.

**Comment by mvordeme** [comment]
This is funny. Last night, exporting to TB definitely didn't work, and I had to compose the deck manually. Tonight, I first checked my resolution because it sometimes changes to custom when I move the window around the screen, but it was still set to 1600 x 900 (windowed). Then I imported a constructed deck and after that a brawl deck without any problems. I even saw the mouse selecting the 0 mana filter, but it must have selected other filters later on.

**Comment by mvordeme** [comment]
It happened to me again, regardless of the resolution selected in both full screen and windowed. There was a conversation at the same time, so I restarted HS, but it didn't improve the situation. Should I post this somewhere else?

**Comment by andburn** [comment]
Not sure what it could be, try adding a tag to the deck with *brawl* in it - for example **Tavern Brawl**. This will stop the export from trying to change the deck title.

The automatic filtering seems to cause problems for some people, maybe we could add an option to allow people to turn off the automatic filtering.

**Comment by mvordeme** [comment]
Oh, sorry. It seems that I have actually hijacked this issue :blush:. It was my issue (see 4th posting) that I experienced again. Maybe I should rather post in #1217.

**Comment by livejamie** [comment]
Suggest merging this with #1217
