### ISSUE TITLE
Can't save decks anymore

### ISSUE THREAD

**Issue by hultgrrr** [Epix37/Hearthstone-Deck-Tracker#1180]
I can't save new decks anymore. Have tested both importing arena and constructed as well as building one manually. Deleted all my old decks to check if it was a problem with total number of decks, but it is still not working. I also have deleted the folder and downloaded a new entity of the Deck Tracker but it is still not working.

**Comment by andburn** [comment]
What exactly is happening, are you getting an error or are the decks just not showing up in the deck list? Check to see you aren't accidentally filtering decks out, see [here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#tag-filter).

**Comment by hultgrrr** [comment]
I stand corrected. Nothing wrong with the release, somehow I've just been filtering out all the decks. Sorry.

**Comment by andburn** [comment]
Its probably nothing you did, it has happened to a couple of other people who never touched the filters. The filters seem to be getting turned on somehow.
