### ISSUE TITLE
HearthStats error: (520) Origin Error

### ISSUE THREAD

**Issue by abathon** [Epix37/Hearthstone-Deck-Tracker#1181]
Hi,
I have a problem with stats in Deck Tracker. And I don´t understand, why this error is called Origin Error? Origin and Hearthstone?
Thanks
Petr

**Comment by riQQ** [comment]
This is a CloudFlare error. It says, HearthStats returned an unknown error.
See: https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520-Web-server-is-returning-an-unknown-error.
