### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Incarceron** [Epix37/Hearthstone-Deck-Tracker#1183]
Not sure where I can post suggestions or if there even is a place, but is there anyway for a card count feature to be added where we can see the number of cards in hand?

It's a very common QoL update that is requested by players and I think it would be very useful.

**Comment by riQQ** [comment]
This feature already exists in the overlay. See the readme at https://github.com/Epix37/Hearthstone-Deck-Tracker.
