### ISSUE TITLE
Automatic deck selection sometimes fails to work

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#1185]
Automatic deck selection doesn't always work. It doesn't auto-select the right deck about 25% of the time, I'd say. During those times, I have to quickly alt-tab to the app to manually find and set my deck, during a new game's mulligan phase.

Is there anything that I can do to increase the chances that the app properly auto-selects the right deck?

**Comment by andburn** [comment]
There does seem to be a problem with auto deck selection, see #1067. 

For you it does work most of the time though, so it might just be the decks that you are using. Do you have many decks that might be similar, for example a lot of Hunter decks have the same core cards - it can be difficult for the tracker to tell similar decks apart.

**Comment by GaryKing** [comment]
No I don't think it's a problem of similar decks. I don't have many decks, to begin with. About 5 constructed and 10 arena ones right now, and all my constructed ones are of a different class.

**Comment by andburn** [comment]
Ok, well that definitely is a problem then. With five decks and five different classes, obviously the deck selection should always be correct. Maybe @Epix37 will be able to see what is wrong, in the meantime I'll see if I can figure it out.
