### ISSUE TITLE
HDT crash and all decks  are erase and settings have been reseted back to default.

### ISSUE THREAD

**Issue by GamerM** [Epix37/Hearthstone-Deck-Tracker#1186]
Hello. I was trying to open up HDT and after skipping the hearthstats login it gave me an error message of HDT crashing. I know it said to email you, but i think it would be better just to make it an issue on github.  All of my save Decks were erase and the settings for HDT. It really sucks and i hope you got a way to fix this or at least prevent it from happening later to other user in the upcoming updates. 

Here is the crash log which i put on pastebin: http://pastebin.com/gZqmCSRf

Other things to note about what happen during that time is that i was playing around the the batch you made to make it automatically start Hearthstone and HDT at the same time. Was trying to add a taskkill to close a folder where i put my games at the same time (It didn't work). Also had to force shutdown my computer. 

Thanks for your help.

**Comment by andburn** [comment]
I'm not sure what caused the crash. The log says `DeckStats.xml` is corrupt. The same thing happened to someone recently (#1174). Maybe @Epix37  will be able to tell whats happening.

There should be a backup of your decks and stats. Go to `C:\Users\<UserName>\AppData\Roaming\HearthstoneDeckTracker\Backups` and use the most recent zip file to replace the corrupted files in `C:\Users\<UserName>\AppData\Roaming\HearthstoneDeckTracker`.

**Comment by GamerM** [comment]
Thanks @andburn for telling me about the backup. That really help me a lot. The decks which was the most important was saved, but the settings were not. I had to redo all the settings to make it my own again. Hopefully there would be a backup for the settings too in the future.

**Comment by Epix37** [comment]
That happens if HDT is closed while (re)writing the xml. Due to the OS shutting down or some other reason. Extactly for that reason the backups were added. Not sure what to do about it though - other than moving away from xml.

The config is now included in the backup aswell.

**Comment by GamerM** [comment]
Aah ok. I see what actually happen now. When i was trying to close the folder through the batch file. I use taskill explorer.exe. I thought it will close folders, but it actually force close  the entire desktop (lol). Which means i terminated every process that was happening on the desktop , and probably HDT was running in the background. Had to force shut down and everything. Thanks Epix37 for adding the config file to the backup. That will help a lot in the future. Closing issue.

**Comment by Epix37** [comment]
This should make things a bit easier in the future:
![backups](https://cloud.githubusercontent.com/assets/7737910/9194819/59228834-401e-11e5-9040-8bc6b7f38889.PNG)
