### ISSUE TITLE
Overlay appears in alt-tab window selection (Win 10)

### ISSUE THREAD

**Issue by SANstorming** [Epix37/Hearthstone-Deck-Tracker#1191]
Before the upgrade to Windows 10, the overlay didn't show up in the alt-tab window list, but now it gets in the way when switching to my most recently used window.
![task_switching_2015-07-31_19-27-00](https://cloud.githubusercontent.com/assets/7953994/9019479/850b2e0e-37ba-11e5-8086-3eac00d6c660.jpg)

**Comment by darius07** [comment]
I can confirm this issue.
