### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by GentleSir** [Epix37/Hearthstone-Deck-Tracker#1195]
Everytime I open the tracker I get this: http://prntscr.com/809rjf
I tried to reinstall and to delete the files from appdata, but nothing works.
Win8.1, it worked until 2 weeks ago

**Comment by GentleSir** [comment]
Nothing?

**Comment by riQQ** [comment]
What's in the log?

**Comment by Epix37** [comment]
Try (re)installing .NET Framework 4.5
