### ISSUE TITLE
no decks detected

### ISSUE THREAD

**Issue by agent0range21** [Epix37/Hearthstone-Deck-Tracker#1197]
no deck is detected 
reinstalled dotnet 4.5 reinstalled hearthstone deck tracker reset config etc..
the decks still doesnt show up

**Comment by agent0range21** [comment]
tracking works tried creating NEW-DECK same name still wont show up the whole deck in the overlay

**Comment by riQQ** [comment]
Have you read the FAQ: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ?
