### ISSUE TITLE
Deck editing window not showing

### ISSUE THREAD

**Issue by drakenkanon** [Epix37/Hearthstone-Deck-Tracker#1200]
Hello,

For a long time now I am having an issue: the deck tracker still tracks the cards played in game, but I can not seem to get the deck editing window to show up. Whenever I launch the tracker only the 2 small windows which track the cards played are showing.

**Comment by GiggliG** [comment]
Check to see if HDT is minimised to the system tray. I fell victim to this once and facepalmed hard when I realised what the issue was.

**Comment by Epix37** [comment]
Alternatively it might be somewhere "off screen" for some reason. See if you can alt-tab to the HDT window and if so, press "Win+LeftArrow" until you see it.
