### ISSUE TITLE
Bug with deck activation

### ISSUE THREAD

**Issue by TheHiding** [Epix37/Hearthstone-Deck-Tracker#1201]
Hey guys, think I managed to pin down a small bug with automatic activation decks. 

I created a deck with a '?' in the deck name. When ever I start play with that deck or any deck listed below it in my deck list, deck tracker won't activate the deck. The deck is highlighted but the activation never happens automatically, manual activation is still possible. 
Decks listed above the one with the ? in the name activate automatically properly when I switch to using one of those decks.

**Comment by TheHiding** [comment]
Yep. Sorry this was fixed. A version or 2 after I originally posted

**Comment by jleclanche** [comment]
Thanks!
