### ISSUE TITLE
Unset active deck so that there is no active deck

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#1202]
Is it possible to unset the active deck so that there is no active deck? For instance, when I'm playing Tavern Brawl, it doesn't usually make sense to have any active deck. 

Occasionally, a prompt will appear from HDT asking me if I want to unset the active deck, but this appears rarely.

**Comment by TheHiding** [comment]
Under Main in the menu bar. Use no deck.

**Comment by Epix37** [comment]
Alternatively you can do the same by rightclicking the tray icon.
