### ISSUE TITLE
Countdown/timer doesn't always appear

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#1203]
The countdown/timer doesn't always appear. It doesn't appear for about 25% of my games, for some reason.

**Comment by Cu8eR** [comment]
@Epix37 - issue persists on latest v0.13.0

**Comment by psybreeze** [comment]
I can confirm this bug, 0.13.7 version, still missing counter about 25-30 percent.

**Comment by Epix37** [comment]
Is this still an issue with v0.14?

**Comment by GaryKing** [comment]
No

**Comment by Epix37** [comment]
:+1:
