### ISSUE TITLE
Deck Tracker will not launch.

### ISSUE THREAD

**Issue by TylerNodell** [Epix37/Hearthstone-Deck-Tracker#1208]
I'm trying to deck tracker for the first time but, when i try to open Hearthstone Deck Tracker.exe, the launcher pulls up the loading image then stops. No matter how long I wait it never launches.

**Comment by Epix37** [comment]
Try (re)installing .NET Framework 4.5

**Comment by CompeteHS** [comment]
Yeah, i have the same issue. It just loads the picture, then says "Hearthstone Deck Tracker has stopped working".
