### ISSUE TITLE
Broadcast Capture

### ISSUE THREAD

**Issue by stdscatchemall** [Epix37/Hearthstone-Deck-Tracker#1209]
Because of the way that you draw the overlay, there is no way for me or anyone else to capture it. Is it possible to make it capture-able by OBS? For the record, Windows sees the overlay on it's own as well as ShareX (Screenshot Program).

Unless this just happens to be an OBS issues :(

**Comment by GiggliG** [comment]
You can capture it with OBS. It's a little tricky to set up the first time, but use the Window Capture option not Game Capture.

**Comment by stdscatchemall** [comment]
All it does is capture one large black screen with no information on it. :(

http://stdscatchemall.com/Screenshots/2015-08-11_01-57-23.png

And no, it doesn't work on OBS1 or OBS Multiplatform

**Comment by stdscatchemall** [comment]
From what I can tell, the issue lies with the fact that the Application uses D3D9. Windows 10 doesn't seem to support it very well, and OBS definitely doesn't work with D3D9 + Windows 10 nicely...

**Comment by Epix37** [comment]
OBS can't capture transparent windows as far as I know. 

There a two workarounds currently: 
1) You can use monitor capture to just capture game+overlay
2) Enable `options > overlay > deck windows`, you can capture those

**Comment by stdscatchemall** [comment]
That's what I was using, but I wanted the overlay itself because of how nice it looks personally. So I modified the original app code and added a compatibility window. Basically, all it does is sit behind Hearthstone. It's a full window so it captures, and you can chroma key the black caused by the lack of texture, or if I really wanted to, I could add a real color to chroma out. It work for what it needs to and it doesn't add much extra memory usage. What I might do is actually add a full implementation of it with a toggle in the settings, then make a pull request with it. For now, it's getting late, and until I know it's stable, i'm gonna keep it personal.

**Comment by Epix37** [comment]
Oh if you could make that into a PR, that would be awesome! :)

**Comment by stdscatchemall** [comment]
I've decided to go down the plugin route for this. I introduced the idea to Kripparrian (where I did integrate it), but he stuck with the Player/Opponent Window, so now, I'm making it into a plugin :)

I'm also doing something no one else has (see screenshot below):
Note the extra TreeViewItem... http://stdscatchemall.com/Screenshots/Hearthstone_Deck_Tracker_2015-08-15_12-50-28.png

**Comment by Epix37** [comment]
A plugin is a even better solution, yea! The options item is neat :D.

Le me know if you need help with anything!

**Comment by stdscatchemall** [comment]
At this point, I'm just trying to think of what other settings to add to it. Since i made a direct copy of OverlayWindow (in order to preserve functionality, and change a few settings to accommodate the window size and a couple of other things), it maintains all the same functionality as you change the overlay settings. So I can't really think of anything other than what I've got...

**Comment by stdscatchemall** [comment]
Plugin is added to available plugins page!

**Comment by stdscatchemall** [comment]
I just realized that I forgot to request that you update MahApps to the most recent version. There were some issues compiling with the old version when I made the program. The latest version works fine with the application :) My plugin won't show up in the plugins list because it's running on the newer version :(

**Comment by Epix37** [comment]
Awesome!

As far as I can see, MahApps is up to date. Their latest release (github and nuget) was 1.1.2 on march 1st.

**Comment by stdscatchemall** [comment]
Yeah, it's on 1.1.2, and the issue seems to have gone away. It seemed like it was a bug with the project or something, don't really know. It's gone. I'm trying to determine why it won't show up in the plugins list, and will update the wiki as soon as I fix it!

**Comment by stdscatchemall** [comment]
K. I've officially stopped bouncing back and fourth on this. It's working now :D

**Comment by kerbooo** [comment]
Hi I need help for capturing WPF transparent Window? When I trying to capture window I am getting black background, is it possible with OBS Classic or not?

My OS is Window 7.

Thank you in advance.

**Comment by DigitalVortex92** [comment]
The project was halted very soon after it's creation. I am unable to help
you due to the nature of the upgrades the main program has seen. I may
possibly work on this in the future, but as of right now, it is dead.

On Feb 7, 2017 12:14 PM, "Kerberos" <notifications@github.com> wrote:

Hi I need help for capturing WPF transparent Window? When I trying to
capture window I am getting black background, is it possible with OBS
Classic or not?

My OS is Window 7.

Thank you in advance.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/1209#issuecomment-278070133>,
or mute the thread

**Comment by riQQ** [comment]
@kerbooo have you tried this https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Streaming-Instructions?
