### ISSUE TITLE
HDT doesnt update the number of played cards

### ISSUE THREAD

**Issue by askarmuk** [Epix37/Hearthstone-Deck-Tracker#1211]
My opponent had played 5 unstable portals. Then he played 2 more portals but overall number of played portals had not updated. HDT showed the number 5. It had updated only when he cast another spell after using 2 portals.

http://youtu.be/dFnwr-hDdmA

**Comment by culinko** [comment]
I think it's similar to #897. I observed this with only 2 of the same card. The Tracker didn't update the count unless you tabbed-out and go back into the Tracker (maybe opponent playing a new card would update it too, like in your case). Disregard the title, at first I thought my issue is related to secrets, but it's not.

**Comment by Epix37** [comment]
finally found and fixes this problem!
