### ISSUE TITLE
Export screenshot - 0 mana file

### ISSUE THREAD

**Issue by culinko** [Epix37/Hearthstone-Deck-Tracker#1218]
Hello. I updated to the latest beta version (0.10.8) and tried export/screenshot. While it was uploaded correctly to imgur, the png file created on HDD always has 0 bytes (for both "save only" and "save & upload" options). Thanks for the fix and let me know if there's anything I can do to help.

**Comment by Epix37** [comment]
0 mana files are always bad! :)

Fix now, thank you.
