### ISSUE TITLE
Wrong Importing card's

### ISSUE THREAD

**Issue by Darkreapertv** [Epix37/Hearthstone-Deck-Tracker#1220]
When you import deck list from constructed it imports wrong deck and cards for all caster classes been like this for the last 3 to 4 updates PLEASE fix constructed deck list importing so it imports correct decks for the classes

**Comment by Epix37** [comment]
Try this:
* Restart Hearthstone
* Re-run the importing setup: `options > tracker > importing > set up constructed importing`
* Restart Hearthstone again
* Try importing again (make sure you follow the instructions; `options > tracker > importing > show constructed importing how-to`)

**Comment by Darkreapertv** [comment]
No still don't work when i try to import my priest warlock or anything caster hero it keeps importing druid spells 


     On Friday, August 14, 2015 9:50 AM, Epix <notifications@github.com> wrote:
   

 Try this:   
   - Restart Hearthstone
   - Re-run the importing setup: options > tracker > importing > set up constructed importing
   - Restart Hearthstone again
   - Try importing again (make sure you follow the instructions; options > tracker > importing > show constructed importing how-to)

**Comment by Darkreapertv** [comment]
you can restart and all but when u try to import any other class but the paladin class it importsz druid spells for all other class decks
 


     On Friday, August 14, 2015 4:01 PM, David Caldwell <darkreaper_tv@yahoo.com> wrote:
   

 No still don't work when i try to import my priest warlock or anything caster hero it keeps importing druid spells 


     On Friday, August 14, 2015 9:50 AM, Epix <notifications@github.com> wrote:
   

 Try this:   
   - Restart Hearthstone
   - Re-run the importing setup: options > tracker > importing > set up constructed importing
   - Restart Hearthstone again
   - Try importing again (make sure you follow the instructions; options > tracker > importing > show constructed importing how-to)

**Comment by douglasquintanilha** [comment]
I'm having the same problem, but he always import a priest deck .

**Comment by norden-oscar** [comment]
i have the exact same problem, trying to import a warlock deck and the neutral cards seem to be importet correctly, but all warlock specific cards are changed to druid cards.
Installed the program yesterday from this repo.
i have hearthstone installed through the battlenet client
playing on EU
Tried the suggestion you made earlier in the thread

Hope you can find something :)

**Comment by Epix37** [comment]
Closing in favor of #2250. See https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/2250#issuecomment-204116658 for info on the state of constructed importing.

**Comment by matteo-mosca** [comment]
I don't know if this can be helpful, but the application "Innkeeper" reads your constructed decks fine, with card quantity too, and does it automatically just running in the background, and then shows your deck to the right when you start a game just like your app does. Maybe you can try to check how they do it?
