### ISSUE TITLE
Importing Tavern Brawl Constructed Broken/missing/etc

### ISSUE THREAD

**Issue by caldwelljt2** [Epix37/Hearthstone-Deck-Tracker#1222]
I'm not 100% sure importing for Tavern Brawl decks is suppose to work, but it sometimes sort of works and sometimes doesn't. When attempting to import most any deck I create I first off never open the standard deck construction screen, and only start hearthstone and enter tavern brawl. When I do import, for some reason the deck comes in but usually with a few cards missing and almost always with some extra class-specific cards added that aren't in my deck (they aren't in ANY of my decks, at the moment). I'm baffled how it's coming up with these cards but it must be tied to card IDs or something else, none of the text in some of the spells appear anywhere else so I'm not sure how it decided to add these cards.

BTW, repeating the process will net an identical result (the same wrong cards are added back in)

Perhaps brawl decks aren't considered constructed yet, but I thought I would pass it along. Exporting to Brawl has no issues, so for now I just manually clean the import up as it's close enough to shorten the process vs. doing it from scratch.

Attached is a picture of what was imported to HDT (left) and the deck as it's show in brawl (right), if this helps.
![importing from tavern brawl](https://cloud.githubusercontent.com/assets/9920640/9279301/99855312-4284-11e5-9265-ef768d15d8a8.png)

**Comment by Epix37** [comment]
Have you tried it with the latest beta release? (https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.10.8)
