### ISSUE TITLE
Add TGT card Images

### ISSUE THREAD

**Issue by everchump** [Epix37/Hearthstone-Deck-Tracker#1225]
I have made the TGT card images；

132 pics ,110pix*35pix per pic.

https://mega.nz/#!txkExbyI!4pCs-smuWk2qfpct6PIq7aVqHvafybpQaxYBTNPpcXs

You can add them all.

**Comment by Epix37** [comment]
Awesome! Thank you.

**Comment by everchump** [comment]
pic name fix：

change "bluff-valiant" to "thunder-bluff-valiant"
