### ISSUE TITLE
No secrets panel

### ISSUE THREAD

**Issue by askarmuk** [Epix37/Hearthstone-Deck-Tracker#1228]
My opponent played Nefarian and got a secret (paladin) from him. He put it on the board but the secrets panel didnt activate.

![hs no secrets panel](https://cloud.githubusercontent.com/assets/8628595/9289114/b96ece42-437e-11e5-82ab-964ebba2d5da.jpg)

**Comment by chucklu** [comment]
Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\GameEventHandler.cs
public void HandleOpponentSecretPlayed(string cardId, int from, int turn, bool fromDeck, int otherId)
        {
            LogEvent("OpponentSecretPlayed");
            _game.OpponentSecretCount++;
            if (fromDeck)
                _game.OpponentDeckDiscard(cardId);
            else
                _game.OpponentPlay(cardId, from, turn);
            _game.AddPlayToCurrentGame(PlayType.OpponentSecretPlayed, turn, cardId);

            var isStolenCard = from > 0 && _game.OpponentHandMarks[from - 1] == CardMark.Stolen;
            _game.OpponentSecrets.NewSecretPlayed(otherId, isStolenCard);

            Helper.MainWindow.Overlay.ShowSecrets();
            GameEvents.OnOpponentPlay.Execute(GameV2.GetCardFromId(cardId));
        }
Already marked whether the secret is stolen,I will try to fix this bug.

**Comment by chucklu** [comment]
I will try to fix this

**Comment by chucklu** [comment]
Spellslinger
Add a random spell to each player's hand.
 
a random spell,how could we tell which secret of hero should be ?

**Comment by Epix37** [comment]
Secrets have a `CLASS` tag. I'm not sure how to handle the case where secrets of multiple classes are played though.

**Comment by chucklu** [comment]
just Nefarian stolen the secret is simple to solve,same as Thoughtsteal

a random secret ,can belong to three heroes,
it make no sense,I wonder if we can pass this case.

**Comment by chucklu** [comment]
a random secret played，I wonder if we can show all secrets of three heroes?
