### ISSUE TITLE
Stats not updating

### ISSUE THREAD

**Issue by mconner27** [Epix37/Hearthstone-Deck-Tracker#1231]
Hello,
So far the import/export feature of creating decks, adding them to my Hearthstone account, and even showing which cards I've played and my opponents played are all working great.
Except for the Stats page. Nothing ever shows up there. Everything is still listed as 0-0.
Ive played a good amount of solo and casual/ranked matches.

Is there something i'm missing to get the Game & Statistics working?

Thank you

**Comment by mconner27** [comment]
Also, next to each one of my created decks, they all say "NO STATS". Even the decks ive used before.

Thank you

**Comment by SeraphineX** [comment]
I just donwloaded this today and it's happening to me too. Glad to know I wasn't the only one with this problem.

**Comment by Epix37** [comment]
Hey,

make sure you actually have a deck set as "active".
See here for more detail: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ

it's definitely a bit unintuitive in the current release. The next update should hopefully make is a bit clearer.

Your games so far have been recorded to a "default deck". You can move them to the correct one via `Games & Statistics > (Overall >) Games > *select all that belong to one deck* > move to other deck`

**Comment by mconner27** [comment]
Works perfectly! 
Thank you for the link. It was very helpful

**Comment by Epix37** [comment]
Great :)
