### ISSUE TITLE
Does anyone use Rainmeter?

### ISSUE THREAD

**Issue by andburn** [Epix37/Hearthstone-Deck-Tracker#1233]
Ok so this isn't an issue with HDT and doesn't really belong here. But it is HDT rleated and I can't think of anywhere else for it at the moment. 

I made a plugin and sample skin for [Rainmeter](http://www.rainmeter.net) that uses HDT statistics to display your current ranked season progress. Anyone interested that uses HDT and Rainmeter can find out [more](https://github.com/andburn/hdt-rainmeter-stats) and download the [package](https://github.com/andburn/hdt-rainmeter-stats/releases/latest).

![Sample Skin](http://i.imgur.com/qrcBknh.png)

**Comment by MechaLynx** [comment]
Might be better to post this on [/r/hearthstone](https://www.reddit.com/r/hearthstone/) and/or [hearthpwn](http://www.hearthpwn.com/). It would get more visibility there and, as you state yourself, this is not the appropriate place to post this.

**Comment by andburn** [comment]
Yeah you're right, reddit is probably the best place.
