### ISSUE TITLE
Cards in hand don't have green text

### ISSUE THREAD

**Issue by Nerdy314159265** [Epix37/Hearthstone-Deck-Tracker#1234]
From the pictures of what the Overlay is supposed to look like, I can tell that the cards that are in my hand at the moment are supposed to have green text.

The only time that a card in the tracker has green text is when I use gang up. The minion I ganged up will have an entry added to the list separate from the rest of it's type and it will have green text.

![Just Hand](https://cloud.githubusercontent.com/assets/6250374/9298024/a37404f0-446d-11e5-8e8e-61cf2aca7be9.png)
![Gang-Up](https://cloud.githubusercontent.com/assets/6250374/9298023/a37044b4-446d-11e5-82bb-d74c12538657.png)

**Comment by culinko** [comment]
Check the setting in Options->Overlay->Player->Highlight cards in hand.

**Comment by Nerdy314159265** [comment]
*sound of hand hitting face* Delete this then.

I figured that it was something enabled by default or that didn't have an option. Just didn't see it when I went through the settings.
