### ISSUE TITLE
Exporting deck to Hearthstone not exporting all cards

### ISSUE THREAD

**Issue by DrMaple** [Epix37/Hearthstone-Deck-Tracker#1237]
I'm trying to export a deck and HDT keeps telling me I'm missing cards which I own. I made a video showing it. I turned the speed down to the slowest so it's easier to see.  

https://www.youtube.com/watch?v=5GBxbFlt0k8

**Comment by Epix37** [comment]
Have a look at this: https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/303#issuecomment-56195879

The important bit:
```
There is a pretty easy workaround. 
Find hearthstone.exe in C:\Program Files (x86), right click, 
and select Properties. Then go to the Compatibility tab. 
Check the box for "Run this program in compatability mode for" 
and select Windows 7. Then restart Hearthstone.
```

(I'm gonna add that to the FAQ)

**Comment by DrMaple** [comment]
Well, I looked through the issue tracker briefly but didn't find anything. Sorry for creating an issue when there's a fix already!

**Comment by Epix37** [comment]
No worries, it's pretty deep in there :).
