### ISSUE TITLE
Importing from game - detecting card counts

### ISSUE THREAD

**Issue by Epix37** [Epix37/Hearthstone-Deck-Tracker#1240]
So this is finally happening: 
http://gfycat.com/UnfitColdAmericantoad

- [x] ~~arena~~ Got something way better for arena now :)
- [ ] constructed
- [x] detect "more than 1"
- [ ] detect actual number
- [ ] GUI in overlay to initiate importing

**Comment by Cu8eR** [comment]
Any progress here? Really needed, it would save a lot of time for me and nerves

**Comment by Epix37** [comment]
Constructed importing is too unreliable for this to work.
