### ISSUE TITLE
Feature request: option to auto-use decks when selected

### ISSUE THREAD

**Issue by MyopicCat** [Epix37/Hearthstone-Deck-Tracker#1241]
Would it be possible to add an option like that? I often switch to a similar looking deck but forget to click the "use" button, and sometimes I don't discover the mistake until I've played several games. This messes up my stats and requires detective work and effort to clean up. Also I think the select/use system is clunky because it adds an extra (unnecessary?) step and the use/active text clutters up the deck list. For bonus points: when the option is active, hide the use/active text.

(This was the default behavior several versions ago. I assume the change was made to enable some advanced feature, but I don't understand which feature would require separated use & selection. Please enlighten me if this suggestion is no longer possible!)

**Comment by Epix37** [comment]
The main reason to separate select and use is that this enables you to look at other decks during games (and without iterating though the log everytime you click on another deck). 

With auto select working again since this update, you should usually not have the wrong deck active, even if you forget to click "use". Have you tried this since the update? (`MAIN > AUTO DECK SELECTION`).

**Comment by Epix37** [comment]
Nevertheless, I added an option for this now since it seemed pretty straight forward to implement. Will need some testing though... might break a few things here and there when enabled.

**Comment by MyopicCat** [comment]
Interesting, I haven't played today so I haven't tested the latest update. I don't know how auto deck selection works - I assume it can only choose decks based on the cards that have been drawn, right? So if two decks differ based on only a card or two, do have to draw those cards to distinguish them. Or is it smarter somehow?

Thanks for the new option!

**Comment by Epix37** [comment]
That's exactly how the detection works, yea. As soon as you draw a card that's not in the deck it will trigger. If you are often switching between very similar decks of the same class that would obviously be the same problem still.

**Comment by Epix37** [comment]
I guess this made it out quick. Had to release a crash fix, so this made it in :).

Let me know if you find any issues with it.
