### ISSUE TITLE
Hearthstone Deck Tracker.exe missing after lastest update

### ISSUE THREAD

**Issue by TheMieberlake** [Epix37/Hearthstone-Deck-Tracker#1244]
Hello,

I installed the latest update about an hour ago, and afterwards I couldn't open Hearthstone deck tracker. Upon investigation, I noticed that the .exe file (Hearthstone Deck Tracker.exe) that opens the program disappeared from the program folder. The closest thing I could find was "Hearthstone Deck Tracker.exe.config", which does not open the tracker.

I tried redownloading Hearthstone Deck Tracker, but I still couldn't find the .exe file. Can you help me out here?

Thank you so much for your help and for the great deck tracker!

![image](https://cloud.githubusercontent.com/assets/10902110/9313969/defcd598-44da-11e5-8abf-e531be4713ae.png)

**Comment by Epix37** [comment]
Try redownloading it here: https://github.com/Epix37/Hearthstone-Deck-Tracker/releases
and extract it to a new folder. The zip definitely contains the exe, I doublechecked :).

Maybe this is some antivirus problem?

**Comment by culinko** [comment]
Yeah, most likely the Antivirus issue.

On a related note, my HDTUpdate.exe couldn't update during the update process (I saw a warning in the HDT log after the update was done). The file is the same size, but just wanted you to know it happened.

**Comment by TheMieberlake** [comment]
Yes thank you, you were right: as it turns out my antivirus deleted the
.exe. I whitelisted the program, and it works fine, with all of my data
saved.

I tried playing a couple games without the Deck Tracker--I never realized
how much I relied on it until I did not have it!

Sincerely,
Justin
