### ISSUE TITLE
Cards in hand and deck counter not dissapearing even when I don't have a deck selected

### ISSUE THREAD

**Issue by SeraphineX** [Epix37/Hearthstone-Deck-Tracker#1245]
http://i.imgur.com/FfVXu3L.png

Is this intended? It's pretty annoying that I have to close the program when I want to do something else and the counters are blocking my view.

Seems like v0.10.10 should've fixed this but for me it hasn't.

**Comment by Epix37** [comment]
The probem is that the overlay is showing when you have something other than hearthstone in foreground, right?

You can fix that by enabling `options > overlay > general > hide if HS in background`.

**Comment by SeraphineX** [comment]
Thanks, I missed that option the first time that I went through the options, just started using the program like 2 days ago.

Works great so far, thanks.

**Comment by Epix37** [comment]
No problem :). Let me know if you have any more questions!

And while we're at it, let me point you to the [FAQ](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ) and [Overlay](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Overlay) sections in the wiki.
