### ISSUE TITLE
Game Not Recorded While Replay Viewer Open

### ISSUE THREAD

**Issue by mvordeme** [Epix37/Hearthstone-Deck-Tracker#1246]
Now and then, a friend challenges me while we are chatting about recent games. If I happen to have the replay viewer open, HDT fails to record the friendly game.

**Comment by Epix37** [comment]
Could you upload the log, the next time that happens?
[See here on where to find and upload the log](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)

**Comment by mvordeme** [comment]
Going to, thanks.

**Comment by mvordeme** [comment]
I ran a couple of tests, and it seems that this problem has disappeared. Closed.
