### ISSUE TITLE
Update prompt - "Not now" option

### ISSUE THREAD

**Issue by culinko** [Epix37/Hearthstone-Deck-Tracker#1247]
In regards to the latest update, I was in a middle of something, so didn't want to update right away, so clicked on the "Not now" option. Unfortunately, the button didn't work. I'm already on the newest version, though.

**Comment by Epix37** [comment]
That's how I get you to update ;).

Serious though, I can't seem to reproduce that issue. Lowering the version in the config.xml will get you the message, maybe you can.

**Comment by culinko** [comment]
Do you mean "CreatedByVersion"? If I change this, it will only tell me that the update was succesful.

**Comment by Epix37** [comment]
Sorry, I meant the version.xml in the application folder, not the config. I'm too used to writing "config.xml", lol.

**Comment by culinko** [comment]
Alright, tried to reproduce it again, but didn't happen this time. So probably GvG mechs fixed it in the meantime :P
