### ISSUE TITLE
Enchancement: Card tracking when using a card with multiple copies in deck

### ISSUE THREAD

**Issue by shikaku2** [Epix37/Hearthstone-Deck-Tracker#1250]
http://i.imgur.com/D5wN3mw.jpg

Like this image, notice the dark cultist.  It still has the 2 but it's half black because you drew one.  Can we have the card tracker work like that?

**Comment by Epix37** [comment]
This becomes problematic when dealing with more than 2 copies in arena decks.

HDT correctly displays what's left in the deck, so there's not really a need to do what they did video editing software.
