### ISSUE TITLE
Importing data from Hearthstone client

### ISSUE THREAD

**Issue by pivywiz** [Epix37/Hearthstone-Deck-Tracker#1252]
My deck tracker seems to be having an issue communicating with my hearthstone client. Trying to import will only pull up the instructions on how to do it, but will not actually do it. Setting the data path is an issue because whenever I attempt to do that, the browse box that appears gives me no option to find the directory folder for hearthstone. Any info greatly appreciated. Just want to use the deck tracker ;_;

**Comment by stdscatchemall** [comment]
Which type of import are you trying to perform?

**Comment by pivywiz** [comment]
Just any deck. Constructed and arena. I can make my deck manually via the tracker but it won't actually track anything because it's like its not communicating with the game client.

**Comment by pivywiz** [comment]
I guess something in the new version made it come to its senses and its working fine now. idk.

**Comment by stdscatchemall** [comment]
Glad to hear :)
