### ISSUE TITLE
Bug with deck export since TGT patch

### ISSUE THREAD

**Issue by needlessnoise** [Epix37/Hearthstone-Deck-Tracker#1253]
The Grand Tournament expansion has been added
![hearthstone screenshot 08-18-15 13 53 31](https://cloud.githubusercontent.com/assets/13856884/9339640/d57fe3c6-45b0-11e5-802d-54e630b476bb.png)
 and so now every time I try to export a deck to HS, it selects the basic set and only successfully exports the basic cards. I can't find an option to disable selecting the set automatically, either.

**Comment by Epix37** [comment]
Things for TGT will be fixed as soon as possible. I'm no wizard :). (wish I was though...)

**Comment by Epix37** [comment]
Things for TGT will be fixed as soon as possible. 

For this there is a temporary, manual workaround: 

* `options > tracker > settings > open appdata folder`
* close HDT
* open `config.xml` with text editor
* find this line `<ExportAllSetsButtonY>0.639</ExportAllSetsButtonY>` (~72)
* change the value to `0.607`
* save & close
* start HDT again, happy exporting!

**Comment by Epix37** [comment]
Should be fine with v0.10.11
