### ISSUE TITLE
Could not find Card XYZ in deck!, since recent update

### ISSUE THREAD

**Issue by gozo1985** [Epix37/Hearthstone-Deck-Tracker#1254]
Seems like there are poping up error messages with "Could not find Card XYZ in deck!" since the recent update. Looks like random card wheir chosen. No Dr. Boom for example in deck even if see it in the decklist on the right. Also happened to many other cards.

**Comment by gozo1985** [comment]
Sidenote: I do edit and save to current version very often and before that happenes. Might be a hint

**Comment by Epix37** [comment]
See #1253. Yes stuff is broken right now.
