### ISSUE TITLE
Card Tracking of Opponents Deck Is Not Working

### ISSUE THREAD

**Issue by Taho22** [Epix37/Hearthstone-Deck-Tracker#1255]
Hi.  Yesterdays patch was working fine for me.  Todays seems to have broke the card counting of the opponents deck.  The total cards at the beginning of a match is more than 30... like 35.  It stays incorrect throughout the match.  Also, the card labels for K, M, etc. are off.  Not sure what's going on.

Wanted to let you know.  Hope it can be fixed soon :)

**Comment by darius07** [comment]
I was just about to write about this. I can confirm with the 3.0.0 patch is not working properly. 
I also experience missing card pop-up even though the card is in my deck and the deck is the correct one.

**Comment by skaforey** [comment]
Can confirm this as well

**Comment by Epix37** [comment]
Working on it!

**Comment by Epix37** [comment]
v0.10.11 should fix most issues.
