### ISSUE TITLE
Incorrect overlay in Patch 3.0

### ISSUE THREAD

**Issue by culinko** [Epix37/Hearthstone-Deck-Tracker#1256]
Hey! I just observed that the overlay is incorrect in the newest HS patch. I drawn only 1 of 2 copies from my deck, but the overlay was dark, like if I had both copies in my hand. Card counter is also incorrect, it was showing 13 for my hand for a while. I suspect that they changed something within the logs, because for example I've found out that Arena rewards are not in Rachelle anymore, so maybe more things have changed.

**Comment by hazoz** [comment]
I have the same problem. Also the secrets disappear after a short while. When an opponent plays a secret, a list of possible secrets always shows up, but now it disappears after a couple of seconds. :/

**Comment by hazoz** [comment]
Also, when using Thoughtsteal, the program asks if to discard the game in the stats after the game, because there is a mismatch between the deck and the played cards. This did not happen before the 3.0

**Comment by Epix37** [comment]
v0.10.11 should fix most issues.
