### ISSUE TITLE
TGT fixes, need testers! 

### ISSUE THREAD

**Issue by Epix37** [Epix37/Hearthstone-Deck-Tracker#1257]
If anyone has some spare time:
* Download the version linked below
* Help me find remaining issues!
(Join us on gitter while you're at it :) https://gitter.im/Epix37/Hearthstone-Deck-Tracker)

I will probably end up posting multiple downloads here. 
~~There's the first: http://www.mediafire.com/download/s3sbmays3bviqb7/Hearthstone_Deck_Tracker-TGT-fixes_1.zip~~
number two: http://www.mediafire.com/download/hucc7g0g002iojh/Hearthstone_Deck_Tracker-TGT-fixes_2.zip

What seems to be fixed so far:
* Exporting to hearthstone
* Hand marks
* Card tracking
* Gang up (other generated cards, too?)

What seems to be fine:
* Arena importing
* Game mode detection
* Replays
* Game start/end / in menu detection
* Constructed importing
* generated cards, hunter: tracking

Broken:
* gold/wins counter [tracking gold might be fixable, win progress tracking seems to be gone]
* ~~generated cards detected as "not in deck"~~

**Comment by STORRM** [comment]
made gitter account DLing new tracker, is there any thing your looking for? i cant code or any thing ill just test stuff. i checked the beta updated box but "Latest BETA version: 0.10.8.0" lower then live, maybe roll out tester version as beta?

**Comment by Epix37** [comment]
I actually *need* feedback asap on these, that's why I'm not releasing them as beta updates.
Here is a new one that now also fixed Gangup and probably similar mechanics. These similar mechanics is what needs testing now. Things that put stuff in decks. Malorne, etc. 

Other than that I can't think of something specific right now. Play around with it, see if you notice anything.

**Here is the new download:** http://www.mediafire.com/download/hucc7g0g002iojh/Hearthstone_Deck_Tracker-TGT-fixes_2.zip

**Comment by STORRM** [comment]
well mediafire DLs at like 15-25BK/s and the tracker updates are more like 500+

i think recycle is going to take 2 ppl to test
i dont have malorne or iron Juggernaut, i would be willing to dust some stuff and craft Iron jug coz i like the idea in panda worrier but fuck crafting Malone.
if they work Beneath the grounds should probably work to.

only other weird deck bord interaction i can think of its Varian Wrynn putting 3 cards in to play from your deck kinda like revers death lord/mind games

**Comment by STORRM** [comment]
im STORRM #6859 on NA if you wont to test some stuff

**Comment by Epix37** [comment]
only have an EU account sadly :/

**Comment by STORRM** [comment]
do you have iron jug and recycle on EU pretty sure i did the used my EU account once

**Comment by STORRM** [comment]
gang up is totally working so is returned and generated cards. ill see if any one in my freind list has the cards

**Comment by STORRM** [comment]
just noticed the hide deck when friends list is open only works for me now when force on is on worked with out it ticked before patch

**Comment by MechaLynx** [comment]
Just confirming that generated Fireballs from Antonidas, Spare Parts and win/loss tracking appears to work perfectly fine.

**Comment by STORRM** [comment]
ok so recycle is not tracking, 2 time i had a cold light put back in to my deck and i drew it the same turn as the card drew the card got a red border to show i drew it but didnt put a copy in to the side tracker. another game healbot put back in to deck didnt show+1 or that i had only showed the other one i still had in deck.

**Comment by MechaLynx** [comment]
Recycle has apparently always been problematic, so not really a new issue.

**Comment by STORRM** [comment]
have you got malorne or iron Juggernaut to test mechalynx?

**Comment by MechaLynx** [comment]
Nope, neither unfortunately. We did just test Recycle though, so that's done.

**Comment by STORRM** [comment]
weird fel reaver doesn't show is burn cards any more, but thats on hearthstones side, i ges Fel reaver buff? you on NA mech? i have 7k dust i was saving to craft new legendarys i wont but ill craft jug to test deck tracker if some ones on NA

**Comment by Epix37** [comment]
this one should fix recycle and malorne (which werw not a new problem since tgt):
https://github.com/Epix37/HDT-Test/releases/tag/v0.10.TGT4

Should be the final test release

**Comment by STORRM** [comment]
how are you going to handle Joust? would be cool to see your ops Joust cards show up in like blue or something to show what they could draw

**Comment by Epix37** [comment]
Not sure yet. but something along those lines, yes.
Released the update. Thanks guys!
