### ISSUE TITLE
Use Automatically selected deck

### ISSUE THREAD

**Issue by dimadoniou** [Epix37/Hearthstone-Deck-Tracker#1258]
When you edit a selected deck (create new version), the deck is not automatically selected. It seems so but the selected deck is probably the previous version.

**Comment by Epix37** [comment]
Seems to work fine for me. 


**What I did**:
* Edit deck
* Make changes, save as new version

**Result:**
* Deck set to newest version
* Deck was set to active and selected
* Overlay also shows new version

**Comment by dimadoniou** [comment]
When you draw the cards that were added in the last version the system doesn't see them. When you finish the game the dialogue to save stats to the decks appears. If you don't draw the new cards you won't notice the difference.
(It is similar when you have the option "Automatically USE decks" unselceted. When you edit a deck you need to select the new version).

**Comment by dimadoniou** [comment]
It happened yesterday. I couldnt reproduce it today with the newest version. It seems fine.
