### ISSUE TITLE
Not Tracking When I Get A Card

### ISSUE THREAD

**Issue by bombdownx** [Epix37/Hearthstone-Deck-Tracker#1259]
The app has stopped showing me what cards I have used, instead my deck list just says there and doesn't move.

**Comment by Epix37** [comment]
Working on it!

**Comment by bombdownx** [comment]
Okay awesome!  I made another deck and it works for that one, will I have to remake all of my decks?

**Comment by zacklytle** [comment]
Not sure if this is related, but my tracking seems fine except I get "Warning! Card not found in deck: [x]" for a lot of cards across all decks.

**Comment by Epix37** [comment]
v0.10.11 should fix most issues.
