### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by Dodd8686** [Epix37/Hearthstone-Deck-Tracker#1260]
Since today, enabling this prevents me from loading into a game. Will just sit at the loading screen then get disconnected.  If I disable HDT, Hearthstone seems to work fine. Odd :(

**Comment by MechaLynx** [comment]
How consistent is this? Does it happen every single time?

**Comment by Dodd8686** [comment]
Yes every time. I've done this about 6-7 times now.

**Comment by Epix37** [comment]
Try updating to v0.10.11 and see if you still have the issue.
If so, try this: Close Hearthstone and HDT, go to `[Your Hearthstone Folder]/Hearthstone_Data`and delete the `output_log.txt`. Then try again.

**Comment by Dodd8686** [comment]
The problem persists. I tried installing the new version and also tried deleting the output log file.

**Comment by Epix37** [comment]
The only other thing I can think of right now that has sometimes an impact on performance is turning on/off windows aero. Maybe try that too.

**Comment by Dodd8686** [comment]
So it's mysteriously started working again after I repeated the steps above a couple time.It looks even better than before good job!
