### ISSUE TITLE
"Card not found" and Opponent's Hand tracker errors

### ISSUE THREAD

**Issue by Amaiar** [Epix37/Hearthstone-Deck-Tracker#1261]
Hi! Since I've been experiencing this and I've not seen anyone else report it in the last few days I thought about informing about it, just in case nobody else noticed.

Before last Patch everything was working just fine, but with some of the errors the new patch brought to the Deck Tracker, I found particularly 2 that are pretty annoying. It seems like the program has hard times trying to reset after each game, and even after I reset it manually, the error persists. It consist on the following:

If I'm playing with a deck (let's say a Deathrattle Shaman) and engage on several games in a row, almost every time I start a new game an error shows saying "card not found: Fire Elemental, Earth Elemental" for example. I've checked and the cards listed are included in the deck I built, so I'm not sure why exactly this happens but I think it has to do with the cards I had in my Hand last game.

At the same time, if I start a new game (with whatever deck I have), the opponents hand shows several marks that should not be there. Heck, his starting hand doesn't even have that many cards. I don't have a screenshot right now since I shut down the program until it gets some fixes, but for example sometimes it looks like my opponents hand consist purely on cards "Stolen" (it shows like 7 or 8 big "S" arranged like a hand, even if my opponent only has 3).

Both these issues made me think that something is wrong with the program resetting the data of each match before the start of the next one. Any Ideas?

**Comment by Epix37** [comment]
the TGT update broke a lot of things. Just release an update that should fix most (if not all) of it.
