### ISSUE TITLE
Cards not found in deck

### ISSUE THREAD

**Issue by SeraphineX** [Epix37/Hearthstone-Deck-Tracker#1262]
I have 8 games played with this deck: http://i.imgur.com/dcqdCBy.png

I made this deck 2 days ago if I'm not mistaken, today I've been playing with it and I'm constantly getting a warning message saying it didn't found certain cards in the deck, I double checked the deck and everything seems fine, the warning metions different cards every game.

**Comment by Epix37** [comment]
Todays hearthstone update messed a lot of things up. v0.10.11 was released a few minutes ago and should fix most (if not all) of the issues.

**Comment by SeraphineX** [comment]
Alright, keep up the good work and thanks. :D
