### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by astie85** [Epix37/Hearthstone-Deck-Tracker#1264]
Can i help with a Dutch translation? I notice all the HS players in The Netherlands i know use this software so maybe a Dutch translation would be nice.

**Comment by Epix37** [comment]
See #471.

It's planned eventuall but there is no ETA. Things keep changing and having to sort out over 10 translations ever time is not really the way to go. (Plus it's a huge amount of work to even integrate)

I did add you to the list in the linked issue though. I'll let you know when the time comes :).
