### ISSUE TITLE
Card counter.

### ISSUE THREAD

**Issue by dcsnunes** [Epix37/Hearthstone-Deck-Tracker#1267]
I would like to suggest to display close to your hand and you opponet's hand the numbers of cards both of them have in hand.
Thanks

**Comment by Epix37** [comment]
There is a hand and deck counter beneath the card lists.

**Comment by dcsnunes** [comment]
I mean, i wuold to see it everytime, not only when i hover the enemy deck list or mine

**Comment by Epix37** [comment]
I mean in the overlay, right underneath the list of cards HDT adds, there are also the counters.

**Comment by dcsnunes** [comment]
Cool, didn't realize it.
Thanks
