### ISSUE TITLE
Missing Arena Stats

### ISSUE THREAD

**Issue by samarthj** [Epix37/Hearthstone-Deck-Tracker#1268]
Since the update Release v0.10.9. All my arena decks and arena stats are missing. They have't showed up again in the next two updates either.

**Comment by Epix37** [comment]
Do you have any filters set (MAIN - QUICK FILTER -  ALL)  or the mode filter at the top of the deck picker set to constructed?

**Comment by samarthj** [comment]
I played around with all the filters. They just don't seem to exist anymore.

**Comment by Epix37** [comment]
Lets try this then: 
* Go to `options > tracker > backups`
* `Create new`
* `Show backup folder`
* Email the one that's called something like "BackupManual_17082015" to epikz37@gmail.com

Maybe I can see what's going on.
