### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by PappaJon** [Epix37/Hearthstone-Deck-Tracker#1269]
When ever i try to register for an account I get an error saying "The remote server returned an error: (522) Origin Connection Time-out". I've tried numerous amounts of times to create an account but same error every time

**Comment by Atebitss** [comment]
Same here man, i think it's just a server problem

**Comment by PappaJon** [comment]
Yeah, it sucks.

**Comment by Epix37** [comment]
Temporary server issues. should be back soon. Click "continue as guest"  for now.

**Comment by PappaJon** [comment]
Ok, thanks.

**Comment by GaryKing** [comment]
Is syncing to Hearth Stats still not working for anyone else? The site itself is up, but syncing still doesn't seem to work.
