### ISSUE TITLE
Not Tracking

### ISSUE THREAD

**Issue by Atebitss** [Epix37/Hearthstone-Deck-Tracker#1270]
I installed this earlier, couldn't sign in due to server issues, tried the deck import, didnt work very well, fixed the mistakes, played a game with the deck active and it didnt even track the cards, then i tried arena with the 'No Deck' and it didnt track the cards

**Comment by Epix37** [comment]
Try restarting Hearthstone, maybe that's enough already. if not, give this a shot: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#not-working
