### ISSUE TITLE
Export Problem: When Exporting to Hearthstone it clicks deck helper repeatedly and adds no cards

### ISSUE THREAD

**Issue by windcall** [Epix37/Hearthstone-Deck-Tracker#1275]
Clicks deck helper button over and over at top, then searches for cards without clicking on them to add them. 

http://pastebin.com/ViuCjZmT

**Comment by LLCoolRog** [comment]
This should be a sticky.
I had this issue along with a lot of other folks it seems.  The only issue for me was my Hearthstone game resolution setting.  In the game control panel it was blank, so I selected 1920x1080 and it works perfectly now on the defaults of:

  Fast (40ms)
  Prioritize golden cards
  Set deck name
  Auto clear cards
  Auto clear filters
  Show dialog before exporting.

Game on!

**Comment by Epix37** [comment]
Sadly github doesn't support stickies, but I added the solution to the FAQ: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#exporting-is-not-working-properly--missing-cards

Thank you for reporting back on that.
