### ISSUE TITLE
Gold Progress is not tracking

### ISSUE THREAD

**Issue by InsidiousJFP** [Epix37/Hearthstone-Deck-Tracker#1278]
After the last update HDT stopped tracking gold progress wins. Tried restarting HDT and Hearthstone but HDT still reads "Wins: 0/3 (10/100G)" even when I log in the next day it still reads the same. I really like this application and thanks a bunch for your hard work. :)

**Comment by Epix37** [comment]
That's actually a bug in hearthstone at the moment as far as I know. Currently there is no way to make this work again.

**Comment by InsidiousJFP** [comment]
Bummerino....oh well, thanks for the quick response.

**Comment by thufirh** [comment]
I was looking through the game logs trying to see what I could find, and after gaining the 3 wins gold I noticed the following in the Rachelle logs:
D 10:05:35.2196986 RewardUtils.GetViewableRewards() - processing reward [GoldRewardData: Amount=10 Origin=TOURNEY OriginData=0]
D 10:05:39.6329510 VictoryScreen.InitGoldRewardUI(): goldRewardState = INVALID

The second line shows up after every game, and I assume is why you are unable to track progress towards the gold reward. But that first line does show when a reward is given. Could this be used to at least track progress to the 100g daily limit? Also, since the tracker can tell wins from losses you could even make a guess about the progress towards the next pay out (a correct guess assuming the player never plays an un-tracked game.)

**Comment by chucklu** [comment]
Crash report
########## 2015/8/27 20:12:18 ##########
System.IndexOutOfRangeException: 索引超出了数组界限。
   在 Hearthstone_Deck_Tracker.OverlayWindow.UpdateGoldProgress()
   在 Hearthstone_Deck_Tracker.OverlayWindow.Update(Boolean refresh)
   在 Hearthstone_Deck_Tracker.MainWindow.<UpdateOverlayAsync>d__9e.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[20:11:16] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[20:11:16] OpponentSecrets: Cleared secrets
[20:11:17] DeckList: Set active deck to: 子非鱼猎人 (Hunter)
[20:11:20] Tracker: Set player itemsource as PlayerDeck
[20:11:20] Tracker: Switched to deck: 子非鱼猎人
[20:11:21] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[20:11:21] OpponentSecrets: Cleared secrets
[20:11:21] GameEventHandler: Reset constructed importing
[20:11:21] Helper: Checking for LIVE updates...
[20:11:21] Helper: Current version: 0.10.16.0
[20:11:21] BackupManager: Running BackupManager
[20:11:21] BackupManager: Backup for today already exists
[20:11:21] PluginManager: Loading Plugins...
[20:11:24] : Checking for duplicate matches...
[20:11:29] Helper: Latest LIVE version: 0.10.16.0

**Comment by RavenousSix** [comment]
I guess the gold tracking feature will never work again unless Blizzard fixes the bug?

**Comment by chucklu** [comment]
private void UpdateGoldProgress()
        {
            var region = (int)_game.CurrentRegion - 1;
            if (region >= 0)
            {
                LblGoldProgress.Text = string.Format("Wins: {0}/3 ({1}/100G)", Config.Instance.GoldProgress[region],
                                                     Config.Instance.GoldProgressTotal[region]);
            }
        }
region is 4
Config.Instance.GoldProgress  is  0,0,2 
Config.Instance.GoldProgressTotal is 10,20,0
 
so,the index is ouf of the array

**Comment by chucklu** [comment]
public enum Region
	{
		UNKNOWN = 0,
		US = 1,
		EU = 2,
		ASIA = 3,
		CHINA = 5
	}
so, 4 stand for what?

**Comment by chucklu** [comment]
I am trying to fix the size of 
Config.Instance.GoldProgress 
Config.Instance.GoldProgressTotal 
Config.Instance.GoldProgressLastReset

**Comment by chucklu** [comment]
[Rachelle] VictoryScreen.InitGoldRewardUI(): goldRewardState = INVALID
Rachelle for what?

**Comment by chucklu** [comment]
[Rachelle] RewardUtils.GetViewableRewards() - processing reward [GoldRewardData: Amount=10 Origin=TOURNEY OriginData=0]

**Comment by chucklu** [comment]
else if (HsLogReaderConstants.GoldProgressRegex.IsMatch(logLine)
                     && (DateTime.Now - gameState.LastGameStart) > TimeSpan.FromSeconds(10)
                     && game.CurrentGameMode != GameMode.Spectator)

I am not sure when HsLogReaderConstants.GoldProgressRegex.IsMatch(logLine) will be true
what's the content of logLine ,can make GoldProgressRegex.IsMatch(logLine) to be true?

**Comment by chucklu** [comment]
[Rachelle] RewardUtils.GetViewableRewards() - processing reward [GoldRewardData: Amount=40 Origin=ACHIEVEMENT OriginData=37]

I got another logLine 
this is a daily task,40 gold reward

**Comment by chucklu** [comment]
I find the rule about gold tracking.
I will try to fix this bug later

**Comment by chucklu** [comment]
fix this bug ,pls check this pull request
https://github.com/Epix37/Hearthstone-Deck-Tracker/pull/1359
