### ISSUE TITLE
Resetting stats on the app

### ISSUE THREAD

**Issue by EspenowE** [Epix37/Hearthstone-Deck-Tracker#1279]
Might just be me, but i cant find a way to reset the stats on the deck tracker. i love this app but i'd love to be able to reset the stats.

**Comment by Epix37** [comment]
What exactly do you mean by reset stats? Delete all recorded games? Delete all decks? both?

Deleting games:
* `STATS > STATISTICS & GAMES > Overall > Games`
* Set all filters to "All"
* Select any game in the list, press `ctrl + A`
* Click `DELETE` at the bottom

Deleting decks (also deletes games)
* Make sure all decks are visible
  * `MAIN > QUICK FILTER > ALL`
  * Select `ALL` in both bars above the deck picker
* Select all decks (select a single one, `ctrl+A`)
* Rightclick > delete

**Comment by EspenowE** [comment]
I ment just deleteing the recorded stats(games) 
Thanks for the fast reply!

**Comment by Epix37** [comment]
Creating a new version of a deck (`edit > SAVE > v1.1`) will also visually reset the stats in the deck picker. By default only stats for the selected version are displayed. This way can keep your old stats, too.

If you already deleted all games but like this solution better you can restore a backup via `options > tracker > backups` - select the latest and click `restore selected`.

**Comment by EspenowE** [comment]
Thanks alot!, no i just needed to reset the wins/losses with everything, as i did some test runs and i just gave up to see if the app was working. :)
Works Perfectly!
