### ISSUE TITLE
mad scientist doesnt seem to show up in my list of cards.. pls help//

### ISSUE THREAD

**Issue by ukscottyuk** [Epix37/Hearthstone-Deck-Tracker#1280]
I set up my mage deck and every other card is showing up and working as intended.. but for some reason when game starts and it shows decklist... the madscientists are missing.. i see my secrets and every other card... jus mad scientists dont seem to show up.. can anyone help pls??

**Comment by Epix37** [comment]
Is it actually in the deck you created in HDT? You can edit the deck by doubleclicking it or rightclick > edit deck.

**Comment by MechaLynx** [comment]
I've tested this using the latest release 0.10.11 and it works as it should. As Epix said, make sure it's in the deck you've made in HDT (if it _was_ made with HDT) and try 'Use no deck' to see if they show up then.
