### ISSUE TITLE
Not working in game

### ISSUE THREAD

**Issue by tiitiix** [Epix37/Hearthstone-Deck-Tracker#1281]
Hi guys,

i just updated HDT, and used it with arena helper.
it worked perfectly

but, in game, the tracker doesn't work. no cards, no probability...
i thought it was a bug in arena, so i tried a practice match.
same thing happens.
![capture](https://cloud.githubusercontent.com/assets/13888595/9385959/7bad406e-4759-11e5-97ca-0d380bb31db4.PNG)

you can see the picture

do you have any idea of what the problem could be?

it used to work before

**Comment by Epix37** [comment]
Hey,

the easiest solution could be simply restarting hearthstone.

If that does not help, try this: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#not-working

**Comment by tiitiix** [comment]
hey, that's good now, just path folder problem! thanks!

**Comment by Epix37** [comment]
no problem!
