### ISSUE TITLE
Enable adding game results for a new deck

### ISSUE THREAD

**Issue by veri745** [Epix37/Hearthstone-Deck-Tracker#1283]
I would like to be able to add game results to a deck after I create it.

One use case is starting an arena run, playing a couple games (with "no deck" selected). and then importing the deck.  HDT already saves replays of these games, but there is no way to attach that result to the newly created deck.

Another use case would be if you didn't have HDT running at the time (e.g. playing on a tablet or phone).  In this case, it would be nice if you could just add a W/L result to the deck.  This is probably more common that the first use case, actually.

**Comment by Epix37** [comment]
See here: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#how-can-i-add-games-manually

**Comment by veri745** [comment]
I swear I read the FAQ and didnt' see this before I created teh issue :/

**Comment by Epix37** [comment]
no worries :)
