### ISSUE TITLE
Brawl games aren't recorded as mode Brawl

### ISSUE THREAD

**Issue by riQQ** [Epix37/Hearthstone-Deck-Tracker#1284]
![hdt](https://cloud.githubusercontent.com/assets/3404787/9391538/8e61e232-4777-11e5-84ec-78a80c2b6780.png)

**Comment by andburn** [comment]
Have you got the replays/logs?

**Comment by riQQ** [comment]
Yes: http://pasted.co/b09961ca

**Comment by andburn** [comment]
Are you sure that log is from a Brawl game, its a game between a Paladin and Warrior?

**Comment by riQQ** [comment]
Oh I'm sorry. I took the last game, but now i see that no replays have been saved.

**Comment by andburn** [comment]
Mmm, Ok.
Are you using the latest version 0.10.11?
Check to see if Brawl is listed under the *Record For* section of `options > tracker > stats`, it is off by default. Although, it seems to be recording as none anyway so it can't be that.

**Comment by riQQ** [comment]
I'm so silly, I didn't select Brawl in the recording options.

**Comment by andburn** [comment]
I think something may still have gone wrong, because if it was off in the options then the games shouldn't have been recorded at all. In you screenshot the brawls were recorded as None. I'll test it out a bit.

**Comment by riQQ** [comment]
Yeah, you're right. But that's another issue.

**Comment by culinko** [comment]
@andburn If you're using no deck, games from all modes are still recorded as None and the matches will stay there until you restart the tracker. There's ticket for that (#1105), although I didn't test other modes than Practice/Spectate, I believe it happens with every mode.
