### ISSUE TITLE
Clicking on anything related to Internet connection crashes

### ISSUE THREAD

**Issue by DragonJockey** [Epix37/Hearthstone-Deck-Tracker#1285]
Clicking the links, hearthstats tab, plugins etc. causes crash.
Crash Report:

########## 20.08.2015 22:58:53 ##########
System.ComponentModel.Win32Exception (0x80004005): Uygulama bulunamadı
   konum: System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   konum: System.Diagnostics.Process.Start()
   konum: System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   konum: Hearthstone_Deck_Tracker.MainWindow.<ParseMarkup>b__60(Object sender, RequestNavigateEventArgs args)
   konum: System.Windows.Navigation.RequestNavigateEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   konum: System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   konum: System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   konum: System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   konum: System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   konum: System.Windows.ContentElement.RaiseEvent(RoutedEventArgs e)
   konum: System.Windows.Documents.Hyperlink.NavigateToUri(IInputElement sourceElement, Uri targetUri, String targetWindow)
   konum: System.Windows.Documents.Hyperlink.DoNavigation(Object sender)
   konum: System.Windows.Documents.Hyperlink.OnClick()
   konum: System.Windows.Documents.Hyperlink.DispatchNavigation(Object sender)
   konum: System.Windows.Documents.Hyperlink.DoUserInitiatedNavigation(Object sender)
   konum: System.Windows.Documents.Hyperlink.OnMouseLeftButtonUp(Object sender, MouseButtonEventArgs e)
   konum: System.Windows.Documents.Hyperlink.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   konum: System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   konum: System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   konum: System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   konum: System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   konum: System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   konum: System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   konum: System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   konum: System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   konum: System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   konum: System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   konum: System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   konum: System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   konum: System.Windows.ContentElement.RaiseTrustedEvent(RoutedEventArgs args)
   konum: System.Windows.Input.InputManager.ProcessStagingArea()
   konum: System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   konum: System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   konum: System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   konum: System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   konum: System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   konum: MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   konum: MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   konum: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   konum: MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[22:58:47] Game: set CurrentGameMode to None
[22:58:47] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[22:58:47] OpponentSecrets: Cleared secrets
[22:58:48] DeckList: Set active deck to: Aggro Paladin (Paladin)
[22:58:48] Tracker: Set player itemsource as PlayerDeck
[22:58:48] Tracker: Switched to deck: Aggro Paladin
[22:58:48] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[22:58:48] OpponentSecrets: Cleared secrets
[22:58:48] GameEventHandler: Reset constructed importing
[22:58:48] Helper: Checking for LIVE updates...
[22:58:48] Helper: Current version: 0.10.11.0
[22:58:48] BackupManager: Running BackupManager
[22:58:48] BackupManager: Backup for today already exists
[22:58:48] PluginManager: Loading Plugins...
[22:58:49] Helper: Latest LIVE version: 0.10.11.0

**Comment by Epix37** [comment]
From googling around a bit it seems like it's some misconfiguration on your end that's causing this.

http://stackoverflow.com/questions/21835891/process-starturl-fails#comment33051080_21835891

Maybe try changing your default browser and see if that does anything.

**Comment by DragonJockey** [comment]
Changing my default browser to Internet Explorer 11 solved the problem. Thanks!

**Comment by Epix37** [comment]
Might even work if you change it back now. Good to know that that works though :).

**Comment by DragonJockey** [comment]
It really does. Thanks again!
