### ISSUE TITLE
Can't export deck

### ISSUE THREAD

**Issue by Eroshark** [Epix37/Hearthstone-Deck-Tracker#1287]
When I try to export a deck from the tracker to the game it starts doing but then it tries to put 2 copies of each card in the deck even if it is only oncce in the deck and then it stops at 15/30 cards and tell me it doesn't find some cards

**Comment by Epix37** [comment]
Sounds like this might be your problem: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#exporting-is-not-working-properly--missing-cards

**Comment by Eroshark** [comment]
That was my problem thanks a lot, and next time I'll read the FAQ twice

**Comment by Epix37** [comment]
no problem!
