### ISSUE TITLE
Suggestion: automatically use no deck in spectator mode

### ISSUE THREAD

**Issue by iluvredwall** [Epix37/Hearthstone-Deck-Tracker#1288]
Basically as the title states; it would be nice to have an option to automatically enable "use no deck" while spectating games, because it's rare that a friend has the exact same deck that I do.

**Comment by ericBG** [comment]
Is there any way to do this manuall right now?

**Comment by Epix37** [comment]
Manually selecting "no deck"? `MAIN > USE NO DECK` or `"systemtrayicon" > use no deck`

**Comment by guillermocandia** [comment]
I put an option in tracker->general: Use no deck in Spectator mode.

Is it necessary to maintain selected the previous deck?
Could be a new property PreviousActiveDeck in DeckList and handle it in HandleGameEnd()
or just put that info in the config?
https://github.com/guillermocandia/Hearthstone-Deck-Tracker/commit/58ae5e8b3367357ef471f0d5bcf94430bd5f195c
