### ISSUE TITLE
Overlay doesn't hide in spectator mode

### ISSUE THREAD

**Issue by riQQ** [Epix37/Hearthstone-Deck-Tracker#1292]
Since the new version, overlay doesn't hide in spectator mode even though the option is selected.

**Comment by mvordeme** [comment]
Same here. HDT even selects a deck and then complains if there are cards missing. Seems connected to  #1265 and may have to do with the changes in logging with HS version 3.0.0.

**Comment by mvordeme** [comment]
Yikes! Now a spectated game was even recorded (no rank, unknown human player, 0 turns, mode NONE).

**Comment by culinko** [comment]
All of the games are still recorded if you use no deck (#1005).

**Comment by mvordeme** [comment]
Never happened to me before. Sometimes I wish games would be recorded, e.g. in TGT Brawl to be able to reconstruct the decks, but they aren't. This was the first time.

**Comment by mvordeme** [comment]
confirmed
