### ISSUE TITLE
Indicate the number for a card that is played by the opponent

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#1296]
If the opponent plays the card that they drew on turn 3, then could HDT please indicate this? 

Either by adding a number below the card when it's on the board that says "3", or if that's too difficult (since the cards will shuffle around a lot), then perhaps place the "3" below the card when it is played? Since all played cards appear in the exact same spot, on the left-hand side.

It can be helpful strategically to know that a player drew what card on what turn. For instance, if they play Flamestrike on turn 9, and the number says 7, then you might wonder why they didn't play it on turn 7, etc.

**Comment by Epix37** [comment]
#1031
