### ISSUE TITLE
Replay Viewer sometimes indicates which cards the opponent discarded during the mulligan phase

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#1297]
In the Replay Viewer, sometimes on turn 0 it displays what cards the opponent apparently mulliganed/discarded. 

That doesn't make sense, because the app shouldn't even know what cards were discarded, should it? Or is that just a bug?

**Comment by Epix37** [comment]
Deduction. Cards are entities and have two kinds of ids: a cardId (identifies which card it is) and an entityId that's unique in each game. If the opponent draws and mulligans a card with entityId 5, you don't know what that card is at that point but as soon as the plays it you can deduce that he mulliganed that card.

**Comment by everchump** [comment]
I think HDT shouldn't display the opponent's discarded cards. 

By paper or pen，you shouldn't know the entityid of a discarded card .  So you shouldn't know which card your opponent have discarded.
