### ISSUE TITLE
Repeating Matches in Constructed/Restoring Last Played Deck

### ISSUE THREAD

**Issue by RMcD94** [Epix37/Hearthstone-Deck-Tracker#1300]
Hi, I fought the same opponent in a row. I had played his deck to almost fatigue (he had 5 cards hidden). We both queued again instantly.

I would like a button to press that restores your opponents last tracked deck. And then does the same thing by removing them when they are played from the list.

Thank you.

**Comment by STORRM** [comment]
you can just look at last played show ops deck. the dev has said he doesn't like the idea of showing it on screen and wont do that. i asked for the same thing.
