### ISSUE TITLE
Suggestion: Track Testing of Secrets

### ISSUE THREAD

**Issue by mvordeme** [Epix37/Hearthstone-Deck-Tracker#1301]
I know that experienced players probably don't need this, but in the confusion of combat, it would often be nice to know which secrets I have already tested for. Depending on whether each played secret can be tracked individually, this could be more or less sophisticated.

Example (against Mage):
1. opponent plays secret (1)
2. I play a minion; nothing happens => *mark Mirror Entity as tested (maybe greyed out)*
3. opponent plays secret (2) => *remove all marks*
4. my minion attacks the enemy hero; nothing happens => *mark Ice Barrier and Vaporize as tested*
5. I cast a spell; Counterspell is triggered.

Now, depending on whether individual secrets can be tracked or not, the following things could happen next:
* HDT does not know whether secret (1) or secret (2) was triggered => *mark Counterspell as tested*
* HDT knows that secret (1) was triggered => *mark Counterspell as tested*
* HDT knows that secret (2) was triggered => *mark Counterspell and Mirror Entity as tested*

Whenever an opponent has played the same secret twice, already, and not obtained any spells during the game, that secret can always be marked.

In a complex situation with many secrets played, this could be quite useful. Maybe the option "automatically gray out secrets" means exactly this, but if it does, it doesn't work for me.

**Comment by Epix37** [comment]
See #548.

Should come eventually!

What you can do now: Enable `options > overlay > interactivity` to manually grey out secrets by clicking on them.
