### ISSUE TITLE
Export Problem

### ISSUE THREAD

**Issue by Harrock** [Epix37/Hearthstone-Deck-Tracker#1303]
When I export a deck it will only search the basic set. I reloaded the program and changed the set in Hearthstone but it doesn't change. Is there a setting I need to adjust?

**Comment by Epix37** [comment]
Did you update to v0.10.11? (https://github.com/Epix37/Hearthstone-Deck-Tracker/releases)

**Comment by Harrock** [comment]
Yes I did.

**Comment by Epix37** [comment]
* `options > tracker > settings > open appdata folder`
* close hdt
* open config.xml with any text editor
* make sure ExportAllSetsButtonY is set to this value: `<ExportAllSetsButtonY>0.607</ExportAllSetsButtonY>`

**Comment by Harrock** [comment]
This is what is has:
<ExportAllButtonX>0.06</ExportAllButtonX>
  <ExportAllButtonY>0.915</ExportAllButtonY>
  <ExportZeroButtonX>0.118</ExportZeroButtonX>
  <ExportZeroButtonY>0.917</ExportZeroButtonY>
  <ExportZeroSquareX>0.108</ExportZeroSquareX>
  <ExportZeroSquareY>0.907</ExportZeroSquareY>
  <ExportSetsButtonX>0.049</ExportSetsButtonX>
  <ExportSetsButtonY>0.917</ExportSetsButtonY>
  <ExportAllSetsButtonX>0.067</ExportAllSetsButtonX>
  <ExportAllSetsButtonY>0.639</ExportAllSetsButtonY>

**Comment by Harrock** [comment]
<ExportAllButtonX>0.06</ExportAllButtonX>
  <ExportAllButtonY>0.915</ExportAllButtonY>
  <ExportZeroButtonX>0.118</ExportZeroButtonX>
  <ExportZeroButtonY>0.917</ExportZeroButtonY>
  <ExportZeroSquareX>0.108</ExportZeroSquareX>
  <ExportZeroSquareY>0.907</ExportZeroSquareY>
  <ExportSetsButtonX>0.049</ExportSetsButtonX>
  <ExportSetsButtonY>0.917</ExportSetsButtonY>
  <ExportAllSetsButtonX>0.067</ExportAllSetsButtonX>
  <ExportAllSetsButtonY>0.639</ExportAllSetsButtonY>

**Comment by Harrock** [comment]
Thank you very much for the help and all the time you put into this app - it is great!!
