### ISSUE TITLE
Stretched Textures

### ISSUE THREAD

**Issue by Eon-Drache** [Epix37/Hearthstone-Deck-Tracker#1304]
Getting stretched textures whenever I mouse over anything that acts as a button. Below is a SS that shows the bug. 

http://i.imgur.com/D1hBYNH.png

Using Windows 10 x64. However, I was getting this issue with Windows 7 x64, too.

**Comment by Epix37** [comment]
Uuhmm... #103 was the same issue I think. Doesn't seem like we actually found a solution.
Try updating your video card drivers.

**Comment by Eon-Drache** [comment]
It happens with the Curse Client as well.... Does the tracker use Flash or Java or anything for its graphics? My graphics driver is up to date.

**Comment by Epix37** [comment]
It's using WPF.

**Comment by Eon-Drache** [comment]
I would think it has something to do with the animations, maybe or the buttons? Cause it's only things that are animated that cause it for me.

**Comment by Epix37** [comment]
No animations there. I have no idea what this might be tbh.
