### ISSUE TITLE
Spare parts...not tracking

### ISSUE THREAD

**Issue by 305jeff** [Epix37/Hearthstone-Deck-Tracker#1307]
Warning: Cards not found in deck: Reversing Switch. Armor Plating.

**Comment by Epix37** [comment]
Not able to reproduce this.

Does that happen consistently?
The next time it does, please post the HDT log ([see here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)) and replay (*.hdtreplay) from that game (in the *Replays* folder in AppData)

**Comment by 305jeff** [comment]
Will do. Thanks!
