### ISSUE TITLE
"can't find Hearthstone window"

### ISSUE THREAD

**Issue by MaestroFuego** [Epix37/Hearthstone-Deck-Tracker#1308]
Hi.

I have the Problem that the Tracker dont interact with my game. First i didn't know why. I made a Deck in the Tracker that i play in the game. But when i play constructed the decklist didn't change when mulligan or drawing cards.

I tried alot to fix this. I set the path of the game in the options. i googled it but only one other person (here in the forum) had the same problem ("can't find Hearthstone window". ). but it was fixed by a newer version. i have the latest version so that will not help. I didnt have an asian version of Hearthstone either.

When i try to export a Deck from the Tracker into the Game it says "can't find Hearthstone window". 
I tried it in Full Screen and Window Screen mode with Hearthstone.

Any Ideas?

greetings for now. Sorry for my bad english

**Comment by MaestroFuego** [comment]
No one? :(

**Comment by MaestroFuego** [comment]
ahhh come on guys!

**Comment by riQQ** [comment]
Have you tried toggling the option `Tracker -> Settings -> Advanced window search`?

**Comment by MaestroFuego** [comment]
First, thanks for a suggest! I tried both, still the same outcome. This programm still cant find my hearthstone window :/

**Comment by Epix37** [comment]
That means it can for some reason not get the hearthstone window in foreground. Try turning on/off window mode gets you any different results.

**Comment by MaestroFuego** [comment]
Yeah also tried both modes. same problem.

**Comment by MaestroFuego** [comment]
sorry but are there better suggestions, than the obvious ones? iam not new to have problem with programms. i use windows over 20 years. posting here is the last outcome for me. there has to be a guy with knowledge i dont have. pls be there.

and thanks epix for the answer but youre suggestion is already mentioned in my original post...

**Comment by andburn** [comment]
This must be something to do with your specific setup. Here are some things you could do that might help us:

1. What version of windows is it 7,8 or 10?
- What other programs are running when this happens?
- Download & run [WinSpy](http://www.catch22.net/software/winspy-17) and put Hearthstone in windowed mode, drag the icon from WinSpy to the Hearthstone window. Post a screenshot like the one below with the result.

![winspyhs](https://cloud.githubusercontent.com/assets/5419653/9656047/4d67f314-522d-11e5-8ef3-c1c579415569.png)

**Comment by MaestroFuego** [comment]
Ok. I have Windows 7 64Bit. I run Chrome on a Second Screen most of the Time. Then Comodo Internet Security in Gaming Mode.

This is what the programm pulled out:

![decktr](https://cloud.githubusercontent.com/assets/13946165/9657165/ebdcba00-523e-11e5-8d75-8c3b1125cf03.png)

hope that can tell you something

**Comment by MaestroFuego** [comment]
If the Deck Tracker would have a Finder Tool like this Programm, that should fixed the Problem i guess. That would be cool Plugin

**Comment by MaestroFuego** [comment]
And this is what happen when i try export a Deck from DeckTracker into the Game
![export](https://cloud.githubusercontent.com/assets/13946165/9657370/9d83f63c-5240-11e5-8b43-2a338561d434.png)

**Comment by Epix37** [comment]
It's most likely not that HDT can't find the window handle but can't get it to foreground. 
Try this:
* Go to `options > tracker > exporting` and set `Wait 0 seconds before starting` to 3.
* Start the exporting and when it says "please dont move your mouse..." tab to the hearthstone window.

**Comment by MaestroFuego** [comment]
Tried it with Window and Without Full Screen Mode. Not working :/

**Comment by andburn** [comment]
Ok, so it wasn't what I thought. I do notice there is a green box around your HDT windows. Some quick googling tells me Comodo is running HDT in [sandbox mode](https://help.comodo.com/topic-72-1-451-4768-.html) which must be limiting its actions. You'll have to some research, but you should be able add an exception according to that article.

**Comment by MaestroFuego** [comment]
Damn youre a Hawkeye. That Sandbox thing fixed the Problem! Thank you very much. I couldnt figure out how to make an exception in for the sandbox, but when i turn it off it works.

Thanks Man!

**Comment by andburn** [comment]
No problem. Glad we found out what it was in the end!

**Comment by Epix37** [comment]
:+1: andburn!
