### ISSUE TITLE
Overylay problem

### ISSUE THREAD

**Issue by LOVEkillU** [Epix37/Hearthstone-Deck-Tracker#1309]
Since this new patch i cant put the deck tracker on my stream becouse the windows dont tracker de overylay, any ideias?

**Comment by Epix37** [comment]
Which window? I just tested Player and Opponent, both seem fine. The overlay was never captureable, and if the plugin is not yet fixed, it should be soon. I think this is the new version (he accidentally released too early): https://github.com/stdscatchemall/HDTCompatabilityWindow/releases/tag/0.1.0
