### ISSUE TITLE
Number of minions, spells and weapons on hearthstats.net

### ISSUE THREAD

**Issue by captBond** [Epix37/Hearthstone-Deck-Tracker#1310]
Good day.
I use the program Hearthstone Deck Tracker 0.10.13. Uploaded decks do not reflect the number of minions, spells and weapons. Screenshot attached. Please tell me how to fix it.

Sincerely.
Den.

**Comment by Epix37** [comment]
I think you missed the screenshot :).

Could you post the hearthstats url of the deck?

**Comment by captBond** [comment]
![2015-08-23 12-13-41](https://cloud.githubusercontent.com/assets/13920423/9446171/d033df0c-4a98-11e5-9c29-5310ebf46fdd.png)

My mistake. )
This one? http://hearthstats.net/decks/08-2015?locale=en

**Comment by trigun0x2** [comment]
Hey @captBond we've had an issue recently and there's a huge backlog of tasks which is suppose to update that value. Hopefully we can get through them soon.
