### ISSUE TITLE
Crash after picking (last) arena card

### ISSUE THREAD

**Issue by jheiv** [Epix37/Hearthstone-Deck-Tracker#1312]
I just finished an arena draft, clicked my last card (Recruiter) and the program crashed.

For what it's worth, on re-opening the program, it gave me the "new arena deck" notification properly, without issue.

Crash log:
http://pastebin.com/5JWL8V5Z

**Comment by Epix37** [comment]
Mhh...

Since it didn't show the last card, it crashed somewhere before this line?  https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/Hearthstone/GameV2.cs#L934

... I'm not sure what's supposed to be null here. Anyone seeing something I don't?
