### ISSUE TITLE
Tracking Messed Up Somehow?

### ISSUE THREAD

**Issue by Aphoristic** [Epix37/Hearthstone-Deck-Tracker#1313]
I was playing vs a Paladin.  He dropped Tuskkar Jouster and Argent Lance one after another and it broke the tracking.  The tracker kept flipping between the cards actually drawn and nothing at all having been drawn.

**Comment by Epix37** [comment]
Do you still have the same HDT session running? If so, or if you encounter this again, please post the log here. [(Where to find and how to post logs)](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)

**Comment by Aphoristic** [comment]
No, sorry.  If it comes up again I'll let you know.

**Comment by ImTechtron** [comment]
I had this happen to me during an arena game. It was one or two games after the 0.10.14 updated. It was also having trouble 'following' the window when moved while it was happening. Hope this helps! BTW, I like the new arena import - works great!
