### ISSUE TITLE
Cloning a "Selected Version" of a deck results in the most recent version being cloned instead.

### ISSUE THREAD

**Issue by Contestest** [Epix37/Hearthstone-Deck-Tracker#1316]
For example, if I have a deck with v1.0 and v1.1 saved in it. Trying to clone only v1.0 of said deck results in v1.1 being cloned instead.

Tested with a deck with v1.0-v1.4 saved, regardless of the selected version, v1.4 is always cloned

Hearthstone Deck Track Version 0.10.13

**Comment by Epix37** [comment]
fixed with v0.10.14
