### ISSUE TITLE
Deck Tracker prevents quickswitching desktops on Windows 10

### ISSUE THREAD

**Issue by chaorace** [Epix37/Hearthstone-Deck-Tracker#1321]
In Windows 10, when using the keyboard shortcuts (win+ctrl+left/right) while HSDT is open, the desktop switching animation will run but immediately refocuses the Hearthstone window. This doesn't happen when using the desktop switcher menu (win+tab).

**Comment by MechaLynx** [comment]
What are your selection options under `options` -> `tracker` -> `general`?

**Comment by chaorace** [comment]
Screengrab: http://i.imgur.com/2J2mj3e.png

**Comment by MechaLynx** [comment]
Try removing the "Flash Hearthstone on turn start" option and see if the behavior persists.

**Comment by chaorace** [comment]
Just tested, doesn't fix the problem. I'm pretty sure this started happening only after the HSDT TGT update

**Comment by MechaLynx** [comment]
Just in case and for the sake of completeness, have you tried switching with HDT _not_ running?

**Comment by chaorace** [comment]
Just checked the same scenario with HSDT off, can't replicate the problem

**Comment by MechaLynx** [comment]
Ok, I assume you're using v0.10.13 now, which version did you upgrade to the latest from? In other words, which was the last version you used that didn't have this problem?

**Comment by chaorace** [comment]
I can't tell if the last version without this problem was v.0.10.11 or v.0.10.12. There was only a small time when I was using v.0.10.12, so I can't be sure.

I'll try testing later if you need me to

**Comment by MechaLynx** [comment]
That should do, just need to know the range of commits to check for this. I can't replicate the behavior because I don't have Windows 10, but someone else might and this way it's easier to know where to look for whatever broke this.

**Comment by dpedigo** [comment]
Good catch! I didn't even think to test with the virtual desktops. Looks like it was caused by the change I made to prevent the overlay window from showing when Alt+Tabbing. I found an alternative way to prevent that and it happens to play nicer with desktop switching.

Must say I'm a bit disappointed with the way they implemented the virtual desktops...

**Comment by Epix37** [comment]
So the solution here might be add an option (or make it automatic based on OS) to set 
``` 
User32.SetWindowExStyle(hwnd, User32.WsExTransparent);
```
or
```
User32.SetWindowExStyle(hwnd, User32.WsExTransparent | User32.WsExToolWindow);
```

without settings the overlay owner to mainwindow. This way it results either in the overlay being visible in the alt-tab switcher or it not working with virtual desktops. Maybe there is a solution for everything?

For the time being, anyone having this issue: feel free to use v0.10.15 if you don't mind your HDT window being always on top.

**Comment by dpedigo** [comment]
Not home at the moment so I'm going off memory. 

Tool windows apparently are shown across all virtual desktops. So the User32.WsExToolWindow flag triggers this particular [piece of code](https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/Windows/OverlayWindow.xaml.cs#L466) during the virtual desktop switching (only via the hotkeys).

When you switch to another desktop via the hotkey the overlay is still the foreground window on the new dekstop. This causes it to bring Hearthstone to the front which is in a different virtual desktop so it switches back quickly.

Removing that code did fix the switching issue for me, but I wasn't sure what side effects it would have with other configurations so I went with what seemed the safer bet at the time by making it an owned window. And now we all know how poorly I test outside of my own use case (windowed with multiple monitors.) :frowning: 

Thoughts? Maybe an option would be a decent direction to go?
