### ISSUE TITLE
Games keep getting copied

### ISSUE THREAD

**Issue by YvesW** [Epix37/Hearthstone-Deck-Tracker#1325]
I just noticed that there are multiple games that keep getting copied. It might have something to do with the hearthstats sync, which fails very often for me. Screenshots are pretty self-explanatory. I haven't played the druid deck in ranked for at least a week probably, but the tracker thinks I've played the same hunter 58 times.
![Hunter](https://cloud.githubusercontent.com/assets/7929021/9482952/42a25fda-4b9a-11e5-82f6-1c130399521d.PNG)
![Druid](https://cloud.githubusercontent.com/assets/7929021/9482954/476b56ac-4b9a-11e5-8f90-7ccdbee42bc2.PNG)

**Comment by Epix37** [comment]
See #1323. Fix it on the way!

**Comment by YvesW** [comment]
I really need some glasses... Great that it's being fixed and thanks for HDT; it's a great tool!
