### ISSUE TITLE
Opponent card age in spectator mode

### ISSUE THREAD

**Issue by flapjack831** [Epix37/Hearthstone-Deck-Tracker#1328]
When I have HDT loaded while spectating a friend play a game, the enemy's card ages are all broken (generally have a combination of 0's, 1's, and -1's rather than the expected 0, 1, 2, 3, etc.). Same goes for the mulligan/keep tracking (everything is usually listed with a K).

**Comment by Epix37** [comment]
If you join in the middle of a spectator game a lot of information is missing. You can set the overlay to hidden while in spectator (option > overlay > general).

**Comment by flapjack831** [comment]
This bug occurs even if I'm spectating from the very beginning, including the mulligan.
