### ISSUE TITLE
Opponent's Cutpurse displays created card instead of coin in hand.

### ISSUE THREAD

**Issue by zachwlewis** [Epix37/Hearthstone-Deck-Tracker#1332]

**Comment by Epix37** [comment]
It's not wrong!

**Comment by zachwlewis** [comment]
It could be more right!

**Comment by GaryKing** [comment]
This needs a few more fixes too.

Like: If Duplicate is used by the opponent, then HDT should know what the two created cards are. It displays the "created card" symbol, but hovering that should show exactly what card they are. It doesn't seem to do that right now.

The same goes for King Mukla, who gives the opponent two bananas. Those bananas should be explicitly marked as bananas somehow, such as when hovering.

**Comment by Epix37** [comment]
Closing in favor of #2224.
