### ISSUE TITLE
Remove the secrets of the opponent

### ISSUE THREAD

**Issue by nitratus** [Epix37/Hearthstone-Deck-Tracker#1333]
It would be nicer if we can choose what's opponent secrets are, For example:
My opponent (hunter) plays a secret , the deck tracker show me what secrets can be, if I attack directly the opponent does not active any secrets , then you can exclude ( automatically or by yourself ) the secrets that can not be, cliking on secrets that can not be for exclude it

**Comment by Epix37** [comment]
See #548.

Should come eventually!

What you can do now: Enable `options > overlay > interactivity` to manually grey out secrets by clicking on them.

**Comment by nitratus** [comment]
ah perfect, realy thanks
