### ISSUE TITLE
HDT window stealing top-layer display

### ISSUE THREAD

**Issue by thufirh** [Epix37/Hearthstone-Deck-Tracker#1335]
I am using a PC with Windows 7 Home Edition, and running Hearthstone in windowed mode. The problem began with the most recent update.

After giving focus to any other window and subsequently giving focus back to the Hearthstone window, the HDT window will be displayed as the upper most window but the Hearthstone window maintains focus. This happens if you Alt-Tab, start bar icon click, or visible window portion click into Hearthstone. The only way this does not happen is if you click the title bar of the Hearthstone window.

I have not tested this with full screen mode.

**Comment by MechaLynx** [comment]
I can confirm this, Win7 Pro x64, using v0.11.15. I hadn't observed this happening before, even though I often use both windows open and overlapping in order to compare if I've transferred a deck properly to HDT.

The behavior is exactly as described by the OP. I did test with fullscreen and it happens there as well.

**Comment by thufirh** [comment]
Pops up in log as soon as window is brought to top:

[10:25:04 AM] UpdateOverlay: Refreshed overlay topmost status

**Comment by Epix37** [comment]
No problems with Win10 *sigh*...

How bad is this? Immediate fix or would -say- next week be fine?

**Comment by thufirh** [comment]
I can live with it. Would depend on how bad it affects full screen players.

**Comment by Epix37** [comment]
Can someone tell me if this is a problem with Win8? Would be a simple fix if it's only Win7 or lower.

**Comment by Epix37** [comment]
Okay, back to normal with v0.10.16. I've had better days...

**Comment by MechaLynx** [comment]
Doesn't fixing this restore issue #1321? I don't see why this can't be a conditional behind a setting, preset depending on the detected OS version. It's fine if a restart is required.

**Comment by Epix37** [comment]
I *did* have the same issue with Win10 afterall.
