### ISSUE TITLE
Export deck as screenshot cropped

### ISSUE THREAD

**Issue by hetoord** [Epix37/Hearthstone-Deck-Tracker#1338]
Exporting a screenshot of a deck results in a cropped image. All decks seem to do this. I can't reproduce this on any other computers at the moment as I have no others available, so someone else might have to confirm if this is a bug or a human error on my part.

<img width="115" alt="utopia control" src="https://cloud.githubusercontent.com/assets/4848211/9501595/6dc4fa28-4c2c-11e5-97b1-ffe796caea12.png">

**Comment by Epix37** [comment]
It's related to your dpi settings. This currently happens when the dpi is set to something >100%.

**Comment by Kharnacier** [comment]
For those, like me, who don't know how to set dpi to 100% (it's in windows properties) : https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/496
Hope it helps :)

**Comment by Epix37** [comment]
Seems to be fixed with 9153391.

**Comment by culinko** [comment]
Is this same as #496?
