### ISSUE TITLE
Tag decks by expansions

### ISSUE THREAD

**Issue by formigao** [Epix37/Hearthstone-Deck-Tracker#1340]
this can be a minor issue.. but recently i had to delete all my decks and make new ones because i just couldn't remember which one i had updated...

If we had a tag with the futures decks that shows WHEN the deck as created / last time updated. 

could be a note next to score or before the hero icon.

This would help a lot.

**Comment by MechaLynx** [comment]
This should be possible to do as an enhancement.

However, if you, or anyone else who has the same need, have to check the last update to the deck, you can see it in `PlayerDecks.xml` which is in `%USERPROFILE%\AppData\Roaming\HearthstoneDeckTracker\` and you can get there through `options` -> `tracker` -> `settings` -> 'open appdata folder`. Once you open it, you can see each deck's last update at the bottom of the info for the deck.

**Comment by anonymous555** [comment]
I already asked for this here
https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1044

He shows it when you edit a deck, but it would be much better to show this on the deck picker without editing.

**Comment by jleclanche** [comment]
Decks now display their last updated time.
