### ISSUE TITLE
issue when exporting

### ISSUE THREAD

**Issue by kyle81298** [Epix37/Hearthstone-Deck-Tracker#1341]
when I attempt to exporta deck, deck tracker chooses the basic card set but never unselects the basic cad set and it results it the deck not being fully exported

**Comment by MechaLynx** [comment]
Have you tried [lowering the export speed](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#exporting) from `options` -> `tracker` -> `exporting` -> `speed`?

**Comment by kyle81298** [comment]
I will give it a shot, but I didn't raise the speed

**Comment by koalafishy** [comment]
Try running Hearthstone in Windows 7 compatibility mode, that fixed the problem for me

**Comment by quark-zju** [comment]
I believe it's related to Windows 10. See my detailed comment at https://github.com/ko-vasilev/Hearthstone-Collection-Tracker/issues/25#issuecomment-135025630

Either Win 8 or WIn 7 compatibility mode should workaround the issue.
