### ISSUE TITLE
Couple of crashes while playing brawl.

### ISSUE THREAD

**Issue by TehJumpingJawa** [Epix37/Hearthstone-Deck-Tracker#1342]
Warlock against various opponents in brawl 11.

https://dl.dropboxusercontent.com/u/54785909/Crash%20report%202682015-1957.txt

https://dl.dropboxusercontent.com/u/54785909/Crash%20report%202682015-2256.txt

https://dl.dropboxusercontent.com/u/54785909/Crash%20report%202782015-013.txt

**Comment by TehJumpingJawa** [comment]
Have a couple more examples if you need them, though they all point to the same cause.

**Comment by MechaLynx** [comment]
I just got a crash playing Warlock in Brawl as well:

[Crash report 2782015-187](http://pastebin.com/Lnyftseu)

[log file](http://pastebin.com/M1v3t8GC)
