### ISSUE TITLE
HDT claims opponent's spare part is the same as mine, even when it isn't

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#1344]
I played Mechanical Yeti, and it died, so both I and my opponent got a spare part.

The one I got was Coolant. When I hover over the spare part that my opponent got, it also says that it's Coolant, too, but when he plays it, it's actually +1 Attack.

So it looks like HDT assumes that the spare part the opponent gets is the same as yours, even when it isn't.

**Comment by dvide** [comment]
Same thing with Spellslinger I've noticed :)

**Comment by Epix37** [comment]
Same thing with a lot of things actually. Currently it looks for last entity id used before that card was created. It's far from correct in most cases but gives you the general idea.

**Comment by GaryKing** [comment]
Probably better to not even bother guessing what card was given to the opponent, because if it's wrong then it can be misleading and therefore possibly dangerous. If you assume that the card the opponent was given is +1 Attack because HDT says so, for instance, then you would play around that, etc.

**Comment by GaryKing** [comment]
Also, for the Cutpurse card, when it attacks a Hero, it awards its user with a Coin. HDT should immediately mark the card given to the opponent as a Coin, since it obviously is one.
