### ISSUE TITLE
Show only the turn timer

### ISSUE THREAD

**Issue by culinko** [Epix37/Hearthstone-Deck-Tracker#1348]
I realized I don't really use any of the other 2 timers, so it would be great if there was a setting to hide the top and bottom timers. Thanks! :)

**Comment by Epix37** [comment]
* options > overlay > general > unlock
* move main timer all the way to the left
* move small timer all the way to the right
* move main timer back

**Comment by culinko** [comment]
Nice little hacks you got there :)
