### ISSUE TITLE
Stats can't be properly filtered via "Version"(selected deck) option

### ISSUE THREAD

**Issue by 29988122** [Epix37/Hearthstone-Deck-Tracker#1352]
Testing parameters example: 
Overall deck stats: 20-10
Mage deck #1: 10-5
Options->tracker->stats->display 
version(s): selected, mode: ranked, timeframe: all time

Steps to reproduce bug:
Display area shown Mage deck #1 with 10-5 correctly.
Click stats->deck status.
Change timeframe.

Result:
Overview classes showing match of ALL THE DECKS which is 20-10.

Expected result:
Showing 10-5 which is the stats of Mage #1.

Also, I still can't figure out the version option. It's a little bit confusing.
Redesign is suggested?

Your tracker made me from R20->R11.
Thank you for all of your efforts!

**Comment by culinko** [comment]
Does this still happen in the current version?

**Comment by 29988122** [comment]
Properly fixed. Thx for the efforts!

**Comment by Epix37** [comment]
:+1:
