### ISSUE TITLE
Stats on new decks don't update in the deck list

### ISSUE THREAD

**Issue by MyopicCat** [Epix37/Hearthstone-Deck-Tracker#1354]
Just a visual bug I think. When you make a new deck (either arena or constructed) it gets marked "NO STATS" in the deck list. Then when you play with it, stats get recorded in the tracker overlay and in the stats menu, but not on the main deck list. The deck retains the NO STATS marker until the entire tracker is restarted. The stats are displayed correctly after the restart.

**Comment by GiggliG** [comment]
The stats i think do get tracked if you change to a different view (such as clicking a different class icon at the top of the deck list), then clicking a different deck to make it active, then switchihng backi to your deck and making it active again.

It's an annoyance, to be sure.

**Comment by culinko** [comment]
This still happens to me every time I create a new deck or a deck version. Running on the newest 0.13.17.

![dragon](https://cloud.githubusercontent.com/assets/11700272/13967420/516f9082-f077-11e5-8a56-238e5742d7ab.png)

![dragon2](https://cloud.githubusercontent.com/assets/11700272/13967426/59b4d09a-f077-11e5-969c-988a79757a5b.png)

**Comment by Epix37** [comment]
Turns out it was related to the custom "no stats" label on the legacy layout. Fixed now.
