### ISSUE TITLE
New feature: show overall stats for the class, not only for particular deck

### ISSUE THREAD

**Issue by vedmaque** [Epix37/Hearthstone-Deck-Tracker#1362]
I actually don't know if this feature exists (can't find), but want this from the very first release.

Use case: always want w/l stat for class to see if all of my warriors losing to mages.

Mostly want this for arena runs to see if warlock easy for any of shamans or not (to be prepared and for general knowledge such as average pally generally stronger than shamans and so on)

**Comment by andburn** [comment]
You can do this already, on the stats page select *Overall* and *Stats*, that gives the table below (you can use the *Mode* filter to show only arena):

![overall_stats](https://cloud.githubusercontent.com/assets/5419653/9566890/b54a1ec4-4f0f-11e5-9529-4bb609c63794.png)

**Comment by vedmaque** [comment]
yep, i know, that this exists, but i wanted it inside game :(

**Comment by MaestroFuego** [comment]
I have a problem with this programm. I posted it 4 days ago. Iam not able to use it the moment. Nobody f*cking cared at all! Why? :*(

**Comment by Epix37** [comment]
Not sure this is necessary tbh. During the game you don't gain much (any?) by knowing of "shaman generally wins again warlock" - depends on the decks on play. Plus I would argue the stats in the screenshot above give you a much better overview of the general situation.
