### ISSUE TITLE
Games where the opponent disconnected should be considered a concede

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#1364]
In the Replay Viewer, games marked with an asterisk are those where one of the two players conceded. I think that games where one of the two players has disconnected should also be marked with an asterisk, for what are presumably the same reasons as why conceded games are also marked. This indicates that the stats don't show the full picture, etc.

For instance, just because you won a game where the opponent disconnected, doesn't necessarily mean that you would have won if they had continued playing, so that's a big reason why the game should be marked with an asterisk.

**Comment by culinko** [comment]
I'm not sure if there is a way to determine that your opponent has disconnected other than TIMEOUT=15 which indicates that your opponent didn't press the end turn button. There are also situations, where your opponent disconnected, but then managed to reconnect back to the game. Also I don't really think disconnects should be treated as conceded games, rather there could be some other indicator to show that your opponent disconnected from the game and never came back.

**Comment by GaryKing** [comment]
Sure, a different indicator would be fine, too. But I think an indicator is still necessary.

How does the concede indicator work? I assume that the logs indicate that the opponent conceded?

Couldn't a disconnect be determined by simply checking the logs to see if the game ends when one of the players has a life total of 0 or less? If the game ends where both players still have more than 0 life, then surely that means that there was a disconnect.

**Comment by culinko** [comment]
These two lines get added when your opponent concedes:
TAG_CHANGE Entity=YourOpponent tag=PLAYSTATE value=QUIT
TAG_CHANGE Entity=YourOpponent tag=PLAYSTATE value=LOSING

Determining the disconnect by a life total wouldn't be a good idea, either. For example if you use Sacrificial Pact on Jaraxxus, you don't lower the opponent's hero below 0 health at all. Also, sometimes your opponent disconnects and then you kill him in 2 turns before "Your opponent left" message kicks in. When I'm looking at one of my logs where my opponent disconnected for 1 or 2 turns, the game ID seems to go to SETASIDE zone, but that could be the same case with not hitting the end turn button.

**Comment by chucklu** [comment]
reconnect back to the game
Under this situation，the deck would not record the game after the game ended.
I wonder , is this a bug?

**Comment by culinko** [comment]
If your opponent disconnects and reconnects to the game, the game is recorded. But if you're talking about you disconnecting and then reconnecting (or restarting the client in the middle of the game), the game would not be recorded (I haven't tested it in the newest version, though). The tickets for that: #299 (closed) and #922.

**Comment by HugoKornelis** [comment]
I don't agree that disconnects and concedes should be displayed the same.
In my experience, 95% of all concedes are technically wins - my opponent sees that I have lethal, his last draw does not give him the required out, so they concede. I do the same when I am in a lost position.

Wins and losses due to loss of connection are different. I have "won" games that I should have lost when my opponent disconnected, and lost games that I should have won when my connection failed.

My preference would be to have separate marks for concede and disconnect. If only one mark is possible, then a mark for disconnected games would, in my opinion, carry more value than a mark for conceded games.

Obviously, I have no idea whether it is at all possible to extract disconnects from the log files HDT uses. :)

**Comment by Epix37** [comment]
Agreed on concede and disconnect not being the same thing. That said, I don't think a special indication is necessary (and I don't even know if there would be anything hinting to that in the logs).
