### ISSUE TITLE
Hearthead import bug

### ISSUE THREAD

**Issue by KayaTheRock** [Epix37/Hearthstone-Deck-Tracker#1366]
While trying to import from hearthhead getting script errors.

See images below:

Thanks

![screenhunter_117 aug 31 15 38](https://cloud.githubusercontent.com/assets/14054739/9578897/877c9fc0-4ff6-11e5-9c6c-1e46932b8cab.jpg)
![screenhunter_118 aug 31 15 39](https://cloud.githubusercontent.com/assets/14054739/9578898/877d5ff0-4ff6-11e5-8af2-27ff78d00016.jpg)
![screenhunter_119 aug 31 15 39](https://cloud.githubusercontent.com/assets/14054739/9578895/877c3c4c-4ff6-11e5-8004-f27e59a8fddb.jpg)
![screenhunter_120 aug 31 15 39](https://cloud.githubusercontent.com/assets/14054739/9578900/877f100c-4ff6-11e5-99a5-1ec254267663.jpg)
![screenhunter_121 aug 31 15 39](https://cloud.githubusercontent.com/assets/14054739/9578899/877ed3c6-4ff6-11e5-9a30-00ce9b0d66be.jpg)
![screenhunter_122 aug 31 15 39](https://cloud.githubusercontent.com/assets/14054739/9578896/877c76ee-4ff6-11e5-89bc-e346b44f6fbc.jpg)

**Comment by KayaTheRock** [comment]
..and it hangs up on the loading screen. Have to close the app manually.

**Comment by Epix37** [comment]
No idea to be honest :/. Any problems with other sites or other decks on hearthhead?

**Comment by KayaTheRock** [comment]
All the decks in hearthhead has the same issue. And so far all the other sites that I tried work perfectly fine (hearthpwn, etc).

My first guess would be that hearthhead changed the interface or something.

You cannot recreate the issue? If it is only me, I will try a clean install.

**Comment by KayaTheRock** [comment]
Ive just installed NetDeck extension and it works like a charm. So Im pretty happy with this workaround.

**Comment by Epix37** [comment]
I can't reproduce this, no. But if NetDeck works for you that's a good solution I suppose :).

**Comment by WaxPaper** [comment]
Before ya close this issue, I wanted to let ya know that I've also been experiencing this for months. It used to eventually import the deck successfully from Hearthhead despite that error prompt he screenshotted, but the past month or so it just hangs forever and the program has to be killed to restart.

Can I help you debug this with some log tracking or anything?
