### ISSUE TITLE
Cant export decks

### ISSUE THREAD

**Issue by clunesterr** [Epix37/Hearthstone-Deck-Tracker#1367]
Evertime i try to export decks, wehther it be from me creating a deckin the app or importing them through a website the app never slects the cards, only types in the names.

**Comment by Helkaer** [comment]
I'm seeing a similar issue. Sometimes when I export it misses a couple cards, other times it miss almost all the cards. If you start with a deck that it has to clear it also clicks the deck helper button several times after all the cards have been removed from the deck. I'm on Windows 10 and I've tried disabling the DPI scaling from Windows in case that is causing problems.

**Comment by Epix37** [comment]
Try this: 
* `options > tracker > settings > open appdata folder`
* close HDT
* delete the config.xml 
* try exporting again

**Comment by Helkaer** [comment]
It still does the same thing for me after deleting the xml file.

**Comment by velvetpants0124** [comment]
I also have the same issue.
Yesterday it worked fine, today not so good.
Only will type the names and not select and then give the missing card info screen.
Tried deleting the xml as well and no luck.

**Comment by Epix37** [comment]
This might be an resolution issue (do you happen to have black bars at the bottom top?).
Try changing resolutions and see if it works.

**Comment by velvetpants0124** [comment]
Yep the resolution/full screen vs windowed was the trick :)

Thanks for the reply!
