### ISSUE TITLE
Collection Tracker?

### ISSUE THREAD

**Issue by GomesCoding** [Epix37/Hearthstone-Deck-Tracker#1370]
It would be amazing if you added a tracking feature for the Collection.
 I thought that if you actually can detect decks by the log (right?) then it would be slowly completing the cards the owner has.. Or maybe with image recognization? Sorry if it's stupid..

**Comment by MechaLynx** [comment]
There is a plugin that does that already: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Available-Plugins - not stupid, just already there :p
