### ISSUE TITLE
request：export screenshot add dust cost

### ISSUE THREAD

**Issue by everchump** [Epix37/Hearthstone-Deck-Tracker#1373]
1，add a option to add the dust cost of a selected deck to be export as a png pic.    can the pic with the deck name ?

2，Different colors GEM，it's easy to know the rarity.

3,Draw Simulator 

can test Mulliganed cards

like this:http://www.gamewalkers.com/games/hearthstone-heroes-warcraft/decks/grim-patron-warrior/

can support inport the gamewalkers.com sites （FROM WEB)

**Comment by Epix37** [comment]
1. Should be possible. 
2. Cards already have rarity-colored borders
3. I never understood the point of those. Doesn't really fit in this application I think.
