### ISSUE TITLE
Export Problem

### ISSUE THREAD

**Issue by Harrock** [Epix37/Hearthstone-Deck-Tracker#1374]
When I go to export a deck to Hearthstone it will only read the zero tab. How do I fix it?

**Comment by Epix37** [comment]
Try increasing the export start delay. See here for reference: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#exporting

**Comment by Harrock** [comment]
I tried normal and slow - same problem.

**Comment by andburn** [comment]
Did you try to export in fullscreen and windowed mode?

**Comment by Epix37** [comment]
I mainly meant this: `Go to options > tracker > exporting and set Wait 0 seconds before starting to at least 1.`

**Comment by Harrock** [comment]
It was already at 1. Should I make it higher?

**Comment by Harrock** [comment]
I switched it to 2 and it worked fine. Thanks for the help.

**Comment by Epix37** [comment]
Great :).
