### ISSUE TITLE
Suggestion: Marker to let you know enemy player is done mulliganing

### ISSUE THREAD

**Issue by MeanRev** [Epix37/Hearthstone-Deck-Tracker#1376]
As per topic. I like seeing how the enemy mulligans before I do mine and HDT helps with that a great deal, but there's one case where there's confusion. If the enemy keeps all the cards of his initial draw, there's no way to tell he has done so. This leads to me often waiting to the end of the mulligan time for no good reason. It would be nice if there was a marker of some kind to let you know I don't have to wait.

I don't know if HDT even has access to that info, though and there might be other reason not to implement such a thing, so np if this never happens. Could be that the info is already in the client and I've just been missing it, in which case I apologise.

**Comment by Epix37** [comment]
This information is currently not visible in the (Hearthstone-)client. I don't know whether that's deliberate or just ..not there for no reason. So while it would be possible, I don't think it's a good idea.
