### ISSUE TITLE
fullscreen issues when a card is drawn

### ISSUE THREAD

**Issue by hskrpwr28** [Epix37/Hearthstone-Deck-Tracker#1380]
Each time I draw a card, my screen goes from full screen to windowed mode.  If I am in windowed mode, it is fine.

**Comment by riQQ** [comment]
Which OS version are you using?

**Comment by hskrpwr28** [comment]
This is on Windows 10 64-bit

**Comment by Epix37** [comment]
Do you switch to fullscreen after starting hearthstone? I think there have been problems with that. If so, try setting hearthstone to fullscreen and restart it.

**Comment by hskrpwr28** [comment]
I think it was just my settings, reset to 1920-1080 and haven't had any problems.  thanks for checking on this, though.
