### ISSUE TITLE
"Show note dialog after game" check box not being saved/loaded properly

### ISSUE THREAD

**Issue by Elitesparkle** [Epix37/Hearthstone-Deck-Tracker#1386]
When I restart the tracker, I need to check the "Show note dialog after game" option again because there is an issue with saving or loading.

Take a look.

**Comment by riQQ** [comment]
Works for me. Do you use the current version?

**Comment by Elitesparkle** [comment]
> Works for me.

I've tried many times, even changing the respective value in the config.xml, but it didn't work properly.
Sometimes it were loading, sometimes not.

I did another try and now it's loading fine.
I don't know how it's possible.

> Do you use the current version?

Yes, version 0.10.16.

**Comment by Epix37** [comment]
So... does work?

**Comment by Elitesparkle** [comment]
> So... does work?

No, I still have the same issue.

**Comment by Elitesparkle** [comment]
It's working again, somehow.
Il 07/set/2015 10:40, "Epix" <notifications@github.com> ha scritto:
