### ISSUE TITLE
Suggestion: show/hide news bar

### ISSUE THREAD

**Issue by Elitesparkle** [Epix37/Hearthstone-Deck-Tracker#1387]
My news bar is currently hidden but I'd like to see it again.

After looking in the options, I can't find any check box to activate it.

Can you add it?
Thanks.

**Comment by Epix37** [comment]
Sure.

For now you can turn it on again by setting ` <IgnoreNewsId>` in the config to `-1`.

**Comment by Elitesparkle** [comment]
> For now you can turn it on again by setting <IgnoreNewsId> in the config to -1.

When I've seen there were the value 7, I didn't know which value to set to enable it again.

Thanks.

**Comment by culinko** [comment]
The option has been added into Tracker -> Settings -> Show news bar.
