### ISSUE TITLE
jousting seems to treat the cards as played

### ISSUE THREAD

**Issue by rrwoods** [Epix37/Hearthstone-Deck-Tracker#1388]
I played a Master Jouster, and the card in my deck that was revealed got grayed out, and the card in my opponent's deck that was revealed was displayed ungrayed (as though he'd played the card already).

**Comment by rrwoods** [comment]
In the same game, I eventually drew the jousted card, and the tracker went nuts -- it continuously did the following, with about a 2-5 second pause between each bullet point:
* the entire overlay disappears
* the overlay reappears, in a "fresh" state (my decklist has all 30 cards normally rendered, my opponent's playlist is empty)
* the overlay "draws"/"plays" all the cards that were played in the game to this point (all the cards in my hand turn orange, their playlist accurately reflects what they've played, PLUS my jousted card is gone from the deck and theirs is in the playlist)
* repeat from step 1.

**Comment by riQQ** [comment]
Do you have the replay and the log?

**Comment by rrwoods** [comment]
I don't have the log, but what do I do to send you the replay?

**Comment by riQQ** [comment]
Upload it to a site like http://uploaded.net/ and post the link here.

**Comment by rrwoods** [comment]
Where is the replay file?

**Comment by rrwoods** [comment]
http://userpages.umbc.edu/~woorich1/rrwoods(Rogue)%20vs%20somebadfish(Warlock)%201705-030915.hdtreplay

**Comment by joelwamser** [comment]
Hi I had this same issue when using cards like King's Elekk and Gadgetzan Jouster. And when it happens its tracking my arena wins incorrectly. Its giving me two wins instead of one. It did it twice so now it says my record with my current arena deck is 9-0 when I'm actually 7-0

**Comment by joelwamser** [comment]
Additionally, is there a way to manually edit the record of a deck?

**Comment by Epix37** [comment]
Happens since the hotfix. Working on fixing this.

@joelwamser https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#add-game

**Comment by riQQ** [comment]
I had this happen to me today. Opponent played a joust card and revealed my Loatheb. As i drew it HearthstoneDeckTracker went crazy as described above. HDT continued to show the overlay after the game in the main menu of Hearthstone. HDT was unresponsive und consumed ~25% CPU (1 core) and i had to kill the process. No replay was saved. The only thing i got is the HDT log for this game: http://pastebin.com/e31W1VNA.

**Comment by ilya-narbutovskikh** [comment]
The same issue with paladin's Argent lance (Arena mod).
Here is log:
http://pastebin.com/RVzekYVP
