### ISSUE TITLE
Can we use git chery-pick instead of merge for this repository?

### ISSUE THREAD

**Issue by chucklu** [Epix37/Hearthstone-Deck-Tracker#1391]
After I found you update the repository,I pull the code to my local repository.
When I check the history of commits,it seems weird.
![qq 20150904063621](https://cloud.githubusercontent.com/assets/3004057/9672690/4772e1f6-52cf-11e5-9af9-5009fbc28b00.png)

* commit d4b35b03e929f3b97a8dee613f48bb42791d98d7
| Author: Epix37 <epikz37@gmail.com>
| Date:   Thu Sep 3 10:19:08 2015 +0200
| 
|     Refactoring: moved CardId stuff to Hearthstone.Database - missed IsActualCard
|  
* commit e33bbece029b4d5d4553ebfd521996ebab8491ff
| Author: Epix37 <epikz37@gmail.com>
| Date:   Thu Sep 3 10:10:49 2015 +0200
| 
|     Refactoring: moved CardId stuff to Hearthstone.Database
|    
*   commit 96445b215797d7838f572b0afc5e277876eb8f49
|\  Merge: 63c77ae 11b5737
| | Author: Epix <epikz37@gmail.com>
| | Date:   Wed Sep 2 23:21:05 2015 +0200
| | 
| |     Merge pull request #1385 from riQQ/master
| |     
| |     Don't try to upload two arena games
| |   
| * commit 11b57371297442b33d9d2aee50ef436527992210
|/  Author: riQQ <riQQ@users.noreply.github.com>
|   Date:   Wed Sep 2 23:07:35 2015 +0200
|   
|       don't try to upload two arena games
|    
Actually commit 11b57371297442b33d9d2aee50ef436527992210 and commit 96445b215797d7838f572b0afc5e277876eb8f49 are doing the same thing.
The difference between them is commit 11b5737 belongs to  riQQ ，And 
commit 96445b21 belongs to Epix ,commit 96445b21 is also a merge commit.

However,we can use git rebase or git cherry-pick to avoid creating unnecessary commit.

**Comment by chucklu** [comment]
I will show you how to use git rebase first,though rebase is not the best choice

$ git checkout -b temp1 11b5737
Switched to a new branch 'temp1'

$ git checkout -b temp 63c77a
Switched to a new branch 'temp'

$ git rebase temp1
First, rewinding head to replay your work on top of it...
Fast-forwarded temp to temp1.

By this method ,we can just fastforward the branch without merge commits

**Comment by chucklu** [comment]
$ git cherry-pick 11b57371
[temp 45c66b0] don't try to upload two arena games
 Author: riQQ <riQQ@users.noreply.github.com>
 1 file changed, 1 insertion(+), 1 deletion(-)

this method can fast forward too

**Comment by chucklu** [comment]
Do you know tortoisegit?by this tool,cherry pick will be easier to do 
http://stackoverflow.com/questions/9415534/cherry-pick-using-tortoisegit

**Comment by chucklu** [comment]
*   commit 63c77ae215980e1d356d133bca230e04734bcf41
|\  Merge: 1583a81 4e67f05
| | Author: Epix <epikz37@gmail.com>
| | Date:   Wed Sep 2 11:08:13 2015 +0200
| | 
| |     Merge pull request #1359 from chucklu/master
| |     
| |     fix bug about gold tracking
| |     
| *   commit 4e67f05995b7d615fce1e97f18deb000d367a6f9
| |\  Merge: 6d0e241 1583a81
| |/  Author: ChuckLu <244657538@qq.com>
|/|   Date:   Wed Sep 2 09:15:08 2015 +0800
| |   
| |       Merge branch 'epix37/master' into chucklu/master
| |     
* |   commit 1583a81e0757076ea9d75a39116871ed65a6b70e
|\ \  Merge: 1878dbb defeff2
| | | Author: Epix <epikz37@gmail.com>
| | | Date:   Tue Sep 1 09:50:55 2015 +0200
| | | 
| | |     Merge pull request #1361 from stdscatchemall/patch-4
| | |     
| | |     Add extension to the Window class
| | |    
| * | commit defeff248e501f3dcf6cc04e1dbdb326ea5c6d9b
|/ /  Author: stdscatchemall <curtis.christopher96@gmail.com>
| |   Date:   Sat Aug 29 11:31:03 2015 -0400
| |   
| |       Add extension to the Window class
| |       
| |       This will allow (me in particular) people to access the underlying window attributes for resizing and focus, as well as make override (extension) methods without completely copying and personally modifying the code myself.
| |       
| |       This makes for easier plugin development on my end while not costing anything to anyone else
| |   
| * commit 6d0e241f5650ae3ed3604ae0e9124c1074bce034
| | Author: ChuckLu <244657538@qq.com>
| | Date:   Mon Aug 31 00:49:16 2015 +0800
| | 
| |     fix bug about wins count,should consider the wins saved in config.xml
| |   
| * commit 3393875a296da249bf6e8f3f792769f23336b0fc
| | Author: ChuckLu <244657538@qq.com>
| | Date:   Mon Aug 31 00:22:00 2015 +0800
| | 
| |     fix bug about gold tracking
| |   
| * commit 1253f54273412a58d6783cc4baa0cbc1e4a65b31
| | Author: ChuckLu <244657538@qq.com>
| | Date:   Sat Aug 29 22:43:27 2015 +0800
| | 
| |     add timezone case for gold progress
| |   
| * commit a342f6ba19df307c1afc05013df57b800b80774d
|/  Author: ChuckLu <244657538@qq.com>
|   Date:   Sat Aug 29 16:29:14 2015 +0800
|   
|       fix "index of out array" bug about gold tracking for region china
|  





============================================================================
SHA-1: defeff248e501f3dcf6cc04e1dbdb326ea5c6d9b
SHA-1: 1583a81e0757076ea9d75a39116871ed65a6b70e
SHA-1: 4e67f05995b7d615fce1e97f18deb000d367a6f9
three commits above ,they are doing the same thing

**Comment by lolo1337** [comment]
Pesonnaly I use GitExtension to manage my Git repositories. https://github.com/gitextensions/gitextensions

**Comment by chucklu** [comment]
http://stackoverflow.com/questions/9229301/git-cherry-pick-says-38c74d-is-a-merge-but-no-m-option-was-given
I encountered a problem about cherry-pick like the problem described by the link.
Sometimes,if we want to keep all the commit history,maybe merge is the best choice

**Comment by chucklu** [comment]
today，I find another article about why we should not use  cherry pick
http://dan.bravender.net/2011/10/20/Why_cherry-picking_should_not_be_part_of_a_normal_git_workflow.html

**Comment by chucklu** [comment]
![mess](https://cloud.githubusercontent.com/assets/3004057/10116223/eb68b96a-645f-11e5-8abf-f87cfafbd1ed.jpg)
I fetch the code from your repository,
loop the following steps
>step1: create a branch on the last commit of the third party,and swicth to the new branch

>step2:rebase the new branch onto master

>step3:checkout back to the master,then merge new branch[no fastword]
then git log graph like this :
![linear](https://cloud.githubusercontent.com/assets/3004057/10116226/01fceb9c-6460-11e5-9dc8-a6b14bc6e656.jpg)
