### ISSUE TITLE
Deck tracker keep resetting during a game.

### ISSUE THREAD

**Issue by vupiner** [Epix37/Hearthstone-Deck-Tracker#1392]
http://pastebin.com/EfvdGbhH

When I play a shaman deck, the tracker keep resetting itself. 
Other decks seems fine, but whenever I play a shaman deck with neptulon(I am not sure whether this card makes a problem), it keeps blinking and resetting but it never settles. It happens mostly in the late game.

**Comment by Ramwen47** [comment]
This has been happening to me too over the past few hours with all arena decks.

**Comment by OriginalAlienOne** [comment]
I came on here to echo that I'm experiencing the same issue when playing a Shaman deck... What I've found is that if I play a joust card that draws a card for me and then places it back in my deck, the deck tracker shows it as having been drawn and no longer in the deck. So, when the card is actually drawn, the deck tracker freaks out and then keeps asking me what deck I am playing. The only thing I can do is exit out of the box, which disables the auto deck selection feature. If I select which deck I am playing, the pop-up will just re-appear in one second after a flash.

**Comment by Epix37** [comment]
Working on fixing all of this. Update will come hopefully next week.

**Comment by OriginalAlienOne** [comment]
Thanks for your hard work, Epix!

**Comment by Epix37** [comment]
I just realized: Turning off `MAIN > AUTO DECK SELECTION` should stop this behaviour for the time being.

**Comment by Dalarrus** [comment]
This is still an issue as of nearly 4 years later.
