### ISSUE TITLE
Can't start HDT - Crashes right at the beginning

### ISSUE THREAD

**Issue by DeliciousSeason** [Epix37/Hearthstone-Deck-Tracker#1394]
Every time i try to start HDT it crashes. I installed a new version of .NET Framework 4.5 / 4.5.2 and 4.6 - neither helped.

Here's the Error Log i found in the HDT directory
http://pastebin.com/peWd52ss

**Comment by Epix37** [comment]
Have a look at #588

**Comment by DeliciousSeason** [comment]
mmh so the # is causing this - interesting :) 

thanks
