### ISSUE TITLE
Changing stats display timeframe only updates the selected deck

### ISSUE THREAD

**Issue by condone** [Epix37/Hearthstone-Deck-Tracker#1397]
Changing options->Tracker->Stats->Timeframe between "Current Season" and "All Time" only updates the stats overlay for the selected deck. Other decks are unaffected. I assume the other selections in the combobox also only update the selected deck.

**Comment by culinko** [comment]
Not just Timeframe, but also Version and Mode.

**Comment by culinko** [comment]
I can still confirm this in the newest pre-release (0.13.4). Also, the values only update for the deck currently in use (not updating for the selected deck as well).

**Comment by Epix37** [comment]
Fixed with v0.14.0
