### ISSUE TITLE
Deck list flashes (maybe related to Joust?)

### ISSUE THREAD

**Issue by hyderhussain** [Epix37/Hearthstone-Deck-Tracker#1399]
Over the past few days, my deck tracker has bugged out in the same way multiple times. The overlay just starts flashing between my full decklist with no cards drawn, to all of the cards i've drawn or played thus far flashing red (as if I just drew them). 

This just happened again immediately after I won a joust with King's Elekk. I'm not sure if it's related to the Jousting mechanic or not.

**Comment by Dodd8686** [comment]
Just seconding this. I have this problem too.

**Comment by Epix37** [comment]
I'm currently re-implementing the way cards are tracked. There should be an update fixing this hopefully next week.

**Comment by Epix37** [comment]
I just realized: Turning off `MAIN > AUTO DECK SELECTION` should stop this behaviour for the time being.

**Comment by hyderhussain** [comment]
Awesome! Thank you.

**Comment by Epix37** [comment]
Also, please do try the [latest pre-release](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.10.17) and see if you find any remaining problems with mechanics like joust.
