### ISSUE TITLE
HDT loses track of Arena game

### ISSUE THREAD

**Issue by HugoKornelis** [Epix37/Hearthstone-Deck-Tracker#1400]
Not sure if this is related to the other "flashing cards" bugs I see.
Twice today, on two different Arena runs, the decklist started to alternate between showing all cards (as if a new game just starts) and showing the cards in hand/played as normal. Ditto for the opponent deck info alternating between 30 in deck/no in hand, and the actual info. Once the game ends, HDT tells me there is no match with the decklist and asks to discard, keep, or use other deck. I select keep, then the game does show up in the deck history but without win/loss information and incorrect coin information. There is no replay file saved for the game.

I do not recall any unusual card being played just before that, but that might be my memory.

Quitting and restarting both HDT and HS appears to fix the issue.

**Comment by megablue** [comment]
I had similar experiences. I am not sure we both experienced the same problem or not. 

In the middle of an arena match. HDT's deck list started flickering. It looks like it was keep reloading the log or something. The turn timers disappeared. If i am correct, it was cause by jousting (i am not sure the exact steps to reproduce the bug though). It seems like after a few joust the HDT will go haywire.

Also, restarting the HDT doesn't helps as long as you're still inside the same game. 

If you let HDT continues its craziness, it will eventually crash and produces an impressive 20MB log.

I've uploaded the log to mediafire @ https://www.mediafire.com/?3k3075t7ssfrtik

**Comment by HugoKornelis** [comment]
Thanks, Megablue! I guess that your log file can be a great help for Epix in finding the issue. I checked my log directory and found nothing, but I did find XML files for all games played, including the ones that failed. I have uploaded the last game to http://www.juti.nl/hugo/Game_341f0794-9e69-45ad-bcb1-67919c1717cf.zip .
I did not try restarting HDT during the game, figuring that starting HDT mid-game would confuse it even more. Thanks for confirming that.

On your suggestion that it might be related to jousting: I checked the decks I used the two times it happened. The first time I did not have any joust cards (but my opponent might). The second time I did have a joust card. Not sure if I played it when the error occured, I will definitely watch what happens to HDT before and after playing joust cards from now on.

**Comment by HugoKornelis** [comment]
Some more observations:
1. It does indeed appear to be related to jousting. Just had it happen again, and it did start after the joust.
2. Not 100% sure yet, but it appears that once the game is over, HDT will recover even if you just start a new game, without quitting and restarting HS and/or HDT.

**Comment by riQQ** [comment]
See #1399, #1392.
