### ISSUE TITLE
Hearthstone Deck Tracker doesn't appear

### ISSUE THREAD

**Issue by Daralanteriel** [Epix37/Hearthstone-Deck-Tracker#1401]
I installed HDT, and set the correct path with hearthstone, and it worked fine. But when i changed the set data path (don't ask me why) with the data folder in hearthstone it doesn't work anymore. I tried using hdt reinstaller o delete the appdata folder, but didn't worked. What can i do?

**Comment by Epix37** [comment]
Data path refers to HDT data, not hearthstone data. Resettings the path and turning 'save in appdata' back on should fix the problem.
