### ISSUE TITLE
HDT crashing on Majordomo deathrattle (tavern brawl)

### ISSUE THREAD

**Issue by armegetton** [Epix37/Hearthstone-Deck-Tracker#1403]
When it first happened, I thought it might be a fluke, but it has happened consistently (every time) during a tavern brawl match.

This last week's tavern brawl, I was using my legendaries. If majordomo isn't played, or doesn't die, there's no issue. But during the face flip from warrior to ragnaros, HDT will crash without fail.

After which, both hearthstone and HDT need to be restarted before it works again. (if only HDT is restarted, the deck overlay won't show nor track games, even if different mode or deck is selected)

Additional things to note: (that are not problems)
- Hearthstone is in windowed-mode
- HDT is using "Use no Deck" in tavern brawl, even though I suppose I could have (haven't tested it)
- due to previous point, no games are being recorded (also because tavern brawl checkbox is unchecked in the options menu), this is intended
- was only using the normal warrior hero, no other classes were tested
- there were no noticeable similarities between enemy class or what other minions on the board were

Not sure if tavern brawl needs to be addressed, but thought you should know. (untested if it happens in other game mode, but due to the latest expansion, it may)

**Comment by riQQ** [comment]
Maybe fixed with https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/1878dbb2817950b94537b7afca313e698cb2eef9. But there's not yet a version containing this change.
