### ISSUE TITLE
Mulligans for opponent aren't working

### ISSUE THREAD

**Issue by robertsmieja** [Epix37/Hearthstone-Deck-Tracker#1407]
Some cards appear as 0 turn cards after mulligan phase. They seem to be consistently the two cards on the right if you start with the coin. If you don't start with the coin, it seems to be marked as M, 0, M, 0.

Screenshots with coin:
http://i.imgur.com/0XkdOOM.jpg
http://i.imgur.com/D0qEVuy.jpg

Screenshots without coin: 
http://i.imgur.com/Y9ZqQNf.jpg

**Comment by Epix37** [comment]
Intentional change, the "K" is redundant.

**Comment by robertsmieja** [comment]
Ok I was confused because it wasn't in the changelog

**Comment by Epix37** [comment]
I will make sure to add it :).
