### ISSUE TITLE
Beta Update Issue - Outdated plugin crashes HDT

### ISSUE THREAD

**Issue by radryan** [Epix37/Hearthstone-Deck-Tracker#1408]
After the update it keeps crashing and gives an error pop up box like alot before it closes itself out. I've attached a screen shot for you. Previous version worked fine. I'm on windows 10.

![image](https://cloud.githubusercontent.com/assets/13872203/9706192/04f482e0-54a4-11e5-82ee-9eb7b5619140.png)
[pastebin](http://pastebin.com/pim8piJw)

**Comment by Epix37** [comment]
Please upload the in the message mentioned crashlog.

**Comment by Epix37** [comment]
Your version of the Arena Helper Plugin is no longer compatible.

**Comment by radryan** [comment]
thanks

**Comment by Epix37** [comment]
Lets leave this open for now :) I bet someone else is going to have the same problem.

**Comment by Epix37** [comment]
fixed with pre-release v0.10.18
