### ISSUE TITLE
Ambush confuses HDT

### ISSUE THREAD

**Issue by HugoKornelis** [Epix37/Hearthstone-Deck-Tracker#1409]
Found a (small) bug today.
My opponent played "Beneath the Grounds". For those who have never seen this card, it is a Rogue card that shuffled three copies of the card "Ambush" in my deck; when I draw this card, it summons a 4/4 Nerubian for my opponent. (Three 4/4s for just 3 mana? Even with the delay, that sounds insane. But let's not get there).

Anyway, a few turns later I drew my first Ambush card; immediately HDT started complaining that the card didn't match the deck, and asked whether I wanted to keep or discard the game.

I have the replay file; let me know if it's needed for further troubleshooting.
(Reference for myself: deck="Arena 06-09 02:18", 9th game)

**Comment by Epix37** [comment]
Should be fixed with the next update. [(which is currently available as a pre-release)](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.10.17)

**Comment by HugoKornelis** [comment]
Wow, that is fast - I am impressed!
Thanks for all your good work, Epix!

**Comment by Epix37** [comment]
That has been in the works for a few days :).
