### ISSUE TITLE
Deck Versions Implementation Has Serious Problems

### ISSUE THREAD

**Issue by Shadostruct** [Epix37/Hearthstone-Deck-Tracker#1411]
I have a cool deck I like with about 20 games worth of stats on it. I change out a single card and figure saving as 1.1 would make sense as it's a small change. Now it reset my stats and shows 0-0 in my overlay when I pick my deck. I realize the stats are still there, I just need to pick v1.0 of the deck, but I want the stats collapsed into one another.

The whole point of v1.x should be a small change versus a v2.0 or higher. A small change should keep the same stats for the deck as the deck is basically the same. As it stands I don't even see an option for me to collapse the stats.

If I had known this I would've just saved as 1.0 and ignored the versions feature entirely. If I could delete 1.1 and go back to my 1.0 I'd be happy as well. But there's no option for that either.

It really irks me that my stats for this deck are such a mess now, and I find it really unintuitive and frustrating there are no options available to remedy this. I just want a clean and accurate representation of my stats.

Thanks for the work on the program, I'm loving it otherwise.

**Comment by Epix37** [comment]
HDT aso has some serious options! :)
You can select which version(s) you want to see stats for via `options > tracker > stats > display`. ([(see also here)](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#im-getting-no-stats-displayed-on-the-deck-list-screen-even-though-i-have-games-recorded)

**Comment by Shadostruct** [comment]
Awesome, thank you, that definitely solves my main problem (Collapsing the stats from both versions).

I'd still like to see a bit more customization with this feature, though. Editing previous versions, deleting v1.1 and keeping 1.0 w/ stats. I think the versions feature could be a powerful tool for people that tweak their decks often and want to keep track of that. It's just a little short of the mark, still, imo.

Unless I'm again missing the option somewhere, in which case my bad.

Thanks for taking the time out to hear me out and help me, I appreciate it. Your software is incredible for someone like me that loves seeing stats indicating my personal performance competitively.

**Comment by Epix37** [comment]
See #999 and #1010. It's a good idea but not very straight forward to impement. 
Soon (TM). ;)

**Comment by Shadostruct** [comment]
Thanks again, glad to see it's on your radar, I look forward to future versions. Good luck with everything.
