### ISSUE TITLE
[request] no log.config anymore

### ISSUE THREAD

**Issue by erenior** [Epix37/Hearthstone-Deck-Tracker#1414]
Hello epix,
hello everyone,

the deck tracker itself is a damn good tool. but as some of you might know there is an issue with lags/fps drops after installing the HDT.

i dont know why but the lag/fps drop is caused by a file in "...\appdata\local\blizzard\hearthstone" named log.config

you can simply check if i am right by deleting the log.config file in that specific folder and restart hearthstone again without using hdt. it will run perfectly smooth (or at least way better, depending on your personal machine)

here is the request epix: can you make it possible to use hearthstone deck tracker WITHOUT creating this config.log file?
i testet all options in hdt but everytime i start hdt the config.log file will be created.

**Comment by Epix37** [comment]
HDT gets **all** it's data from the hearthstone logs which are only generated iff that file exists. HDT without it is not possible. Also see #1274.
