### ISSUE TITLE
Feature Request: Rarity display using gem

### ISSUE THREAD

**Issue by fref** [Epix37/Hearthstone-Deck-Tracker#1416]
I think it would be nice to have the rarity displayed using the colored gem. I only noticed recently that the border of the tiles was slightly different, but I think it's harder to read on the border of the cards than a gem on the tile itself, especially for secrets or when the screen estate is small, or when the deck display has been reduced.

**Comment by Thristle** [comment]
this was a request long ago and that's when the borders were implemented.
it was a design choice, adding a gem was just not "visually appealing"

**Comment by GaryKing** [comment]
The colored borders are hardly noticeable. I just went to check them out right now because I never realized they were there.

**Comment by fref** [comment]
Maybe this could be made optional? I don't know for how long these borders have been there, but as @GaryKing , I had never noticed them until yesterday, and I had been longing for a way to figure out the rarities of the cards played (particularly when trying to figure out what secret could have been played).

**Comment by fref** [comment]
I have a simple suggestion: change the colour of the gem which indicates the cost of the card. Easy to read, pretty and doesn't consume more space. Something like this.
![2015-10-08 19_47_28-hearthstone deck tracker](https://cloud.githubusercontent.com/assets/130824/10375935/801aa178-6dfb-11e5-8443-a4b95326c8b6.png)

**Comment by Cu8eR** [comment]
+1, really nice idea! Just one thing - add settings for this

**Comment by fref** [comment]
Thank you for the implementation, @andburn , I like it! :)
