### ISSUE TITLE
Exporting to HS not working (Only using basic cards)

### ISSUE THREAD

**Issue by Pjmcnally** [Epix37/Hearthstone-Deck-Tracker#1417]
The Export to HS feature is not working. I think it may be a quick fix.  

As part of the export process HS Deck Tracker clicks on the card set selection button in the bottom left of the screen.  It does so (I presume to make sure "All Sets" is selected.  However, it is currently selecting only "Basic" and then reporting all non-basic cards as missing.

The "All Sets" button got moved up a notch when TGT was released and the Export function should just need to be adjusted accordingly.

**Comment by Epix37** [comment]
Probably similar to #1374.

**Comment by Pjmcnally** [comment]
I have followed that thread and tried what is recommended.  I set my original delay to 2 seconds and set the export process to "Very slow".  Neither helped.

At very slow I can watch the computer click on the sets button and then select the "Basic" option so it is only searching within Basic cards.

**Comment by Epix37** [comment]
Most likely #1303 then!

**Comment by Pjmcnally** [comment]
That fixed the issue.  Thank you very much for the help.

**Comment by Epix37** [comment]
Great :) no problem.
