### ISSUE TITLE
Where do games that are saved but don't match any deck go?

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#1418]
If I finish a game, and at the end, HDT says that the deck doesn't match a deck, then it asks me if I want to still save the game or not. If I save it, where can I see it later? I don't see it in the Replay Viewer, for instance.

**Comment by Epix37** [comment]
You can find those under `STATS > GAMES & STATISTICS > (Overall >) Games` when you set the "Games" filter at the top to "All" or "Without deck".

**Comment by GaryKing** [comment]
I tried that before but couldn't find it. Strange.
