### ISSUE TITLE
[REQUEST] Stats per card (i.e. card performance)

### ISSUE THREAD

**Issue by JeromeDane** [Epix37/Hearthstone-Deck-Tracker#1422]
I would love to be able to see the performance of each card in a deck. Since we have full replay data, it seems like a parser could be written to generate and display this data.

Here are things I'd like to be able to look up:

* Winrate when drawing card X
* Winrate when playing card X
* Percentage of matches ends with card X unplayed

This would allow players to see which cards in a deck are performing well or being unused so that they could make adjustments accordingly.

In the UI, you could right click on a deck and select "card stats" or something like that. This would bring up a table of cards in the deck listed vertically, with the rates mentioned above horizontally. You could then sort by each of the rates to immediately identify the most/least effective cards in a deck.

I'd be interested in contributing this feature if no one else has time to implement it, although I'd have to do a lot of reverse engineering first. Let me know.

**Comment by culinko** [comment]
Related: #953

**Comment by culinko** [comment]
Similar: #708.

**Comment by culinko** [comment]
Closing in favor of #446.
