### ISSUE TITLE
Another joust bug

### ISSUE THREAD

**Issue by HugoKornelis** [Epix37/Hearthstone-Deck-Tracker#1423]
In my last game I ran into a Joust-related bug that I have not seen before.

I played a Joust card and I showed Stormwind Champion. Other than normal, the card was then greyed out in my deck as if I had already played it. Then, later in the game, I actually drew the card - and now HDT started to complain that the cards didn't match the selected deck. After that, it kept nagging about it every two seconds or so, no matter how often I clicked that I still wanted to keep playing and recording with the current deck.
After the game I could keep the game, but no replay file is available. (The game result did show up for the deck, though I had to edit the game to register the result)

**Comment by Epix37** [comment]
Is that with v0.10.16 or one of the pre-releases (17 and 18)?

In case of 0.10.16 this is most likely the same problem as #1399

**Comment by HugoKornelis** [comment]
I don't know where I can find the version number, but I never knowingly installed a pre-release and I assume that those will not be used by the auto-updater, so probably 0.10.16.
I have run into the #1399 bug as well, but after reading the feedback here I have disabled the automatic deck selection, and now that behaviour is no longer happening for me.

**Comment by Epix37** [comment]
should be fixed with v0.11.0
