### ISSUE TITLE
Game crash while adding notes to deck in HDT

### ISSUE THREAD

**Issue by JDILLACHANGEDMYLIFE** [Epix37/Hearthstone-Deck-Tracker#1425]
Hi,

I was playing ranked using HDT and I went to add notes to my active deck, typed in some text, and pressed save and it caused my Hearthstone Game Client to crash.  

I tried to recreate in Casual, went into a game and edited active deck, added and saved notes, and it worked fine.  I was not able to re-create. 

Thanks for the great work, one of the best donations I've made!

**Comment by Epix37** [comment]
I don't think HDT is able to crash Hearthstone. There is no interaction with the process/memory/anything. Most likely a coincidence.

**Comment by JDILLACHANGEDMYLIFE** [comment]
Yeah I saw that it is only reading the log file which is why I thought it seemed a bit crazy - though I don't think HS has ever crashed on me like that, something may have got jumbled up in my alt tabbing.  I hadn't used the notes previously, I will try to see if I can ever recreate and follow up. Thanks for the prompt response!
