### ISSUE TITLE
HDT crash as soon as it starts

### ISSUE THREAD

**Issue by Nakamasama** [Epix37/Hearthstone-Deck-Tracker#1426]
I'm getting a failure I can't even read before it goes away. Any assistance would be great!

http://pastebin.com/93zx7xHf for the log

**Comment by Epix37** [comment]
Try extracting the zip again. This could happen if some of the .xml files in the "Files" directory are missing.

**Comment by Nakamasama** [comment]
Yep, extracting it again worked. Thanks!

**Comment by Epix37** [comment]
Awesome :).
