### ISSUE TITLE
Pop-up Hearthstone doesnt work

### ISSUE THREAD

**Issue by tirhin** [Epix37/Hearthstone-Deck-Tracker#1427]
I ticked that pop up hearthstone on turn start line but when my turn comes it doesnt pop up.Hearthstone icon gets orange but window doesnt come to top.I feel like my os doesnt let it.Any ideas?

**Comment by culinko** [comment]
I created #847 for this issue.

**Comment by culinko** [comment]
Great news! This issue should be fixed in the next update.
