### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by Bonfire83** [Epix37/Hearthstone-Deck-Tracker#1429]
Every time I try to install with the HeartstoneDeckTracker.exe I get a message saying that the program stopped working. I have tried downloading it again, restarting my laptop, and trying other releases. Please advise.

**Comment by Epix37** [comment]
Try (re-)installing .NET Framework 4.5

**Comment by Bonfire83** [comment]
Thank you for the extremely fast reply. This came up when I tried.

Details

Microsoft .NET Framework 4.5 is already a part of this operating system.  You do not need to install the .NET Framework 4.5 redistributable.

Same or higher version of .NET Framework 4.5 has already been installed on this computer.

**Comment by Epix37** [comment]
That's why I sad __(re-)__ installing :)

**Comment by Bonfire83** [comment]
So uninstall the first one? Because I don't see an option to directly overwrite it.

**Comment by Epix37** [comment]
Yes. Repair might also work if that's an option.

**Comment by Bonfire83** [comment]
I don't actually see where to choose either Repair or Uninstall.

**Comment by Epix37** [comment]
http://knowledge.autodesk.com/support/autocad/troubleshooting/caas/sfdcarticles/sfdcarticles/How-to-remove-and-reinstall-the-Microsoft-NET-Framework.html

**Comment by Bonfire83** [comment]
Would it be the same as the Microsoft Visual C++ files? Because nothing says Microsoft .net

**Comment by riQQ** [comment]
What do you see, when you filter the programs by the term `.net`?

**Comment by Bonfire83** [comment]
"No items match your search."

**Comment by riQQ** [comment]
Try this: http://blogs.msdn.com/b/astebner/archive/2008/08/28/8904493.aspx

**Comment by Bonfire83** [comment]
Honestly I just give up. I know the program is great, but I don't know if it is worth all this trouble and I am afraid of messing up anything else since nothing else seems to be messing up. Thank you for your time.

**Comment by riQQ** [comment]
Maybe one last short try: run this in an administrative command line`DISM /Online /Cleanup-Image /RestoreHealth` (see: http://blogs.technet.com/b/joscon/archive/2012/09/26/fixing-component-store-corruption-in-windows-8-and-windows-server-2012.aspx)
