### ISSUE TITLE
Bug: The export command no longer works.

### ISSUE THREAD

**Issue by NikolaiAlexanderHimlan** [Epix37/Hearthstone-Deck-Tracker#1430]
After the most recent update, when attempting to export a deck HDT will simply sit on the "Creating Deck" screen and not interact with Hearthstone.  All other features seem to work properly.  I have added a screenshot of the log and can provide the actual log file if necessary.

![image](https://cloud.githubusercontent.com/assets/5479232/9795090/ba2a60a6-57bc-11e5-9908-f20d2662b21a.png)

**Comment by Epix37** [comment]
Seems to work no problem for me. From the exception I would guess the window in not in foreground for some reason.

**Comment by NikolaiAlexanderHimlan** [comment]
I can't reproduce the error anymore myself either.  I made sure it was happening consistently earlier before creating an issue, but it seems to be working fine now.  Yay?

**Comment by Epix37** [comment]
That's good I guess. Closing this for now.
