### ISSUE TITLE
Ranked game wasn't detected

### ISSUE THREAD

**Issue by riQQ** [Epix37/Hearthstone-Deck-Tracker#1433]
HDT-Log: http://pastebin.com/3GVErfEe
Asset-Log: http://pastebin.com/Q2ZVEmNJ

**Comment by Epix37** [comment]
The ranked detection starts at 23:38 but the last asset is unloaded at 23:32. Did you alt-f4 (or similar) out of the game by any chance?

**Comment by Epix37** [comment]
Oh it's not even not detecting ranked but not detecting the game mode. 

You idled in the victory screen after the game right? The mode detection times out after 5 minutes and only actually detects anything once you are back in the menu.

**Comment by riQQ** [comment]
Shouldn't it be in the log somewhere. I copied the log long after i left the victory screen. I didn't alt-f4 or similar.

**Comment by veri745** [comment]
I just had this happen to me as well, may be the same issue as #1398.

I didn't do anything unusual like idle at the victory screen

HDT Log:
http://pastebin.com/TZbTW2qC

Other logs:
http://www43.zippyshare.com/v/eqJwnLsE/file.html
(let me know if 7z isn't ok)

**Comment by riQQ** [comment]
This is obsolete with the new rank detection.
