### ISSUE TITLE
Card generated from Ysera  "lag" behind by a card

### ISSUE THREAD

**Issue by robertsmieja** [Epix37/Hearthstone-Deck-Tracker#1436]
Sorry for finding more problems and bugging you again but that generated card issue occured again with the latest release, Release v0.11.0

Scenario:
I get Ysera Awakens, then Laughing Sister. Ysera Awakens only shows up on the right after I get Laughing Sister.

Screenshots are below.

http://i58.tinypic.com/ephkhw.jpg
http://i60.tinypic.com/105r487.jpg

**Comment by Epix37** [comment]
No need to be sorry, thanks for finding and reporting it! :)
Fixed.

**Comment by Epix37** [comment]
fixed with v0.11.1
