### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Demoniko** [Epix37/Hearthstone-Deck-Tracker#1438]
New release (0.11.1) crashes at startup. 

########## 11.09.2015 11:24:00 ##########
System.Windows.Markup.XamlParseException: Вызов конструктора для типа "Hearthstone_Deck_Tracker.LoginWindow", удовлетворяющего указанным ограничениям привязки, привел к выдаче исключения. ---> System.InvalidOperationException: Последовательность не содержит элементов
   в System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   в Hearthstone_Deck_Tracker.Config.Reset(String name)
   в Hearthstone_Deck_Tracker.MainWindow.ConvertLegacyConfig(Version currentVersion, Version configVersion)
   в Hearthstone_Deck_Tracker.MainWindow..ctor(GameV2 game)
   в Hearthstone_Deck_Tracker.LoginWindow.StartMainApp()
   в Hearthstone_Deck_Tracker.LoginWindow..ctor()
   --- Конец трассировки внутреннего стека исключений ---
   в System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   в System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   в System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   в System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   в System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   в System.Windows.Application.DoStartup()
   в System.Windows.Application.<_ctor>b__0(Object unused)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Epix37** [comment]
Fixed with v0.11.2. Sorry about that.
https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.11.2
