### ISSUE TITLE
Always crash after winning

### ISSUE THREAD

**Issue by wu60918** [Epix37/Hearthstone-Deck-Tracker#1442]
Ranked games, Asia server, HS setting: traditional Chinese language, windowed mode.
After the update, HDT always crashes after winning the match.
What I  tried : restart Hs, restart HDT, restart PC, delete all HDT data and install again. 

########## 2015/9/11 下午 05:01:42 ##########
System.InvalidTimeZoneException: 在本機電腦上找到時區 ID 'Korea Standard Time'，但是登錄資訊已損毀。
   於 System.TimeZoneInfo.FindSystemTimeZoneById(String id)
   於 Hearthstone_Deck_Tracker.LogReader.Handlers.RachelleHandler.GoldTracking(String logLine, IGame game)
   於 Hearthstone_Deck_Tracker.LogReader.Handlers.RachelleHandler.Handle(String logLine, IHsGameState gameState, IGame game)
   於 Hearthstone_Deck_Tracker.LogReader.LogReaderManager.ProcessNewLines()
   於 Hearthstone_Deck_Tracker.LogReader.LogReaderManager.<StartLogReaders>d__1.MoveNext()
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[下午 04:48:17] ConvertLegacyConfig: changed config values
[下午 04:48:17] Game: -------- Reset ---------
[下午 04:48:17] OpponentSecrets: Cleared secrets
[下午 04:48:18] Game: -------- Reset ---------
[下午 04:48:18] OpponentSecrets: Cleared secrets
[下午 04:48:18] GameEventHandler: Reset constructed importing
[下午 04:48:18] Helper: Checking for LIVE updates...
[下午 04:48:18] Helper: Current version: 0.11.2.0
[下午 04:48:18] BackupManager: Running BackupManager
[下午 04:48:18] BackupManager: Backup for today already exists
[下午 04:48:18] PluginManager: Loading Plugins...
[下午 04:48:19] Helper: Latest LIVE version: 0.11.2.0
[下午 04:49:35] : Checking for duplicate matches...
[下午 04:49:59] UpdateOverlay: Refreshed overlay topmost status
[下午 04:50:03] UpdateOverlay: Refreshed overlay topmost status
[下午 04:50:05] UpdateOverlay: Refreshed overlay topmost status
[下午 04:51:49] UpdateOverlay: Refreshed overlay topmost status
[下午 04:51:53] UpdateOverlay: Refreshed overlay topmost status
[下午 04:51:53] LogReader: Current region: ASIA
[下午 04:52:04] GameEventHandler: Reset constructed importing
[下午 04:52:06] UpdateOverlay: Refreshed overlay topmost status
[下午 04:52:11] UpdateOverlay: Refreshed overlay topmost status
[下午 04:52:31] UpdateOverlay: Refreshed overlay topmost status
[下午 04:52:34] GameEventHandler: Reset constructed importing
[下午 04:52:48] UpdateOverlay: Refreshed overlay topmost status
[下午 04:53:00] UpdateOverlay: Refreshed overlay topmost status
[下午 04:53:01] Game: set CurrentGameMode to Casual
[下午 04:53:06] GameEventHandler: Reset constructed importing
[下午 04:53:33] UpdateOverlay: Refreshed overlay topmost status
[下午 04:53:34] GameEventHandler: Reset constructed importing
[下午 04:53:37] UpdateOverlay: Refreshed overlay topmost status
[下午 04:53:44] UpdateOverlay: Refreshed overlay topmost status
[下午 04:54:21] UpdateOverlay: Refreshed overlay topmost status
[下午 04:54:52] UpdateOverlay: Refreshed overlay topmost status
[下午 04:54:53] GameEventHandler: Reset constructed importing
[下午 04:56:21] SaveDeck: Saved Decks
[下午 04:56:21] SaveDeck: auto uploading new/edited deck
[下午 04:56:21] HearthStatsManager: trying to upload deck Hunter_T7 (Hunter)
[下午 04:56:21] HearthStatsManager: background process indicator ON
[下午 04:56:21] HearthStatsAPI: uploading deck: Hunter_T7 (Hunter)
[下午 04:56:21] Tracker: Switched to deck: Hunter_T7
[下午 04:56:21] Game: -------- Reset ---------
[下午 04:56:21] OpponentSecrets: Cleared secrets
[下午 04:56:21] DeckList: Set active deck to: Hunter_T7 (Hunter)
[下午 04:56:21] GameEventHandler: Reset constructed importing
[下午 04:56:21] GameEventHandler: Reset constructed importing
[下午 04:56:21] GameEventHandler: Reset constructed importing
[下午 04:56:22] HearthStatsAPI: HearthStatsId assigned to deck: 2101694
[下午 04:56:22] HearthStatsAPI: HearthStatsDeckVersionId assigned to deck: 2208884
[下午 04:56:22] HearthStatsManager: background process indicator OFF
[下午 04:56:22] HearthStatsManager: success uploading deck Hunter_T7 (Hunter)
[下午 04:56:33] HearthStatsManager: trying to update deck Hunter_T7 (Hunter)
[下午 04:56:33] HearthStatsAPI: editing deck: Hunter_T7 (Hunter)
[下午 04:56:34] HearthStatsManager: success updating deck Hunter_T7 (Hunter)
[下午 04:56:38] UpdateOverlay: Refreshed overlay topmost status
[下午 04:56:44] Game: set CurrentGameMode to Casual
[下午 04:57:02] GameEventHandler: --- Game start ---
[下午 04:57:02] Game: -------- Reset ---------
[下午 04:57:02] OpponentSecrets: Cleared secrets
[下午 04:57:02] Game: set CurrentGameMode to None
[下午 04:57:02] GameEventHandler: --- Opponent turn 1 ---
[下午 04:57:02] Player Draw: id=11, cardId=AT_087, cardName=Argent Horserider, turn=0
[下午 04:57:02] Player Draw: id=19, cardId=EX1_116, cardName=Leeroy Jenkins, turn=0
[下午 04:57:02] Player Draw: id=22, cardId=CS2_188, cardName=Abusive Sergeant, turn=0
[下午 04:57:02] Player Draw: id=30, cardId=EX1_544, cardName=Flare, turn=0
[下午 04:57:02] Opponent Draw: id=48, cardId=, cardName=, turn=0
[下午 04:57:02] Opponent Draw: id=57, cardId=, cardName=, turn=0
[下午 04:57:02] Opponent Draw: id=65, cardId=, cardName=, turn=0
[下午 04:57:02] Player CreateInHand: id=68, cardId=GAME_005, cardName=The Coin, turn=0, mark=Created, created=true
[下午 04:57:02] GameStats: Got coin
[下午 04:57:03] GameEventHandler: Playing against Warlock
[下午 04:57:22] Opponent Draw: id=56, cardId=, cardName=, turn=0
[下午 04:57:22] Opponent Mulligan: id=65, cardId=, cardName=, turn=0
[下午 04:57:26] Player Draw: id=29, cardId=EX1_533, cardName=Misdirection, turn=0
[下午 04:57:26] Player Mulligan: id=30, cardId=EX1_544, cardName=Flare, turn=0
[下午 04:57:26] Player Draw: id=23, cardId=BRM_013, cardName=Quick Shot, turn=0
[下午 04:57:26] Player Mulligan: id=19, cardId=EX1_116, cardName=Leeroy Jenkins, turn=0
[下午 04:57:27] Opponent Draw: id=40, cardId=, cardName=, turn=1
[下午 04:57:30] UpdateOverlay: Refreshed overlay topmost status
[下午 04:57:32] UpdateOverlay: Refreshed overlay topmost status
[下午 04:57:34] GameEventHandler: --- Player turn 2 ---
[下午 04:57:34] Player Draw: id=26, cardId=CS2_203, cardName=Ironbeak Owl, turn=1
[下午 04:57:41] GameEventHandler: --- Opponent turn 2 ---
[下午 04:57:41] Opponent Draw: id=54, cardId=, cardName=, turn=2
[下午 04:57:51] Opponent Play: id=54, cardId=FP1_007, cardName=Nerubian Egg, turn=2
[下午 04:57:52] GameEventHandler: --- Player turn 3 ---
[下午 04:57:52] Player Draw: id=33, cardId=EX1_089, cardName=Arcane Golem, turn=2
[下午 04:57:58] Player Play: id=68, cardId=GAME_005, cardName=The Coin, turn=2, mark=Created, created=true
[下午 04:57:58] Player PlayToGraveyard: id=68, cardId=GAME_005, cardName=The Coin, turn=2, mark=Created, created=true
[下午 04:58:00] Player Play: id=11, cardId=AT_087, cardName=Argent Horserider, turn=2
[下午 04:58:04] GameEventHandler: --- Opponent turn 3 ---
[下午 04:58:04] Opponent Draw: id=55, cardId=, cardName=, turn=3
[下午 04:58:12] Opponent Play: id=48, cardId=NEW1_019, cardName=Knife Juggler, turn=3
[下午 04:58:14] Opponent Play: id=55, cardId=CS2_065, cardName=Voidwalker, turn=3
[下午 04:58:18] GameEventHandler: --- Player turn 4 ---
[下午 04:58:18] Player Draw: id=25, cardId=EX1_536, cardName=Eaglehorn Bow, turn=3
[下午 04:58:28] UpdateOverlay: Refreshed overlay topmost status
[下午 04:58:31] Player Play: id=25, cardId=EX1_536, cardName=Eaglehorn Bow, turn=3
[下午 04:58:33] Opponent PlayToGraveyard: id=55, cardId=CS2_065, cardName=Voidwalker, turn=3
[下午 04:58:34] Player PlayToGraveyard: id=11, cardId=AT_087, cardName=Argent Horserider, turn=3
[下午 04:58:34] Opponent PlayToGraveyard: id=48, cardId=NEW1_019, cardName=Knife Juggler, turn=3
[下午 04:58:37] GameEventHandler: --- Opponent turn 4 ---
[下午 04:58:37] Opponent Draw: id=49, cardId=, cardName=, turn=4
[下午 04:58:49] Opponent Draw: id=51, cardId=, cardName=, turn=4
[下午 04:58:57] GameEventHandler: --- Player turn 5 ---
[下午 04:58:57] Player Draw: id=17, cardId=EX1_610, cardName=Explosive Trap, turn=4
[下午 04:59:04] Player SecretPlayedFromHand: id=29, cardId=EX1_533, cardName=Misdirection, turn=4, mark=Mulliganed
[下午 04:59:08] GameEventHandler: --- Opponent turn 5 ---
[下午 04:59:08] Opponent Draw: id=43, cardId=, cardName=, turn=5
[下午 04:59:20] Opponent Play: id=43, cardId=FP1_022, cardName=Voidcaller, turn=5
[下午 04:59:22] GameEventHandler: --- Player turn 6 ---
[下午 04:59:22] Player Draw: id=24, cardId=EX1_539, cardName=Kill Command, turn=5
[下午 04:59:48] Player Play: id=26, cardId=CS2_203, cardName=Ironbeak Owl, turn=5
[下午 04:59:59] Player Play: id=24, cardId=EX1_539, cardName=Kill Command, turn=5
[下午 04:59:59] Player PlayToGraveyard: id=24, cardId=EX1_539, cardName=Kill Command, turn=5
[下午 05:00:00] GameEventHandler: --- Opponent turn 6 ---
[下午 05:00:00] Opponent Draw: id=44, cardId=, cardName=, turn=6
[下午 05:00:09] Opponent Play: id=57, cardId=EX1_316, cardName=Power Overwhelming, turn=6
[下午 05:00:09] TagChange: WARNING - unhandled zone change (id=69): CREATED -> SETASIDE
[下午 05:00:09] Opponent CreateInPlay: id=69, cardId=EX1_316e, cardName=Power Overwhelming, turn=6, mark=Created, created=true
[下午 05:00:09] Opponent PlayToGraveyard: id=57, cardId=EX1_316, cardName=Power Overwhelming, turn=6
[下午 05:00:10] TagChange: WARNING - unhandled zone change (id=70): CREATED -> SETASIDE
[下午 05:00:10] Player CreateInPlay: id=70, cardId=EX1_536e, cardName=Upgraded, turn=6, mark=Created, created=true
[下午 05:00:10] Opponent PlayToGraveyard: id=43, cardId=FP1_022, cardName=Voidcaller, turn=6
[下午 05:00:13] UpdateOverlay: Refreshed overlay topmost status
[下午 05:00:22] Opponent Play: id=56, cardId=GVG_045, cardName=Imp-losion, turn=6, mark=Mulliganed
[下午 05:00:22] Opponent CreateInPlay: id=71, cardId=GVG_045t, cardName=Imp, turn=6, mark=Created, created=true
[下午 05:00:22] Opponent CreateInPlay: id=72, cardId=GVG_045t, cardName=Imp, turn=6, mark=Created, created=true
[下午 05:00:22] Opponent PlayToGraveyard: id=56, cardId=GVG_045, cardName=Imp-losion, turn=6, mark=Mulliganed
[下午 05:00:22] Player PlayToGraveyard: id=26, cardId=CS2_203, cardName=Ironbeak Owl, turn=6
[下午 05:00:25] Opponent PlayToGraveyard: id=54, cardId=FP1_007, cardName=Nerubian Egg, turn=6
[下午 05:00:25] TagChange: WARNING - unhandled zone change (id=69): PLAY -> REMOVEDFROMGAME
[下午 05:00:25] Opponent CreateInPlay: id=73, cardId=FP1_007t, cardName=Nerubian, turn=6, mark=Created, created=true
[下午 05:00:25] GameEventHandler: --- Player turn 7 ---
[下午 05:00:25] Player Draw: id=6, cardId=BRM_013, cardName=Quick Shot, turn=6
[下午 05:00:39] Player SecretPlayedFromHand: id=17, cardId=EX1_610, cardName=Explosive Trap, turn=6
[下午 05:00:41] Player Play: id=33, cardId=EX1_089, cardName=Arcane Golem, turn=6
[下午 05:00:43] Player Play: id=22, cardId=CS2_188, cardName=Abusive Sergeant, turn=6
[下午 05:00:43] TagChange: WARNING - unhandled zone change (id=74): CREATED -> SETASIDE
[下午 05:00:43] Player CreateInPlay: id=74, cardId=CS2_188o, cardName='Inspired', turn=6, mark=Created, created=true
[下午 05:00:49] Player PlayToGraveyard: id=74, cardId=CS2_188o, cardName='Inspired', turn=6, mark=Created, created=true
[下午 05:00:49] GameEventHandler: --- Opponent turn 7 ---
[下午 05:00:49] Opponent Draw: id=59, cardId=, cardName=, turn=7
[下午 05:01:00] UpdateOverlay: Refreshed overlay topmost status
[下午 05:01:04] Opponent PlayToGraveyard: id=72, cardId=GVG_045t, cardName=Imp, turn=7, mark=Created, created=true
[下午 05:01:04] Player PlayToGraveyard: id=22, cardId=CS2_188, cardName=Abusive Sergeant, turn=7
[下午 05:01:06] Opponent PlayToGraveyard: id=71, cardId=GVG_045t, cardName=Imp, turn=7, mark=Created, created=true
[下午 05:01:18] Opponent Play: id=44, cardId=EX1_320, cardName=Bane of Doom, turn=7
[下午 05:01:18] Opponent CreateInPlay: id=75, cardId=AT_026, cardName=Wrathguard, turn=7, mark=Created, created=true
[下午 05:01:18] Opponent PlayToGraveyard: id=44, cardId=EX1_320, cardName=Bane of Doom, turn=7
[下午 05:01:18] Player PlayToGraveyard: id=33, cardId=EX1_089, cardName=Arcane Golem, turn=7
[下午 05:01:24] GameEventHandler: --- Player turn 8 ---
[下午 05:01:24] Player Draw: id=35, cardId=CS2_203, cardName=Ironbeak Owl, turn=7
[下午 05:01:30] Player Play: id=6, cardId=BRM_013, cardName=Quick Shot, turn=7
[下午 05:01:30] Player PlayToGraveyard: id=6, cardId=BRM_013, cardName=Quick Shot, turn=7
[下午 05:01:31] Opponent PlayToGraveyard: id=36, cardId=HERO_07, cardName=Gul'dan, turn=7
[下午 05:01:31] GameEventHandler: --- Game was won! ---
[下午 05:01:31] Gamestats: Current Game ended after 7 turns
[下午 05:01:31] GameStats: Assigned current game to deck: Hunter_T7
[下午 05:01:31] GameEventHandler: waiting for game mode detection

**Comment by Epix37** [comment]
`Korea Standard Time` is definitely the correct id and it doesn't crash for me when I call `TimeZoneInfo.FindSystemTimeZoneById("Korea Standard Time")`.

Could you translate this for me? 
"System.InvalidTimeZoneException: 在本機電腦上找到時區 ID 'Korea Standard Time'，但是登錄資訊已損毀。"

Googling the second phrase brings up this: http://windows.microsoft.com/en-us/windows/fix-corrupted-user-profile#1TC=windows-7

Maybe that helps?

**Comment by wu60918** [comment]
"System.InvalidTimeZoneException: 在本機電腦上找到時區 ID 'Korea Standard Time'，但是登錄資訊已損毀。"

System.InvalidTimeZoneException: timezone ID 'Korea Standard Time' is found in this computer, but the registration information is damaged.

I think the following link would help but I don't know how to correct it.
https://msdn.microsoft.com/en-us/library/system.timezoneinfo.findsystemtimezonebyid(v=vs.110).aspx

Thanks for help BTW :)

**Comment by Elitesparkle** [comment]
I have a similar issue.

In my case it crashes after a loss, I think.

Here is the crash report for the last crash:
http://pastebin.com/xCj3qbYJ

I have 5 more reports in the folder.
I could upload them, if needed.

**Comment by Epix37** [comment]
https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1443#issuecomment-139515493

**Comment by Elitesparkle** [comment]
> #1443 (comment)

I wasn't sure it was causing the problem.

Thanks.

**Comment by culinko** [comment]
Just a wild guess: isn't this happening because there are some characters (下午) in the time format?

**Comment by Epix37** [comment]
The problem is that the system can not find a TimeZoneInfo for "Korea Standard Time", which exists - this is a system issue.
