### ISSUE TITLE
[End Game Plugin] Always Crashing after Games

### ISSUE THREAD

**Issue by BigBjoern** [Epix37/Hearthstone-Deck-Tracker#1443]
HDT crashes after all my games, regardless of win or defeat.

I tried restarting HDT and HS. I even installed new, after the update fixing a similar issue for asian players.

Im Playing in fullscreen mode, on EU-Servers 1920x1080. 

In Germany (GMT+1).

Im also using the plugin Arena Helper, wich seems to grab wrong Time an Date for saving my Arena Deck.
The Date is off by one day and the time by around 2 hours (wrong time zone/ Summer time)?

Here is the Crash Report:

########## 11.09.2015 12:40:55 ##########
System.TypeLoadException: Der Typ "Hearthstone_Deck_Tracker.Hearthstone.Game" in der Assembly "HearthstoneDeckTracker, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null" konnte nicht geladen werden.
   bei HDT.Plugins.EndGame.Screenshot.Capture.<Advanced>d__4.MoveNext()
   bei System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   bei HDT.Plugins.EndGame.Screenshot.Capture.Advanced(Int32 delay, String dir, Int32 num, Int32 delayBetween)
   bei HDT.Plugins.EndGame.EndGame.<ScreenShot>d__0.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Epix37** [comment]
The current version of the EndGame screenshot plugin does not work. Disable that one for now, there will probably be an update soon!

**Comment by BigBjoern** [comment]
I will try this.

**Comment by BigBjoern** [comment]
It was definately an Issue with the End Game Plugin. Everything runs smooth now. Thank you
