### ISSUE TITLE
Obtained Cards Still Showing as In hand

### ISSUE THREAD

**Issue by BobT36** [Epix37/Hearthstone-Deck-Tracker#1448]
I have the option turned on to highlight cards that are in my hand. 

Cards like the Coin, and others that are Obtained (such as from Webspinner) stay highlighted even after I've played them, and even when the minion has died etc.

This is as of v0.11.2

**Comment by Epix37** [comment]
I think you may have "options > overlay > player > include obtained" turned on? That would cause the coin to stay green..

**Comment by BobT36** [comment]
I do. Switching it off removed the Coin from the tracker, but my Silverback Patriarch (obtained from a Webspinner) still showed in the tracker, and highlighted in green, even after it was played, and died.

I presumed Include Obtained would just mean those cards appear in my deck in the tracker? And would grey out / be de-highlighted in the normal way.

Gold tracking now works btw! <3 Also see my mail about the FPS improvement.

**Comment by Epix37** [comment]
Obtained cards are anything that was created in your hand. Not sure about the Silverback Patriarch. Might have just been the overlay not updating properly. Let me know if you see that again with the option turned off.

**Comment by BobT36** [comment]
Yeah I understand that. Obtained cards being added to the tracker deck and highlighted when drawn works correctly.

I'd expect them to be de-highlighted and greyed out when played though (as with other cards) if that's possible, rather than still showing as if they're in my hand. 

Turning the Obtained option off would just not show them at all ya? (Not what I want)

And yep I'll keep an eye out as I use more webspinners / portals etc. :) 

An easy way of testing would probably be to do the Webspinner or Portal challenges in the Naxx / Blackrock levels?

**Comment by riQQ** [comment]
Maybe changing the color for cards in hand might be a solution. Another reason for this is consistency: it's harder to understand that the green coloring has a different meaning depending on the card owner.

**Comment by BobT36** [comment]
Yep, just tested vs High Justice Grimstone, all cards summoned from portals appear correctly in hand, but stay highlighted in green even after they're played. As the posted above notes, this causes confusion between what I have in my hand, and what I "Obtained" but have already played.

I'd expect them to be greyed out when played, as with other cards. Maybe use a symbol to designate obtained (as with enemy cards), OR keep them highlighted, but change the colour.

**Comment by Epix37** [comment]
Here is a different idea for indicating obtained/created cards:
![obtained1](https://cloud.githubusercontent.com/assets/7737910/9844631/063d7662-5ac5-11e5-9c8d-3fec90977ba3.PNG)
![obtained2](https://cloud.githubusercontent.com/assets/7737910/9844632/07743890-5ac5-11e5-8a7b-b468b04a0ee3.PNG)

I'm not sure which one I like better.
With this the hand highlighting should also work as intended.

**Comment by Epix37** [comment]
Here is another one:
![obtained3](https://cloud.githubusercontent.com/assets/7737910/9846728/42f886c8-5ad4-11e5-8767-a56642ab7ca5.PNG)

I think I like this one

**Comment by Epix37** [comment]
Another issue with greying out played, created cards is that it will not be consistent with cards that were generated in the deck (3 secretkepers created by gang up). Those will be greyed out once the last one is drawn (because they actually were in the deck).

I would say this is an okay solution for now but the only way to properly deal with that might be @culinko's approach: #961
