### ISSUE TITLE
Unable to Import Decks hearthpwn

### ISSUE THREAD

**Issue by prizmpaladin** [Epix37/Hearthstone-Deck-Tracker#1449]
Unable to import decks from hearthpwn. Receive message "Error Could not load deck from specified url" Some examples:

http://www.hearthpwn.com/deckbuilder/druid#31:2;60:2;74:1;84:1;238:2;246:2;282:2;310:2;326:2;434:2;480:2;532:2;535:2;548:2;620:2;667:2;

http://www.hearthpwn.com/deckbuilder/druid#31:2;34:2;237:2;280:1;282:2;329:2;372:2;396:1;459:2;498:1;548:2;587:2;605:1;620:2;633:2;7730:2;7751:2;

Tested importing decks from hearthstats works okay.

**Comment by Epix37** [comment]
Importing from the deckbuilder is not supported, only "published" decks.
