### ISSUE TITLE
HDT always asks me to restart Heartstone for the log.config file

### ISSUE THREAD

**Issue by vikaman** [Epix37/Hearthstone-Deck-Tracker#1450]
Hi there,

HDT is now always asking me to restart Hearthstone (the log.config file) reason. 

I was tired of it so I decided to delete the log.config file to see if the new one that generates would help. For some reason, the log file is not generating now.

I realise this might be more of a Hearthstone problem that HDT issue, but I was wondering if anyone else was seeing this.

**Comment by Epix37** [comment]
Does running HDT as administrator help?

**Comment by Epix37** [comment]
If not, create a new log.config an paste this: http://dpaste.com/0YYCDYF

**Comment by vikaman** [comment]
Yes! That seemed to work. Very odd problem. Sorry to pester you, but would you know why the plugins aren't working?

I run everything in administrator mode and wanted to 'unblock' the .dlls, but I don't have that option. HDT has also been restarted.

Image: http://i.imgur.com/Vo9eRFg.png

**Comment by riQQ** [comment]
Are the plugins enabled (`Options -> Tracker -> Plugins`)?

**Comment by vikaman** [comment]
Sigh. I'm an idiot.

Thanks riQQ!

**Comment by Itball** [comment]
Hey, this didn't solve the problem for me. I've tried running as admin and creating a fresh log.config several times. Anything else I could try? thanks

**Comment by Itball** [comment]
I've done a full reinstall and that sorted it
