### ISSUE TITLE
Issue when trying to log in

### ISSUE THREAD

**Issue by aklaz** [Epix37/Hearthstone-Deck-Tracker#1454]
Hi,
i've got this error when i try to log in with my hearthstats account:
http://i.imgur.com/7pFJjuk.jpg
And when i login as a guest, got this error:
http://i.imgur.com/nsO2BHM.jpg

So, i can only use hearthstone deck tracker as a guest
Any tips?
thank you

**Comment by Epix37** [comment]
This is probably some proxy or firewall issue, not really sure :/.
