### ISSUE TITLE
Feature Request: Default to saved when importing Arena decks

### ISSUE THREAD

**Issue by mindstormer12** [Epix37/Hearthstone-Deck-Tracker#1455]
Hearthstone Deck Tracker has come a long way (I remember having to manually add in duplicate cards in arena and then having to select which deck to use). It is mostly automated now but there's still improvements to be made. How about defaulting to "Save" when importing Arena? Then when you could click "Unsave" if you don't want to automatically save it. I can't see a situation in Arena where you need to change around cards anyway--you just import that 30 cards you've chosen and want them to be tracked.

**Comment by Epix37** [comment]
`options > tracker > importing > arena > importing behaviour: auto import&save`
Is that what you are looking for?

**Comment by mindstormer12** [comment]
Yes... I read all the patch notes and must've missed it. Sorry.
