### ISSUE TITLE
Gold progress bug (minor)

### ISSUE THREAD

**Issue by HugoKornelis** [Epix37/Hearthstone-Deck-Tracker#1456]
I am glad to hear that the previous issue where the gold tracker had stopped working has been fixed, I have now re-enabled the tracker, and it works nice in Play mode,
However, during an Arena run the gold tracker apparently thinks I should be rewarded too. After having won a few arena fights, it is now telling me that some wins have not been awarded, and that I have "7/3" wins. As far as I know, arena games are not counted for the three-wins-ten-gold reward, so HDT should not expect to see a gold reward.

**Comment by GaryKing** [comment]
Yep I'm seeing this too. It seems to think Arena games should reward the 10 gold for every 3 wins, when it shouldn't.

**Comment by chucklu** [comment]
arena games are not counted for the three-wins-ten-gold reward
I do not know this rule
I will try to fix this later

**Comment by chucklu** [comment]
else if ((DateTime.Now - gameState.LastGameStart) > TimeSpan.FromSeconds(10)
                     && game.CurrentGameMode != GameMode.Spectator)
            {
                GoldTracking(logLine, game);
            }
this code just except  Spectator game mode,so we should except arena mode too?

**Comment by chucklu** [comment]
public enum GameMode
	{
		All, //for filtering @ deck stats
		Ranked,
		Casual,
		Arena,
		Brawl,
		Friendly,
		Practice,
		Spectator,
		None
	}
we have 8 game mode in the decker
@HugoKornelis , Spectator and Arena should not include in gold tracker.
so, what abour the other modes?

**Comment by riQQ** [comment]
Only Brawl, Casual and Ranked games count towards the 10 gold per 3 wins bonus.

**Comment by chucklu** [comment]
@riQQ Thank you!I will fix this and send a new pull request to @Epix37

**Comment by LizardDude** [comment]
Arena matches still count toward the gold tracker.
