### ISSUE TITLE
issue with login

### ISSUE THREAD

**Issue by noize1337** [Epix37/Hearthstone-Deck-Tracker#1457]
Hey, always if i try to login / register i get this Error.
-----
Ich hatte heute einen Stromausfall und seitdem Tritt das Problem auf.
Alles gelöscht + Neu gedownloadet nichts gebracht :santa: 
http://puu.sh/k8PD2/8bd028dcdf.png

**Comment by Epix37** [comment]
Sieht nach Server Problemen aus, versuchs einfach später noch einmal.
