### ISSUE TITLE
How comprehensive is the Secrets Interactivity feature?

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#1458]
I just started using HDT with Interactivity On for Secrets, especially against the Secret Paladin deck.

I haven't played enough games yet to figure out all the edge cases of this feature. How comprehensive is it? For instance, if the opponent has already played two Avenges, then would Avenge be greyed out in the Secrets list (only in Constructed, NOT in Arena), since they can only have two? 

Or if I manually grey out Avenge when they only have one secret, but once they play another Secret, does the entire Secret list reset and un-grey any secrets I clicked on?

Or if they have two secrets, and one of them turns out to be Avenge, then would Avenge be then greyed out in the list, since they can't have another Avenge in play? (Unless they then play another one.)

**Comment by Epix37** [comment]
>  How comprehensive is it? For instance, if the opponent has already played two Avenges, then would Avenge be greyed out in the Secrets list (only in Constructed, NOT in Arena), since they can only have two?

Yes, just not in the current release because I broke that.

> Or if I manually grey out Avenge when they only have one secret, but once they play another Secret, does the entire Secret list reset and un-grey any secrets I clicked on?

it adds 1 to every secret

> Or if they have two secrets, and one of them turns out to be Avenge, then would Avenge be then greyed out in the list, since they can't have another Avenge in play? (Unless they then play another one.)

Yes

**Comment by chucklu** [comment]
>For instance, if the opponent has already played two Avenges, then would Avenge be greyed out in the Secrets list (only in Constructed, NOT in Arena), since they can only have two?

Nefarian can give one more Avenge to you

**Comment by Epix37** [comment]
Very very rare case though. You can always click the secret again to "un-grey" it.

**Comment by GaryKing** [comment]
Yes, or Spellslinger too.

Okay, I look forward to using this feature more. It's definitely the most useful feature that I overlooked (because of all the big warning signs on the page where you enable this feature). The most useful feature of HDT overall, that is probably not as well known as it should be, is the replay feature.

**Comment by Epix37** [comment]
Doublechecked, it only takes non-created secrets into account.

Feel free to continue discussion here but I'm gonna close it since it's not really an "issue" (bug, feature request, problem).
