### ISSUE TITLE
HS lag/stutter issues ever since card tracking rewritten

### ISSUE THREAD

**Issue by Rynvar** [Epix37/Hearthstone-Deck-Tracker#1459]
I've been having terrible stutter in HS ever since the version that changed the card tracking system(v0.10.17) up util the latest version (v0.11.2). It happens both in menus and in game, including when starting the game for the first time and browsing the menus, before getting into a match. 

System specs are i5-4690k and R9 270x and the game is running from an SSD, so there is no bottlenecking on the hardwars side. I've checked task manager and there is no abnormal CPU or Disk usage when HS and the tracker are running. The moment I close the tracker, HS goes back to being buttery smooth. 

After installing the latest version, I've also deleted the log.config file and let the tracker recreate it. It has filePrinting = True and consolePrinting = False.

EDIT: I've also tried excluding the tracker, HS and the Blizzard localappdata folder from Kaspersky antivirus, still doesn't help. Reinstalling HS also doesn't fix it.

**Comment by Rynvar** [comment]
Update: I think you can close the issue, I reinstalled AMD drivers since I was starting to get stutter in other games as well and that seems to have fixed the problem.

**Comment by Epix37** [comment]
That sounds good :).
