### ISSUE TITLE
Ranked Game being marked as Casual Game.

### ISSUE THREAD

**Issue by lee-CS** [Epix37/Hearthstone-Deck-Tracker#1460]
i've been using HS for a long time but this is the first time i've seen it happen. Just got the newest patch today.

![casual](https://cloud.githubusercontent.com/assets/6370567/9833291/b4d47d94-5956-11e5-888a-f13c0be8b381.PNG)

**Comment by lee-CS** [comment]
Since some games are tracked as Casual, the actual Rank and the Rank in the tracker does not match up.


![image](https://cloud.githubusercontent.com/assets/6370567/9972945/e09f6cde-5e30-11e5-8671-68dd6a500b6f.png)

**Comment by GiggliG** [comment]
I've seen this happen a few times too now.

**Comment by culinko** [comment]
Incorrect rank is not related to the rest of the games being tracked as Casual, it's related to a couple of other factors that make different assets being unloaded: friendlist opened at some point, opponent's rank, ranking up/down (see the discussion in #775).

**Comment by CovertJaguar** [comment]
I see this often.

**Comment by Rhakete** [comment]
I'm having the same problem. With my settings, it should be recorded correctly.
![hdt-settings](https://cloud.githubusercontent.com/assets/15165994/10556394/0a3dfc9c-7482-11e5-9384-e62f9df25172.png)
