### ISSUE TITLE
All of my games have disappeared????

### ISSUE THREAD

**Issue by FishermanHS** [Epix37/Hearthstone-Deck-Tracker#1462]
I was on this morning, and my decktracker was fine. Went to work, came home, started up hearthstone and the deck tracker, now all of my games in my tracker are missing. I probably had at least 1000+ games logged in the tracker. Weird part is all my decks are still there, just no stats. Tried restarting it, didn't work. Is there a way to get them back? 

![23a0043d0454798808315822b3cc39b8](https://cloud.githubusercontent.com/assets/12855333/9834470/5bcf62d6-596f-11e5-8736-394ceda01a96.png)

**Comment by Epix37** [comment]
* `options > tracker > settings > open appdata folder`
* check the size of the "DeckStats.xml" file, if that's somewhere in the two digit kilobytes it proably got corrupted
* if so:
  * Close HDT
  * go to the "Backups" folder
  * replace the "DeckStats.xml" with the one from yesterday
* if not: this is probably some settings/filter issue

**Comment by FishermanHS** [comment]
It's 81KB and there's another thing under it called "DeckStats_corrupted.xml", so yeah I'm guessing it's corrupted.

How do I replace the DeckStats.xml with one from before it stopped working?

**Comment by Epix37** [comment]
> * if so:
  * Close HDT
  * go to the "Backups" folder
  * replace the "DeckStats.xml" with the one from yesterday

(Backup folder contains zips, take the one dated before today, open, replace DeckStats.xml)

**Comment by FishermanHS** [comment]
Nice, that worked! Thank you so much!
