### ISSUE TITLE
Tavern brawl games not recorded as of 0.11.2

### ISSUE THREAD

**Issue by VicTT** [Epix37/Hearthstone-Deck-Tracker#1463]
The stats for the game are recorded correctly, but Stats->Select Replay shows no replay for games played in Tavern Brawl. Also checked Replays folder: they're not there either.
"Epix, plz fixxxx!"

**Comment by VicTT** [comment]
Also, when I reopened HDT, some Brawl decks that had stats before lost stats, including the ones that were "recorded correctly" today.

**Comment by riQQ** [comment]
It's working for me. Is recording enabled for Brawl? (`Options -> Tracker -> Stats)`

**Comment by VicTT** [comment]
Thanks for the suggestion: you were right; it was not enabled. Before the update, I had logging enabled for every game mode, but Brawl must have got introduced in the last patch. This should be documented to prevent dupes from other people noticing this.
