### ISSUE TITLE
Cant see opponent's played cards on my left side bar.

### ISSUE THREAD

**Issue by HowIsYourMoM** [Epix37/Hearthstone-Deck-Tracker#1464]
Since the last patch im not able to see it,my own cards too.How can i fix it?

Thanks.

**Comment by HowIsYourMoM** [comment]
Im not able to see any of my played cards,opponents and mine,please fix ASAP.

**Comment by Epix37** [comment]
Try restarting HDT and hearthstone

**Comment by HowIsYourMoM** [comment]
LOL Thank you very much and ur hard work epixhube! I was sure i restarted client and HS deck tracker,seems it worked at the second try.Thank you again! Keep it up.And keep updating constantly.we need something like more automatic,less typing.

**Comment by Epix37** [comment]
:)
