### ISSUE TITLE
How can i add my arena deck without typing

### ISSUE THREAD

**Issue by HowIsYourMoM** [Epix37/Hearthstone-Deck-Tracker#1465]
Hi,i just saw Kripp making an arena deck then in 1 second i was able to see his deck in the screen.It wasnt a screenshot because he was using HS deck tracker.He did it without typing.I would like to know how can i automatically do what he did.Where is the option,i dont see it.

Thanks!

**Comment by Epix37** [comment]
You can select how arena importing is supposed be handled under `options > tracker > importing`
