### ISSUE TITLE
Crash report (I can't open Hearthstone Deck Tracker) 

### ISSUE THREAD

**Issue by JimmyHS** [Epix37/Hearthstone-Deck-Tracker#1468]
########## 13/09/2015 15:54:12 ##########
System.Windows.Markup.XamlParseException: L'invocation du constructeur sur le type 'Hearthstone_Deck_Tracker.LoginWindow' qui correspond aux contraintes de liaison spécifiées a levé une exception. ---> System.Exception: Error restoring PlayerDecks backup. Please manually rename "PlayerDecks_backup.xml" to "PlayerDecks.xml" in "%appdata\HearthstoneDeckTracker". ---> System.InvalidOperationException: Il existe une erreur dans le document XML (0, 0). ---> System.Xml.XmlException: Élément racine manquant.
   à System.Xml.XmlTextReaderImpl.Throw(Exception e)
   à System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   à System.Xml.XmlTextReaderImpl.Read()
   à System.Xml.XmlTextReader.Read()
   à System.Xml.XmlReader.MoveToContent()
   à Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckList.Read9_Decks()
   --- Fin de la trace de la pile d'exception interne ---
   à System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   à System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   à Hearthstone_Deck_Tracker.XmlManager`1.Load(String path)
   à Hearthstone_Deck_Tracker.DeckList.Load()
   --- Fin de la trace de la pile d'exception interne ---
   à Hearthstone_Deck_Tracker.DeckList.Load()
   à Hearthstone_Deck_Tracker.MainWindow..ctor(GameV2 game)
   à Hearthstone_Deck_Tracker.LoginWindow.StartMainApp()
   à Hearthstone_Deck_Tracker.LoginWindow..ctor()
   --- Fin de la trace de la pile d'exception interne ---
   à System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   à System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   à System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   à System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   à System.Windows.Application.DoStartup()
   à System.Windows.Application.<.ctor>b__1(Object unused)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

########## 13/09/2015 15:54:22 ##########
System.Windows.Markup.XamlParseException: L'invocation du constructeur sur le type 'Hearthstone_Deck_Tracker.LoginWindow' qui correspond aux contraintes de liaison spécifiées a levé une exception. ---> System.Exception: Error restoring PlayerDecks backup. Please manually rename "PlayerDecks_backup.xml" to "PlayerDecks.xml" in "%appdata\HearthstoneDeckTracker". ---> System.InvalidOperationException: Il existe une erreur dans le document XML (0, 0). ---> System.Xml.XmlException: Élément racine manquant.
   à System.Xml.XmlTextReaderImpl.Throw(Exception e)
   à System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   à System.Xml.XmlTextReaderImpl.Read()
   à System.Xml.XmlTextReader.Read()
   à System.Xml.XmlReader.MoveToContent()
   à Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckList.Read9_Decks()
   --- Fin de la trace de la pile d'exception interne ---
   à System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   à System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   à Hearthstone_Deck_Tracker.XmlManager`1.Load(String path)
   à Hearthstone_Deck_Tracker.DeckList.Load()
   --- Fin de la trace de la pile d'exception interne ---
   à Hearthstone_Deck_Tracker.DeckList.Load()
   à Hearthstone_Deck_Tracker.MainWindow..ctor(GameV2 game)
   à Hearthstone_Deck_Tracker.LoginWindow.StartMainApp()
   à Hearthstone_Deck_Tracker.LoginWindow..ctor()
   --- Fin de la trace de la pile d'exception interne ---
   à System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   à System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   à System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   à System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   à System.Windows.Application.DoStartup()
   à System.Windows.Application.<.ctor>b__1(Object unused)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Epix37** [comment]
* Go to `%AppData%/HearthstoneDeckTracker` (Win+R, paste)
* Delete "PlayerDecks.xml"
* if "PlayerDecks_backup.xml" exists: rename it to "PlayerDecks.xml"
* otherwise: open the "Backups" folder and replace the PlayerDecks.xml with the one from the latest backup.

**Comment by JimmyHS** [comment]
Thanks!

**Comment by Epix37** [comment]
No problem :)

**Comment by Viilla** [comment]
Yo tengo ese problema pero me gustaria un video paso a paso por favor ya q no logro determinar las ubicaciones en mi pc
