### ISSUE TITLE
Cards can appear twice

### ISSUE THREAD

**Issue by robertsmieja** [Epix37/Hearthstone-Deck-Tracker#1471]
It looks like cards can occasionally appear twice. My first guess is that this can happen because the card that came from Webspinner is also in the deck, but they are not grouped together. 

Here's a screenshot: http://i.imgur.com/MwHVVB7.jpg

I'll update with more info if I can.

**Comment by Epix37** [comment]
See #1448. This is working as inteded, just a bit unclear. Trying to find a better solutioin for that as I write this.
