### ISSUE TITLE
Opponent card tracking can "lag"

### ISSUE THREAD

**Issue by robertsmieja** [Epix37/Hearthstone-Deck-Tracker#1472]
The first card my opponent didn't show up until he played the second card.

Screenshots below:
http://i.imgur.com/eWAdZGI.jpg
http://i.imgur.com/9TutVRP.jpg

Appears to be intermittent.

**Comment by Epix37** [comment]
Interesting... especially since the hand count and marks are correct. How often have you noticed this?

**Comment by robertsmieja** [comment]
I've been a bit too busy to play and try to reproduce, but it seems pretty intermittent. 

I would close this issue and if I figure out how to reproduce it I'll reopen it with the relevant information.

**Comment by 305jeff** [comment]
Kind of unrelated, but have you noticed that when you draw a card, it no longer shows up in the deck tracker before it's actually drawn? I definitely miss seeing the card highlight on the tracker before it even shows up in my hand!

**Comment by culinko** [comment]
This used to happen before (rarely), but I don't think I've seen it in a long time. Can someone confirm that this is fixed?

**Comment by robertsmieja** [comment]
I think it's been fixed recently with the card themes update. I haven't seen this since then.
