### ISSUE TITLE
The current version is completely broken.

### ISSUE THREAD

**Issue by ericBG** [Epix37/Hearthstone-Deck-Tracker#1474]
All the cards are "UNKNOWN", importing is broken... I deleted all 21 decks (permanently, I've gotten into a habit of SHIFT+DEL for some reason) that I had because I thought they just needed to be remade. Nope.

DO NOT use the latest version.

**Comment by Epix37** [comment]
The current version is fine.

Try downloading the latest version again: https://github.com/Epix37/Hearthstone-Deck-Tracker/releases and make sure to unzip all files. "UNKNOWN" most likely means some files were not extracted. 

HDT creates daily backups you can restore under `options > tracker > backups`, that will get you your decks back.

**Comment by ericBG** [comment]
I tried redownloading it. I would've even checked with an md4 hash if that was provided, but it was not.

That is great to know, thank you!
