### ISSUE TITLE
Crashes on Start

### ISSUE THREAD

**Issue by Maestrodobis** [Epix37/Hearthstone-Deck-Tracker#1476]
hey my deck tracker failed when I tried to start it up.  Here is a screenshot of the crash file.  Let me know if you need more info.

![deck tracker](https://cloud.githubusercontent.com/assets/10744907/9860502/8f54cb78-5afa-11e5-84b4-abf9eb0339b0.PNG)

**Comment by Epix37** [comment]
Try reinstalling .NET Framework 4.5

**Comment by Maestrodobis** [comment]
I'm using 4.5.2 and I just repaired it. I didn't work

**Comment by Epix37** [comment]
Could you post the rest of the second line that's cut off?

**Comment by Maestrodobis** [comment]
System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'Hearthstone_Deck_Tracker.LoginWindow' that matches the specified binding constraints threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Windows.Controls.TextBox' threw an exception. ---> System.Runtime.InteropServices.SEHException: External component has thrown an exception.

**Comment by Maestrodobis** [comment]
it works now.  I did a complete uninstall reinstall.  Sorry for the trouble!

**Comment by Epix37** [comment]
Great :).
