### ISSUE TITLE
HDT Not responding / not starting

### ISSUE THREAD

**Issue by Morthcongael** [Epix37/Hearthstone-Deck-Tracker#1477]
Hey there. whenever I try to start HDT it boots up,but gets stuck during loading. Uninstalling and reinstalling merely makes it freeze after login screen instead. I tried repairing .NET 4.5 to no use. Anything I can do?

**Comment by Epix37** [comment]
Please try uninstalling and re-installing .NET 4.5.

**Comment by Morthcongael** [comment]
Done, however, it still freezes at the initial loading screen. Any way for me to get a log if HDT never boots up?

**Comment by Epix37** [comment]
Mean do you mean by freezing exactly? "HearthstoneDeckTracker.exe has stopped working"?

You can check if there is a log in "%AppData/HearthstoneDeckTracker/Logs", but I don't think there will be.

**Comment by Morthcongael** [comment]
There is no log, it simply stops responding and never starts up regardless of how long I leave it. :l

**Comment by Epix37** [comment]
* Make sure there is no HearthstoneDeckTracker process already running
* I assume you don't have any decks saved? Try deleting the content of "%AppData%/HearthstoneDeckTracker"

**Comment by Morthcongael** [comment]
No success, freezes after login still.

**Comment by Epix37** [comment]
Maybe there are some files missing? Try downloading and extracting the latest version again: https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.11.3

**Comment by Morthcongael** [comment]
I tried redownloading, reintalling, and even going back and downloading v0.11.0 , all to no sucess. :(

**Comment by mike0180** [comment]
Chances are slim you did the same thing as me, but I Extracted the file directly to my desktop and dragged and dropped the deck tracker icon to my desktop, but it wouldn't load with the icon out of the extracted file.

**Comment by Epix37** [comment]
Please do as instructed here: https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1365#issuecomment-138739947 and post the information found under "General".

(Source might be listed as ".NET Runetime")
