### ISSUE TITLE
HDT crashed when opening Collection tracker plugin

### ISSUE THREAD

**Issue by chfalcao** [Epix37/Hearthstone-Deck-Tracker#1479]
How to reproduce: Open HDT, click on Plugins > Collection tracker
* Independent of whether Hearthstone is running.
* Windows 10 machine

[Crash report](http://chopapp.com/#gtqkk46i)

**Comment by Epix37** [comment]
You are probably using an out of date version of the plugin.
Try downloading the latest one here: https://github.com/ko-vasilev/Hearthstone-Collection-Tracker/releases
