### ISSUE TITLE
collection not imported

### ISSUE THREAD

**Issue by oursgris** [Epix37/Hearthstone-Deck-Tracker#1480]
I can't import the collection and neither the decks
(note I tryied to move the log.config file, I changed the language of the tracker to french)
if I created the deck by hand it works ..

but how can I import all my collection + all my decks

**Comment by Epix37** [comment]
Neither the collection nor decks are or can be automatically imported.

Importing the collection can be done with the collection manager plugin: https://github.com/ko-vasilev/Hearthstone-Collection-Tracker

Decks can be imported via the IMPORT menu item.
