### ISSUE TITLE
Arena record not accurate.

### ISSUE THREAD

**Issue by Tulock** [Epix37/Hearthstone-Deck-Tracker#1481]
Just finished an arena run, and there are two wins missing (see how I avoid the topic of my final win total there ;)).  

Is there any way to manually add those so my statistics will be accurate (even though this will make them take a hit ;))

Cheers.

**Comment by Epix37** [comment]
Games not recorded is maybe related to #1478?
For adding games manually, see here: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#add-game

**Comment by veri745** [comment]
I played 5 games with a paladin deck, against
 * Druid - loss
 * Warlock - win
 * Mage - win
 * Warlock - win
 * Priest - win
 * Paladin - win

The game vs the priest was not tracked

Requested files:
 * HDT log: http://pastebin.com/GkBcx8i5
 * Bob log: http://pastebin.com/dFB2jHt7
 * Power log: too large for pastebin

**Comment by veri745** [comment]
PS: It doesn't look like it had anything to do with the other player not showing up in last played, maybe that was just a coincidence
