### ISSUE TITLE
Deck window background

### ISSUE THREAD

**Issue by AGL2326** [Epix37/Hearthstone-Deck-Tracker#1482]
This is more of a question than an issue. Previously when i used HDT, the deck window background was transparent and now after a while i wanted to use it again and i noticed that it's not transparent anymore. Is there a color code for transparency? or is there a plug in for that maybe? or is it a bug on my end? 

Thank you in advance

**Comment by Epix37** [comment]
The deck window background never was transparent. You can set a color and chromakey that with video recording software but that's about it.

There is no plugin like that as far as I'm aware.

**Comment by AGL2326** [comment]
I guess i remember it incorrectly then. Probably saw a video of somebody using it or something.
Thank you anyway
