### ISSUE TITLE
Importing decks from hearthstonetopdeck no longer seems to work

### ISSUE THREAD

**Issue by thufirh** [Epix37/Hearthstone-Deck-Tracker#1484]
I may have missed it, but I didn't see this issue posted already. HDT is saying it is unable to load decks from hearthstonetopdecks.com, but I know this site is in the sites listed by HDT.

**Comment by Epix37** [comment]
Websites keep changing their layouts etc :/.
I recommend using [NetDeck](https://chrome.google.com/webstore/detail/netdeck/lpdbiakcpmcppnpchohihcbdnojlgeel).

**Comment by thufirh** [comment]
Thanks.
