### ISSUE TITLE
"Restart Hearthstone" problem

### ISSUE THREAD

**Issue by Arkham80** [Epix37/Hearthstone-Deck-Tracker#1487]
I have this problem constantly after latest update. Restart and reinstall of Hearthstone don't help.

![image](https://cloud.githubusercontent.com/assets/11933568/9904750/e9dc42a8-5c88-11e5-91b0-109016458e0a.png)

**Comment by Epix37** [comment]
Close HDT, go to `%LocalAppData%/Blizzard/Hearthstone` (Win+R, paste), open the `log.config` file delete the content and paste this: http://pastebin.com/Y1UR7sqr

**Comment by Arkham80** [comment]
Thanks
