### ISSUE TITLE
Question: cards 'kept' on mulligan

### ISSUE THREAD

**Issue by Paula94** [Epix37/Hearthstone-Deck-Tracker#1488]
Hi, HS Deck tracker is a great thing.

Question: Is there a way to tell the difference between cards 'kept' after a mulligan (if they are all kept), and cards where no mulligan has been performed yet?

- My cards are no longer marked with a 'k' to alert me of 'kept' cards. Only the 'm' mulligan marker, if a mulligan has been performed.

- To me, a hand of all 'kept' cards, and a hand where the mulligan has not yet been performed looks identical.

- I queue and then tab out to a browser. Hence when I return I assume the my opponent has kept all of his excellent hand. Therefore I make my choices accordingly, only to find he has not yet mulliganed.

Is there a preference setting to return the functionality of the 'k' card marker?

Many thanks in advanced,
Rgds Paula

**Comment by Epix37** [comment]
Hey,

The 'K' marks were always shown before the mulligan was performed (I think... at least that was the way it was inteded), so you should not have been to tell if no card were mulliganed anyway.

It's technically possible but Blizzard did intentionally or unintentionally choose not to have the gameclient display that information, that's why HDT won't either.

**Comment by Paula94** [comment]
Thanks for your prompt reply.

I understand what you are saying, but for your reference, after the opponent mulliganed his hand used to be marked with k's and m's, rather than just m's. This made it possible to tell if a mulligan had been performed in the case of m = 0. 

It is a shame that k card markers have been removed from deck tracker, as this information was useful as stated above.

Anyway thanks for your help. I will be donating to deck tracker.
Paula

**Comment by Epix37** [comment]
I know what you mean, but my point was that all the 'K's where there before the mulligan as well.

Before mulligan: "K, K, K"
After mulligan: "K, K, K" if no cards mulliganed.

So whether the 'K's are there or not makes no difference.

Maybe I'm wrong and that's not the way it was but I remember saying no to this request before so it must have been like that at some point at least :).
