### ISSUE TITLE
Heroes are shown as Hunter in Game Overview

### ISSUE THREAD

**Issue by riQQ** [Epix37/Hearthstone-Deck-Tracker#1489]
Replay name and replay are correct, but the game overview is wrong.
HDT Log: http://pastebin.com/RFK6ed1t
Replay: http://www77.zippyshare.com/v/tvYL9QRm/file.html
![hdt error](https://cloud.githubusercontent.com/assets/3404787/9913001/c3cfd3fa-5caa-11e5-8d57-e6e0f84434ff.png)

**Comment by culinko** [comment]
My guess is that it's related to Webspinner (Hunter minion).

**Comment by andburn** [comment]
This happens with the unstable portals brawl too (#1190), so we can still test it now that they've changed it from webspinners.

I've been trying to figure it out, without success. The `GameStats` object always seems to be correct, something must be happening in the loading/saving of the stats to file or the stats page?

It can vary wildly: 
- not saving the game at all,
- saving it but with both players as Mage,
- even saving the game correctly with the right heros, but its displayed on the stats page as Mage vs Mage (something to do with `VerifiedHeros` not sure how that works).

**Comment by Epix37** [comment]
IIRC `VerifiedHeroes` checks the player hero based on cards played. (way outdated)

I'm not really sure how much work I want to put into fixing brawl related things :S.

**Comment by andburn** [comment]
Yeah, it wouldn't be worth the effort to get all the brawl stuff working. I'll have another look at the hero thing, see if I can fix that at least.
