### ISSUE TITLE
Tavern brawl recorded for arena deck

### ISSUE THREAD

**Issue by HugoKornelis** [Epix37/Hearthstone-Deck-Tracker#1490]
I am guessing that this is probably an incorrect settings error, but I checked all the menus and did not find an option that appears tro be related.

When I started a tavern brawl today, HDT popped up with one of my old arena decks. The cards did not match, of course, but I did not get any error message from HDT during the game. And when the game ended, I was not asked what I wanted to do with the deck, as I recall happening before when a deck didn't match.
I then checked the games & statistics for that arena deck, and the tavern brawl game was indeed recorded for that deck. (I deleted it).

I checked the HDT options. Both "Automatically USE decks" and "Autoselect if only one possible" are NOT checked. Both "Discard game if deck does not match cards" and "Ask before discarding" ARE checked.
What have I done wrong?

**Comment by GaryKing** [comment]
HDT seems to be having problems with the current Tavern Brawl, which is the Unstable Portal one (at least for me). 

A few issues I noticed:

- HDT didn't prompt that the currently selected deck does not match the in-game mulligan cards. (3 Unstable Portals.)
- The opponent's deck list was messed up a bit. For instance, some of the cards were duplicated, one of each which was greyed out. And sometimes, Abilities would count as a card, such as Shattered Sun Cleric's ability.
- The wrong class was shown in the Replay Viewer for each Tavern Brawl game. I believe it showed Mage for both Mine and Opponent's class, even though both were wrong.

**Comment by andburn** [comment]
@GaryKing definitely problems with *Webspinner* and *Unstable Portal* brawls (#1489)

**Comment by Epix37** [comment]
This should be fixed with v0.14
