### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by roshavagarga** [Epix37/Hearthstone-Deck-Tracker#1491]
Here is a link to the crash info - http://pastebin.com/PTHd2fpB

A bit before the crash I stopped getting the timers for turns too. They have not returned yet.

**Comment by roshavagarga** [comment]
Opponents' cards during current tavern brawl seem weird too, Is that how they're supposed to look? http://puu.sh/keevr/81f5ca4945.jpg

**Comment by Epix37** [comment]
Same as #1444 - No idea what that is :/.

This weeks brawl seems kinda wonky anyway though.

**Comment by roshavagarga** [comment]
@Epix37 Forgot to mention, I got the crash when I won the match. I was getting the reward for a quest and then it crashed. Not sure if related or not.

**Comment by roshavagarga** [comment]
@Epix37 Is there any way I can check why timers have stopped working for me completely? Thank you.

**Comment by Epix37** [comment]
Should be fixed.
