### ISSUE TITLE
Tavern brawl hero recorded as mage

### ISSUE THREAD

**Issue by GiggliG** [Epix37/Hearthstone-Deck-Tracker#1492]
I reported this before, but cant find the thread.

When playing tavern brawl, and the week is a pre-made deck like this weeks unstable portal, the games are recorded as if Mage. Both for you and your opponent. 

This messes up stat summaries for the classes.

If there's no way to detect actual class used in these brawls, it would be better to record them as a 10th class (Preset Brawl), or No Class.

**Comment by andburn** [comment]
Some discussion about this at #1489.
The actual games seem to be being recorded correctly, something is happening when they are saved to file and/or loaded to the stats screen.
