### ISSUE TITLE
Feature request: a secret panel when WE play a secret too, to gray out the ones our opponent is not playing around anymore

### ISSUE THREAD

**Issue by izmimario** [Epix37/Hearthstone-Deck-Tracker#1497]
since i’m planning to craft and play a secret paladin soon, i think it would be an invaluable tool to be able to have a a secret panel also when a secret is played by YOU, not the opponent, maybe in the low right corner.
that way, when the opponent checks via experiments what your secret is, you can gray out the ones he has mentally discarded.

please please tell me something can be done about it.

**Comment by Epix37** [comment]
Same as #313.
