### ISSUE TITLE
After update Tracker do not show decks.

### ISSUE THREAD

**Issue by Bloomer24** [Epix37/Hearthstone-Deck-Tracker#1498]
It run normal, let me choose deck I use.
But do not show them.

**Comment by Epix37** [comment]
Maybe some filter was set for some reason?
See here https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#decks-i-create-are-not-showing-up-or-disappear-when-i-apply-a-tag

**Comment by Bloomer24** [comment]
No, no filters at all. It is not problem on tracker screen.
Decks are not show when playing. I see list of them on program screen, I can edit them, use/active them but I do not see list of them while playing.
Tracker worked well till update. After I update it decks

**Comment by Epix37** [comment]
Is there no overlay at all or are the decks just not updating?
Make sure `options > overlay > general > hide (completely)` is not checked.

**Comment by Epix37** [comment]
Also try enabling `options > tracker > settings > advanced window search`.

**Comment by Bloomer24** [comment]
no overlay at all. So I cannot say is it tracking or not :P
hide (completly) is not checked
adv window search is active from beginning I think

**Comment by Bloomer24** [comment]
... :p
ok, I checked/unchecked hide completly, done a lot of other checks/unchecks restarted program by in-menu command. And it worked :P
I don`t know what was wrong tho but now itworks ^^

**Comment by Bloomer24** [comment]
And after switching it off/on it do not work again.
