### ISSUE TITLE
HDT is tracking enchantments as cards for the opponent

### ISSUE THREAD

**Issue by NightKev** [Epix37/Hearthstone-Deck-Tracker#1500]
Also some cards are being copied grayed out even though no joust or other card revealing effects occurred. Unsure if it's part of the same bug or not.
![hdt bug 1](https://cloud.githubusercontent.com/assets/849285/9979393/2bd97e3a-5f1f-11e5-87d6-778d252d4f18.png)
![hdt bug 2](https://cloud.githubusercontent.com/assets/849285/9979394/2bf966aa-5f1f-11e5-86af-c1de29f737dd.png)

**Comment by NightKev** [comment]
This time it showed the heroes and their hero powers in the opponent's decklist (both of each) when I was spectating someone.
![hdt pls](https://cloud.githubusercontent.com/assets/849285/11432146/8dbcdc4c-945c-11e5-8d92-e14db6abae44.png)

**Comment by Epix37** [comment]
Yea.. I have seen that (very rarely) too, no idea why it happens though. Restarting seems to fix it usually.
