### ISSUE TITLE
Question about HDTReplay Accuracy and Assumptions

### ISSUE THREAD

**Issue by SpectralCoding** [Epix37/Hearthstone-Deck-Tracker#1502]
First, as a C# developer, this is some of the cleanest OSS code I've seen in a while. Good job to the team for making an awesome application, making it OSS, and keeping it clean!

I'm writing an application that parses the HDTReplay files to extract some statistics about the different cards. My understanding of the format of the replay.json file is that each top level object represents a player action, and the contents of the object represent all known entities (cards, heroes, etc) and their current status via the Tag attributes.

My questions to the developers:
1. What is your confidence in the accuracy of the replay? I'm not looking for 100% perfect, but your feel for "a lot of work needs to be done" vs "we're pretty good but not perfect".
2. Does the file contain all the data necessary to determine X entity did Y damage/healing to Z entity? I notice in your replay viewer you have arrows, but not actual damage numbers. How about more complex stuff like Stormwind Champion (all friendly minions +1/+1), are those effects included or does the parsing app have to figure that out?
3. If I'm trying to track game events (X did Y damage to Z) is the solution parsing replays, a HDT Plugin, or something else?

Thank you for your time.

**Comment by Epix37** [comment]
1. Depends on what exactly you mean by accuracy. There are no missing actions for anything that's suppossed to be recorded (draws, attacks, ...) .
2. There are probably a few things missing, from the top of my head: spell/trigger targets is one of them. Buffs should be included but are sometimes not updated until on the next action.
3. I would say parsing replays would be the easiest way to go about that.

That said, **replays will be changed soon**. I'm working together with some of the [HearthSim](http://hearthsim.info/) guys on a new replay format, which will basically be a xml represenation of the Power.log. See [here](https://github.com/HearthSim/powerlog/wiki)) for more detail.

Not only that, but I'm also in the process writing a C# library that will be
* a C# implementation of the project linked above (parse log -> xml and vice versa)
* able to parse the xml into "usable data", similar to the current json format, just better. The idea is that you will be able to do things like
    * `var gameState1 = replay.GetTurnStart(5);`
    * `var gameState2 = replay.GetNextAction(ActionType.Attack);`  
* hopefully able to parse hdtreplay to the new format


The lib is not available anywhere yet but will be open source as soon as I get it to a somewhat usable state (the coming week?). In case your application is also .NET, this should make some of your work a lot easier. I'd also welcome any collaboration :).

**Comment by SpectralCoding** [comment]
My plan is to be able to allow players to upload their replay files (in bulk or otherwise) and contribute to a community maintained statistic database with stats to allow a more scientific look at how effective certain cards are. For example:

Over 3732 Games:
1. Card X did an average of 13.2 damage and received an average of 6.3 damage..
2. Card Y stayed in hand an average of 5 turns before being played
3. Card Z lasted on the board an average of 2.6 turns.
... etc ...

I don't want to take too much of your time, but **do you feel the xml Power.log implementation from HearthSim is far enough along (or stable enough) to begin developing against**? IE, I can use the above tool to generate my own xml from my Power.log, and then once HDT begins saving replays in that form it will be easier for users to contribute. I assume the goal is for HDT to export in a compatible format or is even a direct C# port.

Is this something you feel would be valuable to include in HDT either as a plugin or as part of the core (similar to contributing to Hearthstats)? Maybe time will have to tell how successful my project is before "dirty-ing" your codebase.

**Comment by Epix37** [comment]
I'm fairly sure the xml replay implementation is definitely usable already. You should come join the #Hearthsim IRC channel on the Freenode network, jleclanche will be able to tell you exactly if there's anything not working yet. (You can also find me there usually - or alternatively on [gitter](https://gitter.im/Epix37/Hearthstone-Deck-Tracker))

The lib, which HDT will use, is a direct port of the python implementation at it's core, plus features to actually process those replays. 

A plugin might be the way to go, we'll see :).

**Comment by kgpasta** [comment]
Saw this conversation and was happy to see someone else also thinking the same thing. I've started developing something for my own purposes that's similar to what @SpectralCoding is suggesting, a plugin for HDT that calculates different metrics based on replays of games. Examples of metrics I've been thinking about are: win rate when specific card is played, how well it trades (2 for 1), (3 for 1), or card advantage (either draw or put something into play).

If either of you are interested in collaborating or working on this together let me know. Right now I've just been using it myself since it runs quite slowly (Goes through each KeyPoint of each Replay extracting statistics), but I want to release it open source eventually as well.
