### ISSUE TITLE
How to use hearthstone in multiple computers using dropbox?

### ISSUE THREAD

**Issue by dcsnunes** [Epix37/Hearthstone-Deck-Tracker#1507]
I would like to ask how to use hearthstone deck tracker with dropbox.
Where I put the files that tracks my data/games/decks and how do I configure the software to put theses files inside the dropbox folder that will be synchronized.
Thanks.

**Comment by andburn** [comment]
Ok so I haven't tried this, but I see no reason why it wouldn't work.

1. Create a folder in your dropbox directory for your tracker data.
- Go to `Options > Tracker > Settings` and press *Set Data Path*, then select the folder you just created.
- Now **un-check** the *Save data in AppData* options.

Your data should now be in the dropbox folder

**Comment by quark-zju** [comment]
It seems Set Data Path feature does not work as expected. I ended up creating a directory junction.
