### ISSUE TITLE
In spectator mode, card marks cannot reflect the turn number

### ISSUE THREAD

**Issue by chisquare130** [Epix37/Hearthstone-Deck-Tracker#1513]
The mark on every card is the turn in which the watcher enters the spectator mode, instead of the turn the card comes to the opponent's hand.

**Comment by Epix37** [comment]
Is this only the case for the cards that were already in the hand at the point of entering spectator or also cards drawn from that point onward?

The former is just the way the logs work, not fixable. The latter would be a bug.

**Comment by chisquare130** [comment]
The cards that were drawn later also show the wrong number.

**Comment by Epix37** [comment]
Should be fixed.
