### ISSUE TITLE
Card counter opponent 

### ISSUE THREAD

**Issue by thebnetplayer** [Epix37/Hearthstone-Deck-Tracker#1515]
How do I activate the feature that tells me what turn my opponent drew their cards, which overlays the top of each card. Right now, nothing is showing up at all

**Comment by thebnetplayer** [comment]
When i click "unlock" under general settings for the overlay, nothing happens. Am i missing a file or something?

**Comment by Epix37** [comment]
Do you see the overlay at all?
Same issue as #1498?

**Comment by thebnetplayer** [comment]
Not sure if that's entirely the same issue,  but I figured it out after an
hour or longer haha. Went into settings and adjusted the opacity settings

**Comment by Epix37** [comment]
Good :).
