### ISSUE TITLE
Hero class icon tooltip

### ISSUE THREAD

**Issue by tac21** [Epix37/Hearthstone-Deck-Tracker#1516]
I should really know them by now but it would be helpful if the little hero class icons had a popup tooltip description, e.g. in the stats screen.

**Comment by Cu8eR** [comment]
Is it really needed? Hero power is shown in HS, in HDT there is no need to know it, or is it?

**Comment by Epix37** [comment]
It has been added to the new arena stats (and will be added to the rest of the new stats). No harm in it.
