### ISSUE TITLE
hearthstone-deck-tracer crashing on startup

### ISSUE THREAD

**Issue by tarrix** [Epix37/Hearthstone-Deck-Tracker#1517]
Hey, i downloaded the newest version of HSDT from your website (v0.11.3) But unfortunatly i get he same error a lot of people have been getting: HSDT stopped working. I have looked around on every single forum google found but nothing has worked.
1. NET framework
2. install old versions
3. deleting files in %AppData%/HearthstoneDeckTracker (I only have a folder called logs adn a file called config)
4. deleting the output_log file from C:...hs_data

aaand yea cant remember them all. well i spend 3 hours now figuring it out.. nottihng worked so far. Please tell me what to do.. :/

My pc is on danish, and therefore my crash report is aswell, but basicly it says "part of the path/source was not found"
########## 9/25/2015 1:23:09 PM ##########
System.Windows.Markup.XamlParseException: Der blev udløst en undtagelse ved angivelse af en værdi på 'System.Windows.Baml2006.TypeConverterMarkupExtension'. ---> System.IO.DirectoryNotFoundException: En del af stien 'C:\Users\Gabriel\Desktop\Hearthstone.Deck.Tracker-v0.11.3\Images\HearthstoneDeckTracker.ico' blev ikke fundet.
   ved System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

please help me xD

**Comment by Epix37** [comment]
Try manually creating all the folders you see in the zip and drop the corresponding files in them.

**Comment by tarrix** [comment]
Alright i fixed it! was just about to write a comment on here. I tried installing a free zip file opener instead of using windows 8.1's Zopener as they call it, and this time there was no issue at all opening the app! Well windwos' app system su**s, what can i say hehe
Thank you a lot for the app, i have already tested one game with it :)

**Comment by Epix37** [comment]
Great :).
