### ISSUE TITLE
HDT - "Windows Has Encountered A Problem" (Possible Fix)

### ISSUE THREAD

**Issue by VersaceJ** [Epix37/Hearthstone-Deck-Tracker#1525]
Hi all,

I felt compelled to create an account on here after having had real trouble over the last couple of days with installing the HDT. After scouring the web and attempting several different solutions to fix this problem I was at a loss. Other people have fixed this problem by updating .NET frameworks, deleting Hearthstone text documents, creating external folders that corresponded with the original folders within the Zip or using external Zip File openers etc., all of which I've had no luck with. 

In the hope that anyone else struggling with the same problem in future doesn't have spend as long as I did to do something so simple this is what I did:

1. Open My Documents and locate the HDT Zip File.
2. Right click the Zip File and click '7-Zip' and then select 'Extract Files'
3. Open the extracted folder and run HDT

Even if this helps one other person then this post will have been worth it!

**Comment by Epix37** [comment]
That would have been pretty much my standard approach for unzipping it. What did you do instead?

**Comment by VersaceJ** [comment]
I'll be honest with you I'm not the most computer literate so I was opening the zip file and and trying to run it from in there, which was where I kept encountering the "Windows has encountered a problem". It turned out the solution was actually really simple but I'd been triying all these complexed methods mentioned above! I just posted in here in the hope I might help someone else lol

**Comment by Epix37** [comment]
Ah I see, thanks. I should probably add a proper installer for HDT. ...Maybe some day :).

**Comment by VersaceJ** [comment]
Haha, only for people as incompetent as me! :smile:
