### ISSUE TITLE
System.NotSupportedException Crash

### ISSUE THREAD

**Issue by Zedseayou** [Epix37/Hearthstone-Deck-Tracker#1529]
Since the most recent update HDT has been crashing on me pretty randomly. I haven't been able to identify why it crashes - sometimes it happens on startup, other times I get a few games in and then it crashes. I have a whole host of crash logs that I don't know how to parse but these are the lines at the start of them:

`System.NotSupportedException: No imaging component suitable to complete this operation was found. ---> System.Runtime.InteropServices.COMException: The component cannot be found. (Exception from HRESULT: 0x88982F50)`

Any advice? I'm having issues attaching the crash log files, it says it can't process them?

Here is the whole text of the most recent one: http://pastebin.com/TzuZV7S2

**Comment by Epix37** [comment]
Try downloading the latest release again here https://github.com/Epix37/Hearthstone-Deck-Tracker/releases and see if that's  helps.

(Also, your collection tracker plugin needs updating :))

**Comment by culinko** [comment]
Are you still experiencing those crashes?

**Comment by Zedseayou** [comment]
Nope - I think was the collection tracker plugin? At least I updated that and no similar crashes since!
