### ISSUE TITLE
Crash upon game ending

### ISSUE THREAD

**Issue by Zelniq** [Epix37/Hearthstone-Deck-Tracker#1531]
This crash happens quite often (since the last update Release v0.11.3), always right as the game ends. 
The only thing I can think of that sets me apart from other users is that I often play HS in a small window size

github wouldn't let me attach the Crash report, so:

```
########## 9/30/2015 9:47:42 AM ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hearthstone_Deck_Tracker.GameEventHandler.<HandleGameEnd>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by riQQ** [comment]
Has to be in these lines if I'm not mistaken. `_game.CurrentGameStats.GameEnd();` produces a log message.
https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/dbc346e4deb84d46769c0f8f91ea55df82194acc/Hearthstone%20Deck%20Tracker/GameEventHandler.cs#L281-L300

Maybe `player` or `opponent` is null.

**Comment by Zelniq** [comment]
Well it seems to have gone away, no crashes after many games. The only thing I changed was unchecking Auto Upload New Games under the Hearthstats menu.

**Comment by GaryKing** [comment]
The game crashes for me every time I play the new Tavern Brawl released today. It uses two unique heroes, so I'm guessing that could be the problem.

**Comment by Epix37** [comment]
Hm I'm actually not so sure what this one is after all. 

`HandleWin/Loss` (which produces the "--game was won--" message) is called before `HandleGameEnd` - and there is no win/loss message either.

**Comment by riQQ** [comment]
It may not be enough to look at the `Power.log` to find this problem?

**Comment by Epix37** [comment]
Uuuuhg... I just realized markdown changes `Hearthstone_Deck_Tracker.GameEventHandler.<HandleGameEnd>d__1.MoveNext()` to "Hearthstone_Deck_Tracker.GameEventHandler.<HandleGameEnd>d__1.MoveNext()". 

So riQQ you were probably right and opponent is null in this case, most likely because of the `UNKNOWN HUMAN PLAYER` issue.
