### ISSUE TITLE
Autoselect feature does not work since TGT

### ISSUE THREAD

**Issue by Zesaric** [Epix37/Hearthstone-Deck-Tracker#1533]
Regardless of setting, the autoselect feature seems to have stopped working. I have only one active deck per class and both relevant options ("Automatically use decks" & "Autoselect deck") enabled - but still I have to manually select the deck for every match!

In previous releases, the autoselect feature has worked fine for me, but since TGT it seems to be broken (at least on my machine).

Any ideas how to fix this?

**Comment by Epix37** [comment]
Make sure you have a (any) deck set as active. Autoselection does not work in "no deck"-mode.

If that's not the solution, please reproduce the problem and [post the log](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues) afterwards.

**Comment by Zesaric** [comment]
Thanks for your swift reply. I always have some deck set as active, so that is not the problem. However, in the meantime I was able to locate and solve the problem:

 

It seemed that my data folder did not contain a PlayerDecks.xml but only a file named "PlayerDecks.xml130882752104632083". When I renamed it to "PlayerDecks.xml" and started HDT, the file would automatically be renamed to "PlayerDecks.xml13088..." again.

 

I then deleted and newly created both my HDT program and data folder, and copied my games, decks and settings from a backup to the newly created data folder. Since then, the deck auto-select is operational again.

 

Means right now the only thing that apparently does not work is the "3  Wins to 10 Gold" tracker - but if I remember correctly you have labelled this as a known bug since TGT.

 

Anyway, thanks for your help!

 

 

Von: Epix [mailto:notifications@github.com] 
Gesendet: Donnerstag, 1. Oktober 2015 10:55
An: Epix37/Hearthstone-Deck-Tracker <Hearthstone-Deck-Tracker@noreply.github.com>
Cc: Zesaric <zesaric@hotmail.com>
Betreff: Re: [Hearthstone-Deck-Tracker] Autoselect feature does not work since TGT (#1533)

 

Make sure you have a (any) deck set as active. Autoselection does not work in "no deck"-mode.

If that's not the solution, please reproduce the problem and post the log <https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues>  afterwards.

**Comment by Epix37** [comment]
That's good to hear.

Well... Blizzard broke the gold tracking with TGT, then it was fixed for the broken logging and now Blizzard fixed it so it's broken again... :D

It's on the todo list for v0.11.5

**Comment by Zesaric** [comment]
Yeah, I can imagine that it's quite a task with game developers changing their file and data structures over and over... ;-)

Which BTW is one of the reason why I have utmost respect for guys like you who create excellent tools for the benefit of the community! So thanks a million and keep it up! :)

**Comment by Cu8eR** [comment]
@Epix37 - I cannot confirm this... at least not with latest version

**Comment by Epix37** [comment]
@Cu8eR please read the posts.

> I then deleted and newly created both my HDT program and data folder, and copied my games, decks and settings from a backup to the newly created data folder. Since then, the deck auto-select is operational again.
