### ISSUE TITLE
Cards discarded by opponent by Doomguard aren't indicated as such

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#1534]
If the opponent plays Doomguard and discards two cards, then HDT just marks the cards as played (i.e. the regular way of marking cards, with no markings at all).

Is it possible to mark the cards as discarded, or at least "burned", like with the red color?

**Comment by Epix37** [comment]
options > overlay > opponent > highlight discarded from deck
despite the name, this also includes hand discards.

**Comment by GaryKing** [comment]
I've already got that enabled but it still didn't highlight the cards.
