### ISSUE TITLE
Crash at game ending

### ISSUE THREAD

**Issue by MaxiKing66** [Epix37/Hearthstone-Deck-Tracker#1535]
I completed a game in the Tavern Brawl with Boom bot and Annoyotron, I was the Boom Bot. At the ending of the game right after the enemy hero exploded the "Oops! Something went wrong." Window showed up.

Guessing the Heroes or the hero Powers aren't in the Decktracker yet?!

I was not able to upload the file "Something went really wrong, and we can’t process that file. Try again" was shown down below.

http://www.file-upload.net/download-10944619/Crash-report-3092015-2321.txt.html

**Comment by andrei-angelov** [comment]
HDT crashes in Tavern Brawl right before game ends.
http://pastebin.com/3rH0yz1t
http://pastebin.com/K3ug2vwu
