### ISSUE TITLE
when the enemy player has 1 card left in the deck, the probability of drawing 2 of the same cards is 200%?

### ISSUE THREAD

**Issue by axpu** [Epix37/Hearthstone-Deck-Tracker#1537]
![image](https://cloud.githubusercontent.com/assets/14918369/10212404/ab3535b0-67cc-11e5-8794-b6796a51036f.png)

**Comment by Jup200** [comment]
![hdt_200bug_c](https://cloud.githubusercontent.com/assets/10400665/10521213/d9c99198-736e-11e5-8493-df76d30c5c4c.jpg)
...it's also in your deck when is 1 card left in deck ...200% is wrong value ...probability cant go over 100%

**Comment by Cu8eR** [comment]
I can confirm this @Epix37
