### ISSUE TITLE
Cards marked as "presents" incorrectly

### ISSUE THREAD

**Issue by 305jeff** [Epix37/Hearthstone-Deck-Tracker#1540]
I'm going to look at this more closely going forward, but I've noticed a few times. I just played against a druid who probably drew his Keeper of the Grove from Ancient of Lore or or Wild Growth/Excess Mana and it marked it as a "Present" in their deck list, as if they had gotten it from an unstable portal or something.

This isn't intended, is it?

Thanks!

**Comment by riQQ** [comment]
I don't think it's intended to be this way.

**Comment by Epix37** [comment]
I think this is fixed.
