### ISSUE TITLE
Crash and 'void system'

### ISSUE THREAD

**Issue by chrischiaa** [Epix37/Hearthstone-Deck-Tracker#1542]
I can't log in to my hearthstone deck tracker account, password and email is correct. Even if i use guest account it just crashes when i press import deck from arena. Please check it out and help me because i do not know what to do. Thanks.

http://pastebin.com/Z8e7CJnH

**Comment by Epix37** [comment]
Try uninstalling and reinstalling .NET Framework 4.5 and/or installing any new windows update.

**Comment by chrischiaa** [comment]
Done and solved bro, thanks man.
