### ISSUE TITLE
A couple of issues (enemy cards played + enemy hand)

### ISSUE THREAD

**Issue by hyderhussain** [Epix37/Hearthstone-Deck-Tracker#1543]
Hi, I've noticed a couple of bugs the past few days.

1) When the enemy casts spells as their first few cards it sometimes doesn't show up in their list of cards played.

2) Sometimes, not sure what triggers it, the opponent's hand is all turn 0's the entire match. 

EDIT: 

3) The clock is currently counting on my turn during his turn. The time is 0:05 to 7:30 right now.

**Comment by iBestr** [comment]
have the same issue.. opponent's hand is all turn 0 and logs are showing that turn is 0 always.

**Comment by Epix37** [comment]
Should all be fixed.
