### ISSUE TITLE
No longer recoding games and Time for game is wrong

### ISSUE THREAD

**Issue by DaveBergeron** [Epix37/Hearthstone-Deck-Tracker#1549]
I seem to have a problem, I noticed HDT not recording my games and overlay seemed to be frozen from the last paladin game. I see the secrets still on the top left. I restarted HDT and restarted my computer. Didn't fix the problem. I actually had the same problem before with an older version and I just installed an older version which worked and then updated to the latest version when it came out and it was working until today.  Anyone else with the problem and anyone know how to fix? I guess I'll install older version for now.

**Comment by DaveBergeron** [comment]
Here's a screetshot: https://lh3.googleusercontent.com/-vvGcimV7pvU/Vg4oiCVvYaI/AAAAAAAAZDo/DF91qy_NjQI/w815-h685-no/capture_001_02102015_024115.jpg

**Comment by Epix37** [comment]
Same as #1553
