### ISSUE TITLE
Deck/Match sync problem

### ISSUE THREAD

**Issue by Palaryel** [Epix37/Hearthstone-Deck-Tracker#1550]
I've noticed a problem (since yesterday) with syncing decks and matches to heartstats. Even if I select force sync, it shows that 1 new deck (instead of 13) is being uploaded and that 13 games are getting uploaded, however, manually checking on hearthstats shows that no decks or games are present (I manually wiped all decks and games that I previously had on hearthstats).

Trying to solve the issue I exported all my decks to XML files, redownloaded the latest stable version, deleted the HDT directory from /appdata/roaming, started HDT and imported each deck manually from files and played a couple of games. After that I choose force sync again, no matches or decks were uploaded to hearthstats again.

The problem persists on 2 PC's (I'm using a separate HDT installation on each PC, the userdata was copied from one to the other).

NOTE: I tried the latest pre release as well, the same issues apply
 NOTE 2: I'd be willing to supply my whole data directory if needed to replicate the issue and find a solution

Latest logs (via Pastebin):
http://pastebin.com/iFMRVXGQ
http://pastebin.com/xgaUN3Ch
http://pastebin.com/f20wRdUd
http://pastebin.com/k3rmBUhY
http://pastebin.com/63BGjsS6

**Comment by Epix37** [comment]
If you manually deleted decks on HearthStats, HDT will try to upload matches using the stored deck id. To "reset" the ids select all your (ctrl-a) and run `HEARTHSTATS > DELETE SELECTED DECKS`. Try syncing again after that.
(Depending on what you mean by "imported each deck manually from files" this might not apply)

What has me a little confused is that you are getting 400 and 404 error codes. Either those are some temporary server issues (I just tired it but had no issues), or maybe something changed with your firewall/proxy configuration?

**Comment by Palaryel** [comment]
I used the "export->save to XML" feature on HDT to save a XML file of each of my decks, then deleted all HDT files from the PC to start with a fresh installation and then used "import->from file" feature to import the XML files one by one (to get my decks back into HDT.

Ill retry the whole procedure again now and upload new log files if the problem persists.
