### ISSUE TITLE
HDT doesn't count gold

### ISSUE THREAD

**Issue by qtrino** [Epix37/Hearthstone-Deck-Tracker#1554]
Hello,
Since the last update, hdt stopped counting gold and it still shows the last status (wins 2/3, 30/100).
Here's a log: http://pastebin.com/cYetJ456

**Comment by qtrino** [comment]
I forgot, it happened on the 0.11.3 so I downloaded the 0.11.4 version but it didn't help

**Comment by Epix37** [comment]
Planned for v0.11.5. 

Blizzard broke it again by fixing it :S.
