### ISSUE TITLE
Can't export saved deck from Deck Tracker to Hearthstone.

### ISSUE THREAD

**Issue by Vaizen** [Epix37/Hearthstone-Deck-Tracker#1555]
So I tried to use the export feature (I already used it a lot before it broke) but it doesn't select any cards nor does it add anything.

Possible cause: I accidentally moved the mouse when it still worked, which broke hearthstone tracker.?
Tried solutions : Uninstalled Deck Tracker and
                          Reinstalled it. = Doesn't fix the issue.
                          Rebooted = Doesn't fix the the issue.
                          Deleted config = Doesn#t fix the issue either.

Exact description of the issue:  Click on export button.
                                                 UI dissapears (how it usually does) to add the cards
                                                 Hearthstone doesn't select anything
                                                 Deck Tracker displays missing cards and shows that it added all the 
                                                 cards even though it didn't .
                                                 Nothing happends.

                                                 

So is there anything else I can do ?

**Comment by Epix37** [comment]
Try these:
* switch hearthstone to fullscreen / windows
* set `options > tracker > exporting > wait for X seconds before starting` to 5.

If neither of those help, please post the hdt_log.txt here after trying to export. ([see here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues))

**Comment by jleclanche** [comment]
Closing due to lack of feedback
