### ISSUE TITLE
Malorne

### ISSUE THREAD

**Issue by kingskybomber14** [Epix37/Hearthstone-Deck-Tracker#1556]
Deck Tracker doesn't realize when Malorne goes back into the deck. My Malorne came off of an unstable portal, so maybe that's the reason, but i know I gang up off of spellslinger it added the cards to the deck, but i ganged up azure drake which had already been in the deck. My best guess is that the problem was that it didn't originate in the deck.

**Comment by Epix37** [comment]
Do you have the replay of that game? Could you upload it (e.g. www.zippyshare.com)?
You can find the replay files in `%AppData%/HearthstoneDeckTracker/Replays`.

**Comment by kingskybomber14** [comment]
Looking at the replay it was much more convoluted, which is probably why it
didn't register. The replay is attached to the email. If that isn't good, i
can try using zippyshare.

**Comment by Epix37** [comment]
Can't attach files via email to github replies :(.
