### ISSUE TITLE
How do i make the window transparent instead of colored background?

### ISSUE THREAD

**Issue by TomerMun** [Epix37/Hearthstone-Deck-Tracker#1558]
i watched someone on stream and he used the deck tracker in windowed mode but his window was transparent as you can see here:
http://postimg.org/image/q5jf9jc65/
how can i do that?
mt window looks like this:
http://postimg.org/image/3vyc99g1v/

**Comment by Epix37** [comment]
You can't. Streams/videos do this by chroma-keying the background. 

Why not use the overlay? You can move everything to where you want it via `options > overlay > general > unlock`.
