### ISSUE TITLE
Wrong game stats when conceding in opponent's turn

### ISSUE THREAD

**Issue by npruehs** [Epix37/Hearthstone-Deck-Tracker#1560]
After conceding during your opponent's turn, the tracker fails to

* mark the game as concede
* save the name of the opponent (showing UNKNOWN HUMAN PLAYER instead)
* save the number of turns

Other stats seem to be recorded correctly.

![missingstats](https://cloud.githubusercontent.com/assets/757321/10267150/77e5a5b4-6a88-11e5-9c16-79128bfa66a1.png)

**Comment by riQQ** [comment]
See #1478.
