### ISSUE TITLE
Deck Tracker Crash

### ISSUE THREAD

**Issue by shamanix7** [Epix37/Hearthstone-Deck-Tracker#1561]
Deck Tracker crashed while I was brawling. I copied the log file to pastebin. After I restarted Deck Tracker, the log gets deleted (that happend always when I encounter strange behaviour of HDT, so  I copied the log file to pastebin before I restarted HDT):
http://pastebin.com/snh79gLy

**Comment by Epix37** [comment]
v0.11.3 does not work with the current brawl. Same as #1535
