### ISSUE TITLE
Shaman: Import from game (constructed) -> always includes 2x Frost Shock

### ISSUE THREAD

**Issue by nickhimself** [Epix37/Hearthstone-Deck-Tracker#1564]
Despite not using the card, 2x Frost Shock are always included automatically in new Shaman decks when using the Import from Game (Constructed) feature.

**Comment by Epix37** [comment]
Constructed deck importing works based on asset unloading, which is not always reliable. Not much that can be done about it though.

Try re-running the setup process: `options > tracker > importing > set up constructed importing`

**Comment by nickhimself** [comment]
Oh, awesome. Thanks!
