### ISSUE TITLE
Tracker need to restart game in order to work

### ISSUE THREAD

**Issue by Isaacheng** [Epix37/Hearthstone-Deck-Tracker#1569]
I was having HS opening for some time, then I open the tracker and got new updates, after that I open the tracker and the win tracker appears on my HS but not showing and recording me and my opponent during games, i try to import deck as well, but it is not working.

Restarting the tracker does not help ,but everything works fine after restarting the game.

**Comment by Epix37** [comment]
HDT should usually tell you that the log.config was updated and you need to restart Hearthstone for it to work. 

HDT recently switched to a different logfile, which hearthstone only writes to after restarting.
