### ISSUE TITLE
Sync Issue with Hearthstats

### ISSUE THREAD

**Issue by Finrodi** [Epix37/Hearthstone-Deck-Tracker#1570]
I don't really know if this belongs here however for the past few days I just cannot sync my stats with Hearthstats properly and I always have that red exclamation point on top saying that "The remote server returned an error: (504) Gateway Timeout."

When I look at Hearthstats I see that my arena runs are only half finished and that my constructed runs are not fully updated as well.

Sometimes it gives other error messages of to why I cannot sync which I will post as soon as I get them.

Cheers

**Comment by Epix37** [comment]
Has that happened in the past 24 hours?

**Comment by Finrodi** [comment]
Yes. Literally 5minutes before I posted this as well as the last couple days.

**Comment by Epix37** [comment]
Should be fixed soon.
