### ISSUE TITLE
export wont work

### ISSUE THREAD

**Issue by bl4ck0r** [Epix37/Hearthstone-Deck-Tracker#1573]
Hi,

first amazing program ! Thank you for your effort!

my export to HS wont work correctly:

Either it works but not all cards would be add (normaly just 20-25) 
or it goes to filter 0 mana and after that it cant find any card.

Thank you

PS: (have newest version)

**Comment by Epix37** [comment]
See my response on gitter. Sounds like one of the solutions in the FAQ should solve your problems.
