### ISSUE TITLE
v0.11.3 / No client auto-update

### ISSUE THREAD

**Issue by dcpc007** [Epix37/Hearthstone-Deck-Tracker#1574]
i have 0.11.3 on Win7.
No update detected at launch.
I have Options > Settings > Check for Update checked (but no beta).

NB : i already see auto updates at start before.

(PS: is it possible to link an issue on a tag or version like 0.11.3 ?)

**Comment by Epix37** [comment]
0.11.3 is the latest release

**Comment by dcpc007** [comment]
Ok, the current "last version" point to a pre-release one ... not see the details.
Should have 2 links in the main page : stable and beta or RC then.
