### ISSUE TITLE
Click secrets to mark them as "checked"

### ISSUE THREAD

**Issue by nipser** [Epix37/Hearthstone-Deck-Tracker#1576]
Enemy plays secret -> All possible secrets appear.

Request:

Make secrets clickable to mark them as checked.

Example:

Paladin plays secret + hero power. I do my turn. At the start of the paladin's turn, nothing happens (secret is not Competitive Spirit). I now turn off Competetive Spirit in the secret-list as I know it can't be it.

Thanks for taking care of me,

Thorben

**Comment by RoboticEarthling** [comment]
This is actually already possible. Go to Options > Overlay > Interactivity and enable it.
