### ISSUE TITLE
Mac OS X

### ISSUE THREAD

**Issue by 32i** [Epix37/Hearthstone-Deck-Tracker#1578]
Hello,
I haven't found the requirements, so I wonder - is this thing working on Mac OS or it's windows only?

Thank you in advance,
Slava

**Comment by Epix37** [comment]
Yes, this one is not compatible with OS X.

Check out https://github.com/bmichotte/HSTracker.

**Comment by 32i** [comment]
Thanks for the quick answer, mate!
I'll try Deck tracker on Windows anyway :)
Good luck!
