### ISSUE TITLE
Will Not Import From Game

### ISSUE THREAD

**Issue by Spedwards** [Epix37/Hearthstone-Deck-Tracker#1579]
So this feature has saved me a lot of time, but today it's just showing me the steps on how to use it over, and over again.

Information that may help solve it:

1. 9th deckslot with Mage.
2. Currently 9 decks saved (and not archived) in HDT, one being an Arena deck.

**Comment by Epix37** [comment]
Try entering and leaving the "Play" screen once or restarting Hearthstone completely.

**Comment by Spedwards** [comment]
Restarting Heathstone worked. Cheers.

While I have you here, how exactly do you update HDT? And how do you check what version you are currently running?

**Comment by Epix37** [comment]
HDT will prompt you to update if a new version is available. You can see the one you are using in the bottom left of the "help" screen (titlebar) or on startup with v0.11.4/5 pre-release.
