### ISSUE TITLE
Import Arena Deck

### ISSUE THREAD

**Issue by Ekkersito** [Epix37/Hearthstone-Deck-Tracker#1581]
HDT says it can't find an arena deck when i have already crafted one.
![image](https://cloud.githubusercontent.com/assets/15053666/10400448/173a168e-6eb9-11e5-823d-37675258c8fa.png)

**Comment by Epix37** [comment]
Any change from leaving and re-entering the arena screen or restarting hearthstone?

If not, please restart hdt, leave and enter the arena screen and post the log here ([see here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)).
