### ISSUE TITLE
Translucent overlay stuck on with 0.11.3

### ISSUE THREAD

**Issue by Fyren** [Epix37/Hearthstone-Deck-Tracker#1582]
The white translucent overlay has gotten stuck on twice for me.  In both cases, it was right after creating an arena deck and opening the HDT window using my system tray.  It might have to do with me not having auto-importing of arena decks on and it trying to pop up the question about importing it?

**Comment by Epix37** [comment]
Do you know what the window state was when the issue occoured? (Tray, Minmized, ...)
Can you reproduce it?

**Comment by Fyren** [comment]
It was in the tray both times.  I didn't complete the second arena run yet, so I haven't had a chance to try.

**Comment by Epix37** [comment]
This might get fixed with MahApps.Metro 1.2, which should be out in a few weeks. If not, I'll look into this agian.

**Comment by HEGladios** [comment]
This happens to me almost all the time. Not quite sure what triggers it, but usually when finishing a new arena deck I open HDT from tray and it will almost always have the white overlay, forcing me to restart it.
