### ISSUE TITLE
the remote server returned an error: 503 server unavailable

### ISSUE THREAD

**Issue by sensoshamaru** [Epix37/Hearthstone-Deck-Tracker#1583]
![error](https://cloud.githubusercontent.com/assets/15057379/10407378/60a1617c-6ec0-11e5-8eba-0fa22264369d.png)

Basically when i open the launcher and i type my email and password an error occurs : ''the remote server returned an error: 503 server unavailable'' Help

PS:the password is correct,i tried creating another accounts but it didn't worked

**Comment by sensoshamaru** [comment]
Just solved it, dont know how tho

**Comment by riQQ** [comment]
HTTP Error 503 is a server problem of Hearthstats. There's nothing Hearthstone Deck Tracker can do about it.
