### ISSUE TITLE
"Hide deck when friendlist is open" doesn't work if a message from/to you is currently onscreen

### ISSUE THREAD

**Issue by NightKev** [Epix37/Hearthstone-Deck-Tracker#1584]
If I wait for the message to disappear then it works again.

**Comment by Epix37** [comment]
The feature works based on pixel checking. Don't think there's much I could do about it in this case.

**Comment by the-gods-are-cruel** [comment]
i can't find this in Options, any clue?

**Comment by riQQ** [comment]
`Options > Overlay > Interactivity`

**Comment by Cu8eR** [comment]
this cannot be fixed, only if @Epix37 add a setting to hide/show elements in the game by clicking on them - something was introduced here by epix, unfortunately I cannot find this issue here
