### ISSUE TITLE
Hearthstone Deck Tracker does not start

### ISSUE THREAD

**Issue by Murlocmaster** [Epix37/Hearthstone-Deck-Tracker#1585]
http://imgur.com/j6L7kE1

Has you can see I'm unable to start HD Tracker, it really bugs me because It doesn't seem to be a common issue in this forum, some help please?

**Comment by Epix37** [comment]
Try these suggestions: http://www.tomshardware.co.uk/faq/id-1931360/0xc00007b-error-fix.html
