### ISSUE TITLE
Incorrectly Counts Secrets

### ISSUE THREAD

**Issue by Spedwards** [Epix37/Hearthstone-Deck-Tracker#1588]
I've noticed that a few times, an opponent will play a Secret early in the game. Long after it gets triggered, he'll play 2+ more secrets and the list of secrets will have (2+) listed next to the one(s) that were already played.

Each secret should max at 2 instead of going up to 5, and should be 1 (or greyed out) if already played. The only exception would be if a Spellslinger or similar was played.

**Comment by Epix37** [comment]
The count represents how many of the unrevealed secrets could be a given sercret.

**Comment by Spedwards** [comment]
I get that @Epix37 however in constructed when no minions like Spellslinger or Lorewalker Cho have been played, you cannot have more than 2 of each spell in your deck and you can only have 1 of each secret active.

**Comment by Epix37** [comment]
Will no longer be an issue with v0.12.3+ as the secret count is always 1.
