### ISSUE TITLE
Getting slow

### ISSUE THREAD

**Issue by burkovae** [Epix37/Hearthstone-Deck-Tracker#1592]
Hi,

seems so that at least for my computer the Decktracker is getting slower and slower by the minute.
[20:06:48] PluginWrapper: Error updating Collection Tracker:
System.TypeLoadException: Could not load type 'Hearthstone_Deck_Tracker.Hearthstone.Game' from assembly 'HearthstoneDeckTracker, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'.
   bei Hearthstone_Collection_Tracker.HearthstoneCollectionTrackerPlugin.<CheckForUpdates>d__8.MoveNext()
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   bei Hearthstone_Collection_Tracker.HearthstoneCollectionTrackerPlugin.CheckForUpdates()
   bei Hearthstone_Collection_Tracker.HearthstoneCollectionTrackerPlugin.OnUpdate()
   bei Hearthstone_Deck_Tracker.Plugins.PluginWrapper.Update()

That is the error message hat keeps flooding the log file till it reaches around 23MB.

Thank you ;-)

**Comment by Epix37** [comment]
Hey, 

for now: disabling the collection tracker plugin will solve the issue. 

The next update (most likely coming tomorrow)  will limit the number of exceptions a plugin can throw.

**Comment by burkovae** [comment]
Hi,

Thank you, that helped! ;-)

Am 11.10.2015 um 20:35 schrieb Epix:

**Comment by Epix37** [comment]
Release v0.12.0. This should no longer happen.
