### ISSUE TITLE
Hearthstone deck tracker broken after installing plugin

### ISSUE THREAD

**Issue by hhybrid1287** [Epix37/Hearthstone-Deck-Tracker#1594]
I Have been using HDT for a little while now, and I decided to install the collection tracker plugin. As I didn't have anything to run RAR files, I installed winzip. I followed the instructions of what to do, and as soon as I extracted it to plugins, HDT stopped working. Now whenever I launch hearthstone, A decklist pops up, even if I do not have that deck equipped.  I cannot launch HDT, and I have tried deleting the file, but it pops up with the error message that the file is open in another location. PLEASE HELP!

**Comment by Epix37** [comment]
You probably have another HDT process still running. Check the system tray / task manager.
