### ISSUE TITLE
Games occasionally fail to completely save

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#1601]
I notice that sometimes, a game will fail to completely save. Meaning that, when I check its replay, the play from the last turn is missing. The replay also uses a different visual format than the usual one, which I guess is the format used for games that are still in progress.

Could this be caused by me alt-tabbing out of Hearthstone too quickly when a game ends? How long should I wait before alt-tabbing out of Hearthstone, to let HDT save the game?

**Comment by Epix37** [comment]
You have to exit the victory/defeat (i.e. go back to the menu) for hdt to save the stats and replay. 

If you do that and it still fails to save, please post the log here after.

**Comment by culinko** [comment]
"The replay also uses a different visual format than the usual one"

This means the replay file was not created and what you see is the "old replay viewer" which takes the cards from the xml file of the game. Did you notice some of the affected games to have 0 minute duration or saved game mode as "None"?

**Comment by GaryKing** [comment]
No, duration is fine, and game mode is fine.
