### ISSUE TITLE
Suggestion: Stats - New column - Total time of playing deck

### ISSUE THREAD

**Issue by Binori** [Epix37/Hearthstone-Deck-Tracker#1602]
![My proposal] (http://i.imgur.com/Zu5J3Zl.png)

**Comment by culinko** [comment]
It would be cool to display the info somewhere, but I don't think this is the right place. Maybe in the deck picker or somewhere at the bottom, like hearthstone tracker does (though only total played time: https://gocorral.files.wordpress.com/2014/09/hearthstone-tracker-arenas.png)

**Comment by Cu8eR** [comment]
yeah, we need more stats... we have a really good and advanced tracker with many useful features but we need stats too!

**Comment by Epix37** [comment]
closing in favor of #1603
