### ISSUE TITLE
Wrong card count and overlay

### ISSUE THREAD

**Issue by boydkr** [Epix37/Hearthstone-Deck-Tracker#1610]
During a game, I noticed my "cards-in-hand" count was way off (said my cards in hand was 13).  Also, my opponent only had one card in hand, but the overlay was showing "turn drawn" indicators for 4 cards, and the opponent hand card count also said 4.

After the game ended, deck tracker offered to discard the game because it didn't match my selected deck.

http://pastebin.com/HDK0VFRU

I attempted to take a screenshot, but silly me forgot that the HDT overlay doesn't show up on game screenshots :/

Log files:
http://www13.zippyshare.com/v/QvPxlUrR/file.html

**Comment by Epix37** [comment]
Should be fixed.
