### ISSUE TITLE
After update Tracker do not show decks #2

### ISSUE THREAD

**Issue by Bloomer24** [Epix37/Hearthstone-Deck-Tracker#1611]
Howdy me again :)
After new update got some semi-minor issue.
1) Tracker open up without any problem
2) After clicking "Open Hearthstone client" it throw message that it cannot find client/cannot start it. But it starts client after some time thou :P Still, even when I show him when heartstone folder is, no change occur - there is message "cannotstart/find..." but client starts aftersome time.
3) Tracker do not show decks :P I need to Restart it from settings when client is up and it works then. so it is like this for me now: start Tracker --> click "strt client" --> close errormessage --> client start --> go to main hearthstone menu --> restart tracker --> Have fun

Any idea/solutionfor me? :)

**Comment by Epix37** [comment]
Does this happen every time?
What happens if you start Hearthstone "manually" before starting HDT?
