### ISSUE TITLE
exporting does not seem to work

### ISSUE THREAD

**Issue by heIlo** [Epix37/Hearthstone-Deck-Tracker#1612]
the export to hearthstone feature seems to have stopped working for me :o 
not all the cards in the deck are exported and those tht are are in the wrong quantites

**Comment by Epix37** [comment]
See if you find a solution here: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#exporting-is-not-working-properly--missing-cards

**Comment by heIlo** [comment]
oops i should have read that first. thanks so much!
