### ISSUE TITLE
Paladin Secrets don't reset after start new game

### ISSUE THREAD

**Issue by pikkedonker** [Epix37/Hearthstone-Deck-Tracker#1613]
I've to this time only seen this with a paladin opponent ! And what I mean with reset is that the list on the lefthand side stays listed in the next game.

**Comment by pikkedonker** [comment]
Hmmm... donated 5 dollars.... not much but on a wage of 230 dollars a month... 47 years of age... please please for the love of god please keep your money in your pocket! Can't even begin to describe the error I'm getting!

**Comment by Epix37** [comment]
Send me the paypal transaction id (epix@hsdecktracker.net) and I will send you the money back.

And if you want help, describe the errors you are getting. Please provide crash reports / logs where applicable. ([see here for how to submit the logs](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues))

**Comment by pikkedonker** [comment]
No need for money back! I'm an ass and really sorry for my outburst!
First of I reloaded my old 11.3.0 and remembered this works like a charm! Well worth the 5 bucks. That's why I'm an ass; should have donated much sooner, I just got frustrated and linked the errors in the new version with my donation.  
Second; The 12.1 doesn't give me syntactical errors but mostly symantical. Like the list remaining in the next round. Got problems exporting lists to heartstone even on lowest setting 150 ms. (yup checked if I had the cards and the quantity of it) Saving the new decks doesn't always work. Have to look into that if that's for instance version wise or not.
I forgot that you do this for free and I had no right to criticise it like this. Sorry!

**Comment by riQQ** [comment]
What's the problem with exporting exactly? Have you tried this https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#exporting?

**Comment by pikkedonker** [comment]
I'll try that and truth B told I'm now running on Win10 (was Win7! wish it still was tbh) So the Win8 and up could B true. Can't B certain when the problem arose with version 12 or Win10, they were installed close to eachother. Also will up the wait setting to > 1... See I am an ass! Maybe the saving deck's is also an Win 10 problem? I'll find out when I run in Win7 compatible mode. Thx!

**Comment by pikkedonker** [comment]
Just wanted to let you know I've not upgraded to 12.1 yet. I'm keepin 11.3.0 as it gives me more stability and works for me. Therefore I cannot look at the solutions you have provided alas.
