### ISSUE TITLE
Antivirus conflict

### ISSUE THREAD

**Issue by HerKrieger** [Epix37/Hearthstone-Deck-Tracker#1615]
Hi everyone,
since the 0.12.1 update i can't run HDT.
My antivirus (Norton Internet Security) close the application as soon as it started (just after the hearthstats windows) and delete the Hearthstone Deck Tracker.exe file. I noticed that it also deleted files in the AppData folder such as the deck file.
Norton says to me it is an SONAR.Heuristic.120 (high risk it says but clearly not my skill field so...) and asks me to reboot my laptop.
The funny thing is that when i right-click/analyse the .exe file, there's no problem for norton.
The deck lost isn't a so big problem, i would be able to recover 9 of them from the game, but i would like to know how to fix this issue in order to continue using HDT while playing.
Thank you for your time.

**Comment by Sentinent** [comment]
It seems like a problem with your anti-virus, and not the deck tracker. Maybe try adding the .exe to your anti-virus's whitelist?

**Comment by HerKrieger** [comment]
That's finally what i did, i add the file to the SONAR whitelist.
i'm sorry i bothered you for so less, now i've got a collection/deck recover time.
Thank you for that great tool that is HDT.
