### ISSUE TITLE
Crash on switching decks in HDT

### ISSUE THREAD

**Issue by arkein** [Epix37/Hearthstone-Deck-Tracker#1616]
OK, so there were a couple of strange things before I encountered the crash.
My first or second opponent (hunter) plays a secret, then concedes.
1) List of secrets remained through all next games.
2) Timer remained counting time from that game.

At some point I decided to get rid of that, so I tried switching active deck in HDT to some other deck.
Switched back to the one I was playing and crashed HDT.

Crash report http://pastebin.com/bZGjMSAU

**Comment by Epix37** [comment]
Likely related to #1553
