### ISSUE TITLE
loading image disable option?

### ISSUE THREAD

**Issue by the-gods-are-cruel** [Epix37/Hearthstone-Deck-Tracker#1618]
i have a very slow PC and the image shows up for about a minute while i want to keep my gaming life a secret from my family, it would be very handy if there is an option to disable the loading logo.

and sometimes, the logo shows up on a black square instead of a transparent background.

much appreciated. :)

**Comment by Cu8eR** [comment]
It has been added here: #1625 #1622 

So in 0.12.3 you will have this option in the settings

**Comment by andburn** [comment]
@the-gods-are-cruel wants the loading splash screen hidden, should be added with #1629

#1625 and #1622 should help performance on a slow computer though.

**Comment by Cu8eR** [comment]
Thanks!
