### ISSUE TITLE
Tracker crashes everytime new game starts

### ISSUE THREAD

**Issue by omarlittle66** [Epix37/Hearthstone-Deck-Tracker#1619]
Just installed the tracker, seems like a great tool but I can't seem to get it working. The moment a new game starts- the tracker crashes. It doesn't seem to matter if I I have a deck active or not. Auto deck selection on or off also no difference.

 I tried a few things, re-installing the tracker, deleting Hearthsthone app files. I run it on Windows 8. Is there something I'm missing? error file 
http://pastebin.com/WmLwArZ1

**Comment by Epix37** [comment]
Try updating/repairing/reinstalaling your .NET Framework.

**Comment by omarlittle66** [comment]
Hey man, That was the problem indeed! Run some repair tool from microsoft site, installed the net framework and it works perfectly now.

Thank you for making such a great tool and such  a quick and accurate response!
