### ISSUE TITLE
Stuck on Enemy Turn

### ISSUE THREAD

**Issue by HSMatheus** [Epix37/Hearthstone-Deck-Tracker#1620]
I have recently had a few games where during the enemy turn, a card would be held but not played and eventually would get stuck on the screen. The enemy timer would not go down. I would sit waiting for 5-10 minutes to no prevail and eventually I get pissed from waiting (I can't even concede, smash the button, nothing happens) so I close down both game and deck tracker. After reopening, I would be rewarded with a disconnect and a loss. This is a seriously frustrating problem especially for the ranked and arena game modes. Is deck tracker causing this? When I play without Deck Tracker, 
this does not happen.

**Comment by culinko** [comment]
This is not an issue with Deck Tracker. You simply disconnected from the game servers.

**Comment by HSMatheus** [comment]
well, but when I play without deck tracker, this doesn't happen my friend... and my internet is fine. When this was happening, I was on youtube, facebook, etc. , normally

**Comment by Epix37** [comment]
As @culinko  said, this is not a problem with HDT. You got disconnected from hearthstones servers for whatever reason. Could be a issue on hearthstones or on your end, no way to tell. 

This would happen whether you use HDT or not. The only way HDT "interacts" with hearthstone is reading textfiles hearthstone generates. It's not possible for HDT to disconnect you from hearthstone.

**Comment by Cu8eR** [comment]
IT is problem with battle.net client, connection between you and Blizzard servers. Not HDT
