### ISSUE TITLE
offering ui translation

### ISSUE THREAD

**Issue by the-gods-are-cruel** [Epix37/Hearthstone-Deck-Tracker#1621]
i'm interested in translating the UI into Vietnamese, please contact me if you're interested. thank you. :)

**Comment by Epix37** [comment]
Thank you. See #471. 

Still no ETA on this though.

**Comment by the-gods-are-cruel** [comment]
Most Vietnamese players play with the US client and I believe there will never be a Vietnamese localization of Hearthstone, I just want to translate the Tracker's UI to Vietnamse so that it would be more user-friendly to our local community. :)
