### ISSUE TITLE
Missing font.

### ISSUE THREAD

**Issue by toxictrace** [Epix37/Hearthstone-Deck-Tracker#1623]
Please, help. Installed Windows 10. Missing font Russian language. How to fix?
![default](https://cloud.githubusercontent.com/assets/10530116/10574645/071838a4-7660-11e5-9ade-d18e5f701da7.jpg)

**Comment by Epix37** [comment]
Does it work it you set `options > tracker > appearance > card language - primary` to russian?

**Comment by toxictrace** [comment]
Language switching works. Only instead of Russian letters the squares.
![hdt1](https://cloud.githubusercontent.com/assets/10530116/10586080/289076b6-76a3-11e5-8afb-4a3df408f01b.jpg)
![hdt2](https://cloud.githubusercontent.com/assets/10530116/10586081/28912782-76a3-11e5-8af7-4796b14967f5.jpg)

**Comment by Epix37** [comment]
Oh I see. 
I'm not really sure what's wrong then tbh, might be something with your system.

It does work for me:
![russian](https://cloud.githubusercontent.com/assets/7737910/10586827/939531ea-769e-11e5-909d-8a88f827b3d3.PNG)

**Comment by Epix37** [comment]
Give this a shot: http://stackoverflow.com/a/11614925

**Comment by toxictrace** [comment]
No, this method does not load. And what font you use for Russian name cards ???

**Comment by Epix37** [comment]
All languages use `Belwe Bd BT`

**Comment by quark-zju** [comment]
I believe it's related to Windows UI font settings. And it seems Windows 10 has a bug in font fallback handling, where previous Windows works well.

In my Win 10, with UI font set to "Segoe UI", some chinese punctuation will display as boxes, just like the screenshot. If the UI font is "Microsoft YaHei UI", the card name will display correctly. (However there are some other places such as the edit note dialog where it displays incorrectly. I suspect MahApps.Metro hardcoded "Segoe UI" somewhere).

Try these steps:

1. Change Windows Display Language to Russian.
2. Relogin. Backup registry `HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics`, especially all `*Font` values.
3. Change Windows Display Language back.
4. Relogin. Restore the registry backup.

**Comment by Cu8eR** [comment]
IT is a bug in Windows 10, not HDT

**Comment by TrueCarry** [comment]
Epix37, is it possible to distribute custom font with HDT, so windows would not broke foreign languages?

**Comment by Scronheim** [comment]
mb change hdt font?

**Comment by Scronheim** [comment]
"All languages use Belwe Bd BT"
where you can download the font with Cyrillic?

**Comment by quark-zju** [comment]
It also happens in user generated content such as deck names, notes. I don't think there is a good solution here.
