### ISSUE TITLE
HDT is recording my ranked gamers as casual.

### ISSUE THREAD

**Issue by ElFeed** [Epix37/Hearthstone-Deck-Tracker#1627]
Title says it all.

**Comment by riQQ** [comment]
Are you using the latest version v0.12.2?

**Comment by ElFeed** [comment]
Yes I am.

**Comment by riQQ** [comment]
If this happens again, could you upload the HDT and Hearthstone logs somewhere?

**Comment by ElFeed** [comment]
Will do.I will check it later on and see what happens

**Comment by Sawovsky** [comment]
This is also the case with me, ranked are recorded as casual. Also, HDT is acting really strangely last couple of days, crashing, or simply stoping to track my games, just showing deck at site but all other layout stats disappear.

**Comment by thoughthouse** [comment]
This is happening to me as well. Here's my HDT log: http://pastebin.com/2yjyTSfY

**Comment by Epix37** [comment]
I have a feeling this might be related to 3.2.0.10604. 

Could you guys post the Asset.log from Hearthstone/Logs after a game did not record correctly?
