### ISSUE TITLE
Can't Open Deck Tracker

### ISSUE THREAD

**Issue by KJess** [Epix37/Hearthstone-Deck-Tracker#1628]
I upgraded from windows 7 to windows 10 and it shows all files are just blank and I cannot open them.

I have winrar and .net framework installed but this is what I see when I unzip

https://gyazo.com/03e5b4c0d351b9c638b99fe5fe6c32ba

Whenever I click on it it asks me to choose an app to open it with. What am I missing?

**Comment by riQQ** [comment]
You downloaded the source code instead of the binaries. Go to https://github.com/Epix37/Hearthstone-Deck-Tracker/releases and download this file: `Hearthstone.Deck.Tracker-v0.12.2.zip`

**Comment by KJess** [comment]
Ah, thank you very much!

**Comment by Cu8eR** [comment]
Yes, always download only released version, not download sources - only if you wanna compile it on your own

**Comment by KJess** [comment]
Cheers guys. Working great.
