### ISSUE TITLE
Ability to Add Version Number to Deck Name?

### ISSUE THREAD

**Issue by pagem** [Epix37/Hearthstone-Deck-Tracker#1630]
Been a while since I've updated and followed this development so apologies if this is a feature already in the tool but...

Is there any way to add the deck version number in HDT to the deck created in Hearthstone when you run an "export"? At the moment I export and then in the Collection Manager select the deck and then append the version number onto the deck name.

Be great if at least optionally I could tell HDT to add the version details to the name.

Thanks, still a great tool ;)

**Comment by Epix37** [comment]
That was not in already, but it's a neat idea. Done! Will be in the next release.
