### ISSUE TITLE
Hearthstone Deck Tracker not tracking stats for Ranked & Tavern Brawl

### ISSUE THREAD

**Issue by Rinqed** [Epix37/Hearthstone-Deck-Tracker#1631]
Whenever I finish a game in Arena the results get tracked (I am using the HearthArena companion app in case there is a compatibility issue) but when I finish a game in Ranked or Tavern Brawl it briefly comes up with the stats (e.g. 1-0), but then it resets to 0-0. I've checked my settings and I've got it so the results are tracked for Ranked, Brawl and Arena so I don't know what is causing this issue - can you help?

**Comment by chrismyeung** [comment]
Arena stats are tracking fine for me, but Ranked isn't working. I don't track Brawl.

**Comment by Epix37** [comment]
When it happens the  next time, please post the hdt log here. [See here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)
