### ISSUE TITLE
Problem to login Deck Tracker

### ISSUE THREAD

**Issue by nextspy** [Epix37/Hearthstone-Deck-Tracker#1633]
Tried to start decktracker but in login this problem appear :
![decktrackerproblem](https://cloud.githubusercontent.com/assets/15240570/10654425/d3882126-7848-11e5-8b09-54e531df0a96.jpg)

**Comment by riQQ** [comment]
Do you have Windows 8.1? Try this: http://stackoverflow.com/questions/32097492/method-not-found-void-system-diagnostics-tracing-frameworkeventsource-beginget.
