### ISSUE TITLE
Export doesn't work for the warrior card "Charge"

### ISSUE THREAD

**Issue by leppyr64** [Epix37/Hearthstone-Deck-Tracker#1634]
Searching for Charge Alex Horley Orlandelli brings up both "Charge" and "Kor'kron Elite" because the Elite has the ability Charge.  Since I don't have a Golden Charge, the "Kor'kron Elite" gets entered into the deck instead of Charge.  Disabling "Prioritize golden cards" will resolve the issue but causes no gold cards to be in my deck.

**Comment by Epix37** [comment]
Did they change the artist name on one of them? I'm sure that used to work.

**Comment by leppyr64** [comment]
Honestly I've been away from the game for a while and don't know all the changes.  Did they possibly add a new filter for the ability "charge"?
