### ISSUE TITLE
can't start at all

### ISSUE THREAD

**Issue by realgodzilla** [Epix37/Hearthstone-Deck-Tracker#1635]
the application can't start at all. i download it then extract it and open the app, hearthstone deck tracker, but it says like this " The application was unable to start correctly (0xc000007b). Click OK to close the application. please help, thanks.

**Comment by Epix37** [comment]
Give the fixes suggested here a try: http://www.pcadvisor.co.uk/how-to/windows/how-fix-application-was-unable-start-correctly-0xc000007b-error-message-3613164/
