### ISSUE TITLE
Missing note + some typos

### ISSUE THREAD

**Issue by Cu8eR** [Epix37/Hearthstone-Deck-Tracker#1637]
In export screen - there should be a note that you have to uncheck gems filter on the bottom of the screen. If you leave it (select for example 2 gems cards) nothing is exported

Also there are some typos in the export screen in HDT

**Comment by Epix37** [comment]
The mana filter is cleared automatically. Did you disable `options > tracker > exporting > auto clear filters`?

What typos exactly? I might be blind.

**Comment by Cu8eR** [comment]
![typo](https://cloud.githubusercontent.com/assets/778890/10675287/a45dc704-78ff-11e5-9c21-2081c07b2dff.png)
