### ISSUE TITLE
Wrong Numbers in Mechanics Window

### ISSUE THREAD

**Issue by all4hm** [Epix37/Hearthstone-Deck-Tracker#1638]
Hello, 

as seen here
![image](https://cloud.githubusercontent.com/assets/15249950/10668395/6a5a156c-78dc-11e5-9a20-48d661be97d0.png)
the number of deathrattles and battlecry effects is wrong
the correct amount would be 
deathrattles: 7 (Boom, 2x Shredder, 2x Darnassus Aspirant, 2x Leper Gnome)
battlecries: 5 (Flame Juggler, 2x Darnassus Aspirant, Dr Boom, Loatheb)

imho

with greetings

**Comment by Epix37** [comment]
Boom does not have deathrattle, but this was indeed wrong. I wonder how no one has ever noticed that. Will be fixed with the next update.
