### ISSUE TITLE
decktracker not exporting correctly

### ISSUE THREAD

**Issue by pevan** [Epix37/Hearthstone-Deck-Tracker#1640]
When exporting from hearthpwn, the tracker isnt working. In the field that inputs the cards name, nothing appears and hence the export doesnt work.

I tried using version 12.2 and the pre-release 12.3. No exporting works.

**Comment by riQQ** [comment]
Have you tried these suggestions: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#exporting?

**Comment by andburn** [comment]
Its this #1642

**Comment by Epix37** [comment]
Closing in favor of #1642
