### ISSUE TITLE
Import Hearthpwn not working anymore

### ISSUE THREAD

**Issue by LordPalpatine** [Epix37/Hearthstone-Deck-Tracker#1642]
Since update to v0.12.3.0 the import from Web (Hearthpwn) is not working anymore.
Imported deck lists unknown cards (see Screenshots).

![dht_1](https://cloud.githubusercontent.com/assets/13450067/10688781/035384d4-7977-11e5-90b3-ff487073298b.png)

**Comment by Epix37** [comment]
Looks like something changed on hearthpwns end. This also is an issue in 0.12.2. Fixed for the next update.

**Comment by ctleung21** [comment]
decktracker still not exporting from hearthpwn! BibleThump

**Comment by Binori** [comment]
As workaround you can do Export from hearthpwn webpage to Cocklatrice format and then in HDT choose "Import -> From Clipboard: Card Names".
