### ISSUE TITLE
Card Analyzer plugin possible with API?

### ISSUE THREAD

**Issue by therationalpi** [Epix37/Hearthstone-Deck-Tracker#1643]
I would like to track the winrate of cards when drawn so I can analyze my deck's performance and improve it. While this would be great to have built in, I would totally consider just building a plugin to do the same. I know there's an API for HDT, and I know that HDT keeps track of all of your cards throughout every game, but I'm not sure if the API gives access to the necessary information.

**Comment by Epix37** [comment]
There is current no API endpoint for that but you can just access the data directly.

Here is an example on how you could get a list of all games for the deck "deck" where the player played a card with the cardid "cardid":
```C#
Hearthstone_Deck_Tracker.DeckList.Instance.Decks.FirstOrDefault(x => x.Name == "deck")
				        .DeckStats.Games.Where(
				                                g =>
				                                g.TurnStats.Any(
				                                                x =>
				                                                x.Plays.Any(
				                                                            p =>
				                                                            p.Type == PlayType.PlayerDraw && p.CardId == "cardid")));
```
