### ISSUE TITLE
Was working perfectly for a few days and now cursor just clocks busy nonstop on load

### ISSUE THREAD

**Issue by Kiltedbear** [Epix37/Hearthstone-Deck-Tracker#1644]
I was playing and it was working perfectly for a few days, but the game crashed on me requiring a hard reset of my PC. I was rushing to try and get back in, so I started tracker while other stuff was loading in the background. It opened the main window and I tried clicking on the start hearthstone button on the right, but the cursor busy animation kept going and going. When I clicked on the app, things inside the bounding box greyed out and I got the message that the app was not responding. I waited for better than several minutes and I had to shut it down. Tried starting again several times and that is all it does now, even after a reboot. I was running 12.2, so I deleted the whole directory and downloaded the pre-release 12.3 and still the same thing happens. It still has my log in info in there however because it still listed the decks I had created in the list even though I never had to log back into the app. I assume the log in details are kept somewhere else. I can't even click on anything inside the window. Should I deleted my log in info and where do I get to it?

**Comment by Kiltedbear** [comment]
Now it seems to work again although just about 10 minutes ago it did not. At the top is a message that says import from Hearthpwn currently not working. Not sure if it's related...

**Comment by Epix37** [comment]
Glad it fixed itself. Did you restart hearthstone in the meantime? Could be something with that. 

Hearthpwn importing not working is not related, they simply changed something on their website that causes cards to appear blank when importing decks.
