### ISSUE TITLE
Stats not saving

### ISSUE THREAD

**Issue by leonatos** [Epix37/Hearthstone-Deck-Tracker#1645]
For a few days now the tracker stopped saving stats for my games (mostly ranked, but I think one lost arena game also didn't register). When a game is over the deck score updates for a short amount of time and then resets to the state it was before that. It doesn't seem to be consistent - every now and then games register but this is very rare now.

This is the latest log, exported as described: http://pastebin.com/ShqNrhfj

**Comment by Epix37** [comment]
Do you have `options > overlay > general > don't reset decks after a game` disabled? If so, try enabling that. I think this might be related.

**Comment by Epix37** [comment]
One other thing: You mention mostly ranked, from the log I would say those games were mostly casual, is that right? Assuming those are the games in question, do you have casual games set to be recorded and displayed? (`options > tracker > stats > record / display`)

**Comment by leonatos** [comment]
Hi, I don't play casual games. This month I have played like 2 to try one deck and that was it. It's all ranked or arena.

I just noticed something interesting. I made a change in one of the non-tracking decks (it seems this resets the stats for it) and it started tracking it again. Maybe something gets corrupted under specific circumstances?

I added the check that suppresses resetting after games and will see if it will help and get back to you, but I have a question. Will a new game clean the previously drawn cards or is there a manual way of resetting?

**Comment by Epix37** [comment]
Do you mean the cards that remain on the overlay when you are in menu after the game due to that option? Those clear when you start a new match, yes.

**Comment by leonatos** [comment]
Nice! By the way - great job with that application, it's really impressive work :)

**Comment by leonatos** [comment]
It seems so far that disabling the deck reset post-game prevented the lost stats. Is this the intended way of working or is it just a workaround? Should I close the issue?

**Comment by Epix37** [comment]
That's great! Definitely not the intended way, no. I'll fix that!

**Comment by leonatos** [comment]
The issue came back regardless of the not-reset setting. I made change to a deck of mine so stats reset to 0-0. Then I went and won a game. 1-0 for a couple of seconds and then it went back to 0-0 like it was happening before. Played cards remained visible, so I know the reset setting is off.

**Comment by Epix37** [comment]
I think I found and fixed the issue. 

Try enabling on recording stats for the game modes casual and other. That should solve the problem for the time being.

**Comment by leonatos** [comment]
Hi again. Some status after the latest update - games are not saving once again, even though I have all game types tracked as instructed.

**Comment by Epix37** [comment]
I'm not really sure where the problem is then :/.

Try resetting the config and see if you still have the same issue. To do so close HDT and rename the `config.xml` in `%AppData%/HearthstoneDeckTracker` (options > tracker > settings > open appdata folder). If that *does* help, please upload your old config.

**Comment by leonatos** [comment]
I did what you told me, it seems to be working so far, will keep an eye on it. Another thing happened now though - after some games end the overlay isn't resetting (cards, timers, attack value, card age keeps on going).

**Comment by Vlaix** [comment]
Got the same issue. No stats being saved/pushed to Hearthstats, and no progress in the bottom gold count. It's as HDT isn't registering anything.

Tried wiping the config.xml file, the option you mentioned is already checked.

I run the HS client on Win 10 x64 and I also used the Heartharena Overwolf overlay (which never interfered before today). It started randomly and didn't correlate with an update or any known change.

**Comment by Epix37** [comment]
If the heartharena overwolf app removes something from the log.config, that would very well be the problem.

Please try starting HDT and Hearthstone before starting the heartharena app, see if the problem persists.

**Comment by Vlaix** [comment]
Doesn't change anything. Ranked stats purely and simply aren't recorded.

**Comment by Epix37** [comment]
After playing a game and going back to menu, is there a "Asset.log" file in "Hearthstone/Logs"? If so, could upload it?

**Comment by Vlaix** [comment]
Asset.log : https://mega.nz/#!oZ5lCATK
Asset_old.log : https://mega.nz/#!9EgDyTiZ

Right now stats seem to be tracked fine. I've noticed inconsistencies when playing versions of deck (past 1.0), but none when playing original decks.

**Comment by Vlaix** [comment]
Quick update : everything works perfectly now. I can only assume that something, somewhere shat its pants earlier.

**Comment by mikeburmester** [comment]
I'm having a similiar issue with games occasionally not being logged.  Attached log and config.  In the log, the game starting at 13:35:34 is the one that didn't save.  Relevant part of the log when trying to save the game:

[13:44:53] GameEventHandler: --- Game was won! ---
[13:44:53] HandleGameEnd: Game ended...
[13:44:53] Gamestats: Current Game ended after 11 turns
[13:44:53] HandleGameEnd: Assigned current game to deck: Demon Handlock
[13:44:53] HandleGameEnd: Waiting for game mode detection...
[13:45:01] GameEventHandler: set rank to 13
[13:45:02] Game: Set CurrentGameMode to Casual
[13:45:02] HandleGameEnd: Detected game mode, continuing.
[13:45:02] HandleGameEnd: CurrentGameMode=Casual, Waiting for ranked detection...
[13:45:02] HandleGameEnd: Done waiting for ranked detection, continuing.
[13:45:02] HandleGameEnd: Waiting for game mode to be saved to game...
[13:45:02] HandleInMenu: Game is now in menu.
[13:45:02] HandleInMenu: CurrentGameMode=Casual, Waiting for ranked detection...
[13:45:02] HandleInMenu: Done waiting for ranked detection, continuing.
[13:45:02] Game: Set CurrentGameMode to Ranked
[13:45:02] Game: Set CurrentGameMode to Ranked
[13:45:17] HandleGameEnd: Game mode was saved, continuing.
[13:45:17] HearthStatsManager: trying to upload match: Win vs Priest, 23/11/2015 13:35:34
[13:45:17] HearthStatsAPI: Game Win vs Priest, 23/11/2015 13:35:34 is not valid (invalid game mode: None)


[config.xml](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/41642/config.xml.txt)
[hdt_log_1448287382.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/41643/hdt_log_1448287382.txt)
