### ISSUE TITLE
Auto-use broken for two updates

### ISSUE THREAD

**Issue by HandsOfBlue** [Epix37/Hearthstone-Deck-Tracker#1646]
The autouse option has not been working properly since at least two updates ago; i have tried unselecting, restarting, and reselecting, then restarting again, and it still shows "cards not in deck" window as opposed to selecting another deck.

**Comment by Epix37** [comment]
Do you have `(menubar) MAIN > AUTO DECK SELECTION` and `options > tracker > general > autoselect deck if only one possible` enabled?

**Comment by HandsOfBlue** [comment]
Ah, didn't know about the menu bar option; thanks!
