### ISSUE TITLE
Error recording game end

### ISSUE THREAD

**Issue by riQQ** [Epix37/Hearthstone-Deck-Tracker#1647]
The game was recorded as 0 turn game, no replay was recorded and the Overlay did disappear in the menu. The timer kept going.

https://gist.github.com/riQQ/68285f6c8bfaa3b3be79#file-hdt_log-txt
https://gist.github.com/riQQ/68285f6c8bfaa3b3be79#file-power-log
https://gist.github.com/riQQ/68285f6c8bfaa3b3be79#file-asset-log

**Comment by jleclanche** [comment]
Fixed
