### ISSUE TITLE
Clone Deck: Keep Stats Issue

### ISSUE THREAD

**Issue by Elitesparkle** [Epix37/Hearthstone-Deck-Tracker#1650]
If you want to clone a deck, you need to choose to clone or delete its games history.

It doesn't matter what you choose: you'll lose them anyways.

Can you check it and, if correct, do something about it?

**Comment by Epix37** [comment]
Works fine for me. Are you maybe only cloning the latest version but stats are on older ones?

**Comment by Elitesparkle** [comment]
> Works fine for me.

Ok.

> Are you maybe only cloning the latest version but stats are on older ones?

Maybe.
I don't remember.
