### ISSUE TITLE
Stats Tables: Games Number

### ISSUE THREAD

**Issue by Elitesparkle** [Epix37/Hearthstone-Deck-Tracker#1652]
In the tables we can see wins-losses (e.g. 3-2) and win percentage (e.g. 60%).

I suggest to add a new values to show the number of games played as a class against another one (e.g. 5).

So, we'll have 3 values instead of 2:
W-L: 3-2
W%: 60%
W+L: 5

Adding this value, you will have some problems, so I'll tell you a way to fix them too.

In the Deck tab there is the Overview Class table.
It will just get a new line for the wins+losses value.

In the Deck tab there is also the Overview Deck table.
Adding a new line for each deck version will be a lot confusing, so I suggest you to show a single line for each version and add 2-3 buttons somewhere to switch among one of the 3 values.

In the Overall tab you decided to use a check box to do something similar for the Overview Detail table.
Since now we have 3 values instead of 2, a check box isn't enough anymore.
I think some buttons will be fine.

The buttons should be something like the tab system you are using to change between, for example, Deck and Overview tabs.

**Comment by Epix37** [comment]
#1603
