### ISSUE TITLE
Exporting with windows 10, Search works but doesn't click cards.

### ISSUE THREAD

**Issue by niceeyeman70** [Epix37/Hearthstone-Deck-Tracker#1654]
When exporting to hearthstone the cards are shown by the program using search but it doesn't click on any of the cards.

**Comment by andburn** [comment]
[This link](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#exporting) might help.
If that doesn't work, you can try unchecking `options > tracker > export > Auto clear filters`.

**Comment by niceeyeman70** [comment]
Speed set to very slow
wait 1 secnds before starting 
all boxes unchecked.  Still cycles through cards with search but doesn't click the card, then at end it gives message that I don't own any of the cards and tells me how much dust I need to craft them.

**Comment by Cu8eR** [comment]
I can confirm that... but it happens only sometimes (windows 10, 64bit)

**Comment by Epix37** [comment]
Any effect from changing hearthstone resolution or turning fullscreen on/off?

**Comment by Cu8eR** [comment]
@Epix37 - when you change speed to normal, it works fine

**Comment by Epix37** [comment]
You are having a different issue then.
> Speed set to very slow
wait 1 secnds before starting 
all boxes unchecked. Still cycles through cards with search but doesn't click the card [...]

**Comment by niceeyeman70** [comment]
Working now, went to options in hearthstone, graphics resolution was blank changed to my resolution (which didn't change the appearance of HS) and now it exports fine.

**Comment by Cu8eR** [comment]
@Epix37 can be closed - all of these kind of issues are because of default settings used for exporting in HDT -> maybe there should be a lower speed selected by default

**Comment by Lucasvor** [comment]
Hi, I'm with the same problem, already tried other options and dont work.
Logs: http://pastebin.com/ZAg5t1Gj

**Comment by andburn** [comment]
@Lucasvor your tracker version is *0.12.2* the current version is *0.13.6*, do you have updates turned off? `options > tracker > settings > check for updates` Update to the latest version and try again, including some of the suggestions above.
The log says you were exporting to brawl, does it export ok in play mode?
Adding a *Brawl* tag to the deck can help when exporting to brawl (right-click deck and click edit tags, and add a new one).

**Comment by Lucasvor** [comment]
So I tried in both modes and updated for the latest version.
And the problem still remains.
new Log: http://pastebin.com/UZ1mDCnP

**Comment by andburn** [comment]
Un-check the box in `options > tracker > exporting > Auto clear filters` and try it once more

**Comment by Lucasvor** [comment]
did not work :(

**Comment by andburn** [comment]
Ok, not sure then :frowning:
Did you try [the steps in the FAQ](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#exporting)?

**Comment by Lucasvor** [comment]
yes tried, I could record a video showing.

**Comment by andburn** [comment]
yeah sure, its worth a go

**Comment by Lucasvor** [comment]
here's the video: http://www.dailymotion.com/video/x3ii6uf_problem_videogames.
and that ends it appears all the missing letters.

**Comment by andburn** [comment]
This is strange, no idea why its not clicking on the cards. There are a few other issues that may be related (#1859, #1853, #1793). I'll see if I can figure something out.

**Comment by Lucasvor** [comment]
Thank you for your help

**Comment by Lucasvor** [comment]
Andburn, I managed to fix the problem.
Was the new nvidia driver who had given the problem, now installed an older version of the driver and it worked.

**Comment by andburn** [comment]
Great, that's good to know.
