### ISSUE TITLE
2 Suggestions

### ISSUE THREAD

**Issue by ShoestringTaz** [Epix37/Hearthstone-Deck-Tracker#1656]
1. I am sure this has been asked a million times - but when oh when oh where is a mac version every going to be developed?

2. Is someone able to develop a plugin that tells you the win rate of particular cards in your deck of the last 50 games say. 

3. On a similar vein is it possible for the tracker or a plugin to tells you the most played cards by your opponents in the last 50 games say?

Thanks for a great app!

**Comment by Epix37** [comment]
1. Most likely not from my end, sorry. Check out this project: https://github.com/bmichotte/HSTracker

2/3. #1643
