### ISSUE TITLE
Hearthstone Deck Tracker has completely stopped working for me.

### ISSUE THREAD

**Issue by ericBG** [Epix37/Hearthstone-Deck-Tracker#1660]
I've just been completely unable to use any of its features since coming back from holiday and I'm despairing. Tried everything short of reinstalling Hearthstone so far - changed log.config 5 times, removed all traces of Hearthstone Deck Tracker twice (which lost me my over 450 games with Freeze Mage :cry:)... It first started yesterday when it wouldn't even pick up that it didn't have the right deck, even if the cards were 30 different cards... now it won't do fuck all, importing doesn't work (it just pops up the first time run message like #935, tracking won't even track the mulligan phase... Bah. Any clues? All relevant configs are attached. (https://gist.github.com/ericBG/7e9b67b4aa214310b800)

BTW even though I'm on the prerelease I've tried like all the past versions.

**Comment by Epix37** [comment]
Is it pointed to the correct hearthstone installation? (`options > tracker > settings`)

**Comment by ericBG** [comment]
Yes, definitely. I'm pointing it to the root directory of it.

**Comment by Epix37** [comment]
Could you restart HDT and Hearthstone, play a game (practice concede is fine) and post the hdt log ([see here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)) as well as all the files from Hearthstone/Logs here?

**Comment by ericBG** [comment]
I think it must've been me not restarting both at the same time. Fixed as soon as I did that -_- I should've known better. Sorry for wasting your time!
