### ISSUE TITLE
Calculating the damage on my side off the board is incorrect

### ISSUE THREAD

**Issue by YvesW** [Epix37/Hearthstone-Deck-Tracker#1665]
I either don't get what the feature does, or the math gets screwed up somewhere. Not sure if it happened for my opponent's damage as well (it's correct on the screenshots anyway, mght screw up on other matches), but I've noticed that it very often displays the wrong number. I often times want to use the feature for druid lethal with force roar, so I only really look at it when playing druid. This means that it might be class specific, since I can't remember it screwing up for other classes.

![1](https://cloud.githubusercontent.com/assets/7929021/10771992/fb99fac2-7cf3-11e5-84a3-c8a0ca3941af.png)
![2](https://cloud.githubusercontent.com/assets/7929021/10771993/fb9bccc6-7cf3-11e5-9a75-09daa5a94885.png)

**Comment by Epix37** [comment]
#1598, #1607
