### ISSUE TITLE
[v0.12.3] PC/Mouse lag after quitting Hearthstone

### ISSUE THREAD

**Issue by scainburger** [Epix37/Hearthstone-Deck-Tracker#1667]
When Hearthstone closes, my mouse moves at what appears to be about 5 fps until I close/restart HDT. Everything else (eg screen/video FPS) works fine, it's just an input delay issue. 

Windows resource monitor reports nothing unusual in terms of HDT usage. HDT log reports no errors.

HDT still detects Hearthstone as running even though there is no Hearthstone.exe process, as seen in the debug window.

Below screenshot steps of reproduction:
- Clear log
- Open debug window
- Run Hearthstone through HDT
- Quit Hearthstone at main menu

![Screenshot](https://cloud.githubusercontent.com/assets/460517/10780346/9d329438-7d90-11e5-9f4b-01b70ffeca1f.png)

*EDIT:* Log level 1 does not show any additional information.

**Comment by Epix37** [comment]
Does the issue remain after rebooting your pc?

This is most likely related to `options > overlay > interactivity`.

**Comment by scainburger** [comment]
The mouse stutter issue was fixed by unchecking "Force on", however HDT still thinks the game is running even with interactivity fully disabled. 

HDT itself does suffer some micro-stutters similar to the previous mouse issue after quitting the game, both with and without interactivity enabled. To clarify, the mouse moves as normal, however there is a noticeable delay after clicking/hovering on something in HDT for a resulting action.

**Comment by scainburger** [comment]
The above issue was caused by "Advanced window search". Disabling it fixed all micro stuttering and HDT properly detected Hearthstone being closed,

**Comment by Epix37** [comment]
Ah, I knew this problem sounded familiar! Thanks for letting me know.

**Comment by Cu8eR** [comment]
I had same issue, this fixed my problem
