### ISSUE TITLE
show opponent decklist when rematched in arena?

### ISSUE THREAD

**Issue by rrwoods** [Epix37/Hearthstone-Deck-Tracker#1668]
I just had a situation where I faced the same opponent name playing the same class as a previous game in an arena run, and lo and behold he had the same cards.  Being able to see what cards they played in previous games would be kinda sweet (in this instance I checked the replay -- but for opponents with nondistinctive names I wouldn't necessarily think to do it).

Interface-wise I'd imagine you show these like jousted cards; right in-line with the decklist, but greyed out (until they play them of course).

There is the issue of the confidence that this is really the same guy.  I'd be content with the requirement of some (configurable) time interval (default one hour?) indicating that it probably isn't the same opponent; even then, you can't be sure, since different players can have the same name (so allow the player to turn this feature off).

**Comment by Epix37** [comment]
I'm not a fan of this kind of thing. I don't think this has been discussed specifically for arena before but multiple times for constructed.

https://github.com/Epix37/Hearthstone-Deck-Tracker/issues?utf8=%E2%9C%93&q=prediction
(I know this is not quite the same as what you are asking but it goes in the same direction)

If you think it's the same opponent you can always manually check the cards he played under `stats > games > show opponent deck`

**Comment by rrwoods** [comment]
Are there hooks in the plugin API for someone to write this for themselves if they wanted to?  I think you'd need functions for
* adding cards to your opponent's deck
* detecting your opponent's name
* detecting your opponent's class
* either all the stuff you use to track the deck or access to the played-cards-history for previous games

**Comment by Epix37** [comment]
I have not tested this but something like this should work:


```C#
public void OnLoad()
{
	Hearthstone_Deck_Tracker.API.OnGameStart.Add(FindOpponent);
}

private void FindOpponent()
{
	var gameWithKnownOpponent =
				DeckList.Instance.Decks.SelectMany(d => d.DeckStats.Games)
				        .FirstOrDefault(
				                        g =>
				                        (DateTime.Now - g.StartTime).TotalMinutes < 60 && g.OpponentName == Core.Game.CurrentGameStats.OpponentName
				                        && g.OpponentHero == Core.Game.CurrentGameStats.OpponentHero);
	if(gameWithKnownOpponent != null)
	{
		foreach(var card in gameWithKnownOpponent.GetOpponentDeck().Cards)
			for(var i = 0; i < card.Count; i++)
				Core.Game.Opponent.RevealDeckCard(card.Id, 0);
	}
}
```

**Comment by rrwoods** [comment]
The CurrentGameStats object appears to be uninitialized at the time OnGameStart is run.  The value of CurrentGameMode is None, and the values of OpponentName and Opponent Hero are both "".

**Comment by rrwoods** [comment]
At the time of the first OnPlayerDraw, the OpponentHero appears to update, but the OpponentName does not.

**Comment by rrwoods** [comment]
If I put the opponent-recognizing code in OnUpdate instead, it recognizes it earlier.

However sometimes the names of the players are swapped (but not their classes).

**Comment by Epix37** [comment]
I meant the "something like this" part :).

Try `API.Core.Game.Player/Opponent.Name`.

**Comment by rrwoods** [comment]
Sorry, I forgot to say:  I am using the fields in API.Core.Game rather than the CurrentGameStats, which I figured out after my first comment after yours.  However the name-swapping is still happening on API.Core.Game.Opponent/Player.Name -- sometimes my name is in Opponent.Name and the opponent's name is in Player.Name.  I can't reliably figure out what this correlates to.

**Comment by rrwoods** [comment]
Also, the RevealDeckCard method doesn't appear to do anything.
