### ISSUE TITLE
Events are triggered on visual begin/end, not when response from server arrived

### ISSUE THREAD

**Issue by SOLiNARY** [Epix37/Hearthstone-Deck-Tracker#1672]
Deck tracker now triggers events (secrets disappearing, showing drawn cards, etc.) based on their actual happening ingame, not when response from server arrived about event.
I liked previous behaviour. Can I turn current one off in options?

**Comment by Epix37** [comment]
While this was not the initial purpose of the change that lead to it, I am very happy with it. Slightly decreasing the unfair advantage HDT already gives anyway is a good thing in my opinion.

Unless there are technical reasons for changing it back at some point, this will not be changed and there won't be an option for it, sorry.
