### ISSUE TITLE
Reset stats

### ISSUE THREAD

**Issue by Rhakete** [Epix37/Hearthstone-Deck-Tracker#1676]
Is it possible to reset my stats completely? I want to basically start from scratch while keeping a backup of my stats up until this point.

**Comment by Epix37** [comment]
Easiest way: edit your deck(s), save as 1.1 without any changes. 

Make sure you have options>tracker>stats>display set to show the selected version.

**Comment by Rhakete** [comment]
Thanks for the quick reply! I was looking for something that let me reset the whole tracker (Sort of like a clean install while keeping a backup for the optione to go back to those stats I already collected) but I guess I will go with the method you suggested. Thank you for all your hard work, you're awesome! :)
