### ISSUE TITLE
When exporting a deck, version number is not added to name.

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#1680]
When I export a deck to HS, the version number is not added to the name. 

I have checked that:

- A version number does indeed exist for the deck. In this case, it is v1.3.
- The checkbox is checked to append the version number to the deck's name.

I'm using the latest stable version, released today.

**Comment by Epix37** [comment]
What's the name of the deck? If too long the version would be cut off.

**Comment by GaryKing** [comment]
Yes that's possible that the name is too long. Like you've done, is probably best to include the version number and trim the name, since the user expects the version number to be there if they have it checkmarked. It'll be obvious to the user that the name was trimmed, and so they'll probably figure out the reason for that.
