### ISSUE TITLE
Crashes & computer freeze when different class secrets are in play and you try to grey out one

### ISSUE THREAD

**Issue by dhoepelman** [Epix37/Hearthstone-Deck-Tracker#1681]
**Situation**:
Face mage in Arena (as hunter, but probably irrelevant)
Mage plays spellslinger and gets and plays a hunter secret (turned out misdirection), and plays a mage secret (turned out mirror image)
I attack a minion with a minion to test for freezing trap & snake trap.

**What happened**:
1. HDT (correctly) displays all the hunter and mage secrets for the opponent
2. Freezing trap and snake trap did not get greyed out after minion attack
3. Clicking on the freeze trap does not grey out the secret, instead, Windows shows the message "Hearthstone deck tracker has stopped responding" and the mouse has become slow/uncontrollable. 

By going to the task manager and killing HDT using solely the keyboard I could restore the mouse (still managed to suboptimally finish the turn in the nick of time :smile:). Did not check CPU usage.

No crash report was generated.

**Expected**:
User can grey out secrets as possible in previous versions if the deduction does not work. HDT does not crash.

**Comment by culinko** [comment]
The issue with Freezing Trap and Snake Trap not graying out automatically should already be fixed. Are you still experiencing the crash when manually graying out secrets?

**Comment by dhoepelman** [comment]
Well it only happened when when the opponent played 2 different classes' secrets simultaneously. I don't think I have encountered that since.

**Comment by culinko** [comment]
I'll try to test your example with a friend later today and then I report back.

**Comment by culinko** [comment]
Tested with a friend. He played Misdirection, Mirror Entity. I attacked into his minion and Freezing Trap + Snake Trap grayed out correctly. No crash occurred after I tried to click on secrets to to make them checked or unchecked.
