### ISSUE TITLE
when "automatically gray out secrets" is selected...

### ISSUE THREAD

**Issue by newherre** [Epix37/Hearthstone-Deck-Tracker#1682]
when "automatically gray out secrets" is selected, the number on the right of the secret when 2 or more are played, which i found very useful, is not shown anymore.

**Comment by joshtab** [comment]
I don't remember seeing this number. It lists the total number of secrets your opponent has in play?

**Comment by Epix37** [comment]
What's the use exactly? You can see the total number of secrets in the game, which one is which does not matter for triggering them.

**Comment by newherre** [comment]
no, maybe i couldnt explain well. an example of the situation before this feature existed:

paladin plays avenge and a minion. i attack his face, play a minion and pass. i gray out all secrets except avenge and redemption. paladin plays repentance. now secrets arent grayed out anymore, but a 2 appears beside avenge and redemption. i suppose that means there are 2 secrets that can be one avenge or redemption, while only 1 of them could be a repentance or noble sacrifice or other.
if i select "automatically gray out...", when the paladin plays repentance, all grayed secrets return normal, but a 2 won't appear beside avenge and redemption, so i won't have a useful tool to remember that avenge or redemption are more likely to be among the secrets played than a competitive spirit or something.

**Comment by Epix37** [comment]
HDT keeps track of each secret separately. 
In your scenario: if the paladin plays a 3rd secret and you trigger it, it will revert back to the state before that secret way played (e.g. everything greyed out but 2).

**Comment by newherre** [comment]
yeah, i know, but the useful number on the right doesn't appear anymore with the new option

**Comment by joshtab** [comment]
Here's a UI change which would allow the player to extract the most amount of information, but still be easy to use:

When the player mouse's over the opponent's individual secrets (as in, one of the question mark bubbles on the opponent's profile), the available secrets list changes - instead of showing the aggregate view, it shows you which cards that one secret could be.

When the player's mouse is anywhere else, it shows what it shows today.

**Comment by newherre** [comment]
i checked again, whether the "gray out automatically" option is selected or not doesn't matter: the number on the right just isn't there anymore, it's a little feature that is gone away with one of the latest updates. can we get it back please?
