### ISSUE TITLE
Games tracked on HDT are not being synced to HearthStats

### ISSUE THREAD

**Issue by Rinqed** [Epix37/Hearthstone-Deck-Tracker#1686]
Starting today I discovered that the games which are getting tracked on HDT are no longer syncing to HearthStats, whereas yesterday and earlier my games (at least my Arenas) were being synced but now they are not, does anyone know what the problem is - I've tried to force a full sync but it doesn't seem to do anything?

**Comment by Epix37** [comment]
Hearthstats servers are having some trouble. Seems to be working for me now. If you still have problems try later again.

**Comment by Cu8eR** [comment]
Today, it works fine. This is an issue with Hearthstats website - maybe they are overloaded, just wait one or two hours and try again
