### ISSUE TITLE
Windows 10 (64-bit), HDT v0.13.1, HS v3.2.0.10604 - Does not Export at all. 

### ISSUE THREAD

**Issue by DenverTech** [Epix37/Hearthstone-Deck-Tracker#1687]
With the most recent release, HDT fails to export. It seems that it isn't grabbing control of the cursor at all. It just sits there, and afterwards it doesn't report any errors, as if the export was successful.

**Comment by Epix37** [comment]
Try changing Hearthstone to windowed/fullscreen as well as the suggestions here: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#exporting

**Comment by Cu8eR** [comment]
All win10 issues reported here are because of bad settings - set fullscreen + set lower speed in exporting. This fixed all problems fir me and my friends on Win 10
