### ISSUE TITLE
HDT Crash after loggin in

### ISSUE THREAD

**Issue by Lumisch** [Epix37/Hearthstone-Deck-Tracker#1695]
Hey folks! 
Yesterday i had a bluescreen while playing HS with HDT! 
After the computer restarted, HDT crashing every time on HDTs mainscreen (where you can choose decks and so on).
when i delete the HDT folder in APPdata and i sign in with my account, it says that there is no HS path! then i find it manually and the same happen it hang it self up! 
I hope some can help me and sorry for my bad english=(

Heres my crash report

**Comment by Lumisch** [comment]
cant copy file... so i just copy the text

########## 04.11.2015 00:27:02 ##########
System.IO.IOException: Die Datei "C:\Users\Felix\AppData\Roaming\HearthstoneDeckTracker\config_backup.xml" ist bereits vorhanden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   bei System.IO.File.Copy(String sourceFileName, String destFileName)
   bei Hearthstone_Deck_Tracker.XmlManager`1.Save(String path, Object obj)
   bei Hearthstone_Deck_Tracker.Config.Save()
   bei Hearthstone_Deck_Tracker.SortFilterDecks.CheckBoxSortByClass_OnChecked(Object sender, RoutedEventArgs e)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   bei System.Windows.Controls.Primitives.ToggleButton.OnChecked(RoutedEventArgs e)
   bei System.Windows.Controls.Primitives.ToggleButton.OnIsCheckedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   bei System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   bei System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   bei System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   bei System.Windows.Controls.Primitives.ToggleButton.set_IsChecked(Nullable`1 value)
   bei Hearthstone_Deck_Tracker.Windows.MainWindow.LoadConfigSettings()
   bei Hearthstone_Deck_Tracker.Core.Initialize()
   bei Hearthstone_Deck_Tracker.App.App_OnStartup(Object sender, StartupEventArgs e)
   bei System.Windows.Application.OnStartup(StartupEventArgs e)
   bei System.Windows.Application.<_ctor>b__0(Object unused)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Lumisch** [comment]
Can't copy file! so i copy the text! =)

########## 04.11.2015 00:27:02 ##########
System.IO.IOException: Die Datei "C:\Users\Felix\AppData\Roaming\HearthstoneDeckTracker\config_backup.xml" ist bereits vorhanden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   bei System.IO.File.Copy(String sourceFileName, String destFileName)
   bei Hearthstone_Deck_Tracker.XmlManager`1.Save(String path, Object obj)
   bei Hearthstone_Deck_Tracker.Config.Save()
   bei Hearthstone_Deck_Tracker.SortFilterDecks.CheckBoxSortByClass_OnChecked(Object sender, RoutedEventArgs e)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   bei System.Windows.Controls.Primitives.ToggleButton.OnChecked(RoutedEventArgs e)
   bei System.Windows.Controls.Primitives.ToggleButton.OnIsCheckedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   bei System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   bei System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   bei System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   bei System.Windows.Controls.Primitives.ToggleButton.set_IsChecked(Nullable`1 value)
   bei Hearthstone_Deck_Tracker.Windows.MainWindow.LoadConfigSettings()
   bei Hearthstone_Deck_Tracker.Core.Initialize()
   bei Hearthstone_Deck_Tracker.App.App_OnStartup(Object sender, StartupEventArgs e)
   bei System.Windows.Application.OnStartup(StartupEventArgs e)
   bei System.Windows.Application.<_ctor>b__0(Object unused)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

########## 04.11.2015 00:27:03 ##########
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei System.Windows.DeferredAppResourceReference.GetValue(BaseValueSourceInternal valueSource)
   bei System.Windows.DependencyObject.GetEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, RequestFlags requests)
   bei System.Windows.DependencyObject.GetValueEntry(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, RequestFlags requests)
   bei System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   bei System.Windows.Shapes.Shape.get_Fill()
   bei System.Windows.Shapes.Shape.OnRender(DrawingContext drawingContext)
   bei System.Windows.UIElement.Arrange(Rect finalRect)
   bei System.Windows.Controls.Canvas.ArrangeOverride(Size arrangeSize)
   bei System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   bei System.Windows.UIElement.Arrange(Rect finalRect)
   bei System.Windows.Media.VisualBrush.DoLayout(UIElement element)
   bei System.Windows.Media.VisualBrush.LayoutCallback(Object arg)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Epix37** [comment]
Try deleting this file
`C:\Users\Felix\AppData\Roaming\HearthstoneDeckTracker\config_backup.xml`
but I think the latter message is the relevant one. I have seen this a few times now and I still don't really know what the issue is or how to fix it. Most likely something "outside of" HDT. Maybe try reinstalling .NET Framework.
