### ISSUE TITLE
question?: May I ask for your formula for the probability that a card is in hand?

### ISSUE THREAD

**Issue by ttowncompiled** [Epix37/Hearthstone-Deck-Tracker#1697]
I have also calculated this probability and I think that our results differ. I'm curious to see what your formula is, if I may.

And also, do you take into consideration the changes that occur over time such as cards being played from hand and cards being pulled from the deck by effects such as Mad Scientist?

**Comment by Cu8eR** [comment]
I am interested too :+1:

**Comment by Epix37** [comment]
```C#
var holdingNextTurn = Math.Round(100.0f * Helper.DrawProbability(1, (cardsLeftInDeck + handWithoutCoin), handWithoutCoin + 1), 1);

public static double DrawProbability(int copies, int deck, int draw)
{
	return 1 - (BinomialCoefficient(deck - copies, draw) / BinomialCoefficient(deck, draw));
}

public static double BinomialCoefficient(int n, int k)
{
	double result = 1;
	for(var i = 1; i <= k; i++)
	{
		result *= n - (k - i);
		result /= i;
	}
	return result;
}
```

It does not account for anything happening on the next turn other than the first draw, nor the time of cards being in hand or anything of that nature.

**Comment by ZergShadow** [comment]
can you explain all numbers and var  in formula?cant understand this.

**Comment by r3lik** [comment]
I too would appreciate it if you explained it a bit more.
