### ISSUE TITLE
API.hearthstats.net remote name could not be resolved

### ISSUE THREAD

**Issue by pefp2008** [Epix37/Hearthstone-Deck-Tracker#1699]
![error api](https://cloud.githubusercontent.com/assets/11478639/10984452/c0ee2052-83eb-11e5-82a5-8ade3973dc5e.png)
I'm not able to sync with hearthstats.

Is this a known issue?

**Comment by riQQ** [comment]
Hearthstats is down right now. See their twitter feed for updates: https://twitter.com/HearthStats.

**Comment by pefp2008** [comment]
OOOOOhh. ok. I don't use twitter

Sorry :P
