### ISSUE TITLE
Mulligan time added to opponent timer

### ISSUE THREAD

**Issue by leMinistre** [Epix37/Hearthstone-Deck-Tracker#1700]
Hello, there are couple problems in the last (0.13.1) version with the timer:

1) The time for the turn now is 1 min 15 secs, but your timer still counts as 1 min 30 secs
2) The mulligan timer addes to the summary opponents time and sometimes your first turn time addes to opponents time as well

Would be great if you could fix it

Thx beforehand!

**Comment by culinko** [comment]
#1007 covers the 1st point.

**Comment by Epix37** [comment]
Actually - the second point is a valid bug, yes.
