### ISSUE TITLE
Can't connect to the Hearthstats server

### ISSUE THREAD

**Issue by Takuhasu** [Epix37/Hearthstone-Deck-Tracker#1701]
Hey,
today I was trying to start and launch the deck tracker, but everytime I try to register or log in it, there's an error [unknown error while recieving].

**Comment by manasdirge** [comment]
same here:
![qq 20151106232454](https://cloud.githubusercontent.com/assets/15692803/11003006/3e1692da-84eb-11e5-8888-1db8fc24fb74.png)
![qq 20151106232634](https://cloud.githubusercontent.com/assets/15692803/11003005/3e0b4772-84eb-11e5-8c50-9d35efa53274.png)

**Comment by andburn** [comment]
This is likely an issue with the Hearthstats servers, due to the scheduled downtime earlier. Until the problem is fixed you can use the *continue as guest* option, on the login screen, to use the tracker.

**Comment by manasdirge** [comment]
thanks!

**Comment by Cu8eR** [comment]
It has nothing t odo with HDT.

**Comment by manasdirge** [comment]
I guess it's not HDT's problem, I can login on my old laptop, but not on the new surface pro 4
