### ISSUE TITLE
503 server unavailable

### ISSUE THREAD

**Issue by klonazapam** [Epix37/Hearthstone-Deck-Tracker#1704]
getting this error whenever i try to log into hearthstats via the app. can log into the website just fine.

**Comment by Cu8eR** [comment]
issue with Hearthstats servers, not HDT!

**Comment by JosePereles95** [comment]
Same problem, it is with the server. HDT works perfectly.

**Comment by Epix37** [comment]
API servers should be working again.

**Comment by GameEngine1** [comment]
the problem is only happening for my laptop. but my main computer does fine.
it switches between error 503 and 504
