### ISSUE TITLE
options-->overlay-->player(opponent)

### ISSUE THREAD

**Issue by chucklu** [Epix37/Hearthstone-Deck-Tracker#1706]
code in this file Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Config.cs
[DefaultValue(new[] {"Win Rate", "Cards", "Card Counter", "Draw Chances", "Fatigue Counter" })]
		public string[] PanelOrderOpponent = {"Win Rate", "Cards", "Card Counter", "Draw Chances", "Fatigue Counter" };

		[DefaultValue(new[] {"Deck Title", "Wins", "Cards", "Card Counter", "Draw Chances", "Fatigue Counter" })]
		public string[] PanelOrderPlayer = {"Deck Title", "Wins", "Cards", "Card Counter", "Draw Chances", "Fatigue Counter" };
I wonder if this can be made into enum,consider to support multi language

**Comment by Epix37** [comment]
It would break existing configs when trying to load it as enum becuse of the spaces in some of the strings. So enums would require a new config entry and some legacy config conversion to get working.
