### ISSUE TITLE
Won't import (constructed)

### ISSUE THREAD

**Issue by CicatrixFacia** [Epix37/Hearthstone-Deck-Tracker#1709]
I have imported at least 10 other constructed decks and Arena Decks. I am using version 0.13.1.  Now I can't import any decks. When I select my deck in HS and go back to the main menu I then click "import - constructed (beta)" and get the import instruction pop up page (every time). At this point it does not import I have included the latest log file using pastebin.com. Here is the copy of the URL: http://pastebin.com/a7SNtMR0

Any help or feedback would be greatly appreciated.

**Comment by andburn** [comment]
Advice from #1579 & #1371 might help
> Try entering and leaving the "Play" screen once or restarting Hearthstone completely.

**Comment by Cu8eR** [comment]
I advice to set delay time to 2sec and speed to slow

**Comment by CicatrixFacia** [comment]
Restarting Hearthstone fixed the issue.
