### ISSUE TITLE
Counterspell and Spellbender don't auto-gray out if you play a spell

### ISSUE THREAD

**Issue by NightKev** [Epix37/Hearthstone-Deck-Tracker#1712]
Counterspell doesn't gray out on any spell played by you, and Spellbender doesn't gray out on any spell that targets a minion.

**Comment by ceceita** [comment]
https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1679

**Comment by NightKev** [comment]
Oh, I didn't realize my search ignored closed issues. Whoops, sorry.

**Comment by Epix37** [comment]
@NightKev Wasn't it you who commented on my habit of usually not closing issues via commits? :P

**Comment by NightKev** [comment]
Shhh...

Actually though it's a bit annoying that searching issues by default only looks at open ones.
