### ISSUE TITLE
A way to reset deck stats every season [enhancement]

### ISSUE THREAD

**Issue by JonnyMcFire** [Epix37/Hearthstone-Deck-Tracker#1718]
I would like to request a way to reset the decks you have built and carry over season to season.  
Another way to look at it would be to say that I would like a view to have an option that displays the current seasons statistics instead of the overall statistics.

**Comment by Cu8eR** [comment]
Yes, something like statistic for every season :)

**Comment by riQQ** [comment]
In the `Stats > Game & Statistics` window you can filter by time frame. Selecting this month or last month is equivalent to filtering by this or last season.

**Comment by Epix37** [comment]
Also possible in the deck picker by settings `options > tracker > stats > display > timeframe` to "season".

**Comment by JonnyMcFire** [comment]
Thank you for the information!  

On a side note, I didn't realize the option existed and I'm a bit embarrassed for opening the issue now that I know this. My Bad.

Thanks!
