### ISSUE TITLE
Won't Auto Detect Deck

### ISSUE THREAD

**Issue by gabessdsp** [Epix37/Hearthstone-Deck-Tracker#1720]
Hey there, so to keep my settings synced across all versions I actually keep my HDT folder in my dropbox so that way it sync across all of my devices. Settings and all. The thing is though on my desktop computer it will auto-detect the deck I am using and switch it over, but on my laptop it will not do that. Since the settings are 100% the same I'm not sure what is going on. I have also tried downloading a new version and running it separately from my desktop and it is having the same issue.

**Comment by Epix37** [comment]
Is `MAIN > AUTO DECK SELECTION` (menubar) enabled on your laptop?

**Comment by gabessdsp** [comment]
yes

**Comment by Epix37** [comment]
Ok, could you reproduce the problem and then post the hdt logs?
[See here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues) for details on that.
