### ISSUE TITLE
Won't Connect to Server (503 Error)

### ISSUE THREAD

**Issue by gabessdsp** [Epix37/Hearthstone-Deck-Tracker#1721]
For about the past week my HDT hasn't been connecting to the server from my laptop. I've tried downloading a new version to no avail, but it seems to be fine from my desktop. All other internet services work fine form my laptop.

**Comment by gabessdsp** [comment]
![errorshdt](https://cloud.githubusercontent.com/assets/1356727/11067639/959df7fc-879b-11e5-9a01-90329abacdf7.PNG)

**Comment by Epix37** [comment]
HearthStats is temporarily down, should be working again soon.

**Comment by gabessdsp** [comment]
Ahh I thought hearthstats and HDT where two separate things
