### ISSUE TITLE
HDT not syncing. Error 503

### ISSUE THREAD

**Issue by pefp2008** [Epix37/Hearthstone-Deck-Tracker#1722]
Hi.
I know that hearthstats wasn't available last week for maintenance.
I can access the website now, but HDT won't sync.
I logged out of HDT and tried to login but i got an error 503  (which you can see in the image attached, which also shows my dashboard in hearthstats, so it can't be that hearthstats is down...)

In the image, is also shown the date and time of the screenshot, to confirm (-4.30-CCS) 

Help?

![hdt](https://cloud.githubusercontent.com/assets/11478639/11068552/0aca01da-87a4-11e5-8a7c-401431cd07d7.png)

**Comment by Epix37** [comment]
HearthStats API is temporarily down, should be working again soon.

Use "continue as guest" (bottom right) for the time being.

**Comment by pefp2008** [comment]
Thanks!!!
