### ISSUE TITLE
Maximize changelog + program after start

### ISSUE THREAD

**Issue by Cu8eR** [Epix37/Hearthstone-Deck-Tracker#1725]
Is there any way how to automaticaly maximize the windows with changelog + HDT? Close buttons and everything else are on the bot, on some resolutions they are not shown without moving the window.

**Comment by Epix37** [comment]
Again, I'm not really sure I 100% understand the problem.

I think the bug we are talking about is that when closing HDT maximized, it's not maximized on start (regardless of updates notes)?
