### ISSUE TITLE
Add a game in statistic window is shown in background 

### ISSUE THREAD

**Issue by Cu8eR** [Epix37/Hearthstone-Deck-Tracker#1726]
Add a game in statistic window is shown (opened) in the background behind the stats window. Can you make it opened above this stats window? It would save some clicks

**Comment by Epix37** [comment]
**Please be more descriptive!**
If possible provide step by step instructions on how to reproduce issues.

~~I'm not sure what you mean. The "add game" dialog is an in-window dialog.~~
I'm going to assume you mean the "old" stats window? And this only is an issue if stats are shown in a separate window? This will no longer be an issue once the construted stats also get moved to the new stats window.

**Comment by Cu8eR** [comment]
OK, so it will be fixed with new stats for constructed :+1:
