### ISSUE TITLE
Wrong card detection, after update.

### ISSUE THREAD

**Issue by chimzuk** [Epix37/Hearthstone-Deck-Tracker#1730]
After the todays Decktracker update it started to mess up with the card detection.
Came to inform you, hope it will be an easy fix for you. 
(downgrade helped for now)

**Comment by Epix37** [comment]
Are you by any chance on a region that hasn't updated to 4.0.0.10833 yet? You can see the current version in the battle.net launcher next to the "Play" button.

If that's not the case please reproduce the issue and post the hdt logs. [See here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues).

**Comment by chimzuk** [comment]
No. The version is 4.0.0.10833. When i got an update of DeckTracker and go to arena, it detects two cards right, and the one of them shows as a card from the new adventure, but it is not of cource. 

Just realized, that this is not the Arena helper plugin thread, I was going to contact the Arena helper autor, but somehow end up here. Sorry.

**Comment by Epix37** [comment]
Oh that makes more sense now! :)
