### ISSUE TITLE
Secrets don't show up on opponent's played cards when they're stolen by Kezan Mystic

### ISSUE THREAD

**Issue by mclemente** [Epix37/Hearthstone-Deck-Tracker#1735]
How to reproduce: play with a Kezan Mystic in your deck, your opponent must be class with Secret cards (Hunter, Paladin, Mage) for testing's sake.
Your opponent must play a Secret and then you drop Kezan Mystic, she'll steal it and it won't show up on the opponent's log, even if the secret is triggered later.

Match where I observed it: Warlock vs Hunter, Hunter played 1 secret, then his Mad Scientist died, bringing another. I drop Kezan and steal Bear Trap from their secrets.
Later on it was triggered, never went to the opponent's log.

**Comment by Epix37** [comment]
Will be fixed with v0.13.3 later today!
