### ISSUE TITLE
Allow for classless decks

### ISSUE THREAD

**Issue by ThePsionic** [Epix37/Hearthstone-Deck-Tracker#1736]
Mainly to be used during Tavern Brawls; allow each and every card into the deck.

**Comment by Epix37** [comment]
That would come with an incredible amount of problems. From internal logic where decks are expected to have a class, to it just not being supported by the UI anywhere. 

It would be a lot of work for something that would rarely find any use. I would suggest using "no deck mode" (`menu: MAIN > USE NO DECK`) instead.

**Comment by Cu8eR** [comment]
I agree with Epix in that case. It would be really time consuming. Anyway I see your point
