### ISSUE TITLE
Still not able to update.

### ISSUE THREAD

**Issue by TiermitBier** [Epix37/Hearthstone-Deck-Tracker#1738]
I cant update since a few weeks, an error occurs at 100%. now with the new cards coming it gets problematic. is there any possibility to uninstall and reinstall without losing all the data?

**Comment by Epix37** [comment]
You can download the latest version [here](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases) and replace all the existing files.

**Comment by TiermitBier** [comment]
problem solved :)
