### ISSUE TITLE
Forgotten Torch - Doesn't show Roaring Torch in deck

### ISSUE THREAD

**Issue by Labdabeta** [Epix37/Hearthstone-Deck-Tracker#1739]
Simple issue: Playing Forgotten Torch does not add a Roaring Torch to the decklist. The total deck size is updated, as are the probabilities, but it doesn't show the Roaring Torch. 

I am aware this presents a unique issue, but as a Software Engineer I can't help but think how easy it should be to automatically add a 0-copy Roaring Torch to every deck that includes Forgotten Torch, then increase the count in the deck whenever it is added. 

Not an urgent issue, but a useful one nonetheless.

Log file: http://pastebin.com/gYX9875t

**Comment by Epix37** [comment]
To add on to this: same goes for Curse of Rafaam, Ancient Shade, Entomb, Excavated Evil, Elise Starseeker and Map to the Golden Monkey. All fixed for the next update.

**Comment by ThePsionic** [comment]
@Epix37 Just to make sure, Beneath the Grounds shuffles 3x Ambush into the opponent's deck. I'm not sure but I think the last time I got that put on me the Ambushes didn't show in the tracker.

**Comment by bancron** [comment]
Excavated Evil doesn't work for me.

**Comment by Epix37** [comment]
Might be fixed with https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/7d1242575b7e716ecb71843b0b7e1ae2d5f989e2, I'll take another look though.
