### ISSUE TITLE
Tracker doesnt do anything in the game. Help pls :)

### ISSUE THREAD

**Issue by pbber** [Epix37/Hearthstone-Deck-Tracker#1743]
Hi folks,
when i start up the current version of the deck tracker and create my new deck in the tracker an the game it simply doesnt work ingame. It doesnt grey out any of my played cards nor does it show me the cards played by my opponent.
I really tried all i could including several reinstalls.

Pls help and sry for my broken english

Regards,
p.

**Comment by SeregPie** [comment]
I have the same issue. Just downloaded and installed it today. It shows the panels but doesn't track the  cards.

**Comment by MushroomHunter** [comment]
Got this problem too.

**Comment by Epix37** [comment]
If it's a fresh install just restarting HDT and Hearthstone might be the solution.

Otherwise make sure it's pointed to the correct hearthstone installation: `options > tracker > settings > set hearthstone path`

**Comment by Epix37** [comment]
The FAQ should now properly adress this problem again. 

https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#its-not-detecting-cards-i-or-my-opponent-play

(If the post above does not help, the second point in the FAQ should)
