### ISSUE TITLE
Feature request: Accounts to share decks between computers.

### ISSUE THREAD

**Issue by brostone51** [Epix37/Hearthstone-Deck-Tracker#1744]
I play hearthstone on both my laptop and desktop, it'd be nice if my decks on HDT could be synced between the two devices.

**Comment by Cu8eR** [comment]
use dropbox or hearthstats

**Comment by ThePsionic** [comment]
Yep, that option already exists. Just make a Hearthstats account and log into it to sync your decks and stats.
