### ISSUE TITLE
Disconnects and Arena

### ISSUE THREAD

**Issue by Buchey** [Epix37/Hearthstone-Deck-Tracker#1745]
Hiho :)
I started using HDT about a week ago, my main reason to use it would be to track my arena stats, as i mostly play arena.
My internet sucks so it happens quite often, that i disconnect during a game. After reconnecting, the HDT doesnt remember which cards were played and thats ok imo. But after the match is over, the HDT doesnt count the win or lose, so my stats are f***ed up, so I end up deleting the Arena runs which arent complete. It would be great that HDT detects the outcome of the game and adds it to the stats if somehow possible.

**Comment by goldenmane** [comment]
I don't know why this is closed, the issue still remain.
