### ISSUE TITLE
Brawls not being logged

### ISSUE THREAD

**Issue by ThePsionic** [Epix37/Hearthstone-Deck-Tracker#1748]
I managed to hack together the Tavern Brawl decks using XML trickery, but logs and replays are not being saved for them.

**Comment by andburn** [comment]
Check to see if brawl is checked in stats recording options (found [here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#games-andor-stats-are-not-being-saved))

**Comment by ThePsionic** [comment]
Hah, woops. Thanks.
