### ISSUE TITLE
Forgotten Torch does not add Roaring Torch to decklist or amt of cards in deck number.

### ISSUE THREAD

**Issue by Carbohydron** [Epix37/Hearthstone-Deck-Tracker#1749]
When playing Forgotten Torch, Roaring Torch is not added to the decklist on the right side of the screen and the amount of cards left in the deck is what the deck would be if Roaring Torch was not added to the deck.

http://pastebin.com/kQsdVVKc

**Comment by Epix37** [comment]
#1739
