### ISSUE TITLE
Export function only includes basic cards

### ISSUE THREAD

**Issue by shadowdriva** [Epix37/Hearthstone-Deck-Tracker#1751]
When I use the export function only the basic cards appear.  Then I get the list stating how much it will cost to craft cards that I already have but are in other sets. I've tried different resolutions within the game and haven't found a solution. Can anyone help?

**Comment by Dark-Green** [comment]
I also have this problem.

**Comment by shadowdriva** [comment]
Make sure you are using the latest version v0.13.3. Go to options under the settings tab you can set it to automatically check for updates.
