### ISSUE TITLE
Russian encoding

### ISSUE THREAD

**Issue by HEPEBAP** [Epix37/Hearthstone-Deck-Tracker#1753]
After new update on windows 10 - 
![hdt_bug](https://cloud.githubusercontent.com/assets/15857634/11169223/813d6218-8bc2-11e5-9438-6deb862980dd.png)

it's problem in Windows, but that problem only in HDT

P.S  That problem only with title
![hdt_bug2](https://cloud.githubusercontent.com/assets/15857634/11169386/0bd8ee5c-8bc7-11e5-84a2-fe1565e8e050.png)

**Comment by Cu8eR** [comment]
It is issue in Win10 according to Google, anyway use another language

**Comment by riQQ** [comment]
See #1623.

**Comment by grounder78** [comment]
I'm using the latest beta HTD 0.13.5.
Name cards can be read, but although font is not as nice as before.
As before, there is a small bug with the symbols " - "  (hyphen)
they appear squares

my previous post #1783

![fontbug](https://cloud.githubusercontent.com/assets/1655120/11753578/eeb9b078-a056-11e5-9053-6bfb589aa17f.PNG)
