### ISSUE TITLE
HSDT not auto updating > No LoE cards

### ISSUE THREAD

**Issue by pefp2008** [Epix37/Hearthstone-Deck-Tracker#1754]
I was playing with a deck that contained LoE and HSDT showed me a "Warning: Cards not found" in reference to Reno Jackson being added to the deck.
When i tried to modify the deck in HSDT, it didn't have Reno in the cardlist, so i checked the version, and found that it was v0.11, instead of v0.13, which is weird, because i auto-updated every time, but it didn't happen for v0.12 and v0.13. It updated in a laptop i have, but not on my desktop???

I'll download the most recent version, but i find weird that it didn't auto-update as always, and as for a recommendation, there should be a manual update check, just in case auto-update didn't work.

**Comment by pefp2008** [comment]
I updated manually by downloading v0.13.3 and replacing all files in the directory.

**Comment by Epix37** [comment]
Is `options > tracker > settings > check for updates` maybe turned off for some reason?
