### ISSUE TITLE
Russian translation bugs

### ISSUE THREAD

**Issue by HellbringerOnline** [Epix37/Hearthstone-Deck-Tracker#1756]
Hi. I have this
![1](https://cloud.githubusercontent.com/assets/14059683/11183567/76203ac4-8c83-11e5-91b6-f0b3218b8761.PNG)
Windows 10.0.10586.3 64bit (12.11.2015)
Tried to change the the file encoding - no results. Others translation still works.

**Comment by riQQ** [comment]
It's a Windows 10 Bug (see #1623).
