### ISSUE TITLE
Card Errors...

### ISSUE THREAD

**Issue by Deloray** [Epix37/Hearthstone-Deck-Tracker#1759]
Hey, got problem with HDT... if i would make a priest deck and try to argus defender -> hdt crash. same with king wrynn...

**Comment by ericBG** [comment]
Can you give more details? What other programs were running at the time? What other cards is there in the deck? How many? Can you give a screenshot before the crash? 

And I assume you mean Defender of Argus and Varian Wrynn?

**Comment by Deloray** [comment]
########## 16.11.2015 15:30:13 ##########
System.UnauthorizedAccessException: Der Zugriff auf den Pfad "C:\Users\Maximilian\Desktop\Hearthstone Deck Tracker\Images\defender-of-argus.png" wurde verweigert.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   bei System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   bei System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   bei System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   bei System.Windows.Media.Imaging.BitmapSource.CompleteDelayedCreation()
   bei System.Windows.Media.Imaging.BitmapSource.get_WicSourceHandle()
   bei System.Windows.Media.Imaging.BitmapSource.get_DUCECompatiblePtr()
   bei System.Windows.Media.Imaging.BitmapSource.UpdateBitmapSourceResource(Channel channel, Boolean skipOnChannelCheck)
   bei System.Windows.Media.Imaging.BitmapSource.UpdateResource(Channel channel, Boolean skipOnChannelCheck)
   bei System.Windows.Media.Imaging.BitmapSource.AddRefOnChannelCore(Channel channel)
   bei System.Windows.Media.Imaging.BitmapSource.System.Windows.Media.Composition.DUCE.IResource.AddRefOnChannel(Channel channel)
   bei System.Windows.Media.ImageDrawing.AddRefOnChannelCore(Channel channel)
   bei System.Windows.Media.Drawing.System.Windows.Media.Composition.DUCE.IResource.AddRefOnChannel(Channel channel)
   bei System.Windows.Media.DrawingGroup.AddRefOnChannelCore(Channel channel)
   bei System.Windows.Media.Drawing.System.Windows.Media.Composition.DUCE.IResource.AddRefOnChannel(Channel channel)
   bei System.Windows.Media.DrawingImage.AddRefOnChannelCore(Channel channel)
   bei System.Windows.Media.ImageSource.System.Windows.Media.Composition.DUCE.IResource.AddRefOnChannel(Channel channel)
   bei System.Windows.Media.ImageBrush.AddRefOnChannelCore(Channel channel)
   bei System.Windows.Media.Brush.System.Windows.Media.Composition.DUCE.IResource.AddRefOnChannel(Channel channel)
   bei System.Windows.Media.RenderData.System.Windows.Media.Composition.DUCE.IResource.AddRefOnChannel(Channel channel)
   bei System.Windows.UIElement.RenderContent(RenderContext ctx, Boolean isOnChannel)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.Render(RenderContext ctx, UInt32 childIndex)
   bei System.Windows.Media.CompositionTarget.Compile(Channel channel)
   bei System.Windows.Media.CompositionTarget.System.Windows.Media.ICompositionTarget.Render(Boolean inResize, Channel channel)
   bei System.Windows.Media.MediaContext.Render(ICompositionTarget resizedCompositionTarget)
   bei System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   bei System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[15:29:55] Game: -------- Reset ---------
[15:29:55] OpponentSecrets: Cleared secrets
[15:29:56] : Checking for duplicate matches...
[15:29:56] GameEventHandler: Reset constructed importing
[15:29:56] BackupManager: Running BackupManager
[15:29:56] BackupManager: Backup for today already exists
[15:29:56] PluginManager: Loading Plugins...
[15:29:56] Helper: Checking for LIVE updates...
[15:29:56] Helper: Current version: 0.13.3.0
[15:29:56] Helper: Latest LIVE version: 0.13.3.0

########## 16.11.2015 15:30:31 ##########
System.UnauthorizedAccessException: Der Zugriff auf den Pfad "C:\Users\Maximilian\Desktop\Hearthstone Deck Tracker\Images\defender-of-argus.png" wurde verweigert.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   bei System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   bei System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   bei System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   bei System.Windows.Media.Imaging.BitmapSource.CompleteDelayedCreation()
   bei System.Windows.Media.Imaging.BitmapSource.get_WicSourceHandle()
   bei System.Windows.Media.Imaging.BitmapSource.get_DUCECompatiblePtr()
   bei System.Windows.Media.Imaging.BitmapSource.UpdateBitmapSourceResource(Channel channel, Boolean skipOnChannelCheck)
   bei System.Windows.Media.Imaging.BitmapSource.UpdateResource(Channel channel, Boolean skipOnChannelCheck)
   bei System.Windows.Media.Imaging.BitmapSource.AddRefOnChannelCore(Channel channel)
   bei System.Windows.Media.Imaging.BitmapSource.System.Windows.Media.Composition.DUCE.IResource.AddRefOnChannel(Channel channel)
   bei System.Windows.Media.ImageDrawing.AddRefOnChannelCore(Channel channel)
   bei System.Windows.Media.Drawing.System.Windows.Media.Composition.DUCE.IResource.AddRefOnChannel(Channel channel)
   bei System.Windows.Media.DrawingGroup.AddRefOnChannelCore(Channel channel)
   bei System.Windows.Media.Drawing.System.Windows.Media.Composition.DUCE.IResource.AddRefOnChannel(Channel channel)
   bei System.Windows.Media.DrawingImage.AddRefOnChannelCore(Channel channel)
   bei System.Windows.Media.ImageSource.System.Windows.Media.Composition.DUCE.IResource.AddRefOnChannel(Channel channel)
   bei System.Windows.Media.ImageBrush.AddRefOnChannelCore(Channel channel)
   bei System.Windows.Media.Brush.System.Windows.Media.Composition.DUCE.IResource.AddRefOnChannel(Channel channel)
   bei System.Windows.Media.RenderData.System.Windows.Media.Composition.DUCE.IResource.AddRefOnChannel(Channel channel)
   bei System.Windows.UIElement.RenderContent(RenderContext ctx, Boolean isOnChannel)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.Render(RenderContext ctx, UInt32 childIndex)
   bei System.Windows.Media.CompositionTarget.Compile(Channel channel)
   bei System.Windows.Media.CompositionTarget.System.Windows.Media.ICompositionTarget.Render(Boolean inResize, Channel channel)
   bei System.Windows.Media.MediaContext.Render(ICompositionTarget resizedCompositionTarget)
   bei System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   bei System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[15:30:21] Game: -------- Reset ---------
[15:30:21] OpponentSecrets: Cleared secrets
[15:30:21] : Checking for duplicate matches...
[15:30:21] GameEventHandler: Reset constructed importing
[15:30:21] BackupManager: Running BackupManager
[15:30:21] BackupManager: Backup for today already exists
[15:30:21] PluginManager: Loading Plugins...
[15:30:21] Helper: Checking for LIVE updates...
[15:30:21] Helper: Current version: 0.13.3.0
[15:30:22] Helper: Latest LIVE version: 0.13.3.0

**Comment by Deloray** [comment]
no other programms or somthing else

**Comment by Epix37** [comment]
Try either starting HDT as admin and/or manually creating all the folders ("Hearthstone Deck Tracker", "Hearthstone Deck Tracker/Files", etc) and dropping all the corresponding files in those.

**Comment by Deloray** [comment]
tried 2 times... doesnt work again. i will make a deck and if i would take the defender of argus -> crash

**Comment by Epix37** [comment]
Definitely very strange. 

Try setting the access rights for the HDT dir and all sub dirs to full rrad/write access. 

Or maybe some weird anti virus thing? Try setting Hearthstone Deck Tracker.exe as an exemption.

**Comment by ericBG** [comment]
Yeah it's very strange. The fact that the defender of argus png is disallowed when you put it into the dec but not when it's in the sidebar is certainly strange. Try deleting and copying that file back in?

**Comment by Deloray** [comment]
Found the problem... i dont know why, but four cards (png's) havnt any permisions, o.0 i gave this four png's completly new permisions for all users and admin -> work. i dont understand why exectly this four cards havnt any permisions ... but thanks a lot for ur help!
