### ISSUE TITLE
Importing constructed decks = complete mess

### ISSUE THREAD

**Issue by savier123** [Epix37/Hearthstone-Deck-Tracker#1760]
It just doesn't compute correctly..i followed the steps closely and it end up showing an incomplete deck that i did not create. 
(Real Deck)
https://gyazo.com/8fb93b27d37a7152e06d3552ef42f44c
(Incorrect results)
https://gyazo.com/4a38e432283258ccd6b6a8825f3989f3

**Comment by Cu8eR** [comment]
Have you tried change importing speed to slow?

**Comment by Epix37** [comment]
Thiis is importing, not exporting.  

Try running the constructed importing setup again under "options > tracker > importing". Druid is definitely a bit iffy though. If running the setup again doesn't help this is probably not fixable :/
