### ISSUE TITLE
Suggestion: Arena deck name, use format 20xx-mm-dd

### ISSUE THREAD

**Issue by Runean** [Epix37/Hearthstone-Deck-Tracker#1761]
The default arena deck name makes the list a mess.
If the date format was unique, like yyyy-mm-dd, then the current arena deck would always be either in the top or bottom (depending on sort).

Currently it's "Arena 15-11 04:09" right now. So as the month progresses, the deck appears lower in the list - that's fine the very first month, but as the months passes, you cannot find your current arena deck anymore (if you've switched to constructed for a time), as it sorts on the day first. 
Your current deck is just somewhere on a very long list, that for the purpose of finding it, might as well be unsorted.

**Comment by andburn** [comment]
You can customize how the arenas decks are named, go to `options > tracker > importing` and press the *Edit* button under *Arena Deck Name Template*. 
You'll want to change it to something like `{Date yyyy-MM-dd hh:mm}` then make sure to press *Save*.

**Comment by Epix37** [comment]
Additionally you can specify the deck sorting (separate for arena!) under `menu: MAIN > SORT / FILTER`.
