### ISSUE TITLE
Stat Tracking bugs

### ISSUE THREAD

**Issue by GiggliG** [Epix37/Hearthstone-Deck-Tracker#1762]
I'm seeing a bunch of bugs in the stats tracking, and have been for at least a couple weeks. The stat tracking used to be very reliable, but lately it's become very very unreliable. I'm seeing three bugs, and all of them are frequent enough to be irritating.

The most common bug is that HDT fails to record the opponent name, leaving an empty field. This happens so often that if i play 3 or more games, this will happen at least once.

The next bug is a lot less common, but still frequent enough to be noticed. Now and then when playing ranked, the game is recorded as Casual.

The final bug is the most serious. Every now and then, HDT saves a game as the wrong class. I dont know how often this happens, because its not easy to tell when it has happened. But I watched three games I played this morning, and saw it happen on two of them, in such a way that I can see what is happening.

I played against a paladin, warrior, and hunter, in that order, and looked at the stats after each game. 

After the paladin game, I looked at the stats, and it was recorded correctly (apart from missing the Opponent Name).

After the warrior game, that game was correctly recorded as warrior (no Opponent name, again), but the preceding game against Paladin had changed to warrior class.

So, I manually changed it back to paladin, and then played my third game. That game showed up as hunter, but the 2nd game (warrior) was now displayed as hunter.

So it seems like when HDT is assigning the class, if this bug occurs, it assigns the class to the current game, and the game preceding it.

In all three of these games, the opponent name was blank, so maybe there's a link between those two bugs (and that may be a way of spotting which games have the wrong class recorded).

**Comment by veri745** [comment]
I see all three of these behaviors also

**Comment by neilrqm** [comment]
I see the mode and opponent name bugs as well.  I don't see the bug with class, but I haven't changed class this week and can't remember the ground truth so I probably just haven't noticed.

I also see a few games with the mode set to "None", which don't show up on Hearthstats.  I've attached a screenshot showing my last set of games that demonstrate these bugs, and have verified that the three marked with mode "None" aren't on my game record on Hearthstats.  Also, my Power_old.log file contains the correct value for the most recent instance of the missing name (the others are too old to be in the log file).  I'm not sure how to verify that the log file contains the correct mode.

N.b. that I played a game of Tavern Brawl, probably on the 18th, and played through the new wing of LOE on the 20th.  Other than that I've only played mage in ranked mode.  

![bugs](https://cloud.githubusercontent.com/assets/6539830/11326142/eac9859c-9115-11e5-87c8-4864eac889aa.png)

**Comment by ceceita** [comment]
post the logs ?

**Comment by neilrqm** [comment]
I didn't have time to check if the logfile is clean.  Is there anything in there I need to redact before posting publicly?

**Comment by GiggliG** [comment]
IIRC the only thing in it is the path to the log file, which includes your windows login user name.
Search for that and delete it, if necessary.

**Comment by neilrqm** [comment]
OK, here is a copy of the log file from when I took that screenshot.

[Power_old.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/42528/Power_old.txt)

**Comment by veri745** [comment]
HDT log: http://pastebin.com/wXK9U9hb

Screenshot:
![wrong_class](https://cloud.githubusercontent.com/assets/5815066/11380161/09611510-92ba-11e5-89a9-589269c87c7a.PNG)

Log files zip:
http://www79.zippyshare.com/v/slEyc6Fy/file.html

**Comment by dvide** [comment]
![ulysses](https://cloud.githubusercontent.com/assets/180188/11382653/0ac634f8-92fb-11e5-84ff-b2394ef9920d.png)

Can confirm another example of this. When the game was saved without the opponent's name, the previous Paladin game (noletters) got changed to Druid. You have to exit Hearthstone and reopen it at this point or it will keep messing up your future games.

Here's the replay file, HDT log file, and Heartstone log files: http://1drv.ms/1Ly7Nco

[YouTube vid](https://www.youtube.com/watch?v=ynIaQ01Pz1Y) of the game vs Druid.

**Comment by veri745** [comment]
This is super annoying, I had no idea how many of the stats were wrong because HDT was changing the class of my opponents.  Basically makes the the win rate stats worthless

**Comment by Epix37** [comment]
Working on fixing game mode and rank detection and I have an idea what might be happening with the name. 

As long as the games have a replay, the opponents class and name can be automatically recovered from that. I will add something to do this.

**Comment by GiggliG** [comment]
That's great to know. Thanks!

When correcting class and name, for games that cant be identified (maybe some brawl/none games for instance), you maybe could add a comment to the note section of the game, to let people find them and decide what to do with them.

**Comment by Mikki79** [comment]
I have the same problems. I think this program is awesome but unfortunately it's so unreliable. You can never depend on it, you have to double check each time that it records the correct game mode and the correct ranks.

Restarting the deck tracker a few times usually fixes the issue eventually, might have to restart Hearthstone as well.
