### ISSUE TITLE
Decks and settings gone after moving OS to different drive

### ISSUE THREAD

**Issue by Arrxzon** [Epix37/Hearthstone-Deck-Tracker#1763]
Where are decks and settings stored ?
I recently ditched the OS on my HDD and upgraded to win10 with a fresh install on my SSD.
I still have all files I previously had before the reinstall on the HDD so is there a way to recover all the settings, stats and decks ? I didn't reinstall DeckTracker either I just launched it from where it was left on the HDD. Or is it just like every other program won't work without the previous OS due to some registry stuff or something.

Thanks.

**Comment by Epix37** [comment]
Data is stored under "%AppData%/HearthstoneDeckTracker" (i.e. `OLD_DRIVE:\Users\USER\AppData\Roaming\HearthstoneDeckTracker`). If you move that to the new drive you should be good.

**Comment by Arrxzon** [comment]
That's a relief, thank you.
