### ISSUE TITLE
Crash when trying to edit an arena match when opponent's class is not set

### ISSUE THREAD

**Issue by AndLen** [Epix37/Hearthstone-Deck-Tracker#1765]
I noticed a number of my matches in my arena run did not have the class set (which is an issue in itself). Trying to edit the match gives the following error:

"Must specify valid information for parsing in the string".

A crash report is also created, which is attached.

The opponents which did not have a class set were all hunters also -- but some hunter opponents *did* have their class set properly.

[Crash report 18112015-1932.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/37563/Crash.report.18112015-1932.txt)

**Comment by gardian06** [comment]
were they all Rexaar, or were some of them Aleria, and if so did it make a difference in whether it was recorded or not?

**Comment by AndLen** [comment]
Not completely sure sorry. I believe I faced one aleria during that run, but there were about 3 hunter games which caused the error. In other words, aleria may have been in one of the error games at most, but there were definitely Rexxar heroes in some of them.

**Comment by Vicas** [comment]
Just want to throw in my own crash report for this. Same issue, except the two missing ones in this run are both Paladins. Both of them crash the deck tracker; all others in this run are editable and I have not yet finished the run yet (though I likely will have by the time you see this).

[Crash report 4122015-2310.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/52725/Crash.report.4122015-2310.txt)
