### ISSUE TITLE
Stop tracking after a few seconds

### ISSUE THREAD

**Issue by Aldodzb** [Epix37/Hearthstone-Deck-Tracker#1767]
Hi,

I have installed HDT today becuase I find it an interesting tool for hearthstone.

Installed, got my account and built my deck.

The problem comes when I start a game, it shows perfectly my hand but after some seconds it stops and shows wrong info (like cards in my hand marked as played)

When i de-select and select again, it happens again, shows it right for a few seconds then stops.

Tryed another versions, same happend. Run as adm, same. 

I added my deck manually, using a file and with the constructor beta option.

Any ideas?
Regards

**Comment by culinko** [comment]
Does this still happen with the newest version?

**Comment by Aldodzb** [comment]
@culinko This is from november lol, thank you anyway for answering. I could fix it in that time. Now it works perfectly.

**Comment by culinko** [comment]
Glad to hear that you could make it work!
