### ISSUE TITLE
Import constructed for warlock

### ISSUE THREAD

**Issue by Lengl** [Epix37/Hearthstone-Deck-Tracker#1769]
# Issue:
There were detected some cards, which are not in my deck (Sacrificial pact, corruption, mortal coil)
Power Overwhelming was not detected.

### Things I've done:
0. Started HDT and Hearthstone
1. Created deck in Hearthstone (you can see it on the screenshot)
2. Saved it.
3. Went back to the main menu
4. Opened "My collection"
5. Opened this deck
6. Went straight back to the main menu
7. In HDT pressed "Import - From game: constructed (BETA)"

### HDT Version:
0.13.3.0

### Screenshot:
![2015-11-18 15-12-08](https://cloud.githubusercontent.com/assets/6824517/11240986/fd05fc4c-8e07-11e5-950e-d59e06379c39.png)

**Comment by Lengl** [comment]
Well, no, I didn't read the FAQ, my bad :( But still, the problem is with __importing__ from Hearthstone, not with exporting.

I have Windows 7 and these export settings:

### Before
![2015-11-19 01-00-42](https://cloud.githubusercontent.com/assets/6824517/11255892/df14141a-8e59-11e5-920c-588e5aed1cbe.png)

### After
![2015-11-19 01-03-17](https://cloud.githubusercontent.com/assets/6824517/11255903/f33eabb2-8e59-11e5-8132-363f9b0c6ebf.png)

And FAQ solutions didn't help :(

**Comment by riQQ** [comment]
I'm sorry, try this (see #1564):
> Try re-running the setup process: options > tracker > importing > set up constructed importing

**Comment by Lengl** [comment]
Yes! There we go, it works! Thank you, you are awesome!
