### ISSUE TITLE
inconsistent order of cards in new deck constructed.

### ISSUE THREAD

**Issue by gardian06** [Epix37/Hearthstone-Deck-Tracker#1770]
in the "new constructed deck" interface why do only class spells show up first (per mana cost) and not class creature as well. 
from the standpoint of building the deck and entering it into the program at the same time it should be class cards then neutral cards (per mana cost)
from the standpoint of entering from an already created deck in collection then it should be all cards in alphabetical order (per mana cost)
it seems a bit convoluted, and trying to have both worlds at once which is cumbersome with either method of importing a deck for tracking.

I know that the deck import function exists, but it has never worked for me in the 10 times I have tried.

**Comment by Epix37** [comment]
It's the same order as in-game.
