### ISSUE TITLE
Is it possible to use 2 decks in spectate mode?

### ISSUE THREAD

**Issue by yharbaliev** [Epix37/Hearthstone-Deck-Tracker#1774]
I am interested in the functionality of having the decks of both players tracked down and then when spectating using both of them.

This is very useful when streaming a tournament and commenting in live action about the state of the decks.

I just want to know if this is possible at the moment and if not have you thought on implementing it?

**Comment by jleclanche** [comment]
It's not possible, nor is it planned.
