### ISSUE TITLE
no games are tracked

### ISSUE THREAD

**Issue by Hellslayer6** [Epix37/Hearthstone-Deck-Tracker#1776]
hi,
i just downloaded the tracker but it does not update the overlay and does not track any game as well.
The deck is built and selected and displayed in the games overlay but it´s not updating if a card is drawn or played.
Also none of my games with active tracker appears in the games statistic.

It seems the program does not notice that there is a match running.

**Comment by riQQ** [comment]
See https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#not-working.

**Comment by Hellslayer6** [comment]
It´s still not running. the directory was already set and log.config was the same - changed it anyway to be sure. 
I´ve restarted both client and tracker and rebooted my pc. no change.

**Comment by Hellslayer6** [comment]
got it - i never reinstalled the client since alpha - some confings were still in alpha/beta mode. reinstallation worked.
