### ISSUE TITLE
Hearthstone Deck Tracker not exporting

### ISSUE THREAD

**Issue by dante0406** [Epix37/Hearthstone-Deck-Tracker#1777]
Hi there,
Up until yesterday the Deck tracker was exporting perfectly.
Then all of a sudden it just won compile the deck in game (0 cards added or cleared). However the list of the deck does appear at the side when presumably it believes its finished.

Im running windows 8 , have tried changing delay time and the compatibility options , any ideas ?

**Comment by Epix37** [comment]
Try changing to windowed/fullscreen and make sure the latter has a resolution set in game.

**Comment by dante0406** [comment]
Hi there, 
thanks for the reply, I have tried using both windowed and full screen both with a set resolution and with and without the tracking sitting on the same monitor. Still no interaction seems to be taking place

**Comment by Epix37** [comment]
See https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1853#issuecomment-189459255.

Closing this for now.
