### ISSUE TITLE
Deck Import Not Auto-Naming

### ISSUE THREAD

**Issue by lunarwolfspirit** [Epix37/Hearthstone-Deck-Tracker#1779]
Eons of versions ago, when I used to import my decks from Hearthpwn, it just automates to the given deck name and goes neatly into my tracker. 

The functionality just disappeared one day and now I seem to have to name every deck I import from Hearthpwn (but not on other sites). Is this a bug? Or are there some hidden options I have left unticked?

**Comment by Epix37** [comment]
Seems to be working fine for me via `IMPORT > FROM WEB`. Are you using the NetDeck chrome extension? That seems to have an issue with getting the name at the moment. (@n4ru)

**Comment by lunarwolfspirit** [comment]
Yes that's exactly it then. Damn.

**Comment by n4ru** [comment]
Thanks for pinging me. I fixed an issue with HearthPwn compatibility recently. Going to doublecheck the name importing.

**Comment by n4ru** [comment]
Issue should be resolved now.

**Comment by Epix37** [comment]
:+1:
