### ISSUE TITLE
when i edit a deck,i would like to clear all cards in deck,and then buld a totally new one

### ISSUE THREAD

**Issue by chucklu** [Epix37/Hearthstone-Deck-Tracker#1780]
since you give a version number to the new deck,actually i only want a single deck for a hero class.

I know ,i can delete the old deck and create a new deck. But I don't want to make it in two steps.
so,when i edit a deck,i hope there will be a button for me to clear all the cards int the deck

**Comment by ceceita** [comment]
it's no sense ..
and new decks don't have a version number.

**Comment by chucklu** [comment]
@ceceita yeah,I just want keep only one deck for a hero class
I do not want to delete the old and create a new one
The best way to do is edit the deck and clear all the cards,and build a new one

**Comment by Epix37** [comment]
Rejected. Just archive old decks if you want to keep stats.
