### ISSUE TITLE
In-game UI stays in foreground

### ISSUE THREAD

**Issue by jwok** [Epix37/Hearthstone-Deck-Tracker#1782]
I am using the current debug config from the master branch. Below is a screenshot of what I see. I'm running Windows 10. This behavior obscures other windows as well, such as MS Paint.

![untitled](https://cloud.githubusercontent.com/assets/6326039/11328196/97cd8616-9153-11e5-9bd3-1f56aa26363c.png)

**Comment by jwok** [comment]
It may be worth noting that the Hearthstone UI makes sounds on mouseover when other windows are on top of it, too.

**Comment by megablue** [comment]
it has nothing to do with HDT. It is the a technical flaw of the game engine.

**Comment by Epix37** [comment]
You can enable `options > overlay > hide if HS in background` to hide it if.. HS is in background :).

**Comment by jwok** [comment]
Hahah, alright thank you. I haven't spent too much time with the program yet :)
