### ISSUE TITLE
Card Names is broken.

### ISSUE THREAD

**Issue by grounder78** [Epix37/Hearthstone-Deck-Tracker#1783]
i use HDT last version. 
After update to Windows 10 TH2 build 10.0.10586. Card Names in Russian is broken. :(

a build of 10.0.10240 was all right

![hdt](https://cloud.githubusercontent.com/assets/1655120/11365755/ae899a0e-92b9-11e5-95b3-cd1ff798d93e.png)

**Comment by disshishkov** [comment]
:+1:

**Comment by Epix37** [comment]
It's a windows bug (affects more than just HDT). See #1623.
