### ISSUE TITLE
HDT working in windows 10?

### ISSUE THREAD

**Issue by aaaqo** [Epix37/Hearthstone-Deck-Tracker#1784]
I downloaded HDT few days ago and I can't make it work. I've googled everything and tried to do all what I can. It won't recognice played cards or played games data etc. So is it suppoused to work with win10 or is that the reason?

**Comment by andburn** [comment]
Have you tried [It's not detecting cards I or my opponent play](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#its-not-detecting-cards-i-or-my-opponent-play) section of the FAQ?

**Comment by Epix37** [comment]
Closing due to lack of feedback.
