### ISSUE TITLE
Deck tracker crashes after i try to see available plugins 

### ISSUE THREAD

**Issue by superstuff** [Epix37/Hearthstone-Deck-Tracker#1785]

**Comment by riQQ** [comment]
Could you provide more information (see https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)?

**Comment by Epix37** [comment]
Most likely this issue: https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1285#issuecomment-133160591
