### ISSUE TITLE
Arena rewards popup crashes HS + deck tracker

### ISSUE THREAD

**Issue by hyderhussain** [Epix37/Hearthstone-Deck-Tracker#1789]
Hi, ever since the new arena tracking features were added, I've had to avoid doing anything with the reward tracking window because interacting with it crashes my game and the deck tracker. 

Trying to record rewards and hitting save crashes, and just unchecking the "Show Automatically" box and trying to X out crashes as well. I've had to just X out of it without pressing anything to keep it from reacting. 

Is there a fix for this/a way to make it stop popping up? I can't find any settings option to disable it. 

Thanks.

**Comment by Epix37** [comment]
Does HDT create a crash report? If so please upload it (http://pastebin.com).

As for disabling it: you can do that under `options > tracker > general > show arena reward dialog...`.

**Comment by hyderhussain** [comment]
Oh weird, I didn't see that option because it's already unchecked. I wonder if it saved when I unchecked 'show automatically' before crashing. 

I have a logs folder, but no crash reports. I can re-enable it then let you know what the error two dialog boxes say after my next arena run.

**Comment by Epix37** [comment]
Sounds like it might have saved, yes.

The crash report folder is located with the .exe, not in appdata.

**Comment by hyderhussain** [comment]
oh, my bad. 

No crash reports since august.
