### ISSUE TITLE
Filter on tags

### ISSUE THREAD

**Issue by jesperhansson** [Epix37/Hearthstone-Deck-Tracker#1792]
A simple feature request. 
I use tags for my decks. I would be awesome if you could filter on tag names as well as deck names.

Btw: Good job with this tool :-)

**Comment by Epix37** [comment]
Check out `MAIN > SORT/FILTER` and `MAIN > QUICK FILTER` (menu bar).

Is that what you are looking for?

**Comment by jesperhansson** [comment]
Totally. I just looked everywhere else. 

From UX perspective I think the buttons are the wrong place ;-)
It should somehow be together with the search..., all, arena, constructed filters.

Thx mate
