### ISSUE TITLE
Hearthstone Tacker doesn't export

### ISSUE THREAD

**Issue by goodfellax** [Epix37/Hearthstone-Deck-Tracker#1793]
Like others reported below, the tracker stopped exporting yesterday, I exported many decks before but now it suddenly stopped working. I tried Full Screen/Windowing it or setting a resolution.. At first it clicked the 0 Mana button and didnt do anything after that.. Now it searches for the cards and it find them, but the Cursor only goes on the cards and doesn't click them so they get into the deck..
Sorry for shit english :D 

For Germans and for Epix:
Falls du mein schlechtes Englisch nicht verstehst. Mittlerweile hab ich es hinbekommen, dass der Tracker die Karten sucht und diese auch findet, nur bewegt sich der Cursor immer auf die jeweilige Karte aber fügt sie nicht hinzu, also er klickt die Karten nicht richtig an oder sowas. Hoffe du hast eine Lösung für das Problem.

MfG 
Goodfellax

**Comment by Epix37** [comment]
https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1853#issuecomment-189459255
