### ISSUE TITLE
Russian letters

### ISSUE THREAD

**Issue by Scronheim** [Epix37/Hearthstone-Deck-Tracker#1794]
Russian characters are not displayed, win 10, the latest update
http://i.imgur.com/lmjKuGf.png

**Comment by Floy3D** [comment]
Да тажа самая проблема, одни квадраты.

**Comment by Floy3D** [comment]
http://s019.radikal.ru/i605/1511/4e/fac1cd66c2af.png

**Comment by riQQ** [comment]
It's a Windows 10 error (see #1623).

**Comment by KAMAELUA** [comment]
Can you change font in your app, or upload it to app folder and use it instead of windows fonts? That way everyone will have ability to customize their font.
