### ISSUE TITLE
HDT doesn't import

### ISSUE THREAD

**Issue by RavenBHK** [Epix37/Hearthstone-Deck-Tracker#1795]
Im using windows 10, fullscreen 1920x1080

I follow all instructions for everything, I can't manually import arena, I cannot manually import decks using the step by step tutorial, when I manually make a deck the HDT doesn't show anything in game bar the deck, there is no percentages nor does it recognise what cards I have.

Sounds like a detection issue with HDT. What should I do?

**Comment by riQQ** [comment]
Try this: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#not-working
