### ISSUE TITLE
card.Type == "Heropower"

### ISSUE THREAD

**Issue by anonymous555** [Epix37/Hearthstone-Deck-Tracker#1796]
Hi:

Recently, hero powers for card.Type is now  "Heropower". Without the spaces.  However, parts of the code still use a string with spaces.  And so hero powers are not recognized.

Hearthstone Deck Tracker/Hearthstone/Card.cs

Type == "Hero Power"

and 

 if(card.Type == "Hero Power")

PowerHandler.cs

I see the no space version in the debuuger.

**Comment by Cu8eR** [comment]
You are right
