### ISSUE TITLE
import deck from web (teamarchon)

### ISSUE THREAD

**Issue by HF-Enigma** [Epix37/Hearthstone-Deck-Tracker#1807]
Is it possible to add support for teamarchon decks? For example, http://teamarchon.com/decks/view/104-aggromech-shaman

**Comment by andburn** [comment]
This doesn't look possible, unfortunately. The site uses images only, and doesn't seem to have any usable card info that the tracker can extract.

```
<li>
  <a href="#" class="card" data-cardid="211" data-original-title="" title="">
    <img src="http://cdn.teamarchon.com/images/cardbars_num/211.png" alt="">
    <div class="card-num card-num-2">2</div>
  </a>
</li>
```

**Comment by Epix37** [comment]
I sent them a message. Let's see if we can make this happen :).

**Comment by HF-Enigma** [comment]
thanks anyway

**Comment by jleclanche** [comment]
Team Archon did not get back to us, so closing this as writing an importer for them would be a hassle. Open to PRs if anyone wants to do it, though.
