### ISSUE TITLE
Carsh deck tracker when I open it

### ISSUE THREAD

**Issue by nachosanchezs** [Epix37/Hearthstone-Deck-Tracker#1810]
########## 01/12/2015 07:12:12 PM ##########
System.Configuration.ConfigurationErrorsException: Error en la inicialización del sistema de configuración ---> System.Configuration.ConfigurationErrorsException: Los datos del nivel de raíz no son válidos. línea 1, posición 1. (C:\Users\Nashoo\AppData\Local\Epix\Hearthstone_Deck_Tracker._Url_l1hb14bh3vebauj5cy2inwkhkrzwfmgj\0.1.0.0\user.config line 1) ---> System.Xml.XmlException: Los datos del nivel de raíz no son válidos. línea 1, posición 1.
   en System.Xml.XmlTextReaderImpl.Throw(Exception e)
   en System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   en System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   en System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   en System.Xml.XmlTextReaderImpl.Read()
   en System.Xml.XmlTextReader.Read()
   en System.Configuration.XmlUtil..ctor(Stream stream, String name, Boolean readToFirstElement, ConfigurationSchemaErrors schemaErrors)
   en System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   en System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   en System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   en System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   en System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(InternalConfigEventArgs e)
   en System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(String configPath, BaseConfigurationRecord configRecord)
   en System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   en System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   en System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   en System.Configuration.ConfigurationManager.GetSection(String sectionName)
   en System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   en System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   en System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   en System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   en System.Configuration.SettingsBase.get_Item(String propertyName)
   en System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   en System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   en MahApps.Metro.Controls.WindowApplicationSettings.get_Placement()
   en MahApps.Metro.Controls.WindowSettings.LoadWindowState()
   en MahApps.Metro.Controls.WindowSettings.WindowSourceInitialized(Object sender, EventArgs e)
   en System.EventHandler.Invoke(Object sender, EventArgs e)
   en System.Windows.Window.OnSourceInitialized(EventArgs e)
   en System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   en System.Windows.Window.CreateSourceWindowDuringShow()
   en System.Windows.Window.SafeCreateWindowDuringShow()
   en System.Windows.Window.ShowHelper(Object booleanBox)
   en System.Windows.Window.Show()
   en Hearthstone_Deck_Tracker.Core.Initialize()
   en Hearthstone_Deck_Tracker.App.App_OnStartup(Object sender, StartupEventArgs e)
   en System.Windows.Application.OnStartup(StartupEventArgs e)
   en System.Windows.Application.<_ctor>b__0(Object unused)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by riQQ** [comment]
Go to this path: C:\Users\<Your Windows Account>\AppData\Local\Epix\ and delete the contents of this folder (see #1786).

**Comment by nachosanchezs** [comment]
thanks :D!
