### ISSUE TITLE
Stats not uploading properly

### ISSUE THREAD

**Issue by c2mc** [Epix37/Hearthstone-Deck-Tracker#1811]
Hello,

I don't know if this has been mentioned before, but it seems that stats are only being partially recorded to the Deck Tracker. For example, the "Fat Man" deck has two versions, stats add up to 33w-24l but only 23w-20l when checking the overall stats via the STATS menu.
For the "Left4Patron" it shows the wins and losses on the main screen, but no stats whatsoever in the STATS menu.

I checked the options, they seem fine and I couldn't find an answer int he FAQ. Any suggestions?

Greetings,
C2MC

![tracker 1](https://cloud.githubusercontent.com/assets/16109954/11519510/29249386-989b-11e5-96df-b0d70d86b35f.png)
![tracker 2](https://cloud.githubusercontent.com/assets/16109954/11519508/2920e07e-989b-11e5-84bc-0366bd61dfcf.png)
![tracker 3](https://cloud.githubusercontent.com/assets/16109954/11519509/292349a4-989b-11e5-9069-374a6a152704.png)
![tracker 4](https://cloud.githubusercontent.com/assets/16109954/11519507/29206df6-989b-11e5-9535-c31fbb9c47a3.png)

**Comment by GiggliG** [comment]
Change the Mode in the top left to All, and see if the numbers change.

HDT has a bug at present where ranked games sometimes get recorded as Casual or None.

**Comment by c2mc** [comment]
Oke, apparently that's it. I wasn't aware of the game-type bug thingy.
Thank you.
