### ISSUE TITLE
No "Hearthstone Deck Tracker.exe"

### ISSUE THREAD

**Issue by Dipbob** [Epix37/Hearthstone-Deck-Tracker#1812]
Hey,

I just downloaded the HDT today, but there is no "Hearthstone Deck Tracker.exe" file to launch the program with. There is CSPROJ-file, but I can't run it. Can anyone help me with this?

**Comment by andburn** [comment]
You need the download the zip file here https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/latest

**Comment by Dipbob** [comment]
![image](https://cloud.githubusercontent.com/assets/16139963/11570149/fefbff34-99f5-11e5-8599-691ee5160c12.png)
 
I've downloaded the zip and extracted it, but there seems to be no .exe file to launch it with.

![image](https://cloud.githubusercontent.com/assets/16139963/11570169/20c26b1c-99f6-11e5-9877-b81f32268478.png)

**Comment by Dipbob** [comment]
Well I feel like a fool now. Been extracting the file for IOS. Thank you for the help!
