### ISSUE TITLE
Fix adventure game mode dection and stats recording

### ISSUE THREAD

**Issue by Epix37** [Epix37/Hearthstone-Deck-Tracker#1813]
NightKev log: http://pastebin.com/K3e0YhLw

(stats recording: stats are recorded when they are not supposed to)

**Comment by Epix37** [comment]
Can't seem to reproduce this issue (anymore?).

**Comment by culinko** [comment]
Is https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1005#issuecomment-167444142 related?
