### ISSUE TITLE
HDT not interacting with HS

### ISSUE THREAD

**Issue by Maeghis** [Epix37/Hearthstone-Deck-Tracker#1817]
Hey!

For some reason or the other, HDT does run, edits and displays decks in HUD, but neither opponent classes are recognized, cards/carddraw are not updated/interacted at all, and obviously stats arent updated either.

It worked for months, through multiple versions..., i am really at loss here

I went multiple times through all settings, and even set the hearthstone and data folders, I found nothing I could have screwed up, but maybe thats still the thing here...

any input/ideas?

yours

Zia

**Comment by Spedwards** [comment]
Have you tried [it's not detecting cards I or my opponent play](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#its-not-detecting-cards-i-or-my-opponent-play) section of the FAQ?

**Comment by no-one-at-all** [comment]
I'm having the same issue, and I checked the section that the commenter above linked to. Nothing has changed, and all the relevant boxes are ticked. Could this be related to the newest HS patch?

**Comment by riQQ** [comment]
No, it's working for me. So it's probably not a Hearthstone problem.

**Comment by no-one-at-all** [comment]
I figured I'd check back in and note that, after restarting both Hearthstone and HDT multiple times, the issue resolved. Still not sure what caused it, or how it fixed itself.
