### ISSUE TITLE
HDT has a negative interaction with the Heartharena overlay

### ISSUE THREAD

**Issue by InvictusSum** [Epix37/Hearthstone-Deck-Tracker#1819]
Hi all, I am trying to use both HDT and the HearthArena overlay, and they both seem to require different config.log settings. 

Whenever I launch the HearthArena overlay, HDT stops recognising cards played. Once I replace it with the config.log downloaded from the FAQ page, the problem is fixed, but the next time I launch the HearthArena app, it tells me to restart Hearthstone to finish setup - presumably to rewrite config.log so it's  incompatible with HDT. 

I want to record my arena games on HDT so I can review the replay, but I also want to use the HearthArena draft assistant. I could do the draft, then shut HS+Heartharena and manually change config.log back, but that's a pain in the ass every time I do an arena run. Any thoughts on how to fix? Is there a config.log configuration that will please both?

Also posted on HearthArena's subreddit: https://www.reddit.com/r/HearthArena/comments/3vlcg4/heartharena_overlay_interacts_negatively_with/

**Comment by Epix37** [comment]
Is this a new problem? I think it used to work.


I'm sure we can figure out a solution here. 
@heartharena what log.config settings does your app require?

**Comment by InvictusSum** [comment]
Thanks Epix, over on the Reddit thread HearthArena said he'd get in touch with you.

**Comment by jleclanche** [comment]
HA says this was fixed.
