### ISSUE TITLE
Canceling deck editing changes selected deck version back to v1.0

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#1822]
The bug "Fixed an issue where canceling deck editing could cause unintended changes of selected deck versions." supposedly fixed in "Release v0.12.2" still exists for me.

When I edit any deck with multiple versions, then cancel out of editing, then the selected version changes back to v1.0. Also, the class that I'm currently on, and the class to the left of the current class, become both selected when I cancel out of deck editing, for some reason.

**Comment by riQQ** [comment]
I can confirm this. I edited a constructed deck with version 1.1 selcted and filter set to mage. After cancelling the editing, the filter was set to Mage and Rogue and the version was set to 1.0.

**Comment by Epix37** [comment]
Tried as few times now, I am not able to reproduce this. 

As the class being selected there: that's most likely the class of the currently active deck.

**Comment by riQQ** [comment]
While I have a rogue arena deck in use, I filter by mage and edit a deck with version 1.1. Then I immediately cancel editing and the bug occurs.

**Comment by Epix37** [comment]
Not sure what I'm doing "wrong" then... stays on 1.1 for me.

**Comment by riQQ** [comment]
Your deck in use has to have a version != selected version of the edited deck.
