### ISSUE TITLE
Graphical bug

### ISSUE THREAD

**Issue by LindenKriesa** [Epix37/Hearthstone-Deck-Tracker#1823]
Small and minor issue, but the picture in the decks for animated armor and ethereal conjurer are flipped, as seen here. http://prntscr.com/9aw620 Minor issue, but i thought I'd report it.

**Comment by Epix37** [comment]
Fixed with https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/7f9361dd73f227060a7b7cbb71312052c5d6f016.
