### ISSUE TITLE
Cannot open Heartstone Deck Tracker (crash report inside)

### ISSUE THREAD

**Issue by hschampion101** [Epix37/Hearthstone-Deck-Tracker#1824]
Whenever I load up the tracker it says Method not found:VoidSystem.Diagnostics.Tracing.FrameworkEventSource.BeginGetResponse(System.Object, System.String)'.

Crash Report - 
[Crash report 6122015-32.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/53093/Crash.report.6122015-32.txt)

**Comment by riQQ** [comment]
Do you have Windows 8.1? Then install these updates:
> Upgrade to windows 8.1 for x64-based Systems (KB3063843)
Upgrade to windows 8.1 for x64-based Systems (KB3068708)

If not, try installing .NET Framework 4.6

**Comment by hschampion101** [comment]
Thanks riQQ, i installed .NET Framework and it worked.
