### ISSUE TITLE
Images Folder not found

### ISSUE THREAD

**Issue by thagat** [Epix37/Hearthstone-Deck-Tracker#1825]
Hi, I just downloaded the zip file (version 0.13.3) and it crashed when I run the .exe file.

The problem wast that it could not find the following folder: C:\Users\<my_user>\Downloads\Hearthstone.Deck.Tracker-v0.13.3\Images\HearthstoneDeckTracker.ico

The problem is that The images folder was within another folder called Hearthstone.Deck.Tracker:

C:\Users\<my_user>\Downloads\Hearthstone.Deck.Tracker-v0.13.3\Hearthstone.Deck.Tracker\

When I moved the contents of the folder named Hearthstone.Deck.Tracker into it's parent folder, the programed runned perfectly

Here is the error log. 

########## 06-12-2015 8:45:52 ##########
System.Windows.Markup.XamlParseException: Se produjo una excepción al proporcionar un valor en 'System.Windows.Baml2006.TypeConverterMarkupExtension'. ---> System.IO.DirectoryNotFoundException: No se puede encontrar una parte de la ruta de acceso 'C:\Users\Usuario Msi\Downloads\Hearthstone.Deck.Tracker-v0.13.3\Images\HearthstoneDeckTracker.ico'.
   en System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   en System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   en System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   en System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   en MS.Internal.AppModel.ContentFilePart.CriticalOpenFile(String filename)
   en MS.Internal.AppModel.ContentFilePart.GetStreamCore(FileMode mode, FileAccess access)
   en System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
   en System.IO.Packaging.PackWebResponse.CachedResponse.GetResponseStream()
   en System.IO.Packaging.PackWebResponse.GetResponseStream()
   en System.IO.Packaging.PackWebResponse.get_ContentType()
   en System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   en System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   en System.Windows.Media.Imaging.BitmapFrame.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy)
   en System.Windows.Media.ImageSourceConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   en System.Windows.Baml2006.TypeConverterMarkupExtension.ProvideValue(IServiceProvider serviceProvider)
   en MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   en System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   en System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   en System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   en Hearthstone_Deck_Tracker.LoginWindow.InitializeComponent()
   en Hearthstone_Deck_Tracker.LoginWindow..ctor()
   en Hearthstone_Deck_Tracker.Core.Initialize()
   en Hearthstone_Deck_Tracker.App.App_OnStartup(Object sender, StartupEventArgs e)
   en System.Windows.Application.OnStartup(StartupEventArgs e)
   en System.Windows.Application.<.ctor>b__1(Object unused)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Epix37** [comment]
See https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/2201#issuecomment-195804378
