### ISSUE TITLE
Region "china" lost in "edit game "and "add new game"

### ISSUE THREAD

**Issue by everchump** [Epix37/Hearthstone-Deck-Tracker#1830]
I use the HDT v0.13.4_pre1

Opp. name didn't appear in the Games of States ，so i try the "Edit Game" ,it works the same as "Add new game". After adding the Opp. name，my region changed to "US" . 
![Lost china region](http://i.imgbox.com/bz76n6r7.png)
I think the title should be "Edit game" ,because i use the "edit game" .

**Comment by riQQ** [comment]
@Epix37 you overlooked the wrong dialog title. It should be `Edit game` instead of `Add new game`.

**Comment by Epix37** [comment]
Should be the same dialog, is it not?

**Comment by riQQ** [comment]
The dialog for editing a game shouldn't be named `Add new game`.

**Comment by Epix37** [comment]
Oh.. yea I completely missed that.
