### ISSUE TITLE
Doesn't accept HS install path

### ISSUE THREAD

**Issue by pcsbx** [Epix37/Hearthstone-Deck-Tracker#1831]
Went to config, pasted in HS installation path. It's confirmed via BattleNet installation data. Launched HDT. Same as before. Tried with final \ and without. Double and triple checked path, config line, that HDT wasn't running during config mods etc. Every time I launch HDT it tells me it cannot find the installation folder and helpfully reminds me that I can't use HDT unless I have HS installed.

<HearthstoneDirectory>D:\Downloads\Hearthstone\Hearthstone\</HearthstoneDirectory> should be the correct entry and it's what I have in the config atm.

Related but different: #990

EDIT: works now. May have been connected to BLZBNTAGT00000843, after Battle.net Scan & Repair both HS and HDT seem to work perfectly.

**Comment by Epix37** [comment]
Good to hear it's working now. Thank you for posting your solution.
