### ISSUE TITLE
HearthstoneDeckTracker/Plugins is not there, How do fix?

### ISSUE THREAD

**Issue by Lightextinct** [Epix37/Hearthstone-Deck-Tracker#1832]
This is all that is there 
![screenshot 281](https://cloud.githubusercontent.com/assets/16214983/11671283/052e09be-9dbc-11e5-9ba3-08cdf4d8fc5f.png)

**Comment by riQQ** [comment]
Plugins have to be downloaded separately. You can just create the folder for the plugins and add the plugins of your choice to sub folders.

**Comment by Lightextinct** [comment]
Thanks that worked :D
