### ISSUE TITLE
all cards show up as "Unknown" please help!

### ISSUE THREAD

**Issue by Lightextinct** [Epix37/Hearthstone-Deck-Tracker#1834]
So I just managed to get the arena helper plugin and now all the cards in every deck just show up as unknown but they still show the quantity of the card in the deck :/
![screenshot 282](https://cloud.githubusercontent.com/assets/16214983/11672265/dba94ac4-9dc3-11e5-9509-3afec1c8a5af.png)

Is this a known bug?

**Comment by Epix37** [comment]
You are most likely missing some files. Try downloading the latest version again ([here](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.13.3)) and see if that fixes it.

**Comment by Lightextinct** [comment]
That worked, thank you very much :3
