### ISSUE TITLE
Downloading saving the Application as an XML file

### ISSUE THREAD

**Issue by Godzofwar111** [Epix37/Hearthstone-Deck-Tracker#1835]
The title says it all. I've downloaded the deck tracker .rar file, I extract it to the folder I want, and when I open it. I get Hearthstone Deck Tracker.exe as one of the files, but instead of this file being an application, the file is an XML Configuration File. If someone could help with this issue it would be most appreciated.

**Comment by riQQ** [comment]
You are probably opening `Hearthstone Deck Tracker.exe.config`. There should be another file named `Hearthstone Deck Tracker.exe`

**Comment by Epix37** [comment]
Also make sure [this](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/download/v0.13.3/Hearthstone.Deck.Tracker-v0.13.3.zip) is the zip you downloaded.

**Comment by Godzofwar111** [comment]
![fuck this](https://cloud.githubusercontent.com/assets/16218205/11694319/12273830-9e6f-11e5-973b-5a5b880bc1ac.png)  This is all that I have, after downloading exactly what was linked. I don't understand why it's being saved as this xml config file

**Comment by riQQ** [comment]
It isn't saved as xml config file. This is an additional file, that comes with the download. The Exe is probably deleted by an antivirus.

**Comment by Godzofwar111** [comment]
What would I do to stop that riQQ? Or how can I find the executable?

**Comment by riQQ** [comment]
Which antivirus program do you use? Are there any messages after downloading HDT?

**Comment by Godzofwar111** [comment]
There is not... I don't run an antivirus.. It just gets downloaded like that

**Comment by riQQ** [comment]
How big is the zip archive of the current version after downloading?

**Comment by jleclanche** [comment]
Closing due to lack of feedback.
