### ISSUE TITLE
HDT won't launch

### ISSUE THREAD

**Issue by Reroid** [Epix37/Hearthstone-Deck-Tracker#1836]
I've had a problem with HDT since yesterday where it just crashed all of a sudden and after that i couldn't seem to open it. It gives me a crash report like this. Does anybody know what to do?
[Crash report 9122015-1045.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/56590/Crash.report.9122015-1045.txt)

**Comment by Epix37** [comment]
Delete this folder `C:\Users\Bruger\AppData\Local\Epix` and it should work again.

**Comment by Reroid** [comment]
That didn't work. It's telling me there is an invalid sign in the used coding, but i can't seem to find where that should be. I've tried to find the file several times but i just can't find it.

**Comment by riQQ** [comment]
Did you delete the whole folder as Epix described?

**Comment by Reroid** [comment]
Yes i did

**Comment by riQQ** [comment]
Could you post your log or a screenshot, please?
