### ISSUE TITLE
Trying to sign in on a new device

### ISSUE THREAD

**Issue by InsaneInsanity13** [Epix37/Hearthstone-Deck-Tracker#1838]
So I got HDT on my desktop and it works great, I really like the application. The only problem now is that I have downloaded it on to my laptop and when I try to sign into my account it gives me an error message that reads: 

Method not found: 'Void
System.Diagnostics.Tracing.FrameworkEventSource.BeginGetRequestStream(System.Object, System.String)'.

I even decided I didn't mind having separate stats for my decks on my different devices and attempted to just create a different account with a new email but it gives me the same error. I have fully deleted and re-installed the files multiple time and it still hasn't worked. Is there anything I can do to fix this?

**Comment by riQQ** [comment]
See #1633.
