### ISSUE TITLE
Card names truncated after exporting as image

### ISSUE THREAD

**Issue by culinko** [Epix37/Hearthstone-Deck-Tracker#1839]
I talked about this some time ago on IRC, but I figured out I that should create a ticket as well, so we won't forget about it. The issue is: After exporting your deck, the card text of some of the cards will get truncated if the card has a long name. The ideal solution would be to use the same properties as the HS client is using (because the info is there). However it's not an easy task to do for all card images at once.

![epsopvk](https://cloud.githubusercontent.com/assets/11700272/11693646/46385a3c-9ea6-11e5-869a-e53dcb43ed91.png)

**Comment by Epix37** [comment]
The same thing actually happens in the overlay and player/opp windows.
