### ISSUE TITLE
ranked games recorded as casual games

### ISSUE THREAD

**Issue by funkyogre** [Epix37/Hearthstone-Deck-Tracker#1842]
all ranked games I played , recorded as causal games in deck games mode, no matter I relog or restart hearthstone , problem still exist

**Comment by Epix37** [comment]
This is with the v0.13.4 pre-release I assume?

Could you post a screenshot of hearthstone in a ranked game?

**Comment by culinko** [comment]
This happened to me as well (didn't happen before at all). Logs (first 2 matches were correctly marked as ranked): http://s000.tinyupload.com/index.php?file_id=07888480556190733546.

**Comment by Epix37** [comment]
@culinko's case should be fixed with 0.13.5

Please let me know if this still is an issue. I think some resolutions (black borders at the bottom and top) might have problems.

**Comment by funkyogre** [comment]
yes , v0.13.4 pre-release 
![1449810527370](https://cloud.githubusercontent.com/assets/16236747/11736382/958f6bbc-a008-11e5-8d4c-8df23fb2ebce.jpg)  I changed all "casual" to "ranked"  manually.
