### ISSUE TITLE
can not use it. crash when i wanna make my first new deck!

### ISSUE THREAD

**Issue by Princenin0** [Epix37/Hearthstone-Deck-Tracker#1843]
Never used this tracker. always when i wanna make my first deck it crashd

System.MissingMethodException: Methode nicht gefunden: "Void System.Diagnostics.Tracing.FrameworkEventSource.BeginGetResponse(System.Object, System.String)".
   bei System.Net.FileWebRequest.BeginGetResponse(AsyncCallback callback, Object state)
   bei System.Net.FileWebRequest.GetResponse()
   bei MS.Internal.WpfWebRequestHelper.GetResponse(WebRequest request)
   bei System.Windows.Media.ColorContext.Initialize(Uri profileUri, Boolean isStandardProfileUriNotFromUser)
   bei System.Windows.Media.ColorContext..ctor(PixelFormat pixelFormat)
   bei System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   bei System.Windows.Media.Imaging.BitmapSource.CompleteDelayedCreation()
   bei System.Windows.Media.Imaging.BitmapSource.get_WicSourceHandle()
   bei System.Windows.Media.Imaging.BitmapSource.get_DUCECompatiblePtr()
   bei System.Windows.Media.Imaging.BitmapSource.UpdateBitmapSourceResource(Channel channel, Boolean skipOnChannelCheck)
   bei System.Windows.Media.Imaging.BitmapSource.UpdateResource(Channel channel, Boolean skipOnChannelCheck)
   bei System.Windows.Media.Imaging.BitmapSource.AddRefOnChannelCore(Channel channel)
   bei System.Windows.Media.Imaging.BitmapSource.System.Windows.Media.Composition.DUCE.IResource.AddRefOnChannel(Channel channel)
   bei System.Windows.Media.ImageDrawing.AddRefOnChannelCore(Channel channel)
   bei System.Windows.Media.Drawing.System.Windows.Media.Composition.DUCE.IResource.AddRefOnChannel(Channel channel)
   bei System.Windows.Media.DrawingGroup.AddRefOnChannelCore(Channel channel)
   bei System.Windows.Media.Drawing.System.Windows.Media.Composition.DUCE.IResource.AddRefOnChannel(Channel channel)
   bei System.Windows.Media.DrawingImage.AddRefOnChannelCore(Channel channel)
   bei System.Windows.Media.ImageSource.System.Windows.Media.Composition.DUCE.IResource.AddRefOnChannel(Channel channel)
   bei System.Windows.Media.ImageBrush.AddRefOnChannelCore(Channel channel)
   bei System.Windows.Media.Brush.System.Windows.Media.Composition.DUCE.IResource.AddRefOnChannel(Channel channel)
   bei System.Windows.Media.RenderData.System.Windows.Media.Composition.DUCE.IResource.AddRefOnChannel(Channel channel)
   bei System.Windows.UIElement.RenderContent(RenderContext ctx, Boolean isOnChannel)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.UpdateChildren(RenderContext ctx, ResourceHandle handle)
   bei System.Windows.Media.Visual.RenderRecursive(RenderContext ctx)
   bei System.Windows.Media.Visual.Render(RenderContext ctx, UInt32 childIndex)
   bei System.Windows.Media.CompositionTarget.Compile(Channel channel)
   bei System.Windows.Media.CompositionTarget.System.Windows.Media.ICompositionTarget.Render(Boolean inResize, Channel channel)
   bei System.Windows.Media.MediaContext.Render(ICompositionTarget resizedCompositionTarget)
   bei System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   bei System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[21:45:03] LogReaderManager: LogReaders could not be stopped, stop already in progress.
[21:45:03] Game: -------- Reset ---------
[21:45:03] Player Name: 
[21:45:03] Opponent Name: 
[21:45:03] OpponentSecrets: Cleared secrets
[21:45:04] : Checking for duplicate matches...
[21:45:04] GameEventHandler: Reset constructed importing
[21:45:04] BackupManager: Running BackupManager
[21:45:04] BackupManager: Backup for today already exists
[21:45:04] PluginManager: Loading Plugins...
[21:45:04] Helper: Checking for LIVE updates...
[21:45:04] Helper: Current version: 0.13.4.0
[21:45:04] LogReader: Current region: EU
[21:45:05] UpdateOverlay: Refreshed overlay topmost status
[21:45:05] UpdateNews: Error loading news: System.Net.WebException: Ausnahmefehler während einer WebClient-Anforderung. ---> System.MissingMethodException: Methode nicht gefunden: "Void System.Diagnostics.Tracing.FrameworkEventSource.BeginGetResponse(System.Object, System.String)".
   bei System.Net.HttpWebRequest.BeginGetResponse(AsyncCallback callback, Object state)
   bei System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream, CompletionDelegate completionDelegate, AsyncOperation asyncOp)
   bei System.Net.WebClient.DownloadStringAsync(Uri address, Object userToken)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Hearthstone_Deck_Tracker.Utility.NewsUpdater.<UpdateAsync>d__1.MoveNext()

########## 09.12.2015 21:45:19 ##########
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Hearthstone_Deck_Tracker.Windows.MainWindow.<Window_Closing>d__1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[21:45:03] LogReaderManager: LogReaders could not be stopped, stop already in progress.
[21:45:03] Game: -------- Reset ---------
[21:45:03] Player Name: 
[21:45:03] Opponent Name: 
[21:45:03] OpponentSecrets: Cleared secrets
[21:45:04] : Checking for duplicate matches...
[21:45:04] GameEventHandler: Reset constructed importing
[21:45:04] BackupManager: Running BackupManager
[21:45:04] BackupManager: Backup for today already exists
[21:45:04] PluginManager: Loading Plugins...
[21:45:04] Helper: Checking for LIVE updates...
[21:45:04] Helper: Current version: 0.13.4.0
[21:45:04] LogReader: Current region: EU
[21:45:05] UpdateOverlay: Refreshed overlay topmost status
[21:45:05] UpdateNews: Error loading news: System.Net.WebException: Ausnahmefehler während einer WebClient-Anforderung. ---> System.MissingMethodException: Methode nicht gefunden: "Void System.Diagnostics.Tracing.FrameworkEventSource.BeginGetResponse(System.Object, System.String)".
   bei System.Net.HttpWebRequest.BeginGetResponse(AsyncCallback callback, Object state)
   bei System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream, CompletionDelegate completionDelegate, AsyncOperation asyncOp)
   bei System.Net.WebClient.DownloadStringAsync(Uri address, Object userToken)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Hearthstone_Deck_Tracker.Utility.NewsUpdater.<UpdateAsync>d__1.MoveNext()

crash report

**Comment by riQQ** [comment]
See #1824.
