### ISSUE TITLE
Russian font not displayed correctly

### ISSUE THREAD

**Issue by filord** [Epix37/Hearthstone-Deck-Tracker#1844]
When I change the language to Russian

http://savepic.su/6699764.png

before i download a new version everything was ok

**Comment by riQQ** [comment]
See #1623. This is fixed in the next release.

**Comment by grounder78** [comment]
I'm using the latest beta HTD 0.13.5.
Name cards can be read, but although font is not as nice as before.
As before, there is a small bug with the symbols " - " (hyphen)
they appear squares

my previous post #1783
![fontbug](https://cloud.githubusercontent.com/assets/1655120/11753693/b0871f9c-a057-11e5-94e1-19f11a88fbc0.PNG)
