### ISSUE TITLE
Crash - System.IO.FileFormatException

### ISSUE THREAD

**Issue by Schmacher** [Epix37/Hearthstone-Deck-Tracker#1845]
[Crash report 11122015-116.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/58342/Crash.report.11122015-116.txt)

Help me

I using .net framework 4.6

**Comment by irufus** [comment]
@Schmacher do you have the font Belwe Bd BT installed?

**Comment by Epix37** [comment]
Please try the [v0.13.5 pre-release](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.13.5) and see if you still have the issue.
