### ISSUE TITLE
Crashes on opening program

### ISSUE THREAD

**Issue by QuentinX5** [Epix37/Hearthstone-Deck-Tracker#1846]
I had just installed League of Legends on my PC which was doing .NET Framework installs, so that may be the issue. I attempted clearing out my HearthstoneDeckTracker AppData folder, as the issue was referring to a file located in there, but the issue came back after starting the program again.

[Crash report 10122015-1124.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/58614/Crash.report.10122015-1124.txt)

**Comment by riQQ** [comment]
Did you delete this folder: `C:\Users\quent\AppData\Local\Epix`?

**Comment by QuentinX5** [comment]
I did not try that. Going into and deleting that folder seems to have allowed the program to function normally.
