### ISSUE TITLE
day of games missing

### ISSUE THREAD

**Issue by Tenemo** [Epix37/Hearthstone-Deck-Tracker#1851]
I'm missing all the ranked games played since 9 Dec 23:42 (I assume 10 Dec 00:00, because that's simply the last game recorded), yesterday in the evening they were still there, for instance, my "Heavy Secret" deck had 20-11 stats (I discussed that with a friend on Facebook and I still have that in chat) and today they just disappeared: "NO STATS". Arena games got recorded and they're still there, but any other are gone. It's not a major issue because that's just one day, but still.

![screenshot](https://cloud.githubusercontent.com/assets/235410/14047391/44de3ed2-f2b0-11e5-8cbf-e76bf013a05e.jpg)

**Comment by Epix37** [comment]
Possibly the same as #1553? If so, should be fixed.
