### ISSUE TITLE
Can't find Hearthstone Deck Tracker.exe

### ISSUE THREAD

**Issue by Dankism** [Epix37/Hearthstone-Deck-Tracker#1854]
I decided to Download the Hearthstone Deck Tracker and after I extracted the Zip version and followed the instructions it required me to open this "Hearthstone Deck Tracker.exe" I looked through the file and could not find it. I found something called "HDTHelper.exe" I tried to open this but the Command Prompt opens for a split second then closes. I would appreciate it if I could start using the Hearthstone Deck Tracker by someone helping me.

**Comment by andburn** [comment]
You have probably accidentally downloaded the source code. You need to get the *Hearthstone.Deck.Tracker* zip file from this address https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/latest

**Comment by Dankism** [comment]
Oh my god, I can't thank you enough for this. I'm also surprised at how stupid I am.
