### ISSUE TITLE
Win/loss rate vs each DECK

### ISSUE THREAD

**Issue by theanine** [Epix37/Hearthstone-Deck-Tracker#1860]
Currently it seems there's only support for "Win/loss rate vs each class" -- this doesn't mean much when there are classes that have wildly different decks (i.e. Freeze Mage vs Tempo Mage).

**Comment by Epix37** [comment]
I think there was an issue on this somewhere... can't find it.

Either way, this is a nice idea for the constructed stats overhaul.

**Comment by Epix37** [comment]
Found it - dope of #2014.
