### ISSUE TITLE
Image Swap

### ISSUE THREAD

**Issue by AnonymousUser52** [Epix37/Hearthstone-Deck-Tracker#1862]
I was recently using this while picking an arena, and when I finished and it auto-imported the decklist, everything was fine except for one problem. While the cards had been recorded correctly, "Animated Armor" had the image for "Ethereal Conjurer", and vice versa. I only noticed the swap because I drafted both, but I suppose it could be two seperate bugs. In any case, you should probably fix it next patch.

**Comment by riQQ** [comment]
See #1823.

**Comment by AnonymousUser52** [comment]
Ah, ok.
