### ISSUE TITLE
Option 'Don't Reset Decks After Game' is being ignored

### ISSUE THREAD

**Issue by Fyrestrom** [Epix37/Hearthstone-Deck-Tracker#1863]
Issue began after updating to v0.13.5, decks reset whether option is checked or not.

**Comment by Epix37** [comment]
Seems to be working fine for me. Can you reproduce this and post the log? [See here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)

**Comment by Fyrestrom** [comment]
I tried to upload my log file but Pastebin said it was too large for a free user. So I decided to delete the log file and play a game to repopulate it. The game did not reset this time. Maybe it was a problem with the log file?

**Comment by Fyrestrom** [comment]
The problem is back.
http://pastebin.com/mXAEiiJ7

**Comment by Epix37** [comment]
See #1919.

**Comment by Fyrestrom** [comment]
I do not have the option to 'hide in menu' selected if that makes a difference.
