### ISSUE TITLE
Cant start the app

### ISSUE THREAD

**Issue by Insanityxt** [Epix37/Hearthstone-Deck-Tracker#1866]
Hello! I downloaded your app from the link you gave at another issue just to be sure but I still get this error when I try to start the app ? Can I get any help ?
![error](https://cloud.githubusercontent.com/assets/16295095/11792571/70b8831a-a2af-11e5-971a-c18845fca262.png)

**Comment by riQQ** [comment]
Try reinstalling or repairing (if reinstalling isn't possible) the .NET framework.

**Comment by Insanityxt** [comment]
Sorry but how do I do this ?

**Comment by riQQ** [comment]
https://knowledge.autodesk.com/support/autocad/troubleshooting/caas/sfdcarticles/sfdcarticles/How-to-remove-and-reinstall-the-Microsoft-NET-Framework.html

**Comment by Insanityxt** [comment]
It worked. Thank you a lot and happy holidays!

**Comment by riQQ** [comment]
Glad it worked. Thank you and happy holidays to you, too.
