### ISSUE TITLE
The active player is incorrectly set to ActivePlayer.Opponent for the player's first turn if the opponent is going second

### ISSUE THREAD

**Issue by theAprel** [Epix37/Hearthstone-Deck-Tracker#1867]
[9:04:55 PM] Opponent Draw: id=37, cardId=, cardName=, turn=0
[9:04:55 PM] Opponent Draw: id=51, cardId=, cardName=, turn=0
[9:04:55 PM] Opponent Draw: id=55, cardId=, cardName=, turn=0
[9:04:55 PM] Opponent Draw: id=62, cardId=, cardName=, turn=0
[9:04:55 PM] Opponent Draw: id=68, cardId=, cardName=, turn=0
**[9:04:55 PM] Opponent Coin: id=68, cardId=, cardName=, turn=0, mark=Coin, created=true**
[9:04:55 PM] GameEventHandler: Playing against Priest
**[9:05:13 PM] GameEventHandler: --- Opponent turn 1 ---**
**[9:05:17 PM] Player Draw: id=26, cardId=GVG_002, cardName=Snowchugger, turn=0**
**[9:05:25 PM] GameEventHandler: --- Opponent turn 1 ---**
[9:05:25 PM] Opponent Draw: id=50, cardId=, cardName=, turn=1
[9:05:27 PM] Opponent Play: id=55, cardId=CS2_235, cardName=Northshire Cleric, turn=1
[9:05:30 PM] GameEventHandler: --- Player turn 2 ---
[9:05:30 PM] Player Draw: id=33, cardId=GVG_085, cardName=Annoy-o-Tron, turn=1

**Comment by theAprel** [comment]
I've traced this to https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/d2bf3bd8a36374fdac36be8d15fedd52979bc949/Hearthstone%20Deck%20Tracker/LogReader/Handlers/TagChangeHandler.cs#L383 :

    var activePlayer = game.Entities[id].IsPlayer ? ActivePlayer.Player : ActivePlayer.Opponent;

On turn 1, both `IsPlayer` and `IsOpponent` are set to `false` in the referenced `Entity`, so this conditional is always false and sets ActivePlayer.Opponent as the active player. I'll try to see where in the code the `Entity` is initialized incorrectly.

**Comment by theAprel** [comment]
This is as far as I'm able to determine. The debugger shows that the Tags attached to `Entities[id]` are a lot different on turn 1 from subsequent turns. On turn 1, the tags are PLAYSTATE, CURRENT_PLAYER, and if the game is outside of Solo Adventure, also TIMEOUT. It seems that the `IsPlayer` and `IsOpponent` fields are set based on the presence of the PLAYER_ID tag, which is absent on the first turn for some reason. Consequently, these fields are not set, and the conditional in [TagChangeHandler.cs](https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/d2bf3bd8a36374fdac36be8d15fedd52979bc949/Hearthstone%20Deck%20Tracker/LogReader/Handlers/TagChangeHandler.cs#L383) is always false.

**Comment by Epix37** [comment]
I think this has no negative consequences aside from something wrong being logged, or have you come across anything?

**Comment by theAprel** [comment]
@Epix37 `Hearthstone_Deck_Tracker.API.OnTurnStart` passes the incorrect ActivePlayer enum to registered callbacks on the first turn if the player went first.

**Comment by FrenchyPoP** [comment]
@Epix37 The only consequence I have noticed with this is, the timer also counts up for the opponent on turn 1 no matter who goes first.

**Comment by theAprel** [comment]
This bug has been fixed. I believe https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/ad664c87d1d9a49c36ea1ef8e24a412a5dd7e636 is the responsible commit.
