### ISSUE TITLE
Opened program one time. Won't open again.

### ISSUE THREAD

**Issue by druidlyshy** [Epix37/Hearthstone-Deck-Tracker#1868]
I can't seem to get the tracker to open. I have tried uninstalling it and downloading it again, but still I cannot open it.

I created a short cut to it on my desktop and tried to open it from there and have also tried opening it from where it is downloaded. My mouse shows it loading for a minute, then done and nothing happens.

**Comment by Epix37** [comment]
No error message of any sort? Any change after rebooting?

**Comment by WhiteHammer66** [comment]
I have the same problem any help?

**Comment by jleclanche** [comment]
Closing due to lack of feedback.
