### ISSUE TITLE
HDT is only recording my last played game

### ISSUE THREAD

**Issue by tgfish** [Epix37/Hearthstone-Deck-Tracker#1870]
I only have one deck loaded (it's Active), I just played 3 games. The counter is reset after each game so it only appears I've played 1 game.

First game I won, counter showed 1-0.
Second game I lost, counter reset to 0-1.
Third game I lost, counter reset to 0-1.

If there's any logs/etc I can upload to help let me know.

I'm playing on a Surface Pro 4 running Windows 10 but Hearthstone is running in Windows 7 compatibility mode.

**Comment by Epix37** [comment]
Is this with v0.13.3? If so, please see if you still have that issue with the latest pre-release: [v0.13.5](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.13.5).

**Comment by tgfish** [comment]
Sorry for the delay, I'll check today

**Comment by Epix37** [comment]
Closing due to lack of feedback.
