### ISSUE TITLE
DeckTracker crashes when enable Arena Helper

### ISSUE THREAD

**Issue by rapid383** [Epix37/Hearthstone-Deck-Tracker#1871]
I've recently resumed playing Hearthstone and came across HS dectracker + Arena Helper.  I've followed the instructions on the website: https://github.com/Epix37/Hearthstone-Deck-Tracker to install both programs.  However, as seen in my attached screenshots, the deck tracker seems to crash when I turn on Arena Helper.  
![hs 1](https://cloud.githubusercontent.com/assets/16308072/11815609/6ab31e20-a387-11e5-8a08-18818a478e05.jpg)
![hs_2](https://cloud.githubusercontent.com/assets/16308072/11815501/f67d6a38-a386-11e5-80b6-c7bf081b8370.jpg)
![hs_3](https://cloud.githubusercontent.com/assets/16308072/11815615/75ba2052-a387-11e5-8f11-b5874672b5b4.jpg)

Can you please see what I need to do to fix this problem?

**Comment by ceceita** [comment]
i dont know if that fixes it , but 0.6.4 is out ...
https://github.com/rembound/Arena-Helper/releases

**Comment by andburn** [comment]
@rapid383 if you have a crash log post it, it should be in a *Crash Reports* folder where you installed the tracker. If not post the `hdt_log.txt` found in `%AppData%\HearthstoneDeckTracker` (directly after you experience a crash).

**Comment by rapid383** [comment]
No Crash Reports folder, and no hdt_log and no %AppData% anywhere in my PC  too.

**Comment by andburn** [comment]
You can copy paste `%AppData%\HearthstoneDeckTracker\Logs` into windows explorer address bar and press return to go to the straight to the log folder. Or navigate to _C:\Users\YOUR_USERNAME\AppData\Roaming\HearthstoneDeckTracker\Logs_

It might also be worth retrying the steps in the [ArenaHelper Readme](https://github.com/rembound/Arena-Helper) again, and checking the [issues there too](https://github.com/rembound/Arena-Helper/issues), for example "[Everytime I try opening arena helper it crashes HDT](https://github.com/rembound/Arena-Helper/issues/33)".

**Comment by rapid383** [comment]
Thanx alot for the help.  Here is the log:

[hdt_log2.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/64070/hdt_log2.txt)

**Comment by rapid383** [comment]
Thanx for the help.  Here is the log:
[hdt_log2.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/64072/hdt_log2.txt)

**Comment by Epix37** [comment]
`Hearthstone Deck Tracker\Plugins\ArenaHelper\x86\opencv_ffmpeg300.dll do not exist.`

Can you check if that does indeed not exist? If so, try downloading ArenaHelper again.

**Comment by rapid383** [comment]
Just downloading from https://github.com/rembound/Arena-Helper/releases

And here is the screenshot after unzipping....
![hs4](https://cloud.githubusercontent.com/assets/16308072/11845634/c4506ec4-a44f-11e5-9c93-e2a52a8e2411.jpg)

Am I suppose to download those source code files too?  Where do I unzip those to?

**Comment by andburn** [comment]
No you don't need the source code files. If you followed the steps it should work?

**Comment by Epix37** [comment]
There are definitely dlls missing though, that's why it crashes. I would guess Arena Helper usually downloads or generates them at runtime? Maybe @rembound can help here?

**Comment by rapid383** [comment]
I definitely followed all the procedures on the website, such as Unblocking before unzipping....but still....

**Comment by rembound** [comment]
It is normal for the opencv_ffmpeg300.dll file to not exist. It will not crash because of it.
@rapid383 mailed me a crash report before that I've attached:
[Crash report 8122015-2232.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/64434/Crash.report.8122015-2232.txt)

**Comment by rapid383** [comment]
I've re-download/install everything since then.  But now, I do not even have the Crash Report folder after I crash.  >.>

**Comment by Epix37** [comment]
Could you post the related windows event log? [See here](http://windows.microsoft.com/en-us/windows/open-event-viewer#1TC=windows-7), you should be able to find it under windows log > application.

**Comment by rapid383** [comment]
- System 

  - Provider 

   [ Name]  Application Error 
 
  - EventID 1000 

   [ Qualifiers]  0 
 
   Level 2 
 
   Task 100 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2015-12-17T13:17:16.000000000Z 
 
   EventRecordID 119690 
 
   Channel Application 
 
   Computer Herman-PC 
 
   Security 
 

- EventData 

   Hearthstone Deck Tracker.exe 
   0.1.0.0 
   5672b076 
   ntdll.dll 
   6.1.7601.19045 
   56258e62 
   c0000374 
   000ced0b 
   1850 
   01d138cd116986c6 
   C:\Users\Herman\Desktop\Hearthstone Deck Tracker\Hearthstone Deck Tracker.exe 
   C:\Windows\SysWOW64\ntdll.dll 
   7dd6bd9f-a4c0-11e5-a6e7-bc5ff45a9491

**Comment by rapid383** [comment]
- System 

  - Provider 

   [ Name]  Windows Error Reporting 
 
  - EventID 1001 

   [ Qualifiers]  0 
 
   Level 4 
 
   Task 0 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2015-12-17T13:17:57.000000000Z 
 
   EventRecordID 119691 
 
   Channel Application 
 
   Computer Herman-PC 
 
   Security 
 

- EventData 

   451501331 
   25 
   APPCRASH 
   Not available 
   0 
   Hearthstone Deck Tracker.exe 
   0.1.0.0 
   5672b076 
   StackHash_9d87 
   6.1.7601.19045 
   56258e62 
   c0000374 
   000ced0b 
    
    
   C:\Users\Herman\AppData\Local\Temp\WERED2D.tmp.WERInternalMetadata.xml 
   C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Hearthstone Deck_32fc57d51af327beb6bc1918d2756a473cb16bb_188e8ab3 
    
   0 
   7dd6bd9f-a4c0-11e5-a6e7-bc5ff45a9491 
   0

**Comment by rapid383** [comment]
Any suggestions?

**Comment by rembound** [comment]
Try to install the debug dll in: https://github.com/rembound/Arena-Helper/issues/33#issuecomment-165782349
Maybe this will give you more debug information in the log file.

**Comment by rapid383** [comment]
- System 

  - Provider 

   [ Name]  Application Error 
 
  - EventID 1000 

   [ Qualifiers]  0 
 
   Level 2 
 
   Task 100 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2015-12-19T05:40:20.000000000Z 
 
   EventRecordID 119928 
 
   Channel Application 
 
   Computer Herman-PC 
 
   Security 
 

- EventData 

   Hearthstone Deck Tracker.exe 
   0.1.0.0 
   56740b62 
   ntdll.dll 
   6.1.7601.19045 
   56258e62 
   c0000374 
   000ced0b 
   bcc 
   01d13a1fac3e64ff 
   C:\Users\Herman\Desktop\Hearthstone Deck Tracker\Hearthstone Deck Tracker.exe 
   C:\Windows\SysWOW64\ntdll.dll 
   fd4a8a77-a612-11e5-8408-bc5ff45a9491

**Comment by rapid383** [comment]
Same result?

**Comment by rapid383** [comment]
+ System 

  - Provider 

   [ Name]  Windows Error Reporting 
 
  - EventID 1001 

   [ Qualifiers]  0 
 
   Level 4 
 
   Task 0 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2015-12-19T05:47:58.000000000Z 
 
   EventRecordID 119932 
 
   Channel Application 
 
   Computer Herman-PC 
 
   Security 
 

- EventData 

   455657158 
   25 
   APPCRASH 
   Not available 
   0 
   Hearthstone Deck Tracker.exe 
   0.1.0.0 
   56740b62 
   StackHash_efd1 
   6.1.7601.19045 
   56258e62 
   c0000374 
   000ced0b 
    
    
   C:\Users\Herman\AppData\Local\Temp\WER850B.tmp.WERInternalMetadata.xml 
   C:\Users\Herman\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_Hearthstone Deck_a08b7eb3242172516854812656d37850b490238d_1aaba4da 
    
   0 
   0969541c-a614-11e5-8408-bc5ff45a9491 
   0

**Comment by rapid383** [comment]
+ System 

  - Provider 

   [ Name]  Windows Error Reporting 
 
  - EventID 1001 

   [ Qualifiers]  0 
 
   Level 4 
 
   Task 0 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2015-12-19T05:47:58.000000000Z 
 
   EventRecordID 119932 
 
   Channel Application 
 
   Computer Herman-PC 
 
   Security 
 

- EventData 

   455657158 
   25 
   APPCRASH 
   Not available 
   0 
   Hearthstone Deck Tracker.exe 
   0.1.0.0 
   56740b62 
   StackHash_efd1 
   6.1.7601.19045 
   56258e62 
   c0000374 
   000ced0b 
    
    
   C:\Users\Herman\AppData\Local\Temp\WER850B.tmp.WERInternalMetadata.xml 
   C:\Users\Herman\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_Hearthstone Deck_a08b7eb3242172516854812656d37850b490238d_1aaba4da 
    
   0 
   0969541c-a614-11e5-8408-bc5ff45a9491 
   0

**Comment by rapid383** [comment]
130294119 
   30 
   FaultTolerantHeap 
   無法使用 
   128903186303 
   Hearthstone Deck Tracker.exe 
   0.1.0.0 
   56740B62 
   ffffbaad 
    
    
     
    
    
   C:\Windows\ServiceProfiles\LocalService\AppData\Local\Temp\FTH84BD.tmp\fthempty.txt 
    
    
   0 
   096dc0fd-a614-11e5-8408-bc5ff45a9491 
   8

**Comment by rapid383** [comment]
- System 

  - Provider 

   [ Name]  Windows Error Reporting 
 
  - EventID 1001 

   [ Qualifiers]  0 
 
   Level 4 
 
   Task 0 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2015-12-19T05:48:02.000000000Z 
 
   EventRecordID 119933 
 
   Channel Application 
 
   Computer Herman-PC 
 
   Security 
 

- EventData 

   130294119 
   30 
   FaultTolerantHeap 
   無法使用 
   128903186303 
   Hearthstone Deck Tracker.exe 
   0.1.0.0 
   56740B62 
   ffffbaad 
    
    
    
    
    
    
   C:\Windows\ServiceProfiles\LocalService\AppData\Local\Temp\FTH84BD.tmp\fthempty.txt 
    
    
   0 
   096dc0fd-a614-11e5-8408-bc5ff45a9491 
   8

**Comment by rapid383** [comment]
Any suggestions?

**Comment by rembound** [comment]
As I said in the other thread:
> No new messages probably means that the crash doesn't occur in the tested code. Maybe some dll or library is incompatible with your system. I can't solve the problem at this point.

**Comment by Epix37** [comment]
Closing since this is a Arena-Helper related issue.
