### ISSUE TITLE
There is no exe in the files

### ISSUE THREAD

**Issue by Asmoday1232** [Epix37/Hearthstone-Deck-Tracker#1872]
Went through after extraction and there is no exe. Did you hide it somewhere?

**Comment by andburn** [comment]
You have probably downloaded the source code by accident get the latest release zip file from https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/latest

(*Another possibility is your virus software may have deleted the exe for some reason*)

**Comment by Asmoday1232** [comment]
Well, thats what I get for trying to do this first thing in the morning. Im going back to bed, clearly I am not thinking >.<

Thanks.
