### ISSUE TITLE
Tracker does not do anything.

### ISSUE THREAD

**Issue by Asmoday1232** [Epix37/Hearthstone-Deck-Tracker#1873]
Tracker, even tho I follow the instructions, does not allow import from game. So I manually made my decks. Now in game it does not track anything. It just has the overlay there and does nothing.

**Comment by irufus** [comment]
Did you make sure you set your home path for Hearthstone to the right directory?

**Comment by Epix37** [comment]
See here: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#not-working

**Comment by Elesion** [comment]
Having the same issue. Overlay for deck does not interact at all - followed instructions and made changes based on FAQs.  Using windows 10.

**Comment by Epix37** [comment]
Closing due to age. Might be fixed by now?
