### ISSUE TITLE
deck tracker wont work

### ISSUE THREAD

**Issue by sale1992** [Epix37/Hearthstone-Deck-Tracker#1874]
It work perfect for me until today in city we lost power so my computer instant shut down, now when i want to start HDT it automatic screen freeze and writte "not responded". I try to delete HDT and instal again but it still dont work, plz help. Ty

**Comment by munjunaw** [comment]
same thing happened to me. Please advise

**Comment by irufus** [comment]
Post your hdt_log.txt in pastebin. You can find it by typing %APPDATA%\HearthstoneDeckTracker\Logs in the RUN menu

**Comment by Epix37** [comment]
See if this helps: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#not-working

**Comment by munjunaw** [comment]
its fine now, after finishing my current run

**Comment by munjunaw** [comment]
thanks everyone! Great great app btw Epix
