### ISSUE TITLE
Stopped recording GameState logs in 0.13.5?

### ISSUE THREAD

**Issue by sebastientromp** [Epix37/Hearthstone-Deck-Tracker#1875]
Using HDT 0.13.5, it looks like the generated output_log only includes PowerTaskList logs, and no GameState logs anymore (which breaks HSReplay parser). Is this intentional? Or is there a specific option I haven't seen?

Thanks!

[output_log.0.13.5.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/63797/output_log.0.13.5.txt)
[output_log.0.13.3.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/63799/output_log.0.13.3.txt)

**Comment by Epix37** [comment]
HSReplay *should* work with PowerTaskList - at least the python implementation - the only thing missing (still) is the CREATE_GAME line.

It only contains PowerTaskList because that is what HDT uses. It's a lot more consistent than GameState.

**Comment by sebastientromp** [comment]
Ok, thanks for letting me know. The C# implementation works with GameState though, which is why I'm asking.

Do you know what the differences between PowerTaskList and GameState are?

**Comment by Epix37** [comment]
I think structure wise the only difference is that FULL_ENTITY lines always contain "Updating" rather than "Creating". 

Other than that, the main difference (and most important one for HDT) is that PowerTaskList does not have the "UNKNOWN HUMAN PLAYER" issue.

**Comment by sebastientromp** [comment]
One more question: are options handled by PowerTaskList? I think they are not necessary for the replay itself, but I'm just curious if it's something that you plan to continue supporting.

**Comment by Epix37** [comment]
I don't think they are. 

I plan on generating hsreplay files by default some time early next year. As long as the conversion somewhat works (hdtreplay logs -> hsreplay) it should be fine.

**Comment by sebastientromp** [comment]
Just did a test with the current hdtreplay logs, and the c# implementation almost works as is. Options are indeed not necessary to replay the file afterwards.
