### ISSUE TITLE
Cant set other language

### ISSUE THREAD

**Issue by Qtqtqtqtqtqt** [Epix37/Hearthstone-Deck-Tracker#1876]
when i try to set a different language and restart the program iwth the button below/restart manually, its again set to english after that, i dont know why. do i have to download a different package or something or am i stupid?!

greets

**Comment by riQQ** [comment]
The option `Card language` only affects the cards, there's no option to change the program's language.

**Comment by Qtqtqtqtqtqt** [comment]
yes i know, but it didnt change the language of the cards and it sets itself back to english after restart

**Comment by andburn** [comment]
Can confirm this, the language change is never saved must be like this since HearthDB was added, @Epix37 its [this line](https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/FlyoutControls/Options/Tracker/TrackerAppearance.xaml.cs#L119).
