### ISSUE TITLE
Golden monkey issue

### ISSUE THREAD

**Issue by BVA64** [Epix37/Hearthstone-Deck-Tracker#1877]
When my opponent plays Golden Monkey the card number and age tracking gets messed up. The overlay shows more cards than what he really has in hand.
This is visible also in the replay file on turn 10 where it looks like as if the opponent drew all the legendary cards he played afterwards on that turn.

https://www.dropbox.com/s/owt8txuww47dzdf/BVA64%28Priest%29%20vs%20NuttyChunks%28Priest%29%201043-151215.zip?dl=0

I'm using v0.13.5

**Comment by Epix37** [comment]
Do you have the hdt log for that game?

**Comment by BVA64** [comment]
[hdt_log_1450247510.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/65255/hdt_log_1450247510.txt)
