### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by Kostyazz** [Epix37/Hearthstone-Deck-Tracker#1878]
HDT crashed after I had conceded in a game and had returned to main menu.
I am using Windows 8.
HDT version is 0.13.3.0
[Crash report 17122015-1520.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/65346/Crash.report.17122015-1520.txt)

**Comment by Epix37** [comment]
Might be fixed. Let me know if it happens again.
