### ISSUE TITLE
Start Launcher / Hearthstone button isn't working

### ISSUE THREAD

**Issue by Sombres** [Epix37/Hearthstone-Deck-Tracker#1879]
I formatted my system partition a few days back and now when I launch HDT and press the mentioned button, nothing happens. Games (along with HDT and Hearthstone) are on the D: partition, which was left intact. I of course have already tried setting the paths in Options->Settings, but that didn't change anything. It does nothing to/with either Hearthstone nor Battle.net launcher (Before the format, it wouldn't open Battle.net launcher, but if it was open, it would start Hearthstone. Now there is absolutely no effect whether the launcher is running or not). HDT version is 0.13.6.

**Comment by Epix37** [comment]
It lauches both via the `battlenet://` protocol. You may need to reinstall the battlenet launcher / hearthstone for it to work.
