### ISSUE TITLE
Restarting via button in options results in two hanging instances

### ISSUE THREAD

**Issue by riQQ** [Epix37/Hearthstone-Deck-Tracker#1880]
Restarting HDT via the button `Restart HDT` in `Options > Tracker > Appearance` results in two hanging instances of HDT, that can't be exited via system tray context menu. Nothing happens after pressing `Exit` in the context menu.
The error message is `Another instance of Hearthstone Deck Tracker is already running.`.

**Comment by Epix37** [comment]
I'm not able to reproduce it. Could you try debugging/fixing it?

**Comment by riQQ** [comment]
Now I couldn't reproduce it either. I don't know what caused this.

**Comment by riQQ** [comment]
This is also reproducible by logging in or out from Hearthstats, which causes HDT to restart.

**Comment by riQQ** [comment]
I can't reproduce this, logging out from Hearthstats and the following restart work fine.
