### ISSUE TITLE
Not Syncing Games with Hearthstats v0.13.6 

### ISSUE THREAD

**Issue by tknights2015** [Epix37/Hearthstone-Deck-Tracker#1882]
Games are not syncing with Hearthstats v0.13.6 

![heartstats](https://cloud.githubusercontent.com/assets/16232528/11887916/b67b5952-a4f5-11e5-80a5-81c608945e04.JPG)
![games](https://cloud.githubusercontent.com/assets/16232528/11887918/bb182b34-a4f5-11e5-889f-ec5628480a11.JPG)
[log_17122015-193345.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/66158/log_17122015-193345.txt)

**Comment by tknights2015** [comment]
Just a footnote. I reverted back to version v0.13.3 And games are synced correctly with Hearthstats.

**Comment by Epix37** [comment]
Found the problem.... apparently updating games on HearthStats does not work, so when you changed the mode to ranked it just deleted the game but did not re-upload it. 

That bug must have been around for about 8 months... that explains so much.

**Comment by Epix37** [comment]
Should be fixed with v0.13.7.
