### ISSUE TITLE
Cant export

### ISSUE THREAD

**Issue by mudum** [Epix37/Hearthstone-Deck-Tracker#1883]
After you choose export to hearthstone/from web, it just stops after it searches the cards

**Comment by machogriz** [comment]
Same issue here. After clicking Export, it names the deck in hearthstone but then doesn't actually add any cards

**Comment by machogriz** [comment]
Nevermind. Found the cause of my issue. I use NetDeck in Chrome and it had populated HDT with a Baron Geddon that cost 0 mana. It obviously couldn't find that in Hearthstone so after removing that from the deck in HDT and adding the Baron Geddon for 7 mana, the export worked as normal.

**Comment by mudum** [comment]
ok issue solved

**Comment by riQQ** [comment]
@mudum was it the same reason why it wasn't working for you?

**Comment by mudum** [comment]
yes
