### ISSUE TITLE
Arena games being recorded as Casual

### ISSUE THREAD

**Issue by RavenousSix** [Epix37/Hearthstone-Deck-Tracker#1884]
As the title says, Arena games being recorded as Casual.

When the little popup at the bottom comes up after an Arena game, it's marked as Casual, I have to manually fix it by hand and change it to Arena.

**Comment by Epix37** [comment]
Could you post the logs of those games? You can find them under `%AppData%/HearthstoneDeckTracker/Logs` (`options > tracker > settings > open appdata folder`).

**Comment by bstuparu** [comment]
Hello Epix, this issue also happens with Ranked games. I am attaching the log file from my end.
[hdt_log.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/66398/hdt_log.txt)

**Comment by Epix37** [comment]
@bstuparu see here for ranked games: https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1881#issuecomment-165717394

**Comment by Epix37** [comment]
Still an issue with v0.13.7?
