### ISSUE TITLE
HDT do not find the exe.config 

### ISSUE THREAD

**Issue by Muffed** [Epix37/Hearthstone-Deck-Tracker#1886]

**Comment by Muffed** [comment]
![image](https://cloud.githubusercontent.com/assets/16351542/11898685/0fbbdb1e-a59a-11e5-9114-2cf20ac303d5.png)

**Comment by Muffed** [comment]
![image](https://cloud.githubusercontent.com/assets/16351542/11898693/2bdccdf8-a59a-11e5-9a76-3eacf79a96d0.png)

**Comment by Epix37** [comment]
What happens if you press "select manually" and then provide your Hearthstone install dir?

**Comment by Muffed** [comment]
i can't find anything in the folder
![image](https://cloud.githubusercontent.com/assets/16351542/11898761/91e1ed5e-a59a-11e5-975f-cdd611825734.png)

**Comment by Epix37** [comment]
It needs the **Hearthstone** folder.

**Comment by Muffed** [comment]
DONE TY!!!! <3

**Comment by Epix37** [comment]
No problem :).
