### ISSUE TITLE
DeckTracker overlay hides when I click on HS window.

### ISSUE THREAD

**Issue by Mordorkaiser** [Epix37/Hearthstone-Deck-Tracker#1887]
Hello,

I am able to import/export, save, edit, etc. When I start playing the tracking begins, but ehwn I click on the HS window, it hides.
I made sure all of the "Hide" options are unchecked.
All of the tracking keeps working, but I need to switch windows in order to see the information, which is not handy.

Any Idea what could it be?

**Comment by Epix37** [comment]
If this is still an issue, check for windows/graphics driver updates. Could also try reinstalling .NET Framework.
