### ISSUE TITLE
Games not being recorded for v0.13.7

### ISSUE THREAD

**Issue by RussianRockman** [Epix37/Hearthstone-Deck-Tracker#1888]
Played several Arena games using 0.13.7 and they did not have replays saved for them.  In addition, stats did not get updated.  I then played a few games in Casual and they did not get replays or stats saved for them either.   I think 0.13.6 may have also had this issue, but I'm not 100% sure.

Restarted both HDT and hearthstone, same issue remained.

Reverted to 0.13.5 and games were saved properly again.

**Comment by tknights2015** [comment]
Games also not being recorded for ranked as of 5:11pm 12/22 MST.
Game played in casual at lunch recorded. First Ranked game later in day, nothing recorded at all
[log_22122015-171358.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/70345/log_22122015-171358.txt)
