### ISSUE TITLE
1.3.7 isn´t starting / same problem at 1.3.6 before

### ISSUE THREAD

**Issue by SteinmannJos** [Epix37/Hearthstone-Deck-Tracker#1890]
I only see the starting icon, then the program stopps working.

I attach the crash report 
[Crash report 19122015-1244.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/67473/Crash.report.19122015-1244.txt)

**Comment by riQQ** [comment]
What's the path to the `Hearthstone Deck Tracker.exe` on your computer?

**Comment by SteinmannJos** [comment]
E:\#HS Decktracker\Hearthstone.Deck.Tracker-v0.13.7\Hearthstone Deck Tracker

**Comment by SteinmannJos** [comment]
I now tried to start it from D: and it works :D     so it is solved

**Comment by riQQ** [comment]
That's  interesting. Is `E:` an external drive or somehow different from `D:`?

**Comment by SteinmannJos** [comment]
No I have one HDD with partitions D: and E:

**Comment by riQQ** [comment]
Was there a `#` in the path?
