### ISSUE TITLE
Import from constructed

### ISSUE THREAD

**Issue by jiqingjerry** [Epix37/Hearthstone-Deck-Tracker#1893]
Everytime I click import and then from game: constructed, it will pop up the how it works: guide for importing and then nothing happens. Can someone please tell me whats going on ty

**Comment by LineWolff** [comment]
Got the same problem. HDT v0.13.7

**Comment by cachirro** [comment]
i have the same problem, import from game not working :(

**Comment by Epix37** [comment]
Try entering the "Play" menu once before starting the import. Constructed importing is sadly not a very stable feature just by the nature of how it works.

**Comment by cachirro** [comment]
Strangely it worked now without doing that, but not good, so i´ve tried that, but also no success, I mean, it imports now, but very unstable, one time 17 cards, other 20 and other 33, don’t know why the different outputs.

 

With best regards,

António Cardoso

**Comment by Epix37** [comment]
It can't detect the number of copies for cards, so it defaults to either 1 or 2 copies of each, depending on whatever is closer to 30.
