### ISSUE TITLE
Bug: Export deck to the game from locale with non-latin characters doesn't work if current language doesn't match

### ISSUE THREAD

**Issue by mirasrael** [Epix37/Hearthstone-Deck-Tracker#1894]
I tried to export deck to Hearthstone with Russian language selected and while searching card names it just types something like "????????????? ?????". I read the code and found what SendKeys used to fill card names. In documentation for SendKeys I found information it only works if right Keyboard Language (in Windows) is selected (my current keyboard language was English). In other cases it causes unexpected behavior ("???? ?????" in my case).  From code I also found option to use clipboard for export. When I switched Keyboard Layout to Russian it start works. It also works well with using Clipboard for Export.
Because I'm usually using English Keyboard Layout as Primary it was hard to me to detect this issue without deep into code. The perfect way to solve this issue - check current keyboard language, switch to language matching selected for HDT, export deck, switch back to previous keyboard language. It may be hard thought. But at least it may be very useful to add notification on Export Instructions screen.

**Comment by Epix37** [comment]
Try enabling `options > tracker > exporting > paste names from clipboard`.

**Comment by mirasrael** [comment]
Yes, I did it. I mentioned it in my comment: "It also works well with using Clipboard for Export". Now it is a way how I use this functionality.
