### ISSUE TITLE
"Don't reset decks after the game" no longer works as before

### ISSUE THREAD

**Issue by MyopicCat** [Epix37/Hearthstone-Deck-Tracker#1895]
I have this option checked, along with the post game note popup option. Previously I've been able to start writing the note, alt-tab back to HS and the tracker to remind myself what was in my opponent's deck and then alt-tab back to finish my note. Now, when I alt-tab from the note to HS, the opponent's deck resets in the tracker so I can't check what was in it. I think this started in 0.13.6 or 0.13.7.

**Comment by Epix37** [comment]
Still an issue with v0.13.17?
