### ISSUE TITLE
Cards drawn shown by tracker before displayed in game.

### ISSUE THREAD

**Issue by KinkyJohnFowler** [Epix37/Hearthstone-Deck-Tracker#1896]
It's a minor issue, but I cannot see any way in the tracker settings to delay this. Before we see the card drawn from the deck in game the card is highlighted in the deck tracker overlay as being drawn.

Turning off highlighting doesn't really solve this either.

**Comment by mvordeme** [comment]
That's due to the delay caused by all the animations going on in Hearthstone. HDT displays the cards as soon as they are drawn.
