### ISSUE TITLE
Not Highlighting Cards when Playing

### ISSUE THREAD

**Issue by GingerBenMan** [Epix37/Hearthstone-Deck-Tracker#1900]
So I just got HDT and set it up. It works for my friend and I have all the same settings, but when I play nothing highlights. My drawn cards, my played cards, my jousted cards, nothing. Nothing updates when I play. It's almost like I have a still image. Please help.

**Comment by riQQ** [comment]
Did you restart Hearthstone after opening HDT for the first time?

**Comment by GingerBenMan** [comment]
that worked. Thanks
