### ISSUE TITLE
No deck mode: SETASIDE not tracked (e.g. Hunter-Tracking)

### ISSUE THREAD

**Issue by HellbringerOnline** [Epix37/Hearthstone-Deck-Tracker#1902]
Tracking does not add cards in my deck.

**Comment by Epix37** [comment]
Could you explain the problem in a bit more detail? With, without deck? Screenshots and logs [(see here)](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues) might help.

**Comment by HellbringerOnline** [comment]
![4](https://cloud.githubusercontent.com/assets/14059683/12023760/c8f49a74-adad-11e5-90d1-c519a0548ca2.png)
![5](https://cloud.githubusercontent.com/assets/14059683/12023762/cd0fcd5e-adad-11e5-9d35-3935ae44e908.png)
![6](https://cloud.githubusercontent.com/assets/14059683/12023764/d05b2e86-adad-11e5-92ae-40bd7992d41e.png)

**Comment by Epix37** [comment]
This is only an issue when no deck is selected, correct?

**Comment by HellbringerOnline** [comment]
I tested only without deck.

**Comment by Epix37** [comment]
Should be fixed with v0.13.16,
