### ISSUE TITLE
When edited arena rewards HDT crashed

### ISSUE THREAD

**Issue by gsapshank** [Epix37/Hearthstone-Deck-Tracker#1904]
When I edited my arena rewards, HDT always crashed at the CARDs part. I tried to input cards name and it crashed.

[Crash report 21122015-2237.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/68585/Crash.report.21122015-2237.txt)

**Comment by riQQ** [comment]
Which text did you input?

**Comment by gsapshank** [comment]
Any text, include numbers.

**Comment by Epix37** [comment]
Closing in favor of #2084
