### ISSUE TITLE
Problem with cards show 

### ISSUE THREAD

**Issue by Blade17** [Epix37/Hearthstone-Deck-Tracker#1905]
I start the match (with deck tracker) and deck tracker doesen't show me the whole deck... but only the cards that I or the opponent draw  :(( pls help me i don't know how fix

**Comment by mvordeme** [comment]
This happens whenever there is no active deck. In order to enable automatic deck detection, there must be an active deck (leftt-click "USE"). If no deck is active, HDT will use no deck (Menu > Main > Use No Deck).

**Comment by Blade17** [comment]
I LOVE YOU , THANKSSSSS <3
