### ISSUE TITLE
Can't open .exe file

### ISSUE THREAD

**Issue by expunge** [Epix37/Hearthstone-Deck-Tracker#1908]
When opening Hearthstone Deck Tracker as admin it say it has stopped working immediately. The problem details I get: 
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	Hearthstone Deck Tracker.exe
  Problem Signature 02:	0.1.0.0
  Problem Signature 03:	56740b62
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.0.30319.34209
  Problem Signature 06:	534894cc
  Problem Signature 07:	27cb
  Problem Signature 08:	0
  Problem Signature 09:	System.Windows.Markup.XamlParse
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Also have reinstalled 4.5 .Net 
Thanks

**Comment by riQQ** [comment]
What's the path to the `Hearthstone Deck Tracker.exe` on your computer?

**Comment by expunge** [comment]
C:/User/Desktop/HearthstoneDeckTrecker.exe

**Comment by riQQ** [comment]
Try to extract the HDT.zip to another location and start from there.

**Comment by expunge** [comment]
Thanks extracted to documents and it works from there.
