### ISSUE TITLE
HotKeyManager ignores binds to mouse buttons

### ISSUE THREAD

**Issue by chaorace** [Epix37/Hearthstone-Deck-Tracker#1910]
HotKeyManager accepts mouse buttons for binding, but methods bound this way will never be called

Example:
```
//Never calls Helper.contextKey when the hotkey is pressed
HotKeyManager.RegisterHotkey(new HotKey(Keys.MButton), Helper.contextKey, "Context Button");
```

The above code should call Helper.contextKey when the middle mouse button is pressed, but does not. I've tested this with the MButton, XButton1, and XButton2 to the same result. Meanwhile, regular keys like F3 work in the same scenario:

```
//Works
HotKeyManager.RegisterHotkey(new HotKey(Keys.F3), Helper.contextKey, "Context Button");
```

**Comment by Epix37** [comment]
The UI side does not support settings mouse buttons so I never even tried this. Since there is no use for it internally, I'm leaning towards just disallowing mouse buttons. Is there any particular reason you would want to bind to mouse buttons?

**Comment by chaorace** [comment]
The plugin I'm working on adds qol shortcuts, some of which I'd like to bind to mouse buttons for convenience. The contextKey mentioned in the example would click on a screen region appropriate to the current context (end mulligan button, end turn button, play button, etc), which I'd like to bind to the mouse for, well, convenience

**Comment by chaorace** [comment]
Is this still being looked at or is this a won't fix kind of issue? If this isn't going to be fixed I'm going to have to implement the functionality myself separately before I release my plugin

**Comment by Epix37** [comment]
I think this will not be fixed any time soon since HDT itself does not support it anyway. IIRC, hooking on mouse events causes stuttering - though I'm not sure if that was only related to position updates or clicks (hence the notice in options > overlay > interactivity).
