### ISSUE TITLE
Hearthstone deck tracker not working

### ISSUE THREAD

**Issue by KerrigamGR** [Epix37/Hearthstone-Deck-Tracker#1913]
When I start hearthstone it doesn't start the overlay at all. It also is not responding when I try to import/export decks. Several times it has stopped my mouse from working completely. Last, if I try to start the program as administrator, it crashes and doesn't even start.

**Comment by KerrigamGR** [comment]
I have tried the program in another laptop and it works. So something is wrong with this one, please help.

**Comment by chaorace** [comment]
The issue tracker's more a place for documenting bugs and feature requests as opposed to support. You'll have more luck and faster responses if you consult the [gitter chat](https://gitter.im/Epix37/Hearthstone-Deck-Tracker?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
