### ISSUE TITLE
Loss not tracking

### ISSUE THREAD

**Issue by Chrome27** [Epix37/Hearthstone-Deck-Tracker#1914]
After the patch, when I lose a match (in arena), loss count is not going up. It goes up right when I lose, but when I go back to the arena page after losing, the loss count goes back down.

**Comment by Epix37** [comment]
Likely an issue with mode recording settings. Check `options > tracker > stats > record`, make sure `arena` is enabled. Other possibility is mode detection fails for some reason, in that case try enabling recording `other` as well.
