### ISSUE TITLE
[arena] unable to add statistic/match result,rewards to deck

### ISSUE THREAD

**Issue by gardian06** [Epix37/Hearthstone-Deck-Tracker#1915]
description: I was playing an arena game, and then Hearthstone started becoming unresponsive. the game kicked me. I attempted to reenter multiple times, and each time a different reason was given for me being kicked (along with no reason at all. one of the times that I got into the game enough for the deck tracker to recognize the game as running it showed a, enter results, popup for the match then the game kicked me again. when I finally got back into hearthstone, and was able to reopen the arena menu it showed my rewards(it was my third loss), but I have no way to enter the results of the match, or the rewards into the deck tracker.

now the deck is set at a 2-2 record in arena, and because the arena run is over I have no way to use the deck(it had 3 copies of some cards), or put the rewards in the results of the deck tracker.

suggestion: add the option to enter rudimentary match result to decks being tracked, and for arena decks allow for rewards to be entered. as in the event of a "retire" option being used I see no way for rewards to be entered.

**Comment by riQQ** [comment]
You can add games manually via the `Stats > [Old] Games and Statistics` menu and the `Add new game` button at the statistics window.

**Comment by gardian06** [comment]
thanks is there a way to add arena rewards to a run?

**Comment by riQQ** [comment]
Yes, there is. `Stats > Arena runs & statistics` and then select `Runs & matches`. Then there's a `Edit rewards button`.
