### ISSUE TITLE
Deck statistics off when creating a deck with the name of a deleted one

### ISSUE THREAD

**Issue by mvordeme** [Epix37/Hearthstone-Deck-Tracker#1916]
I recently tried a new deck, and after failing miserably, I deleted it again. But I somehow liked the name and later created another deck with the same name. The deck statistics have been fishy ever since. It currently displays a win ratio of 54% based on 13-8 wins-losses. The numbers would make a certain sense if there were an additional 0-3 wins-losses for the deleted deck counting towards the ratio.

**Comment by mvordeme** [comment]
... on the other hand, it might be those three mysterious games with a result of "None" in the statistics.

**Comment by Epix37** [comment]
will be fixed with the next update. #2006
