### ISSUE TITLE
My secrets

### ISSUE THREAD

**Issue by HellbringerOnline** [Epix37/Hearthstone-Deck-Tracker#1922]
It would be nice to know to any secrets what you have been checked by the opponent.

**Comment by rodrigokiller** [comment]
What? I dont get it.

**Comment by RickardNi** [comment]
I think what he means is:

When your opponent plays a secret, as you make moves/progress, you rule out more and more secrets. You see this by the secret list in the upper left corner.

I think he would like to have the same thing for himself, when his opponent makes moves and rules out more and more. So to say, get access to the same "secret list" he would see, if he uses the same tracker.

**Comment by rodrigokiller** [comment]
I get it (I think).
But, it makes me to think that, when the opponent plays a secret, and you make progress and you see that there is only two possibilities of secret, when the opponent plays another secret, that two possibilties comes with the number two (2), but, its not possible to have two secrets of the same type, right?

I think, if there is only two possiblities, and the opponent plays another secret, its only possible to be the others secrets, or, at least, one of the two remaining. hehe

**Comment by Epix37** [comment]
#313
