### ISSUE TITLE
Statistic windows aren't visible.

### ISSUE THREAD

**Issue by dlk16** [Epix37/Hearthstone-Deck-Tracker#1924]
When I open "[OLD] GAMES AND STATISTICS", "ARENA RUNS & STATISTICS", or "SELECT REPLAY", the windows don't seem to be visible. I can see them open in the task bar but clicking on them in the task bar doesn't appear to do anything. I'm on Windows 10.

**Comment by Epix37** [comment]
Open the window, alt-tab to it and then press Win+Left-Arrow until you see it.

**Comment by dlk16** [comment]
Thanks it's working now.
