### ISSUE TITLE
Baron Geddon imported as 0-cost card

### ISSUE THREAD

**Issue by ko-vasilev** [Epix37/Hearthstone-Deck-Tracker#1925]
Hey, just imported a deck from hearthpwn with NetDeck plugin for Chrome (http://www.hearthpwn.com/decks/396255-phil-champs-starseeking-cw) and for some reason, Baron Geddon here costs 0 mana.

http://imgur.com/r7NQ2gu

**Comment by ThePsionic** [comment]
It might be possible that the hero from the adventure was imported instead of the card itself.

**Comment by riQQ** [comment]
See #1883.

**Comment by Epix37** [comment]
Fixed with #1911. Closing in favor of #1907.
