### ISSUE TITLE
Reno isn't highlighted in deck list when his effect is active

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#1926]
Reno doesn't get highlighted in my deck list when his effect is active and he's in my hand. I only play Reno decks with one copy of each card, so he should definitely always be active when he's in my hand.

Do I have to enable the setting that highlights cards in my hand, before the Reno highlight also works?

Can someone screenshot what it's supposed to look like, so I even know what I'm looking for?

**Comment by ceceita** [comment]
Hearthstone dont have auto highligh ,  HDT dont have an highlight fuction for Reno .

**Comment by culinko** [comment]
Yes, it does: https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/f4dd1aed4d4dba2cb3cc6c7fbcde5f320d71b9cd

**Comment by GaryKing** [comment]
Yes, would be nice if it was very obvious when the highlight is active on Reno.

**Comment by ceceita** [comment]
ops sorry , i played alot of Reno decks and never noticed ..
