### ISSUE TITLE
No issue but suggestion: Stat how many cards of each addon/expansion we got 

### ISSUE THREAD

**Issue by serjoscha87** [Epix37/Hearthstone-Deck-Tracker#1928]
Like the title says:

It would really be cool if the HDT could number the cards you are missing from the different expansions (TGT, GvG, Classic) to help one decide which booster packs to buy (according to the expansion one misses the mosts cards of).

Example view:

 Expansion stats:
 Classic: 45/120
 GvG: 69/75
 TGT: 81/95

This would tell me to better buy booster packs for the classic....

**Comment by riQQ** [comment]
If you take a look at the [Available Plugins wiki page](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Available-Plugins), there's a plugin that is exactly doing this: [Hearthstone-Collection-Tracker](https://github.com/ko-vasilev/Hearthstone-Collection-Tracker).

**Comment by serjoscha87** [comment]
Oh okay, I am sorry for that ticket!
