### ISSUE TITLE
clone deck version

### ISSUE THREAD

**Issue by funkyogre** [Epix37/Hearthstone-Deck-Tracker#1929]
(sorry for bad english)
I cloned my aggro shaman entired deck version twice for testing then deleted those 2 decks
when I check original aggro shaman deck status , overview class show triple status and I dont know how to fix it.

![1451247656609](https://cloud.githubusercontent.com/assets/16236747/12011843/9d468394-ad1a-11e5-8550-5c087912e1ff.jpg)

overview status  was 3-4 , 1-0 , 7-2 ...etc.

**Comment by Epix37** [comment]
Those games were probably moved to the "default" class decks. See `STATS > GAMES & STATISTICS > Overall > Games`, and set the "Games" filter to "Without Deck". You can change this behaviour by disabling `options > tracker > stats > keep stats when deleting a deck`.
