### ISSUE TITLE
Collection Tracker v0.2.4 crashes with HDT 0.13.7

### ISSUE THREAD

**Issue by joeshoukry** [Epix37/Hearthstone-Deck-Tracker#1930]
Collection tracker keeps throwing an exception: 

I'm using latest builds of both CT and HDT - I'm new to this so not sure if I am doing something wrong

![image](https://cloud.githubusercontent.com/assets/10981458/12011883/c706442e-ac95-11e5-9ece-003f55a4bc65.png)

**Comment by Epix37** [comment]
Are you sure you are on the latest versions on both? Works fine for me.

**Comment by rodrigokiller** [comment]
Works fine for me too
