### ISSUE TITLE
Missing Class Cards [SOLVED]

### ISSUE THREAD

**Issue by Tychoe** [Epix37/Hearthstone-Deck-Tracker#1933]
If you have experienced some issues in the last version of Hearthstone Deck Tracker (which is release v0.13.7) like missing class cards etc. Try to use "Hearthstone.Deck.Tracker-v0.13.3" build instead of lastest version. And here is important DO NOT UPDATE your v0.13.3 build to v0.13.6 nor v0.13.7. When update screen pops up say NO and keep using version v0.13.3 without any errors or missing cards. Tried both v0.13.6 and v0.13.7 versions and experienced missing class cards issue but not in v0.13.3 . This version is working perfectly.

Release v0.13.3:
https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.13.3

Hearthstone.Deck.Tracker-v0.13.3.zip:
https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/download/v0.13.3/Hearthstone.Deck.Tracker-v0.13.3.zip

**Comment by Epix37** [comment]
does not really "solve" anything

**Comment by Tychoe** [comment]
Actually this solved my issue and I wanted to share my experience to all who just suffered from this error. I saw same problem in some threads like https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1906. So I put "SOLVED" to head for to be catchy and easily find on search engines. I'm sorry if it missunderstood. If you need any file to examine let me know I am able to upload. Thank you for reply, I wish you good work :)

**Comment by siragic** [comment]
Ok, it's about regional settings on computer. I've suspected before and now I've tested it recently. I've changed the 'format' of regional settings from 'Turkish' to 'English' and restart the application and it is fixed. Although before it was working correctly on Turkish settings.
