### ISSUE TITLE
Paladin, priest and druid cards are missing.

### ISSUE THREAD

**Issue by reorden** [Epix37/Hearthstone-Deck-Tracker#1934]
Just downloaded the latest version and when i try to make a new deck cant see the class cards of certain classses. Lets say im making a paladin deck and i use filter: class cards, its empty nothing shows.

Also when i import a deck from web it works, shows everything correctly, i can add the missing class cards, but it doesnt add the deck into paladin/druid/priest tab. Also it doesnt show the class icon on the left side. Other than that deck tracker is working.

**Comment by riQQ** [comment]
See #1906, there's a workaround.

**Comment by aliberk8** [comment]
still same problem ...

**Comment by Epix37** [comment]
closing in favor of #1906
