### ISSUE TITLE
Tooltip on generated cards in opponents hand not showing

### ISSUE THREAD

**Issue by BVA64** [Epix37/Hearthstone-Deck-Tracker#1938]
I used to get a tooltip when I mouse over the card age circle on a card that was generated by some event (e.g. A spare part generated by the death rattle of a clockwork gnome) showing the card that generated it. Now I only get the tooltip on cards returned to the opponents hand.

Was this feature intentionally removed?

**Comment by Epix37** [comment]
This was intentionally removed, yes. It was too inconsistent in many cases anyway. I have nothing against adding it again at some point though.
