### ISSUE TITLE
Ctrl+V issue with exporting.

### ISSUE THREAD

**Issue by Agrinofeles** [Epix37/Hearthstone-Deck-Tracker#1941]
![hearthstone 2015-12-31 14-48-07-59](https://cloud.githubusercontent.com/assets/16500112/12064182/9b8bbfbe-afcd-11e5-99db-ab8daf5c3c72.jpg)
Hi.

I used to export a lot of decks earlier through "to hearthstone" and "to hearthstone from web". It was going pretty well. Now when i'm trying to export no matter how it just type "v" letter in deck name and the same "v" letter in the search panel. So it just choose first two cards from class clicking it 30 times and don't work properly.
I tried to restart all things (Tracker, HS, PC) and nothing could help me.
I think that's because tracker type "v" but not "ctrl+v" in search panel.
How can i solve this?

**Comment by Epix37** [comment]
Did you change the behaviour of the ctrl key on your system? 

Try disabling `options > tracker > exporting > paste names from clipboard`.

**Comment by Agrinofeles** [comment]
Somehow it solved itself after some time
