### ISSUE TITLE
deck tracker can not find the install directory for hearthstone

### ISSUE THREAD

**Issue by sp20000** [Epix37/Hearthstone-Deck-Tracker#1942]
when i run the program it says hearthstone install directory not found, however i have installed the game and can run the game, i can also export and import decks using the tracker

**Comment by TrueSkrillor** [comment]
Try setting the path to the install directory manually: go options -> setttings -> "Set Hearthstone Path"
This should fix your issue.
Yours Skrillor

**Comment by kidpoker2k7** [comment]
I am now having the same problem. i tried the solution above and nothing has seemed to work. I can load the tracker but when playing nothing is being tracked and no cards and data are on the side for myself or oppionent. so basically ut loads but nothing is working.
