### ISSUE TITLE
Access Rights

### ISSUE THREAD

**Issue by JonnyMcFire** [Epix37/Hearthstone-Deck-Tracker#1943]
Why is the program trying to access several Protected Registry Keys having to do with SystemCertificates?

![image](https://cloud.githubusercontent.com/assets/15312123/12068235/a501077c-afc6-11e5-8dc7-a0b8e9c978fe.png)

**Comment by JonnyMcFire** [comment]
I am not trying to imply anything negative, I'm mostly curious as to why it would want permission to these registries.  Any thoughts on this would be greatly appreciated!

**Comment by riQQ** [comment]
It's probably used for checking the certificate that is used for updating HDT via https / ssl.

**Comment by Epix37** [comment]
I can assure you HDT is not directly accessing any of those. The answer by @riQQ seems like the most reasonable explanation.
