### ISSUE TITLE
HDT won't track cards

### ISSUE THREAD

**Issue by CloudyWolf707** [Epix37/Hearthstone-Deck-Tracker#1945]
![2016-01-02](https://cloud.githubusercontent.com/assets/13022725/12073362/c0a4d0b0-b0d1-11e5-850c-4eb9bdf88f47.png)
Hi, I've used HDT in the past without any issues, but a few months ago, I recieved a new hard drive for my computer. This one was much bigger than my default ssd, so i decided to move hearthstone and all my steam stuff to this new drive. After i did that, HDT stopped tracking my cards and the overlay started looking funny (as seen in the screenshot).I tried resetting the heartstone path to its new location, as well as messing with the HDT settings, but nothing worked. I also tried deleting HDT and re downloading it but that didn't work. Any ideas on how to fix this?

**Comment by Epix37** [comment]
Try reinstalling Hearthstone as well as the suggestions here: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#not-working

**Comment by CloudyWolf707** [comment]
tried everything you it said as well as reinstalling hearthstone, nothing. the last bullet point in the FAQ talks about where the logs are being created to and then trails off, where should the log files be written to?

**Comment by riQQ** [comment]
They are created at `<Hearthstone Installation Directory>\Logs`.
