### ISSUE TITLE
Deck Tracker Crashes When Making New Deck

### ISSUE THREAD

**Issue by Pirri123** [Epix37/Hearthstone-Deck-Tracker#1946]
I was trying to create a new deck, but shortly after selecting the class the program crashed, I already tried to reinstall the deck tracker but it still crashes anyways.
[Crash report 212016-029.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/76146/Crash.report.212016-029.txt)

**Comment by riQQ** [comment]
Try reinstalling / repairing your .NET Framework installation.
