### ISSUE TITLE
problem with HDT

### ISSUE THREAD

**Issue by hosainkun** [Epix37/Hearthstone-Deck-Tracker#1947]
I downloaded the ZIP and there is no "Hearthstone deck tracker.exe"
there's only ""HDTHelper.exe", "HDTUninstaller.exe", and "HDTUpdate.exe".

**Comment by riQQ** [comment]
Do you run any antivirus software? How big is the archive after downloading?

**Comment by Epix37** [comment]
Chances are you downloaded the wrong zip. See here: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#no-exe
