### ISSUE TITLE
Can't export : name of the cards...

### ISSUE THREAD

**Issue by Azhellarke** [Epix37/Hearthstone-Deck-Tracker#1948]
Hello,
I download HDT a few week, and I never could export a deck correctly, because of the name of the card the tracker write. I'm french so I play with HS in french and I have configure HDT in french too.
When I export a deck, the tracker write tha name of the card and a name of someone, and it continues without delete the text... I just try to export a deck, and when the tracker finish (forgetting 14 cards, the last result of the text research is : "el’thuzad chris robinsonsiphonner l’âme tyler walpolecrache-vase nate bowdenplaie funeste raymond swanlanddestrier de l’effroi alex horley orlandellibaron vaillefendre ralph horsleyéruption de diablotins jaemin kim" =/

**Comment by Epix37** [comment]
I'm not entirely sure what's causing this but the next release will have an option to force clear the search box between cards. That should hopefully help.
