### ISSUE TITLE
Priest , Paladin and Warrior cards are missing.

### ISSUE THREAD

**Issue by lessismoremate** [Epix37/Hearthstone-Deck-Tracker#1949]
Hey there, there is something wrong with my hs decker.priest paladin and warrior's class cards are missing, but other cards are included. i dont know what to do really, i hope you can help me. Cheers!

**Comment by orionok1** [comment]
it has to be something about turkish characters. druid  paladin  and warrior all has i letter

**Comment by lessismoremate** [comment]
so , what is the solution then :P

**Comment by riQQ** [comment]
You can find a possible solution in issue #1906.

**Comment by lessismoremate** [comment]
i fixed my problem by changin my religion, i hope this issue will be gone on next  patch. thank you !

**Comment by NoHuman** [comment]
converting to another religion won't help much kappa

**Comment by andburn** [comment]
@lessismoremate what region did you change from and to, it may help solve the problem? Did you change from Turkish to English too?

**Comment by Epix37** [comment]
Closing in favor of #1906.
