### ISSUE TITLE
Can't run Hearthstone.Deck.Tracker-v0.13.7

### ISSUE THREAD

**Issue by haojiex** [Epix37/Hearthstone-Deck-Tracker#1951]
So I got this crash report. I am not sure if the problem is posted already. I have installed .NET framwork 4.5 and I am runnin Windows 10.

Thanks in advance.

[Crash report 312016-216.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/76829/Crash.report.312016-216.txt)

**Comment by haojiex** [comment]
Tried running as administrator, and running with different version of windows 8, 7 etc.

**Comment by Epix37** [comment]
No idea why this happens. The crash will be fixed with the next release though.
