### ISSUE TITLE
Won't type anything on search box

### ISSUE THREAD

**Issue by icetbr** [Epix37/Hearthstone-Deck-Tracker#1953]
Windows 10, HDT 0.13.7
Tried reinstalling HDT (deleted preferences directory) and restarted the computer even.
Everything work fine until the cursor hits the search box, then it stays blinking and nothing happens.

http://pastebin.com/raw/4nPHffrX

Thanks

**Comment by riQQ** [comment]
The fix for this problem has already been implemented (#1911) and will probably be integrated in the next version.
