### ISSUE TITLE
Problems Exporting Decks

### ISSUE THREAD

**Issue by livejamie** [Epix37/Hearthstone-Deck-Tracker#1955]
I've been having troubles exporting decks to Hearthstone. I tried the disable auto filtering workaround, and changing the speed to slow.

Here's my most recent two tries:

Log: http://paste.ee/p/JUlsC
Result: 
![image](https://cloud.githubusercontent.com/assets/49513/12102437/f58dc516-b2f7-11e5-9503-719e85cf1fbb.png)

Log: http://paste.ee/p/HYM7s
Result: 
![image](https://cloud.githubusercontent.com/assets/49513/12102502/6b011488-b2f8-11e5-9aaa-01cd9a362b54.png)

My resolution is 1920x1080 and it's set in the HS Settings.

I've tried fullscreen and windowed mode.

I'm running Windows 10.

**Comment by livejamie** [comment]
Display scaling doesn't make a difference, same behavior at 100, 125 and 150%

**Comment by Epix37** [comment]
Please enable `options > tracker > settings > show log` and set `options > tracker > logging > log level` to 1, then try again and post the log again.
