### ISSUE TITLE
crash with signature incorrect

### ISSUE THREAD

**Issue by appleken** [Epix37/Hearthstone-Deck-Tracker#1957]
HDT crash while new a deck and finish games.The crash report have the errors about signature incorrect.Here are the logs.I do install the .net 4.5 4.6 and repair it already. Delete the config.xml too. It seems wrong with hearthstats auto upload new deck and auto upload games, if 
I uncheck them, it won't crash. Please help.

########## 2016/1/5 下午 02:44:57 ##########
System.Windows.Markup.XamlParseException: 引動過程的目標傳回例外狀況。 ---> System.TypeInitializationException: 'MS.Internal.SystemXmlLinqExtension' 的類型初始設定式發生例外狀況。 ---> System.BadImageFormatException: [C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll] 簽章不正確。
   於 System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   於 System.Reflection.RuntimePropertyInfo.get_Signature()
   於 System.Reflection.RuntimePropertyInfo.get_PropertyType()
   於 System.ComponentModel.ReflectTypeDescriptionProvider.ReflectGetProperties(Type type)
   於 System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetProperties()
   於 System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor.System.ComponentModel.ICustomTypeDescriptor.GetProperties(Attribute[] attributes)
   於 System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor.System.ComponentModel.ICustomTypeDescriptor.GetProperties(Attribute[] attributes)
   於 System.ComponentModel.CustomTypeDescriptor.GetProperties(Attribute[] attributes)
   於 MS.Internal.Xml.Linq.ComponentModel.XTypeDescriptor`1.GetProperties(Attribute[] attributes)
   於 MS.Internal.Xml.Linq.ComponentModel.XTypeDescriptor`1.GetProperties()
   於 System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor.System.ComponentModel.ICustomTypeDescriptor.GetProperties()
   於 System.ComponentModel.TypeDescriptor.GetPropertiesImpl(Object component, Attribute[] attributes, Boolean noCustomTypeDesc, Boolean noAttributes)
   於 System.ComponentModel.TypeDescriptor.GetProperties(Object component)
   於 MS.Internal.SystemXmlLinqExtension..cctor()
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 MS.Internal.SystemXmlLinqExtension..ctor()
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlReader templateReader, XamlObjectWriter currentWriter)
   於 System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlObjectWriter objectWriter)
   於 System.Windows.FrameworkTemplate.LoadOptimizedTemplateContent(DependencyObject container, IComponentConnector componentConnector, IStyleConnector styleConnector, List`1 affectedChildren, UncommonField`1 templatedNonFeChildrenField)
   於 System.Windows.FrameworkTemplate.LoadContent(DependencyObject container, List`1 affectedChildren)
   於 System.Windows.StyleHelper.ApplyTemplateContent(UncommonField`1 dataField, DependencyObject container, FrameworkElementFactory templateRoot, Int32 lastChildIndex, HybridDictionary childIndexFromChildID, FrameworkTemplate frameworkTemplate)
   於 System.Windows.FrameworkTemplate.ApplyTemplateContent(UncommonField`1 templateDataField, FrameworkElement container)
   於 System.Windows.FrameworkElement.ApplyTemplate()
   於 System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   於 System.Windows.UIElement.Measure(Size availableSize)
   於 System.Windows.Controls.Border.MeasureOverride(Size constraint)
   於 System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   於 System.Windows.UIElement.Measure(Size availableSize)
   於 System.Windows.Controls.Control.MeasureOverride(Size constraint)
   於 System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   於 System.Windows.UIElement.Measure(Size availableSize)
   於 System.Windows.Controls.VirtualizingStackPanel.MeasureChild(IItemContainerGenerator& generator, IContainItemStorage& itemStorageProvider, IContainItemStorage& parentItemStorageProvider, Object& parentItem, Boolean& hasUniformOrAverageContainerSizeBeenSet, Double& computedUniformOrAverageContainerSize, Boolean& computedAreContainersUniformlySized, IList& items, Object& item, IList& children, Int32& childIndex, Boolean& visualOrderChanged, Boolean& isHorizontal, Size& childConstraint, Rect& viewport, VirtualizationCacheLength& cacheSize, VirtualizationCacheLengthUnit& cacheUnit, Boolean& foundFirstItemInViewport, Double& firstItemInViewportOffset, Size& stackPixelSize, Size& stackPixelSizeInViewport, Size& stackPixelSizeInCacheBeforeViewport, Size& stackPixelSizeInCacheAfterViewport, Size& stackLogicalSize, Size& stackLogicalSizeInViewport, Size& stackLogicalSizeInCacheBeforeViewport, Size& stackLogicalSizeInCacheAfterViewport, Boolean& mustDisableVirtualization, Boolean isBeforeFirstItem, Boolean isAfterFirstItem, Boolean isAfterLastItem, Boolean skipActualMeasure, Boolean skipGeneration, Boolean& hasBringIntoViewContainerBeenMeasured, Boolean& hasVirtualizingChildren)
   於 System.Windows.Controls.VirtualizingStackPanel.MeasureOverrideImpl(Size constraint, Nullable`1& lastPageSafeOffset, List`1& previouslyMeasuredOffsets, Nullable`1& lastPagePixelSize, Boolean remeasure)
   於 System.Windows.Controls.VirtualizingStackPanel.MeasureOverride(Size constraint)
   於 System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   於 System.Windows.UIElement.Measure(Size availableSize)
   於 System.Windows.ContextLayoutManager.UpdateLayout()
   於 System.Windows.UIElement.UpdateLayout()
   於 System.Windows.Controls.ItemsControl.OnBringItemIntoView(ItemInfo info)
   於 System.Windows.Controls.ItemsControl.OnBringItemIntoView(Object arg)
   於 System.Windows.Controls.ListBox.ScrollIntoView(Object item)
   於 Hearthstone_Deck_Tracker.Controls.DeckPicker.DeckPicker.SelectDeckAndAppropriateView(Deck deck)
   於 Hearthstone_Deck_Tracker.Windows.MainWindow.<SaveDeck>d__1.MoveNext()
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[下午 02:44:20] LogReaderManager: LogReaders could not be stopped, stop already in progress.
[下午 02:44:20] Game: -------- Reset ---------
[下午 02:44:20] Player Name: 
[下午 02:44:20] Opponent Name: 
[下午 02:44:20] OpponentSecrets: Cleared secrets
[下午 02:44:20] : Checking for duplicate matches...
[下午 02:44:20] GameEventHandler: Reset constructed importing
[下午 02:44:21] BackupManager: Running BackupManager
[下午 02:44:21] BackupManager: Backup for today already exists
[下午 02:44:21] PluginManager: Loading Plugins...
[下午 02:44:21] Helper: Checking for LIVE updates...
[下午 02:44:21] Helper: Current version: 0.13.7.0
[下午 02:44:21] Helper: Latest LIVE version: 0.13.7.0

**Comment by riQQ** [comment]
What was the solution for this problem?
