### ISSUE TITLE
Causing Outlook 2013 to crash

### ISSUE THREAD

**Issue by syntax53** [Epix37/Hearthstone-Deck-Tracker#1958]
I realize this is probably the fault of Microsoft but maybe you have some insight.  I run Microsoft Outlook 2013 and whenever I have Hearthstone Deck Tracker open my Outlook constantly crashes.  It only crashes when HDT is also open and is otherwise very stable.

**Comment by Epix37** [comment]
No idea why this happens or what I could do about it :/.

Never heard of it before, so doesn't seem to be a very wide spread issue either.

**Comment by syntax53** [comment]
I realize this is closed, but just wanted to add that 9 months later this is still a pain in the a$$ :)  I still can't use HDT and Outlook simultaneously.  Well, Outlook runs fine as long as I don't click on it while HDT is running.  Without HDT running Outlook never crashes.
