### ISSUE TITLE
Missing font in game

### ISSUE THREAD

**Issue by lNoobInside** [Epix37/Hearthstone-Deck-Tracker#1960]
I've bought a new PC and installed Hearthstone Deck Tracker.
Everything was fine, until I've started a match. When I'm in game I can't see the name of cards in my deck. I've tryed to download the tracker again, but didn't work.
![immagine](https://cloud.githubusercontent.com/assets/16574966/12141466/d0f4477e-b46f-11e5-994b-c2adec6af98b.png)

**Comment by Epix37** [comment]
This is a issue with some DPI settings. See here: https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1355#issuecomment-136633403
