### ISSUE TITLE
Fail to run the client in windows10 x64

### ISSUE THREAD

**Issue by wangtianze** [Epix37/Hearthstone-Deck-Tracker#1965]
With all the paths setting true, when I click "Start Launcher/Hearthstone" button inside HDT, a window burst out, asking me to find a new application to open battlenet, and it only has one option --find it in the application store. then the HDT show a warning saying that "Error starting battle.net launcher". 
I also tried directly opening the battle.net launcher and Hearthstone, but the HDT didn't work correctly. It didn't show correct data , nor did it record any deck.
I've tried many other ways such as delete the HDT's AppData folder in my C:/, but it didn't work.
I wonder how to solve this problem, as the HDT is really a good helper. 
THX!~

**Comment by riQQ** [comment]
What doesn't work, If you start HDT and Battle.net client separately?

**Comment by wangtianze** [comment]
I've tried it this way, but it seems that HDT just can't get data from the game. It cannot read my deck. and it also cannot show the proper data. so sad...

**Comment by wangtianze** [comment]
As a non-native speaker, sorry for my poor English.

**Comment by riQQ** [comment]
Are there any logs in the directory `<Hearthstone Install dir>\Logs`?
