### ISSUE TITLE
Bugs with Elise

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#1966]
Quite a few bugs when using Elise. For instance, after playing the Golden Monkey, the number of cards in mine and opponent's hands are incorrect, as well as the number of cards in our decks, and the fatigue count. Actually, HDT blacks out all the cards in my deck, and assumes I have no more cards so it immediately starts counting fatigue damage. Instead, it should probably black all cards out, but keep the number of cards in my deck correct.

Also, I noticed that after an Elise game that went to fatigue, I had to restart HDT because it was bugging out on the next game. It showed duplicate copies of every card played for some reason (in the game following the Elise game).

**Comment by soldierswitheggs** [comment]
I got this bug too, at least partially.  After playing the Golden Monkey, HDT started counting fatigue incorrectly, as if assuming I had no more cards in my deck.  However, I had no issues once I started a new game.

**Comment by jeyraof** [comment]
It is also to me.

**Comment by Epix37** [comment]
Fixed with c9f752f. Closing in favor of #2185.

**Comment by riQQ** [comment]
You mean bde4e165b8c0245d7600d7c468c6ece39efcaa37?
