### ISSUE TITLE
Deck autoselection doesnt work

### ISSUE THREAD

**Issue by talmantel** [Epix37/Hearthstone-Deck-Tracker#1967]
I have a deck chosen, lets say a warlock deck. When i play any other deck the deck tracker doesn't auto pick the deck i am using (even though there is only one matching deck to the hero I am playing)
And doesn't open a dialog for to pick from the correct deck. It just shows me on the top left that there are some missing cards, and In the end of the game it asks me if i want to discard, save or move to another deck. When i choose to move it to another deck it does recognize the deck I was playing and shows me it in the deck choosing dialog (and only it)

**Comment by Epix37** [comment]
Please reproduce the issue and post the log. ([See here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues))

The deck it supposed to switch to might also be helpful. Screenshot or copy IDs via `EXPORT`.

**Comment by talmantel** [comment]
log of 2 games i played: http://pastebin.com/4nwpgZi2
first I played a renolock and i think it was still stuck on my earlier game with echo mage
then i played a paladin and it showed me the renolock cards.

there is no specific deck that doesnt work. its all of them. whenever i switch decks in game (in all gamemodes) the deck tracker shows me im missing cards but doesnt offer me to pick a deck, and doesnt pick it automatically

**Comment by Epix37** [comment]
Do you still have this problem with the v0.13.19 pre-release? https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.13.19
