### ISSUE TITLE
turn timer changed

### ISSUE THREAD

**Issue by Labyala** [Epix37/Hearthstone-Deck-Tracker#1968]
Hello

The turn timer has been changed.
It's no more 90sec but 70sec and the appearance of the rope is after 50sec.

Can you fix it please ? thanks.

**Comment by Epix37** [comment]
Is there an official source for that?

**Comment by culinko** [comment]
Timeout is still 75, nothing changed since beta.

**Comment by Labyala** [comment]
Why did you closed ? 
Your tracker have a 90sec timeout instead of 70sec (72sec exactly). 
I don't find official source; Blizzard changed timer without communicating. but you can time yourself in a game.

**Comment by riQQ** [comment]
You can already choose between 75 and 90 seconds turn time at `Options > Tracker > General`.

**Comment by Epix37** [comment]
See #1007 for further explanation on how the timer exactly works.

**Comment by Labyala** [comment]
thanks to riQQ, i hadn't see that in options.
And Thanks to Epix and congratulations for your job, this tracker is very helpful
