### ISSUE TITLE
hearthstone deck tracker opening error

### ISSUE THREAD

**Issue by CavaDio** [Epix37/Hearthstone-Deck-Tracker#1969]
when i try to open the .exe, deck tracker logo appears ,right after stops working and then crash.

[Crash report 712016-2051.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/81657/Crash.report.712016-2051.txt)

thanks for your help

**Comment by riQQ** [comment]
This is hopefully fixed with the next version. Right now you can move the HDT some place outside `C:\Users\<Account name>`.

**Comment by Mavericxx** [comment]
I had the same and when it was working again all of my decks were gone

**Comment by Epix37** [comment]
HDT generates daily backups. You can restore those under `options > tracker > backups`.
