### ISSUE TITLE
Stutter after deleting "log.config" and uninstalling HDT

### ISSUE THREAD

**Issue by Revenants** [Epix37/Hearthstone-Deck-Tracker#1970]
So yesterday i installed HDT and had a great time with it. Today my Hearthstone was super stuttery and i immediately looked for a fix. I've tried all of them so far and none of them have worked. I have deleted "log.config", made an exception for the Hearthstone Folder in Windows Defender, Re-installed Hearthstone and the lag/stutter is still present in certain actions off the game (Card Draw/Card Play/Hero Attack and many more), also when i move my mouse too fast around the board the fps drops significantly(the effects on the scenario freeze/stutter). I run a PC which can play Skyrim on Ultra so the hardware is not the problem. I also have all the latest drivers and BIOS. I am desperate for help as i think in some weird way HDT did something that screwed with my Hearthstone. Any guesses?

**Comment by ClothTiger** [comment]
I'm experiencing the same thing. It just started today. I played for several hours yesterday without any issue. Stutter in-game, and I only can't movie the HDT window around without it stuttering like crazy.

**Comment by ClothTiger** [comment]
I'll add that I tried playing Heroes of the Storm and had similar issues. WoW on the other hand works fine, but it's not impossible there's some kind of problem at Blizzard's end rather than HDT's.

**Comment by ClothTiger** [comment]
I've solved the problem at my end.

I turned off Nvidia Shadowplay, shut down Fraps and set HDT to Windows 7 compatibility mode. I don't think the last two have anything to do with it tho. Interesting enough it still works after I've turned it back on again.

Hopefully this solves the issue for you as well.

**Comment by Revenants** [comment]
Thanks!! I'll try it out

**Comment by Revenants** [comment]
Turns out my computer doesn't even have shadowplay enabled so its for sure something to do with HDT. Like i installed it and the next day HS starts lagging, so def not a coincidence. Any other ideas ??????

**Comment by Epix37** [comment]
The only "modification" HDT makes should be the log.config, so after deleting that (and not starting HDT again) everything should be back to normal.

What has me most confused though is that it worked for a day. If there were any problems with HDT it should have started immediately. Did you make any other modifications to your system? Windows updates maybe? You could try restoring your system to a few days ago if possible.

**Comment by Revenants** [comment]
The lag started when i didnt use the HDT. I didnt change anything since the
day i installed HDT so a rollback wont change anything. The fps lag is
super specific, by example when i move my mouse too fast accros the HS
screen it lags a lot.(-20 decrease). It also lags in card draw or anything
too sparkly.
