### ISSUE TITLE
displaying "select replay" instead of "games and statistics"

### ISSUE THREAD

**Issue by LordJester** [Epix37/Hearthstone-Deck-Tracker#1971]
When i choose option "games and statistics", im being given the same display as for "select replay". Any thoughts?

**Comment by Epix37** [comment]
That is correct. Doubleclick a game (or click "show replay" at the botton) to open the replay.

**Comment by LordJester** [comment]
Ty for response. I realize that, but im telling that i cant get complete statistics of the games, im only getting the list of the single games. If i chose option "games and statistics", i getting the same results as if i chose "select replay". Tyvm for tryin to help.

**Comment by Epix37** [comment]
It's just using the same dialog because there was no reason to create a new one for the replay selection.

What "complete statistics of the games" are you looking for?

**Comment by LordJester** [comment]
Ty for your patience. I cant get the left pic, only the right.

https://camo.githubusercontent.com/6c617408a1f343755145eceee43e30d48be75081/687474703a2f2f692e696d6775722e636f6d2f576b65334375772e706e67

**Comment by Epix37** [comment]
There's a "stats" and a "games" tab, make sure to click the former.

**Comment by LordJester** [comment]
Yes, and when i click games in the stats tab, i get right pic, and should be left? Im i right?

**Comment by Epix37** [comment]
You have to click "stats" to get to the win-loss overview.
