### ISSUE TITLE
.exe fails to open, no error message or crash

### ISSUE THREAD

**Issue by cooken** [Epix37/Hearthstone-Deck-Tracker#1972]
Hi All

Hoping someone can help me with this problem.  When I run the program, the loading cursor pops up for a brief second and then nothing happens.

Anyone else?

Thanks

**Comment by limestud** [comment]
I'm having problems to open it too in windows 7 and error says: you need to install previous version of .NET framenetwork: v4.0 please contact the program editor on how to obtain the correct version.

**Comment by riQQ** [comment]
https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#not-starting

**Comment by cooken** [comment]
.NET repair doesn't fix for me

**Comment by riQQ** [comment]
Do you have at least .NET version 4.5? Try reinstalling. Is there anything regarding HDT in the windows event logs?

**Comment by cooken** [comment]
Hi riQQ

I have at least .NET 4.5.  The following occurs in the event log:

Fault bucket 128978991055, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Hearthstone Deck Tracker.exe
P2: 0.1.0.0
P3: 56740b62
P4: mscorlib
P5: 4.6.1063.1
P6: 565363c9
P7: 40fd
P8: 0
P9: System.Windows.Markup.XamlParse
P10: 

Attached files:
C:\Users\Me\AppData\Local\Temp\WERD5A9.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Hearthstone Deck_f79ba3a81f381e4834ff7154615559e3749bd4f_84f8a2e7_1dc9dff9

Analysis symbol: 
Rechecking for solution: 0
Report Id: 798b63d7-0bab-4849-8227-ecd1711ca1bf
Report Status: 0

**Comment by riQQ** [comment]
Did you reinstall .Net 4.5? Is Visual C++ redistributable installed? If you don't use a windows admin account, try starting with admin rights.
