### ISSUE TITLE
Games are not recording most of the time. Log included.

### ISSUE THREAD

**Issue by MarineKingAizen** [Epix37/Hearthstone-Deck-Tracker#1979]
LOG ATTACHED

Hi Epix, I currently have v0.13.7 and I am still experiencing the same problem I've had for a while now, games are not recording. Every once in a while a few games will record, but most often they won't.

In that attached log, I played 3 games and none of them recorded, neither for the deck nor under All Games, I checked for all modes as well and nothing. It's as if the tracker missed the entire session. I've attached the log for todays 3 games, perhaps you can shine some light on the issue. Thanks.
[hdt_log.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/85542/hdt_log.txt)

ps. I also made this post in an old thread, but I'm not sure it would be seen due to the threads age, so please forgive me if I wasn't supposed to make a double post about this issue.

**Comment by Epix37** [comment]
No need to open duplicate issues.
