### ISSUE TITLE
Nothing "uploads" to HearthStats

### ISSUE THREAD

**Issue by GunnarStahl** [Epix37/Hearthstone-Deck-Tracker#1980]
Hey guys!

I just setup HDT. However, even if I am logged in HearthStats, the program doesn't seem to upload my decks, and matches to HearthStats at all.

I can't see nothing there. I have 5 deck in my programs, and a few matches which doesn't appear on the website I am logged in.

I tried to SYNC, to FORCE FULL SYNC and yet, nothing!

**Comment by Epix37** [comment]
Please restart HDT and use `FORCE FULL SYNC` again. Then post the log here. [See here.](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)

**Comment by GunnarStahl** [comment]
http://pastebin.com/1GWvCt1n

There you go.

**Comment by GunnarStahl** [comment]
So?

**Comment by riQQ** [comment]
Could you upload your `DeckStats.xml` from `%APPDATA%\HearthstoneDeckTracker`.

**Comment by GunnarStahl** [comment]
Sure.

http://pastebin.com/TxVpTF8f

**Comment by GunnarStahl** [comment]
I have created a few new decks today, and all four of them uploaded to HearthStats.
However, my other deck are still not on HearthStats.

Thank you.

**Comment by riQQ** [comment]
I'm sorry, I need the `PlayerDecks.xml`, too.

**Comment by GunnarStahl** [comment]
Sure.

http://pastebin.com/etZW7wRi

**Comment by riQQ** [comment]
There's no deck `Main Druid` in your `PlayerDecks.xml`. That's the one causing the error in the log. So the error is probably caused by trying to upload games that don't belong to a deck.

**Comment by GunnarStahl** [comment]
Ok. How do I fix that then.

**Comment by riQQ** [comment]
Create a new deck and assign these games to the new one via `Move to other deck` at `Stats > [Old] Games & Statistics`.

**Comment by GunnarStahl** [comment]
Nope. Nothings works ever after I did move the game. I can see my new 4 decks, but none of the older ones and none of my games either.

Force Full Sync Log -> http://pastebin.com/R2iaFGHX
PlayerDecks.xml -> http://pastebin.com/4HQGZKZX
DeckStats.xml -> http://pastebin.com/Q2j9nTcG

**Comment by riQQ** [comment]
It tested it with your files and got the upload to work:
- Clone the deck `Ramp Druid` without matches
- Go to `Stats > [Old] Games & Statistics` and select all matches of the old `Ramp Druid` and click `Move to other deck` to move them to the new clone
- `Force full sync`

**Comment by GunnarStahl** [comment]
Still doesn't work.

Since I don't have LOTS of games, I will delete all my data and start all over. I really don't mind.

If it works that way, I'll simply close the issue report.

Thanks for your help riQQ :)

**Comment by riQQ** [comment]
Deleting all these games should suffice.

**Comment by GunnarStahl** [comment]
Deleted all my games, and still, my "old" decks aren't showing on the website.

**Comment by GunnarStahl** [comment]
Deleted every decks in HDT that wasn't showing in HearthStats and redid them. Everything seems okay now.
Thanks for your help riQQ!
