### ISSUE TITLE
Suggestion: support for reconnecting games

### ISSUE THREAD

**Issue by jippiedoe** [Epix37/Hearthstone-Deck-Tracker#1981]
My internet sometimes lags out a bit, resulting in disconnecting from a hearthstone game and the game automatically almost instantly reconnecting. No problem, except the tracker goes crazy when this happens: suddenly my opponents deck apparently had 43 cards left in it, I hadn't drawn any yet but yet still had a full hand, etc. Would be nice if the tracker remembered the draws from before the disconnect, and was able to continue on that instance after reconnecting.

**Comment by Epix37** [comment]
known issue - #922

no ETA on this though.
