### ISSUE TITLE
All of my Decks just deleted pls help

### ISSUE THREAD

**Issue by Mavericxx** [Epix37/Hearthstone-Deck-Tracker#1982]
Today i opened my Decktracker before i started to play and it was just empty, all my decks stats and so on are just gone pls Help if possible maybe the data is saved anywhere or something.
Thank you

**Comment by riQQ** [comment]
There should be a backup folder at `%APPDATA%\HearthstoneDeckTracker\Backups`. Extract the latest one to `%APPDATA%\HearthstoneDeckTracker`.

**Comment by Mavericxx** [comment]
ty <333
