### ISSUE TITLE
Recording everything as Casual even in Ranked

### ISSUE THREAD

**Issue by kingdru** [Epix37/Hearthstone-Deck-Tracker#1983]
Basically what my title says.  Every game I play regardless of casual or ranked is recorded as casual.  I saw past issues but there was never an answer or resolve.

**Comment by kak4477** [comment]
This only happens to me when I lower game's resolution. It works fine on the top available one (1600x900) which matches my desktop.

**Comment by Epix37** [comment]
#1889
