### ISSUE TITLE
Overlay works but game history not recorded + Import Glitch

### ISSUE THREAD

**Issue by lunarwolfspirit** [Epix37/Hearthstone-Deck-Tracker#1987]
Overlay works during games fine, but game history is not being saved.

I'm also experiencing an import glitch using NetDeck in Chrome, where Ragnaros the Firelord imports as the Brawl boss 0 mana card

**Comment by riQQ** [comment]
First problem: are the games not recorded ranked? maybe they are detected as casual (known bug) and you have tracking casual turned off.

Second problem: it's a known bug and fixed with the upcoming release.

**Comment by lunarwolfspirit** [comment]
First Problem: Yes, these are ranked games. However, I already only have "Record for Ranked" ticked... Would there be anything else I could check to potentially debug this?

**Comment by riQQ** [comment]
Workaround for the first problem is turning on tracking for casual games and change back the game mode of the ranked games that are mistakenly detected as casual.

**Comment by Epix37** [comment]
#1907 #1889
