### ISSUE TITLE
will not launch

### ISSUE THREAD

**Issue by oiyscoundrels** [Epix37/Hearthstone-Deck-Tracker#1993]
i have .NET framework 4.6 and tried to install and reinstall the newest version of the deck tracker many times, when i launch the file with hearthstone a black screen comes up and then it crashes, i saw other people are having simular problems

**Comment by riQQ** [comment]
Is there anything in the windows event logs? Is there a crash message? Are there any logs at `%AppData%\HearthstoneDeckTracker\Logs`?

**Comment by oiyscoundrels** [comment]
it does say global program name hearthstone at the top of a completely black screen before it crashes

**Comment by riQQ** [comment]
Could you answer the other question, too?
