### ISSUE TITLE
New update broke my HS config?

### ISSUE THREAD

**Issue by d07RiV** [Epix37/Hearthstone-Deck-Tracker#1994]
I've just updated HDT from a version from several months ago, and it seems that it changed my HS config, preventing it from writing log files.

After the update, my log.config contained the following:

    [Zone]
    LogLevel=1
    FilePrinting=true
    ConsolePrinting=false
    ScreenPrinting=false
    Verbose=true

Checking the output_log.txt, its last-modified time is a couple hours ago, around when I updated the tracker. The old version worked fine (except it didn't recognize new cards), but the new one didn't interact with Hearthstone at all.

Changing `FilePrinting` to `false` and `ConsolePrinting` to `true` fixed the issue.

**Comment by riQQ** [comment]
`Output_log.txt` isn't used anymore. The separate logs like `Power.log` in `<HearthstoneDir>\Logs` are used now.

**Comment by d07RiV** [comment]
Oh, but still, the tracker didn't work after the update, and after I changed log.config back, it started working again. *shrug*

**Comment by riQQ** [comment]
Which version are you using?
