### ISSUE TITLE
Plugins - Displaying a list of dead creatures

### ISSUE THREAD

**Issue by falconmick** [Epix37/Hearthstone-Deck-Tracker#2000]
Hi @Epix37 

Love your plugin functionality so far, it's been really useful. I'm just heading off now having completed a tool which monitors the graveyard and allows me to filter it to show all the murlocs that have died. Tomorow I was hoping to display this as a friendly list like the deck tracker does. Care to point me in the right direction? I am currently saving the Hearthstone_Deck_Tracker.Hearthstone.Card but I can change it to save Hearthstone_Deck_Tracker.Hearthstone.CardEntity if that helps.

Fyi: I'm using this in my current project to make an Anyfin Can Happen Damage Calculator :)

Cheers again on the project, it's awesome :+1:

**Comment by Epix37** [comment]
Hearthstone.Card has a `Background` property, which is the complete card image. You can throw those in some list.
