### ISSUE TITLE
Crash when creating or importing new deck.

### ISSUE THREAD

**Issue by rappleby** [Epix37/Hearthstone-Deck-Tracker#2001]
As described, crash report attached.
[Crash report 1912016-1121.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/95807/Crash.report.1912016-1121.txt)

**Comment by Epix37** [comment]
Try downloading the latest version again and see if works with that. ([v0.13.7](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.13.7))
