### ISSUE TITLE
Hearthstone crashes after Arena Awards pop-up is submitted

### ISSUE THREAD

**Issue by draav** [Epix37/Hearthstone-Deck-Tracker#2004]
After completing and Arena Run, the Awards menu will appear. I will click on the key to see my rewards, then enter the rewards. After I submit, Hearthstone crashes. gives me some strange error I forgot to copy. I can copy it next time if needed.

Nothing is wrong with the tracker and the arena runs saves correctly with the rewards. Hearthstone opens normally when I go back and open it.

Random other things, not sure if relevant:
- This entire time the Awards pop up remains the front most window on screen, despite which window I click on. 
- I pretty much always play in windowed mode not full screen. 
- I think all of battle.net crashes, not just hearthstone. Don't really remember though.

pastebin: http://pastebin.com/nc7Bp2Tm

**Comment by culinko** [comment]
"NetDeckClipbardCheck: System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))"

This would suggest that a NetDeck plugin might have to do something with this crash.

@n4ru You might take a look at this.

**Comment by n4ru** [comment]
It looks like a permissions issue on Alex's end. My extension can't throw errors like that since it's pure JS.

**Comment by Epix37** [comment]
The exception has most likely nothing to do with it.

This could be a driver problem. Try updating your graphics card driver.
