### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by s4rik4** [Epix37/Hearthstone-Deck-Tracker#2010]
When i start HDT, anything happens. I attached the crash report.

Thx for the help!
[Crash report 2212016-1727.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/101153/Crash.report.2212016-1727.txt)

**Comment by riQQ** [comment]
Fixed with next version (see #1951).

**Comment by s4rik4** [comment]
THX for the help!
