### ISSUE TITLE
Install .EXE = "Not a Valid Win32 Application" error message

### ISSUE THREAD

**Issue by karakenio** [Epix37/Hearthstone-Deck-Tracker#2011]
I have WinXP

=(

**Comment by riQQ** [comment]
HDT doesn't work for Windows XP.

>Requirements:
>- Windows Vista or higher
>- .NET Framework 4.5 or higher

**Comment by karakenio** [comment]
Thanks for the feedback.

- Will it be in future versions?
- Is there any older version that works whit XP?

**Comment by riQQ** [comment]
- I don't think there will be
- No, there isn't

**Comment by Epix37** [comment]
As riQQ said, no WinXP support, sorry.
