### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Aimso12** [Epix37/Hearthstone-Deck-Tracker#2012]
Every time i launch the .exe, the program crashes and stops working, i have already looked in the images folder and the .ico is there

[Crash report 2312016-229.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/102132/Crash.report.2312016-229.txt)

**Comment by riQQ** [comment]
It looks like your starting HDT directly out of the donwloaded zip file. Try extracting the whole zip to some place and then starting the exe.
