### ISSUE TITLE
Deck issue

### ISSUE THREAD

**Issue by Thealchemist22** [Epix37/Hearthstone-Deck-Tracker#2013]
I don't open the program since 1/13/16 and when i try to use it again a fatal error comes up

Weird fact: i can play with the program but i can choose my deck or edit or create on new
[Crash report 2412016-2325.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/102700/Crash.report.2412016-2325.txt)

**Comment by riQQ** [comment]
Try repairing the .NET Framework installation.
