### ISSUE TITLE
Setting up Hearthstone Deck Tracker on Mac

### ISSUE THREAD

**Issue by osumatthew2017** [Epix37/Hearthstone-Deck-Tracker#2016]
I'm not quite certain what I'm doing incorrectly, but I downloaded the file and moved it to applications. When I first opened it, I selected the language and it seemed to download the card archives, but whenever I open the application it has two transparent boxes. The one on the left says cards 0/30, but I can't figure out how to properly record decks or make the tracker function. What do I need to do to get the application to work correctly?

**Comment by Epix37** [comment]
I think you posted on the wrong tracker github. HDT works on windows only. 

You were most likely looking for this one: https://github.com/bmichotte/HSTracker
