### ISSUE TITLE
HDT crashes graphic driver and now won't start

### ISSUE THREAD

**Issue by JamesEarlBones** [Epix37/Hearthstone-Deck-Tracker#2019]
WHen I run HDT, it will cause my video to pause then Windows 10 will tell me my graphic driver stopped and restarted.

Yesterday my entire computer froze and now HDT won't open.  I get the window but just the spinning wheel.  I've uninstalled HDT and redownloaded it.  I've moved it to another folder.  But it the problem remains.

**Comment by riQQ** [comment]
Is your graphics driver up-to-date? Any logs in `%APPDATA%\HearthstoneDeckTracker\Logs`?
