### ISSUE TITLE
Could not load Deck from specified URL

### ISSUE THREAD

**Issue by maksymal** [Epix37/Hearthstone-Deck-Tracker#2020]
Hello,

i tried to import some decks from the web, but it's not working. I tried for example to load the meta snapshot Decks from tempostorm, but i always get the same Error:
"Could not load Deck from specified URL".
I tried it with the versiion 0.13.6 and 7 and with activated and non-activated Kaspersky.

Im running it on Windows 7 64bit. Reinstalling didn't solve the issue.

**Comment by Epix37** [comment]
The website was changed, importing from tempostorm will be fixed with the next update. (#2008)
