### ISSUE TITLE
HDT Chrashes after a game ended

### ISSUE THREAD

**Issue by sonnyvm** [Epix37/Hearthstone-Deck-Tracker#2027]
Hello,

the Tracker always crashes after i finish a game. 

Sorry for the short text, but my english is not the best.

Heres the log:

[Crash report 2812016-1959.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/108718/Crash.report.2812016-1959.txt)

**Comment by riQQ** [comment]
It's a [TwitchPlugin](https://github.com/Epix37/HDT-TwitchPlugin) issue, open an issue over there.

**Comment by Epix37** [comment]
The problem is fixed with TwitchPlugin v0.5.
