### ISSUE TITLE
Paladin secrets don't always grey out properly

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#2028]
Paladin secrets don't always grey out properly, especially Avenge, it seems like. This has happened to me several times recently. I don't recall the exact game this happened though, so I'll have to wait until it happens again, and then post a replay of that game once I get it.

In the meantime, it would be helpful if someone can post a log of a game where this happened to them.

**Comment by Epix37** [comment]
will be fixed with v0.13.8 - see #1918
