### ISSUE TITLE
Why are there asterisks in match history when someone concedes?

### ISSUE THREAD

**Issue by Mistrelvous** [Epix37/Hearthstone-Deck-Tracker#2029]
Not really a bug, but I've always wondered why our wins in match history have to have asterisks next to them just because someone conceded instead of letting us finish them off. 

I understand placing an asterisk next to a win if someone concedes in the first two turns, or if the tracker could possibly distinguish someone disconnecting versus conceding (but even then, sometimes people just flat out leave the client if they are going to lose). These two situations I can understand an asterisk is warranted, but it's just weird to me seeing asterisks next to wins in matches just because someone conceded. Most matches in Hearthstone are ended when someone concedes so I'm not sure why asterisks have to be added next to those wins.

**Comment by Epix37** [comment]
Exactly for the reason you stated, they indicate conceded games. I debated removing them a few times. 

There will be a new statistics UI for constructed soon, I will look info finding a cleaning solution for this.
