### ISSUE TITLE
Crash when opening Friendslist

### ISSUE THREAD

**Issue by lordimac** [Epix37/Hearthstone-Deck-Tracker#2032]
Hello, newest Version 0.13.8 crashes when opening the Friendslist ingame.

**Comment by Epix37** [comment]
Please post the crash report here.

**Comment by lordimac** [comment]
Where can I find the crash report?

**Comment by Epix37** [comment]
The crash message should usually tell you. 

You can find them in `Hearthstone Deck Tracker/Crash Reports`.

**Comment by lordimac** [comment]
It's empty, sorry.

**Comment by sc4rab** [comment]
it does that for me as well, when I hover over bottom left corner area, crashes, mouse cursor lags horribly and I also don't have any crash reports in the folder.

**Comment by Epix37** [comment]
Should be fixed with [v0.13.9](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.13.9).
