### ISSUE TITLE
Decktracker has stopped working

### ISSUE THREAD

**Issue by Jossiemime** [Epix37/Hearthstone-Deck-Tracker#2033]
I dont know what happened, i just downloaded the latest version and now every time i open it, it stays like that for like 5 minutes and then it gives me the error "Hearthstone decktracker has stopped working".Always, without fail.Anyone else with this same problem?

**Comment by everchump** [comment]
you can try this:https://github.com/Epix37/HDT-Test/releases/tag/v0.13.9_PRE1

**Comment by Epix37** [comment]
Should be fixed with [v0.13.9](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.13.9).
