### ISSUE TITLE
Alt tabbing out of Hearthstone for a few seconds crashes HDT 0.13.8

### ISSUE THREAD

**Issue by Fonjask** [Epix37/Hearthstone-Deck-Tracker#2035]
Hey! Been loving the program for a long time now, but since the last update it crashes all the time when I alt-tab (and let's be honest - if I didn't alt-tab and concentrate on the game, I wouldn't even need HDT but fuck that :P). Not sure what you need in order to try and reproduce since I'm sure you don't get this issue, or if the logs already tell you everything or not. Let me know!

What I did:
Start HDT
Start Hearthstone
Start casual match
Alttab on turn 2, crash after 1s
The "Hearthstone Deck Tracker has stopped responding" window comes up and I press "close program"
I restart HDT and tab back into Hearthstone
I play turn 3 and 4, then alttab, crash after < 3 seconds

Crash logs:
[hdt_log_crashonturn2.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/110250/hdt_log_crashonturn2.txt)
[hdt_log_crashonturn5.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/110251/hdt_log_crashonturn5.txt)

Specs:
PC, i5 4670K, R9 280X Tri-X
Windows 10 x64
HDT 0.13.8

**Comment by Fonjask** [comment]
Just saw you updated HDT to 0.13.9, will report back if I still get this issue!

**Comment by Epix37** [comment]
I think this should also be fixed with v0.13.9.

**Comment by Fonjask** [comment]
Yep, 10/10 fix. Thanks for all your work!
