### ISSUE TITLE
HDT not remembering window size after Windows restart

### ISSUE THREAD

**Issue by icyrainz** [Epix37/Hearthstone-Deck-Tracker#2040]
The HDT window size keeps switching back to the default value every time I restart my machine.
Since I'm using a 21:9 monitor, the width of the window somehow stretches to very long.

Is this value calculated based on the screen resolution? It can be an easy fix to save this value locally instead of some volatile directory.

**Comment by Epix37** [comment]
The window size is stored in the config just like anything else. There is a known issue where it doesn't properly restore to maximized after closing.

Could this be related to HDT being force-closed when you shut down your machine?

**Comment by icyrainz** [comment]
I tried close it properly and relaunched it, it did open again with correct size. This happens regardless of when hdt is open or not when i restart the machine. Which cfg file is it being stored to? I can try to do a diff between various scenarios to debug this.

**Comment by Epix37** [comment]
The config is stored under `%AppData%/HearthstoneDeckTracker`

These are the relevant properties:
```
  <TrackerWindowLeft>
  <TrackerWindowTop>
  <WindowHeight>
  <WindowWidth>
```
