### ISSUE TITLE
Replays

### ISSUE THREAD

**Issue by kadlecx** [Epix37/Hearthstone-Deck-Tracker#2042]
Hello, I am pretty new to this site and also to HSDT and I wouldn't call it issue, because I would like to know just one thing. Is there any way how can I take out the replay and make it like a video?

**Comment by Epix37** [comment]
You could record the replayviewer with any recording software I suppose. There is no "export as video", autoplay or any functionality like that, sorry.

**Comment by kadlecx** [comment]
Ok, that's not problem, I want to know if I could play the replay somehow and record it with any recording programs.

**Comment by Epix37** [comment]
You could keep presssing the down arrow to go to the next state, but there's no fancy graphics or animations so I'm not sure it would make for a good recording.

**Comment by kadlecx** [comment]
So I can't make videos like "Funny & Lucky Moments" right?

**Comment by Epix37** [comment]
You *could*, but it's not something I would recomment the current replay viewer for, no. Actual recordings of the game make for a much better video.

**Comment by kadlecx** [comment]
Yes, I know. That's a pity, it would be a good feature and some programs are taking your CPU down, so it's harder to record the game if you have low PC.
