### ISSUE TITLE
Edit rewards + add losses

### ISSUE THREAD

**Issue by LarsEriksson42** [Epix37/Hearthstone-Deck-Tracker#2044]
Issues I would like addressed and that I haven't found a solution to is editing wins and losses, and also rewards, because I sometimes play on the phone and it obviously doesn't track.

Also the disconnects won't get tracked though I'm on the computer, so the stats aren't correct for me. I would really like to get it right, by editing it myself.

Is there a graphical way of identifying and the crosses/losses and number of wins of a arena screen and binding that to the deck in use?

**Comment by Epix37** [comment]
I'm assuming you are talking about arena here? You can manually add games under `STATS > ARENA RUNS > Runs & matches > add/edit/delete game`, on the selected run (`edit rewards` is also possible there`). Adding entire new runs is a matter of creating a new arena deck (can be empty). 


>Is there a graphical way of identifying and the crosses/losses and number of wins of a arena screen and binding that to the deck in use?

Currently not possible.

**Comment by LarsEriksson42** [comment]
Much appreciated, thank you!
