### ISSUE TITLE
Feature Request: Backup settings

### ISSUE THREAD

**Issue by 305jeff** [Epix37/Hearthstone-Deck-Tracker#2045]
I only reset my computer about once per month and usually leave HSDT open. As a result, I sometimes have a month gap between backups, since it saves at first launch each day. Perhaps we could have a setting to enable automatic daily backups, regardless of launch? Or maybe first Hearthstone launch per day causes a backup?

Thanks!

**Comment by Epix37** [comment]
First Hearthstone launch per day sounds like a good solution.
