### ISSUE TITLE
Roaring Torches didn't appear in deck last game

### ISSUE THREAD

**Issue by UnholyRaven** [Epix37/Hearthstone-Deck-Tracker#2047]
I've been playing brawl for several hours and in the last game I got a weird bug. Roaring Torches didn't appear in my deck after I had played Forgotten Torches. I noticed this only when my Reno had failed several times.

Could it be connected with that I had discovered 3rd Forgotten Torch from Ethereal Conjurer?

Moreover, there are no "Found known cardId for entity" and "Player CreateInDeck" lines in logs for Forgotten Torches for the last game.

HDT version - 0.13.7

[HDT_logs.zip](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/110970/HDT_logs.zip)

**Comment by Epix37** [comment]
Should be fixed.
