### ISSUE TITLE
Secret list not removed after all were triggered

### ISSUE THREAD

**Issue by knoxius** [Epix37/Hearthstone-Deck-Tracker#2049]
hi! i'm here to report yet another bug:)

there were many traps in that game, so i am not 100percent sure the order they went and when exactly the bug happened, but the last trap i triggered was bear trap, and i am about 90 percent sure it's when they all greyed out (although it should have disappeared).

screenshot: http://imgur.com/06X4nDW

replay screenshots: http://imgur.com/a/2IgEY

if there is any other way i can be  more informative, let me know.

edit: i am sorry, i don't want to be misleading. what i mean is, i think the bug is that all of the trap names _**should have disappeared**_ after traps have been triggered and there were _**no secrets left**_. i hope this will make it more clear now:)

**Comment by culinko** [comment]
Probably one of the hunter traps has a similar bug as Avenge (#2038).

**Comment by Epix37** [comment]
There is no delayed detection for hunter secrets, so it being the same problem as Avenge is unlikely. 

The hiding is also rather isolated and only depends on an special counter that is changed on triggered/played/stolen. So I'm not really sure how this happened. 

@knoxius: Logs from old sessions are stored in `%AppData%/HearthstoneDeckTracker/Logs` (Win+R, paste), could you upload the one that corresponds to that game?

**Comment by knoxius** [comment]
here you go. the mentioned map starts at:

[23:52:09] Opponent Name: SandmanSDM

[hdt_log.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/111225/hdt_log.txt)

**Comment by culinko** [comment]
According to the log, it started with Kezan Mystic stealing Bear Trap (it also set Snipe, Mirror Entity and Repentance to zero - Kezan's battlecry steals secrets before they proc, so this is also a bug). The opponent's secret list disappeared in my case, but the overlay was really wonky, for example the highlight for drawing a card on my decklist would get interrupted in the middle and remain like this for a couple of seconds.

**Comment by culinko** [comment]
It seems like the Bear Trap you stole with Kezan Mystic was never triggered, so this looks like a same bug as #547. You probably used an older version than 0.7.4 when it happened.
