### ISSUE TITLE
significant lag in new version

### ISSUE THREAD

**Issue by r3lik** [Epix37/Hearthstone-Deck-Tracker#2050]
Version 0.13.9 introduced substantial lag during card draw and other mechanics such as destroying a piloted shredder. Did anything change on the log side?

**Comment by Epix37** [comment]
Nothing changed in regards to logging. Is this problem only present with the latest version running? What happens when you use 13.7 again? No HDT at all?

**Comment by r3lik** [comment]
apologies, i spoke too soon. I should have tested more. It was related to some updates on my side. It did resemble an issue from before, which is why I brought it up. You can close the issue. 

Thanks for all the good work
