### ISSUE TITLE
Druid, Paladin, Warrior, Priest Class Cards

### ISSUE THREAD

**Issue by SilentScorn** [Epix37/Hearthstone-Deck-Tracker#2052]
When I try to make a new deck I can't see any class cards. But other classes cards can be seen. Even if i click on "Filter>Type>Class Only" it is empty.
![hdt](https://cloud.githubusercontent.com/assets/16985204/12701813/8cd0837e-c81e-11e5-8e0c-a390f3638e2c.png)

**Comment by Epix37** [comment]
See #1906 for a workaround. I sadly still don't know what's causing this.
