### ISSUE TITLE
Not starting or crashing after last update

### ISSUE THREAD

**Issue by Djahobbe** [Epix37/Hearthstone-Deck-Tracker#2053]
it's simple, even if i reinstall hdt, it doesn't start or it starts (the hdt window doesn't even come out, than my mouse cursor stop working, i can't move it, i can't click) and it crashes, and i've to close it by alt+f4
how can i solve this issue??

**Comment by everchump** [comment]
Maybe you use the v0.13.8 HDT

There's a bug in v0.13.8

So you should download the latest edition v0.13.9

It fix the bug

https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/download/v0.13.9/Hearthstone.Deck.Tracker-v0.13.9.zip

**Comment by Djahobbe** [comment]
ok now it works! i reinstalled, thank you!!!
