### ISSUE TITLE
"Show last played date on deck" different date formats

### ISSUE THREAD

**Issue by PetrP** [Epix37/Hearthstone-Deck-Tracker#2054]
It's using US date format d/m/yyyy.
![](http://content.screencast.com/users/PetrPP/folders/Jing/media/373083f3-368a-4b72-9a86-d0108d4d38f0/2016-01-31_2020.png)

Can you please add option to pick date format? e.g. similarly as arena deck name template:
![](http://content.screencast.com/users/PetrPP/folders/Jing/media/3b013546-03d5-4416-936c-e015244af2b6/2016-01-31_2027.png)

**Comment by Epix37** [comment]
Added option with v0.13.16.
