### ISSUE TITLE
Add my plugin to the official plugins list

### ISSUE THREAD

**Issue by falconmick** [Epix37/Hearthstone-Deck-Tracker#2055]
I actually managed to get it in there without your aproval (well it looked like it was there) but  I didn't want to add it before you agreed to it being on the list... Is it supposed to be open for modification like that?

If it's ok I would love you to add the following:

Header:
`__[Battlecry](https://github.com/falconmick/BattleCryPluggin)__ by [@falconmick](https://github.com/falconmick/)
`
Body:
`Allows the user to bind sound effects to battlecrys ingame. By default when Mysterious Challenger is played, it will play 'AND HIS NAME IS JOHN CENA' after the Challenger says 'Who am I?'`

Github link: 
`https://github.com/falconmick/BattleCryPluggin`

Download Link:
`https://github.com/falconmick/BattleCryPluggin/releases/`

Thanks!

**Comment by Epix37** [comment]
Approved! Great plugin.

 I reverted the last change on the wiki (removal) for you.

**Comment by falconmick** [comment]
Cheers
