### ISSUE TITLE
Cant find Keeper of Uldaman in list

### ISSUE THREAD

**Issue by Hawktrr** [Epix37/Hearthstone-Deck-Tracker#2060]
Hi,

That card was always missing from the start since it came out. I waited for updates to fix this issue. Also re-installed deck tracker. No card. Another card missing too that i cant remember.
How to fix this ?

**Comment by Epix37** [comment]
Just doublechecked, definitely exists for me. Are you possibly trying to find it in a non-paladin deck?

**Comment by Hawktrr** [comment]
Nope,
Of course i am in paladin deck. Another card has this issue too. I just dont remember it.
Also i checked the folders. i saw keeper of uldaman. It is in the folders. It's picture is there. I just dont understand. :(

**Comment by riQQ** [comment]
What's your windows locale?

**Comment by Hawktrr** [comment]
it is win10

**Comment by riQQ** [comment]
That's the version. I need your locale, i.e. your language (see [here](http://windows.microsoft.com/en-us/windows/what-do-with-regional-formats-languages#what-do-with-regional-formats-languages=windows-7), should be somewhere similar on Windows 10)

**Comment by Hawktrr** [comment]
Region : United States
system language is English
i use Turkish Q keyboard
what else do u need ?

**Comment by Epix37** [comment]
See if v0.13.11 fixes this problem.

**Comment by Hawktrr** [comment]
Wow patch fixed it. Great thank you !

**Comment by Epix37** [comment]
Perfect!
