### ISSUE TITLE
Cannot add cards of particular classes

### ISSUE THREAD

**Issue by dorianwhite** [Epix37/Hearthstone-Deck-Tracker#2061]
Hello there,

I've been dealing with this issue for some time. I cannot create new Paladin, Warrior, Druid, and Priest constructed decks. I've been importing decks of those classes I mentioned from the game to the tracker so that I could track them. However, I couldn't manage to find any data, the time I check HearthStats. I reinstalled the tracker but I'm still having the same issue. Any thoughts on how to fix this?

**Comment by Epix37** [comment]
See #1906 for a workaround. I sadly still don't know what's causing this.
