### ISSUE TITLE
Some icons not show, class cards missing

### ISSUE THREAD

**Issue by speedytr** [Epix37/Hearthstone-Deck-Tracker#2063]
Hi I have been trying to solve my problems for 1 month and couldnt find solution.

Some updates ago my deck tracker started to:
1) Don't show some classes icons in main window (paladin, druid,mage). Also their respective decks dont sync with heartstats and only count wins and looses
2) Class cards are not showing while constructing decks

I tried to erase deck tracker folders
-main folder
-epix folder
-folder in appdata/local
nothing changed.

Is there any registry entry or something else to fully erase deck tracker so I can install it from scratch?

**Comment by Epix37** [comment]
Will be fixed with the next update. See #1906 for a workaround.
