### ISSUE TITLE
Hearthstone Deck Tracker crashed and won't open 

### ISSUE THREAD

**Issue by Rodasd** [Epix37/Hearthstone-Deck-Tracker#2065]
So I was at hearthpwn searching for decks and when i tried to export this deck http://www.hearthpwn.com/decks/422868-legendary-cheap-aggrodin-s22 from the Hearthstone Deck Tracker to Hearthstone the Hearthstone Deck Tracker crashed and this message appeared: http://prntscr.com/9y7mwb and now every time i try to open it the same message appears, and when I hit the "Ok" button, it just closes and i can't use the Hearthstone Deck Tracker anymore. Any help would be appreciated

**Comment by riQQ** [comment]
Could you upload or post the crash log. The path to the log is in the error message.

**Comment by Rodasd** [comment]
I'm not sure if this is what you're asking but I think it is 
[Crash report 222016-2059.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/114673/Crash.report.222016-2059.txt)

**Comment by Epix37** [comment]
That's the one.

See here: https://support.microsoft.com/en-us/kb/2771290

> **Cause**
The Windows Imaging Component (WIC) installation is damaged on the computer(s) exhibiting the problem.

> **Resolution**
On Windows XP and Windows Server 2003 computers, you may be able to resolve this problem by installing the standalone WIC redistributable from the following download site. Windows Imaging Component For Windows Vista and later operating systems, try repairing the operating system installation.
