### ISSUE TITLE
Hide in menu.

### ISSUE THREAD

**Issue by Courteneycox** [Epix37/Hearthstone-Deck-Tracker#2066]
If "hide in menu" box checked it's not showing at all. And if it's unchecked it's showing even in menu. It appeared after i reinstalled hsdt (got a latest patch)

**Comment by Courteneycox** [comment]
Just downloaded  0.13.8 there's no such bug.

**Comment by Epix37** [comment]
There was no change from 0.13.8 to 0.13.9 that could cause this. Maybe it was just a matter of restarting Hearthstone ([most likely this problem](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#not-working))?

**Comment by Courteneycox** [comment]
Wel. Just downloaded lates version and it seems ok. But i clearly remember restarting hs and hsdt, even rebooting. Anyway sorry to bother. Thank you for hsdt. =)

**Comment by Epix37** [comment]
Weird, but good to hear :).
