### ISSUE TITLE
Hearthstone Deck Tracker not working

### ISSUE THREAD

**Issue by MeisterTee** [Epix37/Hearthstone-Deck-Tracker#2070]
[Crash report 522016-139.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/119084/Crash.report.522016-139.txt)
[Crash report 522016-1310.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/119085/Crash.report.522016-1310.txt)

**Comment by Epix37** [comment]
See #1824.
