### ISSUE TITLE
Gifted (or returned to hand) cards added to deck

### ISSUE THREAD

**Issue by XDki113r** [Epix37/Hearthstone-Deck-Tracker#2072]
Whenever a card is added to your hand, the card is also added to the deck tracker even though it's not in the deck. This does not affect the number of cards displayed by the deck tracker, therefore I think it is only a visual bug.

For example: 
![capture](https://cloud.githubusercontent.com/assets/1305105/12861644/f0dfb89a-cc32-11e5-81c4-c9daa24cc45a.PNG)
It was a card I got from unstable portal.

**Comment by Epix37** [comment]
Do you have `options > overlay > player > include obtained cards` enabled?

**Comment by XDki113r** [comment]
I was looking for this option, I didn't see it for some reason.
Sorry about that.
