### ISSUE TITLE
Corrupted DeckStats.xml

### ISSUE THREAD

**Issue by ulrikau** [Epix37/Hearthstone-Deck-Tracker#2074]
I attempted to start HDT normally, but it said that something went wrong (the login window did not appear). I exited and attempted to start again, got to the login window and proceeded without logging in, but then got an error message saying that "DeckStats.xml is corrupted". I suspect that this might have to do with a recent tracked game. I believe I switched active deck while it was saving my match (Ranked match). The small popup in the corner showed only the text "- [Casual]".

I do not have a Hearthstats account, so I am currently only tracking my games locally. I have HDT version 0.13.9, running on Windows 7.

My current DeckStats.xml file is empty, and dated right now.
`<DeckStatsList></DeckStatsList>`

I also have a DeckStats_corrupted.xml, where the time stamp is from this morning (the play session when I suspect I switched active deck too soon). When I open this in a text editor the file contains only
`[NUL][NUL][NUL]...`

Here is the [crash report](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/120390/Crash.report.622016-193.t) generated by HDT, but I'm afraid it doesn't tell very much of what happened or when it went wrong.

I'm not sure if these logs will be of any use, but these are the logs from this morning and my two recent attempts:
[2016-02-06 09:16 log](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/120395/hdt_log_1454781812.txt)
[2016-02-06 19:03 log](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/120397/hdt_log.txt)  (hdt_log.txt)
[2016-02-06 19:03 log](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/120396/hdt_log_1454781826.txt) (hdt_log_1454781826.txt)

**Comment by Epix37** [comment]
Go to `%AppData%/HearthstoneDeckTracker` (Win+R, paste) and delete the `PlayerDecks.xml` file. If there is a  `PlayerDecks_backup.xml`, rename it to `PlayerDecks.xml`. Otherwise go to the `Backups` folder and replace it with the `PlayerDecks.xml` from the latest zip.

**Comment by ulrikau** [comment]
This helped, thank you very much! I didn't even realize that backups existed.
