### ISSUE TITLE
Feature request: Arena tab sorting

### ISSUE THREAD

**Issue by Sombres** [Epix37/Hearthstone-Deck-Tracker#2075]
There is this one thing I'm missing in HDT: Sorting the Arena decks. Right now it's highly impractical and just plain annoying that the newest games are on the bottom of the list and the oldest ones are on the top, thus making us scroll down through a (very often) large list to find that wanted one. And so, I'd like to request such feature to change that sorting order.

**Comment by Epix37** [comment]
Check out `MAIN > SORT / FILTER` (menu bar)

**Comment by Sombres** [comment]
Damn, it's so hidden. My bad still. Closing.

**Comment by Epix37** [comment]
You are absolutely right, it's too hidden. I added a button for it to the main UI.
![sort](https://cloud.githubusercontent.com/assets/7737910/12915746/7d182642-cf2d-11e5-8001-1244c304b19a.png)
