### ISSUE TITLE
HDT unable to detect wich deck i'm using

### ISSUE THREAD

**Issue by Ansem93** [Epix37/Hearthstone-Deck-Tracker#2077]
Hi, since a while, I always need to select my deck manually, because HDT can't detect which one i'm using!
I'm the only with this bug?

**Comment by Epix37** [comment]
Is `MAIN > AUTO DECK SELECTION` in the menu bar enabled?

**Comment by tknights2015** [comment]
I have also has this occur multiple times since the new version.
