### ISSUE TITLE
Merge "MAIN" menu item into UI/DeckPicker

### ISSUE THREAD

**Issue by Epix37** [Epix37/Hearthstone-Deck-Tracker#2078]
- [x] use no deck (*moved to deck picker*)
- [x] auto deck selection (*moved to deck picker*)
- [x] sort / filter (*moved to deck picker*)
- [x] quick filter (*removed*)
- [x] class cards first (*moved to `options > tracker > general`*)

**Comment by Epix37** [comment]
![deckpicker](https://cloud.githubusercontent.com/assets/7737910/12929753/bab05e6a-cf74-11e5-9116-065e1371e797.PNG)


Aside from the X being too thick, is this too noisy?

**Comment by andburn** [comment]
I think its fine.
It could be confused with deleting a deck.
Maybe a symbol like this instead?
![no-entry](https://cloud.githubusercontent.com/assets/5419653/12930590/0f82fb0e-cf71-11e5-830f-5bd880a142cd.png)

**Comment by Epix37** [comment]
Cancel symbol works nicely, thanks.

Completed this with https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/cec1d5ce8f351cfc877cee292706016a16d99fe4.

**Comment by culinko** [comment]
This improvement is really nice!

I'm wondering, how often do people switch Auto deck selection on and off? I personally don't use it and I could totally see just a setting for it somewhere in the options.

**Comment by Epix37** [comment]
The problem with hiding autoselect somewhere in the options is this: If you have it enabled and get the list of decks to choose from but close the dialog / select "no deck", it's turned off and you have to fiddle with the options menu to turn it back on. (That reminds me I need to change the message for that :))

I put the button on the left so that it is clearer it does something with the active deck without requiring any text. On the right it probably needs to read at least "NO DECK" - "clear deck" sounds a lot better now that I think of it. That said, I am concered the cancel buton alone is not clear enough.

**Comment by culinko** [comment]
Yeah, you got a point about the no deck button in options.

What do you think about letters like "A" for autoselect, with a tooltip? Or maybe just AUTO and CLEAR?

**Comment by Epix37** [comment]
That does look better

![deckpicker5](https://cloud.githubusercontent.com/assets/7737910/12943275/7ca0c288-cfe0-11e5-8b82-f4fb401bf1c4.PNG)
