### ISSUE TITLE
Screen Shots are blank version 0.13.9

### ISSUE THREAD

**Issue by tknights2015** [Epix37/Hearthstone-Deck-Tracker#2080]
Screen shots taken with HDT are blank. Probably related to the lack of rank detection and showing all games as casual.

![hearthstone 02-09-16 10-10-27](https://cloud.githubusercontent.com/assets/16232528/12939360/e5f980ea-cf7b-11e5-9774-d1bc4d212ecd.png)
[log_922016-222454.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/124226/log_922016-222454.txt)

**Comment by Epix37** [comment]
Please stop opening new issues for things we already have discussions about.

**Comment by tknights2015** [comment]
I could not find any issue with blank screen shots taken with HDT

**Comment by Epix37** [comment]
https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1889#issuecomment-166061512
