### ISSUE TITLE
HDT crashes when trying to start Arena Helper plugin

### ISSUE THREAD

**Issue by Sombres** [Epix37/Hearthstone-Deck-Tracker#2081]
Attaching crash log and error pop-up below.
My laptop every once in a while gets a BSoD (I think it might be related to a corrupt memory block or sth like that) and I had one when I was drafting my arena deck with HDT and Arena Helper plugin on. After that, whenever I try to start Arena Helper once again, whole HDT crashes. Everything else works perfectly (and so did the plugin before that BSoD).
//edit: I tried reinstalling both HDT and the plugin, didn't help.

[Crash report 1022016-1342.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/124704/Crash.report.1022016-1342.txt)
![hdt1](https://cloud.githubusercontent.com/assets/15704735/12947566/861d4946-cffc-11e5-9a57-6c40ffab20d7.png)

**Comment by Epix37** [comment]
See here: https://github.com/rembound/Arena-Helper/issues/62
