### ISSUE TITLE
From Game: Constructed (Beta) problem

### ISSUE THREAD

**Issue by Zebulon1986** [Epix37/Hearthstone-Deck-Tracker#2082]
Hi guys,
First thank you for your awsome job !
I've got a question, I follow the importation setup but every deck I import does get the cards that are in the first page of any of my classes. Is it normal ? Do I do something wrong ?
Plus when you say click once on every class icon, what about Drood which is already open and order of clicks ? 
Finaly I did the importation setup while staying in the menu and it does not seems to change importations results ?
Can you guide me through this ? ^^
Thanks in advance !
And sorry for my english, not my native langage :)

**Comment by Epix37** [comment]
See #2261.

If running the import setup does not help there's probably not much I can do to fix it due to the nature of how the importing works.
