### ISSUE TITLE
Feature request: Add class as a possible template

### ISSUE THREAD

**Issue by skaforey** [Epix37/Hearthstone-Deck-Tracker#2086]
I like to name my arenas something like  "{class name} arena {date}"

I like how autoimporting gives you the option of having just "arena {date}" but I was wondering if we could add a class option for the regular expression parsing.  I was looking into doing it myself in the code, but I see that the procedure to parse the deck name gets called from a few different places and wasn't sure how best to handle it.

**Comment by Epix37** [comment]
The biggest problem I see is that changing the signature of `ParseDeckNameTemplate` will cause the current arenahelper version to become incompatible. If at all possbile I would like to avoid breaking plugins.

**Comment by Epix37** [comment]
@rembound FYI. 

`Helper.ParseDeckNameTemplate` now has an overload that accepts `Deck` as a parameter to allow for `{Class}` parsing. "Worst case": no deck is provided but the template contains `{Class}`, it's replaced with an empty string, resulting in `{Class}_Arena` => `_Arena`.

**Comment by rembound** [comment]
Will add support in the next version of Arena Helper.
