### ISSUE TITLE
There is no Hearthstone Deck Tracker.exe inside

### ISSUE THREAD

**Issue by Antera** [Epix37/Hearthstone-Deck-Tracker#2088]
Hi,

There is no Hearthstone Deck Tracker.exe inside the .zip
Only exe are : HDTHelper.exe, HDTUninstaller.exe and HDTUpdate.exe

And Hearthstone Deck Tracker.csproj

**Comment by riQQ** [comment]
https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#no-exe
