### ISSUE TITLE
Crash on startup.  Windows 10 just started after recent Windows updates.

### ISSUE THREAD

**Issue by geardaddy** [Epix37/Hearthstone-Deck-Tracker#2090]
[Crash report 1322016-957.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/129233/Crash.report.1322016-957.txt)

repeatable after multiple attempts and reboot.

**Comment by geardaddy** [comment]
attempted reinstall of software.  issue persists.

**Comment by Epix37** [comment]
Not really sure why (or how) that happens. Can you run older versions?
