### ISSUE TITLE
Move "show note dialog" options to "notifications"

### ISSUE THREAD

**Issue by zedor** [Epix37/Hearthstone-Deck-Tracker#2093]
This would help people greatly in classifying matchups, for those who are interested.

I see two versions possible:
1) Less complex version would have a simple 'add note' button, where you can input the custom note of your will.
2) More complex version would let you pre-setup tags for classes, for example warrior: 'control', 'patron', 'reno', 'other'. It would additionally let you input a custom note on the spot.

Thanks for considering!

**Comment by Epix37** [comment]
I'm not entirely sure if this is what your are looking for but there is a after-game note dialog popup you can enable via `options > tracker > general > show note dialog after game`.

**Comment by zedor** [comment]
Derp! I went over the options multiple times during the past but I never catched that option. It's exactly what I meant.

Sorry, totally my fault for overlooking it, but perhaps you should switch it over to the 'notifications' part of the options? Thanks in any case!

**Comment by Epix37** [comment]
That would probably make sense! I will do that :).

**Comment by zedor** [comment]
Thanks!
