### ISSUE TITLE
crash every time I save arena rewards

### ISSUE THREAD

**Issue by kuliksco** [Epix37/Hearthstone-Deck-Tracker#2094]
I am running hearthstone on windows 10 x64 at 2560x1600 in windowed mode.

Every time I select the arena rewards and hit OK hearthstone crashes.

Error message is 'Couldn't switch to requested monitor resolution'

Switching to resolution 2540x1531 failed, try lower one
All resolution swithces have failed
Screen: could not switch resolution (2540x1531 fs=0 hz=60)

After closing that error I get

Runtime error!
Program ...hearthstone.exe

R6025
-pure virtual function call

and after closing that I get:

Hearthstone.exe has stopped working

**Comment by kuliksco** [comment]
[deck tracker errors.docx](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/130001/deck.tracker.errors.docx)

**Comment by Epix37** [comment]
Not too sure what would cause this. See if your graphics cards drivers are up to date.
