### ISSUE TITLE
Golden Cards and Options

### ISSUE THREAD

**Issue by kadlecx** [Epix37/Hearthstone-Deck-Tracker#2096]
Hello, I am using HS Deck Tracker for few weeks and I would like to some questions, because I am not so sure about it.
First of all are the golden cards. Can I put golden cards into HS Deck Tracker, if yes, I would like to know how.
And the second thing is about whole Options, I would say...summary for HSDT. What's possible to do in HSDT? I couldn't find enough informations about it.

Thanks for your help and time :-)

**Comment by Epix37** [comment]
No way of adding golden cards in HDT.

The easiest way would be to take 5 minutes and look through the menus and options menu. You can also find the [FAQ here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ).
