### ISSUE TITLE
HS Deck Tracker won't open

### ISSUE THREAD

**Issue by JFKwasAFK** [Epix37/Hearthstone-Deck-Tracker#2097]
I have the latest version of the app and it just won't open.

I tried running as administrator.

**Comment by Epix37** [comment]
If you are not on Win10 try reinstalling .NET Framework.

Is there a crash report?

**Comment by pautnesis** [comment]
I have exactly the same issue and I'm using windows 10. I deleted the deck tracker folder and unzipped it again with no results. It just doesn't open, there is no crash report because the program never opened.

**Comment by riQQ** [comment]
Anything in the Windows Event Viewer?

**Comment by jleclanche** [comment]
Closing due to lack of feedback.
