### ISSUE TITLE
no stats in deck list

### ISSUE THREAD

**Issue by CookieCompiler** [Epix37/Hearthstone-Deck-Tracker#2100]
I deleted some games in the games&stats area. Afterwards the stats in my deck list are missing although there are games belonging to these decks.
![decklist](https://cloud.githubusercontent.com/assets/4922359/13078989/3fa184ee-d4c2-11e5-9098-ba2d292f08e5.png)
![stats](https://cloud.githubusercontent.com/assets/4922359/13078990/3fa270fc-d4c2-11e5-926a-c28dafb0a6f2.png)

**Comment by Epix37** [comment]
Try restarting HDT and if that does not help check the filters in `options > tracker > stats > display`.

**Comment by CookieCompiler** [comment]
Thanks for the help. The filters were not adjusted correctly.
