### ISSUE TITLE
new Tracker stats from hearthstats.net?

### ISSUE THREAD

**Issue by cyruz86** [Epix37/Hearthstone-Deck-Tracker#2102]
Hello,
my PC HDD is crashed last night, now i need to install all my stuff.
My Decktracker is now empty but on hearthstats.net ist all my stuff.
can import all decks and stats from the web to the tool?

sorry for my bad english.

**Comment by riQQ** [comment]
`HearthStats > Sync now` or, if it doesn't work,`HearthStats > Force full sync`.
