### ISSUE TITLE
[v0.13.11] Not working correctly / Not detecting game start/end / Timer blinking

### ISSUE THREAD

**Issue by Yperellanios** [Epix37/Hearthstone-Deck-Tracker#2103]
Hey man! First of all thanks for this amazing program! It's been a great help!

So I have this problem: After the latest update the timer of the turns keeps blinking. The deck statistics don't get tracked after the game ends and also if I queue up for a second game the tracking breaks entirely. It can't track my deck neither my opponent's. The list on the side is also broken with duplicate cards and wrong number of cards. 

Looking forward to a reply. Thanks again!

**Comment by Epix37** [comment]
Try restarting Hearthstone.

**Comment by TemporalOnline** [comment]
I'm having exactly the same problem, restarting HDT or the game didn't work. In order to force the windows to stay open I have to unlock them.

**Comment by Epix37** [comment]
> In order to force the windows to stay open I have to unlock them.

What exactly do you mean by this?

Either way, give this a try:

Open the `%LocalAppData%/Blizzard/Hearthstone/log.config` file with any text editor, replace the content with [this](https://gist.github.com/Epix37/60b525890b3bd772a60d), save and restart Hearthstone.

**Comment by TemporalOnline** [comment]
I mean the tracker windows, one for  secrets, other for my opponent's cards played, my deck, etc. After updating they all will stay closed except for the new battery one and the timer ones, but they will keep blinking. When I go to Overlay>general>unlock overlay, as usual they all get blue bordered and stay open.

**Comment by TemporalOnline** [comment]
NVW, the new 0.13.11 resolved the issues I was having.

**Comment by Epix37** [comment]
Great :).

**Comment by Radiohawk58** [comment]
So I loved your program... and forgive me but I'm not much of a programmer.... where do I find/replace above file, and how do I go about saving it?

**Comment by Radiohawk58** [comment]
Maybe I should ask it another way.... where do I find " %LocalAppData%/Blizzard/Hearthstone/log.config " file to replace, then how do I get it to save in the proper file?

Thanks for any help you can give on this part, or alternatively, how do I roll back to the previous version?

**Comment by TemporalOnline** [comment]
Hey man, something went warry, remember when I said everything was working fine? Well, after I rebooted, now HDT detects the beginning of the game as the end, and ends with the notification of "(not detected) - (not detected) loss" window. The blinking and all came back. I will go back to 13.09 until all is ok for now ;)

**Comment by Radiohawk58** [comment]
@TemporalOnline:  Might I ask... how did you get it to 13.9?  I can't even locate the program to uninstall?

thanks for any assistance you can provide

**Comment by TemporalOnline** [comment]
@Radiohawk58

The 13.09 is here: https://github.com/Epix37/Hearthstone-Deck-Tracker/releases
you scroll down and there will it be.

I don't know where you put your installation of HDT, but wherever it is, first extract the zipped 13.09, (it will create a folder) and copy it. Then, go to the folder where HDT is installed (mine is inside hearthstone's folder) and copy all that is inside there to that folder. Copy that folder there replacing all files and that did it for me.

**Comment by Epix37** [comment]
@Radiohawk58 paste `%LocalAppData%/Blizzard/Hearthstone/log.config` into the run promp (Win+R).


If the problem persists (@TemporalOnline) please reproduce  it and post the log here. [See here.](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)

**Comment by Yperellanios** [comment]
Hey OP here. thanks for the reply. 

I downloaded the newest update today and it works like a charm! Thanks alot!

**Comment by Radiohawk58** [comment]
@Epix37 
Thanks very much... had been so long I couldn't even remember how to find the command prompt :/

found the config file, replaced and seems to be working great!! :)

Thanks again!

**Comment by riQQ** [comment]
I had the flickering timer in brawl, but after switching to ranked, it worked. I played brawl without an active deck and ranked with an active deck.

**Comment by Radiohawk58** [comment]
@Epix37 

> @Radiohawk58 paste  %LocalAppData%/Blizzard/Hearthstone/log.config  into the run promp (Win+R).

If the problem persists (@TemporalOnline) please reproduce it and post the log here. See here.

So the above worked all day yesterday... most of today, started an arena run and it worked fine for the first game, then everything returned.  Flashing timer and not recording the games after that correctly... any suggestions to get it working again?

Thanks for all your efforts.

**Comment by Epix37** [comment]
> **If the problem persists please reproduce  it and post the log here. [See here.](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)**
