### ISSUE TITLE
After the update my overlay is really messed up

### ISSUE THREAD

**Issue by kingpower2009** [Epix37/Hearthstone-Deck-Tracker#2104]
Alright so lets get this started. The first issue i have is that the tracker never considers my game finished as in it will track all the cards i and my opponent play then when the game is over it wont start a new opponent deck or even put my win towards my record. Second issue  The timer keeps blinking and thats really annoying.

**Comment by Epix37** [comment]
See #2103

**Comment by kingpower2009** [comment]
I have that update already it is still doing it for me

**Comment by Epix37** [comment]
Did you restart Hearthstone?

**Comment by kingpower2009** [comment]
Yes i have restarted both clients

**Comment by Epix37** [comment]
HDT might not be able to update the log.config properly. Open the %LocalAppData%/Blizzard/Hearthstone/log.config file with any text editor, replace the content with this, save and restart Hearthstone and HDT again.
