### ISSUE TITLE
Importing a deck from a site to the tracker via NetDeck gives a "hero-less" deck.

### ISSUE THREAD

**Issue by MillenniumDH** [Epix37/Hearthstone-Deck-Tracker#2106]
For example, importing a deck from hearthpwn using NetDeck extension for Chrome correctly gives all the cards in the deck, but the deck itself is not assigned to the hero it belongs to. (It doesn't have class icon, like hammer for paladin or daggers for rogue, on the left of the list in the tracker. Is this a bug or do I have to manually assign each deck the class icon it normally should have?

**Comment by Epix37** [comment]
Seems to working fine for me. If you try to import a deck without and class cards I can see this happening. Please reproduce the issue and post the log here. [See here.](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)
