### ISSUE TITLE
Decks tracking stats even when all tracking options are unchecked

### ISSUE THREAD

**Issue by MillenniumDH** [Epix37/Hearthstone-Deck-Tracker#2107]
Even when all the game modes in the "Record For" tab in the options are unchecked, the decks in the tracker sometimes update their stats when it should be "NO STATS" at all times. Is there something missing here, or is this a bug?

Alternatively, is there a way to reset the stats of a deck without changing its version or contents?

**Comment by Epix37** [comment]
Please reproduce the issue and post the log here. [See here.](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)

You can delete recorded matches under `STATS > GAMES & STATISTICS > Games`.

**Comment by MillenniumDH** [comment]
After a game in Casual, the deck tracker records the win and updates "Tempo Mage" deck to 1-0, even when all options for recording stats are unchecked in the options.

http://pastebin.com/PNacu1q8

This should do it I guess?

**Comment by Epix37** [comment]
The game should be deleted again once you are back in the menu. 
```
[16:35:43] GameEventHandler: Gamemode Casual is not supposed to be saved. Removed game from Tempo Mage (Mage).
```

Due to the way ranked detection works there is no way around this.

**Comment by MillenniumDH** [comment]
You mean that the win/loss should reset after finishing the game?

**Comment by riQQ** [comment]
Same issue here. Played a casual match with a new deck. The stats in the main window were (1-0) but should be (0-0) after finishing the game.

**Comment by Epix37** [comment]
I can reproduce it showing 1-0, but there are no matches in `STATS` and the stats on the deck are gone after refreshing the decks or restarting HDT.

So the games are not actually saved, the UI is just not being updated.

Can anyone confirm?

**Comment by riQQ** [comment]
Yes, i can confirm this. It's only the UI not being updated.
