### ISSUE TITLE
Update Tracker: Discover a bug with Reno Jackson Deck

### ISSUE THREAD

**Issue by sgubby** [Epix37/Hearthstone-Deck-Tracker#2108]
Its seams like the update tracker wont resets my Reno Jackson Deck. 
And the clock timer allso acting werid. Just blinking.
So the deck list wont trigger when I draw a card or use one. All just stands blank from the first game
So I need to close the program and restart it. Don't know if its because of the deck being to large or not. A weird bug.

http://pastebin.com/gk7gS9Lg

**Comment by Epix37** [comment]
See here: https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/2103#issuecomment-185461361
