### ISSUE TITLE
My problem is... this

### ISSUE THREAD

**Issue by Nazbrock** [Epix37/Hearthstone-Deck-Tracker#2111]
Error restoring PlayerDecks backup. Please manually rename "PlayerDecks_backup.xml" to "PlayerDecks.xml" in "%appdata\HearthstoneDeckTracker". ---> System.InvalidOperationException: Il existe une erreur dans le document XML (0, 0). ---> System.Xml.XmlException: Élément racine manquant.

PlayerDecks backup doesn't even exist, i searched but i didn't found it.

**Comment by Epix37** [comment]
Take the one from the most (possibly second most) recent zip in the "%AppData%/HearthstoneDeckTracker/Backups" folder.

**Comment by Nazbrock** [comment]
it doesnt work it sayed :
please manually rename "PlayerDecks_backup.xml" to "PlayerDecks.xml" in "%appdata/HearthstoneDeckTracker". 
But i didn't have this folder --> PlayerDecks_backup.xml

**Comment by Nazbrock** [comment]
seems to be ok i delete all files, download last version but still not enough, i run hdt uninstaller in folder and removed all and now it works. :)

**Comment by Epix37** [comment]
Great :).
