### ISSUE TITLE
Error checking for New version

### ISSUE THREAD

**Issue by blast1809** [Epix37/Hearthstone-Deck-Tracker#2115]
Hello,

When i launch the program i have this screen : 

https://gyazo.com/926cb71cdd3bd918e316fae7762f2758

https://gyazo.com/78197b6522b0ff8e38faa105ee7275e4

Thanks in advance for your help

**Comment by Epix37** [comment]
Are you behind a proxy maybe?

**Comment by blast1809** [comment]
no i not use a proxy, how can u check that ?

**Comment by blast1809** [comment]
here is another screen : https://gyazo.com/43cbaf279cd36abf13ea769a5ac4c7ed

**Comment by Epix37** [comment]
Check if your firewall or antivirus are blocking port 443. Turning them off works for testing it.

You could also try running HDT as administrator.

**Comment by blast1809** [comment]
i have turn off the antivirus but same thing :(

**Comment by Epix37** [comment]
What about the other two suggestions?

**Comment by blast1809** [comment]
how can i check the port 443 ? thanks for your help

**Comment by Epix37** [comment]
> Check if your __firewall or antivirus__ are blocking port 443. __Turning them off works for testing it.__

> You could also try __running HDT as administrator__.

**Comment by blast1809** [comment]
i have try the two suggestions and run as admin, it's not working.

**Comment by blast1809** [comment]
I have uninstall the Antivirus and reinstall and it's working .

Thanks for your help

**Comment by Epix37** [comment]
Weird that reinstalling worked but disabling didn't. 

Good to know, thanks for reporting back.
