### ISSUE TITLE
My decks?

### ISSUE THREAD

**Issue by Turkminator** [Epix37/Hearthstone-Deck-Tracker#2116]
I can not see my decks at application.
<a href="http://www.directupload.net/file/d/4270/co366w5m_jpg.htm" target="_blank"><img src="http://fs5.directupload.net/images/160220/temp/co366w5m.jpg" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>
(win7 32bit)

**Comment by Epix37** [comment]
You have to create the decks in HDT via the `NEW` or `IMPORT` menu items.

**Comment by Turkminator** [comment]
But there is no main button as shown at FAQ?

**Comment by Epix37** [comment]
The `MAIN` menu item has been removed with the latest update. 

> * Simplified UI: Removed `MAIN` menu item.
  * `no deck`, `sort/filter` and `auto deck selection` were moved to the deck picker.
  * card sorting (`class cards first`) was moved to `options > tracker > general`.

Sort / filter is now the double arrow button in the top right. 

Decks are not imported automatically from the game either way though.

**Comment by Turkminator** [comment]
Thank you for help :+1:
