### ISSUE TITLE
games not registered

### ISSUE THREAD

**Issue by cachirro** [Epix37/Hearthstone-Deck-Tracker#2121]
program is open, deck selected, i finish a match, stats don't change, and if i go to history, game isnt there.

happens many times

ps: playing another game same happens, restarting HDT doesnt help, only restarting game makes it register again

**Comment by Epix37** [comment]
Most likely #2103.

**Comment by cachirro** [comment]
maybe, altough there he speaks of many problems, mine is really specific

**Comment by Epix37** [comment]
Please try the solutions suggested there.

**Comment by cachirro** [comment]
so i should do:

> If that does not help, open the %LocalAppData%/Blizzard/Hearthstone/log.config file with any text editor, replace the content with this, save and restart Hearthstone and HDT again.

and not see this problem again?
