### ISSUE TITLE
Stats not saving

### ISSUE THREAD

**Issue by Doberick** [Epix37/Hearthstone-Deck-Tracker#2122]
Hi, today I (upgraded? actualized? dont know which I should use, sorry ^^) the deck tracker after a week with the message "a new version avalaible". Since that moment, deck tracker stopped saving stats for any of my decks, I have tried deleting and creating a new deck and changing some options but it seems all are ok.

Sorry for my english ^^.

**Comment by Epix37** [comment]
Most likely #2103.
