### ISSUE TITLE
Hand detection not working perfectly.

### ISSUE THREAD

**Issue by ericBG** [Epix37/Hearthstone-Deck-Tracker#2123]
![A picture displaying a hand over Truesilver Champion and yet the program claiming it is Anyfin can Happen](https://cloud.githubusercontent.com/assets/3256815/13200227/b123194e-d836-11e5-8365-f991989b106c.png)

**Comment by Epix37** [comment]
Where is your cursor in this image?

**Comment by ericBG** [comment]
I took it using the snipping tool so I'm not sure precisely but I was definitely hovering over truesilver. Next time the issue pops up I'll use the Print Screen button instead.

**Comment by Epix37** [comment]
The detection regions don't match up 100%. If  you were somewhere near the border of the cards this is not an issue. 

If you notice it again please enable `<Debug>` in the config.xml before taking the screenshot. 
Also enable `options > tracker > stats > show log`, go to `Logging > debugwindow` and screenshot the content of `Player Hand`.

Closing this for now.
