### ISSUE TITLE
[Bug report] Exporting decks with quantity=2 and gold foil cards (from HDT to game)

### ISSUE THREAD

**Issue by PudelCastro** [Epix37/Hearthstone-Deck-Tracker#2126]
I've noticed a non-critical bug when exporting decks that contain 2 copies of the same card being selected after selecting gold foil cards.

What happens is the following (consider this scenario):
- Mouse pointer clicks to add plain cards (non-gold) of either quantity to deck, works fine.
- Mouse pointer selects gold foil card(s), works fine (it does this by orienting the mouse pointer a few more pixels to the right).
- If the next card to be selected requires 2 plain cards to be selected, the mouse pointer is stuck/"remembers" the location (further to the right) of the previous gold foil card pick, so it attempts to add 1 gold card and 1 plain card (which fails if I only have 2 plain cards in my collection).
- The export process continues until end but bug may reappear multiple times during this process.

This bug causes me to manually add missing cards after an export, not a critical issue but one that might want to get resolved for improved convenience.

I might add that I'm running Hearthstone and HDT on a low-end computer/laptop, and that I have set the export speed to "Slow (100ms)" because my computer often needs more time to load filtered cards into memory before adding.
HDT version: v0.13.9
Hardware specs:
- model: eMachines eME732Z
- processor: Intel Pentium P6100 dual core 2GHz
- memory: 3 GB RAM
- OS: 64-bit Windows 7 Home Premium

(I'm not sure if this is a known bug, if so please reference to the issue and close this one. I was unable to find a similar issue using search.)

Thanks for your time and continuous work on this awesome piece of software!

**Comment by Epix37** [comment]
Could you reproduce it and post the HDT log? [See here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues).

**Comment by PudelCastro** [comment]
I've reproduced it and I'm attaching the log file: 
[hdt_log.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/141110/hdt_log.txt)

Unfortunately the log incorrectly reports a successfully export at line 504:
`[18:48:52] DeckExporter: Success exporting deck.`

This is the result of the actual export:
![img_actual_export_results](https://cloud.githubusercontent.com/assets/11952102/13227430/e72602ca-d996-11e5-8ef7-b54c295da24a.PNG)

The deck I tried to import:
http://hss.io/d/6768778

As you can see Unstable Portal was only added once after adding the gold foil Frostbolt, this is because the mouse pointer is stuck at being right-oriented after the Frostbolt selection.
Also, as you can see, the exporter did not correctly export the "low mana cards", because my low-end computer was still loading into memory and did not have time (even at 100ms interval) to catch up to the HDT exporter when it was filtering through cards. Once it "stabilizes" after the data is loaded into memory, this is no longer a problem.

One more thing I might add is that the "Zero crystal" sometimes remains uncleared for me when exporting, causing a 0/30 cards exported fail (as the exporter cannot find the filtered cards in the 0-mana range obviously). However this is pretty rare since the 0.13.9 update, I experienced this more before and less frequently now. This may also have to do with either the inability to "catch up" (load to RAM) to HDT on my low end machine, causing missclicks by the exporter or an issue with my display resolution (1366x768).

**Comment by Epix37** [comment]
For the zero crystal issue: try setting a higher value for "wait X seconds before starting" in `options > tracker > settings > exporting`.

Also try enabling `options > tracker > settings > exporting > force clear searchbox between cards` and disabling `prioritize golden cards` .
