### ISSUE TITLE
[Bug report] Can no longer "QUICK SET TAG", can only assign tag to a deck through "EDIT TAGS"

### ISSUE THREAD

**Issue by PudelCastro** [Epix37/Hearthstone-Deck-Tracker#2127]
Attached image:
![hs_hdt_tags](https://cloud.githubusercontent.com/assets/11952102/13203798/b33f0376-d8bf-11e5-90ce-91aaeeff2c19.png)

As you can see I'm using quite a lot of different tags to keep my decks organized. I will probably be adding a few more tags if needed. The issue I'm having started with v.0.13.9 of HDT.
I can no longer quickly assign tags to a deck with "QUICK SET TAG", I must now use "EDIT TAGS" to assign a tag to a deck.

I'm not sure if this has to do with the amount of tags I'm using or if this is a bug that found its way to v.0.13.9, either way it's non-critical but hopefully it can be resolved for convenience.

Thanks for your time!

**Comment by Epix37** [comment]
Can't seem reproduce this with my data. 

Could you upload your latest backup? You can find those via `options > tracker > backups > show backup directory`.

**Comment by PudelCastro** [comment]
Sure, I sent it to you by mail.
Please freely share it within the dev team but not outside if possible.

**Comment by Epix37** [comment]
Will be fixed with the next update! Nasty bug...
