### ISSUE TITLE
Cannot login and crash

### ISSUE THREAD

**Issue by Gramr10** [Epix37/Hearthstone-Deck-Tracker#2128]
[Crash report 2122016-1958.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/139775/Crash.report.2122016-1958.txt)

Cannot login with Hearthstats account because of the issue mentioned in the crash report. If i "continue as guest", the Deck Tracker acts normal, untill i enter a game and it crashes with the same error from the crash report. Running windows 8, which has by default .Net Framework 4.5 . Still tried however, to:
-reinstall 4.5
-repair 4.5
-install the latest version of .Net Framework
-install even 3.5
-tried temporarily disabling antivirus. 

None worked so far. Help?

**Comment by Epix37** [comment]
This should usually be an issues that's fixable by reinstalling .NET Framework 4.5 (3.5 definitely won't work). 

Try uninstalling anything .NET Framework, rebooting and installing 4.5+ again.
If that really doesn't work.. I'm not sure how to fix it. :(
