### ISSUE TITLE
[Request] Create deck that does not conform to rules

### ISSUE THREAD

**Issue by PudelCastro** [Epix37/Hearthstone-Deck-Tracker#2129]
I'd like to suggest to implement a third way of creating a deck (aside from constructed/arena).

For example, currently I'm playing on Heroic vs. Arch-Thief Rafaam, where the player is given a deck that has class cards from both Druid and Hunter if I'm not mistaken, as well some cards that have more than 2 copies (4 Wisps in this deck):
http://www.icy-veins.com/hearthstone/arch-thief-rafaam-guide-with-cheap-decks-for-the-league-of-explorers

I'd like to suggest that a feature is implemented where constraints are removed for these purposes, f.e. this would enable me to use the deck tracker in the rare event that it's needed in this situation. It would also be a good way to make this part of the software more modifiable, maybe further in the future something similar can be created for Tavern Brawl deck construction where certain constraints are imposed etc.

Thank you for your time and consideration.

**Comment by Epix37** [comment]
Added an option to disable it while editing a constructed deck.
![cardlimits](https://cloud.githubusercontent.com/assets/7737910/13253550/e78c3576-da3c-11e5-92c3-fdd560d05cc8.PNG)

This is as much work as I'm willing to put in the current "deck builder". A new one is planned for later this year, we'll see about things like custom constraints then :).

**Comment by PudelCastro** [comment]
That's cool, I appreciate that, thanks!
