### ISSUE TITLE
Integrate function like Collection tracker?

### ISSUE THREAD

**Issue by Ansem93** [Epix37/Hearthstone-Deck-Tracker#2130]
HI, will you integrate a collection tracker working the same way of innkeeper? The plug-in is probably dead because the latest update is from october, and since then the author never answered to any answer.
So can you add a collection tracker function into HDT?

**Comment by culinko** [comment]
Collection Tracker is working correctly for me, the plugin is not dead. There have been some problems with the recent hdt update for some people with windows 10, but I'm sure these will be resolved in the near future. Stop trying to enforce the Innkeeper's memory reading method into hdt.

**Comment by Epix37** [comment]
There are currently no plans to do so, as @culinko said, the plugin works fine.

HDT will not be reading memory or traffic for as long as the logs exist.
