### ISSUE TITLE
After updating to 13.11 overlay glitches out

### ISSUE THREAD

**Issue by ageofmyth** [Epix37/Hearthstone-Deck-Tracker#2131]
Context-I am an infinite Arena player
13.10 also has the same problem.
Timer blinks instead of constant
Get periodic "Deck not found" error while playing the game.  Have to manually reselect the deck I am using.  After awhile error shows up again. I do not change decks.
Oppenent hand overlay (mulligans, # turns a card is held) does not show up at all anymore.
Sometimes enemy cards used overlay messes up, doesn't show cards.
Enemy secret options sometimes glitch out, showing when I play a secret vs when the opponent plays a secret.  Sometimes doesn't even show up when the enemy secret is played or mine is played.

EDIT: Solved? Downgraded to 13.7 and overlay seems to be fixed.  Still want to post this because those bugs are terrible.

**Comment by Epix37** [comment]
See #2103
