### ISSUE TITLE
Deck tracker stopped working

### ISSUE THREAD

**Issue by Franco323** [Epix37/Hearthstone-Deck-Tracker#2132]
Hi.  I have this problem   and every time i open it  crashes and says stopped working. And i did everything. like Reinstalling Net framework 4.5   Opening with administrator mode. And none  worked. i need help i really want this deck tracker i think it is awesome

**Comment by riQQ** [comment]
Could you post the most recent log and error log from this folder `%APPDATA%\HearthstoneDeckTracker\Logs`?

**Comment by Franco323** [comment]
When i open the logs it just blank

**Comment by Franco323** [comment]
But i have the crash report i dont know if it helps :######### 22/02/2016 06:38:46 a.m. ##########
System.TypeInitializationException: Se produjo una excepción en el inicializador de tipo de 'System.Windows.Media.FontFamily'. ---> System.ArgumentException: El valor no está dentro del intervalo esperado.
   en System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   en System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   en MS.Internal.Text.TextInterface.Native.Util.ConvertHresultToException(Int32 hr)
   en MS.Internal.Text.TextInterface.Factory.GetSystemFontCollection(Boolean checkForUpdates)
   en MS.Internal.FontCache.DWriteFactory.get_SystemFontCollection()
   en System.Windows.Media.FontFamily..cctor()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Windows.Media.Typeface..ctor(FontFamily fontFamily, FontStyle style, FontWeight weight, FontStretch stretch)
   en Hearthstone_Deck_Tracker.OutlinedTextBlock.EnsureFormattedText()
   en Hearthstone_Deck_Tracker.OutlinedTextBlock.MeasureOverride(Size availableSize)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Border.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   en System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Documents.AdornerDecorator.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Controls.Border.MeasureOverride(Size constraint)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Window.MeasureOverrideHelper(Size constraint)
   en System.Windows.Window.MeasureOverride(Size availableSize)
   en System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   en System.Windows.UIElement.Measure(Size availableSize)
   en System.Windows.Interop.HwndSource.SetLayoutSize()
   en System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   en System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
   en System.Windows.Window.SetRootVisual()
   en System.Windows.Window.SetRootVisualAndUpdateSTC()
   en System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   en System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   en System.Windows.Window.CreateSourceWindowDuringShow()
   en System.Windows.Window.SafeCreateWindowDuringShow()
   en System.Windows.Window.ShowHelper(Object booleanBox)
   en System.Windows.Window.Show()
   en Hearthstone_Deck_Tracker.Windows.SplashScreenWindow.ShowConditional()
   en Hearthstone_Deck_Tracker.Core.Initialize()
   en Hearthstone_Deck_Tracker.App.App_OnStartup(Object sender, StartupEventArgs e)
   en System.Windows.Application.OnStartup(StartupEventArgs e)
   en System.Windows.Application.<.ctor>b__1(Object unused)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
########## 22/02/2016 06:38:46 a.m. ##########
System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en Hearthstone_Deck_Tracker.App.App_DispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs e)
   en System.Windows.Threading.Dispatcher.CatchException(Exception e)
   en System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   en System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   en MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   en System.Windows.Threading.DispatcherOperation.InvokeImpl()
   en System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   en System.Windows.Threading.DispatcherOperation.Invoke()
   en System.Windows.Threading.Dispatcher.ProcessQueue()
   en System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   en MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by riQQ** [comment]
Try the workarounds from this link: https://support.microsoft.com/en-us/kb/2978135.

**Comment by Franco323** [comment]
No man it doesnt work :C
