### ISSUE TITLE
[Feature request] Create opponent deck

### ISSUE THREAD

**Issue by PudelCastro** [Epix37/Hearthstone-Deck-Tracker#2133]
This is a fairly ambitious feature suggestion, none that should take priority over core functionality I think but nevertheless sometimes cool that might be considered:

- **Active opponent deck**:
The same way that an active deck is can be chosen from a list of created/imported decks for the active player, an **active opponent deck** can be chosen. Let's say you're playing versus a friend who is using one particular deck, it could be considered cheating but it could also be immensely useful, and of course there is no way to actually verify if he is running that deck at this particular time but it would be helpful.
- **Dynamically build opponent deck**:
The idea here is to build up opponent decks through observations (both local via the tracker but perhaps also through websites that collect match data). Let's say that you're facing a specific Paladin archetype one day. By running into "the same kind of Paladin" the game builds up a deck profile, and whenever it assumes that you meet another one of those Paladins it will display the opponent deck based on data/assumption and list what your opponent has already used in his deck. In other words, a real-time opponent deck based on recent data, local and/or sourced from other resources.
- **Build opponent deck through sourcing external data**:
This idea is a spinoff of the previous one. The idea is that a meta snapshot is fed into HDT and throughout playing a match HDT can more accurately guess what kind of deck the opponent is running. Let's say that you're playing versus a Mage: HDT pulls Mage decks from Hearthpwn, then depending on what cards your opponent play it will determine what subarchetype it is (freeze, tempo, mech, ...). HDT will to its best ability try to display the most probable opponent decklist based on recent data regarding decks and the meta. As an optional functionality, if the opponent deck cannot be matched with the lookup of decks then their deck will be fed back into an "indexing resource/website" to build an ever-more accurate description of what cards and decks people are currently running up against.

These suggestions are fairly ambitious and could probably be made into plugins or software not related to HDT in themselves. The last suggestion especially requires a different infrastructure and service than what HDT provides today (sharing of big data instead of only recording data locally and connecting to external services). But anyway, this is just me throwing a few ideas, use as you like it.

As always, thanks for reading this and for providing us with a good piece of software!

**Comment by Epix37** [comment]
Has been discussed a lot, short answer: no, sorry.

For longer answers see here: #6, #263
