### ISSUE TITLE
Deck tracker not tracking

### ISSUE THREAD

**Issue by loliaddict** [Epix37/Hearthstone-Deck-Tracker#2137]
Deck not being tracked after latest HDT update
Downgraded to no avail
[log_2322016-22489.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/142779/log_2322016-22489.txt)

**Comment by Epix37** [comment]
Try restarting Hearthstone.

**Comment by Franco323** [comment]
No help for me do...

**Comment by Epix37** [comment]
See #2103
