### ISSUE TITLE
HDT crashed in middle of a game

### ISSUE THREAD

**Issue by Radiohawk58** [Epix37/Hearthstone-Deck-Tracker#2138]
Hi, crashed in the middle of a game, flashed a dialog box that I think was crash data, but closed w/ the program.
Here's the last log file, although there's not much that I can see in it, should I pull the last one with an actual numbered title?

anyway, here's this one:

http://pastebin.com/nEASDKvf

thanks for all you do, let me know if you need more info

**Comment by Epix37** [comment]
There should be a crash report in the `<HDT install dir>/Crash Reports`.  Could you upload that one?

**Comment by Radiohawk58** [comment]
http://pastebin.com/CLxdNibV

**Comment by Radiohawk58** [comment]
Hi, updated to newest version this morning, crashed in the middle of a game again (arena this time, don't remember if it was arena before lol)
here's the crash report:

http://pastebin.com/Bu8HXZ65

Restarting HDT and Hearthstone, hopefully that will reset?
Thank you.
