### ISSUE TITLE
Error exporting to Hearthstone

### ISSUE THREAD

**Issue by HarenPL** [Epix37/Hearthstone-Deck-Tracker#2142]
When exporting a deck to Hearthstone, HDT choses '0-mana cards' filter at the start and doesn't untick it, resulting in no cards found and HDT popping out a message that the remaining cards are missing (not found in the collection).

**Comment by Epix37** [comment]
Try increasing the start delay: `options > tracker > exporting > wait X seconds before starting`.

**Comment by HarenPL** [comment]
Increased the delay to 1 second first, then up to 5 seconds - did not help with the issue. I can perfectly see the cursor click the '0-mana cards' filter first, then the set-selector on the left and only afterwards moving on to inserting the card names into the search box.

**Comment by HarenPL** [comment]
What seems to work tho is selecting the '0-mana cards' filter myself before starting the export - HDT then unticks it and is able to find all the cards. This still however doesn't seem to be the desired way of getting things done.

**Comment by andburn** [comment]
You can disable the filters, by unchecking `options > tracker > exporting > auto clear filters`

**Comment by HarenPL** [comment]
@andburn That did the trick, thank you :)
