### ISSUE TITLE
Can't launch or reinstall it :(

### ISSUE THREAD

**Issue by Emotion27** [Epix37/Hearthstone-Deck-Tracker#2143]
Whevener I try to launch it, it gives me an error message telling me to post the crashlog here! Sooo here it is.
[Crash report 2522016-1451.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/146513/Crash.report.2522016-1451.txt)

Thanks for your job and your help!

**Comment by Epix37** [comment]
See #1824.

> Do you have Windows 8.1? Then install these updates:
  * Upgrade to windows 8.1 for x64-based Systems (KB3063843)
  * Upgrade to windows 8.1 for x64-based Systems (KB3068708)

> If not, try installing .NET Framework 4.6
