### ISSUE TITLE
Deck Tracker won't do overlay

### ISSUE THREAD

**Issue by bigred64** [Epix37/Hearthstone-Deck-Tracker#2144]
All the overlay items just open up as different windows and don't do the overlay. So whenever I click in HearthStone, the windows disappear behind the game. I've been looking through the options for awhile and can't figure out how to get it fixed. It worked perfectly fine on my desktop PC, but just can't get it to work on my laptop.

**Comment by riQQ** [comment]
Could you provide a screenshot?
