### ISSUE TITLE
Deck tracker Not working

### ISSUE THREAD

**Issue by Franco323** [Epix37/Hearthstone-Deck-Tracker#2147]
So i  Made an issue  That the Deck tracker doesnt work 
Deck tracker has stopped working
Problem: CLR20r3
Can someone Please help me? i tried installing re installing net framework 4.5
 i have windows 7   And i tried everything

**Comment by riQQ** [comment]
Install .NET Framework 4.5.

**Comment by Franco323** [comment]
Already did.  not working

**Comment by riQQ** [comment]
So you tried both reinstalling and repairing? Could you post the event viewer details of this problem?

**Comment by Franco323** [comment]
Yeah i tried reinstalling And repairing.   the event viewer is in spanish  
So i had to translate it  ( I hope this is what you mean by event viewer)

Name of the event : CLR20r3
Problem 01:hearthstone decktracker.exe
Problem 02: 0.1.0.0
Problem 03: 56cc6667
Problem 04: hearthstonedecktracker
Problem 05: 0.1.0.0
Problem 06: 56cc6667
Problem 07: 362 
Problem 08: 1c9
Problem 09: System.nullreferenceexception

**Comment by riQQ** [comment]
Create this registry key `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps` and upload the crash dump from `%LocalAppData%\CrashDumps`. 

Which version of HDT are you using?

**Comment by Franco323** [comment]
Im using the last one And i dont have the crash dumps Well seems like i will not use the Deck tracker ever since this doesnt work.

**Comment by riQQ** [comment]
Have you created the registry entry and then tried starting HDT?

**Comment by Franco323** [comment]
Yeah

**Comment by riQQ** [comment]
Did you make HDT crash again? Does your registry key look like this? 
![regedit](https://cloud.githubusercontent.com/assets/3404787/13544097/6cd20002-e272-11e5-8be8-08ac360c1488.png)

**Comment by riQQ** [comment]
Is this the same issue as the one you posted before (#2132)?

**Comment by Epix37** [comment]
Closing due to lack of feedback.
