### ISSUE TITLE
Setting Up HDT in Google Drive crashes on second PC

### ISSUE THREAD

**Issue by Dakcenturi** [Epix37/Hearthstone-Deck-Tracker#2148]
I installed HDT on my home desktop and have started using my laptop more often. As such, I thought I would try it out in Google Drive in hopes I could use the same data between both machines. I copied the HDT folder from its existing location to a folder inside my local Google Drive folder. After letting it sync onto my laptop I attempted running it and it just crashes.

Error log below: 

> Problem signature:
>   Problem Event Name:	InPageError
>   Error Status Code:	c0000185
>   Faulting Media Type:	00000003
>   OS Version:	6.1.7601.2.1.0.256.1
>   Locale ID:	1033
>   Additional Information 1:	0a9e
>   Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
>   Additional Information 3:	0a9e
>   Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

It still works on the Desktop machine in its new location but it does not work from the sync on my laptop. I tried un-selecting "Save config in AppData" to see if that helped but it didn't seem to make a difference.

**Comment by Dakcenturi** [comment]
One note and I don't know if it makes a difference. The original install is on a Win 10 machine and the second machine is a Win 7.

**Comment by Dakcenturi** [comment]
No thoughts on this one?

**Comment by Epix37** [comment]
I seem to have missed this.

Not sure on the crash, but you will need separate configs for both systems *or* have Hearthstone installed in the same path. Then try disabling `options > tracker > save data in appdata` (enable advanced options for HDT >v0.13.13). 
Before launching HDT on the second machine, make sure to clear the `%AppData%/HearthstoneDeckTracker` folder, or you might run into conflicts with the data, i.e. one will overwrite the other, depending on the config settings. 

Also see #1507 and #545.
