### ISSUE TITLE
DeckTracker not keeping stats

### ISSUE THREAD

**Issue by bombdownx** [Epix37/Hearthstone-Deck-Tracker#2149]
DeckTracker hasn't been recording stats for me recently.  Not only this, but it hasn't been keeping track of the enemy's deck or hand or my deck.  It literally just displays the deck and that's it.  I've tried uninstalling and reinstalling.

**Comment by riQQ** [comment]
https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#not-working
