### ISSUE TITLE
How to remove old arena runs

### ISSUE THREAD

**Issue by chiupei** [Epix37/Hearthstone-Deck-Tracker#2152]
The stats for some old games are still showing under archive.

I have deleted them from the arena tab and also deleted the games in runs / matches, but if I select 'include' under Archive, it shows the old stats.

**Comment by Epix37** [comment]
Do you still see the games under `arena - archived` (archived is the folder icon to the right the class ones) in the deck picker (main UI)?

If these are indeed only old games, the easiest workaround would be to set the time filter to exclude them.
