### ISSUE TITLE
Tracker new version is broken

### ISSUE THREAD

**Issue by filippoMichielon** [Epix37/Hearthstone-Deck-Tracker#2153]
Hello, after updating HDT to latest version i noticed the following bugs: 

- options: tracker is hidden if ANY of the "hide if" option is activated (except for the HS in background one)
- opponent deck reset: opponent deck does not reset after match end
- player deck: the tracker works just bad, showing cards from the previous games, stolen cards, random things (e.g. it showed Anduin Wrynn as a card)

I didn't investigate more because HDT resulted just unusable after this update. I know this issue report is not about its very code, but i wanted to draw the attention to some major bugs i found in this new version.

**Comment by Epix37** [comment]
#2103
