### ISSUE TITLE
Polymorph and Polymorph: Boar

### ISSUE THREAD

**Issue by askarmuk** [Epix37/Hearthstone-Deck-Tracker#2154]
I tryed to export in HS this deck ([link](http://www.hearthpwn.com/decks/423722-mech-bgh-dr-boom-variation)) and HDT added a Polymorph: Boar card in my deck instead basic Polymorph.

Im using russina version of Hearthstone. In russian cards read like 'Превращение' (Polymorph) and 'Превращение в вепря' (Polymorph: Boar).

**Comment by Epix37** [comment]
As a temporary workaround, disabling `options > tracker > exporting > prioritize golden cards` should do the trick.

**Comment by askarmuk** [comment]
Yes one of my P:Bs is golden. Tnx for anwer.

**Comment by Epix37** [comment]
It's not so much the fact that Poly Boar is golden, but rather that the normal Polymorph is not. HDT just checks if there is a card in the second slot, regardless whether it's golden or not.

For most language settings, the artists name is added to the search term to prevent this from happening. I'm not entirely sure why it's not enabled for all. Searching for "Vance Kovacas" seems to work fine regardless of what language I set Hearthstone to. Could you confirm that on your end?

**Comment by askarmuk** [comment]
It worked but not for "Vance Kovac**a**s" and for "Vance Kovacs" (without last _a_).

**Comment by Epix37** [comment]
Sorry, typo. Thanks for testing. I'll have a look at implementing it for all languages again then.
