### ISSUE TITLE
Problem updating

### ISSUE THREAD

**Issue by Tutzu** [Epix37/Hearthstone-Deck-Tracker#2157]
I've been unable to update the app for some time. The updater stops at the Write Update File and redirects me to manual update, which I guess means downloading the new version. I need either a solution to the auto update or how to keep my decks if I download the new version.

**Comment by Epix37** [comment]
You should still have all your data after manually downloading and updating.

**Comment by Tutzu** [comment]
So I should just download it and copy it over the existing one?

**Comment by Epix37** [comment]
Yup!

**Comment by Tutzu** [comment]
Okay, thanx and sorry for the stupid question

**Comment by Epix37** [comment]
No problem, don't worry about it :).
