### ISSUE TITLE
Tracking bug

### ISSUE THREAD

**Issue by Tutzu** [Epix37/Hearthstone-Deck-Tracker#2158]
Just updated and it behaves extremely weird.
![b](https://cloud.githubusercontent.com/assets/17547508/13397670/a515e928-df03-11e5-9046-22652417ce8e.png)

**Comment by Epix37** [comment]
Point one and two [here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#its-not-detecting-cards-i-or-my-opponent-play) should solve your problem.
