### ISSUE TITLE
automatic hide during game when opening friends list

### ISSUE THREAD

**Issue by paul2233** [Epix37/Hearthstone-Deck-Tracker#2160]
Hi Guys,

is there a possibility of hiding the deck-tracker during a game when i open my friendlist?
That would be pretty nice!

In my opinion I have had a setup in which this adjustment worked some time ago.

Thank you all very much and have a good day,
Felix

**Comment by riQQ** [comment]
`Options > Overlay > Interactivity > Hide deck when friendslist is open`

**Comment by paul2233** [comment]
insane - thank you so much! for your knowlege i shared this on facebook - maybe someone is interested! hope thats fine. greetings
