### ISSUE TITLE
Just updated to most recent version - doesn't record games

### ISSUE THREAD

**Issue by Sevacant** [Epix37/Hearthstone-Deck-Tracker#2166]
Yes, my filters are correctly set  (Ranked, Arena). Play ranked games. Doesn't record ranked games. Play Arena games, doesn't record Arena games.

Things I have done to try to fix:
-Reset filters
-Reset log.config file
-Reset Hearthstone pathway
-Reinstalled HDT
-Reinstalled HS 

Halp.

**Comment by Epix37** [comment]
- Depending on what you mean by "reset log.config file", give this a try: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Setting-up-the-log.config
- If you have done that/it did not help. please if log files are created at `<Hearthstone Install Dir>\Logs` and written to when the game is running.
- Start HDT, start the game, start a match, then post the log here. [See here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues).
