### ISSUE TITLE
Overlay works, but other functions (Automatically detecting arena decks, importing decks) do not work

### ISSUE THREAD

**Issue by Mepper** [Epix37/Hearthstone-Deck-Tracker#2167]
I recently installed two new hard drives and the Deck Tracker has not been working normally since then. I changed the location of my Hearthstone game as well as the Deck Tracker (they are on two different hard drives). I did make sure to go into options and set the new path for Hearthstone. In fact, I pressed the "Start Launcher/Hearthstone" button and it launched the game just fine

I went through Windows control panel, programs, and did 'Repair' on the 12 .NET Frameworks things I have installed, but about 3 of the applications only had an Uninstall option, and not Repair.

Anyway, let me know what information I can give you to help you, help me :)

**Comment by Epix37** [comment]
Perform [**these steps**](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Setting-up-the-log.config) and see if that helps.

If not:
1. close HDT and Hearthstone
2. Start HDT
3. Start Hearthstone
4. Start a game (practice is fine)
5. Post the hdt log here ([**see here**](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues))
