### ISSUE TITLE
Hide enemy cards list when you open friends list

### ISSUE THREAD

**Issue by formigao** [Epix37/Hearthstone-Deck-Tracker#2171]
just as title says.
can you put a function that hide the overlay when you open friends list ?

sometimes you want to check friends quick and you cant because the cards lists cover it.

**Comment by riQQ** [comment]
`Options > Overlay > Interactivity > Hide deck when friendslist is open`

**Comment by Ansem93** [comment]
it's not working, both on windowed and fullscreen
