### ISSUE TITLE
Import decks like Innkeeper?

### ISSUE THREAD

**Issue by Ansem93** [Epix37/Hearthstone-Deck-Tracker#2172]
Hi, after the latest update innkeeper can import decks using logs.
Can HDT do the same thing? IT's a lotter better than how it is now

**Comment by Epix37** [comment]
Source?

**Comment by Ansem93** [comment]
the latest update of innkeeper, 0.1.20. With this update it use the hearthstone built in logger, so I think it's how it will detect all your collection in 2 seconds, same with decks

**Comment by Epix37** [comment]
I just had a look. The latest Innkeeper enables hearthstone logging, but **only** the power log. That log does not contain any information regarding decks. So the logging can only be used for card tracking duing the game.

**All other information Innkeeper gathers is read from memory (or possibly traffic).**

Further than that: Innkeeper overwrites the log.config (which, as I said, only contains `power`). This means **HDT will not work** if starting HDT, then Innkeeper, then hearthstone.

**Comment by Ansem93** [comment]
So why is the deck detection method of innkeeper a lot more precise than HDT? :(

**Comment by Epix37** [comment]
> All other information Innkeeper gathers is read from memory (or possibly traffic).

**Comment by Epix37** [comment]
Let me expand on that: There is very little information in the logs regarding deck information. I'm fairly certain HDT is very close to "as good as it can get". The only alternatives being image recognition or OCR. 

What Innkeeper does is, it checks the Hearthstone process' memory for the deck information, which is of course complete and immediate. FYI, this is technically against the TOS (though, the chance of getting banned for it is fairly low).
