### ISSUE TITLE
New version update fail

### ISSUE THREAD

**Issue by Radiohawk58** [Epix37/Hearthstone-Deck-Tracker#2174]
Hi, opened HDT and asked to auto update. Opens command prompt window downloads but won't continue.
Snip of the command prompt window when it's done with the attempt:

http://imgur.com/zqRWBJA

not complaining as the current version is working great for me... providing feedback fyi.

**Comment by Epix37** [comment]
Some file permissions problem probably. Maybe HDT was still running somehow.
