### ISSUE TITLE
Bug with tracking Mage secrets

### ISSUE THREAD

**Issue by galenbrill** [Epix37/Hearthstone-Deck-Tracker#2175]
Hello, first post here, sorry if I'm using confusing phrasing, here's what happened:

My opponent, a Mage, had a minion on the board and played a secret.  When I used Hex on the minion, the secret tracker de-highlighted duplicate and effigy as options for what the secret could be.  The secret ended up being duplicate, when the tracker showed the only remaining possibility to be ice block.  

I think the issue arose when the Hex spell used on the minion changed it to the 0/1 frog, the tracker saw this as that minion being killed, when it hadn't been.  Just thought the bug was worth reporting, hope this is seen by someone who can take action on it.

**Comment by Epix37** [comment]
Could you upload the hdtreplay (`%AppData%/HearthstoneDeckTracker/Replays`) and if you can find it the hdt log (`%AppData%/HearthstoneDeckTracker/Logs`) of that game?

You can just paste those paths in the run dialog (Win+R).

**Comment by galenbrill** [comment]
Alright, I played a lot of games yesterday, but judging on the time I made this post, this should be the correct match.  Here's the hdtreplay:

https://www.dropbox.com/s/mj9nrp3iz01n0ye/CoolGalen%28Shaman%29%20vs%20killua%28Mage%29%201658-040316.hdtreplay?dl=0

And the hdt log:

https://www.dropbox.com/s/syezd4hl7p471k6/magegamelog.txt?dl=0

Hope this helps, thank you!

**Comment by Epix37** [comment]
Thank you. This should be fixed now for the next update.

**Comment by Epix37** [comment]
Should be fixed with v0.13.16.
