### ISSUE TITLE
Sacred Trial not graying out correctly

### ISSUE THREAD

**Issue by erismo** [Epix37/Hearthstone-Deck-Tracker#2176]
I was playing Paladin and it definitely grayed out the secret Sacred Trial after I *summoned* a Silver Hand Knight to make my 4th minion.

The Silver Hand Knight (Hero Power) was not *played* (from my hand, i.e.,) so it should not gray out the secret.

Pretty low priority stuff, just an FYI.

**Comment by erismo** [comment]
Well, now it's "tracking" Secrets for my _Rogue _opponent. 

This is on Turn 5 ... he definitely does not have any Secrets, no Burgle, nothing weird like that. So it might be an artifact from my last Paladin game that I just didn't notice for the first four turns.

[Uh, incidentally the gray/secret tracker thought my previous opponent had Competitive Spirit when I submitted that bug report. Eventually it grayed that out when the turn began. At one point he had 1 secret and everything gray. 
Eventually he had a second secret. It might have been Competitive Spirit. I didn't notice because I lost before it mattered.]

![hearthstone screenshot 03-05-16 00 29 18](https://cloud.githubusercontent.com/assets/17666054/13546161/8ee960c0-e26a-11e5-8261-bc5f526de919.png)

**Comment by Epix37** [comment]
Likely #2103

**Comment by erismo** [comment]
Thanks.
I assume that's for the 2nd issue, not the first. I probably shouldn't have posted that in this thread but it seemed silly to start another thread 90 seconds later.

Like I said, that secret play-vs-summoned issue is very minor.

**Comment by culinko** [comment]
>I was playing Paladin and it definitely grayed out the secret Sacred Trial after I summoned a Silver Hand Knight to make my 4th minion.
>The Silver Hand Knight (Hero Power) was not played (from my hand, i.e.,) so it should not gray out the secret.

Are you talking about Silver Hand **Recruit**? I just tested it vs Innkeeper and this didn't happen either with regular or upgraded hero power (with Justicar) when summoning recruits into 3 or 4 minions on my side of the board. The Sacred Trial was not grayed out in any of the cases.

**Comment by Programazing** [comment]
Just making sure.

**Silver Hand Knight:**
![GitHub Logo](http://media-hearth.cursecdn.com/avatars/147/616/648.png)

**Silver Hand Recruit:**
![GitHub Logo](http://media-hearth.cursecdn.com/avatars/147/546/268.png)

**Comment by erismo** [comment]
Ah, indeed, thanks.

I never know what those guys are called, it's not like they show up in my Collection. :)

It *definitely* grayed out. I should have taken a screenshot, because after that (plus the next turn) it showed ALL the secrets grayed out (with one Secret on the board), which is obviously impossible.

If I hadn't seen it gray out when I summoned the RECRUIT, I wouldn't have known which it was.

**Comment by Epix37** [comment]
@erismo Can you check if you still have the log of that game? `options > tracker > settings > open appdata folder`, in `Logs`.

**Comment by erismo** [comment]
The next opponent I played was SenorTortuga [per screenshot], and he is
in hdt_log_1457326910.txt (system date is 3/6, the newest one), so I assume
that the guy before him would be the correct one (and a Paladin).

Sorry I don't know how to check the log to see who it was.

Attached my logs.

**Comment by Epix37** [comment]
Wait... *You* played, paladin, not your opponent, right? That should not have displayed the secret list in the first place. 

The log looks like things got messed up, eventually resulting in what happened in your second post.


In addition to that I also tried reproducing this today without any success (just as culinko). 
So I'm gonna consider this a non-issue for now. Do let me know if you see this happen again.
