### ISSUE TITLE
Game keeps crashing after I plug in my information from and arena run

### ISSUE THREAD

**Issue by harpuajim** [Epix37/Hearthstone-Deck-Tracker#2177]
After every arena run the window pops up asking me what prizes I got which I like a lot, thanks!  The only problem is that after I enter the values and click "save" I get an an error that pops up about the resolution not being able to switch back and another runtime error.  I play in windowed mode on a 1920x1200 display.  I have attached pictures of the two errors.
![hearthstone error 1](https://cloud.githubusercontent.com/assets/17674837/13548349/25a0b31e-e2bc-11e5-9cab-a2af718b6602.jpg)
![hearthstone error 2](https://cloud.githubusercontent.com/assets/17674837/13548348/259e3bd4-e2bc-11e5-8703-b26f51f3a9c2.jpg)

**Comment by Epix37** [comment]
Seen this one before, sadly no clue what's causing it.

Try updating your graphics card driver if possible.

**Comment by harpuajim** [comment]
There actually is an nvidia driver update I haven't done yet. I'll see if that works. Thanks for the response. Love the program!

**Comment by riQQ** [comment]
I got this error once some time ago, but i can't remember the circumstances. I have an AMD graphics card, so it's not vendor specific.

**Comment by Epix37** [comment]
Did the update help?

**Comment by harpuajim** [comment]
I updated the driver and it seems to have been fixed. I'm currently using 362.00. There's an update available but I'm holding off since there's really no reason since I'm really only playing hearthstone and a couple of older games right now. Thanks for the follow up!

**Comment by Epix37** [comment]
Great! Glad to hear that.
