### ISSUE TITLE
'Cards not found in deck' for new brawl

### ISSUE THREAD

**Issue by askarmuk** [Epix37/Hearthstone-Deck-Tracker#2180]
HDT writes this message when playing current brawl (Deal Your Fate). It happens when you or your opponent choose Fate: Portals.
![bandicam 2016-03-05 01-02-09-923](https://cloud.githubusercontent.com/assets/8628595/13553153/cf2f4fa0-e3a0-11e5-95b6-e872998068d5.jpg)

**Comment by Epix37** [comment]
https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by askarmuk** [comment]
Played new game, here is the log: http://pastebin.com/zjV2PV1p

**Comment by askarmuk** [comment]
Also found another problem in process: clicking on 'Open appdata folder' opens obviously appdata folder but i have installed HDT in custom folder ('E:\Games\_game tools\Hearthstone Deck Tracker') where the working logs folder is.

**Comment by Epix37** [comment]
Should be fixed with the latest release?

**Comment by askarmuk** [comment]
I cant test it until this brawl is back again :\ Or are you talking about 'Open appdata folder' button?

**Comment by Epix37** [comment]
No, I did mean the original issue. 

Changing the 'open appdata folder' behaviour doesn't make much sense, it does what it's supposed to do. An easy way for you to get to your installation would be to rightclick your shortcut and select "open file location".

**Comment by Epix37** [comment]
This should be fixed with v0.14.0
