### ISSUE TITLE
Feature Idea: Option to add a note to a game, in the Game Result Notification

### ISSUE THREAD

**Issue by 1thatonedude1** [Epix37/Hearthstone-Deck-Tracker#2183]
It would be really cool if the Game Result Notification had an option to add a note to that game, like when it popped up as opposed to alt-tabbing, going to game stats then leaving a note there.

Keep up the good work, I get a lot of use out of HDT, Thanx

**Comment by andburn** [comment]
There already is an option to add a note, `options > tracker > notifications > show note dialog after game`

**Comment by 1thatonedude1** [comment]
okay thank you, sorry about that
