### ISSUE TITLE
Suggestion: Add indicator for milled cards

### ISSUE THREAD

**Issue by edasaki** [Epix37/Hearthstone-Deck-Tracker#2184]
Is it possible to add some kind of indicator showing which cards were "milled" (i.e. destroyed by being drawn into a full hand)? Right now, milled cards are just shown as normally played cards.

**Comment by edasaki** [comment]
For example I just played this game where Inner Fire was milled: 
http://i.imgur.com/dJhDUnD.png

It would be very convenient if some icon like that red dot were added to show that the cards was destroyed and not ever played.

**Comment by Programazing** [comment]
:+1:

**Comment by Programazing** [comment]
I like @edasaki's idea. :+1:

**Comment by culinko** [comment]
The option you're looking for is already there! Options > Overlay > Opponent > Highlight discarded from deck.

**Comment by edasaki** [comment]
Oh gosh now I feel really silly. Thanks for pointing that out!

**Comment by Programazing** [comment]
I never noticed that before. Thanks @culinko!
