### ISSUE TITLE
Syncs Not Saving

### ISSUE THREAD

**Issue by gabessdsp** [Epix37/Hearthstone-Deck-Tracker#2186]
I mostly play on my laptop in between classes at school, and that installation seems to be fine. I made a lot of deck changes and such. A couple days later I went to play on my desktop and none of my decks synced like they usually do. I forced a full sync and they were there. After playing for about 30 minutes I closed everything out. When I came back later none of those decks I previously synced where there again. I forced a full sync and they were there. Repeat the cycle for a few days and that's what I have been experiencing.

**Comment by Epix37** [comment]
Please try if this helps: 

Sync again, then create a new (empty) deck and delete it again. Restart HDT and check if the decks are still there.

**Comment by gabessdsp** [comment]
That did not work :(

**Comment by Epix37** [comment]
Ok, please do this:
1. Close HDT.
2. open the AppData folder via `options > tracker > settings > open appdata folder`
3. open the `config.xml` with any text editor
4. change ` <LogLevel>0</LogLevel>` to `1` (~line 175)
5. start HDT again, then reproduce what I suggested previously
6. post the log here ([see here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues))

**Comment by gabessdsp** [comment]
Didn't work. Here's the log:

http://pastebin.com/830pqbZn

**Comment by Epix37** [comment]
I didn't except it to work, I just need to see what happens :).

Could you do that again but with force sync this time? (Just force sync and then post the log again, that is)

**Comment by gabessdsp** [comment]
Here you go http://pastebin.com/y490y6B4

**Comment by Epix37** [comment]
Hm... this is a tough one.

One of the decks below has an issue where it references itself (probably as a version) somehow. 

`Legendary Dragon Priest (Priest)`, `Handlock (Warlock)`, `Secrets Freeze Mage (Mage)`, `Grim Patron Warrior (Warrior)`, `Face Hunter (Hunter)`, `Elemental Lord Shaman (Shaman)`, `Demonlock (Warlock)`, `Legend Secret Pally (Paladin)`

The **"**easiest**"** way this could be solved might be (*I'm not 100% sure this will work*) to __disable__ `HEARTHSTATS > AUTO DELETE DECKS` and `AUTO DELETE GAMES`, then do this:
1. Force sync.
2. Delete one of the decks.
3. Restart HDT.
4. Check if the other ones are still there. If not, back to `1` and try the next one.

If the deck are still there:
1. Force sync again to get the deck back.
2. Rightclick the corrupted deck > `clone > selected version` (important not to clone all versions).
3. Select the corrupted deck in the deck picker (not the clone).
4. `STATS > [OLD] GAMES & STATISTICS > Deck > Games`, select all games (ctrl+A).
5. `move to other deck`, select the clone.
6. Make sure all games are now correctly moved to the new deck, then enable the previously disabled hearthstats options again and delete the deck.

**Comment by gabessdsp** [comment]
I went through each one of those decks, started up HSDT, force synced, deleted the first one, then restarted every time to see it reverting back to what it had previously. So basically none of those decks being deleted fixed the issue. :(

**Comment by Epix37** [comment]
Hm...

Are new locally created decks still there after restarting? (without force sync in that session)

**Comment by gabessdsp** [comment]
Yes

**Comment by Epix37** [comment]
Try this:

1. On your laptop: select the decks and delete them on hearthstats via `HEARTHSTATS > DELETE SELECTED DECK`, then sync again. 
2. On your pc: force sync

**Comment by gabessdsp** [comment]
So if it helps any, the scrap deck I made the other day is synced to hearthstats and it wanted me to download it on my laptop. I did tell it just to delete it, but that is interesting that I made it, it synced, then deleted it but it did not sync with the server.

I just deleted the decks on hearthstats and synced from my laptop. I will let you know shortly what happens on my desktop.

**Comment by gabessdsp** [comment]
Well, they are saved when I quit now. But it duplicated all of my decks :/

**Comment by gabessdsp** [comment]
So I just turned off auto delete on my desktop, deleted everything locally. then forced a sync and everything appears to be working again. :) thank you

**Comment by Epix37** [comment]
Great, that's good to hear!

**Comment by leadingmore** [comment]
This is marked as an available workaround for issue #1528 

Can somebody summarize what the workaround is?  I read a lot of trouble shooting steps but what's actually the workaround?

And I also reported this issue in Hearthstats:
https://github.com/HearthStats/hearthstats/issues/523

The reply there is "Likely an HDT" issue.  

So where did those self-referencing deck come from?
