### ISSUE TITLE
Defaults to "casual" recording of a match

### ISSUE THREAD

**Issue by Radiohawk58** [Epix37/Hearthstone-Deck-Tracker#2189]
Hi, since the new version (13.14) when I finish a ranked game it records it as a casual.  I go in and manually change it to ranked... doesn't crash or anything, but wondering if anyone else is having this issue or if maybe I have a setting somewhere I am unaware of that may be causing this?

**Comment by Epix37** [comment]
* Make sure Hearthstone is actually set to the resolution it "pretends" to be (check the options menu).
* Resolutions that cause black bars at any of the sides cause rank detection to fail.
* Screen dimming software is a possible issue.

If it's neither of those, please make screenshots in a ranked game via `options (enable advanced) > hotkeys` > `game screenshot` and `screenshot` (both!) and post those here.

**Comment by Radiohawk58** [comment]
It was screen res setting w/I HS itself... thank you very much.
Capn :)
