### ISSUE TITLE
Manual secret de-highlight

### ISSUE THREAD

**Issue by Weypare** [Epix37/Hearthstone-Deck-Tracker#2190]
When a secret list appears and i click one of the secrets in the list it de-highlights. Is it a feature or a bug?

**Comment by riQQ** [comment]
It's a feature. With `Advanced Options` enabled, you can change this behavior at `Options > Overlay > Interactivity > Click secrets to gray out`.

**Comment by Weypare** [comment]
Oh... Ok then. Thanks for your help.
