### ISSUE TITLE
Tomb Pillager causing HDT to incorrectly stat games with/without coin

### ISSUE THREAD

**Issue by RayFinkle123** [Epix37/Hearthstone-Deck-Tracker#2193]
The HDT stat tracker incorrectly records game results as having the coin if Tomb Pillager's coin is played. This results in no-coin win rates being very low, because to register as "no-coin", you can't start with the coin AND you can't play a tomb pillager coin. This results in extremely lopsided coin/no-coin winrates according to HDT.

**Comment by culinko** [comment]
I can confirm this being an issue on my games as well. As soon as my Tomb Pillager died, HDT marked me as a second player. Attaching HDT log + Power.log.

>22:48:53|Info|Player.PlayToGraveyard >> [Player] id=25, cardId=LOE_012, cardName=Tomb Pillager, turn=10, zonePos=2
22:48:54|Info|GameEventHandler.HandlePlayerGet >> PlayerGet (id:GAME_005 turn:0 from:-1)
22:48:54|Info|Player.CreateInHand >> [Player] id=104, cardId=GAME_005, cardName=The Coin, turn=10, zonePos=0, mark=Coin, created=true
22:48:54|Info|GameEventHandler.HandlePlayerGet >> Got coin

[hdt_log.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/164536/hdt_log.txt)
[output_log.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/164537/output_log.txt)

**Comment by Epix37** [comment]
Should be fixed with v0.13.16.
