### ISSUE TITLE
Deck Tracker won't Start without Crashing - New Windows 10 Install

### ISSUE THREAD

**Issue by 2percenter** [Epix37/Hearthstone-Deck-Tracker#2194]
Hi, I got the attached crash report (and several like it) just when trying to start the tracker. I recently upgraded to Windows 10. I have had the tracker work once since then and most times it shows the start up icon and then closes. Sometimes it generates a crash report.

Hope this helps!
[Crash report 932016-2020.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/166436/Crash.report.932016-2020.txt)

**Comment by bancron** [comment]
Same here, Windows 7.

**Comment by Epix37** [comment]
@2percenter See if you have any outstanding windows updates. If so, try installing those.

@bancron Try re-installing .NET Framework 4.5. If that does not help please also post the crash report here, it's most likely a different issue.

**Comment by 2percenter** [comment]
There are no updates available. I went ahead and checked my .NET version (even though that was for @bancron) and it looks like I have .NET version 4.5. I didn't try reinstalling it.

**Comment by Epix37** [comment]
Oh? You should usually have 4.6 on Win10 by default. Try updating that then.

**Comment by 2percenter** [comment]
OK, sorry about that. I tried to find my .NET version in regedit and the location I was pointed too didn't appear to be there. So, I tried to install 4.5 and was told I already have that (or later). I just did the same with 4.6.1, so it appears I have that as well. Sorry.

**Comment by 2percenter** [comment]
I am running eset Nod 32 anti-virus and just the default Windows Firewall. It looks like the firewall isn't blocking anything with Hearthstone in the title.

**Comment by bancron** [comment]
I restarted / installed a security update and now it works fine. Thanks for the fast response.

**Comment by 2percenter** [comment]
Turning off eset doesn't appear to help.

**Comment by 2percenter** [comment]
Well, I restarted several times along the way. Never found any updates to install. Nothing ever seemed to help HDT actually start working. Then, my system crashed with a Kernel Security error of some sort. After the following reboot, it has worked ever since. So, I have no idea what the issue was, but for now it appears to be working.

Thanks for all of the help along the way. You guys make/support a great product!
