### ISSUE TITLE
Some kind of crash/bug

### ISSUE THREAD

**Issue by NitroCharged** [Epix37/Hearthstone-Deck-Tracker#2198]
My deck tracker started experiencing problems this morning, it was fine yesterday. At first it was things like having 2 haunted creepers listed seperately, instead of stacked if that makes sense. Now when I finish a game and start a new one, it leaves both my tracker and the tracker of what the opponent plays as they ended last game. Any help?

**Comment by Epix37** [comment]
See step 1 and 2 here: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#not-working

**Comment by NitroCharged** [comment]
did it, this time MY overlay was fine but my opponent's wasn't reset

**Comment by Epix37** [comment]
Please restart HDT and Hearthstone, then reproduce the problem again and [post the log here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues).
