### ISSUE TITLE
Use Joust to reveal own unknown cards in the deck

### ISSUE THREAD

**Issue by yoshimo** [Epix37/Hearthstone-Deck-Tracker#2199]
If you play a brawl, randomonium like this week for example or a new class challenge
certain abilities like joust or certain summoning cards like the starseeker legendary from the explorer adventure mode reveal cards. That are known to be somewhere in the players deck, even if he hasn't played them or drawn them yet.
This revealing business seems to be only applied to enemy decks and if HDT knows that the revealing card and revealed card is in your deck.
If you play a new event with "use no deck", that revealing process fails for your own deck. No monkey card is added during this weeks brawl for me.

**Comment by Epix37** [comment]
use no deck mode should be a lot better with v0.14.0 now.
