### ISSUE TITLE
HDT not starting up

### ISSUE THREAD

**Issue by Abmisub** [Epix37/Hearthstone-Deck-Tracker#2201]
I downloaded the latest version (v0.13.14) of HDT, unzipped it, tried starting up HDT, nothing happens, not even an error msg, or anything, double clicking it does absolutely nothing. Sorry for not having all of the details im a noob when it comes to pc stuff.

**Comment by riQQ** [comment]
Is a process created when double clicking the exe?
Any logs at `%APPDATA%\HearthstoneDeckTracker\Logs`?
Any entries in the windows event viewer?

**Comment by Abmisub** [comment]
@riQQ Nope, no logs, and task manager shows no changes, tried switching off defender and firewall and trying again to no avail, still no response of any sort.

**Comment by riQQ** [comment]
So there's no running process called `Hearthstone Deck Tracker.exe`?
Is .NET Framework v4.5 or higher installed on your system?
Did you try restarting your system?

**Comment by Epix37** [comment]
Do you have windows error reporting enabled? If not, please do enable it.

See here: http://www.tomsguide.com/faq/id-2322283/disable-error-reporting-windows-laptop.html

**Comment by Abmisub** [comment]
@riQQ yes i do have .NET Framework v4.5 or higher installed, i'll restart now and let you know.

@Epix37 its set to automatically check for solutions and send additional report data, if needed.

**Comment by Abmisub** [comment]
@riQQ just restarted, nothing changed unfortunately.

@riQQ @Epix37 thanks a lot for your replies even if it doesnt get resolved :)

**Comment by riQQ** [comment]
Did you check for windows event viewer entries?

**Comment by Abmisub** [comment]
@riQQ thanks man, here's the error msgs, i got 3 error msgs

on the details tab:
1- Application Error
Hearthstone Deck Tracker.exe 
   0.1.0.0 
   56d9a48b 
   KERNELBASE.dll 
   6.3.9600.18202 
   569e72bb 
   e0434352 
   00015b68 
   dcc 
   01d17c7898861061 
   C:\Users\Maha\Downloads\DeviceDoctor.7ZipOpener_mkdtfchztkfbm!App\Hearthstone.Deck.Tracker-v0.13.14\Hearthstone Deck Tracker.exe 
   C:\Windows\SYSTEM32\KERNELBASE.dll 
   d65a89cc-e86b-11e5-8297-40167ea83098 

2- .NET runtime
Application: Hearthstone Deck Tracker.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.Windows.Markup.XamlParseException Stack: at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri) at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri) at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean) at System.Windows.Application.LoadComponent(System.Object, System.Uri) at Hearthstone_Deck_Tracker.App.InitializeComponent() at Hearthstone_Deck_Tracker.App.Main() 

3-  Security-SSP
  0x80040154 
   <none> 
   <none>

**Comment by riQQ** [comment]
It looks like your trying to start the application straight out of the zip file. Unzipping it to a folder and then starting should work.

**Comment by Abmisub** [comment]
@riQQ its unzipped, i have just removed the .NET framework, tried to install it again, but it still says i have a 4.5 version or higher, could that be an error or did i not uninstall it?

**Comment by riQQ** [comment]
Are you sure? The second error contains this path: `C:\Users\Maha\Downloads\DeviceDoctor.7ZipOpener_mkdtfchztkfbm!App\Hearthstone.Deck.Tracker-v0.13.14\Hearthstone Deck Tracker.exe`. Try moving the HDT folder to another place.
Which windows version are you using?

**Comment by Abmisub** [comment]
@riQQ yup, thats just the file name, i have tried moving it now and nothing changed, just to be sure, I think i found an issue though, i checked my current .NET versions and i see v4 as the latest, when i try to download 4.5 it says version 4.5 or higher is already installed

**Comment by riQQ** [comment]
This part of the path is conspicuous: `DeviceDoctor.7ZipOpener_mkdtfchztkfbm!App`.
Again, which windows version are you using? Some windows versions come with an included .NET Framework.

**Comment by Abmisub** [comment]
@riQQ i've changed it now :) and im using windows 8.1 pro

**Comment by riQQ** [comment]
Looks like the .NET Framework 4.5 that comes with your windows is somehow corrupt. Try running:
- `sfc /scannow` 
- `dism /online /cleanup-image /restorehealth`

**Comment by Abmisub** [comment]
@riQQ did both, a window pops up n disappears instantly, i've got no clue at this point lol.

**Comment by riQQ** [comment]
Any messages in the command prompt?

**Comment by Abmisub** [comment]
doesnt last long enough to tell

**Comment by riQQ** [comment]
Start the command prompt as follows: `Win + R`, input `cmd` and hit `Enter`.
Then execute the commands.

**Comment by Abmisub** [comment]
@riQQ thanks for the noob instructions haha, now its doing it

**Comment by Abmisub** [comment]
@riQQ it says windows found some corrupt files and repaired them <3 i love you man, im running the second command now

**Comment by Abmisub** [comment]
@riQQ this is the new error
1-Application Error
Faulting application name: Hearthstone Deck Tracker.exe, version: 0.1.0.0, time stamp: 0x56d9a48b
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18202, time stamp: 0x569e72bb
Exception code: 0xe0434352

2-.NET Runtime
Application: Hearthstone Deck Tracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException
Stack:
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadComponent(System.Object, System.Uri)
   at Hearthstone_Deck_Tracker.App.InitializeComponent()
   at Hearthstone_Deck_Tracker.App.Main()

**Comment by riQQ** [comment]
Try this tool to verify your .NET Framework versions: https://blogs.msdn.microsoft.com/astebner/2008/10/13/net-framework-setup-verification-tool-users-guide/.

**Comment by Abmisub** [comment]
i downloaded the verifier, it succeeded all the way up to 4.5.2

**Comment by riQQ** [comment]
Somehow your system tries to start HDT with the wrong .NET Framework version.
> Framework Version: v4.0.30319
I'm not really sure, what's causing this.

**Comment by riQQ** [comment]
You could try installing .NET Framework 4.6.1

**Comment by Abmisub** [comment]
@riQQ i just did that, same problem occuring, event log shows the same, trying to start it with 4.0.30319,
thanks a lot for all your effor though :) i feel bad for taking so much of your time. Thanks again.

**Comment by riQQ** [comment]
No worries. 
Turn on Windows Error Reporting: Create this registry key `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps` and upload the crash dump from `%LocalAppData%\CrashDumps`.
By deleting the registry key, crash dump creation is turned off again.

**Comment by Abmisub** [comment]
@riQQ failing miserably, gimme a few moments to figure out how im supposed to do this lol

**Comment by Abmisub** [comment]
I created the key, but when i try to get the crash dump from that appdata thing, it says there's no such thing.

**Comment by riQQ** [comment]
You have to run HDT another time, because these dumps are only created if the registry key exists when the application crashes.

**Comment by Abmisub** [comment]
got it!!! i had to attach a zipped version of it, cuz it wouldnt upload the actual one.
[Hearthstone Deck Tracker.exe.6020.zip](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/170547/Hearthstone.Deck.Tracker.exe.6020.zip)

**Comment by riQQ** [comment]
It's says this file is missing: `E:\Hearthstone.Deck.Tracker-v0.13.14\Images\HearthstoneDeckTracker.ico`. Anything at this path?

**Comment by Abmisub** [comment]
omg man, you know what it was? the images folder is at E:\Hearthstone.Deck.Tracker-v0.13.14\HearthstoneDeckTracker\Images , i just moved the images folder one step up, it worked. your persistence is amazing. Much thanks it works now. I really appreciate it all <3

**Comment by riQQ** [comment]
Glad it's working now.
