### ISSUE TITLE
if deck is open for edit, game is not registered

### ISSUE THREAD

**Issue by cachirro** [Epix37/Hearthstone-Deck-Tracker#2202]
:(

**Comment by Epix37** [comment]
Currently there's no way around that. 

There's a chance games get saved to default in that case, check `STATS > GAMES & STATISTICS > Overall > Games`, for the `Games` filter select `Without deck` or `All`. If the game is there you can move it to the correct deck via the `move to other deck` button at the bottom.

**Comment by cachirro** [comment]
thanks for the tip, it's a working work around
