### ISSUE TITLE
Enemy cards added to my deck overlay

### ISSUE THREAD

**Issue by Janjuks** [Epix37/Hearthstone-Deck-Tracker#2203]
Just updated to `v0.13.14`
Imported my new arena deck, played one match. Won if that changes anything. In the next round I noticed that some of the cards that my opponent played, were added to my deck overlay + some of the cards I had played in that match were now greyed out as if I had drawn or played them, but I hadn't. Did a screenshot, but it was too late that I noticed that obviously the overlay was not there.

Also - did not want to create a separate issue - I had no issues with timer until this update that it started blinking. Saw it already as fixed, but I guess it's not.

**Comment by Epix37** [comment]
Point 1 and 2 here should solve your problem: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#not-working
