### ISSUE TITLE
Exporting deck works wrong sometimes at Korean language setting

### ISSUE THREAD

**Issue by obscuredjosh** [Epix37/Hearthstone-Deck-Tracker#2204]
After deck exporting, there's "Mirror Image" card instead of "Duplicate" in my deck.
I think it's because "Duplicate" (복제 in Korean) is the substring of "Mirror Image" (환영 복제 in Korean) and then it can happen with other cards having same substring.

**Comment by Epix37** [comment]
Could you try if it works with this version: https://github.com/Epix37/HDT-Test/releases/tag/v0.13.15_PRE2

**Comment by obscuredjosh** [comment]
Sorry.
I tried but this version is not launched on my pc. permanent sandglass.

**Comment by obscuredjosh** [comment]
I checked v0.13.17, and it's fixed.
Thank you very much.
