### ISSUE TITLE
All stats suddenly gone?

### ISSUE THREAD

**Issue by TheRedViper1** [Epix37/Hearthstone-Deck-Tracker#2205]
So my Laptop shut itself off for some reason and when I restarted it and the HDT i realized all my decks are still there (including Arena rewards as an example) but all stats are gone. Can I fix this somehow and get them back?

**Comment by Epix37** [comment]
Try restoring the latest (one the one before that) backup under `options (advanced) > tracker > backups`.

**Comment by TheRedViper1** [comment]
Ty i didnt even know it did backups, feel stupid for asking now :) Thanks alot

**Comment by Epix37** [comment]
No worries :) you're welcome.
