### ISSUE TITLE
Regardless of what I do, it will not let me import my decks from constructed.

### ISSUE THREAD

**Issue by vhoodzy** [Epix37/Hearthstone-Deck-Tracker#2207]
Anytime I do what ive read to fix the problem it still doesn't work, Ive changed the log. Ive tried restarting it. I've entered a play mode game then exited. LITERALLY NOTHINGS CHANGING THE IMPORT FROM CONSTRUCTED METHOD, PLS HELP ME!

**Comment by Epix37** [comment]
Please restart Hearthstone and HDT, reproduce the problem (collection > open deck > back to menu > import) and then post the log here - [see here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues).

**Comment by vhoodzy** [comment]
http://pastebin.com/2bw9ZnNK this is currently the log thats been recorded last

**Comment by vhoodzy** [comment]
Also overlay will not recognize decks or use any of the counters for cards left, cards used opponent cards used etc..

**Comment by riQQ** [comment]
https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#not-working

**Comment by vhoodzy** [comment]
if i send you ten dollars paypal, will you download team viewer and help me
please. I really want thing to work and I cant figure it out at all.

**Comment by Epix37** [comment]
Just follow the instructions here: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Setting-up-the-log.config

**Comment by vhoodzy** [comment]
yeah man.. thats what i did, im not good with coding at all. thats why im
asking you to help me do it and ill pay you for your service through paypal
for setting it up. Hell ill do 20 for all i care

**Comment by Epix37** [comment]
There is no coding involved. All you have to do is paste some text into a file.

**Comment by vhoodzy** [comment]
I call it coding, because I'm not well educated in this area. Can you
please help me?
