### ISSUE TITLE
The deck tracker is not realizing elise starseeker  is getting the map to the golden monkey

### ISSUE THREAD

**Issue by kingpower2009** [Epix37/Hearthstone-Deck-Tracker#2212]
Exactly what the title says

**Comment by MapleSyrupJunkie** [comment]
This worked before. Did they change the card name/ ID?

**Comment by kingpower2009** [comment]
No idea are you having the same problem?

**Comment by MapleSyrupJunkie** [comment]
Yes, the map being added in the deck is not detected anymore. It was working fine yesterday so I am guessing todays hearthstone update changed something.

**Comment by kingpower2009** [comment]
Yeah

**Comment by Epix37** [comment]
Found and fixed the problem.

There should be a new release later today.

**Comment by Epix37** [comment]
Should be fixed with v0.13.16.
