### ISSUE TITLE
Burrowing Mine not getting added to deck

### ISSUE THREAD

**Issue by bajungadustin** [Epix37/Hearthstone-Deck-Tracker#2214]
simple as that... opponent played a burrowing mine and it is not getting added to my deck.
map to the golden monkey and the golden monkey himself are also not getting added to the deck
possibly an issue with cards getting added to the deck entirely.

**Comment by Epix37** [comment]
With that version are you using? Tray icon tooltip/help in the titlebar shows the version number.

The [latest release](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.13.16) should fix this.

**Comment by bajungadustin** [comment]
13.14

**Comment by Epix37** [comment]
Time to update then :).

You can either download it manually via the link about or restart HDT and you should be promted to update.
