### ISSUE TITLE
The Coin getting added to deck for no reason.

### ISSUE THREAD

**Issue by bajungadustin** [Epix37/Hearthstone-Deck-Tracker#2215]
http://puu.sh/nHxVe/fefc5bc6e1.jpg

**Comment by Epix37** [comment]
Do you have `options > overlay > player > include obtained cards` enabled?

**Comment by bajungadustin** [comment]
yes i thought that was for when somethign gets put into your deck

**Comment by Epix37** [comment]
Assuming you have a deck selected, cards always get added to yours deck automatically. (Does currently not work for no-deck mode)

`Include obtained cards` refers to cards that were added to the hand, rather than the deck. I guess I could clarify that a bit.

**Comment by bajungadustin** [comment]
yeah that was it
