### ISSUE TITLE
HearthStats: Upload arena rewards

### ISSUE THREAD

**Issue by TheMiziko** [Epix37/Hearthstone-Deck-Tracker#2217]
Hi ! So I have problem, where, after finishing arena and filling all the information, I still need to update my gold and dust manually in hearstats. Plus, I wanted to know, why deck tracker creates in hearthstats new deck each time I start arena, and doesn't update any matches. Can I turn it off somewhere, so I will not need to delete all this decks ?

**Comment by Epix37** [comment]
Those are currently not synced, correct. 

You mean there are constructed decks created on hearthstats when you create a new arena run in HDT? If so, I think that's an issue on the HearthStats end.

**Comment by TheMiziko** [comment]
Yes, When will they fix this issue with syncing gold for arena ? And does anyone else have problem with creating decks on heartstats after creating arena ? or is it just me ?

**Comment by Epix37** [comment]
"They" being mostly me, not sure. I'll look into it.

@trigun0x2 I think arena decks appearing in constructed is an issue on your end.

**Comment by trigun0x2** [comment]
I will take a look tonight.

**Comment by TheMiziko** [comment]
@trigun0x2  Thank you :) If you want, I have a screenshot of this issue here : http://puu.sh/nOOXt/be95af68d9.png that's how they look in my decklist

**Comment by trigun0x2** [comment]
Will be fixed on next update. @Epix37 can you close this?

**Comment by trigun0x2** [comment]
Actually, this was an intended feature @TheMiziko. Or else there's no way to see the Arena Decks.

**Comment by sparkybear** [comment]
Are arena rewards supposed to be uploaded to hss.io or no? It seems weird that they aren't already being synced?

**Comment by jleclanche** [comment]
Arena rewards were removed from the logs two patches ago IIRC.

**Comment by riQQ** [comment]
At the moment there is no code in HDT to upload rewards and no code in hearthstats API to handle rewards.
