### ISSUE TITLE
Card count for opponent does not work with NEWEST 4.2.012051 patch

### ISSUE THREAD

**Issue by depechenode** [Epix37/Hearthstone-Deck-Tracker#2218]
The opponent remaining card count seems to be broken after today's patch.  I noticed it happens when the opponent gains cards from example summoning portal (in hand count error - deck reflects wrong count) and also with cards like forgotten torch that puts cars into the active deck.  The count so does change when those cards are played.  I played a few games today and even though my opponent was fatigued, the deck count showed he had 26 cards still.

It worked PRIOR to this LIVE patch for deck tracker.

**Comment by Epix37** [comment]
I was able to reproduce this for one game, then restarted HDT and Hearthstone to get to debugging and everything works fine again. So.. not sure, give that a try I suppose.

If you can still reproduce the problem [please post the log here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues).

**Comment by Epix37** [comment]
Please try if you still have the problem with this version: https://github.com/Epix37/HDT-Test/releases/tag/v0.13.17_PRE1

**Comment by Epix37** [comment]
This should be fixed with v0.13.17.
