### ISSUE TITLE
Cards in deck showed as "created"

### ISSUE THREAD

**Issue by earlhacker** [Epix37/Hearthstone-Deck-Tracker#2219]
http://imgur.com/8O20oxd

Piloted shredder was not created in that game. "Finicky cloakfield" is fine because I killed a mech yeti.
Also, a game before I "had" 3 Loatheb and 4 Force of Nature showing in the deck tracker, 1 and 2 created respectively by mistake. 

I closed HS and HDT and opened again, but then the issue in the image happened.

http://pastebin.com/Z4waq9Qb

**Comment by earlhacker** [comment]
Second game: I dind't change any card in the mulligan and the issue dind't happen.
Third game: the issue starts after the card choice. http://imgur.com/5AHybYa

**Comment by Epix37** [comment]
Could you upload the replays of those games? You can find them under `options > tracker > settings > open appdata folder` `/Replays`.

**Comment by earlhacker** [comment]
I think I'm not recording games. There's not a folder named like that.


This issue is not happening every game. It happens in 2-3 out of 10 games.

**Comment by Epix37** [comment]
I think I found the problem. Please try if that still happens with this version: https://github.com/Epix37/HDT-Test/releases/tag/v0.13.17_PRE1

**Comment by Epix37** [comment]
This should be fixed with v0.13.17.
