### ISSUE TITLE
Win Counter stopped working with the new patch

### ISSUE THREAD

**Issue by rex99x** [Epix37/Hearthstone-Deck-Tracker#2220]
I just updated to the newest version and noticed the win counter stopped tracking (X/3) wins,  Any solution?

**Comment by Epix37** [comment]
Could you play a game where after the counter would update, then post the log? [See here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues).

**Comment by Epix37** [comment]
Please try if you still have the problem with this version: https://github.com/Epix37/HDT-Test/releases/tag/v0.13.17_PRE1

**Comment by Epix37** [comment]
This should be fixed with v0.13.17.
