### ISSUE TITLE
Card names in Deck List are cut 

### ISSUE THREAD

**Issue by nicoladj77** [Epix37/Hearthstone-Deck-Tracker#2221]
I've noticed this since the latest Beta release and it appears on the latest version I downloaded today, names on cards are cut, it displays Dr instead of Dr Boom

![image](https://cloud.githubusercontent.com/assets/333069/13800633/39e3c72c-eb2b-11e5-9662-8173d0bff654.png)

Windows 7 64 bit

**Comment by Epix37** [comment]
What are your systems DPI settings set to?

**Comment by Epix37** [comment]
Does the overlay have the same problem?

**Comment by nicoladj77** [comment]
I had fonts set to 120%, setting them back to 100% fixes the issue. 
I don't know why I started noticing this only when I switched on Aero ( I usually kept it turned off ), which is when I installed the latest Beta!

Thanks for helping
