### ISSUE TITLE
Antonidas does not put a fireball in the opponent's deck.

### ISSUE THREAD

**Issue by HellbringerOnline** [Epix37/Hearthstone-Deck-Tracker#2222]
![default](https://cloud.githubusercontent.com/assets/14059683/13813265/ac2b2076-eb91-11e5-85c1-9595c1d5ba3b.PNG)

**Comment by Epix37** [comment]
The list of the left are cards that were *played*, not drawn/created in hand.

Doing this is something along the lines of #1351 #1995 and requires a lot of hardcoding for special interactions, i.e. a lot of work.

**Comment by Epix37** [comment]
Closing in favor #2224.
