### ISSUE TITLE
Hearthstone minimizing on startup and refuses to enlarge

### ISSUE THREAD

**Issue by dawarchief** [Epix37/Hearthstone-Deck-Tracker#2225]
I've been using this program for a longtime on my PC with no issues but today I installed it on my new laptop and a weird issue arose, whenever I launch hearthstone the game immediately minimizes and refuses to enlarge. It is still running and was working fine prior to me downloading deck tracker.

**Comment by Epix37** [comment]
That happens only when HDT is running?

Try starting Hearthstone (with and without window mode), then HDT.

**Comment by dawarchief** [comment]
It happens regardless of whether HDT is running or not, just having the program installed seems to set something off. I have uninstalled and reinstalled HDT 3 times now to confirm.

**Comment by Epix37** [comment]
"uninstalled" as in removing the log.config?

**Comment by dawarchief** [comment]
I cleared all files associated with HDT

**Comment by Epix37** [comment]
That is, running `HDTUninstaller` and removing the Hearthstone logging? Otherwise, if you just removed the files you unzipped.. this would be very strange.

Can you try it with Hearthstone set to windowed mode?

**Comment by Epix37** [comment]
See if you have any outstanding windows or graphics card driver updates.

**Comment by dawarchief** [comment]
Yea I though it could be a driver issue at first but theirs no updates available, none for windows either. I've tried windowed mode as well.

**Comment by Epix37** [comment]
Having uninstalled everthing to the point where Hearthstone is working: Does doing [this](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Setting-up-the-log.config) cause the same problem?

**Comment by dawarchief** [comment]
Sorry that took so long, but yea didn't work :/. It's really not a problem I guess. I only have to use this laptop for a few more weeks until I can get back to my PC, I'll just have to live without HDT for now

**Comment by dawarchief** [comment]
Alright nevermind I might of figured it out

**Comment by dawarchief** [comment]
I just had to hit alt+enter 2 times, still closes on launch but I've figured out how to pry it open and keep it open. I'm not the most technology inclined person and that may have been a real obvious fix the whole time. Thanks for helping!

**Comment by Epix37** [comment]
No that's indeed a bit weird. I would not have come up with it, good to know though!

Glad you got it working :).
