### ISSUE TITLE
Importing to deck tracker uses artist name therefore can't find cards

### ISSUE THREAD

**Issue by LoveKC94** [Epix37/Hearthstone-Deck-Tracker#2228]
When I use Hearthstone Collection Tracker (with the latest version of Deck Tracker, 0.13.17) it seems to input the artist name without the "artist:" part. So it comes up empty. I suspect this is a problem with deck tracker? I've tried to dig through the source of Collection Tracker and can't find any sort of database for card names. Any help would be appreciated.

**Comment by Dulanic** [comment]
Same issue even /w latest version.

**Comment by andburn** [comment]
Nothing to do with the Deck Tracker, it has already been fixed. The Collection Tracker uses its own implementation ([see here](https://github.com/ko-vasilev/Hearthstone-Collection-Tracker/blob/3846061e1fd54d5132b3ead96d2b565c291ba97e/Hearthstone%20Collection%20Tracker/Internal/Importing/HearthstoneImporter.cs#L169)), which needs to be updated. As you know there already is an [issue](https://github.com/ko-vasilev/Hearthstone-Collection-Tracker/issues/76) over on the Collection Tracker's page.
