### ISSUE TITLE
Hearthstone Deck Tracker is showing incorrect win ratio %

### ISSUE THREAD

**Issue by avatarx0** [Epix37/Hearthstone-Deck-Tracker#2229]
I noticed that hearthstone deck tracker was showing incorrect win ratio %.
Please see the attached.

http://postimg.org/image/hpza9cvmf/
http://postimg.org/image/833b82hsb/

I had 10W-10L as a warrior and when I click "show as percent", it would show 47.6%. It should be 50%.

Also, I had 22W-19L total for this month and it should show 53.7% (22W / 41 total games) win ratio, but hearthstone deck tracker is showing 52.4%...

**Comment by Epix37** [comment]
Most likely the same problem as  for #2006.

**Comment by Epix37** [comment]
Fixed with v0.14.0.
