### ISSUE TITLE
HDT show everything ,but not the deck list

### ISSUE THREAD

**Issue by jimmy120bpm** [Epix37/Hearthstone-Deck-Tracker#2230]
![3](https://cloud.githubusercontent.com/assets/17901865/13843383/3642e28a-ec6e-11e5-94d4-ad45e8382f94.jpg)

![1](https://cloud.githubusercontent.com/assets/17901865/13843254/7bb40782-ec6d-11e5-8363-d5f73062f681.jpg)

**Comment by Epix37** [comment]
Are the `cards`, `card counter`, ... options under `options > overlay > player/opponent` enabled? `options (advanced) > overlay > player/opponent > opacity` set to max?

If so... this is very strange. Please post the [**hdt log**](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues) and your latest backup (`options > tracker > backups > show backup directory`).

**Comment by jimmy120bpm** [comment]
i will sd u at email, can't sd u here

**Comment by jimmy120bpm** [comment]
2016-03-17 23:19 GMT+08:00 Alexander Zeier <notifications@github.com>:

> Are the cards, card counter, ... options under options > overlay >
> player/opponent enabled? options (advanced) > overlay > player/opponent >
> opacity set to max?
>
> If so... this is very strange. Please post the *hdt log*
> <https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues>
> and your latest backup (options > tracker > backups > show backup
> directory).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/2230#issuecomment-197928614>
>

下午 04:28:08|Info|GameV2.CurrentGameMode >> Set CurrentGameMode to None
下午 04:28:08|Info|GameV2.Reset >> -------- Reset ---------
下午 04:28:08|Info|Player.Name >> [Player] 
下午 04:28:08|Info|Player.Name >> [Opponent] 
下午 04:28:08|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
下午 04:28:08|Info|HearthStatsAPI.LoadCredentials >> Loading stored credentials...
下午 04:28:10|Warning|LogReaderManager.Stop >> LogReaders could not be stopped, stop already in progress.
下午 04:28:10|Info|GameV2.Reset >> -------- Reset ---------
下午 04:28:10|Info|Player.Name >> [Player] 
下午 04:28:10|Info|Player.Name >> [Opponent] 
下午 04:28:10|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
下午 04:28:10|Info|DataIssueResolver.RemoveDuplicateMatches >> Checking for duplicate matches...
下午 04:28:10|Info|BackupManager.Run >> Running BackupManager
下午 04:28:10|Info|BackupManager.Run >> Backup for today already exists
下午 04:28:10|Info|PluginManager.LoadPlugins >> Loading Plugins...
下午 04:28:10|Info|Updater.GetLatestVersion >> Checking for live updates... (current: 0.13.17.0)
下午 04:28:10|Info|GameEventHandler.ResetConstructedImporting >> Reset constructed importing
下午 04:28:10|Info|Updater.GetLatestVersion >> Latest live version: 0.13.17.0
下午 04:28:57|Info|LogReaderManager.Stop >> Stopped LogReaders.

**Comment by Epix37** [comment]
You can't attach files in replies to github messages, if you were trying to do that. 

Could you play a match, then get the log again (this one was just of starting the app) and email that, together with the backup, to epix@hsdecktracker.net?

**Comment by Epix37** [comment]
Try this: go to `options > overlay > player` and at the bottom, make sure `Cards`, `Card Counter` `Draw Chances` and `Fatigue Counter` are checked. If they *are*, try unchecking and re-checking them. Then do the same for `opponent`.

**Comment by jimmy120bpm** [comment]
It works! But, i can't resize the objects or change their position now.
![4](https://cloud.githubusercontent.com/assets/17901865/13881221/efa8511e-ed5a-11e5-9f7f-51c8f6af0cac.jpg)

**Comment by Epix37** [comment]
Not really sure what's going on there. Were you able to resolve it? Try clicking the "reset" button below "unlock".

**Comment by Diz1904** [comment]
I'm now having this issue myself after updating to version 0.14--never happened before this. Is there some way to fix this?

**Comment by Epix37** [comment]
Did you try everything I suggested here?

**Comment by Diz1904** [comment]
Yes, I tried unchecking/re-checking those options, restarted HDT, didn't work.

**Comment by Epix37** [comment]
- `options > overlay > general > hide decks` enabled?
- try resetting the overlay via `options > overlay > general > reset`
- check if you see the deck regions when you unlock the overlay (button above reset)
- try renaming the `config.xml` in `%AppData%/HearthstoneDeckTracker` (`options > tracker > settings > open appdata folder`) to anything else. make sure to close hdt before doing so.

**Comment by Diz1904** [comment]
Hide Decks is not enabled; Reset the overlay, no change. I can see the deck regions when the display is unlocked, they're just not visible. Renaming the config.xml had no effect either. I'm confused.

**Comment by Epix37** [comment]
If none of the suggestions here work I'm out of ideas on what the problem could be, sorry.

**Comment by Diz1904** [comment]
The update to 0.14.1 fixed it. I will let you know if it happens again.

**Comment by Epix37** [comment]
:+1:
