### ISSUE TITLE
OutlinedTextBlock problems at very high DPI

### ISSUE THREAD

**Issue by AustinTheGreat** [Epix37/Hearthstone-Deck-Tracker#2233]
ever since updating HDT a couple of days back my UI has been messed up. Within the client itself the mana cost has shifted and the number is now behind the name of the card. In game the 4 boxes for draw chance as well as cards in hand and deck are now shifted and for my deck i can not read the values.

**Comment by Epix37** [comment]
* Could you post screenshots of that?
* Try downloading the [latest version](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.13.17) and see if using a clean install helps. (You'll still have all your decks/stats even if you unzip it in a different location)
* What are your systems DPI settings at? Try changing those.

**Comment by AustinTheGreat** [comment]
DPI is 240x240 
![1](https://cloud.githubusercontent.com/assets/17913013/13862635/2a7ee67e-ec5a-11e5-8c2b-06adbe34329e.PNG)
![2](https://cloud.githubusercontent.com/assets/17913013/13862637/2cc9460e-ec5a-11e5-9e55-7569ce3bc8f5.PNG)
Latest release with a clean install did nothing.

**Comment by Epix37** [comment]
You did not have any of these problems at versions before v0.13.17?

**Comment by AustinTheGreat** [comment]
no, there we no issues until the most recent update

**Comment by SimFriHS** [comment]
I have the same issue on a Surface Pro 1 where the problem was also introduced with v0.13.17. 
<img width="180" alt="dpi issue 1" src="https://cloud.githubusercontent.com/assets/14929688/13864498/19e6a82c-eca2-11e5-8beb-e38648a27fda.PNG">
![dpi issue 2](https://cloud.githubusercontent.com/assets/14929688/13864499/1d1b58e4-eca2-11e5-87d0-efca50a2e67b.png)

**Comment by AustinTheGreat** [comment]
mine started out slightly shifted and upon restarting my computer is shifted even further

**Comment by SimFriHS** [comment]
Mine stay the same after restarting. Disabling display scaling on the device removes the problem.

**Comment by AustinTheGreat** [comment]
disabling display scaling did not fix the problem for me

**Comment by fachexot** [comment]
same here. (iMac 5k)

**Comment by oskbor** [comment]
Also got this issue with the latest update. Using 3840 x 2160 with 200% scaling in windows 10.
Tried lowering the resolution and scaling but the issue remained.

**Comment by Epix37** [comment]
I think I got this mostly solved now. The next update should fix this.

**Comment by Epix37** [comment]
Here's the latest build: https://github.com/Epix37/HDT-Test/releases/tag/v0.13.18_PRE1

Please let me know if there are any remaining DPI related problems.

Any feedback on card themes and animations is also appreciated!

**Comment by Epix37** [comment]
Fixed with v0.14.0.
