### ISSUE TITLE
Updating from 0.13.16 to 0.13.17 gave XML error and has reset all my settings (not decks)

### ISSUE THREAD

**Issue by Fonjask** [Epix37/Hearthstone-Deck-Tracker#2234]
Trying to restore a backup from yesterday results in this error:

http://i.imgur.com/SSoRb0n.png

"The XML-document contains an error"
"system.invalidoperationexception instance validation error is not a valid value for MetroTheme" is what Google tells me the proper translation should be

Trying to manually drag the config.xml into the main folder then starting HDT results in the same error. My old (properly setup) Backup file that was automatically generated yesterday is attached.
[Backup_16032016.zip](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/178612/Backup_16032016.zip)

In this old file at line 295 it says `  <ThemeName />`, which seems a bit broken so I lifted the proper value from the reset config.xml and changed it to `  <ThemeName>BaseLight</ThemeName>` and that seems to have fixed it!

Thanks for your time!

**Comment by Epix37** [comment]
Not too sure why that happens.. How long have you been using HDT? Could be an issues with configs that were created before DefaultValues existed.

There is no v0.13.18, v0.13.17 is the latest release.

**Comment by ThorsAngerVaNeT** [comment]
I have same problem... After update HDT create folder Games131026700923793249 and move all my games (8500+ files) to it, same HDT did with Replays folder (6700+ files).

**Comment by Epix37** [comment]
You should be able to restore everthing to the way it was, then take a backed-up config and modify it in the way Fonjask suggested.

**Comment by ThorsAngerVaNeT** [comment]
Thx, yes, now it's working fine

**Comment by syntax53** [comment]
Same thing happened to me.  I followed Fonjask's instructions with the <ThemeName /> tag but since I had altered my data path I had to reset that as well (found under options -> tick advanced options in bottom left -> settings -> set data path -> restart HDT.  HDT took a LOOONG time to start after doing this.

What I found after doing that was it took all of my data from where I wanted it and moved it to the APPDATA folder.  So I had to go back in and UNtick "save config in appdata" as well as "save data in appdata" and then it moved everything back to where I wanted it.

**Comment by Fonjask** [comment]
> Not too sure why that happens.. How long have you been using HDT? Could be an issues with configs that were created before DefaultValues existed.

Quite a while! Oldest file I can find is from 30 August, 2014.

> There is no v0.13.18, v0.13.17 is the latest release.

Ah you see that's because I'm dumb. HDT's intro screen reverting back to my preferred colour from blue threw me off.

**Comment by syntax53** [comment]
Want to add that many of my settings seem to be reset, when to show to overlay, scale, etc.  Even after fixing things up and restoring backups =\

**Comment by Epix37** [comment]
Fixed with v0.14.0.
