### ISSUE TITLE
Stats not staying updated - Update: Issue is that HDT believes they are casual and not ranked.

### ISSUE THREAD

**Issue by basher192** [Epix37/Hearthstone-Deck-Tracker#2235]
After I finish a match the stats total under my deck name and on HDT update like normal. However, on returning to the deck selection screen the numbers reset to what they were before the match. If I restart HDT or sync with hearthstats the amounts correct themselves again. That being said it is time consuming to continually restart HDT after each match to keep the totals up to date. I have checked my settings to ensure I am not accidently ignoring/deleting matches and it appears everything is set correctly. This is a relatively new issue as I have only started noticing it today. 

Hearthstone is up to date and I am running the latest version of HDT. Let me know if there anything I can provide to help in the investigation.

Update:

Log File
http://pastebin.com/bkjtrkxP

It appears that it thinks that my ranked game was done as casual, which is definately not the case. If I catch the popup I can change it to ranked, as a workaround I've changed my tracking to include casual.

**Comment by Epix37** [comment]
Could you take screenshots during a ranked game using the `Screenshot` and `Game screenshot` hotkey functions? See `options (advanced) > tracker > hotkeys`.

**Comment by GiggliG** [comment]
Regarding the stats:
I've noticed that the stats view on the deck selecting list only updates if you change view and deck  (see below).
The stats themselves are still saved, as you can see if you open the stats screen.

To get the stats to update on the decklist, do something like this: 
* change the view (If you are looking at warrior lists, change to priest, say)
* set a deck in that screen to active
* go back to your original screen, and the stats will have updated

**Comment by basher192** [comment]
Here are the first sets of screenshots. This game was marked as casual and then I subseqently changed it to Ranked from the popup 
http://imgur.com/a/Slg5r
Logs: http://pastebin.com/aEZhr0K3

I then started another game. Without changing any settings and the game recorded correctly. Both games were done at full screen/same resolution same deck (different opponent obviously)
Screenshots - http://i.imgur.com/Rc3vcjm.jpg http://i.imgur.com/fBXaQvr.jpg
Logs - http://pastebin.com/YZMPXha6

**Comment by Epix37** [comment]
Ok, it's what I thought: in the first screenshot the game has black borders on each side, that's causing the rank image recognition to fail. 

So some hearthstone resolution settings changed for your second game.

**Comment by basher192** [comment]
Thats odd... I didn't touch anything, but good to know. Thanks for the help.

I will try to keep an eye out to make sure its set properly.
