### ISSUE TITLE
Getting an error while editing a deck

### ISSUE THREAD

**Issue by Rorsch4ch** [Epix37/Hearthstone-Deck-Tracker#2236]
Hello, I'am new at HDT. Yesterday I downloaded it and created some decks. Today I was trying to edit the decks and keep getting whis error message: "The 'B' start tag on line 1 position 43 does not match the end tag of 'b'. Line 1, position 55."
Here is the log http://pastebin.com/CjpA58VJ
Can someone help me pls?

Sorry my bad English.

**Comment by Epix37** [comment]
Could you link/screenshot the decks you are getting this error with?

**Comment by Rorsch4ch** [comment]
Thanks for the fast reply.
I had changed the name of the cards to my native language (Portuguese). I had created several decks and was only getting this error in one of them (a shaman deck with only basics+naxx cards). Now I changed the language back to English and apparently the error disappeared. I will be using the HDT during the day and if an error occurs I come back here.

**Comment by Epix37** [comment]
This seems to be a problem with the Portuguese card text for Hex.

`<ptBR>Transforme um lacaio num Sapo 0/1 com &lt;B&gt;Provocar&lt;/b&gt;.</ptBR>`

It's the only one case in the whole card data file where a capital tag is used.

**Comment by Rorsch4ch** [comment]
Ok. My HS is in portuguese, so I need the cards name in HDT in portuguese too, so I can export the deck to the game. It's not a big problem, I will leave HDT in portuguese, and when I playing Shaman I can change it back to English to avoid this error.
Thanks for the help, you are the man.

**Comment by Epix37** [comment]
Fixed with v0.13.18
