### ISSUE TITLE
deck tracker is running but not working

### ISSUE THREAD

**Issue by tucka3** [Epix37/Hearthstone-Deck-Tracker#2237]
Hi so i just installed this deck tracker, i completed a deck made it active, but when i play it just doesnt do anything, i see my full deck, but it looks like it doesnt do anything, cards are always shown as 0 draw and 30 in deck, and no statistics are recording.

**Comment by Epix37** [comment]
See https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#not-working

If that does not help, please restart HDT and Hearthstone again, then reproduce the problem (play a game) and post the log. [See here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues).
