### ISSUE TITLE
can not detected china region

### ISSUE THREAD

**Issue by chucklu** [Epix37/Hearthstone-Deck-Tracker#2243]
this method UpdateOverlayAsync under Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Core.cs
Game.CurrentRegion = Helper.GetCurrentRegion();

you can not get the china region from the config file
I found the config file under the C:\Users\Administrator\AppData\Roaming\Battle.net
It will not be updated when i switch to china region,the region config is just valid for US,EU,KR

However,we can get the correct region by check the ServerAddress
 Game.CurrentRegion = Helper.GetRegionByServerIp(Game.MetaData.ServerAddress);

**Comment by chucklu** [comment]
I will try to fix this

**Comment by chucklu** [comment]
finally,i found we must detect the region by server addres before we save the game record
detect the region only for the game start is not enough

**Comment by Epix37** [comment]
Fixed with v0.14.0.
