### ISSUE TITLE
Discovered and owned card highlight as in hand

### ISSUE THREAD

**Issue by Weypare** [Epix37/Hearthstone-Deck-Tracker#2248]
I discovered Power Overwhelming and it highlighted as in hand. But Power Overwhelming in my deck also highlighted.

**Comment by Epix37** [comment]
Happens because in-hand highlighting works based on CardIds rather than entities. Only an issue if cards are separated for some reason (e.g. 'include created'). Not sure if this is worth fixing.

**Comment by Epix37** [comment]
This should be fixed with v0.14.0
