### ISSUE TITLE
It is not tracking gold anymore

### ISSUE THREAD

**Issue by TemporalOnline** [Epix37/Hearthstone-Deck-Tracker#2252]
I just updated from 13.9 to 13.17. It lost all my settings but I could retrieve all my decks from the cloud.

The only problem now, it will not track my gold progress.

Thanks :)

**Comment by Epix37** [comment]
See #2234 about the first problem.

The second should hopefully be fixed with https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/3f1725bb6883428cab3eb2febf375e9584c45610. If you are not on china servers, check if it works after the second game.

**Comment by TemporalOnline** [comment]
HDT from nowhere started to track my gold (it is not the true value, but it is tracking).

So, I believe I may have a use case for this bug: From 2 days ago, (sometimes this happens, it is random) I have been receiving my quests in the middle of the day instead of the usual 12:00 AM (ET? EST? It is sometime after 4AM here) and yesterday I got my gold capped.

I believe HDT detected I was capped yesterday AND just started tracking again now that it thinks my real reset started.

One suggestion to correct it: As you did with the timer (which I would have preferred to be customizable instead of hard coded 75 or 95s, but I digress) you could implement a "hard reset gold" and "hard track gold", not based on whatever you may have been getting from the logs, but based on my preference.

The "hard reset gold" button would reset my current gold amount for the "day".
The "hard track gold" checkbox would track my gold progression no matter what (I believe i should also say how many wins I already have, as I will be "resetting" it, but is not a pressing issue).

I mean HDT, it is obviously tracking my progress, but based on this erroneous time based reset of my quests, it was thinking I was capped when I obviously, in game, was not.

Thanks!

**Comment by Epix37** [comment]
Still an issue with v0.14.0?

**Comment by TemporalOnline** [comment]
It is tracking gold (up to this moment). I was already with 20(they were not detected) but it is tracking :)
