### ISSUE TITLE
Possible way to read pack openings?

### ISSUE THREAD

**Issue by judge2020** [Epix37/Hearthstone-Deck-Tracker#2253]
So i've been looking for a way to actively read pack opening details, like innkeeper does with your collection. Since innkeeper is closed-source it wouldn't be easy making a memory/traffic reader from the ground up, so I decided to just start testing.

So first pack I open to start testing has gallywix in it. My luck, right? Anyways, so I close hearthstone then start grep-ing the hearthstone and blizard/hearthstone directories and it seems that in the **text_enUS.cache** file the cards opened are written down (i got a gallywix, jeeves, shredder, some other card and snowchugger) http://pastebin.com/Q41G6wTS. 

So i'm not sure if HDT could possible read this file (or with precision). If so, it would make for a great way to automate tracking the pity timer through HDT.

**Comment by Epix37** [comment]
Since those are cached values, that probably won't work once you open a card for the second time or have seen it before in your collection.

**Comment by judge2020** [comment]
Alright.
