### ISSUE TITLE
HDT Card count/fatigue bug

### ISSUE THREAD

**Issue by knoxius** [Epix37/Hearthstone-Deck-Tracker#2256]
so i've found yet another bug. yay me!

description: **hdt does not count/counts incorrectly/stops counting** how many cards **_opponent_** has left.

some images: http://imgur.com/a/Uc3GI (in pictures 3 turns have passed, hdt shows that enemy still has 1 card left, but you can see clearly from the screenshots, opponent is already taking fatigue damage).
**EDIT:** well i guess not clearly, because it seems you cant see hdt in the screenshots. sadly.
well then i'll try to show differently

here: http://imgur.com/HXssY55 

red circle, is where it showed 1 card left, even thought opponent didn't have any cards (**for more than 3 turns it stayed at 1**)
green circle, the number of my cards left, hdt showed them correctly, so nothing wrong there.

i really hope you can understand what i mean. it's tiny bug, but it's still a bug:) the most important parts of text i made bold.

my thought process why this happened: opponent used entomb on my elise starseeker,  later she played her, which generated map to the golden monkey for him, which resulted in extra card being put into enemies deck and which somehow resulted in this particular bug. i might be wrong though.

i'll attach hdt log as soon as i find it aswell. here you go: 
[hdt_log.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/184962/hdt_log.txt)

mentioned game starts at:

19:58:34|Info|Player.Name >> [Opponent] Sykee
19:58:34|Info|Player.Name >> [Player] KnoX

well you can find the rest. let me know if you need anything else!

**Comment by Epix37** [comment]
From the log it looks like the stolen Elise was never played. Could either be a bug with entomb or a random issue where HDT missed something in the log for some reason.

**Comment by Epix37** [comment]
Should be fixed with v0.14.0
