### ISSUE TITLE
Several bugs

### ISSUE THREAD

**Issue by Doomelf** [Epix37/Hearthstone-Deck-Tracker#2258]
1. When deleting existing arena decks you get a prompt a new one is detected.
2. When Shadow Madness is used on your minion in Solo Adventures the minion gets included in the opponent deck tracker overlay.
3. Even though tracker stats are disabled I still get tracked on wins/losses below the deck.

**Comment by Epix37** [comment]
1. Thats after deleting the newest one?
2. Do you have replay files / hdt logs for that?
3. #2255

**Comment by Doomelf** [comment]
1. Yes. I make an arena deck, the deck tracker asks to import it. I say yes and after the arena run is finished and i delete it i get a reprompt to import it.

2 No, sorry, it happened a week back i think. When I was battling the innkeeper he used Shadow Madness on my healbot and it appeared in the tracker overlay for my opponent.

3. Sorry for reposting an existing issue.

**Comment by Epix37** [comment]
The arena issue should be fixed with v0.14.0.
