### ISSUE TITLE
Export Deck to Heathstone does not work 

### ISSUE THREAD

**Issue by alkogolikrzn** [Epix37/Hearthstone-Deck-Tracker#2260]
after Hearthstone 4.2.0 update patch I have an issue with exporting on Release v0.13.17 ... HDT just paste "v" in search field for every card. increasing start delay or disabling auto clear filters doesn't help

**Comment by Epix37** [comment]
What version of Windows and localization are you on? 

Is your ctrl key swapped with something else?

**Comment by alkogolikrzn** [comment]
im using W7 home premium x64 sp1.

no, im not using any keyboard extensions.

**Comment by Epix37** [comment]
What's your system,  keyboard and HDT language set to? 

Does switching the keyboard language to English help?

**Comment by alkogolikrzn** [comment]
Russian and English, switching doesn't help.

**Comment by Epix37** [comment]
Was #262 ever a problem for you?

I was under the assumption that it was a general problem and changed exporting to copy-paste by default for non-latin languages. 

If you did not have that problem, reverting that change is probably the easiest solution.

**Comment by Epix37** [comment]
Slim chance I found a better solution that reverting the change. Can you try exporting with this version: https://github.com/Epix37/HDT-Test/releases/tag/v0.13.18_PRE2_exporting

**Comment by alkogolikrzn** [comment]
#262 wasn't problem ever.
test version finally helped, thanks

**Comment by Epix37** [comment]
Oh it does? I did not really expect that. Great, thanks for testing.
