### ISSUE TITLE
Importing constructed decks is broken

### ISSUE THREAD

**Issue by anonbro** [Epix37/Hearthstone-Deck-Tracker#2261]
No matter what you put into your constructed deck, when you import the tracker will just put the same list of cards. Mage deck example:

![asdf](https://cloud.githubusercontent.com/assets/7203579/14020845/21babea0-f196-11e5-8028-0c0ca7379bc3.jpg)

**Comment by Epix37** [comment]
Try running the setup again: `options (advanced) > tracker > importing > set up constructed importing`.

**Comment by tknights2015** [comment]
I am seeing this also and just to note ran set up constructed again.  Very few cards in the deck were listed.  Also,previously only the cards on the first pages were usually incorrect. This has changed to where it is faster to just build the deck manually than try to import the deck.

**Comment by Epix37** [comment]
Closing in favor of #2250.
