### ISSUE TITLE
The member "StatusBar" is not recognized or is not accessible

### ISSUE THREAD

**Issue by chucklu** [Epix37/Hearthstone-Deck-Tracker#2263]
<StatusBar Name="StatusBarUpdate" DockPanel.Dock="Top" Margin="0,1,0,0" Visibility="{Binding Visibility, Source={x:Static utility:Updater.StatusBar}}">

I got this error when i try to view the designer of Windows\MainWindow.xaml

commit 99305c6bc27d6626e43b8c6e5b10fb99c78f6181
Author: Alexander Zeier <epikz37@gmail.com>
Date:   Sun Feb 28 18:59:31 2016 +0100

    display update reminder in UI if update dialog was declined (#2151)

the  commit  above add StatusBar

**Comment by Epix37** [comment]
Try clean/rebuild.

**Comment by chucklu** [comment]
thank you ,it worked again
