### ISSUE TITLE
Tracker Not recording stats at all.

### ISSUE THREAD

**Issue by vilzu** [Epix37/Hearthstone-Deck-Tracker#2265]
Well, the title says it all. Got a deck made for myself, and it is active. but it just doesn't show any stats neither i win or lose, nor does it show any card draw.

**Comment by riQQ** [comment]
https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#not-working

**Comment by vilzu** [comment]
faq checked already, and done. still not working.

**Comment by riQQ** [comment]
So what's your answer to this: `Check if the log files are created at <HearthstoneDir>\Logs and written to`

**Comment by vilzu** [comment]
Yes, in there are log files in the folder, and they have been updated atleast every few days. Last time updated 5 days ago alltho i have played 2 days ago as well.

**Comment by riQQ** [comment]
HDT gets all its information from these logs. If they aren't updated, HDT won't work. If your `log.config` file is correct, try reinstalling Hearthstone.

**Comment by vilzu** [comment]
Pfft. if that is all there is to do i'll use alternative and reinstall when i bother.
Thanks for your assistance, and i guess u can change this to solved then.

**Comment by riQQ** [comment]
I don't know if reinstalling Hearthstone will work.
You can close this issue yourself, if you want.

**Comment by Epix37** [comment]
See https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/2281#issuecomment-203767750
