### ISSUE TITLE
 It does not start Arena Helper v0.6.8 error occurs.

### ISSUE THREAD

**Issue by Roman-Omsk** [Epix37/Hearthstone-Deck-Tracker#2266]
Good afternoon! It does not start Arena Helper v0.6.8 error occurs.

Error picture posted here.

http://s019.radikal.ru/i643/1603/f9/0b6599435843.jpg

help fix the `problem. 

I think the error due cvextern.dll

but I could be wrong, tell me what is the error?

**Comment by Epix37** [comment]
Just opening an issue on the arena helper github (as you did) would have been enough. No need to open one here as well and send an extra email ;).
