### ISSUE TITLE
Insufficient memory to continue the execution of the program.

### ISSUE THREAD

**Issue by Zosoled** [Epix37/Hearthstone-Deck-Tracker#2267]
I tried Import > From Web on a fresh install of HDT. Program located at C:\Program Files (x86), Hearthstone directory is D:\Games\Hearthstone. Crash report attached.
[Crash report 2732016-29.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/190836/Crash.report.2732016-29.txt)

**Comment by Zosoled** [comment]
Confirmed moving HDT from drive C to drive D, alongside Hearthstone installation, resolves this issue.

**Comment by Epix37** [comment]
Try moving it back, I think you may have had something in your clipboard that caused HDT to run out of memory when trying to get the import URL from there.
