### ISSUE TITLE
[v0.13.18] Player/Opponent deck windows - No longer show tooltips

### ISSUE THREAD

**Issue by depechenode** [Epix37/Hearthstone-Deck-Tracker#2268]
As of the most recent update that added fading and themes to deck overlays (the decks displayed NOT on the HS interface itself but elsewhere on the screen), card tool tips no longer work on mouse hover.  The deck windows that are part of the HS interface do however still work for tool tips.

**Comment by Epix37** [comment]
Updated the [v0.13.18 download](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/download/v0.13.18/Hearthstone.Deck.Tracker-v0.13.18.zip) to include the fix for this.

Leave the issue open for now, I'll close it with the v0.13.19 release.

**Comment by depechenode** [comment]
thank you!

**Comment by Epix37** [comment]
fixed with v0.13.19
