### ISSUE TITLE
Shifted numbers in DT window and overlay display

### ISSUE THREAD

**Issue by Herretik** [Epix37/Hearthstone-Deck-Tracker#2269]
Hello. Since the last (or perhaps one before last) update I've been experiencing shifted numbers (and some words too i think) displayed both in the DT window and in game. Any clues how to fix this? Thank you.
![hearthstone 03-27-16 06-39-55](https://cloud.githubusercontent.com/assets/18102008/14066557/e23fdfda-f44c-11e5-8fd8-ea34968cb981.png)
![hsdt window](https://cloud.githubusercontent.com/assets/18102008/14066556/e23b21fc-f44c-11e5-900c-74d04326c9b7.png)

**Comment by Epix37** [comment]
See #2233.

The latest pre-release fixes this: https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.13.18
