### ISSUE TITLE
[v0.13.18] Overlay does not load deck panel order/settings

### ISSUE THREAD

**Issue by depechenode** [Epix37/Hearthstone-Deck-Tracker#2271]
When I set the order preferences for Card Count, deck name etc... it does not save between games sometimes or if I restart Deck Tracker.  Deck tracker sows the correct order in the system, but on screen it reverts to an order NOT specified by the setting in Options.  This is new issue since today's release.

**Comment by Epix37** [comment]
fixed with v0.13.19 pre-release
