### ISSUE TITLE
New font

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#2273]
The new font on the overlay seems more unreadable than before. It looks more similar to the Hearthstone font, but it is not as crisp and clear as the previous one. 

I think a thinner font would be better. It would be best to give us an option to choose whatever font we want, though.

**Comment by depechenode** [comment]
I personally love the new font.  Option is good idea!

**Comment by Epix37** [comment]
The only big difference is that the card font no longer scales separately from the card height: 

![screenshot 2016-03-27 22 24 38](https://cloud.githubusercontent.com/assets/7737910/14067694/b3100a78-f46a-11e5-8155-d18ea2e9337d.png)


This is not something I will"fix", as that feature had many problems of its own. DPI problems, performance issues and good animations would have been very difficult to achieve.

As a workaround for this: make the deck list region in the overlay as big as possible (`optons > overlay > general > unlock`) and if the problem still persists reduce the deck scaling under `options (advanced) > overlay > player/opponent`.


Maybe there will be card theme specific fonts in the future, but probably no full completely free choice.

This one is going to stay for now.
