### ISSUE TITLE
Long deck names appear in really tiny text on one line in the overlay

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#2274]
In the overlay, long deck names still appear on one line, so the text is really tiny. Perhaps split the text onto two lines if it's too long? I'm using the new beta version with the new Dark style.

**Comment by tknights2015** [comment]
I am seeing this also with the Dark style.

**Comment by Epix37** [comment]
fixed with v0.13.19 pre-release
