### ISSUE TITLE
Three extra rows in Replays -> Overall Stats

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#2275]
In the Replays Viewer, when you have Overall and Stats selected, the stats of all classes are shown.

In the latest beta, below the 9 classes and above the Total row, are 3 rows, with no class indicator for them, with values of "0-0" for 9 columns.

I'm not sure why these rows are appearing. They don't appear if I select Deck rather than Overall.

**Comment by Epix37** [comment]
same as #1775?

**Comment by GaryKing** [comment]
Oh yes that's the one. The only difference is I have 3 extra rows rather than 2. Probably related to the Brawl.

**Comment by Epix37** [comment]
Yup, it's non-default heroes. Will be fixed with the constructed stats update. 

Closing since duplicate.
