### ISSUE TITLE
Opponent's deck list doesn't disappear when viewing friends list 

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#2276]
In the latest beta, when I show my friends list, the opponent's deck list doesn't disappear anymore. I have the setting already enabled.

I have enabled "align opponent's deck list vertically", could that be the problem?

**Comment by Epix37** [comment]
Fixed with https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/3a2982dd21b1aed92b33e2321d9ff599aee32c30.

**Comment by Epix37** [comment]
fixed with v0.13.19 pre-release

**Comment by GaryKing** [comment]
The problem still seems to exist with this latest version.
