### ISSUE TITLE
Card count duplication bug in gameplay deck tracker...

### ISSUE THREAD

**Issue by WaxPaper** [Epix37/Hearthstone-Deck-Tracker#2277]
I searched but couldn't find a reference to this bug yet. I've actually been getting it for at least the last couple versions, and I'm using the latest version right now. I can't identify what dictates when the bug occurs versus when it doesn't... It just seems to be random; sometimes restarting the client will fix it but usually it won't. I'd say on average, it happens around 1/3rd of the time.

As you can see in the screenshots below, the in-game tracker shows what appears to be a duplicate count for each card in the deck, which doubles everything. As I pointed to in the pic, both player and opponents' cards and card counts are doubled. It will persist like that throughout gameplay, so that for example, if each player only has 10 cards left in their deck, the tracker will display 20. Here are the pics:

http://i.imgur.com/8N2Yffe.png

http://i.imgur.com/xl3lh8C.png

If there's anything I can do to help debug the issue, please let me know. Thanks!

**Comment by Epix37** [comment]
I think I managed to fix this just minutes ago :). Please give 13.18.5 a shot: https://github.com/Epix37/HDT-Test/releases/tag/v0.13.18.5

Also see https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/2270#issuecomment-202601170. It's not completely the topic of the issue bug I think it's that bug.

**Comment by WaxPaper** [comment]
Sounds like the problem, yep. I'm downloading the test version now but I gotta run so I won't be able to actually test it out until later. If you wanna keep the Issues section tidy, maybe go ahead and close this one if I don't reply back within 24 hours; otherwise I'll hit you back up and try to confirm...

The reason I can't check it by just opening up one game is because based on the past behavior of the bug, I'm assuming I'd have to play through a few games to make sure it's not happening anymore. Unless there's a way to force-duplicate it, I suppose... But yeah thanks for your work!

**Comment by Epix37** [comment]
The way I managed to reproduce it was by resetting the log reading (switching deck, switch to no-deck) right when the opponent turn started or the opponent played something. 

So what then happened was there were some remaining lines to be processed that would tell HDT the initial setup phase was already over, treating the then following cards (created in deck and hand) as if they were created later in the game.

**Comment by WaxPaper** [comment]
That update seemed to have fixed it... Only played about 5 games, but it didn't happen when I played or when I tried to force it using the method you explained. Thanks again!

**Comment by Epix37** [comment]
:+1: Closing this then.
