### ISSUE TITLE
Gang Up not working

### ISSUE THREAD

**Issue by heyjas0n** [Epix37/Hearthstone-Deck-Tracker#2278]
Ever since the HS update with the extra deck slots, Gang Up no longer shows the extra copies in deck tracker during the game. Playing Mill Rogue is too hard now.

**Comment by Epix37** [comment]
> Playing Mill Rogue is too hard now.

lol

Will be fixed with the next update.

**Comment by heyjas0n** [comment]
Awesome. Thank you.

**Comment by Epix37** [comment]
Fixed with v0.14.0
