### ISSUE TITLE
Overlay stops recording.

### ISSUE THREAD

**Issue by Doomelf** [Epix37/Hearthstone-Deck-Tracker#2279]
I was playing in a game and Hearthstone crashed (everything froze). I used Alt+F4 to restart quickly and get back in it. After Hearthstone started and it was my turn the overlay had all cards in it when I had only a few in deck.

Here is the log file if it will help.

http://pastebin.com/fBf52buR

**Comment by Epix37** [comment]
Did it work again with the next game?

Reconnect detection is broken in 13.17 due to changes in 4.2. That's fixed for the next update, not sure if this is the same problem though.

**Comment by Doomelf** [comment]
Yes it worked in the next game as normal. And yes, that is the problem i`m posting about. Glad it`s going to be fixed :)

**Comment by Epix37** [comment]
I mean I'm not sure it did not work in this case because of the reconnect detection. Could have other reasons. But I guess we will see.

Gonna close this for now. There should be another pre-relase today and probably a full release later this week.
