### ISSUE TITLE
Stolen minions not marked as created.

### ISSUE THREAD

**Issue by rappleby** [Epix37/Hearthstone-Deck-Tracker#2280]
When the opponent steals one of your minions, it is not marked as created for them.

When you steal an opponent's minion, it is marked as created for you.

Player.cs

		public void StolenByOpponent(Entity entity, int turn)
		{
			var ce = MoveCardEntity(entity, Board, Removed, turn);
			UpdateRevealedEntity(ce, turn);
			Log("StolenByOpponent", ce);
		}

		public void StolenFromOpponent(Entity entity, int turn)
		{
			var ce = MoveCardEntity(entity, Removed, Board, turn);
			ce.Created = true;
			UpdateRevealedEntity(ce, turn);
			Log("StolenFromOpponent", ce);
		}

**Comment by Epix37** [comment]
Outdated.
