### ISSUE TITLE
Not keeping track

### ISSUE THREAD

**Issue by Zildjian299** [Epix37/Hearthstone-Deck-Tracker#2281]
So i download deck tracker follow steps. Deck tracker does not keep track of when i play a card draw a card or anything opponent's cards dont show up. I have to manually show the overlay even thought its set to hide on main menu, I have to click it to show up. Exporting works but importing just keeps showing the help for importing not actually importing anything. Big issue is it not keeping stats on anything like why would i download this if i cant use it. I had issues with it finding hearthstone path finally fixed that now it just wont track stats of highlited cards in hand or anything please....help.......Warning|LogReaderManager.Stop is the only thing i found in log file.

**Comment by Epix37** [comment]
See https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#not-working

**Comment by Zildjian299** [comment]
i dont have games and statisics i just have is old games and statistics. Arena runs and statistics. Last replay. Select replay and rolad replay from file

**Comment by Zildjian299** [comment]
i have tried to navigate that configuration but cant figure out how to set everything its very confusing is there not an easy way or like a copy past in a folder?

**Comment by Zildjian299** [comment]
witch log.config file yours or hearthstone's cause hearthstone already has it set up

**Comment by Epix37** [comment]
explained here https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Setting-up-the-log.config

**Comment by Epix37** [comment]
If that is set up correctly any you have no log files created/updated in `<HearthstoneDir>\Logs`, it's likely the same problem as #2265.

**Comment by Zildjian299** [comment]
Ok i think i got it but 1 more question what do i do with windows button and r for the run what do i put in that? why cant i just delete the log.config and paste it in? im a bit confused on the win+R

**Comment by Epix37** [comment]
Pasting `%LocalAppData%/Blizzard/Hearthstone` in the Run dialog is the quickest way of opening that location, is all.

**Comment by Zildjian299** [comment]
Ok thank you so very much sorry i have been spamming iv been going at this for 12 hrs lol

**Comment by Zildjian299** [comment]
Yea i replaced the file with that one but no dice......still not tracking meh...i apreciate your help but i think i give up lol

**Comment by Epix37** [comment]
Have a look at #2265. Sounds like you're having the same problem.

**Comment by Zildjian299** [comment]
3-30-2016@ 3:09am last log file time

**Comment by Zildjian299** [comment]
Ok so just reinstalling hearthstone might work so i guess ill try that do i have to re enter that log.config file after as well?

**Comment by Epix37** [comment]
The log.config should not change when un/re-installing hearthstone I think.

**Comment by Zildjian299** [comment]
Alrighty ill give it a go thanks for you instant reply's to my comments i will help fund your overlay when i can. Thanks a bunch.

**Comment by Zildjian299** [comment]
Well just re-downloaded it and still not working is there anything els i can try my cards arent even lighting up green for what i have in my hand....

**Comment by Zildjian299** [comment]
This is my log file.   4:14:53 AM|Info|DeckList.ActiveDeck >> Set active deck to: Greasy (Mage)
4:14:55 AM|Info|MainWindow.SelectDeck >> Switched to deck: Greasy
4:14:55 AM|Warning|LogReaderManager.Stop >> LogReaders could not be stopped, stop already in progress.
4:14:55 AM|Info|GameV2.Reset >> -------- Reset ---------
4:14:55 AM|Info|Player.Name >> [Player] 
4:14:55 AM|Info|Player.Name >> [Opponent] 
4:14:55 AM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
4:14:55 AM|Info|DataIssueResolver.RemoveDuplicateMatches >> Checking for duplicate matches...
4:14:55 AM|Info|BackupManager.Run >> Running BackupManager
4:14:55 AM|Info|BackupManager.Run >> Backup for today already exists
4:14:55 AM|Info|HearthStatsManager.SyncAsync >> starting sync process: forceFullSync=False, background=True
4:14:55 AM|Info|HearthStatsManager.AddBackgroundActivity >> background process indicator enabled
4:14:55 AM|Info|HearthStatsManager.SyncAsync >> Checking HearthStats for new decks...
4:14:55 AM|Info|HearthStatsManager.DownloadDecksAsync >> trying to download decks
4:14:55 AM|Info|HearthStatsAPI.GetDecksAsync >> getting decks since 1459324001
4:14:55 AM|Info|PluginManager.LoadPlugins >> Loading Plugins...
4:14:55 AM|Info|Updater.GetLatestVersion >> Checking for live updates... (current: 0.13.17.0)
4:14:55 AM|Info|GameEventHandler.ResetConstructedImporting >> Reset constructed importing
4:14:56 AM|Info|Updater.GetLatestVersion >> Latest live version: 0.13.17.0
4:14:56 AM|Info|Updater.GetLatestVersion >> Checking for beta updates... (current: 0.13.17.0)
4:14:56 AM|Info|Updater.GetLatestVersion >> Latest beta version: 0.13.5.0
4:14:56 AM|Info|HearthStatsManager.DownloadDecksAsync >> no new decks
4:14:56 AM|Info|HearthStatsManager.SyncAsync >> Checking HearthStats for new matches...
4:14:56 AM|Info|HearthStatsManager.DownloadGamesAsync >> trying to download games
4:14:56 AM|Info|HearthStatsAPI.GetGamesAsync >> getting games since 1459324001
4:14:57 AM|Info|HearthStatsManager.DownloadGamesAsync >> no new games
4:14:57 AM|Info|HearthStatsManager.SyncAsync >> Checking for new local decks...
4:14:57 AM|Info|HearthStatsManager.SyncAsync >> Checking for new local versions...
4:14:57 AM|Info|HearthStatsManager.SyncAsync >> Checking for edited local decks...
4:14:57 AM|Info|HearthStatsManager.SyncAsync >> Checking for new local matches...
4:14:57 AM|Info|HearthStatsManager.RemoveBackgroundActivity >> background process indicator disabled
4:14:57 AM|Info|HearthStatsManager.SyncAsync >> finished sync process
4:15:06 AM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
4:15:47 AM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
4:16:30 AM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
4:16:31 AM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
4:16:33 AM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
4:17:40 AM|Info|OverlayWindow.Update >> Refreshed overlay topmost status

**Comment by Epix37** [comment]
HDT get's 99% of it's information from the files in `Hearthstone/Logs`, if Hearthstone does not create/update those HDT can't work :/.

**Comment by Zildjian299** [comment]
how can other people make it work? mine is not updating and theirs is?

**Comment by Epix37** [comment]
This seems to be a pretty rare case, usually Hearthstone creates the logs just fine. 

No idea why it happens. Probably something machine specific in your end.

**Comment by Zildjian299** [comment]
Its fine every time i try to get a leg up on competition i get kicked in the @@@ lol wish i had better luck.... Thanks for your time i hope i can find a way to to figure it out maybe ill call hearthsone and have them figure it out its thier log files lol

**Comment by Zildjian299** [comment]
Depressed<---------

**Comment by Epix37** [comment]
I would be interested to know if the blizzard support would be willing to help you out with this. I doubt it though.

@jleclanche any idea why Hearthstone might not create log files?

**Comment by Zildjian299** [comment]
Well i got a ticket out let see what happens. I'll let you know about the response. Have a good night

**Comment by Epix37** [comment]
You too, good luck.

Closing this for now.

**Comment by Zildjian299** [comment]
this might interest you http://us.battle.net/hearthstone/en/forum/topic/18122597684

**Comment by Epix37** [comment]
Old problem that has long been fixed :). 
The log.config can be configured to create different output files, the one that HDT currently sets it to and uses (which creates files in Hearthstone/Logs) no longer has that problem. 

It was an issue with the output_log.txt, which contains all of the logs combined into one.

See #1274 for more information.

**Comment by Zildjian299** [comment]
Found a fix Check all virus protection programs running on your pc and disable them or allow deck tracker through also if this does not work you can go to users your name mine is tony then app data find hearthstone folder blizzard and blizzard entertainment and delete them. Then re-download the game and re download deck tracker. Dont open hearthstone link deck tracker to open with hearthstone and find the file path also fix the log.config file again boot it up and your good to go. Deleting all folder will clear old cache folders and log folders and the game this fixes this issue. Again thanks for all your supportEpix37.

**Comment by Epix37** [comment]
Great! Happy to hear you made it work.

And thank you for getting back to be with how!
