### ISSUE TITLE
Windows 10 - The process was terminated due to an unhandled exception.

### ISSUE THREAD

**Issue by pendoza** [Epix37/Hearthstone-Deck-Tracker#2282]
Everytime I start the deck tracker the program stops responding immediately. I need to start the program multiple times before it runs.

I get the following errors in the eventlog:

"Application: Hearthstone Deck Tracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address C224F06C
Stack:

Faulting application name: Hearthstone Deck Tracker.exe, version: 0.1.0.0, time stamp: 0x56e99f5a
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0xc224f06c
Faulting process id: 0x1cbc
Faulting application start time: 0x01d18aa55ecf7a27
Faulting application path: C:\Users\Michel\Desktop\Hearthstone Deck Tracker\Hearthstone Deck Tracker.exe
Faulting module path: unknown
Report Id: 78508529-9bad-402d-aec5-73149fd2da22
Faulting package full name: 
Faulting package-relative application ID: 

Do you know whats going on? It's been like this since 2 updates ago.

**Comment by Epix37** [comment]
2 updates ago including pre-releases? In other words: what version are you currently on?

If not on the v0.13.19, try that one: https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.13.19


So it does work after starting multiple times? That's really odd.

Please check if there is there a log entry in the windows event viewer (Windows start menu > control panel > management tool > event viewer > windows log > application).

**Comment by pendoza** [comment]
I am on v0.13.17. 

Hmm normaly it would tell me if there is an update. Now it didnt it seems. I posted the 2 logs from the eventlog. I am an IT guy myself so just tell me what to do :).

I got error 1000:
Application: Hearthstone Deck Tracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address C224F06C
Stack:

And after it error 1002:
Faulting application name: Hearthstone Deck Tracker.exe, version: 0.1.0.0, time stamp: 0x56e99f5a
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0xc224f06c
Faulting process id: 0x1cbc
Faulting application start time: 0x01d18aa55ecf7a27
Faulting application path: C:\Users\Michel\Desktop\Hearthstone Deck Tracker\Hearthstone Deck Tracker.exe
Faulting module path: unknown
Report Id: 78508529-9bad-402d-aec5-73149fd2da22
Faulting package full name: 
Faulting package-relative application ID:

**Comment by riQQ** [comment]
https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#not-starting

**Comment by Epix37** [comment]
You only get notifications for pre-releases if you have beta updates enabled.

**Comment by pendoza** [comment]
Im in the options but cannot find the beta update option anywhere. Where can I enable it?

**Comment by pendoza** [comment]
This is the third message in application log:

Fault bucket , type 0
Event Name: BEX
Response: Not available
Cab Id: 0

Problem signature:
P1: Hearthstone Deck Tracker.exe
P2: 0.1.0.0
P3: 56e99f5a
P4: StackHash_bdcb
P5: 0.0.0.0
P6: 00000000
P7: PCH_62_FROM_ntdll+0x0007718C
P8: c0000005
P9: 00000008
P10: 

Attached files:
C:\Users\Michel\AppData\Local\Temp\WERD21D.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Hearthstone Deck_9485f7c4c2d323ac0b1dbb4ab275a62c52d53f_fed81695_1d4dd809

Analysis symbol: 
Rechecking for solution: 0
Report Id: 78508529-9bad-402d-aec5-73149fd2da22
Report Status: 97
Hashed bucket:

**Comment by riQQ** [comment]
`Tracker > Sttings > Check for BETA updates`

**Comment by riQQ** [comment]
Have you checked this:
> No logs with source .NET Framework in the event viewer?

**Comment by pendoza** [comment]
There is no such option in my tracker to enable beta updates.

**Comment by pendoza** [comment]
fuck i needed to enable advanced options... pfff lol.

**Comment by pendoza** [comment]
Creating temp file directory
Downloading latest version... 21705/21705KB (100%)
Extracting files...
Writing AForge.dll
Writing AForge.Imaging.dll
Writing AForge.Math.dll
Writing De.TorstenMandelkow.MetroChart.dll
Writing Garlic.dll
Writing HDTHelper.exe
Writing HDTUninstaller.exe
Writing HDTUpdate.exe
There was a problem updating to the latest version. Pressing any key will direct you to the manual download.

**Comment by pendoza** [comment]
I will just remove everything and use the new one. Maybe that will help.

**Comment by pendoza** [comment]
Nope instant crash when I open it. 

Application: Hearthstone Deck Tracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address B6C4F06C

It seems it also uses v4.0.. Why not 4.5?

**Comment by spurries** [comment]
I Seem to be having a similar issue on Windows 10, but latest version of the program.  Nothing ever opens, and I get similar errors

**Comment by spurries** [comment]
Hey, might have found the reason.  Are you opening the zip in WIndows 10 and from the unzipped folder trying to run the .exe?  If so, first extract the whole folder to your computer, then run it from there.  This worked for me.
