### ISSUE TITLE
Card Count Text mispositioned

### ISSUE THREAD

**Issue by Psychode** [Epix37/Hearthstone-Deck-Tracker#2284]
The text for my card counter and draw counter is not in the correct position since the last update. Both have moved about an inch to the right, so my cards in hand is almost in the area for cards in deck, and card in deck is to the right of the entire overlay. The same relative positioning issue happens for draw chances and for opponent draw chances/card counter.

**Comment by Epix37** [comment]
Is this with v0.13.17? The same problem as this? https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/2233#issuecomment-198103524

Or with the v0.13.19 pre-release?

**Comment by Psychode** [comment]
Yes. Sorry. It was the 13.17 issue, but it resolved when I downloaded the 13.19 pre-release.

**Comment by Epix37** [comment]
:+1:
