### ISSUE TITLE
Created/Discovered/Gift Cards missing

### ISSUE THREAD

**Issue by dl123456** [Epix37/Hearthstone-Deck-Tracker#2286]
Cards created by Discover minions are not being tracked (e.g. cards from Ethereal Conjurer , for tonight's games (at least 3 games) after I have updated HDT.

I looked through settings to see if I didnt enable that option after the update, but I couldn't seem to find it, assuming there is one.

I am pretty sure it worked before, did you remove it? If so can you tell me which version still has that feature included?

Thanks.

**Comment by Epix37** [comment]
What list are you talking about? Opponent? Player? With, without deck?

Created minions are now only visible in deck lists while in hand or deck (the former requires `options > overlay > player > highlight cards in hand` to be enabled), no longer when they were played. The reasoning being that is that there is not information to be gained by seeing cards that were not actually in the opponent/player deck after they are no longer relevant (i.e. already played). And it keeps the deck lists a lot cleaner.

There are special cases where those cards *could* be relevant, like when playing against mill rogue - that is something that would fit in well with a feature like #961.

**Comment by DerApfelstrudel** [comment]
I think almost some card mark don't work properly. For example the mulligan mark doesn't seem to work either. Only the coin itself.

**Comment by dl123456** [comment]
Opponent's played cards, and yes I really want that feature back that track that, as I just lost a few games because I wasnt able to tell the card(s) he played last turn whether or not was from discover after the in-game history tab removed them (e.g. fatigue elise mage/elise warrior e.t.c.) , as I usually alt-tab till its my turn.

So which version do I have to roll back to for that feature?

**Comment by Epix37** [comment]
You still can get that information from the state of the list it is now, can't you? If the card is not in the list it was from discover. Another way of telling would be to see if he previously had a card marked as created in his hand and now no longer does.

The last release before v0.14.0 was one v0.13.17: https://github.com/Epix37/Hearthstone-Deck-Tracker/releases

**Comment by Epix37** [comment]
Closing in favor of #961.

**Comment by ShadowFox950** [comment]
It seems it's unable to track gift cards for Decks like Mage Decks, where the Grand Magister casts all spells that were cast by you but didn't start in your deck, is there a way to make the Deck Tracker show that? In it's current state all that happens is they completely Vanish from the Deck list and Graveyard.
