### ISSUE TITLE
HDT didnt track Raven Idol created by Raven Idol

### ISSUE THREAD

**Issue by askarmuk** [Epix37/Hearthstone-Deck-Tracker#2291]
Happened on the current brawl (mb this has no difference):
- druid played Raven Idol (ri) on turn 1 if I remember correctly
- later he played another ri created by first ri
- HDT didnt count 2nd played ri in any way
- later he played ri that was in his deck, not created by another card. It was correctly counted as 2nd played ri

log: http://pastebin.com/jCzPWgUB

![bandicam 2016-03-31 19-44-06-520](https://cloud.githubusercontent.com/assets/8628595/14188122/e274e99a-f79f-11e5-8e68-1b5d776c77d7.jpg)

**Comment by Epix37** [comment]
This is working as intended currently. See my explanation in #2286.
