### ISSUE TITLE
Overlay sizing issues

### ISSUE THREAD

**Issue by ivancuric** [Epix37/Hearthstone-Deck-Tracker#2294]
The default scaling is too big, and at 80% the font becomes hard to read. It's too wide and heavy to be used in smaller sizes with an outline.

The opponent's overlay now covers his rank and most of the chat bubble.

And the secrets seem to have a larger base size compared to the deck trackers.

**Comment by Epix37** [comment]
What do you mean by scaling? The automatic vertical scaling when there's too many cards or `options (advanced) > overlay > player/opponent > scaling`? The latter looks completely fine to me even at 60% scaling. Please post a screenshot of your issue.

**Comment by ivancuric** [comment]
Nah, not the auto scaling. The base size is a lot bigger than the old version:
![hs-sizing](https://cloud.githubusercontent.com/assets/2827047/14230973/1141d3ec-f970-11e5-8e95-0bdae65ad331.jpg)

The old one was more compact, with crisper text.
If I bump down the scaling to 80%, to make it the same size as the [old one](https://camo.githubusercontent.com/f577fb2c3b2a5bcdef932346105a41463342c198/687474703a2f2f692e696d6775722e636f6d2f335a5839456c6d2e6a7067), the font renders a bit blurry.

**Comment by Epix37** [comment]
Uhm.. there's a small chance it gets better when you set it to 79% or 81%. 

I *think* I can see what you mean, but there's a good chance that's just to the image being a jpg. The "old" screenshot looks just as blurry to me.

Even then, there's nothing I can do about this, sorry. The font only has that one style.
