### ISSUE TITLE
Priest's Shadow Madness card adds a minion to the opponents deck without a gift icon

### ISSUE THREAD

**Issue by HellbringerOnline** [Epix37/Hearthstone-Deck-Tracker#2296]

**Comment by Epix37** [comment]
This is with v0.14.0? Please provide screenshots / logs.

**Comment by HellbringerOnline** [comment]
No this is with previous version

**Comment by HellbringerOnline** [comment]
I do not have screenshots

**Comment by Epix37** [comment]
Is this still an issue with v0.14.0 then?

**Comment by HellbringerOnline** [comment]
I dont know yet

**Comment by Epix37** [comment]
Closing this for now. Let me know if it happens again.
