### ISSUE TITLE
Priest's Unstable Portal card (after Thoughtsteal)

### ISSUE THREAD

**Issue by HellbringerOnline** [Epix37/Hearthstone-Deck-Tracker#2297]
Priest's Unstable Portal card (after Thoughtsteal) adds a minion to the opponents deck without a gift icon (not sure). This minion shown in the opp. deck in replay.

**Comment by Epix37** [comment]
This is with v0.14.0? Please provide screenshots / logs.

**Comment by HellbringerOnline** [comment]
No this is with previous version.

**Comment by HellbringerOnline** [comment]
I do not have screenshots.

**Comment by HellbringerOnline** [comment]
![22](https://cloud.githubusercontent.com/assets/14059683/14213574/c61e3df0-f849-11e5-9729-5d68908db0e2.PNG)

**Comment by Epix37** [comment]
Is this still an issue with v0.14.0 then?

**Comment by HellbringerOnline** [comment]
I dont know yet

**Comment by HellbringerOnline** [comment]
![5](https://cloud.githubusercontent.com/assets/14059683/14213667/50b27954-f84a-11e5-9516-3cf927c96c97.PNG)
![6](https://cloud.githubusercontent.com/assets/14059683/14213685/623e5d5a-f84a-11e5-93c4-5980ff07f17f.PNG)

**Comment by HellbringerOnline** [comment]
![7](https://cloud.githubusercontent.com/assets/14059683/14213691/67bf460e-f84a-11e5-89a1-a6472a773afe.PNG)

**Comment by HellbringerOnline** [comment]
![8](https://cloud.githubusercontent.com/assets/14059683/14213703/78ffdbea-f84a-11e5-8aa4-1ead93a085b7.PNG)

**Comment by Epix37** [comment]
Replays never had those indicators. The current replay viewer will also become obsolete soon and will therefore not be fixed/updated anymore.

**Comment by Epix37** [comment]
The first screenshot is the "show opponent deck" button rather than the overlay during a game? That is already covered in #890 then.

**Comment by HellbringerOnline** [comment]
In overlay minion displayed without gift icon

**Comment by Epix37** [comment]
Closing this for now (since it's with an old version). Let me know if you see the overlay part of this problem happen again.
