### ISSUE TITLE
Export to Hearthstone

### ISSUE THREAD

**Issue by tjenoe** [Epix37/Hearthstone-Deck-Tracker#2298]
Have some troubles exporting to Heartstone.

During the export "Use the friends list to start a conversation with a friend."  keeps popping up.

I miss a lot of cards and there are cards added witch aren't in the deck.

Lowering the export speed does help but does not solve the problem.

Did try running HDT as admin.

**Comment by Epix37** [comment]
Restarting hearthstone should solve the friends list error message.

See if setting a start delay or changing hearthstone to windows mode helps with the export.
