### ISSUE TITLE
 is possible to show the time?

### ISSUE THREAD

**Issue by Kakene1** [Epix37/Hearthstone-Deck-Tracker#2300]
Is it possible to show what time it is  in game or server time? would be handy if that could be made possible without to much effort

**Comment by Epix37** [comment]
Doesn't the game already do that in the bottom left?

**Comment by Kakene1** [comment]
ye but its grey and not readable really and i would love to have it on top
next to batteries ^^
2. apr. 2016 2:04 p.m. skrev "Alexander Zeier" <notifications@github.com>:

**Comment by Epix37** [comment]
I don't think there's much point in adding that, sorry. 

Ask blizzard to make it more readable :P.
