### ISSUE TITLE
Blank Arena Runs

### ISSUE THREAD

**Issue by CruzinToVictory** [Epix37/Hearthstone-Deck-Tracker#2303]
Today I noticed that my arena run average was a bit low so I dug into the stats a bit more. There are a bunch of totally blank runs at the botom of my stats that are counting as zero wins. I couldn't figure out how to delete them, so I tried to delete a deck that had no stats.

I deleted 2-3 of these before I realized that all of a sudden most of my Arena decks on the main page say "No Stats", even though I'm seeing stats on the "Arena Runs & Satistcs* page. I probably deleted a functioning run by mistake doing this, but I can't figure out why there are blank runs recorded and how to remove them.

For what it's worth, I downloaded the Arena Helper a few days ago, so I have a feeling that has something to do with it. Any idea how to fix it?

Thanks!

Edit: It also appears to have duplicated some of my runs, but they both say "No Stats" So I'm not sure which one to delete.

Update: I figured out part of it! I had the stats filtered to "this season", which is why it showed blank on that page. I'm not sure what's causing the blank runs, but I was at least able to find and delete them.

**Comment by CruzinToVictory** [comment]
Here are some screen shots, if they help:

![blank runs](https://cloud.githubusercontent.com/assets/10316945/14230128/31f10e14-f911-11e5-9b6a-d71a375fde7f.PNG)
![nostats](https://cloud.githubusercontent.com/assets/10316945/14230127/31f0c94a-f911-11e5-8b67-87492b9c9127.PNG)

**Comment by Epix37** [comment]
@Rembound could this be arena helper?

**Comment by rembound** [comment]
Arena Helper does not mess with old arena runs. If you use the save deck functionality, it adds new decks, but they are saved with the correct flags. Otherwise it does not interfere with deck tracker.

**Comment by Epix37** [comment]
I was rather thinking that Arena Helper could have created duplicate arena runs (in combination with the HDT auto arena importing).

**Comment by rembound** [comment]
Decks aren't saved by default. The user would have to enable auto-saving or click the save deck button, in addition to clicking the HDT import prompt. Each deck also contains a unique guid, until a new deck is created. In my stats, I only see one arena run without stats in a long list of runs. In addition, I have never seen a duplicated deck.

**Comment by Epix37** [comment]
Thanks for the clarification rembound.

Not sure what this is about then, but since you managed to work around it I'm gonna close this for now.

Let me know if this persists to be a problem.

**Comment by fofoni** [comment]
I also have a blank arena run (my fault: I deleted all of the matches of that run, and then I was left with a 0-0 arena run). Is there any way to delete the run itself? I think it's odd that you can delete the matches, but can't delete the run.

**Comment by riQQ** [comment]
Have you tried deleting the corresponding deck?

**Comment by fofoni** [comment]
It worked! Thanks :)
