### ISSUE TITLE
Setup constructed importing bug, with a little troubleshooting

### ISSUE THREAD

**Issue by matteo-mosca** [Epix37/Hearthstone-Deck-Tracker#2304]
Hi there, I know there has been already issue #2250 but I am experiencing the same problem.

The very first time I used constructed importing worked flawless, then after I changed my collection even by 1 single card it stopped working, getting me decks with only a few cards and even of a different class of the deck I was importing.

I have done a little troubleshooting myself, hoping to provide some insight.

I checked what gets written when you run `setup -> advanced -> Setup constructed importing` and I saw that the `config.xml` file in the `%appdata%` is the one.

I saved a copy before doing the procedure, then changed my collection by crafting a card, ran the procedure, and compared the two files with KDiff, and they were binary equal.

So it seems, to me, that the collection data is not getting updated.

Maybe a functionality that allows to reset completely this data before doing the setup again might help?

Thanks.

**Comment by Epix37** [comment]
Why not post this in #2250 then? Closing in favor of that one.

I'll take a look later, but just from looking at the code, saving that data should work fine. Maybe it just imported the same collection? Try modifying the original one before running it.

**Comment by matteo-mosca** [comment]
Yeah sorry, I saw that one closed and I didn't want to reopen it.
