### ISSUE TITLE
Exporting now clicks "0 Mana" filter

### ISSUE THREAD

**Issue by Zesaric** [Epix37/Hearthstone-Deck-Tracker#2306]
I noticed that since 0.14.1 the exporting does not work properly anymore - at least on my PCs (tried it on several). When exporting to  HS, the Deck Tracker "clicks" the "0 Mana" filter first, meaning none of the cards above 0 Mana are found.

Interestingly, when I manually set the filter to "0 Mana" before exporting, the export does work! Means the problem really is that HDT does one click during export which it shouldn't.

Hopefully this can be solved soon, I keep forgetting that now I always have to select 0 Mana before being able to export... ;-)

Thanks in advance for your efforts!

**Comment by Epix37** [comment]
Try increasing the start delay in `options (advanced) > tracker > exporting`. If that doesn't help, you can disable `auto clear filters`.

**Comment by Zesaric** [comment]
Yep, increasing the delay (1s > 2s) did the trick, thanks a lot for your quick help! :-)
