### ISSUE TITLE
Hearthstone Deck Tracker can't Export when Synergy is running

### ISSUE THREAD

**Issue by ryanrapini** [Epix37/Hearthstone-Deck-Tracker#2307]
Updated to the latest version today.

Now Importing to collection no longer works.

### Description of issue:

1. In Hearthstone I navigate to a new, empty deck.
1. In HDT I click Export > To Collection
1. I click Export button to confirm
1. Mouse snaps to the title of the deck in the Hearthstone window (In the case of the logs below, "Custom Rogue")
1. Nothing happens. 

![](https://i.imgur.com/qIbQ4Za.png)
6. Eventually HDT gives up.

I get the following log:

`1:46:53 PM|Info|DeckExporter.Export >> Exporting deckname:Mill, class:Rogue, cards:30
1:46:53 PM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
1:46:53 PM|Info|DeckExporter.Export >> Waiting for 0 seconds before starting the export process
1:46:53 PM|Info|ExportingActions.ClearDeck >> Clearing deck...
1:46:53 PM|Info|ExportingActions.SetDeckName >> Setting deck name...
1:46:53 PM|Info|ExportingActions.ClearManaFilter >> Clearing "Zero" crystal...
1:46:54 PM|Info|ExportingActions.ClearSetsFilter >> Clearing set filter...
1:46:54 PM|Info|ExportingActions.CreateDeck >> Creating deck...
1:46:54 PM|Info|ExportingActions.AddCardToDeck >> try to export card: Backstab(2)
1:46:55 PM|Info|ExportingActions.AddCardToDeck >> try to export card: Preparation(2)
1:46:56 PM|Info|ExportingActions.AddCardToDeck >> try to export card: Shadowstep(2)
1:46:57 PM|Info|ExportingActions.AddCardToDeck >> try to export card: Deadly Poison(2)
1:46:57 PM|Info|ExportingActions.AddCardToDeck >> Exporting aborted, window lost focus
1:46:57 PM|Info|OverlayWindow.Update >> Refreshed overlay topmost status`

## Relevant info

HDT v0.14.1 - Updated it today, it was working yesterday with whatever the last release was.
Windows 10 Pro 64 bit, 3 monitors, 
Hearthstone is running in fullscreen

**Comment by ryanrapini** [comment]
As I was writing this i figured out the issue. I'm running [Synergy](http://synergy-project.org/) now. I don't know if this is worth fixing, as you can always just tell users to disable synergy when importing decks.

Do whatever you want with this issue, sorry for wasting your time.

Might be useful to fix though.

**Comment by Epix37** [comment]
Try if running HDT as admin has any effect. 
But yea. if that's not working I'm not sure how I would even go about fixing this. There's not much I can do beyond sending clicks/keystrokes.

**Comment by Epix37** [comment]
Closing this for now.
