### ISSUE TITLE
The font of the timers has changed? Can't change it back?

### ISSUE THREAD

**Issue by PlanK69** [Epix37/Hearthstone-Deck-Tracker#2309]
Hi.

The font of the timers (player timer, round timer and opponent timer) has changed from the normal "Belwe Bd BT" front (which I really like) to some other kind of strange font.

Is there a way to change it back? Because I've looked and can't find any settings in 'appearance' on the tracker to change it to what I want it to be.

Thanks in advance for your help

**Comment by Epix37** [comment]
There is no way to change the font, nor are there currently plans for reverting the change or adding customization, sorry. 

You'll get used to it :).
