### ISSUE TITLE
Problem updating

### ISSUE THREAD

**Issue by TommyLeeJump** [Epix37/Hearthstone-Deck-Tracker#2310]
Hello, I come for help because I'm stuck with my 13.9 version.
Everytime I open Hearthstone Deck Tracker there's the automatic update but I always get this when I try to install it:
Creating temp file directory
Downloading latest version... 21705/21705KB (100%)
Extracting files...
Writing AForge.dll
Writing AForge.Imaging.dll
Writing AForge.Math.dll
Writing De.TorstenMandelkow.MetroChart.dll
Writing Garlic.dll
Writing HDTHelper.exe
Writing HDTUninstaller.exe
Writing HDTUpdate.exe
There was a problem updating to the latest version. Pressing any key will direct you to the manual download.

I tried downloading it manually but it doesn't work either. It doesn't seem to launch. It's been at least month it's like that :'(
I have Windows 10, I don't know if that helps. 

Here's the log file: http://pastebin.com/pghyvLMq

Thank you for your help!

**Comment by Epix37** [comment]
You should be able to just manually download it (as you did) and overwrite all the files. Make sure to actually extract the zip before running it.

**Comment by gotchapt** [comment]
Yep, update is broken for me too.

**Comment by TommyLeeJump** [comment]
That's what I did but it still didn't work. 
But I downloaded the 13.10 and then upgraded to 14.1 and it seems to work!
Thank you anyway and keep up the good work!

**Comment by Epix37** [comment]
Very strange. Glad you made it work though.
