### ISSUE TITLE
Doesn't detect draw of second execute

### ISSUE THREAD

**Issue by NitsuaRevaew** [Epix37/Hearthstone-Deck-Tracker#2312]
Title explains it, in warrior decks, it never detects the second draw of execute, which means when i go to fatigue it doesnt start counting fatigue draws.

**Comment by Epix37** [comment]
Please provide logs ([see here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)) and screenshots.

**Comment by Epix37** [comment]
Closing for lack of response.
