### ISSUE TITLE
Cards disappearing from decklist

### ISSUE THREAD

**Issue by aLnado** [Epix37/Hearthstone-Deck-Tracker#2317]
Im having this weird problem that some cards just disappear from the decklist, I tried reinstalling, getting an old version and updating from it but none of this worked, the problem isnt present on version 4.10.0 though, just on the new one.

![image](https://cloud.githubusercontent.com/assets/18297817/14303225/2306df6c-fb7f-11e5-880d-dc0d57ad21b3.png)

![image](https://cloud.githubusercontent.com/assets/18297817/14303252/4cc3e11a-fb7f-11e5-99d1-b114a2cce774.png)

the bug happens with random cards, but most of the time I see it happening with azure drake and boom, and sometimes with more than just 1 card

**Comment by culinko** [comment]
Same issue as #757.

**Comment by Epix37** [comment]
Closing in favor of #757. 

I sadly still have no idea why this happens.
