### ISSUE TITLE
Incorrect Emperor Thaurissan Reduction Totals

### ISSUE THREAD

**Issue by adhocish** [Epix37/Hearthstone-Deck-Tracker#2318]
Despite Thaurissan dying 2 turns ago, the counter for his ability continued.

Logs — http://pastebin.com/eku12T8m

![thaurissan-tick-bug](https://cloud.githubusercontent.com/assets/3294357/14327852/2f1848f8-fc02-11e5-971d-08c3549ec929.PNG)

**Comment by Epix37** [comment]
#2301

**Comment by adhocish** [comment]
whoops, my bad!
