### ISSUE TITLE
Nothing works since system backup.

### ISSUE THREAD

**Issue by riass** [Epix37/Hearthstone-Deck-Tracker#2321]
Hey!

So I did a system backup for certain reason to 1 day back. Since then nothing works, no card tracking, no enemy card tracking, the program doesn't show my deck. The only way i can see my deck if I uncheck "hide in menu" so the program thinks i am always in the menu, but it doesn't follow the cards at all, also the position of it reseted. I tried reinstall the program, reset everything to defaults with the uninstaller, restarted pc, even reinstalled hearthstone, reimport/recreated the decks, gave them different name. Its just not working and I don't know what else could i try. Any guesses?

**Comment by riQQ** [comment]
https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#not-working
