### ISSUE TITLE
Enhancement Request - Tracking for Joust cards

### ISSUE THREAD

**Issue by pagem** [Epix37/Hearthstone-Deck-Tracker#2323]
Hi, I have a suggestion for an enhancement to the tracker to capture and show (perhaps under the opponent deck) any cards pulled during resolution of a joust. And then when this card is played it moved from under the opponent deck to be listed in it as played.

This extra tracking would need to work if either the player or their opponent played a joust card.

Just one less thing to remember and would be pretty cool.

I searched and could not find a duplicate request - sorry if I missed one.

**Comment by Epix37** [comment]
This does (should?) happen.

**Comment by Epix37** [comment]
Just tried it to make sure this is indeed working, v0.14.1 *does* this.
