### ISSUE TITLE
addition to the localization

### ISSUE THREAD

**Issue by Drui7** [Epix37/Hearthstone-Deck-Tracker#2325]
when you hover over a picture card, we can see the name, description and type.
names and descriptions are displayed in different languages, and the type is always in English ("beast", "minion" or "spell").
please correct it.
for example Leper Gnome:
https://drive.google.com/file/d/0B2_jAjiSYLeCYldwSEw3MjZhWkU/view   -- in Russian
https://drive.google.com/file/d/0B2_jAjiSYLeCV2Y3SzV2bzE2czg/view  -- in Chinese
https://drive.google.com/file/d/0B2_jAjiSYLeCNnRtQ3c5b1NhcnM/view -- in English

**Comment by Epix37** [comment]
The rest of the translations come from automatically generated files. I wont be manually adding those.

This could either happen with #471, or if full card tool tips are added eventually.

**Comment by Drui7** [comment]
I am ready though all the necessary strings to translate into Russian, and in the shortest possible time and with maximum literacy! just give a list of strings, please
