### ISSUE TITLE
Create Auto-Squelch Feature

### ISSUE THREAD

**Issue by CorgiFat** [Epix37/Hearthstone-Deck-Tracker#2327]
I know its possible but I don't know if it's something that can be easily integrated into HDT. 

What I am proposing is that this new feature auto-squelch opponents whenever you start a game. Why? Because almost every streamer, and many players do this every single game. This feature will probably never be implemented by Blizzard due to the failed hero portraits they tried to sell.

**Comment by Epix37** [comment]
See #1986 for why this won't be added to HDT.

However, there is a plugin (I don't officially promote ;)) that does this: https://github.com/ko-vasilev/hearthstone-autosquelch
