### ISSUE TITLE
Hearthstone crashes after a couple of minutes

### ISSUE THREAD

**Issue by Amahora** [Epix37/Hearthstone-Deck-Tracker#2328]
I don't get an error message besides windows telling me that Hearthstone has stopped working.

Basically I've contacted Blizzard and they told me the problem was the fact that HDT keeps crashing over and over.

I'm running a fresh install of windows 10, I've installed .Net 4.6.1, DirectX + the C++ Redistrubutibles. I have no idea how to view the error log so maybe I could work out the problem for myself. So yea kinda need the infinate wisdom of you guys on this one

**Comment by Epix37** [comment]
So *does* hdt crash over and over? do you have any get crash reports you could upload?

**Comment by Amahora** [comment]
I've checked the %APPDATA% folder there doesn't seem to be a crash log folder.. Just let me know what you need and I'll post the info, I'm kinda new to HDT so sorry if I'm a little slow when it comes to troubleshooting

**Comment by Epix37** [comment]
There should be a crash reports folder with the exe.

**Comment by Amahora** [comment]
Exe Folder:

![hdt exe folder](https://cloud.githubusercontent.com/assets/18366104/14405001/24b424f0-fe7c-11e5-9553-0120f6764e63.jpg)

**Comment by Epix37** [comment]
Huh.. how then did blizzard support come to the conclusion that hdt keeps crashing? Does that actually happen?

**Comment by Amahora** [comment]
I have no idea. I basically sent them my MSInfo + DxDiag info and apparently he determined it from those reports. I haven't noticed HDT crashing but Hearthstone does run fine when I don't use HDT.

**Comment by Epix37** [comment]
No problem. Good luck :/.
