### ISSUE TITLE
Deck Tracker wont update

### ISSUE THREAD

**Issue by unsub24** [Epix37/Hearthstone-Deck-Tracker#2329]
When trying to update, it downloads and then goes through the extracting files,after that it says there was a problem updating and to click  any button to update manually.  So how do I update and make sure all my data is in the new version?

**Comment by unsub24** [comment]
Never mind I have this worked out. I just had to manually download and install. I thought if I did it like this it wouldn't carry over all my decks. Very nice program man, I love it!. If I wasent a broke ass sob I would donate. Keep up the good work!!

**Comment by Epix37** [comment]
:+1:
