### ISSUE TITLE
Can't move / resize Objects when unlocked

### ISSUE THREAD

**Issue by nicoell** [Epix37/Hearthstone-Deck-Tracker#2332]
I'm having problems moving/resizing the different objects. It looks normal I guess, but I just cannot interact with them.
http://imgur.com/Z25TuCJ

I tried enabling interactivity, disable Hiding in Background, using a clean new install (including clean Appdata folder). Nothing worked so i guess it's a problem with the MouseHook.

Here's the Log of me trying to Unlock the objects.
http://pastebin.com/rapMjhrZ

**Comment by Epix37** [comment]
Try 
- speficially setting a resolution in Hearthstone
- running Hearthstone in windowed mode / fullscreen
- running HDT as administrator

**Comment by nicoell** [comment]
Oh dear, the classic Run as Admin it is. It figures...
