### ISSUE TITLE
Stats not working properly

### ISSUE THREAD

**Issue by GunnarStahl** [Epix37/Hearthstone-Deck-Tracker#2335]
I am using HDT and I have a particular issue. English isn't my mother tongue, so I hope you will understand clearly.

Let's suppose I sue "Deck #1" to play a Game. It's brand new deck, so, 0 win, 0 loss.

I see the track on the right, and at the top of my decklist, it's written Deck #1 0-0 (0%). I win the game. This "title" now reads Deck #1 1-0 (100%). So I play another game. Whoops!! Title now reads "Deck #1 0-0 (0%)". My stats are resetted! Oh noes! So anyway, I play another game and I win. Title reads "Deck #1 1-0 (100%)". I play another game. Stats are reading 0-0 again!

So basically, it doesn't update my stats after each game.

I found out that, each time I finish a game (win or lose), if I don't go to "Hearthstats -> Sync Now", my stats will *never* update. So, after each game, I have to go to HDT to "Sync now" and it kinda bugs me out.

The situation I just described is on my GF laptop. She plays Hearthstone and that kind of stuff always happen with her stats. However, on my desktop, I have no problem at all. My stats are updating after each game without any issue. We even compared our settings to be sure it was okay. I even reinstalled HDT on her laptop to be certain.

So... what is wrong?
Thanks!

**Comment by Epix37** [comment]
Are the game modes you are trying to record enabled under `options > tracker > stats > record?

**Comment by GunnarStahl** [comment]
Yes!

**Comment by Epix37** [comment]
With what game mode does this happen? Ranked?

If you have recording enabled for ranked, but not casual, it could be this problem: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#ranked

**Comment by GunnarStahl** [comment]
Yes, it happen only with Ranked because she don't want it to track any other stats like casual and friends game for example.

**Comment by culinko** [comment]
Are the games listed in Stats/[OLD] Games & Statistics?

**Comment by GunnarStahl** [comment]
Alternative Screen capture is checked.
The options menu have a resolution set.

**Comment by GunnarStahl** [comment]
@culinko Yes, they are.

**Comment by Epix37** [comment]
What about black bars?

Try changing the resolution and/or windowed/fullscreen mode.

**Comment by GunnarStahl** [comment]
I just found out resolution was set to 1360*768 and my Windows resolution is 1366*768, so it may be that. She will test that.

**Comment by GunnarStahl** [comment]
Just tested with the other resolution. Same stuff.

After she won a game, her deck was showing the same stats 11-11 (50%). In HDT? Same thing, 11-11 (50%).
She "Sync'd now". HDT was showing 12-11 (52%).

She really have to Sync to have her stats updated. On my desktop, I don't have to do that.

**Comment by Epix37** [comment]
Try enabling recording casual games, see if that at least saves the games.

**Comment by GunnarStahl** [comment]
I went to her Stats and put "Ranked" in "Mode" to display all her Ranked games. Hell, no games AT ALL were recorded. 

It's all recorded as "Casual" games.

**Comment by GunnarStahl** [comment]
Does have the "Alternative screen capture" option checked may cause a problem?

**Comment by Epix37** [comment]
Possible. HDT will auto enable alt screen capture if the default method fails. Try disabling it with the changed resolution.

**Comment by GunnarStahl** [comment]
Problem solved.

By unchecking the "Alternative screen capture" option, her stats now update, and HDT now recognize she plays ranked games.

Thank you for your support, and keep up the good work with HDT, an AMAZING tool!!

**Comment by Epix37** [comment]
Awesome! :)
