### ISSUE TITLE
Multiple secrets have incorrect count

### ISSUE THREAD

**Issue by culinko** [Epix37/Hearthstone-Deck-Tracker#2338]
After #1588 has been fixed, some of the cases still remain bugged. This only applies for constructed modes.

1) After you triggered 2 copies of the opponent's secret and opponent played any new secrets, the overlay would correctly not show the secret (this case was fixed).

2) After you triggered one of the copy of opponent's secret and opponent played 2+ more secrets, the overlay would show 2+ for each secret, including the one that has already been activated (Redemption and Repentance in the picture below).

![multiple-secrets-2](https://cloud.githubusercontent.com/assets/11700272/14443971/e71919f2-0042-11e6-9f0f-65947a2a27bc.png)

3) If your opponent plays 3 or more secrets (from the deck, not created), the overlay shows 3+ for each secret, even though 2 is the deck limit.

![multiple-secrets](https://cloud.githubusercontent.com/assets/11700272/14443980/ee17ce6a-0042-11e6-9c61-a559e3535f5b.png)

**Comment by Epix37** [comment]
The numbers indicate the number of secrets in play that could be any given secret, nothing more.

There's two problems with the way you assume it's working: 
- Arena and created cards break the 2 card limit
- There can never be more than 1 of any given secret in play anyway

**Comment by culinko** [comment]
Yeah, that's why I mentioned only constructed modes. Not sure how hard it would be to check for which mode you're currently playing and adjust the secret table accordingly. And created cards should have the creator tag, or could be compared to the deck at the game creation. I'm pretty sure you already know which cards are created.

Anyway, counting the secrets internally and only displaying one for each shouldn't be a problem for you to do :)

**Comment by Epix37** [comment]
My main point still being though: that's not what the count means.

**Comment by culinko** [comment]
Ok I see the point.
