### ISSUE TITLE
Only a few Features Available

### ISSUE THREAD

**Issue by DarkenedWill** [Epix37/Hearthstone-Deck-Tracker#2342]
I downloaded the Deck tracker and I've tried working it a few times, deleted it, re extracted it and installed it again, tried reinstalling the .net frame and I can only see the in-game features. No off-game stuff like options, no stats, no deck import/export. I can only see the in-game stuff like cards drawn and cards played. Cant seem to do any setups or anything, like I said onloy in-game features.

**Comment by Epix37** [comment]
Try alt-tabbing to the window, then press Win+Left until you see it.

**Comment by DarkenedWill** [comment]
actually it acts like the window is there but completly invisible.

**Comment by Epix37** [comment]
Never heard of this before.

Maybe try reinstalling .NET Framework.

**Comment by DarkenedWill** [comment]
I already did, but Ill try again right now...

**Comment by Epix37** [comment]
Video card driver and/or Windows updates could also help.

**Comment by DarkenedWill** [comment]
well... seems the problem is with my windows, the theme makes all settings appear in black, I may have temprarly fix3ed the issue but it seems theres more work to be done but thanks at least now I can use the features. thank you very much!!

**Comment by Epix37** [comment]
Great :).
