### ISSUE TITLE
Mulligan never ends after reconnecting. 

### ISSUE THREAD

**Issue by Lollypop** [Epix37/Hearthstone-Deck-Tracker#2344]
After you reconnect during the mulligan turn, `Hearthstone_Deck_Tracker.API.Core.Game.IsMulliganDone` doesn't change to false when the mulligan ends, this can easily be reproduced by going into a pratice game, turning your game off during the mulligan and then reconnecting.

Thanks

**Comment by Epix37** [comment]
Fixed :+1:

`Game.IsMulliganDone` will still not update instantly, just due to the way player identification works after reconnect, but does now on the next opponent draw.
