### ISSUE TITLE
Could not auto-import Arena deck

### ISSUE THREAD

**Issue by likeyoucare** [Epix37/Hearthstone-Deck-Tracker#2345]
Yesterday my arena decks stopped auto-importing. I'm playing from two PCs and a deck which I drafted from one PC didn't import on another. I tried to debug a bit and found out next that it seems Blizzard changed something. In arena.log you now can see only unique cards from your arena decklist. So if your have a deck without dublicates, your deck will be successfully auto-imported. If you have at least two copies of any card, auto-importing will fail.
Everything works fine while you drafting a fresh deck though. Haven't found out why it works yet.
You could try to catch a bug repeating next steps:
0) turn on auto-import in settings
1) draft a deck with at least two copies of any card
2) quit Hearthstone
3) delete the deck
4) start Hearthstone
5) enter arena screen

If this succeeds you probably want to delete arena.log file or try log in to your account on another PC.

**Comment by Epix37** [comment]
Could you post the corresponding `Arena.log` and `hdt_log.txt` files? ([see here for the latter](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues))

**Comment by likeyoucare** [comment]
Here's relevant messages from both:

D 12:01:38.7346040 DraftManager.OnChoicesAndContents - Draft Deck ID: 784470657, Hero Card = HERO_08
D 12:01:38.7346040 DraftManager.OnChoicesAndContents - Draft deck contains card FP1_005
D 12:01:38.7346040 DraftManager.OnChoicesAndContents - Draft deck contains card EX1_399
D 12:01:38.7356040 DraftManager.OnChoicesAndContents - Draft deck contains card CS2_131
D 12:01:38.7356040 DraftManager.OnChoicesAndContents - Draft deck contains card AT_008
D 12:01:38.7356040 DraftManager.OnChoicesAndContents - Draft deck contains card CS2_024
D 12:01:38.7356040 DraftManager.OnChoicesAndContents - Draft deck contains card AT_100
D 12:01:38.7356040 DraftManager.OnChoicesAndContents - Draft deck contains card LOE_002
D 12:01:38.7356040 DraftManager.OnChoicesAndContents - Draft deck contains card EX1_082
D 12:01:38.7356040 DraftManager.OnChoicesAndContents - Draft deck contains card CS2_028
D 12:01:38.7356040 DraftManager.OnChoicesAndContents - Draft deck contains card CS2_032
D 12:01:38.7356040 DraftManager.OnChoicesAndContents - Draft deck contains card LOE_029
D 12:01:38.7356040 DraftManager.OnChoicesAndContents - Draft deck contains card LOE_047
D 12:01:38.7356040 DraftManager.OnChoicesAndContents - Draft deck contains card GVG_001
D 12:01:38.7356040 DraftManager.OnChoicesAndContents - Draft deck contains card NEW1_012
D 12:01:38.7356040 DraftManager.OnChoicesAndContents - Draft deck contains card CS2_029
D 12:01:38.7356040 DraftManager.OnChoicesAndContents - Draft deck contains card EX1_059
D 12:01:38.7356040 DraftManager.OnChoicesAndContents - Draft deck contains card GVG_096
D 12:01:38.7356040 DraftManager.OnChoicesAndContents - Draft deck contains card BRM_002
D 12:01:38.7356040 DraftManager.OnChoicesAndContents - Draft deck contains card AT_119
D 12:01:38.7356040 DraftManager.OnChoicesAndContents - Draft deck contains card CS2_117
D 12:01:38.7356040 DraftManager.OnChoicesAndContents - Draft deck contains card AT_007
D 12:01:38.7356040 DraftManager.OnChoicesAndContents - Draft deck contains card FP1_001
D 12:01:38.7366041 DraftManager.OnChoicesAndContents - Draft deck contains card AT_006
D 12:01:38.7366041 DraftManager.OnChoicesAndContents - Draft deck contains card CS2_172
D 12:01:38.7366041 DraftManager.OnChoicesAndContents - Draft deck contains card AT_110
D 12:01:38.7366041 DraftManager.OnChoicesAndContents - Draft deck contains card LOE_046
D 12:01:38.7366041 DraftManager.OnChoicesAndContents - Draft deck contains card CS2_033
D 12:01:38.7366041 DraftManager.OnChoicesAndContents - Draft deck contains card GVG_095
D 12:01:38.7366041 SetDraftMode - ACTIVE_DRAFT_DECK
 
==========
 
12:01:39|Info|GameV2.NewArenaDeck >> Created new arena deck: Mage
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: FP1_005 (1/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: EX1_399 (2/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: CS2_131 (3/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: AT_008 (4/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: CS2_024 (5/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: AT_100 (6/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: LOE_002 (7/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: EX1_082 (8/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: CS2_028 (9/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: CS2_032 (10/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: LOE_029 (11/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: LOE_047 (12/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: GVG_001 (13/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: NEW1_012 (14/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: CS2_029 (15/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: EX1_059 (16/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: GVG_096 (17/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: BRM_002 (18/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: AT_119 (19/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: CS2_117 (20/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: AT_007 (21/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: FP1_001 (22/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: AT_006 (23/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: CS2_172 (24/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: AT_110 (25/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: LOE_046 (26/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: CS2_033 (27/30)
12:01:39|Info|GameV2.NewArenaCard >> Added new card to arena deck: GVG_095 (28/30)
12:01:39|Info|GameV2.CurrentMode >> DRAFT

**Comment by likeyoucare** [comment]
P.S. In this case, I have 3 Snowchuggers in my deck.

**Comment by Epix37** [comment]
Neither list contains a single Snowchugger (GVG_002) - something doesn't make sense here. And if it was completely missing the list should show 27 cards, not 28.

**Comment by Epix37** [comment]
This only happens when you import a existing arena run and you still get those 28 cards when you import manually via `IMPORT > FROM ARENA` right?

I don't think this is worth trying to fix. There's probably not much I could do anyway if the data is missing from the log.

**Comment by likeyoucare** [comment]
Yeah I know there's nothing anyone can do in case of log provides incomplete information. I stuck with this issue cause haven't use manual import for a while. And adding extra copies manually isn't that big deal.
Thank you for your help and the great app!

**Comment by likeyoucare** [comment]
P.S. Yeah it was not 3x Snowchugger but 3x Frostbolts. My fault! :-)
