### ISSUE TITLE
Automatic sync how?

### ISSUE THREAD

**Issue by SeniorAdrian** [Epix37/Hearthstone-Deck-Tracker#2348]
How do a twitch the settings in order to start the app when i open the game? Do i have to click on the exe of the app everytime i want to use it? I already checked the box "Start Hearthstone with HDT tracker" but when i open the game the app dosent start, i have to click on the exe of the app in order to use it everytime.

**Comment by Epix37** [comment]
HDT can't automatically start with Hearthstone. The setting you enabled works the other way around: It will attempt to start Hearthstone when you start HDT.
