### ISSUE TITLE
Deck Tracker reset

### ISSUE THREAD

**Issue by Frosttfire** [Epix37/Hearthstone-Deck-Tracker#2349]
Having a card that isn't in the current deck, in this case, argent squire instead of rafaam, results in the tracker flashing all the cards and resetting constantly. https://a.pomf.cat/eenxiw.gif

**Comment by Epix37** [comment]
Does one of the decks HDT is switching between have more than one version?

**Comment by Frosttfire** [comment]
No, it was the only deck and it had one version.

**Comment by Epix37** [comment]
Could you upload the logs of that happening? See here: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by Frosttfire** [comment]
couldn't find a host without restrictions on size.
[hdt_log.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/222587/hdt_log.txt)
