### ISSUE TITLE
Card image does not appear

### ISSUE THREAD

**Issue by CrendKing** [Epix37/Hearthstone-Deck-Tracker#268]
Sometimes the card image in the deck list does not appear. See http://imgur.com/0H6gdqa . This can frequently be triggered by selecting a deck and scroll up and down by either using mouse wheel or scrollbar. The image will appear if mouse over on the missing image.

Tested on Windows 8.1, tracker version 0.5.1.

**Comment by Epix37** [comment]
Actually manged to fix this.. no idea why the changes make it work...

**Comment by CrendKing** [comment]
I can also confirm that as of 0.7.5 the problem seems to be gone.
