### ISSUE TITLE
fixing inaccurate stats manually

### ISSUE THREAD

**Issue by surasshu** [Epix37/Hearthstone-Deck-Tracker#292]
a game i won wasn't properly recorded somehow, and shows both result and mode as "none". would be fantastic to be able to edit these values manually when they're inaccurate!

**Comment by rdellaripa** [comment]
Just found this thread because I've gotten disconnected a few times today as games were ending, and they left the games as mode "None", which seems to cause problems with the sync to Hearthstats.

**Comment by GiggliG** [comment]
With today's update, you can find games marked as "None" by looking at the stats filter with options, "All", "With Deck", "Without Deck". 
Select Without Deck, and your games will hopefully show up. 
Then you can move them to the deck they should be assigned to.
I hope this helps with hearthstats sync.
