### ISSUE TITLE
Overlay flashes when game starts

### ISSUE THREAD

**Issue by askarmuk** [Epix37/Hearthstone-Deck-Tracker#310]
I started my first game after starting hs. HDT was loaded at the windows startup.

http://youtu.be/RZYuLGMxwpA

**Comment by Epix37** [comment]
Does this still happen with v0.7.x?

**Comment by Fyren** [comment]
I don't remember it happening in a while.

**Comment by FenrisWolffe** [comment]
I don’t think I’ve seen it in a bit... unsure pre- or post-update, though.
