### ISSUE TITLE
reword "what are all these percentages?"

### ISSUE THREAD

**Issue by techdough** [Epix37/Hearthstone-Deck-Tracker#333]
Its really hard to understand the [2] and [1] explanations for opponent. Consider rewording this or picking a different way of representing these percentages. hard to tell the difference between having and drawing.

explanation from this image is much easier to understand, https://camo.githubusercontent.com/5ad7ee58b205bc051c8c1cd7b32964d12137bc6b/687474703a2f2f692e696d6775722e636f6d2f45576436556e672e6a7067

**Comment by Cu8eR** [comment]
@Epix37 - what about to add this into readme file to the main page of this page on github?

**Comment by techdough** [comment]
yea that would be fine as well.

**Comment by Cu8eR** [comment]
@Epix37 - I think this can be closed... now we have really nice icons in GUI :)
