### ISSUE TITLE
Export collection

### ISSUE THREAD

**Issue by Glaived** [Epix37/Hearthstone-Deck-Tracker#337]
Would it be possible to have a feature to export our collection of cards? recovering more information, and to have returned to a csv or other file

**Comment by Mustack** [comment]
I'm thinking of doing this. I had started an autoit project to do it but I think it would be better to leverage this project. @Epix37 What do you think of this?

**Comment by andburn** [comment]
The [Collection Tracker plugin](https://github.com/ko-vasilev/Hearthstone-Collection-Tracker) already automatically gets you card collection. It probably makes most sense to add an export to feature to that project?

**Comment by Mustack** [comment]
Oh, I guess I didn't look hard enough for an existing solution. Thanks for pointing this out.
