### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dhoepelman** [Epix37/Hearthstone-Deck-Tracker#339]
I was wondering what license the source is under, as I only see a license for the UI icons.
The main license is usually in a `LICENSE` file on the repo root (github does this when creating a new REPO).

If you're unsure. [Here's a compact comparison](http://choosealicense.com/licenses/). I would advise one of the following:

 * GPL : You must release changes as GPL. You cannot include this code in closed-source projects.
 * BSD 3-clause: Do whatever you want, but don't use our name if you change it or hold us liable for anything
 * BSD 2-clause/MIT: Do whatever you want but don't hold us liable for anything

**Comment by ermau** [comment]
:+1: Need to add a license

**Comment by mnuzzolilo** [comment]
Any update?
