### ISSUE TITLE
Quality card

### ISSUE THREAD

**Issue by Glaived** [Epix37/Hearthstone-Deck-Tracker#364]
Possible to add the quality of the card (Legendary, epic ..) on tooltips, or on overlay ?

**Comment by Cu8eR** [comment]
@Epix37 - really good suggestion - or at least add a card preview into tooltip

**Comment by Epix37** [comment]
if you have a good idea how to display this without it looking horrible, please let me know ;)

**Comment by Cu8eR** [comment]
@Epix37 - put card thumbnail under the tooltip window (or above it when you will be on the bottom of the window). Something like this: 
1) idea 1
![idea1](https://cloud.githubusercontent.com/assets/778890/7003362/950b6d8a-dc59-11e4-953b-98bce3ab3163.png)
2) idea 2
![idea2](https://cloud.githubusercontent.com/assets/778890/7003365/9a3c11d8-dc59-11e4-8bf3-9946d34d0b6a.png)

About quality of the card - make a toogle above the list of cards to show a quality of cards - make a border around the card with color according to its quality
![border color](https://cloud.githubusercontent.com/assets/778890/7003380/bdc062bc-dc59-11e4-88bc-cb864e64c589.png)

P.S. I am sorry for my terrible images :) I can make them better if you wish

**Comment by Cu8eR** [comment]
![exp1-icon](https://cloud.githubusercontent.com/assets/778890/7003424/99e8e160-dc5a-11e4-8c34-e7ec452806b9.png)
![icon-naxx](https://cloud.githubusercontent.com/assets/778890/7003426/9b0a06aa-dc5a-11e4-9425-7978f20e68f2.png)
![exp2-icon](https://cloud.githubusercontent.com/assets/778890/7003427/9c54dbe8-dc5a-11e4-90fd-38790bc25ec5.png)
![exp2-icon](https://cloud.githubusercontent.com/assets/778890/7003430/9f8f05c2-dc5a-11e4-9f1c-728e0297850d.png)

**Comment by Epix37** [comment]
I have a really good idea for the quality, similar to your borders. I'll post that in a bit.

Full image tooltips:
* Adding 1000+ cards in 16 languages would make the .zip HUGE.
* Alternative: Download on demand
    * From where? I'd probably have to host them myself
    * Where do I get all of them in all of the languages? Will I get them reliably when new updates come out?
    * What's would traffic cost?

**Comment by Cu8eR** [comment]
@Epix37 - I would include only cards in english lang. Rest cards in different languages would be added as a downloadable pack. 

For English cards there is no problem to get them -> I would start with them and cards in rest langs would be added later as a plugin

**Comment by Epix37** [comment]
"worry about other languages later" is not really a good way to look at this I think.
And even with only english in the download, that's still increases the size 5-10 fold. The way to do this would be dynamically downloading them. 

Also they should not be attached to the current tooltip but replace it if desired. (on by default)

This could work: 
![screenshot 2015-04-06 13 16 38](https://cloud.githubusercontent.com/assets/7737910/7003688/3798c99e-dc5f-11e4-8c7e-dd673e14cc88.png)

**Comment by Cu8eR** [comment]
OK, maybe I have found a solution: http://hearthstonejson.com/

About card borders -> it looks nice, maybe it needs a little bit modify it -> especially the color of the border (I think it doesnt fit to the tradicionally blizz color for rarity)

**Comment by Epix37** [comment]
i don't understand the hearthstonejson link

**Comment by Cu8eR** [comment]
Code for colors from blizz:
0 Poor ff9d9d9d
1 Common ffffffff
2 Uncommon ff1eff00
3 Rare ff0070dd
4 Epic ffa335ee
5 Legendary ffff8000
6 Artifact ffe6cc80
7 Heirloom ffe6cc80


About the link - it contains all cards, you can download other languages easily, just one image card (background) and text is changeable according to the language.

**Comment by Epix37** [comment]
There are no card images on hearthstonjson. All of the text I do already have (obviously).

**Comment by Epix37** [comment]
using the colors codes from above:
![screenshot 2015-04-06 13 34 30](https://cloud.githubusercontent.com/assets/7737910/7003849/c484ad1c-dc61-11e4-8b9a-0d0e1635467c.png)

The colors are multiplied with the original border at 150 alpha, that's why they won't quite be the same, but just slapping the color on looks dumb. This is suble and get's the point across very nicely imo.

**Comment by Cu8eR** [comment]
I agree - now I am thinking about card thumbnails :) it seems to be complicated -> there is no problem to host the files (I dont know how many downloads you have for every version - so it depends on the monthly bandwidth).

I would start with English cards, rest would be downloadable separately (download and overwrite)

**Comment by Epix37** [comment]
Again, not really what I would want. If you offer a separate download anyway, you might aswell just download them dynamically. 

v0.9.10 has 20k downloads after 4 days now.

**Comment by Cu8eR** [comment]
OK, thats a really nice number! CG.

What about to download them on demand from hearthhead.com like this plugin for wordpress? It loads cards in language which you set in the plugin setting
http://coder.flowdee.de/hearthstone-cards-for-wordpress/

https://wordpress.org/plugins/hearthstone-cards/

**Comment by Epix37** [comment]
I don't know if the hearthhead people would be too happy about me just doing that :). *If* that's an option though, sure.

**Comment by Cu8eR** [comment]
I think there is no any other way how to do this for other languages. Everytime you will have prons and cons.

**Comment by Epix37** [comment]
Nono, this would be fine. I just saying hearthhead might not be ok with it.

**Comment by Cu8eR** [comment]
I think they will be OK - just add a note into changelog or into readme and they will be happy. :)

**Comment by Epix37** [comment]
OH you *think* :). I guess I'm gonna go find an email and ask lol.

**Comment by riQQ** [comment]
This can be closed, right?
