### ISSUE TITLE
Assign a deck for the opponent? 

### ISSUE THREAD

**Issue by lukasi273** [Epix37/Hearthstone-Deck-Tracker#376]
It would be really awesome if we could assign a deck for the opponent player. E.g.; 

A match starts, you are facing a Warlock, you get a popup dialog window, listing all the Warlock decks stored within the Tracker app. You are allowed to assign one of them (or pick 'none' if you wish to maintain the default functionality) as your opponents deck. You can change the opponent deck at any given time during the game (in the case that you picked Handlock but your opponent is Zoo, etc)

It could even automatically assign deck for an opponent, if you have a Zoo deck and Handlock deck in storage, opponent plays Flame Imp during the game, assign Zoo. 

The opponent window would then function in the exact same way as the player window does right now. Almost everyone on the ladder runs the same deck for each class, however in the case that the opponent plays a card that's not on the list you assigned for him, just have it appear as 'green' (e.g. as if it was summoned from a Webspinner). 

-----
Advanced (extra) functionality:

1. It could memorize specific deck alterations for each given opponent you face. Let's say you face a Warlock (Johnny123) playing Handlock. He plays Power Overwhelming and Leeroy Jenkins during the game. But your Handlock deck stored in the Tracker does not contain these cards, so they appear in 'green' (summoned). Next time you face Johnny123 playing Warlock, Tracker automatically assigns your Handlock deck, BUT with the inclusion of Power Overwhelming and Leeroy Jenkins, since it memorizes the opponent name. 32 cards instead of 30, since the app doesn't know what he replaced those cards with (yet). 

2. To add to the above, it could also memorize and store entire decks that each specific player plays. So, if an opponent is Legolas123 - Hunter and plays all 30 of his cards, next time you face Legolas123 - Hunter, restore the 30 cards he played in the previous game as his current decklist (you can of course change his deck during the game if you want/need to).

I think this would be a really epic addition to an already epic app. Obviously doesn't have to be 1:1 to what I just said, it's just the way I imagine. What do you think? It would still be within Blizzards policy, as they specifically mentioned 'a program that does what you can do with pen and paper is fine'.

**Comment by rolandschulz** [comment]
I think it would be very useful. At least right now one sees mostly the same decks just with a few tech cards replaced (at least for rank 8-4). And just showing the most common cards for a certain deck type is not more than one can achieve with a 2nd monitor or piece of paper showing list of decks. Thus it doesn't give an unfair advantage but is cheaper and more convenient and thus useful in HDT. For those few cards which are often replaced one could list each option with the percentage each is selected among the top decks selected from whatever source (HDT database or some website). Another advantage of being able to select the deck type in game would be that this information could be used for the statics/tagging. That way the static matrix which currently shows the overall stats (for each class vs each other class) could show each deck type vs each deck type. Thus one could see how often one wins/loses with/against zoo/handlock separately.
