### ISSUE TITLE
Multiple Instances of Tracker on the same system.

### ISSUE THREAD

**Issue by FenrisWolffe** [Epix37/Hearthstone-Deck-Tracker#391]
Epix,

I think I mentioned this to you once, but didn't go into detail. I use the tracker on my desktop, as well as my laptop. The only real thing of importance there is that when I change a deck, I export it from one, and import it to the other.

My wife also uses the tracker on our laptop. I have two instances set up in different folders... and each was pulling from it's own Playerdecks.xml - In short, everything was working fine.

Today I ran an update that I had apparently missed, and both deck lists were cleared and only showed decks from months ago.

Please, I'm sure this is a matter of only two lines of code, but I don't know the first thing about it. Can you PLEASE, instead of JUST the checkbox for storage in the data folder, allow a path to be entered for the decklist/config/deckstats/playerdeck files? Please? 

Sincerely,
A wolf who now has to spend hours re-editing and entering deck lists.

**Comment by Epix37** [comment]
was added with v0.8.0 (?)
