### ISSUE TITLE
Deck counter messing up with Burrowing Mine

### ISSUE THREAD

**Issue by Elitesparkle** [Epix37/Hearthstone-Deck-Tracker#432]
When Burrowing Mine is added to a deck, the card counter should increase by one since the deck gets a new card.

Not handling this when Iron Juggernaut is played will cause the deck counter to be inaccurrate since the deck will have N cards in it but the counter will be at N-1.

To track this event, if the Burrowing Mine doesn't get mentioned in the game log, you could look for an Iron Juggernaut being played from hand.

For reference:
http://www.hearthstonetopdecks.com/cards/burrowing-mine/

**Comment by culinko** [comment]
Is this still an issue?

**Comment by Epix37** [comment]
I think not. Needs confirmation.
