### ISSUE TITLE
hotkeys to quickly toggle the overlay?

### ISSUE THREAD

**Issue by megablue** [Epix37/Hearthstone-Deck-Tracker#444]
is it possible to implement hotkeys to quickly toggle the overlay? it will be great

**Comment by NightKev** [comment]
+1 on this, maybe you know of a good way to do it now?

**Comment by quark-zju** [comment]
This may help: https://github.com/thomaslevesque/NHotkey

**Comment by Epix37** [comment]
Looking into it a bit, that might not even be necessary. This seems to work pretty well: http://stackoverflow.com/questions/2450373/set-global-hotkeys-using-c-sharp

Not sure why I haven't found that before.

**Comment by Epix37** [comment]
What kind of hotkey functionality would you guys like to see?

Some ideas:

* Show/Hide overlay
* No deck mode on/off
* Export Deck
* Import from web/arena/constructed
* Show HDT
* Show stats
* Close HDT (Restart HDT?)
* Start Hearthstone?

**Comment by NightKev** [comment]
"Clear last game/reset decks" would be nice.

**Comment by andburn** [comment]
I was thinking this would be more useful for overlay stuff, rather than the actual app itself. I like these:

- Show/Hide overlay
- Show/Hide damage
- Show/Hide timers
- No deck mode on/off
- Show HDT
  - *probably don't need the import/export etc. with this, just do them normally?*
- Screenshot with overlay (*a new feature really* :smile:)

I wonder is there a nice way to implement this so things could be *Hot-Keyable* and allow a menu where keys could be assigned? Probably not worth the effort.

**Comment by quark-zju** [comment]
The RegisterHotKey is not hard to find. I thought that `elegant` means to avoid Win32 API directly :)

For operations inside HDT main window, I think the old-school menu item accelerators may be the more standard way. For example, `Alt+E` activates "**E**xport" and then `H` = "Export to **H**earthstone". Then we only need a global hotkey to bring HDT to front to use these key combinations.

Global (or, limited to "when HS is focused") hotkeys are something the user want to use in game. Toggling overlay elements is a use case. I personally want an "edit turn note" feature, press one key and then write down my mistakes on that turn.

**Comment by culinko** [comment]
Toggle show/hide: card marks, secrets panel. So far only these two came to mind.

**Comment by Epix37** [comment]
Here's what's currently implemented:
![screenshot 2015-10-20 20 16 23](https://cloud.githubusercontent.com/assets/7737910/10616859/8eda202e-7767-11e5-8c4f-b693929ca276.png)

Would attack, timers and secrets really be things you need to change often enough to require a hotkey? Secrets are hidden anyway if there is no secret active. I can somewhat see cardmarks.
