### ISSUE TITLE
Feature Request: gradient removal

### ISSUE THREAD

**Issue by jsogvndsi** [Epix37/Hearthstone-Deck-Tracker#473]
This is completely cosmetic but the list of decks having a gradient coloured background clashes jarringly with the smooth Windows 8 theme the rest of the application has.  A simple removal of the gradient and using a solid, soft colour for each would hugely improve the look of the application.

**Comment by Epix37** [comment]
See my post in [#979](https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/979#issuecomment-109247537) (work in progress).
