### ISSUE TITLE
[Suggestion] Extend Stolen marker on enemy hand

### ISSUE THREAD

**Issue by BVA64** [Epix37/Hearthstone-Deck-Tracker#476]
It would be nice if we could keep track of the additional information we have about "stolen" cards. We could have separate labels for the following or as a mouse over tool tip on the letter S with the list of all possible cards:
- spare part
- from unstable portal
- drawn by HTC
- Call Pet (could be a beast)
- Tracking (chosen by tracking so it is probably a good card)
- Webspinner (beast)
- Mind vision
- Thoughtsteal
- Far Sight
- Gnomish Experimenter (Chicken)
- Ysera Dream cards
- Neptulon

Returned card:
- Freezing trap (+2 cost)
- Duplicate
- Echo of Medivh
- Antonidas
- Shadowstep
- Sap
- Headcrack
- Vanish
- Kidnapper
- Sense Demons
- Lorewalker Cho
- Youthful+Aincient Brewmaster
- Gazlowe (Mech)

**Comment by BVA64** [comment]
The issue still persists with the new log reader.

**Comment by Epix37** [comment]
Returned seem to work from what I can tell. Stolen.. not so much.

**Comment by BVA64** [comment]
It is a bit hard for me to find the matching log sections. What about saving the raw log data into the replay file as well. Just a thought.

**Comment by Epix37** [comment]
I think I got stolen marks working for the most part now. If possible they show the actual card (works for fireballs created by archmage antonidas), otherwise the card that most likely created it.

**Comment by BVA64** [comment]
Works much better now.

Also found some issues when the Tinkertown Technicians combo is activated. No card is shown as a tooltip at all on the S marker. The card draw is also missing from the ReplayView.

https://www.mediafire.com/?9so4w7b9bqkfdlb
