### ISSUE TITLE
Wrong Hero displayed in Stats

### ISSUE THREAD

**Issue by Toxinho** [Epix37/Hearthstone-Deck-Tracker#479]
The Hero displayed for the 1st arena game is always the last hero played not the current one.

![bug hero](https://cloud.githubusercontent.com/assets/10262214/5519697/31bc3630-895f-11e4-9714-01d05b1a0680.jpg)

Here is the log :  http://pastebin.com/Bb5meAYF

**Comment by Epix37** [comment]
should be fixed with v0.7.0
