### ISSUE TITLE
'Auto deck selection' interactions with Spectator Mode

### ISSUE THREAD

**Issue by jsogvndsi** [Epix37/Hearthstone-Deck-Tracker#480]
1. If both options are enabled, `Hide in spectator` appears to be overridden and `Auto deck selection` takes over, choosing a deck of the same class as the person you are spectating is currently using.  This doesn't seem to happen 100% of the time unfortunately and only seems to occur if the tracker was started prior/during playing a normal game and **then** spectating a game.

2. While spectating someone and attempting to view/edit a different deck, the tracker client will force the selection of a deck of the same class as the person you are currently spectating.

**Comment by Epix37** [comment]
Spectator mode detection should work a lot better with the coming update.
