### ISSUE TITLE
Deck stats/title not updating sometimes

### ISSUE THREAD

**Issue by lukasi273** [Epix37/Hearthstone-Deck-Tracker#485]
Hello,

An issue recently came up (wasn't present before), when you change your selected deck to another one in the Hearthstone deck tracker, the title/stats of the deck in the 'Player' window do not change accordingly until you click on your Hearthstone game window. Weird! 

Also another smaller issue, sometimes when you change to a deck that contains much more cards than your currently selected one, the cards will go outside of the window, once you click on the 'Player' window the cards will then resize to a smaller height, would it be possible to make this size re-focus automatic? Cheers!

P.S. this is on the 'additional window' mode, probably no such issues on the normal mode =(

**Comment by Epix37** [comment]
with v0.7.0
