### ISSUE TITLE
Exporting with (some) golden cards

### ISSUE THREAD

**Issue by caldwelljt2** [Epix37/Hearthstone-Deck-Tracker#486]
I have tried exporting my cards to hearthstone but I'm running into issues with those cards that are golden. Specifically cards that are Golden when I have only one golden of two cards... I'm not entirely sure if this should be happening as I do have some golden cards making it into my decks.

What I do is, ever since my 3rd pack I decided to keep golden cards and whenever I get a duplicate I DE one of the non-golden cards. I have some double golden cards from packs (which works fine, since the others have been DEed, and/or in the case of legendary, the "normal" epic has been DEed). The basic golden cards seem to make it just fine, so I'm wondering if EACH card is clicked just to the right each time before clicking on the card itself, or if this only happens on "basic" cards.

Anywho, this isn't a huge but, but it seems to effect most of the decks I import and export (I have a lot of 1/2 golden pairs). I could fix this by DEing the basic or golden one and sticking with one or the other, but I'd hate to do that just to fix this.

**Comment by dvide** [comment]
@caldwelljt2 It works if you tick 'Prioritize golden cards' in Options -> Other -> Exporting to Hearthstone.

If that's not ticked it does have this problem when you have 1 golden and 1 non-golden.

**Comment by Fyren** [comment]
I also have this problem, though setting prioritize golden cards does make the exporting work.  If I set the speed to 150ms, then I can see it just clicks the normal card twice and doesn't try to click the golden card when I only have one normal and one golden card in my collection.

I personally only put golden cards in if I have no choice, so I end up manually fixing the deck and leaving the prioritize option off.

**Comment by riQQ** [comment]
Should be fixed by #1496
