### ISSUE TITLE
Cancel button on import from web gives error

### ISSUE THREAD

**Issue by caldwelljt2** [Epix37/Hearthstone-Deck-Tracker#487]
Very minor issue, but hitting Cancel instead of entering a valid URL to import a deck from the web generates and error: "Could not load deck from specified URL".

This doesn't affect the outcome as an import was left out, but it's just an odd message (and, should the program be ever step through some tasks after this screen, it's possible those steps could mess something up in a later version).

**Comment by Epix37** [comment]
fixed with v0.7.0
