### ISSUE TITLE
Unnecessary window after startup

### ISSUE THREAD

**Issue by askarmuk** [Epix37/Hearthstone-Deck-Tracker#492]
When HDT starts up with Windows an useless windows shown:

https://yadi.sk/i/-6uGH62idgsYf

I used a checkbox in HDT to start it at startup. I can restore this window and then minimize HDT and then HDT will correctly minimize to tray.

**Comment by 305jeff** [comment]
Same issue as OP here.

**Comment by Fazer2** [comment]
The issue is still not solved. It makes it irritating to either have always an open window at the system start or a titlebar near the taskbar that you need to restore manually and then properly minimize to tray.

**Comment by Epix37** [comment]
The next MahApps release will fix the issue that forced me to make the changes causing this. I will be able to easily fix this, then.

**Comment by Epix37** [comment]
Please let me know if there's still any issues with the latest build here: https://github.com/Epix37/HDT-Test/releases
