### ISSUE TITLE
Keep importing URL

### ISSUE THREAD

**Issue by waibcam** [Epix37/Hearthstone-Deck-Tracker#493]
Hi Epix,

what do you think about the idea of keeping the URL we use to import decks from website.

Then, 2 options could be added when selecting a deck:
1. View Deck (which will redirect the user to the website
2. Sync the deck, which will basically keep the deck up-to-date after pressing the button.

Check this mockup (I 'm not good but just to give you an idea):
![ss 2014-12-29 at 07 17](https://cloud.githubusercontent.com/assets/7987454/5571816/955ebc16-8f96-11e4-8872-b1650168e1ab.jpg)

What do you think ?

All the best for new year party man !

**Comment by stogle** [comment]
+1 for a view website button.

**Comment by GiggliG** [comment]
I think this would be great too.

**Comment by stogle** [comment]
Awesome, thanks.
