### ISSUE TITLE
Updated LogReader (now using tags) / new feature: replays

### ISSUE THREAD

**Issue by Epix37** [Epix37/Hearthstone-Deck-Tracker#494]
As suggested by @thesh0ck, I now updated the LogReader to mostly use `TAG_CHANGED` logs with 17782ca4.

The tracker is now aware of the state of all entites in the game (at least what's known to the client). 
This makes all kinds of statistics, replays and probably a lot more possible! Tell me if you have ideas!

The new log reader is most likely still flawed, I would appreciate any help on finding remaining issues: [NewLogReader branch](https://github.com/Epix37/Hearthstone-Deck-Tracker/tree/NewLogReader)

**Comment by Epix37** [comment]
Progess :)
![screenshot 2015-01-01 13 23 04](https://cloud.githubusercontent.com/assets/7737910/5592155/967cb5f6-91b9-11e4-9338-79c740d53908.png)

**Comment by JonnyMcFire** [comment]
Hello,

Sorry for rezzing this thread, but I would like to know if it is possible to add the information you gain from the log to the card tool tip?

Here are some possible use case scenarios to help explain my thought process.

Scenario 1: 
1. Opponent plays Earth Shock 
2. I mouse over Earth Shock on the overlay
 * Displays Elements (Detailed information on what the card targeted is displayed)
  * what turn it was played
  * how much damage it did
  * what the remaining life total of the minion targeted

Scenario 2: 
1. I play Defender of Argus
2. I mouse over Argus on the overlay
 * Displays Elements
  * Element: Minions that were buffed
   * Display result of buffing the minion([4/4 -> 5/5][+Taunt][Azure Drake])
   * 0 - 2 elements displayed
3. I later attack an unbuffed Knife Juggler with my unbuffed Argus
4. Mouse over Argus
 * Displays Elements
  * Element: Minions that were buffed (as above)
  * Element: Attack Event 1
   * Target
   * Turn Number
   * Damage dealt (Possibly zero or reduced)
    * Result of damage 
     * Knife Juggler died or has x remaining health
   * Damage received (Possibly zero or reduced)
    * Result of damage 
     * Argus died or has x remaining health

I can flesh out some more scenarios at another time.  I think to do this, you can expose some of the same functionality you used for the replay and just add to the cards list of actions as the game progresses.  This means separating duplicate cards, or having a split display if you highlight a card that has been used more than once.

Thanks for taking the time to evaluate this idea.

-Jonny
