### ISSUE TITLE
Other operating systems

### ISSUE THREAD

**Issue by PlasmaPower** [Epix37/Hearthstone-Deck-Tracker#495]
It would be nice if this supported other operating systems like OS X and Linux (Hearthstone runs fine on Linux through wine). I know other OS X issues have been closed with alternatives, but there are still no alternatives for OS X and Linux that offer similar features like displaying the cards your opponent has played.

**Comment by Epix37** [comment]
See here: http://www.reddit.com/r/hearthstone/comments/2ylebk/osx_teaser/

**Comment by PlasmaPower** [comment]
@Epix37 Thanks! Would that compile on Linux too? I wouldn't expect much effort put into Linux, but I would appreciate it if it would be easy to do.

**Comment by Epix37** [comment]
Maybe you can get it to work with mono / wine somehow, but I don't think so (at least this project). As for the OSX version I linked above, I don't know. Not mine :).

**Comment by PlasmaPower** [comment]
I see. The only thing stopping me from using this on Linux is the lack of WPF support for mono.
