### ISSUE TITLE
export screenshot is cropped

### ISSUE THREAD

**Issue by Dushku** [Epix37/Hearthstone-Deck-Tracker#496]
First post and I just wanted to say: I LOVE this tool! Thank you for all the hard work.

![trump qm](https://cloud.githubusercontent.com/assets/10361228/5591152/9917046e-911a-11e4-9dd5-b5fd9f4b69b1.png)

Export screenshot always only shows first 16 different cards and crops off the right side. I didn't find any other thread on the subject, so I assume it's my settings, but I can't figure out which. Any help would be appreciated.

**Comment by Dushku** [comment]
For what it's worth, I was able to hit Print Screen while it rapidly brought up a window in response to the export screenshot command. It lists all the cards, but it too drops off the right side.

![temp](https://cloud.githubusercontent.com/assets/10361228/5591414/3aff5ec2-9128-11e4-8408-92c5a57ed4be.jpg)

**Comment by Epix37** [comment]
Pretty sure this is related to your DPI settings. That *should* be accounted for but apparently that doesn't work.

**Comment by Dushku** [comment]
My desktop is set to 1920 x 1080.

**Comment by speedymatv** [comment]
Basically if you DPIscaling is more than 100% default windows, the screenshot crops. If you go to run.exe and type in "dpiscaling" you will be able to choose which percentage to use. Unfortunately I haven't find any solution to this. I use 125% scaling and everytime I want to make a screenshot I reduce it to 100% and log off/log in again

**Comment by Epix37** [comment]
The weird thing is that it *should* work (I think): 
Here's the [call](https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/MainWindow/MainWindow_Export.cs#L75) and the [screenshot method](https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/Utility/Helper.cs#L133).

If anyone has ideas...

**Comment by Dushku** [comment]
To whom it may concern:

When I originally posted this issue, my goal was to be able to put the screenshot in my stream/videos. However, since the program allows me to make my deck a separate window, I instead just have my broadcasting software include that window. This is actually better than my initial approach as it changes automatically as I change decks.

Thanks again for this remarkable tool!
