### ISSUE TITLE
Card Rounds not tracked properly in spectate mode

### ISSUE THREAD

**Issue by haagenson** [Epix37/Hearthstone-Deck-Tracker#500]
After the latest update, the numbers overlayed on opponent cards is not accurate while in spectate mode.  It often displays a K on cards just drawn.

**Comment by Epix37** [comment]
The tracker now relies on the turn numbers hearthstone logs, which turn out to be not so accurate in spectator if you join after the mulligan. Not sure what to about this yet.

**Comment by haagenson** [comment]
A good solution might be to use the "old" way of doing it for spectate mode only.

**Comment by Cu8eR** [comment]
yes I agree

**Comment by Epix37** [comment]
Not quite that simple sadly but I'll see what I can do.
