### ISSUE TITLE
Replay options

### ISSUE THREAD

**Issue by Calioe** [Epix37/Hearthstone-Deck-Tracker#502]
Thanks a lot for your nice soft..The new replay mode seems wonderful...
Would it possible to get it for not only the last match in this mode..? I have noticed only the last match is in this kind of replay mode?
A question can we register nickname of each opponent (not only the last one also?)

Thanks again for this!

**Comment by Epix37** [comment]
The replay mode does not work with old game files (pre v0.7.0). It's not possible. But every game from now on should have this kind of replay.
