### ISSUE TITLE
Hide layout after games

### ISSUE THREAD

**Issue by Mcherioux** [Epix37/Hearthstone-Deck-Tracker#503]
Hey ! I enjoy this project a lot, thanks for keeping updates on it ;)

Just wanted to point out that the "Hide in menu" option is no longer doing its job since the last update, I'm still seeing Decks from previous game when it ends ^^

Thanks, 
Spark

**Comment by Epix37** [comment]
There's seems to be an issue with game-end detection. I'm working on it right now.

**Comment by Epix37** [comment]
should be fixed now with v0.7.1

**Comment by Confirm4Crit** [comment]
I'm still having this issue, games do not properly end.
