### ISSUE TITLE
Issue with cards in hand

### ISSUE THREAD

**Issue by kyle81298** [Epix37/Hearthstone-Deck-Tracker#506]
I had a issue were i had 4 (this was on the initial draw in the start of the game)cards in my hand but it showed that I only had 1

**Comment by Epix37** [comment]
Do you have the tracker still running from that game?
If so 
1) go to  options > other > tracker, check "show log-tab" at the bottom
2) switch to the log- tab
3) "save to file", file will be located in [your HDT folder]/Logs

upload the file to e.g. www.pastebin.com

**Comment by ToonBoon** [comment]
Same thing for me, though the other way around. Seems like it doesn't properly close out the last game and keeps counting those cards to the current game.

http://i.imgur.com/1TB6dE0.jpg
http://pastebin.com/UJChHrVF

**Comment by Epix37** [comment]
This could be related to the game not resetting on start (#511). Thanks for the log!

**Comment by Epix37** [comment]
fixed with v0.7.2?
