### ISSUE TITLE
Crash after updated to v0.7.1

### ISSUE THREAD

**Issue by megablue** [Epix37/Hearthstone-Deck-Tracker#508]
The application failed to start with the following error.
=======
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Hearthstone Deck Tracker.exe
  Application Version:	0.1.0.0
  Application Timestamp:	54a97aa5
  Fault Module Name:	AppProfiles.dll
  Fault Module Version:	1.0.5.5
  Fault Module Timestamp:	5277f418
  Exception Code:	c0000005
  Exception Offset:	0002ee4c
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	17417
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by Epix37** [comment]
From what version did you update?

Google makes it sound like this is related to Radeon Pro.

**Comment by megablue** [comment]
ah... sorry i just installed Radeon Pro recently.
