### ISSUE TITLE
Percentages in stats and on decks don't match

### ISSUE THREAD

**Issue by Calioe** [Epix37/Hearthstone-Deck-Tracker#509]
Hello 
I have change for the new version as i had issue with recording on V 0.7.0
Now it seems working (last game is recorded) but it dosn't update the game % on the global menu I have put an exemple with Kolento Deck
![capture2](https://cloud.githubusercontent.com/assets/7279626/5606898/e4960754-9445-11e4-8412-3cc168533a2f.JPG)
![capture](https://cloud.githubusercontent.com/assets/7279626/5606899/e576582c-9445-11e4-997f-d580d42245a7.JPG)

**Comment by Epix37** [comment]
The stats in the stats window take the filters (mode, timeframe, etc) into account. The deck list currently does not. I would guess that's the issue here.

**Comment by Calioe** [comment]
Thanks ;)
