### ISSUE TITLE
overlay still here on menu

### ISSUE THREAD

**Issue by Calioe** [Epix37/Hearthstone-Deck-Tracker#510]
hello
overlay is stlill visible (and the timer continue also) on menu... in spite of the fact I have selected to hide it on menu in the option 
(It works on old version)

**Comment by Epix37** [comment]
This is with v0.7.1?
Does happen after all game modes?

**Comment by Calioe** [comment]
yes with 0.7.1 after ranked mode I don't have played other game mode

**Comment by Epix37** [comment]
see #511
