### ISSUE TITLE
0.7 (0.7.1 and 0.7.2) Strange note behavior.

### ISSUE THREAD

**Issue by hyperbolist** [Epix37/Hearthstone-Deck-Tracker#517]
If "Wait until back in menu" is selected with "Show note dialog after game", multiple note windows appear in succession.  The first note will not be saved.  The second note will be saved.  And a third note window appears when closing Hearthstone.

--edit-- In some cases, the hearthstone window is "hidden" after entering a note in the note popup window and can never be restored.  Tested with both gameendfixmaybe2 and gameendfixmaybe3.

If "Wait until back in menu" is not selected, none of this strange behavior occurs.

**Comment by Epix37** [comment]
should be fixed with v0.7.2
