### ISSUE TITLE
v 0.7.1 not finishing games

### ISSUE THREAD

**Issue by marcelomandaji** [Epix37/Hearthstone-Deck-Tracker#518]
After the last update hearthstone-deck-tracker is not finishing the game properly. It counts the result but the oponnent deck still shows in the screen and is not hiding in menus.

**Comment by Fyrestrom** [comment]
Mine is doing the same. It also does not reset the deck properly when starting a new game. I have to go back, deselect the deck and select it again to reset it.

**Comment by Epix37** [comment]
see #511
