### ISSUE TITLE
New issue with replay and also results accounting

### ISSUE THREAD

**Issue by Calioe** [Epix37/Hearthstone-Deck-Tracker#521]
It seems some results are not recorded in ranked mode on V 0.7.1 (I have copy the 0.7.2 you have posted in a msg before on this but it still writen as 0.7.1...?)
I have noticed that the file is correctly registered here:
C:\Users\Fifi\AppData\Roaming\HearthstoneDeckTracker\Replays
(with the last oponent) but when I ' m looking stat record or replay Select game i can't find it...(victory specially)..
(I have checked I have no filter on)

**Comment by Calioe** [comment]
please leave the old version by waiting a correct new one perhaps??

**Comment by anonymous555** [comment]
Same here, it looks like games after the 1st aren't recorded.

**Comment by askarmuk** [comment]
Just go to download section and download 0.6.7.

**Comment by Epix37** [comment]
The latest mediafire link in #511 should fix these issues. Once I (hopefully) get a few confirmations, I'll release an update.

**Comment by Epix37** [comment]
v0.7.3 should fix this.
