### ISSUE TITLE
wrong deck detected

### ISSUE THREAD

**Issue by Theliel** [Epix37/Hearthstone-Deck-Tracker#522]
Since 0.7.0+
-Constant "wrong deck detected". Same decks, same cards, same locale.
-Some overlay numbers/letters are missing 

returning back to 0.6.7 and all working fine again

**Comment by Epix37** [comment]
also related to #511 actually

**Comment by Epix37** [comment]
should be fixed with v0.7.2

**Comment by Epix37** [comment]
*should be fixed with v0.7.3
