### ISSUE TITLE
Deck overlay don't reset after game

### ISSUE THREAD

**Issue by FitzcairnHS** [Epix37/Hearthstone-Deck-Tracker#524]
Hi, i use this awesome deck tracker since months and it's the best HS tool for sure but i get an issue since the last update after a game the decks player and opponent dont reset even if the option "dont reset deck after game" is uncheck. So I have to close and restart deck tracker after each game.

**Comment by Epix37** [comment]
See #511. Please try the last download link in there and let me know if that fixes anything.

**Comment by FitzcairnHS** [comment]
I let an answer on the #511 511 topic
