### ISSUE TITLE
Tags managing not working

### ISSUE THREAD

**Issue by Jup200** [Epix37/Hearthstone-Deck-Tracker#525]
I can add new, select or unselect Tag, but other buttons dont work (DELETE SELECTED, UP, DOWN, TOP, BOTTOM)
![image](https://cloud.githubusercontent.com/assets/10400665/5613067/d81bf738-94de-11e4-9974-7cbbc0612cd3.png)
First time I use BOTTOM, one Tag overwite another tag.

**Comment by Epix37** [comment]
I just reproduced this no problem, tried something to fix it, didn't work. Changed it back, everything works. I don't understand...

**Comment by Jup200** [comment]
I finaly manage to delete tag. My problem was, I didnt selected tag properly. If there is only one tag, I cant delete it. But with UP, DOWN buttons strange thigs happens:
1.
![image](https://cloud.githubusercontent.com/assets/10400665/5668496/474bc884-9770-11e4-95db-c924e63fedc0.png)
2. add abc, xyz tags 
![image](https://cloud.githubusercontent.com/assets/10400665/5668579/fd47a888-9770-11e4-9068-cd7958986cba.png)
3. select xyz 
![image](https://cloud.githubusercontent.com/assets/10400665/5668596/15db3fd6-9771-11e4-8ae0-52e95a64a5a0.png)
4. click UP 
![image](https://cloud.githubusercontent.com/assets/10400665/5668615/3365d110-9771-11e4-963e-00020a42e1a8.png)
xyz overwrite abc
