### ISSUE TITLE
Arena Pulls in 0.7.2

### ISSUE THREAD

**Issue by FenrisWolffe** [Epix37/Hearthstone-Deck-Tracker#527]
Every card is duplicated. I show two of everything in the deck list after I import.
![seeing double](https://cloud.githubusercontent.com/assets/8535261/5613560/bf4a7be0-94ab-11e4-8e84-1c9f5d23502d.jpg)

**Comment by FenrisWolffe** [comment]
Nevermind. Closed both, restarted both, problem resolved.

**Comment by Epix37** [comment]
Should no longer happen with v0.7.2
