### ISSUE TITLE
APPCRASH please help

### ISSUE THREAD

**Issue by tiers2roses** [Epix37/Hearthstone-Deck-Tracker#528]
ive tried everything that i know, i cant seem to get this to work.

i love you long time if you help!

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Hearthstone Deck Tracker.exe
  Application Version:	0.1.0.0
  Application Timestamp:	54aa776d
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7600.16385
  Fault Module Timestamp:	4a5bdbdf
  Exception Code:	e0434352
  Exception Offset:	0000b727
  OS Version:	6.1.7600.2.0.0.768.3
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by Epix37** [comment]
#370 should help ypi

**Comment by tiers2roses** [comment]
that fixed it, thank you so much mate!
