### ISSUE TITLE
Lesser Heal shown twice in ReplayViewer

### ISSUE THREAD

**Issue by BVA64** [Epix37/Hearthstone-Deck-Tracker#529]
Great and incredibly fast work with the new statistics! 

A minor bug I found:
Lesser Heal is shown twice in ReplayView
> [Player] PlaySpell Lesser Heal -> Northshire Cleric
> [Player] Draw Shrinkmaster
> [Player] HeroPower Lesser Heal

**Comment by Epix37** [comment]
I'm not entirely sure what to remove here. 

Not all heropowers can be logged as PlaySpell, but removing that for heropowers feels kind of wrong too. Maybe I can somehow merge these.

**Comment by BVA64** [comment]
You can leave it like this I guess. It's not a major issue.

**Comment by BVA64** [comment]
A multi-level tree would solve the issue. I'm closing this one.
