### ISSUE TITLE
Result of recombobulation not shown in ReplayView

### ISSUE THREAD

**Issue by BVA64** [Epix37/Hearthstone-Deck-Tracker#530]
https://www.mediafire.com/?kz1zr376pmfkx3e

Turn 11 - Sludge Belcher stolen with Shadow Madness recombobulated into a Stormpike Commando. Stormpike Commando is not shown. It is destroyed later in turn 12 but it is never shown on screen.

**Comment by Epix37** [comment]
I think this is the same issue that causes the minion not destroyed in brawl to not show up. Thanks.

**Comment by BVA64** [comment]
A possibly similar issue with Faceless Manipulator on turn 16.
https://www.mediafire.com/?hibyaxe7y4n6b7i

**Comment by Epix37** [comment]
I think I got it sorted out. 

Tag changes are usually logged like
`TAG_CHANGE Entity=[name=Harvest Golem id=19 zone=PLAY zonePos=1 cardId=EX1_556 player=1] tag=ZONE_POSITION value=0`

However, after the recombulation (and I assume the same goes for brawl and faceless) the entity is only refered to by it's id: `TAG_CHANGE Entity=69 tag=ZONE value=PLAY`

Only for a few tag changes, too. After that it's back to the normal entity string. Weird stuff.

**Comment by BVA64** [comment]
Recombobulator now works fine. Thaddius is also shown as expected.
Some other messages have appeared as a side effect which are fine like:
> PlaySpell Power Word Shield
> **Summon Power Word Shield**
> Draw Auchanai Souldprist

This issue can be closed.

**Comment by Epix37** [comment]
Lets keep the issue open until the fixes are actually live. I'm not quite sure what I think about all the additional summons yet tbh.

**Comment by Epix37** [comment]
fixed with v0.7.4
