### ISSUE TITLE
Bug: Minion disappeared in replay mode while Mirror Entity triggered

### ISSUE THREAD

**Issue by hauntedjuan** [Epix37/Hearthstone-Deck-Tracker#537]
The opponent played Druid of the Claw in charge mode, my mirror entity triggered and his DotC disappeared. Three puu.shes shows it. Also note that i frostbolted the DotC and the replay says i frostbolted nothing. Also note that every damage the DotC did is replayed correctly.

Edit: The same happend to the second DotC. It disappeared after he played it.

http://puu.sh/e9Puv/12f806bf56.jpg opponent played DotC
http://puu.sh/e9Pvz/46d3fd7cdf.jpg got mirrored and the opponents DotC disappeared
http://puu.sh/e9Pyd/0810525f18.png frostbolted 'nothing'

**Comment by Epix37** [comment]
same as #535, see #530 - issue fixed for next update (I'm gonna leave this one open for visibility)
