### ISSUE TITLE
Importing error from hearthstoneplayers.com

### ISSUE THREAD

**Issue by NLZ** [Epix37/Hearthstone-Deck-Tracker#538]
I can't import some of the decks from hearthstoneplayers, for example this one:
http://hearthstoneplayers.com/beginner-deck-tech-basic-warlock/
It's trange beauce others work just fine.

**Comment by Epix37** [comment]
fixed earlier today by @mvy with #536

**Comment by Epix37** [comment]
fixed with v0.7.4
