### ISSUE TITLE
Different enemy secrets shown as identical in the Replay

### ISSUE THREAD

**Issue by BVA64** [Epix37/Hearthstone-Deck-Tracker#539]
A Paladin opponent played two secrets in turn 1 and turn 3.

The tree view on the left correctly shows them as Avenge and Noble Sacrifice but in the upper right corner both are shown as Avenge. In turn 8 one secret was triggered. The remaining secret changed to the correct one after that.

I had "Automatically gray out secrets" enabled in settings. Not sure if it was the cause of the issue or not.

https://www.mediafire.com/?xf2107dyzt1bzcz

**Comment by Epix37** [comment]
fixed with v0.7.4
