### ISSUE TITLE
Idea: Change in replay file format

### ISSUE THREAD

**Issue by BVA64** [Epix37/Hearthstone-Deck-Tracker#543]
How about adding the actual lines from the HS log file which belong to a game as a separate file in the zip container.

Benefits:
- bug reports can be easily reproduced
- old replays can be upgraded to have better/richer content after bug fixes or added features
- HS logs don't get accidentally lost and it is much easier to include the relevant portions in an issue
- JSON file could be completely replaced by parsing the HS log lines when loading replays, reducing code complexity

**Comment by BVA64** [comment]
I made some changes to save the log into the replay file. #552 
No changes were made to the way the JSON file is handled.

**Comment by Epix37** [comment]
Looks good, thanks
