### ISSUE TITLE
Multiple PCs / Multiple-switching

### ISSUE THREAD

**Issue by caldwelljt2** [Epix37/Hearthstone-Deck-Tracker#545]
Ok, I may be a bit nuts, but if I can find a solution that works for this, it would be peachy.

I run hearthstone on multiple different devices and sometimes more than one at a time. There isn't much consistency to it, other than I keep expecting my decks to be in and 50% of the time they either aren't or they are still in a modified state. I run three accounts each across three servers US/EU/Asia. All of them have different card sets available so pulling in existing card decks doesn't work unless i'm pulling ones that match card on-hand. I have naming standards to keep them all straight, but they simply are spread out between multiple computers and I end up having to scrape my deck back together or do a bunch of hackery (RDP/copy/paste/etc)

Is there a way to either share one set of configs amoungs a number of computers? (I do have the ability to network/share them and can keep files synchronized, but I haven't delved into trying it yet). I'm open to using either some kind of web-storage for decks or files, networking, or pretty much anything that I can ultimately automate or slim to very few mind-numb steps (i.e. I don't want to have to think about where I'm getting the deck from or putting it to, I'd just like to hit something or perform a few steps and then know that whatever decks I added whenever/wherever are pulled in and are available for usage).

Hope that makes sense. I don't know if this is an "issue" for Hearthstone-deck-tracker, as the issue is how I play, but I think this is the only place I can post seeking a solution for it.

Cheers and FANTASTIC job on this project (when I have a deck loaded, it's an invaluable tool).

**Comment by jabocop** [comment]
A even better way to accomplish this is to use symbolic link this is how I configured my Deck-Tracker:
1. Move the HearthstoneDeckTracker folder (with all the files) located in %APPDATA%\HearthstoneDeckTracker to your Dropbox folder. Make sure that the original folder does not exist.
2. Create a symbolic link that connects %APPDATA%\HearthstoneDeckTracker with the dropbox folder use the command : 
mklink /j %APPDATA%\HearthstoneDeckTracker d:\dropbox\HearthstoneDeckTracker
3. Do the same way on all computers you wish to use.
4. Enjoy your synced Hearthstone Deck Tracker

**Comment by FenrisWolffe** [comment]
@jabocop Jabocop, thank you for the great information. One question that is probably over-simple... In your command (Entered in Cmd, I suppose?) is j the letter of your internal hard drive, and d the letter of the drive you've created/assosciated with Dropbox?

Cheers!

**Comment by jabocop** [comment]
/j is the switch to create a directory junction (this should be j no matter which drive that is used) and d: is the drive letter of the disk I used. 
%APPDATA% is the shortcut for the user data directory, could be replaced with c:\Users\[Username]\Appdata\Roaming

**Comment by Ruudt** [comment]
Perhaps choosing the data location could become a setting in the tracker. It would make syncing between pc easier. I originally was looking for the data location for backup, but syncing it is just that much better!

**Comment by Epix37** [comment]
Choosing the data location is already in for next update (#571)

**Comment by Epix37** [comment]
#629 !

**Comment by FenrisWolffe** [comment]
Perhaps this is too complex, with the links, but on a WIndows machine, I still cannot get this to work seamlessly. 

Perhaps a step by step guide, if anyone has time?

**Comment by FenrisWolffe** [comment]
Point of note, I followed these instructions as best I could, step by step, and now my deck tracker will not open at all.

![command](https://cloud.githubusercontent.com/assets/8535261/6766767/d39030b0-cfe1-11e4-85a4-f272c387b6fe.png)

**Comment by 5th-Amendment** [comment]
@FenrisWolffe May I ask you where you got that wallpaper on the right?

**Comment by FenrisWolffe** [comment]
@5th-Amendment *big grin* I was watching The Hunger Games: Catching fire.

However, http://www.reddit.com/r/wallpaper/ is a great source.

**Comment by FenrisWolffe** [comment]
Please re-open this issue. It is still not working, or possible, except maybe for Jabocop....?

**Comment by Epix37** [comment]
This issue is as open as it can be.

**Comment by jabocop** [comment]
Yes it does work for me. I am really sorry if I caused any problems but I described the way I accomplish it the best way I could. If you look in your %APPDATA% folder, after you followed my instructions. How does it look? A link with the name HearthstoneDeckTracker should exist (a link looks like a folder with an arrow on it). If you open this link it should contain the same files as your dropbox folder.

**Comment by FenrisWolffe** [comment]
1. Opened HDT, switched both options to Appdata.
2. Closed HDT.
3. Moved all from Appdata to Dropbox folder
4. Created Sym. link to dropbox folder. (Works, points, etc.)
5. Moved all old games, etc, game.exe to dropbox folder.
6. Created new shortcut.

At this point, crashes immediately every time I double click the icon.

7. Download fresh copy, unzip contents of "Hearthstone Deck Tracker" into "HearthstoneDeckTracker" folder (Why are these two folders different inside of the program?
8. Double click icon, empty copy opens.

Now if I could just get all my decks and my games in there, I'm sure this would keep the correct win-loss stats and such.   

Help?

**Comment by FenrisWolffe** [comment]
Correction, it does not actually open, even the fresh clean copy, so long as it is in that directory. It HAS to be something with the difference in spelling/spacing.

########## 4/3/2015 7:25:00 PM ##########
System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'Hearthstone_Deck_Tracker.MainWindow' that matches the specified binding constraints threw an exception. ---> System.IO.FileNotFoundException: Could not find file 'C:\Dropbox\HearthstoneDeckTracker\config.xml'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Hearthstone_Deck_Tracker.Config.Load()
   at Hearthstone_Deck_Tracker.MainWindow..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

########## 4/3/2015 7:25:02 PM ##########
System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'Hearthstone_Deck_Tracker.MainWindow' that matches the specified binding constraints threw an exception. ---> System.IO.FileNotFoundException: Could not find file 'C:\Dropbox\HearthstoneDeckTracker\PlayerDecks.xml'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Hearthstone_Deck_Tracker.MainWindow.SetupDeckListFile()
   at Hearthstone_Deck_Tracker.MainWindow..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
![directory](https://cloud.githubusercontent.com/assets/8535261/6990685/a58dafca-da37-11e4-9e03-a02d795a99ee.jpg)

**Comment by FenrisWolffe** [comment]
(Could this be a sharing issue? When I follow the link created, I see this:
![locks](https://cloud.githubusercontent.com/assets/8535261/6990740/14e6cbf8-da39-11e4-930c-4d7058401e45.jpg)


Let me know if you can. For now, I'll restore what I had and deal with the fact the computers don't match. :(

**Comment by FenrisWolffe** [comment]
Sorry for all the spam, one final thought. With 6-8 backup files of each, I have tried restoring only the key files, and now the whole directory backed up from a zip. I cannot get anything to come back. :(

**Comment by Epix37** [comment]
It looks like the config and playerdecks files are set to readonly. As to how or why, I don't know.

But since this doesn't seem to work too well, have to tried moving the whole folder to dropbox? I've heard people had success with that.

**Comment by FenrisWolffe** [comment]
When you say fixed it, you mean with the directory in dropbox, now both computers should show the same stats? *super excited*

**Comment by Epix37** [comment]
Where did I say "fixed it"? Wrong issue?

**Comment by FenrisWolffe** [comment]
I’m sorry, I mixed the emails up... (
Re: [Hearthstone-Deck-Tracker] sync between 2 computers doesn't work, the cards are not updated on the second computer (#742)) is the one that you said you found and fixed it.

**Comment by Epix37** [comment]
Ah, yes.
See #629 for a list of what's fixed and what's yet to do.

**Comment by FenrisWolffe** [comment]
Hey folks. Been a couple weeks or more. Thought I'd check in to see if anyone had read my posts and had a suggestion or had many any progress on the dual system front.

**Comment by Epix37** [comment]
Hearthstats syncing looks very solid with the v0.10 prereleases so far.

**Comment by FenrisWolffe** [comment]
So basically, 
1. Play on Computer A.
2. Sync Computer A.
3. Sync Computer B.
4. Play on Computer B.
5. Sync Computer B.
Repeat?

**Comment by Epix37** [comment]
Or you just turn on "auto sync" and "sync on start" on both :).

**Comment by FenrisWolffe** [comment]
I promise you if that worked fully for decks & stats, I wouldn’t keep bumping this thread.

**Comment by Epix37** [comment]
What exactly are the issues remaining for you with the latest v0.10 prerelease for you?

**Comment by FenrisWolffe** [comment]
I have 0.9.10, Is that the latest?
I have a desktop and a laptop. I use HDT on both. I also set up my wifes HDT on the laptop. (Her config/info in roaming, mine in the dropbox folder.
Decks don’t always update. Even if they do, the win/losses *never* transfer/tally up. Dropbox makes conflicted files at times, but that’s it.

Also, on the desktop, if I have HS & HSDT running on monitor 1, and a movie playing (normally full-screen or maximized) on monitor 2, HSDT will not export.

Thanks, I appreciate you,
James

**Comment by Epix37** [comment]
0.9.10 is the latest actual release, but not the version I am talking about :). You can download the latest pre-release here:https://github.com/Epix37/HDT-Test/releases

**Comment by FenrisWolffe** [comment]
I *just* saw that earlier. Do I have to delete everything to install, or unzip and overwrite?

**Comment by Epix37** [comment]
If you don't have your data in AppData you have to overwrite, otherwise you can just drop it anywhere.

**Comment by FenrisWolffe** [comment]
I installed the pre-release, testing today. Are the sync options removed or hidden?

**Comment by Epix37** [comment]
Not that I can recall. One thing that is not working yet in that version is the syncing of tags (down) but that's fixed by now.
