### ISSUE TITLE
Single Deck in Wrong Deck Detected

### ISSUE THREAD

**Issue by ToonBoon** [Epix37/Hearthstone-Deck-Tracker#546]
What is the use of the dialog if there is only a single deck detected?

I have it set to auto switch, it switched from my hunter list to A mage list, then prompted me for the actual mage list I am running.

**Comment by Epix37** [comment]
So... apparently the option wasn't even used. Not sure where that got lost but it works again now.

**Comment by ToonBoon** [comment]
Splendid!

**Comment by Epix37** [comment]
fixed with v0.7.4
