### ISSUE TITLE
Secrets tooltip still shows after stealing a secret

### ISSUE THREAD

**Issue by RoboticEarthling** [Epix37/Hearthstone-Deck-Tracker#547]
A Mage opponent played Mirror Entity in Arena. The secrets tooltip showed up. The next turn, I (a Paladin) stole the secret using Kezan Mystic. The secrets tooltip didn't disappear even though the opponent no longer had any secrets.

I can't remember if the tooltip stayed there the whole game, but I think it did.

**Comment by Epix37** [comment]
Fixed for the next update with f14ab9f

**Comment by Epix37** [comment]
fixed with v0.7.4
