### ISSUE TITLE
Enhance auto gray out to detect attacks, plays, etc.

### ISSUE THREAD

**Issue by ToonBoon** [Epix37/Hearthstone-Deck-Tracker#548]
Is it supposed to gray out a mirror entity after you play a minion? Because that's not what it does right now. If that's not what it's supposed to do then what does it do exactly?

**Comment by Cu8eR** [comment]
good suggestion... same for counterspell secret when you play a spell card and nothing happens... or for vaporize

**Comment by mvy** [comment]
What are the trigger conditions for all secrets?

- Hero is attacked by minion
- Spell is cast
- Minion is played
- Minion dies

By the way, I was wondering if there is a format for the log somewhere? Or do you collect some of your recent matches to deduce it?

**Comment by BVA64** [comment]
**Hero is attacked (by hero or minion):** Explosive Trap, Misdirection, Ice Barrier, 
**Hero is attacked (by minion only):** Vaporize
**Hero takes damage:** Eye for an Eye,
**Hero takes fatal damage:** Ice Block,

**Spell is cast:** Counterspell,
**Spell is cast on minion:** Spellbender 

**Minion dies:** Duplicate, Avenge, Redemption
**Minion is attacked:** Snake Trap,

**Minion is played:** Snipe, Mirror Entity, Repentance
**Minion attacks:** Freezing Trap, 
**Minion or Hero attacks:** Noble Sacrifice

**Comment by Epix37** [comment]
@mvy There's no documentation of the log available. I would guess you can find it in the code but so far I (and I guess others, too) just deduced it from collected logs.

**Comment by mvordeme** [comment]
It is working really great. Thanks to whoever implemented it. :+1:

**Comment by riQQ** [comment]
I think this can be closed.
