### ISSUE TITLE
Games after the first not being recorded

### ISSUE THREAD

**Issue by GiggliG** [Epix37/Hearthstone-Deck-Tracker#550]
Since Sunday, I've noticed that only the first game after starting up HDT is being recorded in the game and deck history.
I have had at least one update since then (I'm on 0.7.3), and the error is still present.

I remember this issue occurred many months ago, but I have no idea what you did to fix it.

**Comment by Epix37** [comment]
Hey,
Could you upload a log of that happening?

**Comment by GiggliG** [comment]
How do I do that again? I looked in the logs folder, but there aren't any recent logs there.

**Comment by Epix37** [comment]
Options > other > tracker > show log tab, 
Options > log > save to file

**Comment by GiggliG** [comment]
I've sent you the log file, and the deckstats.xml file it mentions.
The error is very consistent, HDT always records the first game but none after that.

**Comment by GiggliG** [comment]
Epix identified the problem here. For reference in case anyone else suffers this:
A while ago, I reported a bug, and Epix asked me to change a value in the config file (ClearLogFileAfterGame from true to false).
When this is set back to True, the error goes away and games are recorded again.

**Comment by Epix37** [comment]
Should no longer happen with v0.7.4
