### ISSUE TITLE
Lord Jaraxxus in replay

### ISSUE THREAD

**Issue by BVA64** [Epix37/Hearthstone-Deck-Tracker#551]
Lord Jaraxxus has some glitches in a replay:
- Portrait of hero is not replaced
- Health of hero is not updated (stays the same after LJ was summoned)

http://www.mediafire.com/download/ai7hc25f82cjsd4/BVA64(Priest)_vs_Der(Warlock)_0848-080115.hdtreplay
Turn 25

**Comment by Epix37** [comment]
works now.

**Comment by Epix37** [comment]
fixed with v0.7.4
