### ISSUE TITLE
Improvement of deck cards count display

### ISSUE THREAD

**Issue by mvy** [Epix37/Hearthstone-Deck-Tracker#553]
Hey, 

I wanted to suggest a slight modification in the way that the cards count is displayed in the tracker. I almost went to do a modification to add a label by myself, then I struggled with multiple concepts that are unfamiliar to me within visual studio.

Then I realised that the cards count is displayed in the title bar. It struck me that for like couple of week I've been using HSDT building countless decks, it never happens to me to notice that count were even there. 

When I thought, 'ho man, how many cards do I have here?' I expected to see it on the bottom of the card list, like you can see that in game. So, why wouldn't HSDT display it the same way instead/in addition of the title bar? Shouldn't be so much of a trouble if we just put a small label with `xx/30` at the bottom of the cards list? (If brave enough, a localised string 'Card count' could also be added)

What do you think of this ?

**Comment by Elitesparkle** [comment]
I agree. It's difficult to notice the cards quantity up there.

It should be somewhere near the mana curve graph.

**Comment by Epix37** [comment]
I would put it below the "Deckname" and "Search..." textboxes, but this is probably, yes.

**Comment by Elitesparkle** [comment]
That's a good place too but, since you can save uncomplete decks, I think it's a little better to have it near the mana curve graph.
