### ISSUE TITLE
Ability to Import Opponent Deck Missing

### ISSUE THREAD

**Issue by Fyrestrom** [Epix37/Hearthstone-Deck-Tracker#554]
There used to be a way to Import your opponent's (partial) deck from a tracked game as a new deck. This button was located in the details of the match. Since Replay was added the Show Details button was replaced with the Show Replay button, but I cannot seem to find a way to import the deck from the replay. Am I missing something?

**Comment by Bahzur** [comment]
Yes. Just look at the mainwindow under "Import". :)

**Comment by Epix37** [comment]
That imports the cards played by the player. Opponent import is indeed currently missing.  I will be adding that to  the stats dialog with the next update.

**Comment by Bahzur** [comment]
Oh, sry, thought that was actually ment for the opponents cards, never used that button.

**Comment by Epix37** [comment]
re-added with v0.7.4
