### ISSUE TITLE
Turntimer vanished

### ISSUE THREAD

**Issue by Bahzur** [Epix37/Hearthstone-Deck-Tracker#555]
Squish one bug, another three pop up!
After some matches, it seems the timer couldnt be bothered anymore and just didnt show up to do his duty:
![noturntimer](https://cloud.githubusercontent.com/assets/4956200/5677377/d53d177c-97e5-11e4-9685-ad555ad9d185.png)
Log included: http://pastebin.com/jN6ziUku
Dont really know how that happened. :(

**Comment by Epix37** [comment]
Do you see it when you unlock the overlay?

**Comment by Bahzur** [comment]
Reporting back in; the timer vanished after some matches today, and unlocking the hud did indeed bring it back, with the right values. After that i locked the hud again and it stayed (for now ^^).
