### ISSUE TITLE
Wrong deck detected: give option to select "no deck"

### ISSUE THREAD

**Issue by surasshu** [Epix37/Hearthstone-Deck-Tracker#556]
Sometimes i'm just messing with a new deck and don't import it into deck tracker yet. In these cases, the deck detection rightfully says "wrong deck detected", but offers a bunch of decks, and I just have to disable the deck detection thing. Would be nice if I could select "no deck" from that window too!

**Comment by Elitesparkle** [comment]
Good idea.

**Comment by Epix37** [comment]
I agree. Done.

**Comment by Epix37** [comment]
added with v0.7.4
