### ISSUE TITLE
Game not recorded

### ISSUE THREAD

**Issue by Fyren** [Epix37/Hearthstone-Deck-Tracker#558]
I was playing in arena and finished my run.  I looked over at HDT and I see that the last game I played (and lost to end my run, which might be a coincidence) wasn't recorded.  It seems maybe different than issue #550 since it recorded more than my first game.

Here's my log: https://gist.github.com/Fyren/b23eff806c1e059281e4

Of note, in the last game moves are labeled as turn 0 and at the end, it says the game will be discarded due to there being zero turns.

In that log, I think I played two arena runs, going like 1 or 2-3 and then 8-3, if it's relevant.

**Comment by Fyren** [comment]
Actually, looking at the replay list, I don't see any of the games from the first run.  My replay list has games from before today, then ten games out of the eleven from the second arena run.

**Comment by Epix37** [comment]
See #549 for the zero turn issue. Not sure about why there would be no replay files though. I think they're not being deleted at all currently.

**Comment by Fyren** [comment]
In the gist, at line 11091 is when I started the first arena run and I think lines 12154 is a log line saying I lost the last game of that run.  The timestamps are from about 7:30 to 8 PM my local time.  I attached a screenshot of my replay list.  You can see the games from my second run (besides the last one) are there, but before that the previous game is from days ago.
![replays](https://cloud.githubusercontent.com/assets/3320115/5690836/7e43e10c-9863-11e4-96dc-d7eb44f31675.png)

**Comment by Epix37** [comment]
Oh, I was talking about the actual replay files not getting deleted (.hdtreplay). Stats do get deleted if you delete the deck (depending on options), so that would explain this.

**Comment by Fyren** [comment]
What's the list populated from if it's not the replays directory in appdata?

**Comment by Epix37** [comment]
Replays were a very recent addition. Stats are saved in the DeckStats.xml

**Comment by Epix37** [comment]
The "zero turns"-issue should be fixed with v0.7.4

**Comment by Elitesparkle** [comment]
I've played 5-6 games in the last 1-2 hours but I see only one record in the Stats.

After playing the first game, I went there and there was a game. Now there is a different one, but still only one.

Here is the log:
http://pastebin.com/6XPt0k9i

**Comment by Epix37** [comment]
While this should no longer happen with v0.7.4, see if it's the same issue as in #550. (To get to the config: options > other > tracker > open appdata folder)

**Comment by Elitesparkle** [comment]
Ok.

I've changed the ClearLogFileAfterGame string from false to true during a game (Ranked) and it didn't get recorded but the next one (Arena) did.

**Comment by Epix37** [comment]
Sorry, I should've mentioned this: you have to close the tracker before editing the config. (you have to do it again)

**Comment by Elitesparkle** [comment]
I should have figured that out.

Too late. I'm on version 0.7.4 now.

Anyways, check my first post on this issue again.
I edited it because it wasn't describing the situation in the right way.

Maybe this problem is related to class/deck switching, if even possible.

**Comment by Epix37** [comment]
The description matched exactly that problem. Even with v0.7.4 you should still change that config setting.

**Comment by Elitesparkle** [comment]
Yes, I did it already.
Thank you.
