### ISSUE TITLE
Adding new marks for opponent cards

### ISSUE THREAD

**Issue by eXpressionist** [Epix37/Hearthstone-Deck-Tracker#560]
Hello. First, thanks for the great tool. And sorry for my English.
Personally, I would like to see a new option: add advanced marks for "special" obtained cards (which now just tagged as S), like "St" - stolen, "Sp" - spare part, "D" - duplicate, "R" - returned, probably there is anything else I forgot (like spawned cards from Gazlowe or Neptulon).
It could be confusing at first, but if add this info to Help section, I believe most users of this program occasionally find this helpful.

**Comment by BVA64** [comment]
There is a tooltip if you move your mouse over the "S" letter that shows the source of the stolen card. 
If the tooltip is not shown make sure you have the latest version (this is a fairly recent feature) and that it is turned on under Options -> General -> Overlay -> Card-mark tooltips.

**Comment by Epix37** [comment]
Mark tooltips should be turned on by default. I think even more different marks wouldn't do any good.
