### ISSUE TITLE
Can't open the app

### ISSUE THREAD

**Issue by sefer66** [Epix37/Hearthstone-Deck-Tracker#563]
When i download the file, and try to run "Hearthstone Deck Tracker.exe", it just doesn't do nothing. It seems to be loading something but then nothing happens. Don't rly know what the problem can be, hope you can help me! :)

**Comment by Epix37** [comment]
Do you have .NET Framework 4.5 installed?

**Comment by basharxblast** [comment]
i have the same problem, and yes i have .NET Framework 4.5
