### ISSUE TITLE
Update overlay problem

### ISSUE THREAD

**Issue by Fyren** [Epix37/Hearthstone-Deck-Tracker#565]
I was running 0.7.3 and you released 0.7.4.  I clicked on HDT in my system tray and then got a window that looked like this:

![overlay](https://cloud.githubusercontent.com/assets/3320115/5693086/1509cacc-98cb-11e4-8396-7dd5996245ae.png)

I think this is the update overlay, just without most of the overlay?  I was unable to interact with the window, but was able to right click the tray icon and pick exit.  After starting HDT again, the overlay worked fine and I updated.

**Comment by Epix37** [comment]
This is probably the same issue as #499? 

I just tried to reproduce this and failed. Possibly

**Comment by Fyren** [comment]
Could be the same.  I didn't try playing any games while HDT was in that state.  Since the right click menu for the tray icon was working, it wasn't really frozen.  Windows never gave me the "not responding" dialog.

I'm using Win7 64-bit.

**Comment by Epix37** [comment]
I have a feeling this is related to windows 7. I'll investigate, thanks.

**Comment by Fyren** [comment]
It didn't happen again with the 0.7.5 update, so it might not reliably happen.

**Comment by Epix37** [comment]
The window should now activate automatically before showing the update message. While that's a bit more "intrusive", I think it should solve this.

**Comment by Fyren** [comment]
This just happened again with the 0.8.0 update, same as in the original report.

**Comment by Epix37** [comment]
The next update might finally fix this. (it will probably still happen when updating the next time)
