### ISSUE TITLE
Some info on the FPS issue

### ISSUE THREAD

**Issue by lukasi273** [Epix37/Hearthstone-Deck-Tracker#566]
Hi

Not sure if this is any helpful, but when I upgraded from Win 7 to Win 8.1 on my PC, the FPS issue (normal mode tracker) was completely gone, my FPS did not even move one bit down. 

Then I went back to Win 7, same .NET framework version, same drivers, FPS issue back once again. How come it's only on Win7? Maybe this will lead you to something.. :)

**Comment by Epix37** [comment]
Random guess: what happens if you turn off aero on win7?

**Comment by lukasi273** [comment]
Indeed it was Aero related. W7 Aero on - FPS does not get affected at all my hearthstone tracker. 
W7 aero off - FPS drops to 30-50 during game.
