### ISSUE TITLE
Improvement request: Servers recognition

### ISSUE THREAD

**Issue by Calioe** [Epix37/Hearthstone-Deck-Tracker#567]
Hello
probably already requested , but it would be great to have the possibility to register the Server (NA,EU,ASIA) in the statistics and in the replay results (I think it was possible with the last tracker I used HearthstoneTracker)

Thanks a lot!

**Comment by Epix37** [comment]
You can achieve this via tags: 

1) EDIT > TAGS: add US, EU, ASIA
2) Add tags to decks
3) DECKS > QUICKFILTER > (select e.g.) US
4) STATS > Overall > "Apply tag filters"

**Comment by Cu8eR** [comment]
It would be nice to add a tag automatically

**Comment by Epix37** [comment]
What's the best way to detect the server?

**Comment by Calioe** [comment]
I don't know but you have it automatically on the hearthstonetracker : I put you the link towards project I think in opensource : https://github.com/HearthstoneTracker/HearthstoneTracker
