### ISSUE TITLE
Symbol "!" in deck name broke export to HS

### ISSUE THREAD

**Issue by Anatoly-v0I** [Epix37/Hearthstone-Deck-Tracker#570]
This is a screenshot http://i.imgur.com/VVzeJy9.png
Exprorts nothing. And if i delete "!" from deck name in Decktrecker, export do nothing anyway. It's need relaunch HDT to fix (not HS).

And big thanx for great app!

**Comment by Anatoly-v0I** [comment]
A can do some video, if it is needed.

**Comment by riQQ** [comment]
I can't reproduce this. Does it depend on the Hearthstone language?

**Comment by culinko** [comment]
Is this still an issue?
