### ISSUE TITLE
Suggestion: from date to date filter

### ISSUE THREAD

**Issue by Elitesparkle** [Epix37/Hearthstone-Deck-Tracker#573]
The timeframe filter is easy and fast to use but it doesn't allow to filter games by date in every possible way. Choosing a date to start from and a date where to end would allow to filter games by date much better.

For example, currently I can't filter games to see the ones I've played in the last 3 days.

Maybe you could let the timeframe filter stay as well.

**Comment by GiggliG** [comment]
I'd like this feature too.

**Comment by Epix37** [comment]
Closing in favor of #692
