### ISSUE TITLE
HearthstoneTopDeck web import broken

### ISSUE THREAD

**Issue by n4ru** [Epix37/Hearthstone-Deck-Tracker#576]
They updated their site a few weeks back. I'm guessing the app hasn't updated accordingly yet.

Here's the updated code I use to grab card names in jQuery - might save you a few seconds:
`$.trim($(this).text().replace(/[\t\n]+/g,''))`

And for the deck name:
`$('#wrapper > #center > .headbar > div[style*="float:left"]')`

**Comment by skaforey** [comment]
You're talking about from wwww.hearthstonetopdeck.com right? If so, it seems to be working for me

**Comment by n4ru** [comment]
Weird... it wasn't working for me last night (while other websites work), but now it works for me. My mistake, I suppose.
