### ISSUE TITLE
Problem with deck export to Hearthstone

### ISSUE THREAD

**Issue by toxictrace** [Epix37/Hearthstone-Deck-Tracker#577]
When Russian keyboard layout program imports the deck is normal, but the name of the deck displays in English layout. When the English keyboard layout name cards represented by a "?" and finds nothing. What am I doing wrong ???
Sorry for my English. :) Google Translate.

![hearthstone_screenshot_1 14 2015 14 11 33](https://cloud.githubusercontent.com/assets/10530116/5737997/4cbe3f68-9bf8-11e4-9e70-e4af3de6aaf8.png)
![hearthstone_screenshot_1 14 2015 14 11 08](https://cloud.githubusercontent.com/assets/10530116/5737998/4cc2e9e6-9bf8-11e4-839f-f03246062033.png)

**Comment by Epix37** [comment]
Try turning on *options > other > exporting > paste names from clipboard*

**Comment by toxictrace** [comment]
TNX, already decided. ;)
