### ISSUE TITLE
Suggestion: opponent's deck core view

### ISSUE THREAD

**Issue by Elitesparkle** [Epix37/Hearthstone-Deck-Tracker#580]
Activating this view will let you see the core of the opponent deck.
Turning it off will let you use the tracker as it is now.

The core is be a set of card every one will be able to build, like a deck.
One for each class isn't enough since some classes have access to more than one competitive deck.

At the top of the opponent's deck list on the overlay you'll see the core. This part will be managed as for the deck mode.
Below it you'll see the rest of the deck as usual but not the cards from the core. This part will be managed as for the no deck mode.

During the game you should be able to change which opponent's deck to load (e.g. no deck, Zoo Warlock, Handlock) from the software's window and/or from the tray icon.

Alternatively you could implement a pop-up window like the one showed when a wrong deck is detected. You'll need to look if the core loaded is right or wrong in the same way you do for decks.

I don't know if I forgot some details.
I'll add them later, if needed.

**Comment by Epix37** [comment]
I think this goes too far in the direction of "deck prediction" again. 
See #376 and also #263 for my reasoning behind not wanting to implement that.

**Comment by Elitesparkle** [comment]
I don't think that the attemp to predict part of the opponent deck is a big problem.

We try to predict the opponent deck with our mind already.
When we are playing against Warrior, for example, at the start of the game we assume it is Control Warrior because it is more popular than other Warrior decks. The software should do this.

To do this, we just need to be able to build a deck or a part of a deck for each class. We don't need a detection feature. The list we preared will be loaded. If it is wrong (e.g. when loading Zoo core against Handlock or when we meet a less popular deck), we'll just ignore it while playing. We could also switch to another list or deactivate the function somehow.

**Comment by Epix37** [comment]
Deck prediction is currently not on the table, sorry.

**Comment by Elitesparkle** [comment]
As you wish.
