### ISSUE TITLE
Replay: Counterspell is not correctly detected. 

### ISSUE THREAD

**Issue by mvy** [Epix37/Hearthstone-Deck-Tracker#581]
The counterspell is not correctly register in the replay files.

Look at turn 21 : pyroblast is cast from my hand, but misses to a counterspell (which is neither showing on the secret list nor triggered in the list)

http://pastebin.com/e1ZeKZ7d

**Comment by Epix37** [comment]
Could you upload the actual replay file (found in the *Replays* folder), not the game file? :)

**Comment by mvy** [comment]
https://www.dropbox.com/s/f6adx7vzdusn9um/Mvy%28Mage%29%20vs%20Clarissa%28Mage%29%200116-150115.hdtreplay?dl=0

**Comment by Epix37** [comment]
uhm.. Are you sure there was a counter spell? The opponent took damage and there is no mention of a counterspell in the actual log from the game.

**Comment by mvy** [comment]
I targeted a minion with my Pyroblast

**Comment by mvy** [comment]
Oh wait I got it! The -10 is not display on the current turn, but is removed on next turn. My bad on this one.

**Comment by Epix37** [comment]
There were two pyros played in that game, one by your opponent, one by you.

Yours: 

`TAG_CHANGE Entity=[name=Pyroblast id=8 zone=HAND zonePos=1 cardId=EX1_279 player=1] tag=CARD_TARGET value=36`

id 36:
`FULL_ENTITY - Creating ID=36 CardID=HERO_08` (HERO_08 = mage, the opponent in this case)

This is what was logged by the game. Your pyro in that game definitely hit the mage. Maybe you uploaded the wrong file?

**Comment by mvy** [comment]
No I was just damn too tired I guess. I even thought he had 3 Ice Block which I know is definitely impossible. Nevermind :P

**Comment by mvy** [comment]
Along with the #582 it could be interesting to better materialise the damage taken?

**Comment by Epix37** [comment]
Yes. It's a work in progress after all :).
