### ISSUE TITLE
"Unknown Human Player" in Name Field w/ 0 Turns (Stats Screen)

### ISSUE THREAD

**Issue by giygas73** [Epix37/Hearthstone-Deck-Tracker#583]
Hey, love the program, but recently I have been seeing "UNKNOWN HUMAN PLAYER" appear in the stats window. The "turns" goes to 0 also, but the win/lose condition is recorded correctly. I cannot attribute this to anything, it appears to happen a lot when playing against warlocks though but I have also seen it with druid and priest (it happens rarely, but still enough to be annoying, especially when some of my decks are important in number of turns and I review games sometimes and stuff to see if there is any correlation between number of turns and my win condition (mainly this is dealing with my Fatigue Mage, but also I like to examine if number of turns does anything with my Control Warrior as well).

The earliest I see this occurring in my logs is Jan 9th 22:48 (against a Priest) and since then it happens in something like 1-5% of my games (hard to tell for sure, it's really random), and also some guy over on the HearthStats github (where I posted this issue originally by accident) has informed me that he actually saw the same thing in his program as well, which to me says this must be something in the log files going awry (since afaik both of these programs use the logs to monitor the game).

Here is a screenshot of what I am talking about: https://imgur.com/lazamhA

Let me know what you need in terms of logs and stuff and I can try to provide that.

Thanks :)

**Comment by Epix37** [comment]
Is the opponents name ingame "UNKNOWN" as well?

I see two scenarios here: 
1) The opponent is "UNKNOWN" in game as well, in which case this is an issue on hearthstones end without there being much I could do about it.
2) The opponent was "UNKNOWN" for some amout of time, but *identified* later on. Is this case, the tracker might have records of two opponent entities.

**Comment by giygas73** [comment]
No, although I have seen the issue where the opponent was UNKNOWN in game, this appears to be separate because I remember an instance where I saw the guys name in game and later it said unknown in the logs, so I'm thinking this could be more like scenario 2 above. It's just strange because it hasn't ever happened then all of a sudden on Jan9th it pops up. I thought I pinned it down to being when I changed between decks (like something with auto-deck-selection feature) but then I saw it happen when I hadn't changed the deck before, so god only knows what's going on. Maybe I just never noticed it though and it was happening all along, because (iirc) the showing of player names is a new feature. Hmmm.

I'll keep my eye on it and see if I can correlate it to anything, tough cause it barely ever happens though.

Thanks,

**Comment by giygas73** [comment]
I just saw this happen live actually. I was playing a priest, and as soon as thoughtsteal was played, turn 5 (also he had coin in hand) the turn "counters" on the opponent hand went to all -1 . At the end of the match, the game is recorded with 0 turns and UNKNOWN HUMAN PLAYER as the opponent name.

Of course it's not just thoughtsteal, because it happens for other classes too, but it seems like something in how its counting cards in hand is messing up the turn counter. I have a feeling this could be something to do with draw, or adding to the hand that's overflowing. I see it most for warlocks, which naturally draw more.

Cheers,

**Comment by giygas73** [comment]
Just saw this happen again, this time it was vs a hunter, happened right after he drew from his loot horder on turn 5

**Comment by Epix37** [comment]
http://us.battle.net/hearthstone/en/blog/17796670/hearthstone-patch-notes-2107628-1-29-2015
> Addressed an issue that sometimes resulted in player names showing up as Unknown in-game. You’re a player, not a Secret!

Let's see if that fixed it.

**Comment by giygas73** [comment]
It looks like it may have. I guess it was just the server side after all lol. I got it once right after the update, but since then I haven't seen anything. I guess we can close this. Oh and love the idea for deck version numbers, that helps so much, previously I had like 4 warrior decks now they are just versions :)
