### ISSUE TITLE
Import from Clipboard bug

### ISSUE THREAD

**Issue by GiggliG** [Epix37/Hearthstone-Deck-Tracker#584]
I imported a deck which contained the following:

Hunter's Mark
Multi-Shot
Gladiator's Longbow

These three were imported as unknown cards, and names were shown like this:

s Mark
Shot
s Longbow

Clearly something wrong with the hyphen and apostrophe.

**Comment by skaforey** [comment]
I just copy and pasted what you typed, imported from clipboard: card names and it worked flawlessly.....

**Comment by Epix37** [comment]
Works fine for me, too. Could this be an issue with keyboard/language settings?

**Comment by Epix37** [comment]
Got it. The issue appears if the names have a count attached. So `Hunter's Mark` works fine, `Hunter's Mark x2` does not.

**Comment by GiggliG** [comment]
Good to know. Sorry for not being able to reply earlier. Yes, i had x2 on all of those.

**Comment by Epix37** [comment]
fixed with v0.8.0
