### ISSUE TITLE
Suggestion: victory/defeat screen automatic screenshot

### ISSUE THREAD

**Issue by Elitesparkle** [Epix37/Hearthstone-Deck-Tracker#585]
Some players are competing in tournaments and they could need a screenshot of the result of their game as a proof of their victory.

I'm asking for a feature that will record a screenshot automatically.
You could also add a button in the Stats window to access to the screenshot folder or to open the image direcly with the default software used by the operating system.

**Comment by Epix37** [comment]
I think relying on the software to make screenshots for you when you **need** them is not a good idea. If the end-game detection fails.. no good.

**Comment by Elitesparkle** [comment]
I see.

How could it fail?
How do you detect it? Do you look for a particular log line?

**Comment by Epix37** [comment]
Pretty much, yes. It did fail a lot after the v0.7.0 update due to several issues. 

It *should* be stable now, but I'm not 100% certain it will be in all cases, always.  What if the game for some reason decides to not log something or we run into file access issues or.. the tracker freezes right at that moment.. so many possibilites.

**Comment by Elitesparkle** [comment]
For example, you could let it show a message when the screenshot has been successfully taken.
Every time a game ends, we'll just need to wait for that message and then click to proceed.

**Comment by Epix37** [comment]
I don't want the software to have that responsibility. Adding that feature is fine, but relying on it is bad.

**Comment by Elitesparkle** [comment]
Just add a warning where you decline any responsibility and show it to the user when he tries to activate this feature.

**Comment by Cu8eR** [comment]
useless feature

**Comment by Elitesparkle** [comment]
Useless comment?

Many features can be considered useless by some but useful by others.

**Comment by Cu8eR** [comment]
But this is one of them :) is it really hard to push a print screen button after game? And moreover it is not realiable way how to prove anything

**Comment by culinko** [comment]
I don't really get why you said that the feature is useless, when you actually looked forward to it (#344). I think this suggestion is really good, especially for people who participate in tournaments. I'm not saying we should rely on the feature, but having it would be really awesome!

**Comment by andburn** [comment]
I've made a plugin to do this. Its not going to be something you can ever rely upon 100%, for various reasons. Read more [here](https://github.com/andburn/hdt-plugin-endgame) and download [here](https://github.com/andburn/hdt-plugin-endgame/releases/latest). Send me feedback over at the plugin's own [page](https://github.com/andburn/hdt-plugin-endgame/issues).

**Comment by culinko** [comment]
You are awesome!
