### ISSUE TITLE
Suggestion : Add a button in the stats page for add manually games 

### ISSUE THREAD

**Issue by Zoby-one** [Epix37/Hearthstone-Deck-Tracker#587]
I play HearthStone on my computer and on my iPad.
I would like to add the games that i played on my iPad in HearthStone Deck Tracker for a best monitoring...
Could it be possible ?
(Excuse for my bad english, I'm french)

**Comment by GiggliG** [comment]
I'd like this too. Obviously manually added games wouldn't support the replay/game history feature, but would probably just need: Class Played, Opponent Class, Win/Loss, Coin/No Coin.

**Comment by Epix37** [comment]
Will be in the next update!
![screenshot 2015-02-07 13 01 37](https://cloud.githubusercontent.com/assets/7737910/6092027/7d4d2368-aec9-11e4-866d-449f62368ede.png)

**Comment by Epix37** [comment]
added with v0.9.0
