### ISSUE TITLE
blocker: invalid icon path

### ISSUE THREAD

**Issue by elfrab** [Epix37/Hearthstone-Deck-Tracker#588]
System.Windows.Markup.XamlParseException -> System.Windows.Baml2006.TypeConverterMarkupExtension -> System.IO.DirectoryNotFoundException: D:\Images\HearthstoneDeckTracker.ico

the icon path is invalid, causing the application to crash on start.
this happens with the:
compiled downloadable exe,
0.75 source code,
master source code

MainWindow.xaml
Icon="..\Images\HearthstoneDeckTracker.ico" Activated="MetroWindow_Activated"

PlayerWindow.xaml
Icon="/Hearthstone Deck Tracker;component/Images/HearthstoneDeckTracker.ico"

OpponentWindow.xaml
Icon="/Hearthstone Deck Tracker;component/Images/HearthstoneDeckTracker.ico"

**Comment by Epix37** [comment]
If this is the same issue I heard about a while back, then it's a weird permissions problem.

In that case:
Manually create the folders ("Hearthstone Deck Tracker", "Hearthstone Deck Tracker/Files" and "Hearthstone Deck Tracker/Images"), then drop the corresponding files into those.

**Comment by elfrab** [comment]
I doubt it's a permission problem. He basiclly just looks for the icon at the wrong place. The exception is clear about that.

I'm not familiar with xaml, but when i replace the paths with that:
{DynamicResource HearthstoneDeckTracker.ico}
it works.

I can compile (release) and can start the app on any location on my system.

However VS2013 complains (warning) that he cannot resolve the icon resource.

**Comment by Epix37** [comment]
Did you try creating the folders manually? I don't know of anyone else currently having this issue, so that might very well be it. 

Might not actually be a permissions problem but something like that anyway. 

I do remember that DirectoryNotFound was the exception in that case. That had me confused for a while back then.

**Comment by elfrab** [comment]
I found the reason. My path contains #.
I tried several other special chars and they all work fine. It doesn't look like an encoding issus.
This is really strange.

**Comment by Epix37** [comment]
Indeed very strange. # should not be an invalid character.

**Comment by Wellxam** [comment]
This IS a weird issue, assuming '#' is used to get the folders to auto-sort to the top like me, '$' seems to work without issue... also simply giving into its demands and copying the icon to the specified path in the crash log seems to work... this has to have been one of the weirder issues I've seen.
