### ISSUE TITLE
Export to HearthStone - I get "No Matches Found" for cards that exist during macro run

### ISSUE THREAD

**Issue by roymayfield** [Epix37/Hearthstone-Deck-Tracker#589]
Hi Epix, I set macro speed to very slow, and tried flipping "paste names from clipboard", but still only about 1/2 of the deck gets defined in HS (14-18 cards).  Behavior observed on 0.7.4 and 0.7.5.

**Comment by Epix37** [comment]
What language are hearthstone and the tracker set to?

**Comment by roymayfield** [comment]
HDT is set to English.  I am running w8.1 Pro, language is set to English (United States).

**Comment by Epix37** [comment]
Any chance it is this issue: #303?

**Comment by FenrisWolffe** [comment]
When this has happened to me, I normally made some small silly mistake like having something in the search field (I.e. "Legendary" or "dragon" and it excludes most of the cards.

The other times, I've moved the mouse on accident, causing the tracking to be off.

**Comment by roymayfield** [comment]
This was indeed issue #303 !!!  Kudos Epix for flagging this out!!!  Cheers, roy
