### ISSUE TITLE
Cannot Start Program, Instantaneous Crash

### ISSUE THREAD

**Issue by csdan** [Epix37/Hearthstone-Deck-Tracker#591]
I cannot even load up the program itself, as the crash is instantaneous.

Also, I attached a image of the crash report because apparently GitHub doesn't support txt file types....
![crash report 1712015-2359](https://cloud.githubusercontent.com/assets/10377247/5791486/3fa46824-9ea6-11e4-8bcb-c3ffca89d953.png)

* I've tried re-installing Deck Tracker to no prevail.

* I've tried changing my Hearthstone window size to maximized & set Hearthstone to full screen, because I thought that could've been the issue after reading the crash report. :P Still though, to still no prevail.

There isn't anything else to say besides that regarding the crash.

Hopefully I can get this fixed soon, because I haven't gotten a chance to try this program in-game yet.

**Comment by Epix37** [comment]
Deleting the config.xml in "%AppData%/HearthstoneDeckTracker" (press WIN+R, paste) should do it,

**Comment by csdan** [comment]
​​
Thanks, that worked! :)
