### ISSUE TITLE
Program only displays cards that have been drawn and not in deck

### ISSUE THREAD

**Issue by rinzlerx** [Epix37/Hearthstone-Deck-Tracker#592]
While playing the program no longer shows all of the cards in my deck displayed on the right-hand-side. The cards only appear as they're drawn. I just want to see my whole deck and have the drawn cards grayed out similar to Trump's videos.

**Comment by Epix37** [comment]
Decks are not detected automatically. You have to either create them (menu: NEW) or import them via some method (menu: IMPORT).

Note: only arena decks can be imported from the game.

**Comment by rinzlerx** [comment]
I understand this, what I am trying to say is that even when I have my decks imported, the decks aren't all displayed. They only appear when they're drawn. I want them to all appear on screen and be grayed out when they're drawn.

**Comment by Epix37** [comment]
Select the deck in the tracker itself.
![screenshot 2015-01-18 19 54 45](https://cloud.githubusercontent.com/assets/7737910/5793637/dc54cc18-9f4b-11e4-9408-ff41984b7188.png)
-> 
![screenshot 2015-01-18 19 54 43](https://cloud.githubusercontent.com/assets/7737910/5793638/dec4e5aa-9f4b-11e4-81ca-355f469b406e.png)

**Comment by rinzlerx** [comment]
Thank you so much.

**Comment by Epix37** [comment]
No problem, enjoy!
