### ISSUE TITLE
Importing decks from ingame deck lists

### ISSUE THREAD

**Issue by misaochan** [Epix37/Hearthstone-Deck-Tracker#593]
Hey, thanks for this addon, works great so far!

The only problem I have is... there doesn't seem to be an option to import from an ingame deck list? I know there is one for arena, but I mean for constructed. And there is 'import from last game' but that only pulls up the cards that were actually drawn. So what usually happens is that after I export a deck, I make modifications to the deck ingame, and then I have to manually modify the tracker list after that.

**Comment by Epix37** [comment]
Not possible, sorry.
