### ISSUE TITLE
The app doesn't seem to work.

### ISSUE THREAD

**Issue by sefer66** [Epix37/Hearthstone-Deck-Tracker#595]
Hi,
So i have a problem with the app. The app doesn't seem to detect when i'm on a game. It works when i'm in the menu, because i can hide or not the app in the menu and it recognize when i', in the menu. The problem is that, the app doesn't recognize when i start a game, it's like i was on HS's menu. 

Thank you!

**Comment by Epix37** [comment]
Try restarting hearthstone and the tracker.

**Comment by sefer66** [comment]
Already tryed. Even tryed to reinstall HS

**Comment by Epix37** [comment]
Go to options > other > tracker and click "set hearthstone path", select your Hearthstone folder. Check if that fixes the problem. 

If not: Close Hearthstone and the tracker. Then copy the "log.config" file from [Hearthstone Deck Tracker]/Files to "%LocalAppData%/Blizzard/Hearthstone" (press WIN+R, paste) and replace the existing one, if there is one. Check again.

**Comment by sefer66** [comment]
Okay, it worked, thank you!

**Comment by Epix37** [comment]
Perfect. Out of curiosity, which one did it?
