### ISSUE TITLE
Sugestion: Support elitedecks.net for import

### ISSUE THREAD

**Issue by leonardoraele** [Epix37/Hearthstone-Deck-Tracker#597]
One of the bests sites to search for decks is http://www.elitedecks.net/, please add support to import decks from it.

**Comment by skaforey** [comment]
Created pull request.  Just a note, and it may be just my area, but this site was experiencing a lot of timeouts during testing.

https://github.com/Epix37/Hearthstone-Deck-Tracker/pull/598

**Comment by Epix37** [comment]
added with v0.8.0
