### ISSUE TITLE
"Highlight cards in hand" doesn't works

### ISSUE THREAD

**Issue by WantedThing** [Epix37/Hearthstone-Deck-Tracker#601]
I'm using HearthStone on Europe server with french language.
I tried all different combinations in the settings but i'm still not able to make this work. I searched on youtube for french videos showing your program running and it seems that the problem doesn't concern only me, that's why i write it here.

**Comment by Cu8eR** [comment]
I can confirm it... no highlight

**Comment by WantedThing** [comment]
I realized that it works if you're playing with a deck you have configured and enabled in the HS-Deck-Tracker.

Otherwise, it's buggy, nothing is higlighted except :
-Bonus cards like the piece
-Units or cards that come back to your hand
-Cards in your hand after a disconnection
-Cards in your friend's hand when you go watch him play

I hope it helps^^

**Comment by Epix37** [comment]
So this in only happening in "no deck"-mode, yes?

**Comment by WantedThing** [comment]
Yes.
