### ISSUE TITLE
Suggestion: collection tracker

### ISSUE THREAD

**Issue by formigao** [Epix37/Hearthstone-Deck-Tracker#602]
a system that automatically track your connection and create a database for it
when you import decks sometimes you don't have the cards needed for it

i would love if the program could show what cards im missing and also could generate a txt file with your collection so if you want to ask for a suggestion of deck you can send the file for someone and that people would know what you have to help you better.

would be nice too if it showed what cards you have 2 golden adn 2 normals so you could dust the duplicates

sorry my bad english.

**Comment by GiggliG** [comment]
I'd like this, but there's a complication: People may play in more than one server (or even with more than one account) so could have more than one card collection.
So you'd need the ability to add cards to a specific collection, and then switch which collection HDT was using as the active collection, for the purpose of showing you (perhaps by highlightign) which cards in a deck aren't in that collection.

**Comment by Epix37** [comment]
This is probably obsolete (or at least not worth the additional effort) with #604.

**Comment by formigao** [comment]
hum this 604 looks good !!

what about duplicates ? 

Golden and normal cards.

other day i got a extra 1100 dust removing cards i had a 4. ( 2 Golden 2 normal)

**Comment by Epix37** [comment]
What exactly is the question?

**Comment by formigao** [comment]
for example : http://i.imgur.com/a5ld0WD.jpg

I have 4 Rei das feras.

2 normal and 2 golden.

a feature that could say for me what others cards i have extra copies would be amazing.

so we can dust the extras more easily.

**Comment by jw013** [comment]
There's already a button in hearthstone to disenchant all your extra cards.
