### ISSUE TITLE
Just downloaded the deck tracker and it isn't working 

### ISSUE THREAD

**Issue by JrRocket000** [Epix37/Hearthstone-Deck-Tracker#603]
While exploring Hearthstone on Reddit today I came across this post http://www.reddit.com/r/hearthstone/comments/2tedxq/are_you_using_any_toolsthird_party_apps_if_so/[1]
I discovered this third party application called Hearthstone deck tracker https://github.com/Epix37/Hearthstone-Deck-Tracker[2]

So I went on ahead and installed it, after installing it I ran the program and created my decks, but after I got into a game of hearthstone it didnt show the same overlay as the pictures on the website and from the YouTube videos I watched on the program, it also was not keeping track of the cards that my opponent had played and wasn't taking the cards out of my deck that I had played!

I was wondering if someone could help me solve this problem :)

I have attached an album showing the overlay that I have and the settings for Hearthstone Deck Tracker
http://imgur.com/a/5CEYD [3]

**Comment by Epix37** [comment]
See if #595 helps you.

**Comment by JrRocket000** [comment]
I thank you for the super quick response, and one of those issues did fix my problem that I was having, although  I don't know which one fixed it:D
Ill be using this program alot its amazing :)

**Comment by Epix37** [comment]
Very good :). Enjoy!
