### ISSUE TITLE
Import deck from Hearthstone

### ISSUE THREAD

**Issue by Naffhan11** [Epix37/Hearthstone-Deck-Tracker#608]
Is there no way to import the constructed deck from HS into the tracker? I've seen it on another HS tracker, but since moving to yours (because it's far superior) I've found it time consuming to make adjustments to the deck in game, and then have to do it in the tracker as well. 
May not be possible, and I'm sure it's something you've considered, but would love to see this feature.

**Comment by Epix37** [comment]
You are correct, I'm pretty positive it's not possible for the games logs. I tried quite a bit :). Mkjogo (I guess you were using?) does this via monitoring traffic, which is something I want to avoid doing for staying as clear from TOS violations as possible. 

I would very much love to see that feature too.

**Comment by Naffhan11** [comment]
I see, that's fair enough.
Great work on the tracker by the way, really helpful and interesting. 
I look forward to future updates.

**Comment by Epix37** [comment]
Thanks :). 

The next update will have quite a bit of cool new stuff!
