### ISSUE TITLE
Move Hearthstone Tracker to another PC

### ISSUE THREAD

**Issue by Greycrow777** [Epix37/Hearthstone-Deck-Tracker#609]
Hi ..

How i can copy hearthstone tracker with all my data ( Decks and replays ) to another pc without losing anything

sorry for silly question but i tried today to do that by coping files on picture below and it wasn't work for me

http://i.imgur.com/Ue3IX0o.jpg

Thanx for help in advance

**Comment by Epix37** [comment]
If you want to use it exclusively on the new PC disable `Save data in AppData` and `Save config in AppData` in `options > other > tracker` that will move all the data (except replays with the current version) in the tracker folder. 

To move the replays if desired, open the appdata folder via `options > other > tracker > open appdata folder` and copy the `Replays` folder manually.

If you with to use the tracker on multiple PCs check out #545.

**Comment by Greycrow777** [comment]
OMG !!

I follow your steps until i reach to "other" menu and then .. antivirus ( Bitdefender ) shows up and deleted lunch file !!

have look here http://i.imgur.com/wVaQDIo.jpg

even recover it from antivirus wasn't help so i downloaded hearthstone tracker again and i tired to copy lunch file to fix my damaged folder but sadly i can't launcher into that folder !! ( access is denied  ) and the funny thing that i can copy in anywhere else ...

so after all that happen i give up and download fresh tracker and guess what !!
it's not working for unknown reason .... 

error message
http://i.imgur.com/N37BVYi.jpg 

report file
########## 1/28/2015 02:35:02 ص ##########
System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'Hearthstone_Deck_Tracker.MainWindow' that matches the specified binding constraints threw an exception. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\X_MAD\AppData\Roaming\HearthstoneDeckTracker\config.xml' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at Hearthstone_Deck_Tracker.Config.Load()
   at Hearthstone_Deck_Tracker.MainWindow..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)


by the way did that mean i lost my deck data please don't me that happen and save my life ...

**Comment by Epix37** [comment]
This seens to happen alot lately. I don't quite understand why or at least why it didn't before. 
Could be an issue with it accessing things on the clipboards it's not supposed to, if that's the case be971ad should fix that.

You did download it from here: https://github.com/Epix37/Hearthstone-Deck-Tracker/releases, right?

You might have to somehow give it permissons back, I'm not sure how that works though (possibly #454 ?). 

Your decks and data should be fine, they are stored at "%AppData%/HearthstoneDeckTracker".

**Comment by Elitesparkle** [comment]
Could it be related to the fact that he changed where to save the configuration files?

**Comment by Epix37** [comment]
As I understood, the didn't even get to that point.

**Comment by Elitesparkle** [comment]
> As I understood, the didn't even get to that point.

Oh, right. So we can exclude that as a possible cause.

**Comment by Greycrow777** [comment]
Antivirus causes a lot of problems for hearthstone tracker
I test some things like add tracker files in "excluded Files and folder " in bitdefender menu and change some options ..

at the end it wasn't fix anything so I turn bitdfender off totally by shut down these settings in picture
http://i.imgur.com/gdXfvgV.jpg

and finally my tracker back to work again " for now " but i'm not totally sure what will happen if i open tracker menu or something like that while antivirus turn on!!

I hope these lines help anyone who have similar issue like me 

as you understand now i'm using new hearthstone tracker  and it's empty because the old one damaged and i'm trying to bring my old files again for now ( decks and replays ) into the new hearthstone tracker and i don't know how to do that so could you please tell what i should do ?

**Comment by Epix37** [comment]
As I said, decks and data are stored at "%AppData%/HearthstoneDeckTracker"(options > other > tracker > open appdata folder or press WIN+R and paste the address).

Did you succeed in disabling any of the options? If so, the data might now be located in the "damaged" folder and you might have to copy it back to appdata. Otherwise it *should* still be in appdata.  

Look for a config.xml and a PlayerDecks.xml (maybe even a PlayerDecks_backup.xml), let me know where they are (appdata or local) and I can tell you what to move where.

**Comment by Greycrow777** [comment]
First when i was trying fix old issue i take copy of files in "%AppData%/HearthstoneDeckTracker" and save it in another place in order to delete all old files with tracker and reinstall fresh one so now "%AppData%/HearthstoneDeckTracker" has default files and i have these files from old tracker ( in picture below )
http://i.imgur.com/UcU6D2e.jpg

do i need to replace files or what because i already tried that and it wasn't work or maybe i did it by wrong way !! tell me the correct steps get my old config and decks list into new tracker ?

by the way yes i can disable anything now in tracker option also i noticed something new after getting last tracker version ..
when i open tracker this message comes up http://i.imgur.com/8eOkEd5.jpg
I just close it and keep working normally but i don't know what it's mean or what is effect

**Comment by Epix37** [comment]
Was there no "PlayerDecks.xml" file when you made the copy? That's the one where, well, the decks are stored :(. That's the one you need. If that file is gone, there's not much that can be done. Maybe check your recycle bin.

The error message on start may be related to the antivirus issue still, I'm not sure. All it means is that the update-check (for a newer version) failed.

**Comment by Greycrow777** [comment]
wasn't that file you mean the last one in here ? http://i.imgur.com/UcU6D2e.jpg
Yes it is i think .. so what i need to do !

**Comment by Epix37** [comment]
No it's not :(. That one is basically empty and there's actually no reason for the tracker to generate that file anymore, I'm just too lazy to remove it.

**Comment by Greycrow777** [comment]
So sad to hear all my work gone with wind ..
Ok to make sure not falling in this situation again all i need is take copy of files from "%AppData%/HearthstoneDeckTracker" as backup and maybe in future if i install new hearthstone tracker on any PC all i need is just past my backup files on appData folder again .. right ?

**Comment by Epix37** [comment]
In short, yes.

**Comment by Greycrow777** [comment]
I really appreciate your help .. *Respect*
Thank you bro wish you the best

**Comment by Epix37** [comment]
No problem, sorry for the mess.
Lets hope I can find out why this happens.

**Comment by Epix37** [comment]
One more thing, do you have logs from your antivirus software deleting the tracker, you could send me? Maybe that helps figuring this out. (epikz37@gmail.com)
