### ISSUE TITLE
Card Age issue

### ISSUE THREAD

**Issue by lee-CS** [Epix37/Hearthstone-Deck-Tracker#610]
Earlier today I had card age showing -1 for all cards, now it is showing 2 for all cards. 

Marks (Kept Cards, Mulligan'd, Spare parts, etc.)  Seems to be working fine though.

**Comment by Epix37** [comment]
This *could* be an issue on blizzards end (server issues), logs seem very inconsistent lately.

**Comment by GaelicSmash** [comment]
Im seeing the wrong amount of "Age counters" for the actual amou8nt of cards ingame. Currently playing innkeeper just to test this app/tool, but like I said, wrong overlay info  :(

**Comment by Epix37** [comment]
Haven't seen / heard of this issue in a while, closing for now.
