### ISSUE TITLE
Record opponent level in ranked game

### ISSUE THREAD

**Issue by MarioZG** [Epix37/Hearthstone-Deck-Tracker#611]
Can you find in logs level of your opponent in ranked game ? 

At this moment i just add a note with opponent level after each game. This allows me to filter stats by level, but dedicated field would make it more usable...

**Comment by Epix37** [comment]
Kind of. 

After each game assets get unloaded, two of which are the medals:
`[Asset] CachedAsset.UnloadAssetObject() - unloading name=Medal_Ranked_17 family=Texture persistent=False`

Two issues:
1) asset unloading is sometimes unreliable
2) I don't know of a way to tell which asset unload belongs to the player and which to the opponent.

**Comment by Elitesparkle** [comment]
> 2) I don't know of a way to tell which asset unload belongs to the player and which to the opponent.

You could check if they are loaded every time in the same order.

**Comment by Epix37** [comment]
I think I tried that and it wasn't the case. That was a long time ago though, I could be wrong or it could have changed.

**Comment by Epix37** [comment]
I think I just made this work!

**Comment by MarioZG** [comment]
That is awesome! Looking forward to try and test it!

**Comment by Elitesparkle** [comment]
> I think I just made this work!

Nice.

**Comment by MarioZG** [comment]
Seems to works nice! well done!

One question - at this moment it logs players rank. Can we choose to log opponent's rank?

**Comment by Elitesparkle** [comment]
> One question - at this moment it logs players rank. Can we choose to log opponent's rank?

Right. They are different sometimes.

**Comment by Epix37** [comment]
For now it'll be only your own rank. Opponent is not out of the question for the future tough.

**Comment by Cu8eR** [comment]
Is it really useful? In almost 99% time you get opponnent which is on the same rank as you (or +-1). 

@Epix37 - what do you think? If it is possible why not, but as I said above - I really wanna know my rank
