### ISSUE TITLE
Bitdefender Detected HearthStoneDeckTracker.exe as a threat

### ISSUE THREAD

**Issue by Fyrestrom** [Epix37/Hearthstone-Deck-Tracker#614]
Bitdefender thinks it is Trojan.Generic.12668508 and quarantined it.

**Comment by Epix37** [comment]
See my last post in #605. Update should be out this weekend.

**Comment by Epix37** [comment]
Though, you *can* actually download the (almost) latest build here: https://github.com/Epix37/Hearthstone-Deck-Tracker/pull/599#issuecomment-72009724

There should be no issues, but I would still suggest you back up your "%AppData%/HearthstoneDeckTracker" (Win+R, paste) folder before you do so.

**Comment by Epix37** [comment]
Should be fine with v0.8.0
