### ISSUE TITLE
Consider making it for Mac?

### ISSUE THREAD

**Issue by cerminalo054** [Epix37/Hearthstone-Deck-Tracker#616]
Can you please consider making or converting this to Mac. I know many of my friends and me would benefit use it.

**Comment by Epix37** [comment]
There are people working on that :) https://github.com/Jeswang/Hearthstone-Deck-Tracker-Mac

**Comment by sethbc** [comment]
@cerminalo054 it's bad protocol to keep submitting the same request over and over.

**Comment by cerminalo054** [comment]
i just submitted it once. And this was my first time....

**Comment by cerminalo054** [comment]
The first time I thought it didn't go through.... And this time i forgot i asked in the first place. I am sorry if you thought i wanted to intentionally ask the question multiple times.
