### ISSUE TITLE
Export to heartstone not correct

### ISSUE THREAD

**Issue by MarioZG** [Epix37/Hearthstone-Deck-Tracker#617]
I'm on latest commit - https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/55588f7d88ae470ba04a3d21340cc0cd0607f40e .

When exporting deck to heartstone, it stops at 16 cards. It looks like it's selecting cards 4 times instead of 2, and thinks it;s all done, when in the matter if fact it's half-way there...

**Comment by Epix37** [comment]
I would bet it's #303

**Comment by MarioZG** [comment]
You just won a…. ?. Closing.
