### ISSUE TITLE
Exporting only exports half the cards

### ISSUE THREAD

**Issue by Epix37** [Epix37/Hearthstone-Deck-Tracker#620]
I'm sure this will come up with the release of v0.8.0.

To solve this problem check out #303. (tl;dr: set hearthstone to windows 7 compatibility mode)

**Comment by d07RiV** [comment]
Thanks, that partially helped, but it still takes me 2-3 attempts to export the entire deck, it seems to often miss multiples of cards.

**Comment by Epix37** [comment]
Try lowering the speed in options > other > exporting
