### ISSUE TITLE
Deck versioning and naming conflicts

### ISSUE THREAD

**Issue by MyopicCat** [Epix37/Hearthstone-Deck-Tracker#622]
I love the new versioning system! But is there a way to migrate my existing deck versions into the new system? For example, say I have have old decks called Mech 1.0, Mech 2.0, Mech 2.1 and Mech 2.2. I'd like to be able to make them all versions of the same Mech deck, while retaining version numbers, history and game stats. If this is not currently possible then consider it a feature request! :)

Also, it would be nice if I could have a mage deck and a shaman deck that were both called Midrange without this resulting in a naming conflict. I currently have to include the class in most of my deck names, which feels clunky.

**Comment by n4ru** [comment]
I think your best bet is exporting them to clipboard as IDs and re importing into the same deck, as a new version. Shouldn't take too long unless you have a ton of these.

**Comment by Epix37** [comment]
I think merging the stats will be the issue here

**Comment by MyopicCat** [comment]
I interpret your answers to mean that there is no current way to do this while retaining game stats. If so, how about a new option in the Save menu called something like "Save as subdeck"? This option would prompt you for a deck name and version number. Would that work?

**Comment by Epix37** [comment]
You interpret correct. 
It *is* possible by editing the PlayerDecks.xml but probably not worth the trouble. 

I can't see this feature finding much use outside of a few initial deck merges, so I'm not sure how much time I'm willing to invest at the moment. 

I can say this won't make it into the next release, unless someone else wants to do it. For once I actually know what the next update will be, I think you guys will like it. (No spoilers yet though :))
Maybe this will make it into the release after that, together with deleting versions and moving stats between versions.

**Comment by Epix37** [comment]
As for your second point, multiple decks with the same name: that's something I plan to have in the next update.

**Comment by MyopicCat** [comment]
OK, I'll keep my fingers crossed for a later version. I did have a look at PlayerDecks.xml before posting, but the nested <DeckHistory> tags scared me away. Out of curiosity, why do you need to store deck history at all? Couldn't you store each sub-version as a complete deck, and have the application infer the history by diffing the deck lists? Maybe the reason is obvious, I'm not a developer.

Well done with that offhand comment, I'm dying to see the next version now ... :)

**Comment by Epix37** [comment]
I didn't implement that part of the versioning system myself (idk if I would've done it differently though), for the aspect of a "history" it makes perfect sense. The option to set the selected version was added later. 

And in case you missed it, the next version: #629 :).

**Comment by Epix37** [comment]
"Merging" can be done the way @GiggliG describes it [here](https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/777#issuecomment-78404042). Not the best way but I don't think it worth putting too much effort into this. Though it will be easier with the next release, which will allow to move multiple games at once, to a arbitrary version of a deck.
