### ISSUE TITLE
Arena import ignores duplicates of cards

### ISSUE THREAD

**Issue by d07RiV** [Epix37/Hearthstone-Deck-Tracker#624]
Simply put, when importing an arena deck, it only lists 1 of each card, so if I have multiples of some cards, it ends up with an incomplete deck.

Looking at the log file, apparently there's nothing that can be done about it?

**Comment by Epix37** [comment]
![screenshot 2014-12-26 14 00 32](https://cloud.githubusercontent.com/assets/7737910/5988652/a9bb27ac-a969-11e4-96a2-a70471660452.png)

:)
