### ISSUE TITLE
Automatic Features aren't functioning since latest Hearthstone patch

### ISSUE THREAD

**Issue by Tabien** [Epix37/Hearthstone-Deck-Tracker#626]
I've tried previous version and have the same trouble. It's not an antivirus thing. It seems more like the program just can't read the log file anymore. not sure if the code got messed up or if blizzard changed where it's located with the most recent patch.

**Comment by trickster74** [comment]
I'm having issues as well. It will still display my deck over on the side of the screen, but does not highlight or remove cards as they are played or track the opponent's deck or draws.....

**Comment by Epix37** [comment]
Hm, seems to be working for me, so it's at least not a change on blizzards side. You had me worried for a second there :).

Any change from restarting hearthstone, tracker and battlenet launcher?

**Comment by Tabien** [comment]
I've tried restarting all of those with no luck. I even tried downgrading to previous versions of the tracker with no luck. It's no longer tracking the cards that are drawn, nor selecting the current deck, nor  importing from arena. It really seems like it's just not reading the log file anymore.

**Comment by Epix37** [comment]
Try setting the hearthstone directory again via `options > other > tracker > set hearthstone path`.

**Comment by Tabien** [comment]
tried that, no difference

**Comment by Epix37** [comment]
Play a game (concede practice works) without the tracker running and upload (or email to epikz37@gmail.com) the following 3 files:

1) `Hearthstone/Hearthstone_Data`: `output_log.txt` 
2) `%AppData%/HearthstoneDeckTracker`: `config.xml`
3) `%LocalAppData%/Blizzard/Hearthstone`: `log.config`

2) and 3) you can just copy and paste into run (Win+R) to open them.

**Comment by Tabien** [comment]
ok, attached them to an email called hearthstone files and sent them to you, hopefully it's what you wanted. I'm heading to bed. will check back when I wake up. Thanks for looking into this.

**Comment by trickster74** [comment]
Should I do the same? I am experiencing the same issues....

**Comment by Epix37** [comment]
Rebooting seems to have solved the issue for @Tabien. No similar experience for you?
