### ISSUE TITLE
Different program recognition?

### ISSUE THREAD

**Issue by Ampelioides** [Epix37/Hearthstone-Deck-Tracker#628]
Hi all, 

Getting a lot out of the deck tracker, but i realize that sometimes when I open up other games (in this case, Mountain and Cosmochoria) that the deck tracker turns up when they are loaded? I assume this is due to them using some sort of similar engine or program or w/e (can you guess I'm not a tech guy?)

Is there something that can be done to specify it to only display when HS is open?

Cheers.
![image](https://cloud.githubusercontent.com/assets/10794958/5991611/b820ec6e-aa45-11e4-95bc-847f8cdef65f.png)

**Comment by Epix37** [comment]
Go to `options > other > tracker` and disable ` Advanced window search`

**Comment by Ampelioides** [comment]
Oh thanks!
