### ISSUE TITLE
Deck Tracker not loading

### ISSUE THREAD

**Issue by OUGHT** [Epix37/Hearthstone-Deck-Tracker#632]
On a fresh Windows, when I double-click on exe, I recieve nothing, no visual responce except Windows spinning circle. Task manager shows that Tracker closes after 5-10 seconds.
How can I fix it?

**Comment by Epix37** [comment]
Do you have .NET Framework 4.5 installed?

**Comment by OUGHT** [comment]
Nope. The problem is gone after installing =-)
