### ISSUE TITLE
Export Replay

### ISSUE THREAD

**Issue by adithep** [Epix37/Hearthstone-Deck-Tracker#636]
I think it would be really nice if we can export replay data to any text format for example xml or json.

**Comment by Epix37** [comment]
The .hdtreplay files just zips. Open it and you'll find a output_log.txt which contains the original log data, as well as a replay.json with is a 2d array of [entities](https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/Hearthstone/Entities/Entity.cs).

**Comment by adithep** [comment]
Thanks!

**Comment by voilamochu** [comment]
Hi, where are these .hdtreplay files located?

**Comment by yurifw** [comment]
Sorry to commento on such an old issue, but I just opened the hdtreplay files and they just contain the output_log.txt. Is there a way I can get this in JSON format?

**Comment by azeier** [comment]
The json format no longer exists, sorry.

**Comment by yurifw** [comment]
Is there any other format I can get the info easier then the output_log.txt? All the information I can found is outdated. If I click to see the replay I can download an XML, is there a way to get that XML without a webscraper?

**Comment by jleclanche** [comment]
Take the ID of the replay. For example, for `https://hsreplay.net/replay/u3FYcWm2vXr9ZNtZsyavC6`, that is `4EDxpNihFAbY3YFMo7aGgC`.

Then go to `https://hsreplay.net/api/v1/games/<shortid>/`. Example: https://hsreplay.net/api/v1/games/u3FYcWm2vXr9ZNtZsyavC6/

The URL `replay_xml` is what you want.
