### ISSUE TITLE
Nozdormu timer

### ISSUE THREAD

**Issue by Maximumpower** [Epix37/Hearthstone-Deck-Tracker#638]
If i play nozdormu timer should change from 1:30 to 15 seconds but it doesn't

**Comment by Cu8eR** [comment]
@Epix37 - I can confirm this - 2 days ago I played Nozdurmu in my game and the timer was 90sec instead of 15sec

**Comment by GiggliG** [comment]
While this is true, i don't think the timer matters much when nozdormu is active - if you are taking time to look at the timer, you might be in trouble!

**Comment by culinko** [comment]
@Epix37 I think this is implemented, right?

**Comment by Epix37** [comment]
Yes
