### ISSUE TITLE
CPU usage spiking randomly after being open for a while

### ISSUE THREAD

**Issue by NightKev** [Epix37/Hearthstone-Deck-Tracker#642]
I started HDT up about 4 hours earlier and have been playing HS off and on since then, but I noticed my computer kept freezing up for a moment every few seconds. When I checked task manager, it showed HDT as using max CPU suddenly and then dropping back to 0 (at the time I wasn't playing HS). After closing it the freezing is gone, so it was definitely caused by HDT. Other than HDT, my system was averaging <5% cpu usage. My OS is Windows 7 64-bit.

**Comment by Epix37** [comment]
Weird. Can you give me a more exact interval?

**Comment by Cu8eR** [comment]
@NightKev @Epix37 I have already reported this some time ago... with newer version I have this problem only sometimes and only for 2-3 sec when I start my deck tracker - I think it is becuase of autoupdate component and loading my decks. After that all is OK
