### ISSUE TITLE
Exporting deck glitched in weird way.

### ISSUE THREAD

**Issue by ChilledDragon** [Epix37/Hearthstone-Deck-Tracker#643]
When I exported my deck to hearthstone, the mouse just clicked on "suggest a card" numerous times before starting creation of the deck.

**Comment by Epix37** [comment]
Could you check your config.xml and tell me what these values are at?
```
  <ExportClearCheckYFixed>
  <ExportClearX>
  <ExportClearY>
```
You can find the config.xml via `options > other > tracker > open appdata folder`.

To work around this you could for now disabled `auto clear cards` in `options > other > exporting to hearthstone`.

**Comment by ChilledDragon** [comment]
<ExportClearCheckYFixed> 0.185
  <ExportClearX> 0.83
  <ExportClearY> 0.13

**Comment by Epix37** [comment]
Hm those should be correct. What's your resolution? You could try (w/o the tracking running) to slightly increase the ExportClearCheckYFixed to 0.19 or 0.195.

**Comment by ChilledDragon** [comment]
1920x1080, I'll try that and report back
