### ISSUE TITLE
new request improvement in deck presentation

### ISSUE THREAD

**Issue by Calioe** [Epix37/Hearthstone-Deck-Tracker#645]
Hello

Thanks again for the last improvement made, which are very good (possibility to have versionning on deck)
I would like to ask something which will be useful:
-to have creation date after the name of each date (it will help to find it)
-to have possibility to make filter or sort out by name or creation date , in the deck presentation on the main page (sorry for my bad english)....
I ask again but it will be great to see the server where the deck were played (NA, EU...)
thanks!!

**Comment by Epix37** [comment]
Hey,

I assume this is related to having "too many decks"? If so, #637 might solve this already.

About the EU, NA: You can add new tags (server specific) via EDIT > TAGS and tag your decks with those.

**Comment by Calioe** [comment]
Hey

no, I was speaking about the fact to add informations on decks, like the creation date in order to find easily the older or the newest deck imported ou created
And Tag is less automatic way to have it but thanks for the tip!

Thanks

**Comment by Epix37** [comment]
I'm forgetting about my own features here. You can change the sorting of the deck list via `DECKS > SORT / FILTER` and choose between name, winrate, last edited and tags. 

Last edited should be pretty close to what you are looking for.

**Comment by Calioe** [comment]
NICE!

Thanks:))))



> Message du 08/02/15 à 19h35
> De : "Epix" 
> A : "Epix37/Hearthstone-Deck-Tracker" 
> Copie à : "Calioe" 
> Objet : Re: [Hearthstone-Deck-Tracker] new request improvement in deck presentation (#645)
> 
> > I'm forgetting about my own features here. You can change the sorting of the deck list via DECKS > SORT / FILTER and choose between name, winrate, last edited and tags. 
> Last edited should be pretty close to what you are looking for.
—
> Reply to this email directly or view it on GitHub.


___________________________________________________________
Mode, hifi, maison,… J'achète malin. Je compare les prix avec Voila.fr http://shopping.voila.fr/

**Comment by Calioe** [comment]
Hello 

Thanks for last update!
i put you a copy of heartpwn:




In fact this is this kind of filters and sort out than I think very USEFUL (season , win rate, cards included, editing or creation date will be great...)

thks!!
> Message du 08/02/15 à 19h35
> De : "Epix" 
> A : "Epix37/Hearthstone-Deck-Tracker" 
> Copie à : "Calioe" 
> Objet : Re: [Hearthstone-Deck-Tracker] new request improvement in deck presentation (#645)
> 
> > I'm forgetting about my own features here. You can change the sorting of the deck list via DECKS > SORT / FILTER and choose between name, winrate, last edited and tags. 
> Last edited should be pretty close to what you are looking for.
—
> Reply to this email directly or view it on GitHub.


___________________________________________________________
Mode, hifi, maison,… J'achète malin. Je compare les prix avec Voila.fr http://shopping.voila.fr/

**Comment by Cu8eR** [comment]
@Epix37 - you have added region detection system for reseting max daily gold progress (100 g/day) - maybe you could add tagging for a region where the game was played.

**Comment by Epix37** [comment]
Games already have a region property.
