### ISSUE TITLE
Export to Hearthstone doesn't work

### ISSUE THREAD

**Issue by zeetto** [Epix37/Hearthstone-Deck-Tracker#646]
I have the resoulution on 1600x900 (screen 1980x1080) everytime it "clicks" on a card to add it, it misses with half an inch or so. How do fix it? :/

**Comment by Epix37** [comment]
It just tied those settings and it seems to work no problem.

Are you using the latest version? I can see this happening if you started v0.8.0 once but then went back to v0.7.x.

**Comment by zeetto** [comment]
I use the v0.8.0 i've never used the older version

**Comment by Epix37** [comment]
Is there just cards missing or does it export zero cards?
Does clearing existing cards in deck and searching for cards work?
If so, please check what the following values in the config.xml (`options > other > tracker > open appdata folder`) are set to:
```
  <ExportCard1X>
  <ExportCard2X>
  <ExportCardsY>
```

**Comment by zeetto** [comment]
this is my info: 
 <ExportCard1X>0.04</ExportCard1X>
  <ExportCard2X>0.2</ExportCard2X>
  <ExportCardsY>0.168</ExportCardsY>

**Comment by Epix37** [comment]
That looks correct.

>Is there just cards missing or does it export zero cards?
Does clearing existing cards in deck and searching for cards work?

**Comment by zeetto** [comment]
If you mean in the client of deck tracker, then yes. I can also import from web and edit in my decks, i even use it when i play to keep track of my games. But it just won't export decks into hs, because it fails to click on the cards. It does click, but just sligthy above where it is supposed to do it. It can also type in the correct name.

**Comment by Epix37** [comment]
That's weird.

Try (without the tracker running) to set the ExportCardsY value in the config to 0.2. This is % of screen from the top, so 20% of the screenheight, from the top. If that's not enough try increasing it further.

**Comment by zeetto** [comment]
Cool, now it can export again, but i still have a little problem where it sometimes misses 3-5 cards

**Comment by Epix37** [comment]
Maybe try lowering the speed in `options > other > exporting`

**Comment by zeetto** [comment]
It works perfectly now xD

**Comment by Epix37** [comment]
:+1:
