### ISSUE TITLE
The New ("deck history") panel...

### ISSUE THREAD

**Issue by FenrisWolffe** [Epix37/Hearthstone-Deck-Tracker#647]
Has made the overall tracker *quite* large onscreen when importing or editing. Is there a way to resize/hide panels?

Also, in stats, a "versions/all toggle would be cool.

**Comment by Epix37** [comment]
I'm currently working on separating arena runs from constructed decks. For that the history panel has to go anyway so I will add a way to also hide in (by default w/o versions) for constructed decks.
