### ISSUE TITLE
New deck picker 

### ISSUE THREAD

**Issue by Epix37** [Epix37/Hearthstone-Deck-Tracker#648]
![screenshot 2015-02-08 11 34 33](https://cloud.githubusercontent.com/assets/7737910/6096225/98f25206-af86-11e4-870b-89fd5facbfcd.png) ![screenshot 2015-02-08 11 34 40](https://cloud.githubusercontent.com/assets/7737910/6096227/9ac08832-af86-11e4-8e92-53046dcae908.png)

What do you guys think about the general idea? (**it's not done**)
* Easier to switch between classes
* Allows to display multiple (selected) classes
* Win% of class gets lost (I don't really want to put that on the icons) but you can see that in stats anyway.
* I will change the "deck item" to something that fits the metro or hearthstone style a bit better (ideas are welcome)

(yes, my deck names are superb!)

**Comment by Epix37** [comment]
This is starting to look half decent (and work)

![screenshot 2015-02-08 17 22 05](https://cloud.githubusercontent.com/assets/7737910/6097259/68841ed4-afb7-11e4-944d-96b1eb71b3c5.png)

**Comment by Elitesparkle** [comment]
> What do you guys think about the general idea? (it's not done)

I like the way it is currently but I'll tell you my opinion about this version anyways.

> - Easier to switch between classes

Did you consider to put the bar to select classes horizontally, above the list?

> - Allows to display multiple (selected) classes

I think it looks better if you don't make the icons bigger when they aren't selected.

> - Win% of class gets lost (I don't really want to put that on the icons) but you can see that in stats anyway.

You could add percetages and, why not, win-loss numbers below each icon or, if you keep it vertical, on their side.

At the end of each deck line, you should add the win-loss numbers as well, even if you don't end up releasing this new layout.

**Comment by Epix37** [comment]
>Did you consider to put the bar to select classes horizontally, above the list? 

That would mean the min-width of the window thing does towards the 1000px mark. Way too wide. I working on getting it even slimmer again.


>I think it looks better if you don't make the icons bigger when they aren't selected.

I'm not 100% on that one either, BUT:
* so much space around them looks awkward
* the selection highlighting makes it migh clearer which ones are selected that it just being slightly bigger
* imagine it's a button you're pushing down :)

> You could add percetages and, why not, win-loss numbers below each icon or, if you keep it vertical, on their side.

I want to keep that bar as small as possible. IMO it's just not necessary if you can see it with a few click in the stats. Not really information you need to have available at any second.

>At the end of each deck line, you should add the win-loss numbers as well, even if you don't end up releasing this new layout.

I tried this a few months ago, it get's problematic once the number of games on a deck are too high. "100 - 100" just doesn't fit anywhere.  
I *do* however plan add this to arena runs, which will be separate from constructed decks in the future. Separating arena runs is also the main reason I re-did this in the first place. It's just a huge mess otherwise.

**Comment by Epix37** [comment]
Released with v0.9.0.

Feel free to still leave feedback.

**Comment by dvide** [comment]
Definite improvement but not sure about the ALLCAPS. I started using CamelCase to save room, because deck names can't be longer than 24 chars in game. Now my MIDRANGEECHOMAGE (MidrangeEchoMage) reads more like MIDRANGEE CHO MAGE to my brain! :D

**Comment by Elitesparkle** [comment]
@Epix37, you could keep them uppercase on the tracker but make them
lowercase when exporting to Hearthstone.
Il 09/feb/2015 16:45 "Jack Whitehead" <notifications@github.com> ha scritto:

**Comment by Epix37** [comment]
The exporting part was accidental, I'll fix that, thanks. 

About allcaps.. I'm gonna make it an option :). Caps fits the metro stuff better.

**Comment by Epix37** [comment]
Uhm.... @Elitesparkle: There is no uppercase when exporting for me. Does that happen with all decks for you?

**Comment by Elitesparkle** [comment]
I have just answered considering what he said.

Now that I've used it, I can say it's working like before.

> Uhm.... @Elitesparkle: There is no uppercase when exporting for me. Does
that happen with all decks for you?

**Comment by dvide** [comment]
@Elitesparkle I wasn't saying that it exported as uppercase (didn't try it). Just meant that I stopped putting spaces in my deck names to save characters, and started using CamelCase to distinguish words.

@Epix37 Don't worry about implementing this option just for me. I've put spaces back in the deck names and it's fine. I don't care about it that much. Only do it if enough other people really want it too.
