### ISSUE TITLE
Crash when opening the tracker

### ISSUE THREAD

**Issue by Elitesparkle** [Epix37/Hearthstone-Deck-Tracker#651]
I tried to open the tracker, but it crashed.
I tried 5-6 times then it opened. I noticed it didn't try to update, even if there is version 0.9.0 available.
I closed it and tried to open it again, but it crashed.

Crash report here:
http://pastebin.com/Q7iwWC5x

**Comment by ralphon** [comment]
Same problem. 
Crash report here:
http://s000.tinyupload.com/?file_id=90161509825822416560

**Comment by Epix37** [comment]
That is with v0.8.0 right? Probably minimized to tray?

Does it work again if you download 0.9.0 manually?

**Comment by Elitesparkle** [comment]
> That is with v0.8.0 right? Probably minimized to tray?

Yes.

> Does it work again if you download 0.9.0 manually?

I didn't want to update manually to give you some information about this problem.

By the way, I had it open and, when I started Hearthstone, the update window appeared.
Now updating.

**Comment by wordbearer** [comment]
I have the same problem, with a quite similar crash log (http://pastebin.com/6CZd609d) .

> That is with v0.8.0 right? Probably minimized to tray?

It occured with v0.8.0 and was not minimized to tray (autostart on boot)

> Does it work again if you download 0.9.0 manually?

Works perfectly fine again, thanks :)

**Comment by Elitesparkle** [comment]
It happened again, even after the update.

**Comment by Elitesparkle** [comment]
I have some new information about this.

I wasn't able to open the tracker so I figured out a solution.
Open the "config.xml" file and set the "CheckForUpdates" string to "false".

It will help you to narrow down the possibilities.
I guess it's something related to the automatic update.

**Comment by Epix37** [comment]
It is happening because of this: e73d347
I modified the behaviour with v0.9.0 0abcde7 but the core issue (ActivateWindow()) still remains. I'll remove that for now..

**Comment by Epix37** [comment]
Alright I got this sorted out now! The issue was that the window was not fully initalized when the windowstate was set. Since neither waiting for _initialized nor IsLoaded does the trick, I added a 10 sec delay before the message. Should to it.

**Comment by Elitesparkle** [comment]
> Alright I got this sorted out now! The issue was that the window was not fully initalized when the windowstate was set. Since neither waiting for _initialized nor IsLoaded does the trick, I added a 10 sec delay before the message. Should to it.

Can't you check if not null instead of using a timer?

**Comment by Epix37** [comment]
That's actually an issue with MahApps (the metro-style framework I'm using), not my software. I don't have access to element throwing the null exception.

**Comment by ralphon** [comment]
Oh wow. I really didn't understand a single word in this conversation at all. Could someone just explain in a simpler way please? Much appreciated. :)

**Comment by Elitesparkle** [comment]
> Oh wow. I really didn't understand a single word in this conversation at all. Could someone just explain in a simpler way please? Much appreciated. :)

If you can't open the software, you need to manually modify the configuration file.

How:
- Press "Windows logo key + R".
- Write "%appdata%/HearthstoneDeckTracker" and confirm.
- In that directory you'll see a file named "config.xml".
- Open it with a text editor (e.g. Notepad).
- Find this line: ```<CheckForUpdates>true</CheckForUpdates>```.
- Set it to "false", close the software, save the file and then restart the tracker.

**Comment by Epix37** [comment]
I would not suggest turning off the update check.

Simply update to the latest version manually: https://github.com/Epix37/Hearthstone-Deck-Tracker/releases and turn off "minimize to tray" until the next update.

**Comment by Epix37** [comment]
should be fixed with v0.9.3
