### ISSUE TITLE
Old HearthStats games assigned to wrong deck

### ISSUE THREAD

**Issue by dvide** [Epix37/Hearthstone-Deck-Tracker#652]
This happened to my mum, who used to use HearthStats before HDT added stat tracking.

She set up her HearthStats sync but told it not to download her old HearthStats decks. It downloaded and assigned the approx. 2000 old games that were stored on her HearthStats account to her 'Strifecro MechMage Boom' deck in HDT. Not sure why it chose that deck.

![untitled](https://cloud.githubusercontent.com/assets/180188/6111288/9ea627f0-b07f-11e4-81bf-6f6ff35bb499.jpg)
![untitled2](https://cloud.githubusercontent.com/assets/180188/6111290/a3962c24-b07f-11e4-9488-be593bce4548.jpg)

**Comment by Epix37** [comment]
Do you still have the session running? Could you upload the hdt_log.txt from the Logs folder for me?

**Comment by dvide** [comment]
Damn sorry, unfortunately we closed it since. We also did another full sync and downloaded the old decks on HearthStats this time, and it seemed to assign the old games to those decks correctly but the 2000 odd games in 'Strifecro MechMage Boom' still remained there too. In other words there were duplicate entries for each old game, one assigned to the correct deck and one to 'Strifecro MechMage Boom'. We deleted them all from 'Strifecro MechMage Boom' and everything seems fine now, other than maybe a few other bugs which I'll report in other threads.

**Comment by Epix37** [comment]
I think I got this fixed for the next release. 

What should do **then** (i.e. not yet): 

1) logout of hearthstats in the tracker
2) go to stats, select all the matches that dont belong there
3) be sure you logged out
4) press delete
5) matches shouldn't sync again

**Comment by dvide** [comment]
Okay. Hope it works (don't think we'll be able to test the fix). As I say we've already deleted those extra games and it seems ok now. Hopefully it won't cause any issues that we didn't logout first or wait for the update :)

**Comment by Epix37** [comment]
uhm... it maaay have deleted all those matches on hearthstats now..

**Comment by dvide** [comment]
It didn't, thankfully (though she wouldn't have minded anyway).

**Comment by Epix37** [comment]
well.. uh.. good, lol.
