### ISSUE TITLE
Arena/Constructed bar issue

### ISSUE THREAD

**Issue by Elitesparkle** [Epix37/Hearthstone-Deck-Tracker#653]
When I select Arena, Arena decks are listed and Constructed decks aren't but an Arena deck is missing.
When I select Constructed, Constructed decks are listed and Arena decks aren't, but the one missing when selecting Arena is there.

**Comment by Epix37** [comment]
Am I correct in assuming the arena deck has no matches or not exclusively arena matches on it?

**Comment by Elitesparkle** [comment]
No, it's impossible it happened to only one deck for each class.
There's one Arena deck in the Constructed section for each class.

There is another issue.
When a wrong deck is detected and there is one of those new "filters" up
(e.g. Arena), you can't chose a deck that's from the other category (e.g.
Constructed) because it won't be listed in the window appearing.
Il 09/feb/2015 18:53 "Epix" <notifications@github.com> ha scritto:

**Comment by Elitesparkle** [comment]
> Am I correct in assuming the arena deck has no matches or not exclusively arena matches on it?

You are right.
There are some games with the value "None" in the Mode column associated to those decks.

**Comment by Epix37** [comment]
Ok.

That is not really something I can correct automatically on old games. 
You *can* manually edit the PlayerDecks.xml and set `<IsArenaDeck>false</IsArenaDeck>` to `<IsArenaDeck>true</IsArenaDeck>` on the affected decks. That's the only way I can think of at the moment.

**Comment by Elitesparkle** [comment]
> That is not really something I can correct automatically on old games.
You can manually edit the PlayerDecks.xml and set <IsArenaDeck>false</IsArenaDeck> to <IsArenaDeck>true</IsArenaDeck> on the affected decks. That's the only way I can think of at the moment.

I know but the issue seems different.

I've just noticed those games don't belong to the Arena they are associated to.
Some are even from the wrong class. I can see it from the cards played in the game history.
They have been linked to them somehow with the latest update, maybe.

The games causing this issue are all dated between 26 and 28 January 2015, except one that's dated 18 December 2014.

Can you figure out how can it be?
Maybe something related to deck names management.

**Comment by Epix37** [comment]
Here is how I check if a game is an arena game: 
```
private bool? _isArenaDeck;
public bool IsArenaDeck
{
	get { return _isArenaDeck ?? (_isArenaDeck = CheckIfArenaDeck()) ?? false; }
	set { _isArenaDeck = value; }
}
public bool? CheckIfArenaDeck()
{
	return !DeckStats.Games.Any() ? (bool?)null : DeckStats.Games.All(g => g.GameMode == GameMode.Arena);
}
```

`_isArenaDeck` gets ignoed as long as it's null, no not explicitly set by anything. This the value in the PlayerDecks.xml. It get's either set when you create a new arena run (new with v0.9.0) or when CheckIfArenaDeck, which checks if all associated games are arena games, returns true or false. If there is no games it stays undetermined. If it's set (IsArenaDeck is the PlayerDecks.xml has a value), no further checks are made.

To IsArenaDeck in the PlayerDecks.xml will overwrite what the tracker determined.

**Comment by Elitesparkle** [comment]
I guess the decks haven't been labeled as Arena decks since there were those games associated to them.

I'm manually changing the values since there were only 8 affected games.
I still don't get why they weren't labeled as Arena games.

**Comment by Epix37** [comment]
Because they have matches with mode "None" associated with them. A "old" deck is only considered an arena deck if it has __exclusively__ arena matches on it.

**Comment by Elitesparkle** [comment]
> Because they have matches with mode "None" associated with them. A "old" deck is only considered an arena deck if it has exclusively arena matches on it.

Yes, I've got that part but why there are games not related to a deck linked to it?

**Comment by Epix37** [comment]
What do you mean not related to a deck?

**Comment by Elitesparkle** [comment]
> What do you mean not related to a deck?

For example, there is a Druid deck named "Arena 14-01 16:00" that contains 8 games.
5 of them are dated 14 January and they are, in order, 2 wins and 3 losses.
3 of them were labeled as "None", don't have opponent's names and are dated 27 Jaunary.

**Comment by Epix37** [comment]
So the question is how the games got in there in the first place?
No idea :).Could be some weird hearthstats syncing issue with the deck being considered constructed..? not sure. The date doesn't make much sense to me.

**Comment by Elitesparkle** [comment]
> So the question is how the games got in there in the first place?
No idea :).Could be some weird hearthstats syncing issue with the deck being considered constructed..? not sure. The date doesn't make much sense to me.

Syncing is off.

It's clear that the last 3 games don't belong to that Arena run since the first 5 games make it a 2-3 run, so it's over.

How could it be that those games have the wrong deck set?

**Comment by Epix37** [comment]
I don't know. Maybe you had the deck selected at some point. Not really an important issue if it's not happening continously IMO.

**Comment by Elitesparkle** [comment]
> I don't know. Maybe you had the deck selected at some point.

It could be.

> Not really an important issue if it's not happening continously IMO.

Of course.
I was just trying to understand what happened.

**Comment by Elitesparkle** [comment]
Ok, I've deleted those strange games and changed deck to Arena mode manually.

>  There is another issue. When a wrong deck is detected and there is one of those new "filters" up (e.g. Arena), you can't chose a deck that's from the other category (e.g. Constructed) because it won't be listed in the window appearing.

What about this?

**Comment by Epix37** [comment]
Will be fixed, yes.

**Comment by anonymous555** [comment]
Some older decks have the arena tag.  Could use that

**Comment by Epix37** [comment]
73dfdb7 should fix the issue where the deck selection dialog doesn't contain filtered decks.
