### ISSUE TITLE
Two other HearthStats sync bugs

### ISSUE THREAD

**Issue by dvide** [Epix37/Hearthstone-Deck-Tracker#654]
Bug 1:
![untitled](https://cloud.githubusercontent.com/assets/180188/6112125/efcdc3ee-b085-11e4-80cf-9101f8cae92c.jpg)
Every time it syncs it asks about these decks again. If we click Sync here, it'll ask about the same decks again next time. These are all decks that weren't originally on HearthStats, and the decks are now on HearthStats.

Bug 2:
![untitled2](https://cloud.githubusercontent.com/assets/180188/6112126/efce80c2-b085-11e4-83b5-40e673f332af.jpg)
![untitled3](https://cloud.githubusercontent.com/assets/180188/6112127/efd2de24-b085-11e4-86eb-2292c844dac7.jpg)
Every time it syncs it tries to upload these 5 games again. As you can see from the log, these are friendly games. I don't think HearthStats has a way to add friendly games so I guess that's why it fails on these?

Here's the log: http://pastebin.com/rQq0DVQ0

**Comment by Epix37** [comment]
1. are all matches with versions I assume? that is already solved and will be fixed with the next update shortly. 

2. being worked on right now :)

**Comment by dvide** [comment]
Ah yes you're right. Those are all decks with versions :)

**Comment by Epix37** [comment]
new version is out, should fix 1. (you have to sync them again)

2. is a serverside issue and will be fixed soon
