### ISSUE TITLE
Stats display for deck not correct

### ISSUE THREAD

**Issue by MarioZG** [Epix37/Hearthstone-Deck-Tracker#655]
It shows all games against each version.

**Comment by Epix37** [comment]
What version, synced? from where to where? Is the total (ALL) correct?

**Comment by MarioZG** [comment]
Latest version.

 

I don’t use sync at all.

 

Fix at my fork: https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/cd2bbb1ceea7b430e21337d5a66dc06365c7b57e

**Comment by Epix37** [comment]
Perfect, thank you.

**Comment by Epix37** [comment]
fixed with v0.9.3
