### ISSUE TITLE
Deck Tracker Crash when opening

### ISSUE THREAD

**Issue by zucca92** [Epix37/Hearthstone-Deck-Tracker#656]
Hi , first than all thx u fopr this program . This is my first time i tru to use it , when i open it ( from Hearthstone Deck Tracker.exe ofc ) it crash . i tried with v0.9.0 , 0.9.1 and 0.9.2 . How i can fix it ? 

This is the details of the problem 

Nome evento problema:	APPCRASH
  Nome applicazione:	Hearthstone Deck Tracker.exe
  Versione applicazione:	0.1.0.0
  Timestamp applicazione:	54d8bcdd
  Nome modulo con errori:	KERNELBASE.dll
  Versione modulo con errori:	6.1.7601.18229
  Timestamp modulo con errori:	51fb1116
  Codice eccezione:	e0434352
  Offset eccezione:	0000c41f
  Versione SO:	6.1.7601.2.1.0.256.1
  ID impostazioni locali:	1040
  Informazioni aggiuntive 1:	0a9e
  Ulteriori informazioni 2:	0a9e372d3b4ad19135b953a78882e789
  Ulteriori informazioni 3:	0a9e
  Ulteriori informazioni 4:	0a9e372d3b4ad19135b953a78882e789

Leggere l'informativa sulla privacy online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0410

Se l'informativa sulla privacy online non è disponibile, leggere quella offline:
  C:\Windows\system32\it-IT\erofflps.txt

**Comment by Epix37** [comment]
#370 should have the fix for you

**Comment by zucca92** [comment]
ok , thx u . it's working now

**Comment by Epix37** [comment]
:+1:
