### ISSUE TITLE
All versions of old HearthStats decks downloaded as v1.0

### ISSUE THREAD

**Issue by dvide** [Epix37/Hearthstone-Deck-Tracker#658]
My mum has this old Zoolock deck on HearthStats with versions. As you can see on HearthStats it just has major version numbers v1, v2, etc (because it used to work that way; not sure if it still does).

When this deck was downloaded to HDT, it created all 6 versions as v1.0:
![untitled](https://cloud.githubusercontent.com/assets/180188/6113610/8d937de4-b090-11e4-8a6e-6b49355a1f98.jpg)
![untitled2](https://cloud.githubusercontent.com/assets/180188/6113611/8d97cb74-b090-11e4-8c62-8cd9a909a354.jpg)

**Comment by Epix37** [comment]
Could you email me the PlayerDecks.xml and DeckStats.xml?

**Comment by Epix37** [comment]
Oh, also: is the order of the versions correct?

**Comment by dvide** [comment]
Just had a closer look. All versions are identical, both on HearthStats and HDT (despite the deck history tab showing changes, which I assume are correct but I cannot verify the order). I don't think they were originally all identical on HearthStats, so I think HDT messed up when downloading them, and then reuploaded the messed up versions, overwriting the original ones on HearthStats? 

I've emailed those files you asked for.

**Comment by Epix37** [comment]
possibly related to #662?

**Comment by dvide** [comment]
Maybe. It's unfortunate that we won't be able to test the fix to see if it also fixes this issue, since we won't be able to recreate the state her HearthStats account was in originally. Unless you can think of a way?

BTW: HDT isn't prompting me to update to 0.9.3 (after restarting it). Should I just give it a little longer?

**Comment by Epix37** [comment]
oops I forgot to update the new file it checks, thanks lol
