### ISSUE TITLE
Problems with export to Hearthstone. Probably wrong encoding. [RUS]

### ISSUE THREAD

**Issue by MiLorDrs** [Epix37/Hearthstone-Deck-Tracker#659]
Firstly, this is a great app. Thanks!
When I use the Russian language in the game and in the application, the application does not export the deck.
![image](https://cloud.githubusercontent.com/assets/6084244/6115317/dc6098e2-b0b5-11e4-8129-6e792324019b.png)

P.S. Also, I'm really looking forward to the version for OS X. Thanks :)

**Comment by Epix37** [comment]
You're welcome :)

To fix the exporting: enable `options > other > exporting > paste names from clipboard`

FYI: I'm not the one developing the OS X version ;)

**Comment by MiLorDrs** [comment]
It's works! Thank you ~^_^~

**Comment by Epix37** [comment]
:+1:
