### ISSUE TITLE
Fetuare Request: Secrets

### ISSUE THREAD

**Issue by Gunpowderchant** [Epix37/Hearthstone-Deck-Tracker#660]
I love that when a player has a secret it shows you all the posible secrets, but it would be nice to be able to tick them off, once you try a trigger for one of them and nothing happend,

**Comment by Epix37** [comment]
enable `options > general > overlay > 'extra features'`:)

**Comment by Gunpowderchant** [comment]
Thank you, im an idiot.

**Comment by Gunpowderchant** [comment]
Thank you, im an idiot.

2015-02-09 18:09 GMT-03:00 Epix <notifications@github.com>:

**Comment by Epix37** [comment]
There is so much stuff in the options, no way to know everything :). No worries!
