### ISSUE TITLE
Missing All Local Stats After Deleting Decks from Hearthstats

### ISSUE THREAD

**Issue by Fyrestrom** [Epix37/Hearthstone-Deck-Tracker#664]
They are all gone locally. No where to be found. The only decks that still have stats were ones that had not been synced. Very disappointing.

**Comment by Epix37** [comment]
Where and how exactly did you delete decks?

**Comment by Fyrestrom** [comment]
Hearthstats > Delete Selected Deck

I wanted to clear everything and resync. So I selected each deck and used the above command.

**Comment by Fyrestrom** [comment]
All of the decks are still there, they all have dashes in the win rates now.

**Comment by Epix37** [comment]
Good news: stats are not gone. Working on a fix.

**Comment by Epix37** [comment]
This should fix it: http://www.mediafire.com/download/z8qqs2y04c104vv/Hearthstone_Deck_Tracker-v0.9.4PRE1.zip

Select a deck with missing stats, `HEARTHSTATS > DELETE SELECTED DECK`, restart tracker. Please let me know if that works for you.

**Comment by Fyrestrom** [comment]
Confirmed. Stats are back after following steps above.

**Comment by Epix37** [comment]
very good! sorry about that.
