### ISSUE TITLE
Sometimes not saving manually added games

### ISSUE THREAD

**Issue by dvide** [Epix37/Hearthstone-Deck-Tracker#665]
To reproduce:

Backup your HDT data folder and then clear it out (so you're starting from fresh). Open HDT and import this deck and save it: http://www.hearthpwn.com/decks/140918-natural-remedies

Manually add a new game in the Stats panel assigned to the Natural Remedies deck. Just leave the game details at default (Win vs Druid, etc.). Close and reopen HDT and the game you added should be gone.

**Comment by Epix37** [comment]
Finally an issue I don't need to panic over :). Fixed.

**Comment by dvide** [comment]
lol :+1:
