### ISSUE TITLE
Can't open Hearthstone Deck Tracker after version 0.8.0

### ISSUE THREAD

**Issue by Pand3m0nia** [Epix37/Hearthstone-Deck-Tracker#666]
Every release after 0.8.0 I try to open the program, but the "Loading" icon appears then I get a Windows message saying that Hearthstone Deck Tracker has stopped working.

Furthermore, since I've started using the program the Auto-update feature never seems to work, it always gives an error about creating a Temp directory and says I need to update manually.

Thanks

**Comment by Epix37** [comment]
I would suggest trying to reinstall the latest .NET Framework before we look any further.

For the updater issue: try  #454

**Comment by Pand3m0nia** [comment]
Thank you very much for your speedy reply. Changing the Permissions as mentioned in that link seemed to fix both the updating issue as well as the start-up issue.
