### ISSUE TITLE
Can't reopen the tracker from systemtray

### ISSUE THREAD

**Issue by mof990** [Epix37/Hearthstone-Deck-Tracker#667]
After the last update I can no longer open the tracker after minimizing it to the system tray.

**Comment by Epix37** [comment]
uuuh.. Windows 7?

Neither clicking nor right - show opens it?

**Comment by mkrain** [comment]
I have the same issue on windows 8.1.  I find that I have to close the program before I can maximize it but minimizing it again causes the same issue.

**Comment by mof990** [comment]
Windows 8.1. Right clicking - show doesn't work either.

**Comment by Epix37** [comment]
So you *can* get it open by trying to open it, then restart it? 

If not:  go to "%AppData%/HearthstoneDeckTracker" (Win+R, paste), open the `config.xml` and set `<MinimizeToTray>true</MinimizeToTray>` to `false`

**Comment by mof990** [comment]
To make it work I have to right click - exit and start the program again.

**Comment by Epix37** [comment]
Alright, thank you. As long as you can get it open at all you should be fine for a day I guess? :)
Should be fixed now and there will probably be an update tomorrow night (~24 hours from now)

**Comment by zminin** [comment]
Same issue here on windows 7 waiting for patch

**Comment by 305jeff** [comment]
Good morning! Status update on this? I have disabled minimize to system tray but do miss it a bit! Thanks.

**Comment by Epix37** [comment]
I should have time to work on this again mid next week, so some time then.

**Comment by zminin** [comment]
Thanks you guys are great, tracker helped me get to legendary for the first time yesterday.
Do you think you could implement better sorting in stats though?

**Comment by Epix37** [comment]
Please let me know if there's still any issues with the latest build here: https://github.com/Epix37/HDT-Test/releases
