### ISSUE TITLE
Crashes on start (>v0.9.0), when run without admin permissions

### ISSUE THREAD

**Issue by WizardBlack** [Epix37/Hearthstone-Deck-Tracker#668]
Log Name:      Application
Source:        Application Error
Date:          10/02/2015 22:35        :22
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Win7PC
Description:
Faulting application name: Hearthstone Deck Tracker.exe, version: 0.1.0.0, time stamp: 0x54da54ae
Faulting module name: KERNELBASE.dll, version: 6.1.7601.18409, time stamp: 0x53159a86
Exception code: 0xe0434352
Fault offset: 0x0000c42d
Faulting process id: 0x3204
Faulting application start time: 0x01d04581db03a3ed
Faulting application path: C:\Program Files (x86)\Hearthstone Deck Tracker\Hearthstone Deck Tracker.exe
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll
Report Id: 1913e3bc-b175-11e4-9142-d05099097dda
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-02-10T22:35:22.000000000Z" />
    <EventRecordID>23766</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Win7PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Hearthstone Deck Tracker.exe</Data>
    <Data>0.1.0.0</Data>
    <Data>54da54ae</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>6.1.7601.18409</Data>
    <Data>53159a86</Data>
    <Data>e0434352</Data>
    <Data>0000c42d</Data>
    <Data>3204</Data>
    <Data>01d04581db03a3ed</Data>
    <Data>C:\Program Files (x86)\Hearthstone Deck Tracker\Hearthstone Deck Tracker.exe</Data>
    <Data>C:\Windows\syswow64\KERNELBASE.dll</Data>
    <Data>1913e3bc-b175-11e4-9142-d05099097dda</Data>
  </EventData>
</Event>

**Comment by WizardBlack** [comment]
Just found it works OK when I run as admin.

**Comment by Epix37** [comment]
This seems to happen now for some reason.. not sure why. If anyone has ideas, please tell me.

**Comment by dvide** [comment]
It's the hdt_log.txt file. You can't write to Program Files directories unless the app is run as admin.

**Comment by Epix37** [comment]
ooh, right. thank you.

**Comment by dvide** [comment]
I think it's considered bad practice to output anything to the program's directory, so that would also include the deck screenshots and XML exports. In this case, because there is no installer it doesn't matter so much. It requires that people unzip to Program Files before they'll see this problem. But I think maybe outputting the screenshots / XML exports somewhere else is a good idea too. I think it should actually present the user with a file save dialog, so the user can choose where he/she wants to save them on a case by case basis.

**Comment by dvide** [comment]
Actually, thinking about it, there might be a problem with the updater too? But if you attempt to run Updater.exe with elevated permissions, that will probably solve it. (Then the user should be presented with a UAC dialog before it updates.)

**Comment by Epix37** [comment]
Yes, you are probably right. Thank you for the PRs!
