### ISSUE TITLE
Can't add more than 2 of a card in Arena

### ISSUE THREAD

**Issue by Pand3m0nia** [Epix37/Hearthstone-Deck-Tracker#676]
I apologise if this has been already mentioned, I've looked through the recent issues and couldn't find. I decided to use the program for one of my Arena runs, but unfortunately it won't let me add a 3rd copy of card (in this case it was Starfall).

Thanks

**Comment by mvy** [comment]
This used to work, at least when importing from Hearthstone.

Is there a regression?

On 11 February 2015 at 16:48, Pand3m0nia <notifications@github.com> wrote:

> I apologise if this has been already mentioned, I've looked through the
> recent issues and couldn't find. I decided to use the program for one of my
> Arena runs, but unfortunately it won't let me add a 3rd copy of card (in
> this case it was Starfall).
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/676>.
>



-- 
Dr. Yves "M'vy" Stadler
Ph.D in IT, Security and Networks

**Comment by Pand3m0nia** [comment]
I used the "Import from Last Game" option and then manually added the remaining cards if that helps.

**Comment by mvy** [comment]
Isn't there an "import from arena" button ? I'm not at home so can't test
myself right now.

On 11 February 2015 at 16:53, Pand3m0nia <notifications@github.com> wrote:

> I used the "Import from Last Game" option and then manually added the
> remaining cards if that helps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/676#issuecomment-73904672>
> .
>



-- 
Dr. Yves "M'vy" Stadler
Ph.D in IT, Security and Networks

**Comment by Pand3m0nia** [comment]
There is, but it doesn't seem to work all that well, it wants to add things like "Bear Form", :Summon a Panther", and "The Coin" to the deck.

**Comment by mvy** [comment]
Ok, I just tested with the lastest version. 

New > Class > Arena Run 

Then you can add as much of a card as you wish.

The "From Game: Arena" you need to go to the arena screen then leave, then use the import function. You might have to do this in an empty "arena run" deck as well.

**Comment by Pand3m0nia** [comment]
Hmmm, it seems to randomly work now, I don't know what I did to change that.

**Comment by Epix37** [comment]
You have to choose "arena run" when creating a new deck to be able to add more than 2 of a card.
