### ISSUE TITLE
Decks Missing After Editing Tags

### ISSUE THREAD

**Issue by k128** [Epix37/Hearthstone-Deck-Tracker#678]
I noticed that many of my constructed decks were under the Arena tab.  I checked the tags and they had no tags set, so I set them to constructed.  They then disappeared and do not show up under any of the tabs.  The only decks now visible under the Constructed tab are the arena decks that were misplaced there and which have been tagged as Arena.

Edit: Tested and tagging decks as Constructed under the Arena tab makes them disappear just like it did under the Constructed tab.  Tagging as Arena does not cause the issue.  Disappearance occurs whenever decks are tagged as Constructed or Favorite UNLESS already tagged as Arena.

**Comment by Epix37** [comment]
Tags don't affect whether decks are categorized "constructed" or "arena". The types of matches on them do. I'm gonna add a way to "convert" in both directions for cases like this.

I would guess the reason you no longer see them is because you're filtering for certain tags? Try `DECKS > QUICK FILTER > ALL`

**Comment by k128** [comment]
Tried DECKS>QUICK FILTER>ALL.  Still not showing them under any tab.

**Comment by k128** [comment]
It looks like the tag filtering was the issue.  That means I'm instead having two less severe issues:
1.  Quick Filter -> All isn't working
2.  Decks are being miscategorized

**Comment by Epix37** [comment]
The quickfilters sometimes don't react. Did changing the filter in `DECKS > SORT / FILTER` work then? 

Your decks that are miscategorized, Do the arena decks have non-arena games on them and constructed decks arena games?  (Either way, as I said: I'll add a way to change switch decks between arena and constructed)

**Comment by k128** [comment]
Yeah, DECKS > SORT / FILTER worked.  You're right, the quick filter is finicky.  It appears that the arena decks under constructed do have ranked games under them, though I have never actually played ranked with those decks, so it must have been games where the auto-detect didn't switch the deck or something.
