### ISSUE TITLE
Game Stats now in TRIPLICATE!

### ISSUE THREAD

**Issue by GaelicSmash** [Epix37/Hearthstone-Deck-Tracker#679]
As per title, since the last update every match is recorded in triplicate when I view the stats. (On looking into it further it seems its just when I select  "Overall" & "Games" together).

**Comment by Epix37** [comment]
Does that happen with all decks?

**Comment by GaelicSmash** [comment]
I think ive sussed out what was happening. As I changed a card in the deck,
id then save it as V1.1 etc. Then when playing with the new deck it
recorded in stats for each copy of that deck, inspite of only playing with
1. Im assuming this was what was causing it as I did have 3 versions of the
same deck (original & 1.1,1.2). As soon as I deleted the original & 1.1 I
noticed its only recording 1 lot in "Stats" again, like its supposed to.

Btw, thanks LOADS for your reply & this awesome app dude. Seriously wicked
little tool !

**Comment by dvide** [comment]
Sounds like it might be related to the 0.9.5 fix.

@GaelicSmash Did you use the 'SAVE AS NEW (v1.0)' option to create these decks? I tested that out on 0.9.4 and whenever you had a game assigned to one of the decks it would also assign it to the other, so they would appear twice in Overall Games.

@Epix37 To replicate: Download 0.9.4 and use a fresh config. Import [Natural Remedies](http://www.hearthpwn.com/decks/140918-natural-remedies) and save the deck. Edit Natural Remedies and call it 'Natural Remedies 2' and then use SAVE AS NEW (can also change some cards if you want but it doesn't matter). Edit Natural Remedies again and call it 'Natural Remedies 3' and then click SAVE AS NEW again. Now manually create a game assigned to Natural Remedies and it should show up triple in Overall Games, one for each deck.

**Comment by GaelicSmash** [comment]
No I used "Save as V1.1, 1.2 etc.

**Comment by dvide** [comment]
@GaelicSmash How did you delete v1.0 and v1.1 then? I thought you couldn't delete deck versions?

**Comment by GaelicSmash** [comment]
???  Yeah,  deleted 1.1 &  1.2. That's the only way I found out the
"Triplicate" issue in my op was related to these versions

**Comment by dvide** [comment]
Sorry, I'm just trying to understand. You said originally: '... I did have 3 versions of the
same deck (original & 1.1,1.2). As soon as I deleted the original & 1.1 ...'

That to me implies you deleted 1.0 and 1.1. Now you're saying you deleted 1.1 and 1.2. But I still don't understand how that's possible because as far as I'm aware, there's no function yet to delete a version of a deck, only the whole thing (all 3 versions). Did you delete the whole thing and then recreate one of the versions as a brand new deck?

**Comment by dvide** [comment]
Ok just want to make sure of something. Are you saying you had your 3 versions of the same deck set up like this?

![untitled2](https://cloud.githubusercontent.com/assets/180188/6180597/2fc35af4-b31f-11e4-9811-7aa08a30b705.jpg)

Or like this (where you choose which version you want to play from the dropdown list):

![untitled](https://cloud.githubusercontent.com/assets/180188/6180595/29cec44e-b31f-11e4-8eda-a2d466e25572.jpg)

**Comment by GaelicSmash** [comment]
The top picture

**Comment by dvide** [comment]
Okay thanks, that's helpful. I think this bug has already been fixed then with 0.9.5.
