### ISSUE TITLE
Question on the Code

### ISSUE THREAD

**Issue by greece57** [Epix37/Hearthstone-Deck-Tracker#682]
I'm just trying to read myself into the Code have I have 2 questions for the beginning.

If I want to implement a 'board' - so the Program really knows whats happening on the board - would the Game-Class be the right place to put the Board-Object in?

Do you think it is possible to extend the HsDT in this way or will I face some problems trying to do it?

**Comment by mvy** [comment]
The board is two lists of ordered cards. So basically it's the same as a
deck or a hand, but there can be more card type and no more than 7 (??) in
it.

On 12 February 2015 at 15:55, Niko <notifications@github.com> wrote:

> I'm just trying to read myself into the Code have I have 2 questions for
> the beginning.
>
> If I want to implement a 'board' - so the Program really knows whats
> happening on the board - would the Game-Class be the right place to put the
> Board-Object in?
>
> Do you think it is possible to extend the HsDT in this way or will I face
> some problems trying to do it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/682>.
>



-- 
Dr. Yves "M'vy" Stadler
Ph.D in IT, Security and Networks

**Comment by greece57** [comment]
Oke yes thats right.

But is it possible to really let HsDT understand what is happening on the board? For example if a minion attacks/kills another minion

**Comment by Epix37** [comment]
What do you mean by "understand"?

**Comment by greece57** [comment]
I'm thinking of adding sth like a 'best move calculator' (just as project in my free time - I don't know if I can build sth that will really work)

So by understand I mean that the HsDT can track what is happening on the board (if a minion attack's another minion for instance) and if I can add the functionallity to simulate moves on the board itself ;)
