### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by zeusonline** [Epix37/Hearthstone-Deck-Tracker#684]
This program just instantly crashes when i try to run it. The updater also seems to do nothing at all.

**Comment by Epix37** [comment]
Try running as administrator. That issue will be fixed with the next update.

**Comment by AuntJ** [comment]
Same problem (running as admin didnt work)

**Comment by Epix37** [comment]
It it's not administrator please manually download the latest version here: https://github.com/Epix37/Hearthstone-Deck-Tracker/releases
