### ISSUE TITLE
Crashing Upon Opening

### ISSUE THREAD

**Issue by AuntJ** [Epix37/Hearthstone-Deck-Tracker#689]
When ever I try to run the program it stops responding, I have tried running as admin, restarting my computer, deleting and redownloading and such. I have not found a fix, any help would be very helpful! And thank you for reading!

**Comment by Epix37** [comment]
Try (re)installing the latest .NET 4.5 Framework

**Comment by tooslow0** [comment]
I've done that and I still have the issue.

**Comment by tooslow0** [comment]
Do you have any other suggestions?

**Comment by FenrisWolffe** [comment]
Can you paste the latest crashlog?
