### ISSUE TITLE
Multiple games movement to other deck

### ISSUE THREAD

**Issue by Elitesparkle** [Epix37/Hearthstone-Deck-Tracker#691]
When I try to move multiple games to a different decks all at once, only one game is moved.

After it is moved, I can still see it in the list.
To make it desappear, I have to refresh it somehow (e.g. changing a filter).

**Comment by GiggliG** [comment]
I see this issue too, being able to move multiple decks at once would be awesome.

**Comment by WaxPaper** [comment]
Ditto! It's pretty tough to manipulate as-is; maybe something similar to the Windows shell would work, like CTRL-clicking selects multiple games? Even the shift-click to select multiple list items in a series would be cool, too...

**Comment by GiggliG** [comment]
You can already use the normal multi-select commands (eg. CTRL+left click to select several items at once), but when you move to another deck, only the top deck is actually moved.

**Comment by Epix37** [comment]
Done! Will be in 0.9.7

**Comment by Epix37** [comment]
The move game dialog now also let's you specify the target version.

![screenshot 2015-03-07 14 11 18](https://cloud.githubusercontent.com/assets/7737910/6541484/0c1370aa-c4d4-11e4-8f8c-713f0650bcd9.png)

**Comment by dvide** [comment]
Looks good :)

**Comment by GiggliG** [comment]
Fantastic!
