### ISSUE TITLE
My drawn / played cards not showing in deck overlay

### ISSUE THREAD

**Issue by p3king** [Epix37/Hearthstone-Deck-Tracker#694]
Hi,

until recently everything was working fine, but since a few days my drawn cards aren´t shown anymore ingame. My opponents played cards are visible though. Also, replays show up just fine, including my cards. 

I don´t setup my decks and let the tracker just show what I draw. Hand and deck card count are drawn right where they used to, so I probably didn´t configure it outside of the visible area.

Here´s a screenshot of the problem:
http://imgur.com/40vYClu

And heres my config (I think) if it helps:
http://marcberghaus.de/files/config.xml

I already tried to redownload the newest release but it didn´t help (currently running 0.9.5)

**Comment by dvide** [comment]
Managed to reproduce this with the config file and I used git bisect to track it down. The bug was introduced in this commit: ab5c45ea6d19

Something to do with the new deck picker.

**Comment by dvide** [comment]
Ok I think I've figured out why this is happening. We want `Overlay.ListViewPlayer.ItemsSource = Game.PlayerDrawn` when no deck is selected, but at the bottom of `LoadConfig` method in `MainWindow_Load.cs`, it's forced to `Game.PlayerDeck`. This method runs after the OverlayWindow constructor, so if you first load HDT without a deck selected and then just start playing, you should see this bug.

https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/ab5c45ea6d19cb58a8ed0ac4c4801ca492b3424a/Hearthstone%20Deck%20Tracker/MainWindow/MainWindow_Load.cs#L670-677

**Comment by p3king** [comment]
Thanks a bunch for the fix and workaround guys, you are awesome.
(Should I close this now or wait for the release?)

**Comment by dvide** [comment]
Thanks @p3king!
