### ISSUE TITLE
Version bug with a recent update

### ISSUE THREAD

**Issue by Sokhar** [Epix37/Hearthstone-Deck-Tracker#697]
Hi,

I have a Pala deck whixh has 3 version : v1.0, v2.0 and v3.0.

With V1.0 i have a total of 72 W / 44 L, with 2.0 13/10 and with 3.0 1/0.
Theses stats are correctly written in "Stats / Deck / Stats", but when i select one of the deck to play on Hearthstone, these total stats are bugged.
V1.0 and V2.0 are shown as 0 / 0 during the games and V3.0 is shown as 86 / 54 (sum of the three).

I haven't played since last week, at this moment every version was correctly updated and showed its own stats.

Collateral bug : when i play with with v1.0 or v2.0, the 0/0 evolves correctly in the in game display (1/0, 1/1, 1/2) but nothing is saved on the tracker. The stats in "Stats / Deck / Stats" stay the same as they were last week.

I tried to delete the deck on hearthstone and re-import the v2.0 from the tracker but it didn' work, stats stay at 1/2.

Thanks for your incredible tool and i hope this will help you.

**Comment by Cu8eR** [comment]
@Epix37 @Sokhar I cannot reproduce it
