### ISSUE TITLE
Won't automatically change my decks anymore

### ISSUE THREAD

**Issue by Exyle** [Epix37/Hearthstone-Deck-Tracker#698]
It used to auto changed my decks depending on what class I used, but now it stopped. Help?

**Comment by GiggliG** [comment]
I'm having this problem too.
Basically, whenever I have it set to autodetect, it presents a list of decks to choose from, I pick the right deck, and it pops up the list again. No matter how many times I try, or which deck I pick, it will not accept it, and I have to disable deck detection and manually select my deck.

**Comment by GiggliG** [comment]
Update: this isn't happening all of the time. It's puzzling.

**Comment by Exyle** [comment]
I can't find the option for autodeck

**Comment by FenrisWolffe** [comment]
If I have a movie playting on my other monitor, then the tracker will not detect my deck at times, and it will NEVER Export.

**Comment by skaforey** [comment]
I can confirm this issue as well.  Exyle, what did you find to fix it? It's definitely not consistently getting it wrong, but when it does, I have to alt+f4 the program and restart it.

**Comment by Epix37** [comment]
This should be fixed now.
