### ISSUE TITLE
More Sync Issues.

### ISSUE THREAD

**Issue by FenrisWolffe** [Epix37/Hearthstone-Deck-Tracker#700]
Just had a failed sync myself. Tracker kept saying it was uploading decks, then versions, then games. None of it showed up on Hearthstats.

Deleted all decks from Hearthstats, repeated steps, same results.

Re-saved all decks as new Version 1.0, deleted all copies, repeated steps, same results.

I'm at a loss.

Edit: How odd, 15 minutes later, they appeared. (30+ total) Must just be server delay. You can delete/close this one.

**Comment by FenrisWolffe** [comment]
So I've been playing for hours. Made some new decks, etc. Closed HS, closed the tracker. Re-opened the tracker and hit sync. It's 5:07. The last game in the tracker shows 4:15. No filters, etc. Those matches are just gone. Help?
![tracker](https://cloud.githubusercontent.com/assets/8535261/6220692/168b25ac-b5ff-11e4-8148-04d73030881f.jpg)

**Comment by FenrisWolffe** [comment]
Further thought. Just looked at my other computer, and I have been leaving Dropbox open at both. Could Dropbox's sync be messing up the Deck Stat files?

**Comment by GiggliG** [comment]
I am not the developer, but I have had issues with dropbox sync before, with it locking files while they are being synced so the file doesn't get updated. When this happens, though, dropbox usually creates a copy of the file, so you can have a look at the files being synced and see if any of them have Copy (or your name, like "Fenris Wolffe's Copy") in the name.
If that is happening, it confirms DropBox is the culprit.

**Comment by FenrisWolffe** [comment]
I just created my wifes Hearthstats. 3 times now, I have tried Sync, and then Force Full Sync. She has 208 games, and it simply will NOT upload them to her account.
