### ISSUE TITLE
TempoStorm.com Decks not importing

### ISSUE THREAD

**Issue by CodeMan2** [Epix37/Hearthstone-Deck-Tracker#702]
Since the new update / design of tempostorm.com, decks from that site can no longer be imported. (Error. Could not load deck from specified url)
Like this: https://tempostorm.com/decks/reynads-blingtron-mech-mage

Cheers!

**Comment by skaforey** [comment]
Their site is very unfriendly towards page scraping in the sense that most of the markup is loaded via javascript after the initial html is loaded.  I'm not sure of a good way to do it, but maybe Epix has an idea?

**Comment by n4ru** [comment]
if you're using Chrome, the NetDeck extension will let you export from TempoStorm without any issues.

**Comment by andburn** [comment]
Thought I'd fix this, I still like adding decks with DeckTracker directly. (@n4ru NetDeck is cool though :smiley:)

**Comment by Epix37** [comment]
awesome, thank you.
