### ISSUE TITLE
Suggestion: Show number of cards in deck while editing

### ISSUE THREAD

**Issue by Kurposkano** [Epix37/Hearthstone-Deck-Tracker#703]
When I'm making a deck I always get frustrated that I have to click "Save" to find out how many cards are in the deck. Show the number visually and change as I add / remove cards.

**Comment by Kurposkano** [comment]
And... I just noticed the number of cards is in the title. It is not very intuitive. I have used this deck tracker for almost a month and I never noticed. Expected something near the mana break down or near any controls associated with building the deck.

**Comment by ppalladinos** [comment]
I agree, its not very intuitive where it is currently. I had never noticed it either until I saw this... :)

**Comment by Epix37** [comment]
Now displayed on top of the deck (only) when editing.
![screenshot 2015-02-28 11 20 20](https://cloud.githubusercontent.com/assets/7737910/6425797/eb76e91e-bf3b-11e4-89b7-f587006bcaf0.png)
