### ISSUE TITLE
Can't set hearthstone path

### ISSUE THREAD

**Issue by epsylon1991** [Epix37/Hearthstone-Deck-Tracker#704]
Hi,

I can't set the path manually, I don't know why. I click on set hearthstone path and nothing happens.

I tried reinstalling the game in default directory (C:\Program Files (x86)\Hearthstone) didn't work. HDT can't found the directory.

Is there any way to fix this issue? Thanks.

**Comment by Epix37** [comment]
fixed with edbb637
