### ISSUE TITLE
OpenClipboard failed cause crash

### ISSUE THREAD

**Issue by chucklu** [Epix37/Hearthstone-Deck-Tracker#705]
########## 2015/2/18 2:39:45 ##########
System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard 失败 (异常来自 HRESULT:0x800401D0 (CLIPBRD_E_CANT_OPEN))
   在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   在 System.Windows.Clipboard.Flush()
   在 System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   在 System.Windows.Controls.DataGrid.OnExecutedCopy(ExecutedRoutedEventArgs args)
   在 System.Windows.Controls.DataGrid.OnExecutedCopy(Object target, ExecutedRoutedEventArgs args)
   在 System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   在 System.Windows.Input.CommandManager.ExecuteCommandBinding(Object sender, ExecutedRoutedEventArgs e, CommandBinding commandBinding)
   在 System.Windows.Input.CommandManager.FindCommandBinding(CommandBindingCollection commandBindings, Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   在 System.Windows.Input.CommandManager.FindCommandBinding(Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   在 System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   在 System.Windows.UIElement.OnExecutedThunk(Object sender, ExecutedRoutedEventArgs e)
   在 System.Windows.Input.ExecutedRoutedEventArgs.InvokeEventHandler(Delegate genericHandler, Object target)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   在 System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)
   在 System.Windows.Input.RoutedCommand.ExecuteCore(Object parameter, IInputElement target, Boolean userInitiated)
   在 System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   在 System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   在 System.Windows.Input.KeyEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   在 System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   在 System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[2:39:14] Helper: Checking for updates...
[2:39:14] Helper: Current version: 0.9.5.0
[2:39:15] Load: Copied log.config to C:\Users\Administrator\AppData\Local\Blizzard\Hearthstone\log.config (AlwaysOverwriteLogConfig)
[2:39:15] Game: set CurrentGameMode to None
[2:39:15] Hearthstone: Done loading localized card database (zhCN)
[2:39:15] Game: Done loading card database (enUS)
[2:39:15] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[2:39:15] OpponentSecrets: Cleared secrets
[2:39:16] Tracker: Set player itemsource as playerdeck
[2:39:16] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[2:39:16] OpponentSecrets: Cleared secrets

**Comment by chucklu** [comment]
Stats-->Deck-->Games
I used "ctrl+a" select all the details,and then try to use "ctrl+c" to copy the details.
Then the app crashed

**Comment by Epix37** [comment]
Hm, I can't reproduce this.

**Comment by chucklu** [comment]
ok,I found this problem on my laptop.
I try this on my another computer，actuallly this problem disppeared.
Maybe this is my laptop's problem.
