### ISSUE TITLE
Suggestion: Most Played Cards with Win / Loss Stats

### ISSUE THREAD

**Issue by scorchpc** [Epix37/Hearthstone-Deck-Tracker#708]
Hi,

I think it would be super awesome if the program could be updated to track the most played cards and show their win / loss stats, both for your decks and your opponents decks. 

This way, you can see which cards are beating you most, and tech against them, for example. 

If this feature happens, I will donate. 

Cheers!

**Comment by Epix37** [comment]
Closing in favor of #1422.
