### ISSUE TITLE
Suggestion: card filter by mechanisms and capacities

### ISSUE THREAD

**Issue by jeantend** [Epix37/Hearthstone-Deck-Tracker#711]
Hello, 

For example, sometimes i would like to see all cards with provocation in their description.
It could be made with a filter listing all capacities, you choose the capacity and it shows all cards with the capacity choosen.
Or it could be made with an option to search also in cards description, and you would write "provocation" in the search field and it would shows all cards with provocation in their description.

Regards,

**Comment by Epix37** [comment]
You can turn on "advanced text search" (I think that's what it is called)  in `options > general > other` to achieve exactly this.

**Comment by jeantend** [comment]
yes thats it, thank you for the information !
