### ISSUE TITLE
question : how to send again all my local deck to hearthstats if they have been deleted on the site ?

### ISSUE THREAD

**Issue by jeantend** [Epix37/Hearthstone-Deck-Tracker#713]
they have already been sent, but I dont know some are nomore on the hearthstats site. So i delete all online decks and I want to send them all again.
But "Force full sync" doesnt works, nothing is sent :(

**Comment by Epix37** [comment]
You have to run `hearthstats > delete deck` on each deck. It will probably give you a message that deleting was not successful but re-uploading should work again after.

**Comment by jeantend** [comment]
Thanks for the help
yes it works

Regards,

**Comment by jeantend** [comment]
just one more question : what is the difference between "Sync now" and "Force full sync" ?

**Comment by jeantend** [comment]
just one more question : what is the difference between "Sync now" and "Force full sync" ?

**Comment by Epix37** [comment]
Sync now only gets decks/matches since the last sync from hearthstats, force full sync gets all.

**Comment by jeantend** [comment]
Hmmm I dont really when to use the full sync and when the basic sync is enought. Thanks for the answers !

Regards,
