### ISSUE TITLE
[NetDeck Issue]: ArenaValue Deck going into Constructed

### ISSUE THREAD

**Issue by ppalladinos** [Epix37/Hearthstone-Deck-Tracker#715]
Hi! Congrats on the work so far! I'm loving this app.
This happened to me for the first time after adding quite a few decks from arenavalue.com using the NetDeck chrome plugin: 
The deck was moved into constructed decks and I can't find a way to change it's type to Arena.
Is there a feature somewhere enabling this change?

Thanks!

**Comment by n4ru** [comment]
I'm the developer for NetDeck. I'll talk to Epix about this and get it sorted :)

**Comment by n4ru** [comment]
Looking over it, it seems that decks imported through NetDeck aren't tagged at all. Untagged decks come up in Constructed by default. So I'll see if I can auto-set certain tags.
