### ISSUE TITLE
Export stats to XLS/CSV spreadsheet

### ISSUE THREAD

**Issue by sAspen** [Epix37/Hearthstone-Deck-Tracker#717]
I'd love to be able to export my (overall & deck) stats to a spreadsheet format.

**Comment by GiggliG** [comment]
oh yes please! I would love this feature.

**Comment by andburn** [comment]
This is also mentioned in #436 & #828. So I've implemented this as a **very** basic plugin that dumps all stats out into a single CSV file on the desktop.

To test it out you need the plugins test build of the [deck tracker](https://github.com/Epix37/HDT-Test/releases/tag/v0.9.8_PRE3_PLUGINS).
Then get the plugin [here](https://github.com/andburn/hdt-plugin-statsconverter/releases/tag/v0.0.1) and unzip into the deck tracker folder.
Then go to *options* > *plugins* > *StatsConverter* > *Extract*. Not sure how it will perform with large records, I've only tested it on about 1000.

**Comment by GiggliG** [comment]
I tried it on a data set of 1700 games, and it seems to have worked fine.

**Comment by GiggliG** [comment]
Do you need to update this to work with the  latest HDT? It doesn't seem to work for me any more.

**Comment by andburn** [comment]
Fixed, see [here](https://github.com/andburn/hdt-plugin-statsconverter/issues/1)

**Comment by Epix37** [comment]
@andburn do you want me to add that one to the "available plugins" list?

**Comment by andburn** [comment]
Forgot about this, I've added support to import log files and tidied it up a bit more.

@Epix37 I just added myself to the plugins list. You can probably close this too.
