### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by n4ru** [Epix37/Hearthstone-Deck-Tracker#719]
Would be nice to have support for some basic hotkeys. Even just one to Export to Hearthstone would be nice, so I could open up a new deck screen, hit a combination, and have it exported without me having to flip through windows to export.

**Comment by dantedog** [comment]
I made the same mistake. There are some hotkeys in the game. For instance, to export to hearthstone is 'alt' + 'x' + 'h'

If you press alt, the characters in the top menu become underlined etc...

**Comment by Epix37** [comment]
#859 maybe a viable alternative?
