### ISSUE TITLE
"Export to Hearthstone" not working, WIndows 7. Config XML, video and screenshots attached

### ISSUE THREAD

**Issue by MarineKingAizen** [Epix37/Hearthstone-Deck-Tracker#720]
Hi, when I export decklist to Hearthstone, it seems to misclick and tries to message friends instead of properly searching for cards. The misclick seems to be about 10pixels below search box. I didn't move the mouse or do anything to cause the tracker to misclick. I've tried tweaking all the export settings, but nothing works. Tried slowing it down, that has no effect either. I've tried searching google for this issue, but I've not seen anyone who had this exact problem. 

Specs: I'm running Windows 7 32-bit on a standard desktop PC. Resolution is set to 1280x960

Interesting fact: When I first installed this program, the export to hearthstone feature was working perfectly. Then after doing some configurations, it no longer worked but to my knowledge I didn't change anything that should matter. Tried deleting and re-installing the program, but it remembered my settings and decks even though I deleted the logs and everything.

Interesting fact 2: If I run Hearthstone without full screen mode, the export feature works just fine because the program seems to click in the correct area to search cards. The problem only occurs in full screen mode.

Interesting fact 3: If I set "<ExportSearchBoxY>0.915</ExportSearchBoxY>" to 0.900, the program will click the correct area for the search box in fullscreen. But, it does't successfully add any cards, it just searches the cards and then ends with the same error as always (which is a listing of all the cards I don't own, even though I do own all the cards).

Screenshots: http://imgur.com/a/sLiii
Video: http://www.dailymotion.com/video/x2hthly_tracker-issue
Config XML: http://pastebin.com/rsKj8Bav

**Comment by skaforey** [comment]
I can confirm that this seems to be broken for me as well with the latest release.  It used to work fine, but all of a sudden in full screen mode, it will not work.

**Comment by Binori** [comment]
@MarineKingAizen, if every user would post bug reports as you it will be perfect world ;)

**Comment by Epix37** [comment]
Please try [this](https://www.reddit.com/r/hearthstone/comments/2oqn8t/useful_trick_to_get_borderless_fullscreen_again) and let me know if the problem persists.
