### ISSUE TITLE
If I select an old version of a deck, stats don't track

### ISSUE THREAD

**Issue by Mistrelvous** [Epix37/Hearthstone-Deck-Tracker#722]
What is the point of older versions of decks if the deck tracker doesn't keep stats for them?

I selected an older version of a deck (version 1.0) and after playing 5 or so games today, I realized none of those match results were saved. When I went to look at history, the most recent game results were that of my version 2.0 of the deck, which was last played more than 20 days ago. 

If we cannot keep track of old versions (e.g. version 1.0) of a deck, what is the point of even having different versions? Shouldn't we just make new decks outright each time?

**Comment by Epix37** [comment]
That seems to be working for me.

Any chance you have `Discard game if incorrect deck` enabled in `options > other > record games` and the decks don't match? Otherwise this could be related to #707.

**Comment by Mistrelvous** [comment]
Hmm.. if this is not happening for others, there might be another explanation.. It appears the changes I made to my deck in version 2.1 made it so the deck was the exact same composition as version 1.0. So, maybe having 2 versions of a deck with the exact same composition can cause the tracker to be confused and therefore not track match results altogether. I wish there was a way to delete a version of a deck (e.g. I want to delete version 2.1 but want to keep version 1.0 and 2.0) but I guess that is not possible right now. 

I'll try editing version 2.1 to be different from version 1.0 and then see if the match results from version 1.0 are being saved.

**Comment by Taho22** [comment]
Having the same issue.  Tracker is not keeping stats for games played with v1.0 of a deck that I'm using.  Any work-around?  Should I just make it again or something.  What is the point of having versions if you cannot go back to play previous versions?

**Comment by Epix37** [comment]
To help figure this out, please play a game with a deck and selected version where it does not record the game and upload the hdt_log.txt found in "HearthstoneDeckTracker/Logs" afterwards. (www.pastebin.com)

**Comment by Taho22** [comment]
Sorry, I didn't see this in time and deleted the offending deck (all its versions).  I then recreated it with a new name.  After that, it seemed to be working correctly (only has 1.0 version now).

The offending deck had multiple versions which I had played and kept stats on, but I had never played version 1.0.  Then, I recently got the card I needed to complete the 1.0 version.  I switched to the 1.0 version.  The in-game card tracking would work correctly, but then no games/stats were being recorded.  It was like those games never happened.

Maybe it has something to do with the fact that I never played the 1.0 version before I played other versions.

If I notice it again with a different deck, I will upload the file you are requesting.

**Comment by Mistrelvous** [comment]
Just wanted to update you on this issue. I tried editing version 2.1 of my deck to be different from version 1.0 and then played a game with version 1.0 deck. The game was not recorded at all. During the game, the cards were being tracked but after the game, the deck tracker treated it like the game didn't exist at all.

I looked at the log afterward and it was like I had nothing in the past 20 minutes:
[9:38:30 AM] Helper: Checking for updates...
[9:38:30 AM] Helper: Current version: 0.9.5.0
[9:38:30 AM] Load: Copied log.config to C:\Users\owner\AppData\Local\Blizzard\Hearthstone\log.config (AlwaysOverwriteLogConfig)
[9:38:30 AM] Game: set CurrentGameMode to None
[9:38:30 AM] Game: Done loading card database (enUS)
[9:38:30 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[9:38:30 AM] OpponentSecrets: Cleared secrets
[9:38:31 AM] Tracker: Set player itemsource as playerdeck
[9:38:31 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[9:38:31 AM] OpponentSecrets: Cleared secrets
[9:38:37 AM] Game: >>>>>>>>>>> Reset <<<<<<<<<<<
[9:38:37 AM] OpponentSecrets: Cleared secrets
[9:38:37 AM] Tracker: Switched to deck: Warrior

I'm just going to delete the deck completely and save the old deck as a new one. It's not ideal but I don't know what else to do.

**Comment by hauntedjuan** [comment]
I can confirm this issue... workaround for now seems to be to save the old version of deck you want to play again as a newer version. I also noticed that the game isnt totally lost because you actually could start the ReplayViewer of that game (if you click on Replay). Stats are not tracked at all tho.

**Comment by Epix37** [comment]
To quote myself: 
> To help figure this out, please play a game with a deck and selected version where it does not record the game and upload the hdt_log.txt found in "**%AppData%**/HearthstoneDeckTracker/Logs" afterwards. (www.pastebin.com)

(Log directory changed with the last update)

**Comment by hauntedjuan** [comment]
Wasnt at home to do so. here is the log http://pastebin.com/kfrCtYKe

**Comment by Epix37** [comment]
So it's definitely being recorded, that's good I guess. 

And those games do not show up in stats under any version (all filters set to 'all')?

**Comment by hauntedjuan** [comment]
Nope they don't show up in the stats with all filters off.

**Comment by Epix37** [comment]
Could you email me your PlayerDecks.xml and DeckStats.xml, found in "%AppData%/HearthstoneDeckTracker"? (epikz37@gmail.com)

Plus, which deck is missing matches at roughly what time / day.

**Comment by hauntedjuan** [comment]
I sent you the email with the information.

**Comment by Epix37** [comment]
You only sent the PlayerDecks.xml, I need the DeckStats.xml, too :).

**Comment by hauntedjuan** [comment]
Whoops. Sent it now.

**Comment by Epix37** [comment]
Good news: I found a way to automatically recover the games. Most of them will not have a deck assigned but the next update will allow for moving multiple games at once to a different deck.
![screenshot 2015-03-06 21 41 07](https://cloud.githubusercontent.com/assets/7737910/6535957/910099c2-c449-11e4-96df-1ed7094b4f49.png)


Now to find the underlying issue.

**Comment by Epix37** [comment]
Fixed. Should be working as intended with the next update.

Thanks for the help guys and thanks @hauntedjuan for the data!

**Comment by hauntedjuan** [comment]
The pleasure is mine!

**Comment by dvide** [comment]
@Epix37 I don't think that's the appropriate fix. I think it's now always going to assign the games to the latest version, rather than the selected version.

![untitled](https://cloud.githubusercontent.com/assets/180188/6540142/1e479fe2-c486-11e4-8ca1-6d704c1b748d.jpg)

**Comment by Epix37** [comment]
Whoops. Should be good now :).

**Comment by Epix37** [comment]
If anyone wants to do some testing, latest build:

**Please back up your "%AppData%/HearthstoneDeckTracker" (Win+R, paste) folder, just in case**
https://github.com/Epix37/HDT-Test/releases/tag/v0.9.7

**Comment by rolandschulz** [comment]
There doesn't seem to be a v0.9.7 tag but only PRE5 and PRE6 but those are older than your fix and thus shouldn't contain it.

**Comment by Epix37** [comment]
I deleted the one liked here and didn't update, sorry.

Not sure why the two releases say 10 days ago but they are not. Both contain this fix.
