### ISSUE TITLE
Deck stats needs a scroll bar

### ISSUE THREAD

**Issue by VicTT** [Epix37/Hearthstone-Deck-Tracker#726]
![noscroll](https://cloud.githubusercontent.com/assets/2959425/6388313/3a207112-bda1-11e4-92da-e737469e35f3.png)
The problem is that the last entries in the table are not visible. This only happens after selecting a deck and then clicking "Stats" (Overall).

**Comment by Epix37** [comment]
Just making the window bigger fixes the issue here, but you are right. I will add a scrollbar.
