### ISSUE TITLE
Launch old Games Viewer

### ISSUE THREAD

**Issue by GiggliG** [Epix37/Hearthstone-Deck-Tracker#729]
Before we had the excellent Replay Viewer, there was a simpler Game Viewer.
Is there any way to launch that from the current interface? The games are still being saved in that format and to be honest, I prefer that view for quickly looking at a game.

**Comment by Epix37** [comment]
Holding `left ctrl` while clicking "show replay" or doubleclicking a game now opens the old dialog.

**Comment by GiggliG** [comment]
Great!
