### ISSUE TITLE
Hearthstone Deck Tracker should not overwrite log.config (without asking)

### ISSUE THREAD

**Issue by VicTT** [Epix37/Hearthstone-Deck-Tracker#730]
My log.config used to look like this:
[BattleNet]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Asset]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Ben]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Bob]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Brian]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Cameron]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Derek]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[FaceDownCard]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[HealthyGaming]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Jay]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Kyle]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[LoadingFile]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Mike]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Net]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Packets]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Packet]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Power]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Rachelle]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Sound]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Zone]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
---------------------------
---------------------------
---------------------------
Now, it looks like this:
[Zone]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Bob]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Power]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Asset]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
[Rachelle]
LogLevel=1
FilePrinting=false
ConsolePrinting=true
ScreenPrinting=false
It's perfectly alright to change it, but perhaps asking/warning would be a good idea (maybe making an auto-backup for when/if the app gets uninstalled). The fun part was that I was planning to do a very similar thing to this app, so that's why I had all the loggers in place. I'm sure this doesn't apply to many people, but it should be worth implementing for the sake of compatibility.

**Comment by Epix37** [comment]
There currently is a config setting for that. `%AppData%/HearthstoneDeckTracker/config.xml`: `AlwaysOverwriteLogConfig`

**Comment by Epix37** [comment]
The easiest solution here would be to not replace the file but check on start if the required logs types are there and add them if not.

Another issue you might run into is that the tracker clears the output_log.txt after each game for performance sake.

**Comment by Epix37** [comment]
no longer overwrites the file but adds the required lines with v0.10.2.
