### ISSUE TITLE
Suggestion: import games (stats and/or replays) from output_log.txt

### ISSUE THREAD

**Issue by VicTT** [Epix37/Hearthstone-Deck-Tracker#731]
I saved around 10 games as output_log's for when I had the time to write a parser for them. I'm guessing it shouldn't be too hard to trick the app into thinking I'm running a HS session by reading from them and writing to the actual output_log.txt sequentially while keeping HS in the background, but there should be no point to my even trying. Perhaps this could be made into a feature? Pretty please?
Perhaps, even ignoring messages from loggers that are not used by the app?
My output logs all feature lines such as:
[Kyle] GraphicsManager Update, Graphics Quality: Medium
because I turned on most loggers. If this could be handled gracefully within the program, that would be great. If not, no biggie, I can parse them.
My thanks in advance.

**Comment by Epix37** [comment]
I don't think there would be much use for this. 

Probably the easiest thing you could do is write a script that writes your output_logs line by line into the actual output_log (while hs is running). The tracker should pick that up just as a normal game.

**Comment by VicTT** [comment]
I was thinking of doing just that, but then I thought that perhaps there are other people like me that don't always have their PC with them but still play HS whenever possible (work, school, friends, etc.) on other computers. Therefore, in order to keep their stats tracked, they would only have to upload the output_log.txt on their dropbox or whatever, and then use the Tracker to update their away-from-home progress. It's not a mandatory feature, but I have a few HS friends that play away from home; I couldn't speculate on just how widespread the phenomenon is, though I'm tempted to think that in corporate work environments where the user has no administrative privileges, this would come in very handy, as it is much easier to upload a file than to convince your boss that he should convince IT that Hearthstone Deck Tracker is something you can't do without. Does the Tracker currently ignore lines from loggers that it didn't register?

**Comment by Epix37** [comment]
Anything that's not relevant is ignored, yes.

**Comment by GiggliG** [comment]
Would there be someway to get logs from the android version of hearthstone in a format that would work with this?

**Comment by Epix37** [comment]
Possibly, but I don't have any idea how.

**Comment by ajukraine** [comment]
It would be wonderful feature, which gives the possibility to import existing logs into the tracker. For example, I have Hearthstone installed on Linux (via Wine) and therefore I can't use tracker (it's not supported through Wine, because of WPF). So I would like just to archive my logs, while I'm playing on Linux machine, and then import all of them on Windows machine. Thus I'll not loose my gaming history. I use it to track how good my improvements to decks are.

Would it be possible to implement such a feature? If not, I'll try to allocate some time and try to do it on my own. But I guess, you can do that much faster then me.

**Comment by andburn** [comment]
I have added support for importing stats from log files in the [StatsConverter](https://github.com/andburn/hdt-plugin-statsconverter) plugin, get the latest release [here](https://github.com/andburn/hdt-plugin-statsconverter/releases). Send all feedback and issues to the plugins own [page](https://github.com/andburn/hdt-plugin-statsconverter).

@Epix37 this can probably be closed now
