### ISSUE TITLE
Suggestion : have an icon to see if you have some notes on a deck

### ISSUE THREAD

**Issue by jeantend** [Epix37/Hearthstone-Deck-Tracker#734]
Hello,

Currently, you cant see which deck have some notes and which one doesn't.
It would be nice to have an icon on the line when the deck has some notes.

If easy to do, it would also be interesting to have a popup which show the notes when you rollover the icon.

Thx for your work,
Regards,
Jean

**Comment by Epix37** [comment]
I like that idea. 

Something like this possibly (simple tooltip): 
![note](https://cloud.githubusercontent.com/assets/7737910/6441914/05282df8-c0ec-11e4-8a4e-722bdb043906.png)

**Comment by jeantend** [comment]
yes how you made it, is great :)
Thanks

**Comment by GiggliG** [comment]
Great idea, and execution.

Will this distinguish between decks with notes, and imported decks where the only note is the website url?

My preference would be to remove that url from the notes, and have a seperate button for that, as discussed in an earlier suggestion.

**Comment by Epix37** [comment]
With the coming addition of a "show website" feature (soon(TM)), removing urls from the notes entirely would probably be the easiest solution.

**Comment by Elitesparkle** [comment]
What about showing the notes on the left of the mana curve graph?
I don't think it's a problem not to see 3 decks without scrolling down.

**Comment by Epix37** [comment]
That would increase the minumum height of the window since all the icons on the left need to be visible. It could obviously be optional and the min height would increase depending on that, BUT if you need to see the notes (e.g. during a game) you can just leave the flyout open.
