### ISSUE TITLE
Export to HS missing card count

### ISSUE THREAD

**Issue by NLZ** [Epix37/Hearthstone-Deck-Tracker#735]
When exporting to HS it doesnt count/recognize when there is only one card in my collection, it only mentions when Im missing both of them.
Dont know if its a bug or a limitation of the system.

**Comment by Epix37** [comment]
I like that idea. 

Something like this possibly (simple tooltip): 
![note](https://cloud.githubusercontent.com/assets/7737910/6441914/05282df8-c0ec-11e4-8a4e-722bdb043906.png)

**Comment by Epix37** [comment]
And an acutual reply to this:

There are known issues when cards are marked as "new" in game. Otherwise it is supposed to be able to tell 1 from 2 missing cards,

**Comment by NLZ** [comment]
Picture for proof, should I give you some logs or something?
![export](https://cloud.githubusercontent.com/assets/884277/6442079/493142ae-c0ed-11e4-8b82-fd12f2978c94.jpg)

**Comment by Epix37** [comment]
The log would probably say that everything except the shown was found.

Were the remaining 7 cards missed when exporting (do you own them) or are they not showing up on the incomplete report either?
Have you tried lowering the speed in `options > other > exporting`?

**Comment by NLZ** [comment]
I dont own the missing cards.
Same result on 150ms.

**Comment by Epix37** [comment]
This could possibly be a resolution issue. Are all the cards listed if you set the game resolution to 1024x768 ?

**Comment by NLZ** [comment]
The cards are listed the same way when you change resolution. Everything is smaller proportionally.
Tried both in 1024x768 windowed and fullscreen, same results.
Checked with other deck and hero too just to be sure.

**Comment by Epix37** [comment]
Alright, I will look into it. Thank you!

**Comment by NLZ** [comment]
No, thank you for your hard work :)

**Comment by condone** [comment]
ebde19db0fef8129bb624086ac5380bf7dbb7f3b fixed this bug

**Comment by NLZ** [comment]
Still broken :(

**Comment by Epix37** [comment]
Hm weird... seemed to work fine for me :/.

**Comment by NLZ** [comment]
![clipboard01](https://cloud.githubusercontent.com/assets/884277/7379345/7c35356e-edf4-11e4-9ed1-46183abb1a83.jpg)
I have 14/30, it only lists 13 as missing, but you can see the mana bar that the deck has 30 cards.
Doesnt lists the 3 Giants that I have one already.

![clipboard02](https://cloud.githubusercontent.com/assets/884277/7379685/e5cb8b84-edf6-11e4-8073-bb68877b22c2.jpg)
Doesnt lists the second missing Juggler, Argus and Doomguard.

So if you only have 1 card but the deck needs 2, it still doesnt work. If there is only 1 needed and you have 0 it works properly.

I tried it on an other machine, clean installion, but the result is the same.
I use version 0.10.0.

Also the associated bugfix ebde19d seems to be unrelated.

**Comment by dvide** [comment]
I've always had this problem too, but I assumed it was a limitation that couldn't be worked around. Nice to know that's not the case. I've just tested it with exporting on a really slow speed (100ms) and it works like that for me, but not with anything faster. I can consistently export without skipping cards on 40ms so I've always left it on that. My hardware is not the greatest though; CPU is pretty old now.

**Comment by Epix37** [comment]
Adjusted the delay before checking for the lock with higher updating speeds with v0.10.1

**Comment by dvide** [comment]
Can confirm this works for me now at 40ms. Good job :+1:

**Comment by NLZ** [comment]
Worked like a charm, thanks. :)  40ms is perfect, even on 20ms it only missed 2 Kill Command.
As a side note when I couldn't find the Kill Commands, it counted them towards the dust.

**Comment by dvide** [comment]
Yeah I meant to say it also counts Old-Murk Eye towards the dust. It should skip soulbound cards.
