### ISSUE TITLE
Since 2015-03-02 update, a lot of my decks are displayed as "0-0 0%"

### ISSUE THREAD

**Issue by Mistrelvous** [Epix37/Hearthstone-Deck-Tracker#737]
The recent update today (March 2nd 2015) has caused many of my deck stats to be displayed as "0-0 0%" even though when I look at their game history, there are many games tracked for those decks. Not sure why this is, unless the tracker has ignored stats for decks not played in some time, but I don't see an option in the options for the deck tracker to ignore stats for decks not recently played.

**Comment by Epix37** [comment]
Stats are currently only displayed for the selected version, could that be the case?

**Comment by Epix37** [comment]
Most likely same issue as #739. Will be fixed with the next update.

**Comment by Cu8eR** [comment]
@Epix37 - should be fixed, at least I canoot reproduce it anymore
