### ISSUE TITLE
Deck Stats displaying incorrectly for games with only 1 version

### ISSUE THREAD

**Issue by GiggliG** [Epix37/Hearthstone-Deck-Tracker#739]
The new update is very nice. i like the split display of percentage and games played.

However, there are two issues with it:
1) For decks which have only one version, the stats displayed are sometimes incorrect.

For instance I have a druid deck, with 28 wins, 15 losses, win% of 65.1%. In the deck list view though, it shows as - / 0-0.
Another deck has a 63% win rate, with 21-12 win/loss, and in the deck view it shows 60% / 6-4

I have tried changing the time filter in the stats tab, and have tested every single one, but i cant get the above scores, so I don't know where it's getting these incorrect views from.

Some decks with only 1 version are showing correctly, and every deck with multiple versions that I've looked at is showing correctly (but i cant be sure that's always true).

2) My second issue: I don't actaully want to show the current version stats in the global deck list. I want full history summary there. Could this be changed to an option, for which stats it summarises there?

**Comment by Epix37** [comment]
1) Could you send me your playerdecks.xml and deckstats.xml again for testing?

2) Yes, that is a good idea.

**Comment by GiggliG** [comment]
The files have been sent.

**Comment by Epix37** [comment]
Fixed, thank you!

**Comment by GiggliG** [comment]
Great!

**Comment by GiggliG** [comment]
I had an idea for the options for this setting:

Display Stats For:
* Latest Version (current intended behavior I believe)
* Active Version
* All Time History (The setting I would prefer)
* Active Filter from the stats tab

**Comment by Epix37** [comment]
I will just add "active version" (which is the current behaviour) and "all versions" (all time history) for now. I'm not sure the others are really that useful (I don't like the stats filter affecting other stuff in the first place), plus that doesn't require any new code :).

**Comment by GiggliG** [comment]
Good enough :)

**Comment by Epix37** [comment]
Added filters for: 
Version: {All, Selected, Latest}
Mode {All, Ranked, Casual, ... }
![screenshot 2015-03-05 19 36 31](https://cloud.githubusercontent.com/assets/7737910/6511854/d0387de2-c36f-11e4-8632-27fe1925a144.png)

**Comment by GiggliG** [comment]
Looks good!

**Comment by rdellaripa** [comment]
So I had a thought about this this morning...what if the stats that are normally shown are for all the current .X versions (1.0, 1.1, 1.2, 1.3, etc) combined? That way if you've just swapped a couple cards here or there but it's basically the same deck, it displays the same stats, but if you've made significant enough changes to save it as, say, 2.0 instead of 1.8, the stats shown are just for 2.x.

**Comment by Epix37** [comment]
I like the idea.  How to phrase that though? "current major", "selected major"? Will people understand what that means?

**Comment by rdellaripa** [comment]
Is there any existing phrasing in reference to the save function on 1.0, 1.1, 2.0? If not, I'd favor something like "current major version"...

**Comment by Epix37** [comment]
There we go. 

![screenshot 2015-03-11 16 32 59](https://cloud.githubusercontent.com/assets/7737910/6599877/8a9afe62-c80c-11e4-864c-c5e88551e904.png)

Still not sure how happy I am with the naming.
