### ISSUE TITLE
Since the update my Hearthstone deck tracker doesn't load.

### ISSUE THREAD

**Issue by gamerguyqqq** [Epix37/Hearthstone-Deck-Tracker#740]
I love the program thanks for sharing it with the world. However, since the update my Hearthstone deck tracker doesn't load. Does anyone know how i can fix this issue? I click on the icon and the giant logo appears, but nothing happens after that.

**Comment by Epix37** [comment]
Is the process still running after the logo disappears? Tray icon? Does starting as administrator work?

**Comment by gamerguyqqq** [comment]
I'll have to check when I get home from work. Thanks for the quick response.

**Comment by gamerguyqqq** [comment]
I restarted my computer since the update and the tracker works now!
