### ISSUE TITLE
Can't get the program to install

### ISSUE THREAD

**Issue by mmacarthur** [Epix37/Hearthstone-Deck-Tracker#747]
When I run the installer all I get is an error message saying it stopped working. I ran the installer as admin and am also running .Net Framework 4.5.2.

**Comment by Epix37** [comment]
Please try **re**installing the .NET Framework and reboot.

**Comment by mmacarthur** [comment]
Thanks for responding so fast. I tried what you said and still got the same error message as before even after re-downloading the .exe file. Do you have any other ideas?

**Comment by Epix37** [comment]
Just to make sure, you downloaded [this file](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/download/v0.9.6/Hearthstone.Deck.Tracker-v0.9.6.zip) and all the .dlls are still in the same folder as the .exe as you are trying to run it?

**Comment by mmacarthur** [comment]
I was trying to run the .exe by itself outside the folder which I now realize is immensely stupid. Thanks for all your help everything works great now. Love the program

**Comment by Epix37** [comment]
Ah, good :). No problem and have fun!
