### ISSUE TITLE
Request: Autoupload to Imgur

### ISSUE THREAD

**Issue by btouellette** [Epix37/Hearthstone-Deck-Tracker#754]
It'd be nice if I could upload a deck screenshot directly to imgur from the application: 
https://api.imgur.com/
http://pc-tips.net/imgur-api-vb-net/
http://stackoverflow.com/questions/16178350/imgur-api-version-3-uploading-examples

**Comment by Cu8eR** [comment]
I dont think it should be support by this app

**Comment by Epix37** [comment]
I disagree, I think this would be pretty neat. But lots of other stuff has way higher priority.
