### ISSUE TITLE
Request: New Deck detection/tracking

### ISSUE THREAD

**Issue by caldwelljt2** [Epix37/Hearthstone-Deck-Tracker#755]
One feature I've been waiting for is the detection of in-game created decks for storage in hearthstone tracker. After a round of games today, I found myself wanting even just the basic tracking of "no-deck" games, what I mean is once I create a deck in the game, and hit play, so long as I don't leave the choose deck screen and just re-hit the play button (essentially playing a newly created deck over and over), I wanted to know what my win-loss ratio was (after 10+ games I lost track of how many I had won and was curious).

Anyways, this started a round of thinking that it could be possible to accomplish both using mostly already written programming (at least no new game in interaction pieces should be needed). Essentially, shouldn't it be possible to do the following:
1. Detect that the player has not left the deck creation screen and has hit "play" again (optionally also assuring the selected the same deck).
2. Assign a "dummy" deck, and track the win-loss ratio for use so long as the user keeps re-upping/playing.
3. Track/merge all the cards played across all the games played (hopefully capturing most if not all the cards in the deck)
4. When the person finishes, either have a selection or prompt the user to save the deck
5. (Optionally) any features implemented/assigned to the "dummy" deck from #2 above could be applied and stored in the standard methods (win/loss, full game saves, etc).

I'm not sure how popular it would be, but based on how I keep wanting decks "out" of hearthstone, I would imagine that some players might be interested if they could install and start pulling their decks out of hearthstone this way. It also allows for a more hands-off approach, where you can start playing and just let it collect data that can later be interacted with and re-imported.

Anyways, I'm not much of a programmer, but I am a thinker, and this is what I thought. :) Hope my 2cents are worth something.

**Comment by Epix37** [comment]
FYI: Games without deck *are* tracked! In the stats screen: ```Filter > Games: Without deck```

This has been requested a few times and I'm not a fan. To detect a deck has two copies of a card requires that card to be played two times in a single game, meaning it will most likely take a quite few games to complete the deck. You would most likely end up having to add the last few cards manually in many cases.

And if you plan on playing multiple games with the deck anyway, why not take the 20 seconds it takes to create a deck in the tracker? FYI2: You can add cards with enter or 1-5 (to add 1st-5th) in the edit screen, to build decks very quickly

**Comment by Epix37** [comment]
I *may* actually just have found a way to reliably import constructed decks from the game similar to the way it works for arena.

**Comment by dvide** [comment]
Oooh, hope that pans out @Epix37 :+1:

**Comment by Epix37** [comment]
Give it a try: #762 :)

**Comment by Cu8eR** [comment]
@Epix37 - it is done, am I right?

**Comment by Epix37** [comment]
Depending on how well the constructed importing turns out to work, yes.
