### ISSUE TITLE
Export (Arena Deck) -> Screenshot includes colon ":" in suggested filename - invalid Windows filename character

### ISSUE THREAD

**Issue by TheFrequency** [Epix37/Hearthstone-Deck-Tracker#758]
When I go to export my arena deck to a Screenshot, since the default Arena deck name is a date stamp "ARENA 07-03 08:33", the suggested file name is "Arena 07-03 08:33.png".  The colon is an invalid filename character in Windows, so this suggested filename will always be invalid.

Suggested fix:
Have the Arena Screenshot suggest a filename with a valid timestamp in "YYYYMMDD HHMM" format.  Example: "Arena 20140307 0803.png

**Comment by Epix37** [comment]
Same issue as #753. Saving screenshots / exporting used to remove invalid characters, that got lost for some reason. Will be fixed with the next update.
