### ISSUE TITLE
HearthStats authentication in log

### ISSUE THREAD

**Issue by dvide** [Epix37/Hearthstone-Deck-Tracker#767]
Noticed this line in my log file:

    [15:33:45] HearthStatsAPI: < {"success":true,"auth_token":"OxdUMovfvySSrruFKoRr","email":"dvide@example.com","userkey":"w5n7klm084u2yn7qaatmcnfj1iyn4hoj"}`

I'm assuming this is sensitive info, but I've changed the data so don't get any funny ideas :) But I think this shouldn't get outputted in case users post their logs here when reporting a bug.

**Comment by Epix37** [comment]
That only gets logged when in debug mode. None of the release builds ever do so.

**Comment by dvide** [comment]
Ah right okay thanks.
