### ISSUE TITLE
Gold progress indicator

### ISSUE THREAD

**Issue by Epix37** [Epix37/Hearthstone-Deck-Tracker#774]
Inspired by [this reddit post](http://www.reddit.com/r/hearthstone/comments/2yim9b/i_want_to_be_able_to_track_my_gold_progession/) I added a tooltip to the gold frame in the main menu, displaying the x/3 wins and total gold earned that day.
![screenshot 2015-03-10 18 50 56](https://cloud.githubusercontent.com/assets/7737910/6581341/85941f9a-c756-11e4-9ca9-a547308d5240.png)

The number of wins (x/3) is pulled straight from the log at the end of a game and should be accurate most of the time (given you play with the tracker running). 
The total gold is probably a bit less accurate. 10 is added to the value every time the log shows "3/3" wins and it's reset after the first win of the day. Problem is: the reset time varies depening on where you are in the world. Playing on other devices will obviously throw this off quite a bit.

Thoughts? Ideas on how to solve the reset time issue? Maybe there is a log line I missed, containing information about how much gold was already earned? (there are messages for achievements)

**Comment by dvide** [comment]
This is a very useful feature. I've often wanted to see this information myself.

Is there any way to detect what region the player is playing on (Americas, Asia, or Europe)? Then we could just reset it at that time. It would also be useful to put that informations in the game stats.

If we can't detect it, I was thinking that a profile switcher feature would be worth working on. It's a big feature but it would basically just load a separate config.xml, PlayerDecks.xml, DeckStats.xml, etc, depending on the selected profile. It would allow users who share the same computer and windows user, but have different Battle.NET accounts, to switch their HDT profile. It also allows the same user to play on different regions, where they might have different decks, by switching up their HDT profile. And then perhaps you could just have a combobox in the options for each profile to specify what region the profile is for, and use this for determining the reset time.

**Comment by Epix37** [comment]
IIRC, the HearthlyGaming log contains the account country. We could deduce the region from that. That's only logged on game launch though I think. Another way might be some config of the bnet client / hearthstone? I tried looking for something a few weeks back but couldn't find anything worthwhile in any of the configs.

I thought about different profiles before, too. Should be very easy to implement. Although I would assume you wouldn't actually use different profiles for the region? That would mean you couldn't see stats for other regions / overall stats and would have to create/import decks multiple times. OR have means of copying and syncing decks across profiles etc.. Ugh!

We could probably rather have a special "regions" property on decks to separate those and a "region" field on games.

That's *IF* we can properly detect it.

**Comment by dvide** [comment]
What's the HearthlyGaming log? 

Just had a look with Sysinternals Process Monitor. There's a file in `%AppData%/Battle.net` called `d813f3dc.config` on my machine that changes with the region switcher in the battle.net client. 

`"LastSelectedGameRegion": "EU",` - this takes the value EU, KR, or US.

**Comment by Epix37** [comment]
HealthyGaming is one of the log "types" you can add to the log.config. 

That config item sounds promising though!

**Comment by dvide** [comment]
Ah right. Yeah I think the config item is the way to go :)

**Comment by dvide** [comment]
On my mother's machine, the information is in `ebca815c.config` and not in `d813f3dc.config`. Not sure why the difference though.

**Comment by Epix37** [comment]
I figured the name would be different everywhere. Shouldn't be much of a problem.

**Comment by dvide** [comment]
I thought so too but they're the same two filenames that I have. Just that on hers it's in the other file.

The same key exists in `ebca815c` for me, but it's blank and doesn't update: `"LastSelectedGameRegion": ""`

Either way it should be easy I think to get the information we need from them. Only trouble would be, I think, if it's not necessarily blank in one of the files, but then it also doesn't update when the region switches. Then we might not be able to figure out which one is accurate.

**Comment by dvide** [comment]
`%ProgramFiles%\Hearthstone\ConnectLog.txt` contains the region information.

`Tue Mar 10 22:54:06 2015 [ACCO] AccountListener.OnAccountLevelInfoUpdated account=50822816 currency=GBP accountRegion=2 currentRegion=3 country=GBR`

`currentRegion` can either be 1, 2, or 3 for Americas, Europe, or Asia respectively. I think this is the way to go; it's much easier to deal with.

**Comment by Epix37** [comment]
Perfect.  The region is now detected on game launch.

**Comment by dvide** [comment]
Okay cool, so I assume the reset times are the same as the daily quests. 

So that would be midnight in:
Europe: CET (CEST in daylight savings),
Americas: PST (PDT in daylight savings),
Asia: KST

According to [Hearthstone Wiki](http://hearthstone.gamepedia.com/Quest#Gaining_daily_quests).

**Comment by Epix37** [comment]
I have no idea what I'm doing... would this work?

```
TimeZoneInfo timeZone = null;
switch(Game.CurrentRegion)
{
	case Region.EU:
		timeZone = TimeZoneInfo.FindSystemTimeZoneById(DateTime.Today.IsDaylightSavingTime() ? "CEST" : "CET");
		break;
	case Region.US:
		timeZone = TimeZoneInfo.FindSystemTimeZoneById(DateTime.Today.IsDaylightSavingTime() ? "PST" : "PDT");
		break;
	case Region.ASIA:
		timeZone = TimeZoneInfo.FindSystemTimeZoneById("KST");
		break;
}
var offset = timeZone != null ? timeZone.GetUtcOffset(DateTime.Now) : new TimeSpan();
var date = (DateTime.Now + offset).Date;
if(Config.Instance.GoldProgressLastReset.Date != date)
{
	Config.Instance.GoldProgressTotal = 0;
	Config.Instance.GoldProgressLastReset = date;
}
```

**Comment by dvide** [comment]
No idea either but playing around, I think it could work something like this:

````c#
using System;
namespace TimeZones
{
    class Program
    {
        enum Region
        {
            EU,
            US,
            ASIA
        }

        class Config
        {
            public static Config Instance;
            public DateTime? ResetEU;
            public DateTime? ResetUS;
            public DateTime? ResetASIA;

            public int GoldProgressEU = 0;
            public int GoldProgressUS = 0;
            public int GoldProgressASIA = 0;
        }

        class Game
        {
            public static Region CurrentRegion;
        }

        static readonly string tzCET = "Central Europe Standard Time";
        static readonly string tzPST = "Pacific Standard Time";
        static readonly string tzKST = "Korea Standard Time";

        static void Main(string[] args)
        {
            Config c = new Config();
            Config.Instance = c;


            // lazy assign, this will only need to happen once ever
            if(!Config.Instance.ResetEU.HasValue)
                UpdateResetTime(Region.EU);

            if (!Config.Instance.ResetUS.HasValue)
                UpdateResetTime(Region.US);

            if (!Config.Instance.ResetASIA.HasValue)
                UpdateResetTime(Region.ASIA);



            // Set from the ConnectLog.txt
            Game.CurrentRegion = Region.US;


            // On update loop
            DateTime serverTimeNow;
            switch (Game.CurrentRegion)
            {
                case Region.EU:
                    serverTimeNow = TimeZoneInfo.ConvertTimeBySystemTimeZoneId(DateTime.UtcNow, TimeZoneInfo.Utc.Id, tzCET);
                    if (serverTimeNow > Config.Instance.ResetEU)
                    {
                        Config.Instance.GoldProgressEU = 0;
                        UpdateResetTime(Region.EU);
                    }
                    break;
                case Region.US:
                    serverTimeNow = TimeZoneInfo.ConvertTimeBySystemTimeZoneId(DateTime.UtcNow, TimeZoneInfo.Utc.Id, tzPST);
                    if (serverTimeNow > Config.Instance.ResetUS)
                    {
                        Config.Instance.GoldProgressUS = 0;
                        UpdateResetTime(Region.US);
                    }
                    break;
                case Region.ASIA:
                    serverTimeNow = TimeZoneInfo.ConvertTimeBySystemTimeZoneId(DateTime.UtcNow, TimeZoneInfo.Utc.Id, tzKST);
                    if (serverTimeNow > Config.Instance.ResetASIA)
                    {
                        Config.Instance.GoldProgressASIA = 0;
                        UpdateResetTime(Region.ASIA);
                    }
                    break;
            }
        }

        static void UpdateResetTime(Region region)
        {
            switch (region)
            {
                case Region.EU:
                    Config.Instance.ResetEU = TimeZoneInfo.ConvertTimeBySystemTimeZoneId(DateTime.UtcNow, TimeZoneInfo.Utc.Id, tzCET).Date.AddDays(1);
                    break;
                case Region.US:
                    Config.Instance.ResetUS = TimeZoneInfo.ConvertTimeBySystemTimeZoneId(DateTime.UtcNow, TimeZoneInfo.Utc.Id, tzPST).Date.AddDays(1);
                    break;
                case Region.ASIA:
                    Config.Instance.ResetASIA = TimeZoneInfo.ConvertTimeBySystemTimeZoneId(DateTime.UtcNow, TimeZoneInfo.Utc.Id, tzKST).Date.AddDays(1);
                    break;
            }
        }
    }
}
````

I think you're right about not needing to check for daylight savings. I think it'll pick that up automatically.

**Comment by dvide** [comment]
I see how your way works now as well, and I think that would work fine. If it's not the same day as the last reset time, then reset gold progress and update the last reset time to today. Makes sense. I think you might need to use `DateTime.UtcNow` though, and would need to keep track of 3 seperate 'last reset' dates and gold progresses though I think, for each region.

**Comment by dvide** [comment]
Pretty sure you don't have to do any special checking for daylight savings now, because when you get `vat tz = TimeZoneInfo.FindSystemTimeZoneById("Pacific Standard Time");` and do `tz.GetUtcOffset(DateTime.UtcNow)`, it results in `-07:00:00` even though PST is supposed to be `UTC -8:00`. But they're [currently observing](http://www.timeanddate.com/time/zone/usa/los-angeles) PDT which IS `UTC -7:00`.

So it looks like it's correct.

**Comment by dvide** [comment]
This seems like the easiest way to get the current date of the server:
`var date = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, timeZone).Date`

**Comment by Epix37** [comment]
Alright, so this *should* now work I guess :).

**Comment by dvide** [comment]
Looks good :)

**Comment by TunaOddfellow** [comment]
I try to play on my PC as much as possible since i love how the Deck Tracker helps. Might there be a way to manually adjust the tracked numbers when we go off sync? Thank you this is a great tool.

**Comment by roboserg** [comment]
How do enable it by default to be always visible, not when mouse over in the main menu

**Comment by riQQ** [comment]
- Enable `Advanced options`
- Enable `Gold progress always visible (in menu)` under `Options > Overlay > General`

**Comment by roboserg** [comment]
sorry, didnt see it. Many thanks!
