### ISSUE TITLE
Android tablet version

### ISSUE THREAD

**Issue by Celiece** [Epix37/Hearthstone-Deck-Tracker#776]
Is there anyway to make this usable on android tablets at this time? I know .exe's can be converted into .apk's somehow, but i was wondering if this is possible or on the to-do list since hearthstone is now available on tablet.

**Comment by Epix37** [comment]
It's far from as simple as "just converting the exe" :). Very far.
I have no idea if it's even *theoretically* possible android, so that's a no for now, sorry.
