### ISSUE TITLE
The game run slowly when hs deck tracker is unabled...

### ISSUE THREAD

**Issue by Roflmaoo** [Epix37/Hearthstone-Deck-Tracker#779]
Since yesterday hearthstone keep lagging but stop lagging when I quit hs deck tracker...
Never happened before any suggestions?

**Comment by Epix37** [comment]
Could be related to aero. Try turning that on/off if you can.

**Comment by Roflmaoo** [comment]
I already tryed turning off aero... I also reinstalled hearthstone and nvidia drivers but still lagging :/

**Comment by Epix37** [comment]
So all is good? :) 

I don't think there is anything I can do about the issue itself. It's just due to the overlay being transparent.

**Comment by Roflmaoo** [comment]
Yeah all good :D
Aero was disabled after doing windows update don't know why...
So I just had to enable it again, may help other ppl in the future.
But I guess you already know it can cause issues accoring to your advice ;)

**Comment by Akejj** [comment]
Hey I got the same problem but the aero thing didn't fix it. It has something to do with my other monitor I feel like. I have a 2nd monitor which has native 1920x1080 resolution but is 60hz while my main monitor is 144hz. When I unplug my 2nd monitor hearthstone has max fps but whenever I plug my 2nd monitor in and have hearthstone + hearthstone deck tracker open the fps drops to ~79. Without hearthstone deck tracker the game runs smoothly. The same problem occurs while the game is ran in fullscreen or windowed mode. When in windowed mode the fps drops even more to ~55. Dropping the resolution to 1024x768 in the game and running it in windowed mode I get fairly high fps ~187.
Just asking if there would be any other fix or suggestion. Thanks.
