### ISSUE TITLE
Suggestion: different stats layout in the deck picker

### ISSUE THREAD

**Issue by Elitesparkle** [Epix37/Hearthstone-Deck-Tracker#780]
Since the last update, we can see the win-loss count but, having it below the percentage seems a bit weird. It's not easy and fast to read.

I suggest to show the win-loss count on the left (or right) of the percentage, rather than above (or below) it.
Doing this way, we'll see 2 columns: one with the win-loss count and the other one with the percentage, like we had in the past.

I hope you like it.

**Comment by Epix37** [comment]
How would that be faster to read?

I see no reason to change it.

**Comment by Elitesparkle** [comment]
> How would that be faster to read?

Because each line will have 2 values at the end, on the same line, rather than 2 values on 2 different lines.

If I have 2-3 decks for each class, the color will help me to "align" the numbers but, if I have more, it will be difficult to read without looking insistently.

**Comment by Epix37** [comment]
I think it's fine the way it is.

**Comment by Elitesparkle** [comment]
> I think it's fine the way it is.

I don't. :D

Nevermind.
