### ISSUE TITLE
Deck Multiselect

### ISSUE THREAD

**Issue by Epix37** [Epix37/Hearthstone-Deck-Tracker#782]
Well that was easier than I expected.

The deckpicker now support multiselect. (Like everywhere else, use ctrl/shift to do so). 
Works (or should work) with: Deleting, archiving, move to constructed/arena and tagging!

Please do test!
Download: https://github.com/Epix37/HDT-Test/releases/tag/v0.9.7PRE8

This version now also generates data backups (of playerdecks, deckstats and defaultdeckstats) once a day (found in `%AppData%/HearthstoneDeckTracker/Backups`) so you don't need to do that manually this time.

If there is any other functionality that should work with multiselect please let me know. 

Known issues:
* `QUICK SET TAG` does currently not properly load the tags of all selected decks. 
* Performance is probably not the best at the moment

**Comment by GiggliG** [comment]
I just tested this with mass tagging, and it worked perfectly, which will be a godsend.
It was very slow, though you did mention performance would be an issue, so that's not too much of a concern.

**Comment by dvide** [comment]
8016d6b maintains the current deck selection when you are editing tags. Previous it would clear the active selection and reselect the active deck, mostly as a side effect of clearing the entire list of displayed decks and refilling it when updating. This meant you couldn't add two or more tags to multiple decks without having to reselect all the decks in between each change.

Let me know if this is okay to merge to master.

**Comment by Epix37** [comment]
That's something I planned on fixing myself, too. Go ahead :).

**Comment by dvide** [comment]
+1: Also fixed problem when selecting archived decks with unarchived decks. Now the archive button is visible when there is at least one unarchived deck in the current selection. Likewise, unarchive button is visible when there is at least one archived deck in the current selection. So if you select archived decks with unarchived decks, both menu items will be visible.

**Comment by GiggliG** [comment]
I had something weird happen
I selected three decks, went to edit tags, and created a new tag "Promising". I then clicked UP, to move it up the list, and got a second tag of the same name. I think it created a new tag and moved that one up.
I selected it again, and clicked Top - and a new tag of the same name appeared at the top of the tag list, while the original remained at the bottom.

Aside: you shouldn't be able to have multiple tags using the same name.

**Comment by Epix37** [comment]
I think I found and fixed what caused the tag behaviour. 

And you can't usually have tags with the same name, only through that bug.

**Comment by Epix37** [comment]
Here is the latest (hopefully final) build: https://github.com/Epix37/HDT-Test/releases/tag/v0.9.7PRE9
See if you can still reproduce the tag issue now.

**Comment by GiggliG** [comment]
Sorry I didn't get to test this before the official update, but it does work now.
There is one glitch unrelated to multi-select:

* Select the tag at the bottom of the tag list. 
* Click Up one or more times, so it is no longer the bottom entry.
* Click down, repeatedly. The tag will stop moving when it is one above the bottom. Pressing down will not move it to the last position in the tag list.

The Bottom button works fine.
