### ISSUE TITLE
Request: Is it possible to show attack on the board?

### ISSUE THREAD

**Issue by fmoraes74** [Epix37/Hearthstone-Deck-Tracker#783]
It would be really nice if it could show how much attack is present on each players board. I assume that given the replay system knows the attack of the cards, it should be possible to calculate it and add to the overlay.

**Comment by Cu8eR** [comment]
@Epix37 - it can be closed... we have it now :) thank you!

**Comment by fmoraes74** [comment]
Yes, it works great. Thanks.
