### ISSUE TITLE
3 wins counter issue

### ISSUE THREAD

**Issue by Elitesparkle** [Epix37/Hearthstone-Deck-Tracker#789]
When "Hide in menu" in Options > Overlay > General is checked, I can't see the 3 wins counter.

**Comment by Epix37** [comment]
There is no way around that. 

I could possibly add it to the tracker ui somewhere.

**Comment by Elitesparkle** [comment]
You could add it as a separate element, like the rest, so that we could
enable or disable it.

But this won't be enough.
You should also create a special overlay configuration, that could be
chosen checking an option, and put it in place of the current "Hide in
menu" or as a new option (e.g. "Hide in menu, keep 3 wins counter") to keep
both.

**Comment by GiggliG** [comment]
I normally have Hide In Menu checked, and was a bit confused when the wins counter didn't show up till I guessed this was the cause.
I think it would be nice, though not essential, for that to be an independent item that you switch on or off, independently of the other overlay elements.
