### ISSUE TITLE
Suggestion: discard game confirmation

### ISSUE THREAD

**Issue by Elitesparkle** [Epix37/Hearthstone-Deck-Tracker#791]
When a game is going to be discarded, can you let the software show a window to notify it?
Can you add two buttons to confirm or cancel the operation?

This function could be optional.

**Comment by GiggliG** [comment]
That's a good idea

**Comment by Epix37** [comment]
I would say this is only makes sense for discarding when the cards don't match?
A zero turn game is just that and shouldn't need this imo.

**Comment by Epix37** [comment]
![screenshot 2015-03-15 13 30 49](https://cloud.githubusercontent.com/assets/7737910/6655969/8cbbdb40-cb17-11e4-9f96-4f48c8abc466.png)
![screenshot 2015-03-15 13 24 56](https://cloud.githubusercontent.com/assets/7737910/6655970/8dd090fc-cb17-11e4-9b96-8e912a2686b4.png)

**Comment by dvide** [comment]
Now that I see it, I see that this makes a lot of sense. Nice addition. :+1:

**Comment by Elitesparkle** [comment]
> I would say this is only makes sense for discarding when the cards don't match?
> A zero turn game is just that and shouldn't need this imo.

You are right.

Well done.
