### ISSUE TITLE
3 wins counter doesn't show up in fullscreen mode

### ISSUE THREAD

**Issue by hetoord** [Epix37/Hearthstone-Deck-Tracker#792]
I was excited to try out the 3 wins counter, but it didn't show up no matter what I did. I finally figured out that the counter doesn't show up in fullscreen mode, but works as intended in windowed mode.

I'm playing on a Surface Pro 3 running Hearthstone in Windows 7 compatibility mode. I'm not sure what resolution I'm playing on (HS didn't display it, but I think I set it to 1920 x 1200), but I've tried a few different resolutions and the counter never showed up. I switch between fullscreen and windowed mode using alt + enter, and had HS in fullscreen mode when I first started it after the recent update, if that matters. The rest of the overlays seem to be in the right spot and when HS is in windowed mode the 3 wins counter is also in the right spot.

**Comment by Epix37** [comment]
It shows up fine in fullscreen mode for me. Does it by any chance show up if you move your cursor to the left or right of the gold in game?

You could also try [turning on borderless window mode](https://www.reddit.com/r/hearthstone/comments/2oqn8t/useful_trick_to_get_borderless_fullscreen_again).

**Comment by hetoord** [comment]
I moved the cursor a bit in the general area of where the pop up should be and found it a bit to the bottom and to the left of where it should be, in the black bar that's there to serve as padding because the resolution I'm running HS in isn't quite the same as the one of my screen. So it does show up, just not in the right spot. The other overlay elements seem to be in the right spot, so it's odd that this one is off by so much.
![screenshot](https://cloud.githubusercontent.com/assets/4848211/6652604/805ac508-ca74-11e4-8e12-9f1e790584c7.png)

**Comment by Epix37** [comment]
The positioning for that area works a bit differnt from the rest of the overlay items. Instead of using alt-enter, does the ingame options menu maybe contain the correct resolution for you? Setting it there and enabling fullscreen mode should fix this.

**Comment by Cu8eR** [comment]
I have same problem... maybe is possible to adjust where i wanna show it (and own setting for hide/show)
