### ISSUE TITLE
HSDT crashes

### ISSUE THREAD

**Issue by pefp2008** [Epix37/Hearthstone-Deck-Tracker#793]
Hi.
I follow the steps to run HSDT:
-Download
-Unzip (to desktop in my case)
-Try to run (normally or as an administrator)
-HSDT crashes
This is the info i get from the crash window (it's in spanish, but should be easy to read):

Firma con problemas:
  Nombre del evento de problema:	APPCRASH
  Nombre de la aplicación:	Hearthstone Deck Tracker.exe
  Versión de la aplicación:	0.1.0.0
  Marca de tiempo de la aplicación:	55041f45
  Nombre del módulo con errores:	KERNELBASE.dll
  Versión del módulo con errores:	6.1.7601.17514
  Marca de tiempo del módulo con errores:	4ce7bafa
  Código de excepción:	e0434352
  Desplazamiento de excepción:	0000b727
  Versión del sistema operativo:	6.1.7601.2.1.0.256.1
  Id. de configuración regional:	8202
  Información adicional 1:	0a9e
  Información adicional 2:	0a9e372d3b4ad19135b953a78882e789
  Información adicional 3:	0a9e
  Información adicional 4:	0a9e372d3b4ad19135b953a78882e789

Any help?

EDITI have tried with and without Hs or battle.net launcher running.

**Comment by Epix37** [comment]
Try (re)installing .Net Framwork 4.5 and reboot

**Comment by pefp2008** [comment]
Thx. It worked :D

**Comment by Epix37** [comment]
Great :) have fun!
