### ISSUE TITLE
Suggestion: 100% portable to be able to easy move to another computer

### ISSUE THREAD

**Issue by Binori** [Epix37/Hearthstone-Deck-Tracker#802]
Hi,

I have 3 computers and like to play HS on all but there is not quite stright copy/paste application to use the same decks etc.

Could you make the app more portable? or maybe allow to store data in the Cloud so the same are available from different machines.

For now what should I copy? Main program + my AppData will be enough? Thank you!

**Comment by mkrain** [comment]
I had suggested this in a enhancement:

https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/579

I have the same issue in that I use OneDrive to sync my folders but on my tablet the sync doesn't happen as fast so I have to do some manual syncing.

**Comment by Epix37** [comment]
You may want to give #545 a read, especially [this](https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/545#issuecomment-70380390)
