### ISSUE TITLE
Suggestion: Improved replay viewer

### ISSUE THREAD

**Issue by HandEyeProtege** [Epix37/Hearthstone-Deck-Tracker#804]
I'm a huge fan of the replay viewer -- I think this is an invaluable tool to critically examine and improve my gameplay.  However, in practice I find it clunky to use because the turns and sequence of actions in the left column is an overwhelming amount of information presented in a hard-to-parse way.

By contrast, consider the lightweight "replay" provided by Track-o-bot: 

![trackobot](https://cloud.githubusercontent.com/assets/11563983/6743499/ea688192-ce57-11e4-9006-2c38e536053d.png)

All it shows is what card is played on each turn, but it's presented in a way that's very easy to take in at a glance: players turns are on opposite sides of the timeline, and there's no extraneous information to get in the way.

Of course, all that extraneous information is what makes HDT's replay valuable.  I'm greedy and I want the best of both worlds.  What I'd love to see is for the left column of the replay viewer to show a condensed version of the game akin to what Track-o-Bot offers, just showing cards played.  If you want more detail about a turn, you could expand that to show each individual action on the turn.  And, of course, you could still see the board state at any point.

Typically the Track-o-bot style overview is enough to give me the flow of the game, and if there's something I want to drill down on that minimalistic view of the game is STILL preferable because it lets me easily zero in on the turn that I'm interested in.

**Comment by Epix37** [comment]
The replay viewer will see imporovement at some point!

You *can* still access the old game viewer by holding CTRL whiling clicking "show replay" in the stats screen. Maybe this is close enough to what you are looking for for now.

![screenshot 2015-03-20 07 20 21](https://cloud.githubusercontent.com/assets/7737910/6746950/d9003538-ced1-11e4-8618-a176585c3fc0.png)

**Comment by GiggliG** [comment]
One improvement that would be great is to have the left side (which shows the actions taken) to be a resizable frame within the window, so I can expand it.
Also, if one line of text wraps to the next, indent all but the first line, so it's easier to see each action visually.
Also using alternating background shading for each event would help a lot too.

**Comment by Epix37** [comment]
[work in progress]
how is this? :)

![screenshot 2015-03-28 20 40 16](https://cloud.githubusercontent.com/assets/7737910/6882589/b7cb3d6c-d58a-11e4-90f3-6e120d9620b0.png)

I will probably add checkboxes to the top, too, similar to the screenshot above.

**Comment by HandEyeProtege** [comment]
That looks awesome!  The checkboxes to show or hide things like attacks/deaths/etc. would be perfect to get rid of the clutter, but you'd still have the option to see them if you wanted.

Nitpicky feedback: it would be great if each event could fit on a single line.  Maybe instead of using text like "Play" or "HeroPower" you could find a small icon that would represent each action.  And I don't think it would be a problem if the name of the card gets cut off; 99% of the time I'll know what something like "Oasis S..." is and you could show the full text on hover.

I can't wait to see this in action!

**Comment by Epix37** [comment]
Went with a context menu for the checkboxes, this way everthing stays very clean but you obviously need to know that it exists, not sure.
![screenshot 2015-03-28 22 15 09](https://cloud.githubusercontent.com/assets/7737910/6882934/f6d52ac4-d597-11e4-877c-5c275347211b.png)

I originally went with two lines because I still had "Attack attackername -> defendername", no way to fit that in one line :).
Side to side comparison for single and double line:
![screenshot 2015-03-28 22 05 32](https://cloud.githubusercontent.com/assets/7737910/6882913/0549870e-d597-11e4-9575-43b27384026a.png)
Single like looks very odd in my opinion, even more so if you have different lenghts for the "prefix" (draw, attack, ...). **Icons might look really good, if so you have suggestions on ones to use, please suggest away!**


Also not quite sure on the grouping (checkboxes, icons) yet. Currently I have this
(straight up the code but I'm lazy and it should be understandable enough)
``` C#
switch(kp.Type)
{
	case KeyPointType.Attack:
		if(!Config.Instance.ReplayViewerShowAttack)
			continue;
		break;
	case KeyPointType.Death:
		if(!Config.Instance.ReplayViewerShowDeath)
			continue;
		break;
	case KeyPointType.DeckDiscard:
	case KeyPointType.HandDiscard:
		if(!Config.Instance.ReplayViewerShowDiscard)
			continue;
		break;
	case KeyPointType.Draw:
	case KeyPointType.Mulligan:
	case KeyPointType.Obtain:
	case KeyPointType.PlayToDeck:
	case KeyPointType.PlayToHand:
		if(!Config.Instance.ReplayViewerShowDraw)
			continue;
		break;
	case KeyPointType.HeroPower:
		if(!Config.Instance.ReplayViewerShowHeroPower)
			continue;
		break;
	case KeyPointType.SecretPlayed:
	case KeyPointType.SecretStolen:
	case KeyPointType.SecretTriggered:
		if(!Config.Instance.ReplayViewerShowSecret)
			continue;
		break;
	case KeyPointType.Play:
	case KeyPointType.PlaySpell:
	case KeyPointType.Summon:
		if(!Config.Instance.ReplayViewerShowPlay)
			continue;
		break;

}
```

**Comment by GiggliG** [comment]
Would it be possible to have the frame containing the actions resizable, so i could expand it to make everything single line, or compress to make it double line?

Alternatively, use a symbol or colour to represent Draws and another symbol or colour to represent Plays, Deaths, etc, then you can omit those words.

**Comment by Epix37** [comment]
It's already about double as wide as it was before, do you really want to have it go across half your screen? :) Plus... I tried and didn't work out too well, so if I can avoid it I'd like to. Centering wrapping text properly is ugly.

I agree icons would be the way to go. Just need to find decent icons now.

**Comment by HandEyeProtege** [comment]
GiggliG's color idea is a good one.  I was brainstorming about icons, but I don't have anything specific to point you to.  I'll see if I can find any, but might not have a chance for the next couple days.  (I do agree that if you keep the prefix the double lines look better.)

I like the context menu.  (Maybe you could make it a "Filter" dropdown so people can discover it.)  Regarding groupings, I think the only one that seems weird to me is the "play" group.  If I had that checked, I'd expect to see ALL cards that get played, including secrets.  And I think you could even lump hero power into that group too.  And I assume "summon" means when a card summons a token, like Violet Teacher or Razorfen Hunter?  I'd probably make that a separate grouping instead of including it with plays.  (Imagine what the replay would look like after playing Onyxia!)

**Comment by Epix37** [comment]
Having ~6 colors might be hard to remember (especially not so common ones), plus it would probably look a bit weird, depening on how you implement that I guess. Icons would be a lot more self explanatory. 

SecretPlayed belongs to Play, good point. I think I could agree on heropower, too. Summon means mainly tokens, yes. I plan on merging multiple summons, Onyxia whelps whouls show as "Summon Whelp x6". Having it as a separate group might still be good though.

I'm trying to find a place for the filter where it doesn't break the look too much.. Harder than one would expect.

**Comment by Epix37** [comment]
Latest build: https://github.com/Epix37/HDT-Test/releases
Should be pretty stable. More than the live version actually.

**Comment by GiggliG** [comment]
Just installed and had a look at replays. It's already a big improvement over the old version.
Regarding the colour/icon suggestions: Is it possible to use different shaped boxes? It already looks like a flowchart, and a different flowchart-style container for each type of event might help. You'd need a key, though.

One thing to consider about grouping things like onyxia's multiple 1/1s, and also things like muster for battle, etc, is what happens if you have knife juggler down? You have to show the damage each summon causes.

**Comment by Epix37** [comment]
I think shapes would have the same issues as colors. I'm still voting icons :). I'll try to find (or even make) some tomorrow I think.

Easy! Procs (Knife juggler, Rag, etc.) don't work anyway in replays :P. I don't see that happening any time soon either, as I can't get that information directly from the log. Would have to somehow deduce those...

**Comment by HandEyeProtege** [comment]
I'm loving the latest build!  This is going to be so much more useable for me.

The one issue I'm noticing is if I'm looking at a filtered set of events (Play + HeroPower) and I want to see more events to make sense of the turn I'm looking at.  I can think of two solutions:

1) If I have a row selected and I change the filter, keep that row selected.  (And keep it scrolled to the same position in the view.)
2) Have some option on the "Turn X" row to toggle showing all events for that turn.  Probably a bit more complicated, but gives you finer control over what you're looking at.

**Comment by Cu8eR** [comment]
is there any tooltip with a card shown?

**Comment by Epix37** [comment]
@HandEyeProtege with 2) you mean removing all filters for a specific turn only?

@Cu8eR on the "Draw Faerie Dragon"-like nodes? Currently not. That's a good idea though.

**Comment by Epix37** [comment]
New build with all of the above: https://github.com/Epix37/HDT-Test/releases

**Comment by Epix37** [comment]
I really suck with inkscape but to get an idea what it could look like:
![1](https://cloud.githubusercontent.com/assets/7737910/6885375/32d8d47c-d61e-11e4-89bf-9ca444b2c816.png)

**Comment by HandEyeProtege** [comment]
Yep, that's exactly what I meant.  Between that and once you get icons in, I think you've nailed everything I was looking for our of a replay viewer!

How are you doing on the icons?  Besides the ones you show above, here are a couple I was imagining.

Discard: Cards with a red X over them instead of + sign.  (Your + above could be green to contrast with it.)
Death: A black skull.
Hero power: A golden circle.
Secret: A question mark.

**Comment by Epix37** [comment]
Icons...

I want to keep everything in one color to work with the accent I think. At least as long as I do it myself. Making that stuff is hard enough already :). 

Discard: I was thinking `-` instead of `+` but a cross might work, too.
Death: yup
HeroPower: really not sure
Secret: yup

And the one I have no idea what to do with: **Play**.
Maybe an extra one for summon, too, or just the same as play.


... I need to find someone who's good at making these sort of things.

**Comment by HandEyeProtege** [comment]
Oh, play -- I forgot about that one!  I was imagining something like this: ![play](https://cloud.githubusercontent.com/assets/11563983/6886319/a5623546-d5ed-11e4-9f63-9f8b607baccd.png)

Except, you know, nicer.  Sadly I'm completely inept when it comes to coming up with graphical stuff.  I am pretty good at searching for clip art and munging it to fit my needs, though.  :)

**Comment by HandEyeProtege** [comment]
As a side thought: you have so many people using the deck tracker, I'm sure SOME of them have graphical talents.  Next time you post an update on reddit (or wherever) you could ask for help with icons and I bet people would jump at the chance.

**Comment by GiggliG** [comment]
Regarding hero power, would the class icon work? Or is that too detailed for this view?

**Comment by GiggliG** [comment]
For Play, maybe something like a card deck, with one card being drawn.
Something like simplified versions of
http://www.clker.com/cliparts/8/5/4/b/11949911381154569537asso_carte_architetto_fr_01.svg.med.png
or
http://images.clipartpanda.com/open-giving-hands-clipart-hand-with-card-hi.png

**Comment by Epix37** [comment]
Heropower: I think class icons (or class hero powers actually) are overkill. Something along these lines would problably be good:
![capture](https://cloud.githubusercontent.com/assets/7737910/6887584/5174ef6a-d664-11e4-881e-e91254211dac.PNG)


Play.. yea.. idk. One face down, and one face up card might work if you could somehow get that clear enough on that scale. 

Really depents on whoever I can find for this (I put something in the newsticker now). 
I just don't want 6 icons in 4 inconsistent styles.

**Comment by andburn** [comment]
There is an icon set available at http://game-icons.net/ under [CC BY 3.0](http://creativecommons.org/licenses/by/3.0/) in SVG and PNG. Until someone comes forward to do some custom icons, they are not bad. There's lots of possible of options, I've just picked out a few that might be useful.
![icons](https://cloud.githubusercontent.com/assets/5419653/6900137/755a1b1a-d6fc-11e4-8efc-43accea02505.png)

http://game-icons.net/lorc/originals/wood-axe.html
http://game-icons.net/lorc/originals/skull-crack.html
http://game-icons.net/lorc/originals/ace.html
http://game-icons.net/lorc/originals/poker-hand.html
http://game-icons.net/lorc/originals/prayer.html
http://game-icons.net/lorc/originals/cowled.html
http://game-icons.net/lorc/originals/pawn.html
http://game-icons.net/felbrigg/arrows/thrust.html
http://game-icons.net/lorc/originals/lob-arrow.html
http://game-icons.net/lorc/originals/uncertainty.html
http://game-icons.net/willdabeast/deviations/orb-wand.html
http://game-icons.net/lorc/originals/pirate-grave.html

**Comment by Epix37** [comment]
Oh those are awesome!

**Comment by Epix37** [comment]
![screenshot 2015-03-30 19 16 10](https://cloud.githubusercontent.com/assets/7737910/6902162/57bd348c-d712-11e4-8886-6949ae268e9c.png)
Went with these for now. Having play and heropower be the same icon should be fine.
![screenshot 2015-03-30 19 25 43](https://cloud.githubusercontent.com/assets/7737910/6902199/a3b6bebc-d712-11e4-9152-ad08e0702ead.png)
