### ISSUE TITLE
Hunters beta import from game

### ISSUE THREAD

**Issue by themacklee** [Epix37/Hearthstone-Deck-Tracker#805]
1st of all love the addon
I have been using the new beta Import from game: constructed 
I have been having great success importing my decks .....all but hunters... hunters mark always shows in deck no matter if it really is, other cards do this also. most decks i have imported to this point needed to have a duplicates removed or added never a cards that wasn't in original deck.

**Comment by Epix37** [comment]
How well the importing works highly depends on what cards are in the deck. Everything that's visible on the left side (in the book) may cause trouble. I would suggest running the setup for constructed importing agan and see if that solves it. (option > importing > set up constructed importing)
