### ISSUE TITLE
Where is the .exe file?

### ISSUE THREAD

**Issue by qtic** [Epix37/Hearthstone-Deck-Tracker#806]
Hi! 

I feel like the biggest idiot right now since anyone else haven't said anything about this (as far as I know), but where's the .exe file I'm supposed to run? I downloaded the .zip file and extracted it and couldn't find it in any of the folders or through searching?

I'm probably missing the most obvious thing right now, but what do I do?

**Comment by dvide** [comment]
Did you perhaps download the souce code zip rather than the binary on the [release page](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.9.7)?

**Comment by qtic** [comment]
That's exactly what I did. Evidently I was right about being an idiot.
Cheers for the help!

**Comment by dvide** [comment]
:+1:
