### ISSUE TITLE
Scaling too small

### ISSUE THREAD

**Issue by DragonNL** [Epix37/Hearthstone-Deck-Tracker#813]
Hello,

First, thanks for the awesome work.

My request, increase the maximum scaling, I play on 1440p(2560x1440) and even the maximum size
still looks quite small on the screen.
I'd imagin it be unusable on 4k.

Thank you for the awesome work and I hope the max scaling can be upped a bit in a future version.

**Comment by graydon-armstrong** [comment]
I love the program so far and would like to second larger scaling as I also play on 4k and the largest size is about half what is comfortable reading.
