### ISSUE TITLE
Gold tooltip not showing when 'hide in menu' is checked

### ISSUE THREAD

**Issue by d07RiV** [Epix37/Hearthstone-Deck-Tracker#816]
I always use the 'hide in menu' option because there is no reason to see my and especially my last opponent's decks in menu (not top mention it covers the friend list). However, now it also disables the gold tooltip feature. Is there any way to have one but not the other?

**Comment by Epix37** [comment]
With the next update hide in menu will no longer affect that tooltip and there will be an option to have it turned on permanently.
