### ISSUE TITLE
Deck tracker crashes

### ISSUE THREAD

**Issue by Legioner89** [Epix37/Hearthstone-Deck-Tracker#817]
Hi!

The deck tracker has started crashing since today. There is the crashlog, unfortunately, in Russian:

########## 20.10.2014 8:24:08 ##########
System.Windows.Markup.XamlParseException: Вызов конструктора для типа "Hearthstone_Deck_Tracker.MainWindow", удовлетворяющего указанным ограничениям привязки, привел к выдаче исключения. ---> System.IO.IOException: Файл "config_backup.xml" уже существует.
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   в System.IO.File.Copy(String sourceFileName, String destFileName)
   в Hearthstone_Deck_Tracker.XmlManager`1.Save(String path, Object obj)
   в Hearthstone_Deck_Tracker.Config.Save()
   в Hearthstone_Deck_Tracker.MainWindow.FindHearthstoneDir()
   в Hearthstone_Deck_Tracker.MainWindow..ctor()
   --- Конец трассировки внутреннего стека исключений ---
   в System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   в System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   в System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   в System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   в System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   в System.Windows.Application.DoStartup()
   в System.Windows.Application.<.ctor>b__1(Object unused)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

Hope you can see something familiar there =)

It happens when I open the deck tracker while playing with this deck: http://www.hearthpwn.com/decks/186065-spark-snake-bite-s11-beast-synergy

Or when I start playing with this deck with the opened Deck Tracker.

**Comment by Thristle** [comment]
the program is trying to save the configuration and it can't. 
are you using the latest version? the name used for the config is not the same as i see in the code 
anyway the save location (if you didn't change it) is "%appdata%\HearthstoneDeckTracker" 
do you see a config.xml files in there?
