### ISSUE TITLE
Question regarding Games display

### ISSUE THREAD

**Issue by Pand3m0nia** [Epix37/Hearthstone-Deck-Tracker#822]
Hi there,

I have a question regarding the Games display. I have noticed that some games have an asterisk next to the where it says "Win" or "Loss" and I just am curious as to what that indicates?

Thanks

**Comment by Epix37** [comment]
I'll actually tell you if you mouse over it :).
It indicates conceded games.

**Comment by Pand3m0nia** [comment]
Oh right, never noticed before, thanks :)
