### ISSUE TITLE
Can't move HDT folder

### ISSUE THREAD

**Issue by pefp2008** [Epix37/Hearthstone-Deck-Tracker#824]
Hi.
When i downloaded the app, i unzipped the folder to the desktop. After testing it (really cool app), now i find that i cannot move that folder to another place on my PC.

How is that possible?

**Comment by Epix37** [comment]
Is the program possibly still running?

**Comment by pefp2008** [comment]
I marked the option: "close when HS closes", so it shouldn't be running. 
I'll try closing processes with the task manager to see if it works.
I'll be reporting.
