### ISSUE TITLE
Card images sometimes missing in old game viewer (ctrl+show replay)

### ISSUE THREAD

**Issue by culinko** [Epix37/Hearthstone-Deck-Tracker#830]
I use the old game replay viewer to quickly look at the opponent deck to fill the deck type into the 'Note' field and noticed that the card images are missing sometimes if you scroll up and down for a bit. Attaching a screenshot.
![replay-pictures](https://cloud.githubusercontent.com/assets/11700272/6883310/7c86ecf6-d5a8-11e4-9f17-096c1e483f85.png)

**Comment by Epix37** [comment]
Yea, I was too lazy to fix that here :).
Will become completely obsolete with the coming changes to replays anyway: #804

**Comment by culinko** [comment]
I still kinda like this viewer more :) As I was saying, it helps me fill out the opponent deck type quicker, because you know most of the cards by their color (e.g. Explosive Trap is red). So I was gonna use the old viewer until some automated way of detecting opponent's deck type will be available. Perhaps a button like "Show Opp. Deck" next to the "Import Opp. Deck" could be a viable option? The layout could look like the old replay viewer, but it would just display the cards grouped like a normal deck. This way I wouldn't need to use the old replay viewer at all ;) Anyway, should I create another ticket for that feature request?

**Comment by Epix37** [comment]
How about replacing "import opp deck" with "show opp deck", which open a flyout containing the decklist and an import button? 

No need for an extra issue, this is fine.

**Comment by culinko** [comment]
That would be awesome, yeah! I just hope it won't upset people that they need to make an extra click to import the opp. deck :)

**Comment by Epix37** [comment]
I don't think it get's used *too* much, but seeing the deck before getting booted out of the stats screen is proably a good thing.

**Comment by Epix37** [comment]
There we go :)

![screenshot 2015-03-29 01 16 56](https://cloud.githubusercontent.com/assets/7737910/6883525/4f79faf6-d5b1-11e4-86e2-47f7c4aba322.png)

**Comment by culinko** [comment]
That's neat, I like it!
