### ISSUE TITLE
Suggestion: Add note popup box after each game

### ISSUE THREAD

**Issue by jammo2k5** [Epix37/Hearthstone-Deck-Tracker#833]
Add an option to have a pop up box to add a note to the last game in the options menu.

**Comment by MyopicCat** [comment]
There already is one, see under Options/Tracker/General.

However, there is a tiny glitch. The note dialog pops up as it should, but then the tracker window immediately steals its focus so you have to move or minimize the tracker to find it again. Epix37, consider this a small bug report!

**Comment by jammo2k5** [comment]
ahhh I didn't see this. thanks.

**Comment by Epix37** [comment]
@MyopicCat  could you open an issue for that (so I don't forget)? I will have a look at that.
