### ISSUE TITLE
Ablility to track legend ranks

### ISSUE THREAD

**Issue by culinko** [Epix37/Hearthstone-Deck-Tracker#836]
Hey, I just found out that after you reach legend, the tracker doesn't track the current legend rank and the field is just empty (because the code says 0>25). The last match that had "Rank 1" was the winning match that pushed me to legend, because the "Rank" in the stats is the rank that you had before you started the match. I was browsing the logs and found out that there is "[Bob] legend rank 1527" at the end of the file (2 times). So there could be possibility to add tracking the legend rank as well, you just need to take the legend number from the PREVIOUS ranked game that you played this month (If we want to be consistent with displaying rank before the match). The info should be like "L 1527" or something similar. I really want this info to be visible. Also if people are saving all ranked .hdtreplay files, there is a possibility to add missing legend ranks from the past games that have already been tracked (I mean automatically within the tracker, not manually). What do you think about this request? :)

**Comment by culinko** [comment]
Actually, I've found out that sometimes the two numbers are identical, sometimes they differ by 1, not sure why. 4/8 of my matches have same numbers, 4/8 of my matches have different numbers, sometimes the first one is bigger, sometimes the first one is smaller.

One example from my game: 
[Bob] legend rank 1989
"23 lines of text"
[Bob] legend rank 1988

I guess you would need to test with someone who has legend rank to confirm what rank did the game show after the match to find out if the first or the second one is the correct number.

**Comment by Epix37** [comment]
I guess that happens if someone else wins/loses rank in the mean time.

**Comment by culinko** [comment]
Can confirm it now, I've seen it on stream. It showed 400 right after the victory screen, but showed 399 when in deck selection.

**Comment by Epix37** [comment]
Closing in favor of #2117. Coming soon.
