### ISSUE TITLE
Opponent card markers not working properly.

### ISSUE THREAD

**Issue by pefp2008** [Epix37/Hearthstone-Deck-Tracker#839]
Hi.
With the recent update to HS and HDT, i found that my opponent's card markers are shown wrong.
Things i have seen so far:
-Cards' turn markers go to -1, or keep at 0 (the ones that show in which turn  they were drawn)
-Cards' turn markers keep showing as K (original hand markers)

I restarted both HDT an HS after the updates, and it keeps showing.

**Comment by pefp2008** [comment]
Seems to have fixed itself after another match.
Check, just in case :)

**Comment by Epix37** [comment]
Probably same issue as #819 ?
