### ISSUE TITLE
'Use no deck' is not working from the tray

### ISSUE THREAD

**Issue by askarmuk** [Epix37/Hearthstone-Deck-Tracker#840]
If I try to choose 'Use no deck' option from the try icon it will not work. It will work if I choose it from main window.

Tracker is starting with Windows.

**Comment by Epix37** [comment]
Hm.. works completely fine for me.

**Comment by askarmuk** [comment]
Looks like it woks for me now in 0.9.9. Recently tracker didn't show my cards until I choose 'Use no deck' from main window. Choosing 'Use no deck' from the tray was useless.

**Comment by Epix37** [comment]
Ok :).

**Comment by askarmuk** [comment]
Hmm im sorry but seems it still presents in the tracker. Try to do these steps:
- start Windows with tracker autostarted
- do not open tracker main window!
- start HS
- start any game with random deck for example
- click right mouse button on the tray icon and choose 'Use no deck'
- this will not work. I will not see my cards.
- open main tracker window and choose Tracker > Use no deck
- this will work. My card will appear.

**Comment by Thristle** [comment]
Does it still work with normal use?

**Comment by Epix37** [comment]
Most likely #808. The overlay does not update until you click out of hearthstone one. 

Try if this version works: https://github.com/Epix37/HDT-Test/releases/tag/v0.10_PRE1
