### ISSUE TITLE
Could not load deck from specified url !

### ISSUE THREAD

**Issue by Zorgloub** [Epix37/Hearthstone-Deck-Tracker#841]
Hello
I n arrive more has import decks via Websites.
J have deja imorter several decks but the ca does not walk any more.
Thank you

**Comment by Epix37** [comment]
Do you have example URLs that do not work?

**Comment by Zorgloub** [comment]
yes ,
http://www.hearthstone-decks.com/deck/voir/bloodlips-mage-1-legend-4009

**Comment by Epix37** [comment]
Ah, yes. I contacted the webmaster a while back about missing ids for the GvG cards, did not yet get a response.

You can use the [NetDeck Extension](http://netdeck.n4ru.it/extension.html) if you are using chrome or the [NetDeck Bookmarklet](http://netdeck.n4ru.it/bookmarklet.html) with any other browser. (Note: it can not get GvG cards from that website either, but all the classic cards will be imported this way)

**Comment by n4ru** [comment]
Actually, it supports GvG cards now :)

**Comment by Epix37** [comment]
NetDeck that is, I guess? :)

**Comment by n4ru** [comment]
Haha yea, that's what I meant.

**Comment by Zorgloub** [comment]
I can import no deck via this Website, before ca works.
With less other Websites c is ok.
I n use not google chrome but Mozilla firefox.
Sorry for my english Oo
