### ISSUE TITLE
Decklist Name Filter

### ISSUE THREAD

**Issue by Epix37** [Epix37/Hearthstone-Deck-Tracker#842]
Implemented @GiggliG's idea from #828:
![screenshot 2015-04-01 19 00 55](https://cloud.githubusercontent.com/assets/7737910/6946599/d0eb9dc2-d8a1-11e4-8d2b-ab2bb4e1dd35.png)
![screenshot 2015-04-01 19 00 59](https://cloud.githubusercontent.com/assets/7737910/6946600/d20faf40-d8a1-11e4-9551-8dd577a64bcb.png)
![screenshot 2015-04-01 19 01 03](https://cloud.githubusercontent.com/assets/7737910/6946601/d3a0f2ba-d8a1-11e4-8ed7-2778f54a6e8a.png)

**Comment by GiggliG** [comment]
Nice!
