### ISSUE TITLE
Make it portable

### ISSUE THREAD

**Issue by Dude1571** [Epix37/Hearthstone-Deck-Tracker#850]
Hello, I really like this program it's awesome.
But I'd love even more if the program could save all the data from %appdata% to a folder inside the folder where the program already is.

Thanks.

PD: I speak Spanish.

**Comment by Epix37** [comment]
In `optons > tracker > settings` disable `Save config in AppData` and `Save data in AppData`

**Comment by Dude1571** [comment]
Thanks, I'm sorry for the trouble. I was trying that, but I probably didn't test it right.

**Comment by Epix37** [comment]
Got it working now? :) No trouble!

**Comment by Dude1571** [comment]
Yes, thank you so much.

**Comment by Epix37** [comment]
No problem!
