### ISSUE TITLE
Suggestion: highlight my discarded cards

### ISSUE THREAD

**Issue by askarmuk** [Epix37/Hearthstone-Deck-Tracker#851]
I didnt find any option to highlight cards discarded from my hand. It is necessary for example when playing vs mill decks.

**Comment by Epix37** [comment]
I'm not quite sure I see the necessity. You can see which cards are left in the deck (and hand, optinally) and how many. Whether a card was drawn, played or discarded doesn't really make a difference, does it? It's gone.

What am I missing?

**Comment by askarmuk** [comment]
Thats because i want to see which cards came to my hand from drawing or from another way and which of them were discarded. The difference is that I can play cards from my hand and I cant play my discarded cards ^^

**Comment by Epix37** [comment]
You mean when playing in "no deck"-mode?

Though, still.. if the card shows up in the list but is not in your hand (which you can clearly see), you obviously can't play it.

**Comment by Cu8eR** [comment]
@Epix37 I agree with you, I dont see any point for this

**Comment by Cu8eR** [comment]
Maybe just add red /orange border for discarted cards

**Comment by askarmuk** [comment]
Yes I play 'no deck' mode. Information about ьн cards that were discarded is important in match. I think adding this feature worth it.

**Comment by Epix37** [comment]
I still don't see the value from knowing which cards were discarded and which were not.

You have two copies of Flamestike in your deck. With any combination of played/discarded, you both were removed from the deck. You now have no Flamestrikes left. Knowing if one or more of them were discarded adds no value and does not help you decide for a better play. In the current situation of the game you have no Flamestrikes you could draw or play.

What's a scenario where that knowledge would help?
