### ISSUE TITLE
Deck-Tracker can not export the deck into the game correctly

### ISSUE THREAD

**Issue by Adomb** [Epix37/Hearthstone-Deck-Tracker#852]
![afttf](https://cloud.githubusercontent.com/assets/8226013/6965676/461d9810-d975-11e4-85ac-3d88f6626884.png)
does not delete the previous entry because not clicks on the search icon
![aftto](https://cloud.githubusercontent.com/assets/8226013/6965722/71af52ca-d975-11e4-9fea-c13e88837a5d.png)
eventually,  only half the deck

**Comment by Thristle** [comment]
i have 2 computers that i play HS on. the top image is like my laptop and the bottom one is like my pc. the search term should be at the bottom location and not the top. some kind of bug in HS

**Comment by Epix37** [comment]
See [#303](https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/303#issuecomment-56195879)
