### ISSUE TITLE
each time that the tracker is opened,gold is raised by 10 without any reason

### ISSUE THREAD

**Issue by MACDARK007** [Epix37/Hearthstone-Deck-Tracker#855]
http://prntscr.com/6op1ih 

http://prntscr.com/6op3xq

check the images,please. and i think there is a issue also with the deck selection. I'll check and report back.

**Comment by Epix37** [comment]
Two possibilites: 
1) You have `ClearLogFileAfterGame` in the config disabled. (I did not test that too much that I can see that being an issue here)
2) You are starting HDT (multiple times for some reason?) right after you won a ranked/casual game, in which you got your 3/3 wins 10 gold reward.

I added a check for the latter now.

**Comment by MACDARK007** [comment]
where is that line? (ClearLogFileAfterGame) i can't find it or is that a command for the program?.

Yesterday,I just opened once and restarted because says "You need to restart Hearthstone,etc" ... i did and then just begins to happen,even now just woke up and i proceed to open first the tracker then Hearthstone and the gold raised. By the way,let me ask you,i only have this problem or also happens to you?.

**Comment by Epix37** [comment]
That's somewhere around line 20 in the config. But if you can't remember changing it for a specific reason you probably didn't. 

Ah I see. And no, I have not had this happen yet (and I restart it a lot :)) but I managed to reproduce it when trying to. The next update will fix that.

**Comment by MACDARK007** [comment]
Ok,thanks for clear the doubts and thanks in advance by this good work about this :+1:. Greetings!
