### ISSUE TITLE
Not working with Gang Up

### ISSUE THREAD

**Issue by zacklytle** [Epix37/Hearthstone-Deck-Tracker#858]
The deck count and card list doesn't show actual when ganging up one of your own minions.

**Comment by Epix37** [comment]
Already fixed for the next update! :)

**Comment by ToonBoon** [comment]
Any way I can convince you to push this update to live? A big reason I use this is that it opens my brain up for other things, for a mill deck actually knowing how much of which card is left in your deck is very important.

Additionally the game not recognizing the deck is a tad annoying.

**Comment by Epix37** [comment]
Not until next weekend at the earliest, BUT *just for you* I uploaded the latest build again: https://github.com/Epix37/HDT-Test/releases (prerelease 3)

**Comment by ToonBoon** [comment]
Amazing, doing killer work, dev! <3
