### ISSUE TITLE
Search field loses focus while removing cards from the deck

### ISSUE THREAD

**Issue by culinko** [Epix37/Hearthstone-Deck-Tracker#860]
This is minor issue, but it's kinda annoying.

It's cool when you type into the search field and click a card you want to add into the deck, the focus still stays on the search window. However, the search field loses focus when you click on the cards you already have in your deck (left column). It would be great if this would work on the left column too.

I also found out if you add more than 9 copies of the same card to an arena deck, the card counter switches to legendary star. I don't know if you could even have 10 copies of the same card in the deck, but it should still count past 9. Randomly stumbled upon this :)

**Comment by Epix37** [comment]
Good point, I can see that being annoying. Works when removing cards, too, now.

Displaying more than 9 as a star is working as intended. Now with Gang Up, that **could** happen in some cases, but that's not worth investing any time into :). Very very rare case,

**Comment by culinko** [comment]
Thanks for the quick fix, much appreciated!
