### ISSUE TITLE
Make "Show opp. deck" button toggle the list

### ISSUE THREAD

**Issue by culinko** [Epix37/Hearthstone-Deck-Tracker#862]
Hey, I use the "Show opp. deck" button very often, I was wondering if you could make the button toggle (show/close) the list, not only show. What I mean is, now it only shows the list and you need to click on the arrow on the top of the list to close it. It would be awesome to be able to click the "Show opp. deck" button again to close the tab as well. So one click opens the list, second click closes the list. I hope you understand what I mean. Thanks a lot :)

**Comment by Epix37** [comment]
Too lazy to move your hand a few inches huh? ;)

Implemented that, plus selecting another game while the flyout is open now loads that deck.

**Comment by culinko** [comment]
Yeah, I guess ever since I started using deck tracker I've become a little spoiled with all these crazy features and I want more :P You are a wizard though, implementing stuff at a speed of light!
