### ISSUE TITLE
Bug with Gazlowe and Flame Leviathan

### ISSUE THREAD

**Issue by illinoiscx** [Epix37/Hearthstone-Deck-Tracker#863]
I was able to see that my opponent had had a Flame Leviathan added to their hand after playing Gazlowe + Mirror Image. No damage was done to any of the characters, so it definitely wasn't a case of it being drawn from their deck. In this case, surely I shouldn't be able to see what card has been created by Gazlowe even if it is Flame Leviathan. I felt like I was cheating and I'm pretty sure this would be against Blizzard rules. Screenshot included, though I didn't realize it wouldn't include the overlay. This is me hovering over the card in my opponent's hand which Hearthstone Deck Tracker tells me is Flame Leviathan: http://i.imgur.com/UhoUj0G.jpg

**Comment by Epix37** [comment]
Most important question: *was* is Flame Leviathan?

**Comment by Epix37** [comment]
Oh, do you have a replay of this game? You can find the replay files in "%AppData%/HearthstoneDeckTracker/Replays" (Win+R, paste).

**Comment by illinoiscx** [comment]
Checked the replay, it was definitely a Flame Leviathan. It was played on the next turn.

**Comment by Epix37** [comment]
Please do upload or email me the replay.

**Comment by illinoiscx** [comment]
Replay attached

**Comment by Epix37** [comment]
That doesn't work if you reply to the github email ;).

epikz37@gmail.com

**Comment by Epix37** [comment]
Alright, I excluded created flame leviathans from the information that reaches the tooltips. Thank you for reporting this.
