### ISSUE TITLE
Cannot Start Application.

### ISSUE THREAD

**Issue by InsidiousDarkstorm** [Epix37/Hearthstone-Deck-Tracker#865]
On loading the Exe file, from the zip download, I get a "Hearthstone Deck Tracker has stopped working." error immediately.

here's the problem details.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Hearthstone Deck Tracker.exe
  Application Version:	0.1.0.0
  Application Timestamp:	551d0e32
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.18409
  Fault Module Timestamp:	53159a86
  Exception Code:	e0434352
  Exception Offset:	0000c42d
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

I had never had this problem before I had to reformat a new hard drive with this silly Dell diskette, which has no drivers on it.

I have been reinstalling drivers and got all of my devices functioning.

Maybe this has something to do with it.

Please help

**Comment by Epix37** [comment]
Try (re)installing .NET 4.5
