### ISSUE TITLE
Application not tracking any of my cards

### ISSUE THREAD

**Issue by knockoutpill** [Epix37/Hearthstone-Deck-Tracker#871]
I installed the application and created my deck in it. The deck shows on my screen when I'm playing the game. I can mouse over the cards and get their respective info. But it doesn't track what I'm drawing. It's as if it hasn't noticed that I started a game.

Do I need to play at a certain resolution? I usually play at 3620 x 2036 windowed. I also tried playing in full screen but there was no change.

OS: Windows 8.1.
.Net version on my machine? 4.5 is supposed to come preinstalled with Windows 8 or higher, so I guess I'm running that. However, the highest version I can see in \windows\microsoft.net\framework is 4.0.30319. HOWEVER, when I try to install 4.5 the installation program tells me "Microsoft .NET Framework 4.5 is already a part of this operating system.  You do not need to install the .NET Framework 4.5 redistributable".

**Comment by Epix37** [comment]
Try restarting hearthstone and/or setting the game path via "options > tracker > settings > set hearthstone path".

**Comment by knockoutpill** [comment]
Setting the path to c:\program files(x86)\hearthstone\hearthstone.exe worked.

Thanks.
