### ISSUE TITLE
Blackrock mountain boss titles still wrong

### ISSUE THREAD

**Issue by anonymous555** [Epix37/Hearthstone-Deck-Tracker#873]
![wrongnossname](https://cloud.githubusercontent.com/assets/8370128/6997446/285e5ca4-db70-11e4-819f-d345eadc414f.png)
The boss title is wrong. For example, the 2nd boss it titled "Jeering Crowd".  Possibly the regular expression for blackrock mountain needs refinement.  See screenshot.

**Comment by anonymous555** [comment]
It's only partially fixed. The name is now fixed on the main screen, but when I got to the stats page, the opponent in the individual game says "The Innkeeper".  Also when I try to show the replay it only shows the old replay viewer, not the new one.

**Comment by Epix37** [comment]
Turns out, the opponent name actually *is* "The Innkeeper" in those games. At least according to the log.

Fixed both those issues now though.
