### ISSUE TITLE
Deck exporter not detecting cards

### ISSUE THREAD

**Issue by dare2move** [Epix37/Hearthstone-Deck-Tracker#876]
On a previous version the exporter would work until 16 cards or so, after which it would still enter the search properly but not mouse over to add the cards. I believe it stops detecting them since I get the message that those cards are missing.

On this version the exporter is unable to detect the cards starting from the first one and is just going through all the searches but never adding the cards.

I have tried messing with export settings, adding a 3 second delay, fullscreen on/off, and windows 7 compatibility mode.

**Comment by Epix37** [comment]
Can you see by how much the click on the card misses? Or is there no click at all?
Please restart HDT, try to export a deck, close HDT. Then go to "%AppData%/HearthstoneDeckTracker/Logs" (Win+R, paste) and upload the hdt_log.txt to www.pastebin.com. Post link here.

**Comment by dare2move** [comment]
Here is the log: http://pastebin.com/09Lyf9id
There is no click at all. The mouse never moves from the search box but the correct cards do get searched and show up

**Comment by Epix37** [comment]
Hm... could you upload a screenshot of your collection screen (deck open)? Could be some sort of resolution thing I suppose. Kinda weird the searching works though.

**Comment by dare2move** [comment]
Hey, I fixed the problem by resetting the program. I'm going to write down everything I tested and post my old config in case it can help you.

Turns out the exporter wasn't hit-or-miss and suddenly stopped working, it just doesn't detect specific cards and which ones are detected is affected by resolution and speed.

-my screen's native resolution is 1920x1080. This in-game resolution seemed to gather the most cards, up to around 17 for my mage deck. The amount of cards sometimes change on a consecutive try but it seemed to gather roughly the same amount fullscreen on/off, and with re-sized windows in this resolution.

-most other in-game resolutions I tried gathered less cards. The other resolutions couldn't detect any cards with fullscreen off except for 1600x900... which seemed to detect just as many cards as the 1920 in all settings.

-different export speeds like 20ms or 60ms affected the cards detected by 1-3 cards but slower or faster was not strictly better. On the slowest speed I could tell the mouse was not just missing the mark

-it could not detect all neutral cards, or any cards in my priest, hunter, and druid deck. Only detected truesilver champion from paladin. Worked on all my mage cards, some warlock, some shaman cards. Didn't test the other classes

At this point I was so confused I just went and deleted the config file from appdata.. not before saving it of course! Here is config.xml: http://pastebin.com/ufjSZH2N
Not sure if same thing this is "config.xml130699939316709358" :http://pastebin.com/5bFjwPKa
Right now I am using the default generated config and everything works :)

**Comment by terroare** [comment]
I have the same issue. Tried almost the same things, with no success.

**Comment by Epix37** [comment]
I actually have the same issue at the moment.

**Comment by Epix37** [comment]
Okay.. I have no idea. 
* Renamed old config, new one was generated. Works.
* Generate diff, check each setting. Still works.
* Restore old config, works...

So: Go to "%AppData%/HearthstoneDeckTracker", rename/delete the config.xml, start HDT and try exporting.

**Comment by mycide** [comment]
I have had these 2 issues as well. I have tried going full screen, removing full screen. slowing the setting. What it looks like to me, is it clicks the first card 3x instead of 2x, and something happens on that third click that makes the searches start to fail. it cant find any cards at that point. to get back to the cards once its ended, i have to type something into the search field, which appears empty to start, then hit the clear button. after that all my cards appear again as they normally do.

**Comment by Epix37** [comment]
Closing in favor of #303
