### ISSUE TITLE
Saving Constructed Decks not showing up

### ISSUE THREAD

**Issue by sp47** [Epix37/Hearthstone-Deck-Tracker#878]
Have done it both manually and with the import from game. No problems with arena decks however.

It seems to save but nothing shows up in the constructed decks. When I go to play and the deck is wrong, a dialog pops up telling me so and asks me to choose. The deck appears there!

**Comment by Epix37** [comment]
Make sure you have "ALL" or "CONSTRUCTED" selected in the bar above the decks and "ALL" in the class-bar. Then try setting  "TRACKER > QUICK FILTER > ALL".

**Comment by sp47** [comment]
yep checked all that, same issue :(

**Comment by Epix37** [comment]
Try closing HDT and then deleting the config.xml in "%AppData%/HearthstoneDeckTracker"  (win + R, paste).

**Comment by sp47** [comment]
that works mate! cheers. love your work.

**Comment by Epix37** [comment]
Great! :)
