### ISSUE TITLE
Hearthstone install directory not found

### ISSUE THREAD

**Issue by DyslexicSloth** [Epix37/Hearthstone-Deck-Tracker#883]
When I start up Hearthstone Deck Tracker it says it can't find my Hearthstone directory. I have Hearthstone installed. I can't import any decks from my game. Strangely I can export decks but after I export a deck I see a list of the cards which just stays on my screen until I close Hearthstone Deck Tracker, it doesn't change when I play a card or even exit out of Hearthstone.

**Comment by Epix37** [comment]
Try setting the patch via `options > tracker > settings > set hearthstone path`

**Comment by DyslexicSloth** [comment]
Nothing happens when I click it. The mouse becomes a loading wheel for a split second but nothing else happens.

**Comment by Epix37** [comment]
Hm.

Try manually editing the config: "%AppData%/HearthstoneDeckTracker" (Win+R, paste), open "config.xml" and set `<HearthstoneDirectory>C:\Program Files (x86)\Hearthstone</HearthstoneDirectory>` to the correct path. Without HDT running.

**Comment by DyslexicSloth** [comment]
Thank you. That fixed all my problems. :D

**Comment by KingZaant** [comment]
I've tried doing all of the above but it wont let me open the "config.xml" file.

**Comment by Epix37** [comment]
You can open it with any text editor.

**Comment by KingZaant** [comment]
what do i set the path too? im really sorry im awful with computers :(

**Comment by Epix37** [comment]
The path of your hearthstone installation.

**Comment by Quadooo** [comment]
The suggested solution did not work for me. When I restart HDT it is sets the xml var back to "  <HearthstoneDirectory />" again.

**Comment by Epix37** [comment]
Did you close HDT before editing the config?

**Comment by Quadooo** [comment]
Yes.

**Comment by Epix37** [comment]
Did you try setting the path via `options > tracker > settings > set hearthstone path`?

Also see if starting HDT as admin has any effect. If neither works and it doesn't, I don't know what the problem could be :/.

**Comment by Quadooo** [comment]
Also tried that. Did not work. As admin did not work. Windows 8 mode did not work either (using windows 10). I also changed my HS path since the path name had a dot in it. But that did not seem to be the issue either. 

Going to reinstall HDT, maybe it will help.

**Comment by Quadooo** [comment]
Well, I do not know what the issue is. HDT seems to have issues with my game path( "D:\Battlenet\Hearthstone"). It will put it in the config.xml if I set the directory with help from HDT `(  <HearthstoneDirectory>D:\Battlenet\Hearthstone</HearthstoneDirectory>).` But when I start HDT again, it doesn't seem to work with it and asks for the directory again.

**Comment by Quadooo** [comment]
Solved the problem bye installing Hearthstone and HDT on my C drive. Probably has something to do with the fact my D drive is a partition of the same physical drive as C.

**Comment by Epix37** [comment]
Very strange. Glad you could make it work though!

**Comment by Quadooo** [comment]
Yeah, I think I had to refer to "D:" bye it's name instead of it's drive letter, but I do not know the proper syntax for that. Or maybe it was something else :)

**Comment by hedaz29** [comment]
Hello Sir/Madam:)

Hope you are well.
I'm trying to edit this config file but  cannot. It's opening in Internet Explorer and I cannot edit the line of <HearthstoneDirectory>
What do I need to do exactly? Reinstall Hearthstone and the deck tracker again on the same partition or?
Thanks

**Comment by hedaz29** [comment]
PS: I'm exceptionally bad with computers...
Sorry for this in advance.

**Comment by hedaz29** [comment]
I moved files around previously between drives because I wanted to move it from SSD to 1TB hard drive, this may be why this problem happened..it was fine before this

**Comment by Quadooo** [comment]
To be able to edit the file here's what you have to do:
step 1: Right click on the file
step 2: choose "Open With" and select "Notepad"
Step 3: Edit

**Comment by hedaz29** [comment]
Hello Sir/Madam,

Thank you very much for your help. I just reinstalled the tracker onto the
C: drive same as where the Hearthstone files were installed on.
Thank you for your help.:)

Have a great week.:)

Best wishes,
Dan
