### ISSUE TITLE
Piloted Shredder

### ISSUE THREAD

**Issue by swith1** [Epix37/Hearthstone-Deck-Tracker#887]
When Piloted Shredder dies in game and a micro machine is summoned it put an Icon of Lotheb on the right hand side.

**Comment by Epix37** [comment]
Maybe loatheb was played/discarded, too? I can't see this hapening otherwise,

**Comment by swith1** [comment]
how can I send you the replay so you can see for urself ? 
 
Date: Fri, 10 Apr 2015 15:51:24 -0700

**Comment by swith1** [comment]
nvm ur right after I read the file.
 
Date: Fri, 10 Apr 2015 15:51:24 -0700
