### ISSUE TITLE
No .exe file

### ISSUE THREAD

**Issue by wrestlingwiz** [Epix37/Hearthstone-Deck-Tracker#888]
I just downloaded the newest release and there is no .exe file to run. I have searched on tutorials and everywhere and I cannot find it in the file. Has something been changed and the guides were not updated?

**Comment by Epix37** [comment]
You need to download "Hearthstone.Deck.Tracker-vX.X.X.zip" under [Releases](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases).

**Comment by wrestlingwiz** [comment]
Thank you
