### ISSUE TITLE
All deck stats lost when update from 0.9.5 to 0.9.10

### ISSUE THREAD

**Issue by Franavalon** [Epix37/Hearthstone-Deck-Tracker#892]
Hi.
A few days ago, I decided to update to 0.9.10 version from my old 0.9.5 version. I didn't update before because I've removed the autoupdate check by error, and I started to miss the new BRM cards.
When I've update the version to the last one, I found that all my deck statistics was lost. However, I could recover the data because an automatic backup.
So, if I use the old version, the statistics can be showed, but If I use the last, stats are lost.
How can I import the stats to the 0.9.10 version from 0.9.5? 
Thx in advance

**Comment by GiggliG** [comment]
Assuming you know where HDT keeps its data (%Appdata%/hearthstonedecktracker) you could try this:

* Make sure HDT isn't running
* Backup your data folder.
* Delete the data folder (HDT) and the install folder
* Do a new install of HDT
* run it once, set up config how you want, shut it down
* From your backup, copy and paste the Deckstats.xml. PlayerDecks.xml, and the Games and Replays folders. Don't copy the config.xml file unless you want to set up again.

Now run HDT and see how it works.

**Comment by Epix37** [comment]
Are your games still there? (stats > games)
If so, this is probably just a filter thing. See if changing the settings in "options > tracker > stats > display" makes any stats show up.

**Comment by GiggliG** [comment]
Oh yes, As Epix knows, I've panicked over what i thought was lost data before but I'd actually set a filter and later forgot about it. So click Tracker -> Quick Filter -> All to check this.

**Comment by Franavalon** [comment]
Thx.
I will try later and I will post the results 

Thx again

**Comment by Franavalon** [comment]
I've followed step by step GiggliG instructions. I can see my decks on tracker, but it shows 0-0 in the stats. :(
Any advide?

**Comment by Epix37** [comment]
> Are your games still there? (stats > games)
If so, this is probably just a filter thing. See if changing the settings in "options > tracker > stats > display" makes any stats show up.

**Comment by Franavalon** [comment]
No, Stats>games is an empty window.
I have more than 6400 games recorded on games folder (C:\....\AppData\Roaming\HearthstoneDeckTracker\Games) and more than 5700 replays under c:\...\replay folder.

I was checking Deckstats.xml file and I find this line on all the games:

 <DeckId>00000000-0000-0000-0000-000000000000</DeckId>

Maybe this is the problem because each game is not referenced to a deck, so my stats are corrupted. Am I right?

**Comment by culinko** [comment]
When you click on stats > games, do you have selected Overall? Because if you have deck selected and the matches are not assigned to a deck, there will be no results.

**Comment by Franavalon** [comment]
Yes, I've selected Overall, but the windows is empty.

Thanksfully I have a backup  of the files that I did yesterday. If you want I can upoad the files.

**Comment by Epix37** [comment]
I thing you can try: restore your backup, delete the config.xml, start v0.9.10. Are the stats still gone?

If so, please do upload your backup,  yea.

**Comment by Franavalon** [comment]
Yes, I did that. I think taht I tried a lot of different ways without results.
Here are my Deckstats.xml and playerdecks.xml file.
http://www.mediafire.com/download/alnu1cx6lqbpbdl/Hearthstone_Deck_Tracker_Stats.7z

**Comment by Epix37** [comment]
I don't quite understand why, or what is happening how this is how it worked for me:
1) Restore backup, delete config.xml
2) Run v0.9.5 (no stats there at this point)
3) Wait for it to automatically restart, stats are now all there
4) Close v0.9.5, run v0.9.10. Stats are still all there.

**Comment by Franavalon** [comment]
I don't know. Probably some header or something similar was corrupted on stats file, but just something which is only necesary for v0.9.10, because v0.9.5 open the stats file without problem, and it continues adding data to the stats file. But  even the file is modified once and again, it can't be open.
Anyway, I assumed that I've lost my old stats and I've started a new ones.

Thx very much for your effords to try to solve my problem. This is an awesome app. Keep doing your best with the project.

Regards

Fran
