### ISSUE TITLE
Stats Filter

### ISSUE THREAD

**Issue by mastermeo** [Epix37/Hearthstone-Deck-Tracker#893]
I would like to be able to filter games displayed in the Stats tab  based on another criteria than the Note FIlter. 

IE 1: Enter an opponent's name to filter games played against that opponent.
IE 2: Enter a class name to filter games played with or against that class.

Thanks, keep up the good work!

**Comment by culinko** [comment]
1) I agree, it could be next to "Note filter". Many times I search for players manually just to see if I already played against them, this would be great if I can just search for their name.
2) You can already filter the opponent class, but not your class. It can be handy too, yeah.

**Comment by Epix37** [comment]
see #692 and #799. Stats screen rework and after/with that. more filters, is coming. Possibly already with v0.10.0 (next release).

2) you can filter both already

**Comment by mastermeo** [comment]
2) Realized that shortly after my message.

Thank you!

**Comment by culinko** [comment]
Damn, I was in the Deck tab and not in Overall, whoops.
