### ISSUE TITLE
Card count on overlay didn't update

### ISSUE THREAD

**Issue by culinko** [Epix37/Hearthstone-Deck-Tracker#897]
This is how the situation occurred:

1) Mage played 2 mad scientists
2) I killed them both and their deathrattles triggered mirror entity and counterspell
3) I triggered both secrets
4) Mage played mirror entity from hand
5) I triggered the secret, but only 1 mirror entity was displayed on the overlay (After match when viewing opp. deck, the number was correct)

Here is the log (it was last game): http://pastebin.com/raw.php?i=LGp7UXYy

**Comment by culinko** [comment]
I'm not sure if it's related, but observed this behavior also with wrath. My opponent played wrath twice, both to draw a card and it was still showing 1 on the overlay. I didn't miss anything, double checked it in opp. deck and in the replay. It was the last match in this log.

Log: http://pastebin.com/raw.php?i=sw7CvuP3
Replay: http://kopasite.net/up/5ki4bw586h17k6n/culinko(Warrior)%20vs%20Azga(Druid)%200225-300415.hdtreplay

**Comment by culinko** [comment]
Observed this again with power word shield. But then I tabbed out to another program, then came back to Hearthstone and the overlay showed correctly two. I hope this helps you more.

**Comment by Epix37** [comment]
Should be working now (v0.10.9)
