### ISSUE TITLE
Show opp. deck - missing images

### ISSUE THREAD

**Issue by culinko** [Epix37/Hearthstone-Deck-Tracker#898]
This issue may be similar to missing images in old replay viewer. I encountered it only one single time and can't reproduce it anymore. This is how it looked like:

![missing-images](https://cloud.githubusercontent.com/assets/11700272/7149517/d36e5eaa-e30e-11e4-832d-3496a03f1def.png)

**Comment by Epix37** [comment]
Yea... this one... used to happen with all the card lists, I still don't really know why it is/was happening.

**Comment by culinko** [comment]
I found out that this bug happens with "Collection Tracker" plugin. Multiple random images are missing every time. Is there anything I could do to help you find out what's causing this issue?

**Comment by culinko** [comment]
Closing in favor of #757.
