### ISSUE TITLE
New Partial Export problem (on deck that used to export fine)

### ISSUE THREAD

**Issue by caldwelljt2** [Epix37/Hearthstone-Deck-Tracker#899]
I have a deck based off one I got on hearthpwn a while back, since that deck is public and it happens with that deck as well, i'll paste the info from it below.

In short, I get 11 card of 30 exported (I own all the cards), and I find a string of jumbled text in the search blank. By jumbled I mean it appears to be out of order (like it clicked in the middle of the string of text and started typing.

The text string I am left with is "lexstrasza raymond swanlandragnaros the firelord greg staplesdr. boom alex garnergadgetzan auctioneer matt dixonazure drake ben zhangantique healbot jesper ejsingviolet teacher james rymanbloodmage thalnos alex horley orlandelli"

I'll past the screen grab too. I tried to confirm my premise above by matching letters to names, since words like "deadly, bloodmage, and agent" appear to smashup something like "dement", however when I noticed the word "james" in the search blank, I couldn't help but notice none of the cards I have in this deck have a "J" (Then again, i'm up REALLY early/late, and I may have overlooked it). So, given that, can anyone take a stab at what is happening?

I have tried adjusting the export settings and reloading/rebooting, but I got the same results. I exported manually for now and haven't seen this affect any other deck (yet). If I get no feedback and/or I just get frustrated and want to troubleshoot it more, I may tackle popping  various cards in/out to see if there is a common culprit (card or other position/naming/etc).

![hearthstone screenshot 04-15-15 04 31 03](https://cloud.githubusercontent.com/assets/9920640/7155298/a6080214-e32b-11e4-8851-688736a24215.png)

Deck I am importing/exporting: http://www.hearthpwn.com/decks/307-miracle-rogue
-----------------------------
p.s.

Cheers and thanks for all the _hard_ work you guys do, good luck with the new curveballs the new cards have thrown at you. I encourage you to "think big" in  terms of how to make this work "future proof" (as I saw worded in another thread), as I know blizzard is going to keep throwing new cards/combinations/counts, and maybe even gui/graphics/etc changes, and i'd love your tool to be ready and not hit hard wih rewrites over-reliance on any one "assumption" that gets broken.

I say this because, in my own humble way, I worked on various WoW plugins a while back, where assumptions in coding caused issues with patches, and those were even working with a published API that would change with little/no notice. I found  the same basic things I did weren't thought threw in terms of "future" possible/impending changes. Often in hind-site, if I had asked myself "what-if" more, and less "blizzard will never _____" I wouldn't have to rewrite whole plugins or parts of plugins.

**Comment by Epix37** [comment]
See #303 :).
