### ISSUE TITLE
Request: Auto Disable Overlay

### ISSUE THREAD

**Issue by zenjury** [Epix37/Hearthstone-Deck-Tracker#906]
something like 'auto disable overlay after XX game' will help improve user skill or memory (for player who need to)

can be set default in option
can choose to hide only some type of overlay
can set for specific deck when make new one (make 20min. warrior reduce default 6 to 2 etc.)

easy way to recall overlay for present game in case of lost track (right click icon in system tray?)

**Comment by Epix37** [comment]
#859 would allow you to hide the over easily at any given time.

**Comment by zenjury** [comment]
wow that's really good function and easy to use too

thank for hard work and fast reply
