### ISSUE TITLE
Cannot sign in to Hearthstats

### ISSUE THREAD

**Issue by kekivelez** [Epix37/Hearthstone-Deck-Tracker#908]
Insert username and password and when trying to sign in returns the following error;
Error: The remote server returned an error (417). Expectation Failed

Here is the Log i recovered from the error 
http://pastebin.com/jnGnhRXJ

**Comment by Epix37** [comment]
Are you using a proxy by any chance? Apparently this can happen with proxys that don't support "100-continue".

Try adding a new file to the HDT folder, called "Hearthstone Deck Tracker.exe.config" and paste this into it: 
```XML
<configuration>
    <system.net>
        <settings>
            <servicePointManager expect100Continue="false" />
        </settings>
    </system.net>
</configuration>
```

Restart HDT, see if you still have that problem.

**Comment by kekivelez** [comment]
No proxies. That configuration file seems to have done the trick though, it signed in

**Comment by kekivelez** [comment]
I'm closing the issue thanks for the response and sorry for reporting back late finals have been killer
