### ISSUE TITLE
Not Working Properly

### ISSUE THREAD

**Issue by Malvagio87** [Epix37/Hearthstone-Deck-Tracker#911]
So i followed the steps as they were given.

1) Download latest release here (green button)
2) Extract file
3) Run "Hearthstone Deck Tracker.exe"
4) Create your decks under "New" (or import from any of the supported websites), click save.
5) Play!

The overlay, overlays the information on the screen, but it does not update the information while i play a game, but seems to work just fine when importing a deck (as can be seen via the attached video).

What could be causing this to happen?

I tried researching more about it but there is no Wiki in regards to what all the features do/mean and i could not find anyone else having this problem.  I also watched video tutorials but they just apparently work right off the bat.

Here is a link to a quick video showing the problem

https://dl.dropboxusercontent.com/u/14308507/Deck%20Tracker%20Issue.mp4 

I am using v0.9.10

Any help would be much appreciated.

**Comment by Epix37** [comment]
Most likely the path to your hearthstone installation is incorrect (for whatever reason).

Try setting it via `options > tracker > settings > set hearthstone path`. (I've heard a few times now that this does not work for some reason - alternaitve: go to `%AppData%/HearthstoneDeckTracker`, open the `config.xml` and set `<HearthstoneDirectory>...</HearthstoneDirectory>` to the correct path.

**Comment by Malvagio87** [comment]
Still not working =(
![still not working](https://cloud.githubusercontent.com/assets/4371991/7304145/48a924d8-e9c3-11e4-8e6b-b12caa8355d4.png)

**Comment by Malvagio87** [comment]
just realized this is ticket 9-1-1 lol

**Comment by Epix37** [comment]
Try this then:
* close HDT and hearthstone
* copy the log.config from [HDT]/Files to "%LocalAppData%/Blizzard/Hearthstone"
* Start both again, see if it works
* if no: check if you find a "output_log.txt" in "Hearthstone/Hearthston_Data" and if so, if it contains any lines starting with "[Power]"

**Comment by Malvagio87** [comment]
Also i noticed this and thought it was strange since the log says im playing a druid and i am.
![still not working 2](https://cloud.githubusercontent.com/assets/4371991/7305743/226e3a3c-e9ce-11e4-85c2-d49d88d25969.png)

**Comment by Malvagio87** [comment]
In the middle of a match currently but i will do that once im done and report back

**Comment by Epix37** [comment]
The log says playing *against* druid :).

But this tells me replacing the "log.config" should do the trick!

**Comment by Malvagio87** [comment]
copied the log.config file
starting it back up now.

**Comment by Malvagio87** [comment]
Appears to be working but after the battle shouldnt the overlay reset or will that only happen when a new battle is started?

![question 1](https://cloud.githubusercontent.com/assets/4371991/7306031/625dcaa2-e9d0-11e4-8d1c-62ee4e4b2b45.png)

**Comment by Epix37** [comment]
Hmm, maybe "dont reset decks after a game" is checked in `options > overlay > general`? Either way it *should* happen when a new game starts.

**Comment by Malvagio87** [comment]
That was checked.

Another "error" i saw was when we started this game, even though i was going first, the chess counter on the left had the other player going first.

**Comment by Malvagio87** [comment]
that seems to happen every time

**Comment by Epix37** [comment]
Yea the timer is a bit wonky.. Turns are not actually 90 seconds either though, but 70 seconds plus the animation delay up to a maximum of another 20 seconds :).
