### ISSUE TITLE
Hearthstone deck tracker has stopped working

### ISSUE THREAD

**Issue by Ryoma1234** [Epix37/Hearthstone-Deck-Tracker#912]
Hello,

I've just downloaded the zip file and when i go to the .exe file to start it up it gives me "hearthstone deck tracker has stopped working"

This is what the problem signature says

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Hearthstone Deck Tracker.exe
  Application Version:	0.1.0.0
  Application Timestamp:	551d0e32
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.18015
  Fault Module Timestamp:	50b83c8a
  Exception Code:	e0434352
  Exception Offset:	0000c41f
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	2057
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Any clue what's going on?

**Comment by Epix37** [comment]
Try reinstalling .NET Framework 4.5.

**Comment by Ryoma1234** [comment]
cheers that worked :)

**Comment by Epix37** [comment]
great :)
