### ISSUE TITLE
Help please.

### ISSUE THREAD

**Issue by PityDude** [Epix37/Hearthstone-Deck-Tracker#915]
I open hearthstone,then open the HsDeckTracker.Nothing happens,notthing appears.How to solve this problem?I tried opening HsDT as administrator still doesen't work...

**Comment by Lexandur** [comment]
I have the same problem, currently trying to run it on windows 7.

**Comment by PityDude** [comment]
Mee too on windows 7 :(

**Comment by Lexandur** [comment]
FIXED.
The problem was the .net frameworks 4.5
Install it and it will work fine.

**Comment by PityDude** [comment]
Thanks friend!
If you want to have some friendly matches add me on hearthstone :) My name is GetRekt :+1:
:8ball:
