### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by PityDude** [Epix37/Hearthstone-Deck-Tracker#916]
I open hearthstone,then i open the deck tracker..Then?How to make the deck tracker appear in HearthStone?Please write step by step how to.
![hsdt](https://cloud.githubusercontent.com/assets/12120269/7336972/1ed52d24-ec1f-11e4-998f-1a4df6fa8dda.jpg)

**Comment by GiggliG** [comment]
In your screenshot, the deck tracker is *already* appearing in hearthstone. See the white text at both sides of the heathstone window?

What you need to do in HDT is go to New menu, and create the deck that you are using. Do this for each deck. (If you are using decks found online, you can usually use the import menu to import them into HDT).

Once you have your decks created in HDT, it will display properly in hearthstone.

**Comment by Epix37** [comment]
Thanks @GiggliG
