### ISSUE TITLE
Opponent Names no longer show up in latest version (Apr 28, 2015)

### ISSUE THREAD

**Issue by Mistrelvous** [Epix37/Hearthstone-Deck-Tracker#919]
When you look at past games, opponent names no longer show up. If you played a Hunter, it now just says "Hunter" and if you played Mage, it now just says "Mage" instead of user's battlenet Tag/name.

**Comment by GiggliG** [comment]
I came here to post this issue too.
Note: names from before the update show perfectly well. For new games, HDT now seems to be storing the class name in place of opponents name.

**Comment by Epix37** [comment]
Thanks for the clarification. Will most likely be fixed with v0.10.1 this weekend (or earlier if a more severe issue shows up).

**Comment by dvide** [comment]
Think this fixes it. It was searching the key space rather than the value space of the [`HeroIdDict`]([https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/48688655a5b5ff6bed1797dcc4b3afd0f6ec3b15/Hearthstone%20Deck%20Tracker/Hearthstone/CardIds.cs#L99-L112]).

**Comment by Epix37** [comment]
Looks like that should do it, yes. Thanks!

**Comment by Epix37** [comment]
All the names will now be automatically fixed with the next update, if the game has a replay attached.

**Comment by Contributor2008** [comment]
, it started after a recent update.  Looking forward to the fix, thanks!

**Comment by Epix37** [comment]
fixed with v0.10.1
