### ISSUE TITLE
Where Did Hearthstats Integration Go?

### ISSUE THREAD

**Issue by mkrain** [Epix37/Hearthstone-Deck-Tracker#920]
After updating to 0.10.0 the hearthstats functionality is missing.  The main page mentions it in the import menu but it's nowhere to be founds.  Has this been removed, and if so why no mention of in the changelog?

**Comment by Epix37** [comment]
You can find the hearthstats menu under "plugins"  now. Even though it's not actually a plug-in, I'm running out of space in the menu bar :).

**Comment by mkrain** [comment]
Got it, thanks.
