### ISSUE TITLE
A new bug after I update version 0.10.0 

### ISSUE THREAD

**Issue by chucklu** [Epix37/Hearthstone-Deck-Tracker#921]
Status  menu
the detail for game,
the name of opponent is shown as class

**Comment by chucklu** [comment]
![qq 20150429201719](https://cloud.githubusercontent.com/assets/3004057/7390639/bb5cfd68-eeac-11e4-9f73-b6c2ab941242.png)
here is the picture

**Comment by Epix37** [comment]
See #919.
