### ISSUE TITLE
Plugins using the newest version of MahApps won't work.

### ISSUE THREAD

**Issue by yuantliu** [Epix37/Hearthstone-Deck-Tracker#924]
Hey all, I'm attempting to develop a plugin for the program that brings up a GUI that lets you calculate Mad Bomber/Arcane Missile/Knife Juggle odds.
A heads up for all the plugin developers, I was attempting to use the MahApps.Metro framework for my GUI (which is the framework used in HDT), but my plugin won't load. After some debugging, I found out that the MahApps version used by my plugin is 1.1.2.0 (newest one from NuGet) but HDT is still using 1.1.1.0. I switched MahApps off for my plugin and used regular WPF and the plugin was able to load successfully.
Hopefully this will save all the plugin developers some time and maybe we can get the MahApps version that HDT uses updated for the next release.

**Comment by Epix37** [comment]
Updated to 1.1.2.0 now for next release.

**Comment by yuantliu** [comment]
MahApps works now for the plugins. Thanks.
