### ISSUE TITLE
Plugin development: add status on board to Entity class

### ISSUE THREAD

**Issue by yuantliu** [Epix37/Hearthstone-Deck-Tracker#927]
I'm writing a plugin and I'm having trouble determining if an entity is a minion that's on the board or not.

Maybe I'm clueless but when I'm trying to iterate through Hearthstone.Game.Entities dictionary, I can't tell if the values are minions in hand, minions on the board, spell in hand, or even the hero power. It would be nice to have an attribute in the entity class that makes clear whether the card is a spell or a minion or hero power or weapon and whether it's on the board or not.

**Comment by Epix37** [comment]
[This](https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/Replay/ReplayViewer.xaml.cs#L220) is how I get that kind of information in replays. But I agree, having those as entity properties would be handy. 

You might also want to check out the debug window, found via "options > tracker > logging (turn on in settings) > debugwindow"

**Comment by Epix37** [comment]
I added a few properties now (see c058cd9).

```
IsOpponent,
IsMinion,
IsWeapon,
IsInHand,
IsInPlay,
IsInGraveyard,
IsInZone(zone)
IsControlledBy(id)
```

TAG_CARDTYPE.SPELL does apparently not exist, and since my game won't start at the moment apparently, I'm not sure how to deduce that. So IsSpell is missing for now.

Suggestions for any others?
