### ISSUE TITLE
Hero Powers not logged correctly

### ISSUE THREAD

**Issue by anonymous555** [Epix37/Hearthstone-Deck-Tracker#928]
It looks like player and opponent hero power usage is not being logged correctly.  See here in function

Analyze

in 

HsLogReader.cs

You set 
											_playerUsedHeroPower = true;

or 

		_opponentUsedHeroPower = true;

So they are both set to true, but never set back to false.
Think they need to be set back to false, otherwise we only see the hero power logged once.

if(playerEntity.Value != null && playerEntity.Value.GetTag(GAME_TAG.CURRENT_PLAYER) == 1 && !_playerUsedHeroPower
								   || opponentEntity.Value != null && opponentEntity.Value.GetTag(GAME_TAG.CURRENT_PLAYER) == 1 && _opponentUsedHeroPower)
								{
									var card = Game.GetCardFromId(id);
									if(card.Type == "Hero Power")
									{
										if(playerEntity.Value != null && playerEntity.Value.GetTag(GAME_TAG.CURRENT_PLAYER) == 1)
										{
											_gameHandler.HandlePlayerHeroPower(id, GetTurnNumber());
											_playerUsedHeroPower = true;
										}
										else if(opponentEntity.Value != null)
										{
											_gameHandler.HandleOpponentHeroPower(id, GetTurnNumber());
											_opponentUsedHeroPower = true;
										}
									}
								}

**Comment by Epix37** [comment]
fixed, thanks
