### ISSUE TITLE
The "Ragnaros-Majordomo" problem (similar to Stalagg-Feugen)

### ISSUE THREAD

**Issue by alex9801** [Epix37/Hearthstone-Deck-Tracker#932]
The new "Majordomo Executus" card has the string "Ragnaros the Firelord" in the description, which is an individual card name at the same time.

This may cause some problem when exporting deck, if the deck includes ragnaros but there is no golden ragnaros in the collection.

Adding "Golden Ragnaros the Firelord" checkbox might be appropriate.

**Comment by Epix37** [comment]
Cards are searched as "[cardname] [artistname]". Stalagg and Feugen are done by the same artist, Ragnaros and Majordomo are not, should be no problem.

**Comment by dvide** [comment]
Just noticed the 3 mana Warrior spell Charge has this issue with Kor'kron Elite, since Kor'kron Elite has the word Charge in its card text and they both share the same artist: Alex Horley Orlandelli.

**Comment by Epix37** [comment]
Since you get the golden version of charge pretty early on (level 23 and 26), and charge is the first card in the list, this is probably likely not a problem for most people.

But yea.. might have to add the cardtype/rarity to the search again in some cases. Or just for all cards by default?
