### ISSUE TITLE
HS localization issue (related to Stalagg-Feugen problem)

### ISSUE THREAD

**Issue by alex9801** [Epix37/Hearthstone-Deck-Tracker#933]
In the current card pool, the only card pair which has the other one's name in the description(or name itself) is Stalagg-Feugen (+ Ragnaros-Majordomo)

But this is based on one language : English.
In other language settings, there is some more pairs like above.

For example, "Duplicate" and "Mirror Image" are translated to "복제" and "환영 복제" respectively in Korean localization.

Providing different checkboxes for different language settings seems absurd, but I just wanted the problem to be mentioned, at the very least.

**Comment by Epix37** [comment]
See my response in #932. This is a very unlikely problem.
(Duplicate and mirror image, again, have different artists)

If you are aware of any specific cases, I would be happy to fix them.
