### ISSUE TITLE
Changed Assembly Name

### ISSUE THREAD

**Issue by Epix37** [Epix37/Hearthstone-Deck-Tracker#934]
Per request (to make controls reuseable in plugins) I removed the whitespaces from the assembly name and adjusted everything accordingly (0f88a23). 

If anyone can think of implications I did consider, please let me know!

**Comment by terroare** [comment]
What do you mean more specifically?
How can I help?

**Comment by Epix37** [comment]
Nothing specifically. I just worried doing this may have sideeffects I didn't see. Everything seems to be fine though.
