### ISSUE TITLE
Import from constructed only showing instructions

### ISSUE THREAD

**Issue by SammyTheBEAST** [Epix37/Hearthstone-Deck-Tracker#935]
I have an issue with import from constructed. When I press the button it shows the instructions, after I do everything it says I click on the button again and the instructions pop up again. I did this around 5 times restarting twice and I still haven't been able to import my Hunter deck. I did setup up constructed importing and no error message pops up. Please help!

**Comment by Epix37** [comment]
Try restarting hearthstone and/or entering the "Play" screen once before starting the importing process.

**Comment by SammyTheBEAST** [comment]
Got it working, accidentally changed the where the hearthstone file was. I also found that when exporting to hearthstone it types in the artists name which causes trouble when finding stalagg and feugen. It also had trouble finding burly rockjaw trogg in all of my decks which then slows down the export and makes some high cost cards not get exported (I also tried to slow it down but it didnt change anything).

**Comment by Epix37** [comment]
Do you have golden versions of stalagg / feugen? You need to specify that in "options > tracker > exporting". The artist name should not cause any trouble.

What exactly do mean mean "trouble finding burly rockjaw trogg"?

I guess that depends on the game resolution you set. You can also adjust the scaling / opacity of the card lists via "options > overlay > player/opponent".

**Comment by SammyTheBEAST** [comment]
I do not have golden versions of them

When it gets to finding the trogg it stops, waits around 10 seconds then finishes the deck and gives an error saying it couldnt find the trogg and I may need to craft one although I have 2.

Hmm, it doesnt look like my game resulution is doing anything to help that, if I scaled down the list anymore I couldnt see the images or words :P

**Comment by culinko** [comment]
It searches for "Burly Rockjaw Trogg Chris Rahn":
![hearthstone screenshot 05-05-15 00 49 15](https://cloud.githubusercontent.com/assets/11700272/7464179/ef298810-f2c0-11e4-815e-09bc333c67a7.png)

But the artist should be Aleksi Briclot:
![hearthstone screenshot 05-05-15 00 49 15](https://cloud.githubusercontent.com/assets/11700272/7464193/0c85b992-f2c1-11e4-8f4a-0ba71202e1ed.png)

**Comment by Zildjian299** [comment]
same problem and it dont keep track of cards i draw or have or play nor the oppnent.
