### ISSUE TITLE
import from : http://www.hearthstone-decks.com won't work

### ISSUE THREAD

**Issue by TonioFrance** [Epix37/Hearthstone-Deck-Tracker#936]
hello,
i try to import a deck : http://www.hearthstone-decks.com/deck/voir/mtrochenoire-seigneur-immortel-9393
to hearstnoe deck tracker Version : 0.10.0

it's says : 
could not load deck from specified url

best regards.
antoine

**Comment by Epix37** [comment]
Was fixed just today with #931 :).

**Comment by TonioFrance** [comment]
Arf !
sorry !
i've just read the open error, not the close one !
thank a lot !!
