### ISSUE TITLE
Region no longer updates correctly when switching regions

### ISSUE THREAD

**Issue by Contributor2008** [Epix37/Hearthstone-Deck-Tracker#937]
Great product, I love the features of the Tracker.  One thing I've seen within the last couple of updates is this, however.  I log into BN & start playing on a particular server, finish up my games there and then select another region from the pick list & play some more games there.

The stat's page in HDT will show all of the games as being played on the initial server/region that I started out on i.e. I play 2 games on US server, switch to Europe and play 3 there, but the Tracker reflects all 5 of them as being on US.

I can make it recognize the change in servers if I close HDT and re-open it after I switch servers.

Thanks for looking into this.

**Comment by Epix37** [comment]
should be fixed with v0.10.1
