### ISSUE TITLE
Ability to store the entire hs log automatically

### ISSUE THREAD

**Issue by culinko** [Epix37/Hearthstone-Deck-Tracker#938]
Perhaps this could be added as a plugin, if you don't want this functionality in the core.

Currently, the only thing that is saved is the match itself, which is saved in the replay file. I would like to be able to save more stuff, e.g. arena draft, arena rewards, pack openings and more. So if any new features/plugins will be added in the future, you would already have the data ready for them. Do you think it will be possible somehow to store the entire log somewhere?

**Comment by Epix37** [comment]
That *is* basically the entire log. Nothing about arena drafts/rewards, etc. is logged.

**Comment by culinko** [comment]
Are you sure? There is some arena tracker that claims otherwise. "Arena Tracker reads the Hearthstone log to keep track of your arena games and rewards."

https://www.reddit.com/r/ArenaTracker/comments/2tyhmd/arena_tracker/

**Comment by Epix37** [comment]
Huh, rewards actually are. TIL. I'm pretty sure that's it though.

As far as I know there is no way to track anything other than the selected class when it comes to arena.

**Comment by culinko** [comment]
So, would it be possible to store that info somewhere? Basically what I would like to have is the first thing from #875. I know I can screenshot the rewards screen manually or write the info down, but I'm pretty sure having the tracker do it automatically would be so much better. If there is no other important stuff in the log than the rewards and hero selection, you can close this issue I guess. I just wanted to find a way to not lose the valuable info from the log in case more stuff gets implemented later on.

**Comment by culinko** [comment]
Okay, so I enabled all txt logging and found out these things are logged:

- Arena (drafting state, complete deck state, reward state, no draft state). [Ben] handles those. Timestamps are switched because I finished one run and then captured the drafting phase of next run after that. Unfortunately, I think you can't trace the drafting picks or the complete deck anywhere.

D 18:57:38.6403044 DraftManager.OnBegin - Got new draft deck with ID: 323195012
D 18:57:38.6413045 SetDraftMode - DRAFTING
D 19:03:25.1234860 SetDraftMode - ACTIVE_DRAFT_DECK <i>(you get this line every time you click on "Arena" menu entry or after every arena match if you have an active arena deck)</i>
D 18:55:37.1950862 SetDraftMode - IN_REWARDS
D 18:57:33.4161660 SetDraftMode - NO_ACTIVE_DRAFT

- Arena hero pick. [Rachelle] handles those:

D 18:57:43.2464265 DraftManager.OnChosen(): hero = HERO_08

- Arena rewards. [Rachelle] handles those as well:

D 18:55:37.2320872 DRAFT REWARDS:
D 18:55:37.2340873 	reward 0=[BoosterPackRewardData: BoosterType=9 Count=1 Origin=UNKNOWN OriginData=0]
D 18:55:37.2350873 	reward 1=[GoldRewardData: Amount=40 Origin=UNKNOWN OriginData=0]
D 18:55:37.2370873 	reward 2=[GoldRewardData: Amount=25 Origin=UNKNOWN OriginData=0]
D 18:55:37.2390874 	reward 3=[GoldRewardData: Amount=150 Origin=UNKNOWN OriginData=0]

- Not sure, but after I opened pack with one rare and one epic, some sounds were unloaded by [Asset]. But I don't know what happens if you open multiple of the same rarity or more packs.

D 19:05:38.1320106 CachedAsset.UnloadAssetObject() - unloading name=VO_ANNOUNCER_EPIC_26 family=Sound persistent=True
D 19:05:38.1340107 CachedAsset.UnloadAssetObject() - unloading name=VO_ANNOUNCER_RARE_27 family=Sound persistent=True

**Comment by culinko** [comment]
I added all stuff to #875, I don't think I need this issue open anymore, now that I know what is and what isn't logged.
