### ISSUE TITLE
Burly rockjaw trogg export

### ISSUE THREAD

**Issue by SammyTheBEAST** [Epix37/Hearthstone-Deck-Tracker#939]
When I export a deck that has the burly rockjaw trogg it says:
"The following cards were not found:
Burly Rockjaw Trogg
You need 40 dust to craft this card"
I have 2 of these cards, not golden, in my collection. I have noticed when it tries to find the card hearthstone says its not found. I love this program and the export and import feature is amazing.

**Comment by culinko** [comment]
Yeah, see my comment: https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/935#issuecomment-98879408

**Comment by SammyTheBEAST** [comment]
Is there a manual way to fix this until a new patch comes out? Almost all of my decks have them :P

**Comment by Epix37** [comment]
There is indeed a way to manually fix it:
open "[HDT]/Files/cardDB.enUS.xml" and change the `<Artist>` in line 14540 (or just search "burly").

**Comment by Epix37** [comment]
Fixed now. Seems like the artist was changed by a recent patch.

**Comment by SammyTheBEAST** [comment]
Can you add an option to change weather to search artists or not?

**Comment by Epix37** [comment]
Why would you not search for the artist? It solves a lot of problems.

I don't think Blizzard changing artist names is going to be something happening on a regular basiss.
