### ISSUE TITLE
Bat file

### ISSUE THREAD

**Issue by Sjafen** [Epix37/Hearthstone-Deck-Tracker#941]
@echo off
start "" "C:\Program Files (x86)\Hearthstone\Hearthstone Beta Launcher.exe"
start "" "C:\Program Files (x86)\Hearthstone Deck Tracker\Hearthstone Deck Tracker.exe"

Is this all i gotta do ? And where do I put it ? I cant seem to find any *exe file in the download and so on...
Newbie

**Comment by Sjafen** [comment]
I found out how to create the file but the program does not start. there is no exe file.

**Comment by culinko** [comment]
https://github.com/Epix37/Hearthstone-Deck-Tracker/releases

Click the first link in Downloads section.
