### ISSUE TITLE
Display stats in multiple modes in deck selection

### ISSUE THREAD

**Issue by culinko** [Epix37/Hearthstone-Deck-Tracker#945]
Hi, I just started to play arenas again and was wondering if you could add separate option to Options/Tracker/Stats/Display for arena games. What I mean is, currently you can only select one mode to display, e.g. I have displayed stats for selected version/ranked/all time. But it displays 0-0 for arena decks (because ranked is selected). If I select arena, the arena decks now have their winrate next to them, but ranked decks don't (for obvious reasons). Could you add another option for arena decks too? So there would be 2 sets of options, one for constructed and one for arena, so I could be able to see both ranked and arena winrates at the deck selection screen. It would be awesome, thanks! :)

**Comment by Epix37** [comment]
I guess the easier solution would be to have arena decks not affected by the selected mode at all. Doesn't make much sense anyway.

**Comment by culinko** [comment]
Great work, thanks!
