### ISSUE TITLE
Feature request: custom view filters

### ISSUE THREAD

**Issue by VicTT** [Epix37/Hearthstone-Deck-Tracker#947]
The thing that's missing from the view filters is a NOT filter..Implementing that, though, I feel would probably make the UI cluttered or at least require a redesign. Therefore, in the interest of not wasting anybody's time, I suggest implementing just a button (possibly under expert settings) that allows you to input a text filter that specifies what you're looking for, under whatever syntax you want. Parsing an expression like that shouldn't take much work; I'm thinking something like:
"NOT CategoryName1 AND (CategoryName2 OR CategoryName3)" should be the most you could ever expect to parse. You might think it's not relevant, but trust me, after having more than 30 decks imported into the tracker, it becomes a nightmare to filter without having a working NOT filter. It's impossible to shove things in meaningful categories without significant overlap, It makes sense for the user to want to see, for instance, NetDecks, not from Kolento, Constructed, not Aggro.
Since you mentioned that the plugin system deals/would deal poorly with the UI, I figured this is probably something to be done within the main program.

**Comment by Epix37** [comment]
Closing in favor of #2110.
