### ISSUE TITLE
CLR20r3

### ISSUE THREAD

**Issue by melthephoenix** [Epix37/Hearthstone-Deck-Tracker#949]
After I reinstalled microsoft NET v4.5 I tried to open the programm and it shown this (by the way sory about that but my PC has Greek language on it). Any suggestions:
  Όνομα συμβάντος προβλήματος:	CLR20r3
  Υπογραφή προβλήματος 01:	Hearthstone Deck Tracker.exe
  Υπογραφή προβλήματος 02:	0.1.0.0
  Υπογραφή προβλήματος 03:	553fc356
  Υπογραφή προβλήματος 04:	mscorlib
  Υπογραφή προβλήματος 05:	4.0.30319.34209
  Υπογραφή προβλήματος 06:	534894cc
  Υπογραφή προβλήματος 07:	27cb
  Υπογραφή προβλήματος 08:	0
  Υπογραφή προβλήματος 09:	System.Windows.Markup.XamlParse
  Έκδοση λειτουργικού συστήματος:	6.1.7601.2.1.0.256.1
  Αναγνωριστικό τοπικών ρυθμίσεων:	1033
  Πρόσθετες πληροφορίες 1:	0a9e
  Πρόσθετες πληροφορίες 2:	0a9e372d3b4ad19135b953a78882e789
  Πρόσθετες πληροφορίες 3:	0a9e
  Πρόσθετες πληροφορίες 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by Epix37** [comment]
Try reinstalling .NET 4.5 *again* or repairing it.

**Comment by melthephoenix** [comment]
How can I repair it because reinstallation isn't a good option

**Comment by melthephoenix** [comment]
It didn't work. I have .NET 4.5.2 you think this may be the problem?

**Comment by Epix37** [comment]
Shouldn't be the problem, no.
Try this maybe: http://www.personalcomputerfixes.com/general-errors/how-to-fix-clr20r3-error/

**Comment by Epix37** [comment]
I think the link above is specific to other software, sorry. Possibly try downloading a fresh copy of HDT? Or maybe installing an older version of .NET might work, who knows,
