### ISSUE TITLE
Sync Error Handling

### ISSUE THREAD

**Issue by livejamie** [Epix37/Hearthstone-Deck-Tracker#950]
Sync didn't appear to be working for me today. I went to the Hearthstats page and I get

> This website is under heavy load

> We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.

I assume this is why sync isn't working. Maybe some sort of indication that Hearthstats isn't responding or something would be a good idea.

**Comment by Epix37** [comment]
Added error notifications

![errors](https://cloud.githubusercontent.com/assets/7737910/7665622/37341fea-fbc1-11e4-83f7-5e08a63ab707.PNG)
