### ISSUE TITLE
After renaming arena deck, the deck name stayed the same in stats

### ISSUE THREAD

**Issue by culinko** [Epix37/Hearthstone-Deck-Tracker#951]
This is how it happened: I played a couple of arena matches without having any deck selected in the deck tracker. After that, I created an arena deck called "something" and moved the matches into the deck. Then I renamed the deck to "Arena 11-05 03:00". The deck is still called "something" in stats/games. Is this the intended behavior? I fixed this when I moved the matches to the newly renamed deck again.

**Comment by Epix37** [comment]
I could see an argument both ways, but I think updating the names makes sense.

Now, doing this with arena decks seems to work perfectly fine, constructed seems to require restarting HDT for it to take effect but that shouldn't be too big of a deal.
