### ISSUE TITLE
Deck sorting

### ISSUE THREAD

**Issue by culinko** [Epix37/Hearthstone-Deck-Tracker#952]
Is there any possibility to sort decks? I like how the constructed decks are sorted, by class. But in case of arenas, I would like to sort them by creation date. Would it be possible to add some sorting methods for each deck tab (constructed, arena, all)?

**Comment by Epix37** [comment]
You can sort via `TRACKER > SORT / FILTER`. That always keeps the class order though. 

Splitting that and/or allowing more freedom might be a good idea.

**Comment by culinko** [comment]
Also, sorting by winrate could be useful, too.

**Comment by Epix37** [comment]
Also already exists. 

I added an option to disable the forced class sorting:
![sort](https://cloud.githubusercontent.com/assets/7737910/7586027/e4496f80-f8a8-11e4-80ed-24b96ed5b1c0.PNG)

This is across all tabs, but should do the trick. (and mainly: was quick to implement :))

**Comment by culinko** [comment]
Oh, I'm blind, my fault. Tbh the "Tracker" menu is kinda unintuitive, I was expecting to find the sorting and filters elsewhere (initially I was trying to right click the search button, lol). Not sure if it's just me or someone else feels the same. But I can get used to it, though.

**Comment by dantedog** [comment]
Hijacking this a little bit. @Epix37 Is there a way to show all decks (including archived) at one time?

**Comment by dantedog** [comment]
And while I'm thinking about this, does a sort by last played/stats updated option make sense?

**Comment by Epix37** [comment]
You hold CTRL and then select "ALL" and the archived icon in the class bar. 

I thought about adding "last used", too. Might make it into the next version, not sure yet.

**Comment by dantedog** [comment]
Thanks!
