### ISSUE TITLE
Getting a spare part makes HDT think your deck doesn't match the selected one

### ISSUE THREAD

**Issue by NightKev** [Epix37/Hearthstone-Deck-Tracker#957]
When I killed my opponent's Mechanical Yeti, when I got the spare part it said "Warning: Card doesn't match deck" (or something to that effect) in the top left and I had to tell it to save the game even though it didn't match after the game ended.

**Comment by culinko** [comment]
Another example: As Warlock, I stole Malorne with Sylvanas, then suicided him and the tracker displays the warning now.

**Comment by mvordeme** [comment]
Yet another example: A Webspinner gave me Malorne, and when it died, I got the warning and Malorne was not added to the deck.

**Comment by 305jeff** [comment]
I have the same issue with spare parts and unstable portal. I tried deleting the entire HSDT folder and re-downloading...left the appdata folder untouched except I copied over the new log.config as suggested.

**Comment by mvordeme** [comment]
Today, the Malorne thing happened again, and I got the idea that maybe culinko's and my reports are actually related to #1046. It seems that the tracker can't deal with duplicate occurrences of legendary minions.

**Comment by culinko** [comment]
It's not about duplicate legendary minions, it's about Malorne not being originally in the deck.

**Comment by mvordeme** [comment]
Then why does it work in other cases? Spare parts don't seem to be a problem for me, for example. Webspinner and Unstable Portal are usually working, too. Even Malorne is not a problem as long as he doesn't die and gets added to the deck a second time. I have only seen this kind of problem with legendary minions, lately.

**Comment by culinko** [comment]
"Even Malorne is not a problem as long as he doesn't die and gets added to the deck" - This is the important part. He gets added to the deck as a 31st card. Spare parts and unstable portal add cards to your hand, not to your deck. The card that add stuff to your deck (Gang Up) has been fixed already, but seems like Malorne hasn't been. As for spare parts, I didn't have any problems with them, just OP had.

**Comment by mvordeme** [comment]
It was just an idea after re-reading #1046. Sneed's Old Shredder *is* part of the deck and it brought up the warning when caught in a Freezing Trap. I don't remember having any trouble with Freezing Trap on other occasions.

**Comment by 305jeff** [comment]
I stopped playing the mage deck so I'm not seeing the same errors with unstable portal and spare parts...but I just played against a warrior with Iron Juggernaut and it seems like drawing the bomb caused it to think I played the wrong cards again...there's definitely still something wrong.

**Comment by mvordeme** [comment]
Just another hint that it might be connected to legendary minions and not primarily to whether they are added to your hand or to your deck: I had Chromaggus on the board when I drew Rend Blackhand twice, and the warning was displayed.

**Comment by culinko** [comment]
Oh, you might be onto something, actually. It could be related to the Legendary limit 1 (because you can't have 2 of the same legendary in your deck). You are right.

**Comment by Tmarty** [comment]
+1, got this bug yesterday after Malorne from my webspinner died.

**Comment by culinko** [comment]
Alright, I tried to reproduce drawing double legendaries from Chromaggus in current version, there were no errors.

So the only issue here seems to be Malorne created from outside of the deck (Webspinner, Unstable Portal).
