### ISSUE TITLE
PC crashed after the game ended and it did not update the deck stats.

### ISSUE THREAD

**Issue by Kiougar** [Epix37/Hearthstone-Deck-Tracker#958]
Is it possible to manually increase loss count on one deck? Because, after my PC crashed I can't set the losses to 3...

**Comment by Epix37** [comment]
Yea you can manually add games: Select your deck, click "STATS" in the menu bar: `Deck > Games > add new game`

**Comment by Kiougar** [comment]
Ok done. I think there should be an option in the right click context menu of each deck to Add Games.
Also, it's now a 3 loss deck but it still has the white background (where it should be a green I suppose).

**Comment by Kiougar** [comment]
Nevermind, the background color is the class I played. I just realized that! Closing this issue!
