### ISSUE TITLE
Deck Tracker does not not recognize cards

### ISSUE THREAD

**Issue by Borsock** [Epix37/Hearthstone-Deck-Tracker#959]
The window where all teh cards are, stay all the time the same, no cards are descountes for the list.

**Comment by Epix37** [comment]
* Try restarting HDT and Hearthstone
* Make sure `<HearthstoneDirectory>...</HearthstoneDirectory>` in the config.xml in "%AppData%/HearthstoneDeckTracker" (Win+R, paste) is set to the correct path
* Copy the "log.config" from "[HDT]/Files" to "%LocalAppData%/Blizzard/Hearthstone" and overwrite the existing one

**Comment by Borsock** [comment]
I dont have any archive call "log.config" on [HDT]/Files

**Comment by Epix37** [comment]
Then redownload the latest version again here: https://github.com/Epix37/Hearthstone-Deck-Tracker/releases, and extract/overwrite everything.
