### ISSUE TITLE
Spectated games were not properly fixed after 0.10

### ISSUE THREAD

**Issue by VicTT** [Epix37/Hearthstone-Deck-Tracker#962]
![spectated](https://cloud.githubusercontent.com/assets/2959425/7641170/98e5fbe6-fa90-11e4-9f5e-4e3c8b00e022.png)
Forgive my handwriting.

**Comment by Epix37** [comment]
Do those games have replays?

**Comment by VicTT** [comment]
Yep. And on that note, the games didn't take 0 turns either. That's something I noticed a long while ago...assumed you were aware of it/fixing it..
P.S. Looked for replays in replay folder; at least 2 of them (the Rogue ones at the bottom have replays). Also there's "Halg(Druid) vs UNKNOWN HUMAN PLAYER(Shaman) 0235-080515.hdtreplay" in the replay folder that's not showing up.

**Comment by culinko** [comment]
Is this still an issue?

**Comment by culinko** [comment]
Closing in favor of #1917.
