### ISSUE TITLE
Saving a deck screenshot should use a different date template

### ISSUE THREAD

**Issue by NightKev** [Epix37/Hearthstone-Deck-Tracker#969]
"[deckname] DD-MM HHmm.png" doesn't sort well at all, it should be something like "[deckname] YYYY-MM-DD HHmm.png" (or better yet, have a customizable template so that we don't have to manually set the filename each time).

**Comment by Thristle** [comment]
when i save a deck as a screenshot (from the export menu) the "save as" dialog opens and default name is the deck name. 
can you specify how to do your kind of save?

**Comment by NightKev** [comment]
It would be the same, except it would auto-fill the filename differently.

**Comment by Epix37** [comment]
I think what he is referring to is that the default file name is "[deckname].png", not "[deckname] DD-MM HHmm.png".

**Comment by Thristle** [comment]
But there is no date template right now.

**Comment by NightKev** [comment]
I guess I am referring to the "import from Arena" deck naming template... oops. I completely forgot that that names the deck with a date... so I guess THAT'S what I want changed lol.

**Comment by Epix37** [comment]
Here we go: 

![1](https://cloud.githubusercontent.com/assets/7737910/7667793/ee0efc88-fc18-11e4-9831-786b041dfd6c.PNG)
![2](https://cloud.githubusercontent.com/assets/7737910/7667794/f029efd2-fc18-11e4-82cb-c6b06561b925.PNG)
![3](https://cloud.githubusercontent.com/assets/7737910/7667795/f1c7d070-fc18-11e4-876f-f8beabb3d7e5.PNG)

**Comment by NightKev** [comment]
Seems great to me!
