### ISSUE TITLE
Restore deleted decks

### ISSUE THREAD

**Issue by Burz14** [Epix37/Hearthstone-Deck-Tracker#970]
Is there a way to retrive deleted decks and undelete them? And also, is there a way to only delete a version of a deck without deleting it as a whole?

**Comment by Epix37** [comment]
Question 1: Kind of. HDT generated daily backups stored in "%AppData%/HearthstoneDeckTracker/Backups". Depending on how much stats/decks you would lose this might be work it. No other way to "undelete" decks.

Question 2: Currently there is not.

**Comment by Burz14** [comment]
thanks for the quick help, the backups worked just fine
