### ISSUE TITLE
Duplicates in Opponent Deck (Solo Adventure)

### ISSUE THREAD

**Issue by mvordeme** [Epix37/Hearthstone-Deck-Tracker#971]
When playing a BRM match against Vaelastrasz, some of the cards he played twice appeared twice on the overlay instead of being consolidated. The opponent deck display from the recorded game is okay, though. I don't remember seeing this in ranked play.

![duplicates](https://cloud.githubusercontent.com/assets/12465335/7663843/79a63cc2-fb72-11e4-918b-194f85b484ff.png)

**Comment by GiggliG** [comment]
I've seen this happen too, but not for a while. It happened for me in play mode, before BRM.

**Comment by culinko** [comment]
This happened to me too, some time ago against an AI. I think I was editing overlay options at the time, but not quite sure what did I change.

**Comment by culinko** [comment]
Pretty sure these cards got milled, because of the boss hero power.

**Comment by Epix37** [comment]
Too lazy to look that up, but pretty sure that's fixed.
