### ISSUE TITLE
Feature: Import deck from screenshot

### ISSUE THREAD

**Issue by rolandschulz** [Epix37/Hearthstone-Deck-Tracker#972]
It would be nice if one could import a deck from a screenshot image.

An implemeantion in Java: https://github.com/HearthStats/HearthStats.net-Uploader/blob/master/companion/src/main/java/net/hearthstats/game/ocr/DeckCardOcr.java 
And there are multiple tesseract (OS OCR library) C# bindings: https://github.com/charlesw/tesseract (newest), http://www.pixel-technology.com/freeware/tessnet2/ , https://code.google.com/p/tesseractdotnet/

**Comment by GiggliG** [comment]
I don't know how easy this is, but it would make things so much easier for importing decks people often share on sites like reddit.

**Comment by jleclanche** [comment]
Rejecting this - OCR / Image recognition is far too hard, unreliable and doesn't work well with localizations AND is a huge maintenance burden as it has to be updated every patch.

Not worth it I'm afraid. Feel free to build a plugin for it, though.

**Comment by rolandschulz** [comment]
A more robust solution than OCR might be to do an image comparison to all known cards. Of course one would still need to do image recognition to find the borders of each card slot. And it would also be hard with localization. Just an idea if someone wants to do the plugin.
