### ISSUE TITLE
issue with opening HDT past version 0.9.0

### ISSUE THREAD

**Issue by engraze** [Epix37/Hearthstone-Deck-Tracker#973]
Every time I try to open hearthstone deck tracker above v0.9.0 it just brings up the loading icon. 
That's it. Nothing opens, no errors are displayed, it just shows me the icon and then it disappears seconds after.

I have: 
Updated net framework to 4.5
Changed security settings to give USER full permission on 'C:\Hearthstone Deck Tracker\' 

There is no log file.
I am on Windows 8.1

**Comment by Epix37** [comment]
Try
a) reinstalling .NET
b) moving the HDT folder to somewhere that does not require premissions (desktop should work)

**Comment by engraze** [comment]
Tried both. Exact same results. v0.9.0 still working.

**Comment by Epix37** [comment]
Hmmm... 

Try renaming/deleting the config.xml in "%AppData%/HearthstoneDeckTracker" and check if the latest version starts.

**Comment by engraze** [comment]
No results. But upon deleting it and opening the executable, it makes a config.xml again with:
*< Config> < /Config>*

Meanwhile, in the %AppData%/HearthstoneDeckTracker there is a log file. All it says is '*[4:13:19 PM]: Another instance of HDT is already running.*' repeatedly. I went to the task manager and there is no process though.

**Comment by Epix37** [comment]
Reboot maybe. No idea what this is honestly.

**Comment by engraze** [comment]
Found a crash report also. And, I did try rebooting a million times already whilst reinstalling .NET framework.

Here's the report: http://pastebin.com/JUm31hQb

**Comment by Thristle** [comment]
you could add the use File.Copy with 3 inputs. the third 1 being a Boolean overwrite input. 
it will overwrite the file but i dont think it's too important to keep those backups
