### ISSUE TITLE
Opponent's deck shows one more secret if stolen and re-stolen by Kezan Mystic

### ISSUE THREAD

**Issue by culinko** [Epix37/Hearthstone-Deck-Tracker#976]
This happened to me today. My opponent stole my Mirror Entity with Kezan Mystic and I stole it back with my own Kezan Mystic. Opponent's deck on overlay (and in "show opp. deck" after the match) was showing 3 Mirror Entities, but my opponent only played 2 (one from the hand and the other from Mad Scientist's deathrattle). Thanks for the possible fix.

**Comment by culinko** [comment]
So the possible solution that came to mind: Mark the stolen secrets green (same as other out-of-deck cards). Same goes if you happen to steal the secret back. This way you will see who played how many secrets from the deck if you ignore all the green ones.

**Comment by Epix37** [comment]
I will have to change a few things to make jousting work properly. This might get fixed in the crossfire. If it doesn't we'll go from there.

**Comment by culinko** [comment]
Great. Yeah, the joust will be a tough one.

Sorry, I'm just browsing through my reported issues and since you happen to have a bit time and you already fixed some of the issues, I'm using this as an opportunity to get more stuff fixed :P

**Comment by Epix37** [comment]
Stolen cards get marked as "created" now, should be fixed.
