### ISSUE TITLE
Hearthstone-Deck-Tracker cause Heartstone to crash when switching between programs

### ISSUE THREAD

**Issue by HisGunship** [Epix37/Hearthstone-Deck-Tracker#978]
When you minimize Hearthstone and reopen it, sometimes it will cause Hearthstone to crash and show "couldn't switch to requested monitor resolution".

**Comment by Epix37** [comment]
And this **only** happens when HDT is running?
Try maybe updating the graphics card drivers.

**Comment by HisGunship** [comment]
Oh, I think that was the problem, thank you!
