### ISSUE TITLE
Hearthstone slowing doing quite significantly when hearthstone deck tracker is open.

### ISSUE THREAD

**Issue by Akejj** [Epix37/Hearthstone-Deck-Tracker#984]
Hey I got the same problem but the aero thing didn't fix it. It has something to do with my other monitor I feel like. I have a 2nd monitor which has native 1920x1080 resolution but is 60hz while my main monitor is 144hz. When I unplug my 2nd monitor hearthstone has max fps but whenever I plug my 2nd monitor in and have hearthstone + hearthstone deck tracker open the fps drops to ~79. Without hearthstone deck tracker the game runs smoothly. The same problem occurs while the game is ran in fullscreen or windowed mode. When in windowed mode the fps drops even more to ~55. Dropping the resolution to 1024x768 in the game and running it in windowed mode I get fairly high fps ~187.
Just asking if there would be any other fix or suggestion. Also this issue has occured just recently, have not had a problem with this earlier. Thanks.

**Comment by Akejj** [comment]
Also this occured recently.

**Comment by Epix37** [comment]
There have not been any changes to the overlay in quite a while, did you maybe change something on your end? Hardware, drivers, etc?

**Comment by Akejj** [comment]
I don't know.. I have no idea what could cause that :/

**Comment by smokeh** [comment]
Has this been looked at yet? I'm having the same issue. I have 3 monitors hooked up, 1 is 144 hz and the other 2 are not. Using the deck tracker, my animations stuttered so much it was unplayable, I had to uninstall (deck tracker). I tried making some updates to the options.txt file, changing max FPS and vsync, but nothing worked except uninstalling. I have yet to try setting my desktop refresh rate back to 60, or unplugging other monitors.

**Comment by MechaLynx** [comment]
I assume you where using v0.10.16? How long has this been happening for?

Also, try using [v0.10.15](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases/tag/v0.10.15) and see if it still happens.

**Comment by Epix37** [comment]
Also see here: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#why-is-my-game-so-choppy--fps-so-low-after-using-hdt

**Comment by FlamingFox911** [comment]
This may help: Try disabling Timer. I found that the timer is what lagged me a fair amount. I disabled it and I ran at full 60 frames again.

**Comment by culinko** [comment]
Is this still an issue ever since the logging changed from log_output.txt to .log files?

**Comment by Epix37** [comment]
Haven't heard anything about it in a long time. Gonna close for now.

**Comment by FlamingFox911** [comment]
I can confirm that the timer issue has ceased and it does seem to be a bit more fluid. Thanks, @Epix37 and crew.
