### ISSUE TITLE
display class

### ISSUE THREAD

**Issue by gendalv** [Epix37/Hearthstone-Deck-Tracker#987]
Can you add an icon of class on the decks themselves? It would be nice to see visually, what class is the selected deck for. Currently the only way to see it is to click on each class filter and observe where the selected deck stays.

**Comment by Epix37** [comment]
The decks are actually colored according to this: http://www.wowwiki.com/Class_colors

Also, the cards should usually give it away.

**Comment by gendalv** [comment]
Epix37, it's only viable for old players, not for new player who don't know all the cards.

**Comment by Epix37** [comment]
Fair point. It should be pretty easy to get used to the class colors though. 

Also, if you have "auto deck selection" under the "tracker" menu point enabled, it will automatically switch to the deck you are currently using in-game (if saved in HDT).
