### ISSUE TITLE
Can`t set game path.

### ISSUE THREAD

**Issue by Ghayaa** [Epix37/Hearthstone-Deck-Tracker#990]
When i start the Tracker it says "Hearthstone install directory not found". Nothing happens when i click "select manually" or when i go and "set hearthstone path" from the settings. Also, i don`t seem to find a "config.xml" file inside the installation directory(i saw that some issues are solved there).

**Comment by Ghayaa** [comment]
Solved it. Found the config.xml file. Looks like instead of "<HearthstoneDirectory> game path </HearthstoneDirectory>", it contained "<HearthstoneDirectory />". Changet it manually. Hope i helped you. Keep up the good work.

**Comment by Epix37** [comment]
\<Node /\> is just short for \<Node\>\</Node\>, meaning it's empty. (You can write \</\> by escaping it like \\\<).

But I assume you just set the correct path in the config and it's working now?

**Comment by Ghayaa** [comment]
Exactly. The buttons in the aplication didn`t work.

**Comment by Epix37** [comment]
Yea, not sure why :(. Works fine on my machine.
