### ISSUE TITLE
Enhancement: Fancy animations

### ISSUE THREAD

**Issue by 21011996** [Epix37/Hearthstone-Deck-Tracker#994]
Trump got similar looking HDT to yours, but with fancy animations. Can you implement at least fade? Colored thingies would be nice.
Not pressuring, just asking.

http://www.youtube.com/watch?v=0Bkg2UPNhYU&ab_channel=Trump

**Comment by Epix37** [comment]
"Trumps HDT" is called post editing :). But yea, I thought about doing this a few times. I would like to eventually add something like that.

**Comment by 21011996** [comment]
@Epix37 Simple cross-fade, or even pre-drawn border witch opacity goes from 0 to 100 and back to 0.
But i think you've got better ideas how to do it:)

**Comment by Cu8eR** [comment]
I like this :) it looks professional :)

**Comment by culinko** [comment]
Some animations are already included in the newest beta :)

**Comment by Epix37** [comment]
Added with v0.14.0
