### ISSUE TITLE
Game Replay does not show minions dealing damage from effects (e.g. Flamewaker)

### ISSUE THREAD

**Issue by JSallee** [Epix37/Hearthstone-Deck-Tracker#995]
When reviewing games it does not show where minion effects dealt damage.  Flamewaker and boombots deathrattle being two that I've noticed.  If it kills a minion you'll see it listed, but not where the damage originated from.  On anything less than a kill you have to infer it from reviewing later turn events and notice the difference in health

**Comment by Epix37** [comment]
See #541
