### ISSUE TITLE
When I end my turn, highlights my next card before my opponent gets their card

### ISSUE THREAD

**Issue by DaRKSLuSHiE** [Epix37/Hearthstone-Deck-Tracker#996]
Hi, love the app.  The only problem I'm having is when I end my turn, the deck tracker highlights my next card IMMEDIATELY before my opponent has even gotten their card.  Knowing what card I'm about to get before my opponent plays their turn is a huge advantage and I've been looking for a way to turn that off.  Is that intended or a bug?  Please help, I really want to use the app but dont want to risk having my account banned

**Comment by Epix37** [comment]
It only happens this extremely in bot games since all the action are immediately done and its just animations playing out.
