### ISSUE TITLE
Bug: some tags can't be deleted

### ISSUE THREAD

**Issue by Elitesparkle** [Epix37/Hearthstone-Deck-Tracker#998]
Since the addition of the new deck picker in version 0.9.0, I don't need to use my custom tags Arena and Constructed anymore.

When I try to delete those tags, they desappear but, if I go there the next day, I see they haven't been deleted.

When I create a new Arena deck, it gets the Arena tag automatically somehow.

**Comment by culinko** [comment]
I can add/remove tags without any problems with both quick set tag and edit tags (if by labels you mean tags).

If you are importing the Arena decks from the game, it won't give any tags to the decks in the next tracker version when you uncheck "tag decks on import". This one got fixed already.

**Comment by Elitesparkle** [comment]
> I can add/remove tags without any problems with both quick set tag and edit tags (if by labels you mean tags).

Yes, I meant tags.
I can remove tags as well, except for those 2 tags. They are bugged somehow.

> If you are importing the Arena decks from the game, it won't give any tags to the decks in the next tracker version when you uncheck "tag decks on import". This one got fixed already.

Okay.
I'm importing the Arena deck from the game.

**Comment by culinko** [comment]
Yeah, the 2nd issue will be fixed in new version (#968).

**Comment by Elitesparkle** [comment]
Some of my Arena decks still have the Arena tag, but I don't have that tag in my list.

I've just used a workaround to fix the problem: add a new tag and remove it.
