### ISSUE TITLE
Suggestion: overwrite old deck versions

### ISSUE THREAD

**Issue by Elitesparkle** [Epix37/Hearthstone-Deck-Tracker#999]
When saving a deck, it could be useful to be able to save it as an older version, without creating a whole new deck or saving it as new (e.g. I have Handlock 1.4 and I want to edit its 1.1 version).

**Comment by culinko** [comment]
Yeah, if you pick any of the previous versions and you want to save it after editing, it lists the 1.4 as 
"current". It should list your version you picked as current with every other version too.

**Comment by Epix37** [comment]
similar to #1010
